### ISSUE TITLE
Update macOS hosted image

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#1014]
On March 23 2020, Azure Pipelines will be removing the following hosted images:

> * Windows Server 2012R2 with Visual Studio 2015, a.k.a `vs2015-win2012r2`
> * macOS X High Sierra 10.13, a.k.a `macOS-10.13`
> * Windows Server Core 1803, a.k.a `win1803`
> 
> https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/

Many of our pipelines are currently using `macOS-10.13`, which will need to be updated.  I recommend moving to the latest `macOS-10.15`.

**Comment by kurtzeborn** [comment]
Moving this straight to "Dev" column since time is tight on this.

**Comment by bsiegel** [comment]
Roadblock: We require Xcode 9.x to build 32-bit versions of `azure-uamqp-python`. Newer versions of Xcode will require us to increase the `MACOSX_DEPLOYMENT_TARGET` which will in turn only allow us to build 64-bit binaries.

**Comment by mikeharder** [comment]
I believe we will need to find a way to build the 32-bit version of `azure-uamqp-python` outside of DevOps hosted agents then.

**Comment by bsiegel** [comment]
@mikeharder the other option is that we can add a step to download/install the older version of Xcode. Unsure if there's an optimized way to do that without having to download the whole multi-GB archive from Apple on every build.

As Adrian points out, we might also be fine just sunsetting support for 32-bit Python on MacOS.

**Comment by chidozieononiwu** [comment]
What was the conclusion for this discussion. 
Is it to sunset support for 32-bit python on MacOs. If so can I go ahead and upgrade the VMImage versions to `macOS-10.15`  [here](https://github.com/Azure/azure-uamqp-python/search?l=YAML&q=macOS-10)

**Comment by mikeharder** [comment]
The conclusion is to sunset 32-bit python.  However, in addition to changing the VMImage, we might also need to disable the 32-bit build to prevent build failures.

@scbedd: Are you the best person to do this, or someone on the Python team?

**Comment by mikeharder** [comment]
I believe the new mac image also uses a different version of xcode, so the pipeline yml might need to be updated as well:

https://github.com/Azure/azure-uamqp-python/blob/50fcb405fbf1620e5128ccebb4b9be98adfceac3/.azure-pipelines/client.yml#L93

**Comment by scbedd** [comment]
Brandon did the original version. I haven't had much to do with it outside of some minor adjustments. Dozie or I would probably be the people to do it yeah. I'm not going to get this to in the extremely near future though.
