### ISSUE TITLE
Write public documentation how to use New-TestResources.ps1

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk#1021]
We need to document how to use New-TestResources.ps1 (though we should move it first; see Azure/azure-sdk-tools#358), including how to create a service principal until we do it ourselves (see Azure/azure-sdk-for-net#9060).

**Comment by kurtzeborn** [comment]
@danieljurek, with the last PR (https://github.com/Azure/azure-sdk-tools/pull/410), all that's left here is updating the contributing.md files to reference the script and it's documentation.
