### ISSUE TITLE
Board Review: Service Bus

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk#1026]
(TBD)

## The Basics

* Service team responsible for the client library:
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview
* Contact email (if service team, provide PM and Dev Lead):

## About this client library

* Name of the client library: servicebus
* Languages for this review: C#, Java, JavaScript, Python
* Link to the service APIs: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-overview

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/b5d7e3304000449c859c2016f718db52
* Link to samples for champion scenarios: https://gist.github.com/JoshLove-msft/5352a6e19aa49a1b99fc8e43b3bf7043

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net). Link:https://apiview.dev/Assemblies/Review/6af850ed7eb04843a6897afbe13cdd28
* Link to gist code [samples](https://gist.github.com/hemanttanwar/d892eb7b3b6cce302262317bc6ae67e6).
More code sample in git [link](https://github.com/hemanttanwar/azure-sdk-for-java/tree/feature/servicebus-track2-queue-client-api-7697-apidesign-another-option/sdk/servicebus/azure-messaging-servicebus/src/test/java/com/azure/messaging/servicebus).

### Python

* Upload the api as a Draft PR.  Link to PR:
* Link to samples for champion scenarios:

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR:
* Link to samples for champion scenarios:

## Champion Scenarios
 **Service Bus Client: Service Bus Receiver/Sender Client Proposal**

The Service Bus client library offers two primary clients for sending and receiving messages, the ServiceBusSenderClient and ServiceBusReceiverClient respectively. Each designed for different operations but unified in their approach to provide a consistent experience for developers. These clients embrace a common design philosophy in providing developers an experience optimized around ease of use, familiar patterns, and a consistent API across them.

Both of the clients are designed to be user-friendly for someone who is new and does not know backend concept of Queue, Topics in details and also to some one who is coming from legacy concept of messaging. 

**Concepts**
**Namespace** :  A namespace is a scoping container for all messaging components. Multiple queues and topics can reside within a single namespace, and namespaces often serve as application containers.
**Topics** : You can also use topics to send messages. While a queue is often used for point-to-point communication, topics are useful in publish/subscribe scenarios. Enable an application to announce events to multiple interested consumers asynchronously.
https://docs.microsoft.com/en-us/azure/architecture/patterns/publisher-subscriber

![image](https://user-images.githubusercontent.com/5825640/75057674-68e2ba80-548e-11ea-8b5c-d8a7edd7a6e3.png)

**Subscriptions** : A subscriber to a topic can receive a copy of each message sent to that topic. Subscriptions are named entities.

**Queue** : Messages are sent to and received from queues. Queues store messages until the receiving application is available to receive and process them.

Enable multiple concurrent consumers to process messages received on the same messaging channel. This enables a system to process multiple messages concurrently to optimize throughput, to improve scalability and availability, and to balance the workload
https://docs.microsoft.com/en-us/azure/architecture/patterns/competing-consumers

![image](https://user-images.githubusercontent.com/5825640/75057450-e1954700-548d-11ea-8dc4-0fc3e72fe14d.png)

**Things to know before reading**
	• Some details not related to the high-level concept are not illustrated; the scope of this is limited to the high level shape and paradigms for the feature area.

**Target segment: Regular , Middleware , DIY (Do it yourself)  Developers**

**Regular Developers**: Most of the developers write to Queue/Topic and read from Queue/Subscriptions. Their use case is simple but used a lot in production. For example Read one message, process it and  go to next message.
**Middleware Developers** : These SDK writers who wrap Queue/ Topic in middle which are agnostic of server  side concept or vendor agnostic. Their point of  view is "send" or "receive".
**DIY Developers**: These are advance users who want to do everything on their own. For example message handling, exception handling, managing transactions etc.

**Champion Scenarios**
**Scenarios 1 : Sender can send messages**

A Real world existing application:  
https://www.cloudamqp.com/blog/2017-09-25-breaking-down-a-monolithic-system-into-microservices.html
https://www.parkster.com/se/parking-with-parkster/

Parkster is company which provide solution for managing parking lots, payments, billing to large number of parking lots all over the world. Parkster started out with a monolithic architecture. They wanted to have their business model proven before they went further, so they started with one application which became monolithic . A monolithic application is where the whole application is built as a single unit. All code for a system is in a single codebase that is compiled together and produces a single system. 
The biggest reason we moved from monolith to microservice were decoupling. Parkster’s move from a monolith architecture to a  15-20 microservice architecture. These multiple microservices communicating via message queues.

Once a parking spot is reserved by customer, One ReservationService will send a message to "ParkingLotManagerService" microservice using a queue.
![image](https://user-images.githubusercontent.com/5825640/74887266-52721d00-532f-11ea-8970-256e126d580a.png)

  ReservationService    ------>  ParkingLotManagementService

**Message** : (Spot 15) is reserved for 4 hours starting at 2 PM PST.

- ReservationService has a guaranteed delivery to the queue.

- Message sequence is not  guaranteed unless queue is session enabled and client specify that.

- The ParkingLotManagerService does not have to be online. 

**Exception case**: 
What if the receiver hangs/takes JUST long enough to not be able to renew before lock has expired and is claimed by another consumer? : Since the receiver did not renew lock before it expired, this message will be placed in queue and next customer can receive it.

**Scenarios 2 : Receiver can receive messages**

The ParkingLotManagerService should be able to receive messages asynchronously. The ParkingLotManagerService will receive one message at a time and update its system with start and end time for parking. It will also start a background timer which will inform other services when parking time slot expire.

- There could be one or more competing consumers.
- Receiver could manage message in queue i.e. complete, defer, abandon, and dead-letter
- Receiver could  Renew locks on messages and sessions in queues.
- Receiver could peek-lock a message.
- The receiver can indicate message processing is complete.

**Message Locking**: While this message is being processed , no other thread/process can process this same message. 
**Receive And Delete**:  Sometime a receiver do not want to lock the message, It will receive a message and service delete this message from Queue.
 
Example :If we have "**AverageCustomerPerDayService**" which count how many customer uses parking lot on average everyday. It will increase count by one for each message and if it fails to do for few messages it wouldn't cause company a fortune.  

**Exception Cases**

- If receiver takes longer time to process, the lock will be released and which makes this message available .

- What if receiver crashes before if complete the message, this message will be made available to other receiver for processing?

**Scenarios 3 : Middleware can Send and Receive messages agnostic of Topic/Queue**

Some companies build middleware products where user does not care about service concept of Queue and Topics. And user just care about sending to or receiving from "Messaging System" without knowing how it is implemented.
 
Scenario 1 and 2 list all features needed for this scenario. 

**Scenarios 4 : Publisher can publish message to a topic** 

- A publisher can send/publish a message to topic which can be consumed by one or more subscribers.

For Example  "Order service" publishes an order. 
	"Order # 101,Category=Book, Name:Programming Server Side  by Jeffery Richter, Number of books = 2, Price = $100.00"

**Topic Name** = "ORDER_TOPIC"

- When the message is sent to topic it is guaranteed delivery. 
- The subscribers does not have to be online.
- The sender does not know how many subscribers are there.

![image](https://user-images.githubusercontent.com/5825640/74887533-02e02100-5330-11ea-9bec-9721088499fd.png)

**Scenarios 5: Subscriber can subscribe to a topic**

**Topic Name** = "ORDER_TOPIC"
Subscriber 1 Name = "User_Service Subscriber"
Subscriber 2 Name = "Price Service Subscriber"
Subscriber 3 Name = "Delivery Service Subscriber"
Subscriber 4 Name = "HeavyProduct Delivery Service Subscriber"

- There could be more than one subscriber. 
- Each subscriber gets their own copy of message.

- A filter could be applied on a message. For example 
	Subscriber 4 Name = "HeavyProduct Delivery Service SUBSCRIBER" Filter Rule = "Category == Appliance"
	
Above order will be received by first three subscriber but not by Subscriber 4 because it does not satisfy filter rule.
**Other common uses cases for filter** 
Security : In some cases, we can restrict a subscriber to see one specific type of message.
Debugging : Some MS groups uses filter 1=1, to receive all the messages and determine why other subscriber are not receiving messages.

**Scenarios 6 : Receiver can receive messages in sequence**

A Real world existing application:  
https://www.cloudamqp.com/blog/2017-09-25-breaking-down-a-monolithic-system-into-microservices.html
https://www.parkster.com/se/parking-with-parkster/

Once a parking spot is reserved by customer,  ReservationService will send a message to ParkingLotManagerService using a queue. The customer changes mind with in few minutes and decide to cancel the reservation. 

This scenario need FIFO which is only guaranteed when using **sessions**, since otherwise things would get messed up if we get the cancel message before the reserve message.

Lets say following is message sequence executed by consumer.

**Message 1** : Spot 15 is reserved for 4 hours starting at 2 PM  , Session ID ="SPOT-15"
**Message 2** : Spot 15 reservation for 2 PM is cancelled, Session ID ="SPOT-15"

The ParkingLotManagerService will receive these message in sequence for Session ID ="SPOT-15". 

**Scenarios 7 : Receiver can receive messages in sequence for next available scenario**

A Real world existing application:
https://www.cloudamqp.com/blog/2017-09-25-breaking-down-a-monolithic-system-into-microservices.html
https://www.parkster.com/se/parking-with-parkster/
Once a parking spot is reserved by customer, ReservationService will send a message to ParkingLotManagerService using a queue. There are multiple messages for different parking spots.

Lets say following is message sequence executed by consumer.

Message 1 : Spot 10 is reserved for 4 hours starting at 2 PM , Session ID ="SPOT-10"
Message 3 : Spot 15 reservation for 2 PM is cancelled, Session ID ="SPOT-15"
Message 2 : Spot 10 is extended for 2 more hours , Session ID ="SPOT-10"
Message 4 : Spot 15 reservation is cancelled , Session ID ="SPOT-15"

The ParkingLotManagerService request for "any" available session for processing 
Service will pick next available session, for example Session ID ="SPOT-15". 

**Scenarios 8: Management Scenario**
	There are more operation which are management in nature.
	Create Queue , Topic and Subscription
	Add / Remove Rule/Filter 
       Note : No API are discussed for management scenario here but we noted them here as reference for completeness.

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by adrianhall** [comment]
Architecture Board:

.NET for Service Bus:
- What is the default value of `ProcessingOptions.AutoComplete` - it's true (JS is using false in T1)
    - We should be consistent
- Don't like the `ProcessingOptions.MaxConcurrentCalls` name - reconsider name
    - There are APIs in .NET BCL that have the same concept - use similar name
- `DeadLetterAsync` - maybe `MoveToDeadLetterAsync`?  Come up with a new name.
- `ProcessMessageAsync` - can we move the param into a struct?  It's more extensible.
    - JS has a context with the deadLetter method on it (etc.) - might be worth exploring
- There are concerns around state changes (dead letter is called on the client, abandon is an exception, and otherwise, completion is implicit) - it's hard to rationalize.
- Error handling flow seems to be really confusing - make easier.
- Where is the autoLockRenewal configured?  It's configured when you start processing.
- Concerns around the error handler - what errors do I need to deal with?  Should we be doing more?
    - Guarantee from SB is "at least once"  - this feels like more work on the client / developer
    - Need to consider event completion correlation.
- Why is `ReceiveBatchAsync` returning a `Task<IEnumerable>` vs. `Task<List>` or `Task<Array>`
    - Would be better to return task-of-array, since it's better performance (allocation issue), but a List<T> would be ok too.
- Should we put the primitives in so that you can do the auto-lock stuff even in the lower level API?
    - Event based API makes things easier, but we need low level APIs.
- Why is the GetSessionIdAsync() async?  When you create the client, you don't have the session ID.  The rest of the time, it's available.
    - Open to changing it.
- Lots of these concepts appear in Event Hubs.  Are we aligning?  (Yes)
- Java and .NET need to reconcile specific differences around the clients.

Line by line .NET
- Remove `RenewLockAsync()`
- Potentially use factory methods for complex constructors on `ServiceBusReceiverClient`
- Can we unify between ServiceBus and EventHubs for `CustomRetryPolicy`?
    - If the customer learns how to use retries in EH, it should look the same in SB
    - Why have `CustomRetryPolicy` AND the regular retry options?  JeffreyRichter design
- `ExceptionReceivedContext` and `ExceptionReceivedEventArgs` should be flattened
- Consider converting `ExceptionReceivedEventArgsAction` to an enum
- `ServiceBusConnection` ctor - think about factory methods as above.
- Consider rename `UserProperties` => `Properties` to align with Event Hubs
- Convert `DateTime` to `DateTimeOffset` and remove the `Utc` suffix.
- `Peek` naming is awkward.  Was peek in T1.  Service uses "Browse".  Think about methods of hiding it.
- Collapse `ServiceBusException` ctors.
- Filters need to be redesigned - do they actually help?  What are the common use cases.
- Introduce MessageBatch for batch sending (with a TryAdd pattern)

Java notes:
- Need more complete examples to see what the error handling / processing looks like
- Rationalize the clients with .NET - should be consistent unless there is a good reason not to
- Either keep ReceiveMessageOptions and put it on receive as well, or explode it and keep it on the client builder.  Do the same on other languages.
- Come up with a better name than anySessionId() - python uses nextSessionId (talk to other languages)
- Hide lockToken from user - ref JS/.NET for details.
- Remove ServiceBusResourceType from public API
- For sync receiver, we need the number of messages to receive, time to wait, etc.

-
