### ISSUE TITLE
Board Review: Data Lake GA

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk#1038]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library:
* Link to documentation describing the service:
* Contact email (if service team, provide PM and Dev Lead):

## About this client library

* Name of the client library:
* Languages for this review:
* Link to the service REST APIs:

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/548418d761fb45ce9fc98c8cfa9f5ef8/3216a5e9778344369ec26224161c30c1
* Link to samples for champion scenarios:

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/3144ca86242147b9bbce634cf534ce1e?diffRevisionId=2366027b741b4b3ab5deb4dcaaa939f1
* Link to samples for champion scenarios:

### Python

* Upload the api as a Draft PR.  [Link to PR](https://github.com/Azure/azure-sdk-for-python/pull/9987/commits/f79a84d8a7bd72d308a4a5e9e3531061ceaabdae) (The API diff against last API review)
* Link to samples for champion scenarios:

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR: https://github.com/Azure/azure-sdk-for-js/pull/6321, https://github.com/Azure/azure-sdk-for-js/pull/7659
* Link to samples for champion scenarios:

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Describe the champion scenario
    * Estimate the percentage of developers using the service who would use the champion scenario
    * Link to the code sample

_ Repeat for each champion scenario _

Examples of good scenarios are technology agnostic (i.e. the customer can do the same thing in multiple ways), and are expected to be used by > 20% of users:

* Upload a file
* Update firmware on the device
* Recognize faces in an uploaded image

Examples of bad scenarios:
* Create a client (it's part of a scenario, and we'll see it often enough in true champion scenarios)
* Send a batch of events (again, part of the scenario)
* Create a page blob (it's not used by enough of the user base)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by JonathanGiles** [comment]
Can I confirm whether or not the datalake API for Java is also part of this review (I see it linked, but I note the title specifically calls out .NET).

**Comment by tg-msft** [comment]
Yes @JonathanGiles - this is to get GA approval for all languages.

**Comment by KrzysztofCwalina** [comment]
.NET APIs look good. Thanks!

**Comment by JonathanGiles** [comment]
The Java apiview is missing responses to a few issues raised. Can these be reviewed and considered? Thanks

**Comment by gapra-msft** [comment]
Hi @JonathanGiles I think I just missed responding to a few when I was responding to them all. They should all be updated now.

**Comment by bterlson** [comment]
JS/TS APIs are good to go.

**Comment by JonathanGiles** [comment]
Can we get an updated revision for the Java APIs up into APIView, now that the changes have all been made? Thanks

**Comment by JonathanGiles** [comment]
Also, for Java, has anyone reviewed the generated JavaDoc? I just went to build it and noticed that datalake is not integrated into the code snippets configuration, and was failing to generate JavaDoc. I've included datalake in the JavaDoc generation as part of this PR: https://github.com/Azure/azure-sdk-for-java/pull/8858

**Comment by gapra-msft** [comment]
@JonathanGiles I just added an updated version of the Java APIs (whatever is currently on master now) . Please let me know in case there's something I missed.

**Comment by amishra-dev** [comment]
@gapra-msft @JonathanGiles Just putting here what I have discussed with both of you offline. All outstanding issues are resolved and Jonathan will take a final look and signoff today.

**Comment by JonathanGiles** [comment]
One minor typo in the Java API to be resolved, then it looks good to me. The point I made regarding reviewing your JavaDoc is relevant also - please do a pass over them to ensure they are rendered as you expected, as no one has reviewed the actual rendered output. I have merged a PR for you that fixes the fact Data Lake was never added to the docs output to include code snippets.

**Comment by gapra-msft** [comment]
Thanks @JonathanGiles, I totally missed the casing issue when I was refactoring the method names.

I'll go through the javadoc once I get this last change in.

**Comment by gapra-msft** [comment]
@JonathanGiles just updated APIView for Java with the fixed typo.

**Comment by amishra-dev** [comment]
@JonathanGiles are we good for Java?
@johanste the PR with your suggested changes have merged, can we assume your signoff?

**Comment by JonathanGiles** [comment]
Java is good to go.

**Comment by annatisch** [comment]
Python is good to go pending the merge of the last PRs:
https://github.com/Azure/azure-sdk-for-python/pull/10170
https://github.com/Azure/azure-sdk-for-python/pull/10208
