### ISSUE TITLE
Board Review: Azure.Storage.Blobs new SAS generation API

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk#1040]
## The Basics

* Service team responsible for the client library: Storage
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview
* Contact email (if service team, provide PM and Dev Lead): amishra, jaschrep

## About this client library

* Name of the client library: Azure.Storage.Blobs (pattern matched to Common, Files.Shares, Files.DataLake, Queues
* Languages for this review: C#
* Link to the service REST APIs: N/A. Client-only feature.

### .NET

* Upload DLL to [apiview](https://apiview.dev/Assemblies/Review/7a03b7db2e29407d905e5f796ef95a57?diffRevisionId=dfd13489651643d79482aa93ba1acc4e).  Link: NOTE that a multi-feature review was scheduled, so these packages will contain changes not related to this specific feature.
    * [Common. Rev6 against Rev5.](https://apiview.dev/Assemblies/Review/b48340c11dab4e88b3b2bd269bc03661?diffRevisionId=aed36a5529a144f09e0881ea731e7ffb) Anything with the name "Sas" in it.
    * [Blobs.](https://apiview.dev/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660?diffRevisionId=556861fd56ac4d1d9ccdbb3c511a2c98) Rev10 against Rev9. Anything with the name "Sas" in it.
* Link to samples for champion scenarios: 
```csharp
public Uri Sample(BlobClient client, BlobSasPermissions permissions, DateTimeOffset sasExpiration)
{
    var settings = new BlobSasSignatureValues(permissions, sasExpiration) // apply mandatory settings; different combinations of mandatory settings have different constructors
    {
        // apply optional settings
    };
    string queryString = client.GenerateSas(settings);
    return AppendQuery(client.Uri, queryString) // method that appends uri syntactically correctly (joining with "?" or "&" as needed)
}
```

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario:
    * Create on-the-fly, limited time access to a storage resource with explicitly granted permissions.
    * Most high-profile customers use this feature.
    * Sample inline above.

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by adrianhall** [comment]
From @jaschrep-msft initial email:

This is the link with a before/after diff of new APIs added to Azure.Storage.Blobs to give customers a new SAS generation interface, following Java’s refactor.
 
Additions (since there’s a lot of text on that page):
* `BlobServiceClient`, `BlobContainerClient`, `BlobBaseClient` got new methods
* New class `BlobSasSignatureValues`
 
Things of note:
* The overall design of a constructed SAS values object to be passed into a generate method on the client was designed and approved for Java. This is a port of that design.
* The diff references an invisible `AccountSasSignatureValues` class. This class exists in Azure.Storage.Common, and so is unable to be included in the API review by this tool. It follows the exact same patterns as `BlobSasSignatureValues`, just exposing the options for account SAS instead.
* There will be similar changes for Files, Queues, and DataLake, so any patterns we agree on here will be ported across those packages as well.
* New class names were taken from Java’s implementation, property names have been taken from .NET’s `BlobSasBuilder`.
* This API set is a full replacement of everything else publicly exposed to do with SAS generation. The plan with the introduction of these new APIs is to set `EditorBrowsable=false` on all the old SAS construction classes. Existing flags enums are maintained.

**Comment by JeffreyRichter** [comment]
How do the SAS permissions get signed? This requires that the client use a shared key credential or you use a user delegation key. If the client doesn't have either of these, how is the SAS token generated?

**Comment by jaschrep-msft** [comment]
@JeffreyRichter the client method uses the shared key stored in the client to sign the SAS with. SAS tokens that have the option of being a user delegation SAS have an overload of the method that also takes a user delegation key.

**Comment by JeffreyRichter** [comment]
What is the BlobClient doesn't have a shared key or the ability to get a delegation SAS. For example, what if the BlobClient itself is a SAS url?

**Comment by jaschrep-msft** [comment]
@JeffreyRichter then the method will throw. This is in line with the Java library's behavior that this change is modeled after.

**Comment by JeffreyRichter** [comment]
I'm not a fan of this design then (in any language). To build a SAS token, what's needed is the resource, the other SAS values (like permissions, expiration, IP range, etc.) and the shared key or the delegation. Putting a method on a BlobClient object doesn't guarantee that you/the customer has everything you need. In addition, creating a SAS is a security-related operation and code that is creating one of these should really be explicitly doing it. This is why I never had functions to create SAS tokens on client objects. Also, you don't need a XxxClient object first to get the resource information. 

I think what you really want is the way to grab the resource information ONLY from an Account/Blob/ContainerClient. So, you could offer a function on a XxxClient that takes a SASValues structure (I can't remember the exact name off the top of my head); the function would just fill in the resource-specific fields and leave the other SAS value fields as is. And then, with a fully-populated SASValues structure, sign it to get the token exactly the same way that the old SDK did.

**Comment by jaschrep-msft** [comment]
I'd like to ensure I understand what you're proposing and reveal some finer-grain motivational details. There are specific things we want to make easier for the user beyond just the method being on the client and pulling the key.
- A clarifying and enforced way to set the mutually exclusive SAS options of stored access policy ID vs permissions and expiry time.
- Locking down the signed version, which is currently freely settable and will create an invalid SAS if the user tries to alter it from the default.
- Unifying how to set permissions with how to set the rest of the SAS fields (currently a method on the side compared to everything else being a property.
- Remove the unnecessary user complexity of the middle man `BlobSasQueryParameters`. Currently a user must go from the confusing builder to a parameters object and then call `ToString()` to get the actual SAS token. Parameters provides little user value unless they want to parse an already existing SAS.

Many of these changes would be strictly breaking, and so providing new classes for SAS construction is necessary to fulfill these designs, so we are already in the realm of a completely new implementation rather than providing utilities for the existing ones. If this affects your proposed design of putting a utility method on the client, please let us know.

My interpretation of your proposal, under the assumption of new model classes remaining part of the approach, is that you are *only* tweaking the actual method on the clients to fill in the resource data and hand the model back (this remaining the *only* way to set the resource details). The model class would then have something along the lines of `public string GenerateSas(StorageSharedKeyCredential credential)` and its user delegation key equivalent. A code snippet of this interpretation would play out as follows:
```csharp
BlobClient blobClient; // you already have your client
StorageSharedKeyCredential credential; // you already have your credential

var perms = BlobSasPermissions.Read; // previously existing enum
var expiry = DateTimeOffset.Now.AddDays(1);
var sasValues = new BlobSasSignatureValues(perms, expiry) // new class
{
    StartsOn = DateTimeOffset.Now.AddHours(1)
};

string sas = blobClient
    .PopulateSasValues(sasValues) // your suggested variation on new BlobBaseClient method
    .GenerateSas(credential); // your suggested method on BlobSasSignatureValues
```
Only the last line of this snippet would be different from storage team's initial suggestion; our snippet would have the second-to-last line return the string directly as they already had the credential. Or would your final statement look like this?
```csharp
string sas = blobClient
    .GenerateSas(sasValues, credential); // storage team's initial proposal, but the credential is an explicit argument
```

**Comment by XiaoningLiu** [comment]
Have similiar questions:

1. For JS SDK, client object doesn't know explict type of the credential it holds. Or even if pipeline is fully customzied and provided by customer, there is no known credentials.

Considering this, accept a explict credential parameter in genereateSas sounds more reasonable. 

2. In current design, `generateSAS` may generate a blob service level SAS, or a delegatation SAS. (Correct me if I'm wrong). How does customer know the type of SAS they get?

These 2 types of SAS are different, such as delegation SAS has much short expiry time period within 7 days.

3. Account SAS generation seems not in the scope of this proposal?

**Comment by jaschrep-msft** [comment]
@XiaoningLiu 
1. That's good to know. In .NET and Java, it's pretty difficult to get credentials into your first client without explicitly providing it as an argument, at which point it's easy for clients to save them and pass them around internal constructors.
2. Two part response
   - The customer knows what kind of SAS they are getting based on the client they generate it from.
     - BlobServiceClient makes an accountSAS (optionally scoped to blob service depending on SAS options)
     - BlobContainerClient makes a container SAS
     - BaseBlobClient and its children make a blob SAS. If the blob client targets a specific snapshot, it will be a blob snapshot SAS.
   - `GenerateSas()` will have two overloads in all applicable cases. One will accept a shared key and one will accept a user delegation key. Expiry time is set the same way through each overload; the fact that user delegation keys have max time restrictions is unavoidable, and we can throw on generation if they try to set an expiry after the user delegation key expiry.
3. I'm not sure what you mean by account SAS generation being out of scope. You mentioned a SAS scoped to the blob service level. Is that not an account SAS scoped to the blob service? Please correct me if I'm wrong, but as far as the data plane is concerned there are two SAS types):
   1. Account SAS, which can be optionally scoped to a specific service like blobs. Can only be signed with an account shared key.
   2. Service SAS, which can be scoped to a container, blob, or blob snapshot. Can be signed with either an account shared key or a user delegation key.

**Comment by jaschrep-msft** [comment]
@JeffreyRichter can you confirm whether or not we are on the same page?

**Comment by JeffreyRichter** [comment]
I'm OK with this proposal: 
   string sas = blobClient.GenerateSas(sasValues, credential);

**Comment by bterlson** [comment]
Me too!

**Comment by jaschrep-msft** [comment]
@KrzysztofCwalina does this design have your sign-off?

**Comment by KrzysztofCwalina** [comment]
I have several questions and concerns about the feature. I would prefer to talk about it at the arch review.

**Comment by kyle-patterson** [comment]
Scheduled for 3/25.

**Comment by kyle-patterson** [comment]
Link to recording: (MSFT INTERNAL): https://msit.microsoftstream.com/video/d12aa4ff-0400-86e7-2cb7-f1ea72dada72

Q: ComputeSasSignature is protected static, why is that? 
- API intended for users is on the clients, not on the sharedkeycredential. The key is used to sign the message, and should not be shared with the remainder of the code. AccountKey can be accessed within the base class, but there is an internal type that can call this static method. Referring to a previous conversation on storage batching, this is an existing pattern that would not be exposed to users.


This api change deprecates the AccountSasBuilder:

- Issues with the builder (why is it being deprecated?): Customers are reporting that it was very heavy-handed to create a client with Sas. Java did a similar move, shrinking 5 calls to 1; trying to replicate that here. However, there may be many more issues with deprecating this, especially for users already on the codebase that weren't facing issues.

**ACTION**: @tg-msft to review deprecation case for AccountSasBuilder

**RECOMMENDATION**: Do not remove the old one unless we see stronger customer feedback, but consider marking it obsolete to warn future users.

**RECOMMENDATION**: Review the need to create a full BlobClient, which forces higher memory/dev usage in the new libraries
