### ISSUE TITLE
Burner feed publishing is failing sometimes

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#1048]
For example see [build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=273265&view=logs&j=69a3c8ee-8902-50a5-9068-fb7d318ff9fc&t=051a6b77-d83b-5583-cb8f-a103918c47f5). This happened a few other times in the last month but I cannot find the other builds now.

```
The nuget command failed with exit code(1) and error(System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden - User 'd4915092-6049-4d25-9e81-7a43c45ca368' lacks permission to complete this action. You need to have 'AddPackage'. (DevOps Activity ID: C30DA526-5859-47F8-A21B-E1A119A3F376)).) ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden - User 'd4915092-6049-4d25-9e81-7a43c45ca368' lacks permission to complete this action. You need to have 'AddPackage'. (DevOps Activity ID: C30DA526-5859-47F8-A21B-E1A119A3F376)).
```

I suspect either the burner feed creation is not completing in time or is failing to setup the permissions correctly for us to be able to publish.

Aside from the issue, which we should try to fix, we should reconsider if we even want to publish to a burner feed for our nightly builds as they immediately get cleaned up anyway so no one is even using them.

**Comment by mitchdenny** [comment]
I've followed up with the Artifacts team to see if they know what is going on here. I had a quick browse through the code for the service and permissions appear to get applied synchronously to the feed when it is created so if setting permissions was going to fail I would expect it to fail when creating the feed, not publishing the package.

**Comment by pakrym** [comment]
Same today https://dev.azure.com/azure-sdk/internal/_build/results?buildId=274528&view=results

**Comment by mitchdenny** [comment]
Thanks for letting me know. I reached out to the Artifacts team and they let us know that the application of permissions isn't synchronous with creation of the feed. So there is a chance for a bit of a race condition here.

The most reliable thing to do here is to add retries to package publishing, unfortunately tasks within an Azure Pipeline are retryable (only at the job level). As a quick fix I think we'll put a short time delay in which should solve the problem for us, but longer term we'll need to do one of two things:

1. Make the job retryable (will still fail, but you just retry the job).
2. Swap from using the NuGetCommand task to invoking NuGet directly (preferred).

**Comment by mitchdenny** [comment]
I've deployed a quick fix to this (added a 15 second delay after burner feed creation). I'm going to keep this issue open because that is just temporary. If it proves to work then we'll need to move to a retry model if possible rather than just a dumb delay ... but 15 seconds should be enough given that this appears to be transient.

**Comment by mitchdenny** [comment]
Removed this stage completely.
