### ISSUE TITLE
Change Request: Remove Sovereign Cloud info until design is finalized

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#1049]
The sovereign cloud design isn't finalized, but it is published https://azure.github.io/azure-sdk/general_design.html#sovereign-clouds-and-default-endpoints

I recommend removing it until the design is fully fleshed out.

Solution: roll back this commit, finalize design, then repub when ready

https://github.com/Azure/azure-sdk/commit/6e497b1f19a70b39a101c04dbef6744a9a6c4f50

**Comment by adrianhall** [comment]
PR #1050 approved and merged.

**Comment by jongio** [comment]
Thank you.
