### ISSUE TITLE
Support KnownAuthorities across all languages

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#1054]
Right now, when a user wants to work with an alternate cloud they have to specify the authority host in code.

Python has implemented a KnownAuthorties object that allows a user to reference the known other cloud authorities via a const like this: 

`credential = DefaultAzureCredential(authority=KnownAuthorities.AZURE_GOVERNMENT)`

All of the other languages require the user to specify the full url to the known authority, like this:

`new EnvironmentCredentialBuilder().authorityHost("https://login.microsoftonline.us/").build()`

Ideally, we are consistent across all langs for this.

I have filed issues for the other 4 langs:

JS: https://github.com/Azure/azure-sdk-for-js/issues/7597
.NET: https://github.com/Azure/azure-sdk-for-net/issues/10228
Java: https://github.com/Azure/azure-sdk-for-java/issues/8627
Go: https://github.com/Azure/azure-sdk-for-go/issues/7745

**Comment by jongio** [comment]
Related: https://github.com/Azure/azure-sdk-for-java/issues/8626 - [FEATURE REQ] Support setAuthorityHost with CredentialBuilderBase #8626

**Comment by adrianhall** [comment]
Sounds like we should put this in the general guidelines as well, so that future implementors of a new language will take it into consideration.  I suspect this belongs in the "azurecore.md" file.  Want to take a swag at a PR for this, @jongio?

**Comment by jongio** [comment]
Will do.

**Comment by jongio** [comment]
This is now supported in all langs. Thanks team!
