### ISSUE TITLE
[FEATURE REQ] Increase retention for Publish Builds

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk#1059]
Pipeline runs that result in a successful publish of a package should be retained for 6 months before being cleaned up.

**Comment by weshaggard** [comment]
I believe @mitchdenny  was also looking to see if we can set a longer time then 60 days at the individual pipeline level. @mitchdenny is this something you are looking into or did you want @chidozieononiwu to pick that up?

**Comment by mitchdenny** [comment]
Yes. I'm working on a script that makes a REST API call. We would call this script after a package is released.
