### ISSUE TITLE
Standard way to share code/scripts between release pipelines

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#106]
Because we can't currently check in YML files for our release pipelines we should ensure that code written in the release pipelines is shared as much as possible and checked into a common repo.

The goal of this issue to move all code from our release pipelines into this repo: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-build-tools

This will allow for better sharing and source control until AzureDevOps catches up and we can check in our YML files.

**Comment by weshaggard** [comment]
For all our existing release pipelines I've already moved as much of the script files and tools as we can into the azure-sdk-build-tools repo.  I will add this to our pipeline guidelines so we can try to stay clean when we add additional release pipelines but for now I'm closing as there isn't anything to do.
