### ISSUE TITLE
Board Review: Support New Environment Variable AZURE_AUTHORITY_HOST

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#1060]
## Proposal
This is a proposal to add AZURE_AUTHORITY_HOST environment variable and honor it before calling functionality that depends on it, i.e. TokenCredentialOptions.

## Background
When accessing Gov, German, China, or other cloud, developers must set the appropriate authority host for the target cloud: Developers that need to set the authority host will want to have flexibility in how they manage that setting via configuration.  It would be nice if the SDKs supported setting this property via an environment variable - because that is what these customers will do any way.

This will also make the code more portable so that users can configure this setting via CI variables when testing against various environments.

The current public endpoints are as follows:

|Name               |AuthorityHost|
|--|--|
|AzureCloud |        https://login.microsoftonline.com
|AzureChinaCloud|   https://login.chinacloudapi.cn
|AzureUSGovernment|  https://login.microsoftonline.us
|AzureGermanCloud|   https://login.microsoftonline.de

```bash
az cloud list --query '[].{Name:name, AuthorityHost:endpoints.activeDirectory}' -o table
```
> Note that there will be more in the future some that will not be documented and some that will come from customers own Identity system deployments.

## Implementation
When instantiating a credential object, such as `DefaultAzureCredential` a developer is required to set the authority host via the IdentityOptions object and the DefaultAzureCredential constructor. 

For example, here's how each of the languages set this value:

### Python
```python
credential = DefaultAzureCredential(authority=KnownAuthorities.AZURE_GOVERNMENT)
```
### TypeScript
```js
const credential = new DefaultAzureCredential({ authorityHost: "https://login.microsoftonline.us" });
```

### C#
```csharp
var options = new DefaultAzureCredentialOptions { AuthorityHost = new Uri("https://login.microsoftonline.us/") };
var client = new KeyClient(new Uri(keyVaultUrl), new DefaultAzureCredential(options));
```

### Java

Java Option # 1 (Version 1.1.0-beta.2 +)
```java
// Version 1.1.0-beta.2 or greater
DefaultAzureCredential cred = new DefaultAzureCredentialBuilder()
  .authorityHost("https://login.microsoftonline.us/").build();

KeyClient keyClient = new KeyClientBuilder().vaultUrl(dotenv.get("AZURE_KEYVAULT_URL")).credential(cred)
  .buildClient();
```
Not supported in DAC today.  Issue filed here: https://github.com/Azure/azure-sdk-for-java/issues/8626

Java Option # 2 - Don't use Env Var
```java
new EnvironmentCredentialBuilder().authorityHost("https://login.microsoftonline.us/").build()
```

Java Option # 3 - Use reflection

```java
IdentityClientOptions options = new IdentityClientOptions().setAuthorityHost("https://login.microsoftonline.us/");
DefaultAzureCredentialBuilder cred = new DefaultAzureCredentialBuilder();
Field identityClientOptions = cred.getClass().getSuperclass().getDeclaredField("identityClientOptions");
identityClientOptions.setAccessible(true);
identityClientOptions.set(cred, options);

KeyClient keyClient = new KeyClientBuilder().vaultUrl(dotenv.get("AZURE_KEYVAULT_URL"))
                .credential(cred.build()).buildClient();
```

## Post-Implementation

After this is implemented, all of the above code can be simplified to just `new DefaultAzureCredential()` and set the authority host via the AZURE_AUTHORITY_HOST env var.

## Action
- Create a new Env var named AZURE_AUTHORITY_HOST and honor that value when constructing a TokenCredentialOptions object.

Order of precedence:
1. User set value in code
2. Environment variable
3. Default value https://login.microsoftonline.com

Related: 
- This setting will also be needed with the upcoming 'dynamic' load of cloud configuration data that is currently being prototyped. #663

**Comment by adrianhall** [comment]
Shouldn't we wait on this until after the sovereign cloud design work?

**Comment by jongio** [comment]
@adrianhall - It is related to sovereign cloud, but each new environment variable needs to go through board review, so filing a new request.
