### ISSUE TITLE
Board Review: Bonzai Service

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-sdk#1098]
Placeholder for the Bonzai review.

**Comment by kinshuman** [comment]
Share point link - https://microsoft.sharepoint.com/:f:/t/ProjectSocratesAI/Ej9h9QxjbkdMiKMfXTvpuT0Bar1Oqpw54OciPdvocpfFeQ?e=jiblSO

API Documentation - 
https://microsoft.sharepoint.com/:t:/t/ProjectSocratesAI/ETP5Ek_yV6xJoaHUStVOVo0Bo0rvkfdaMjbX9P__T4yUOQ?e=QuuU7i

**Comment by kyle-patterson** [comment]
Link to recording (MSFT INTERNAL): https://msit.microsoftstream.com/video/d747a1ff-0400-aa75-0f73-f1ea67d1ef44

Link to overview and scenarios (MSFT INTERNAL): https://microsoft.sharepoint.com/:w:/t/ProjectSocratesAI/EeKXJnJ8VpVDq8arrx2waIwBQICjPdNSSRU6VCEkvf609A?e=EDvJK0

**ACTION** Feature team to upload a language API to apiview using the instructions here: https://azure.github.io/azure-sdk/policies_reviewprocess.html#api-listings
