### ISSUE TITLE
Smoke tests: Do we require AZURE_AUTHORITY_HOST (or whatever the final name is)

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk#1104]
Right now 3 of the 4 smoke tests fall back to a default authority host associated with the public cloud. Should we require that an authority host be provided for the smoke tests or use the default behavior? 

Continuing discussion from: https://github.com/Azure/azure-sdk-for-net/pull/10417#pullrequestreview-374611099

**Comment by kurtzeborn** [comment]
You've changed the world a bunch since this issue was opened.  Not sure if this matters or still applies any longer.

**Comment by benbp** [comment]
Closing this as it doesn't relevant, or at least, a priority since it hasn't been touched. In general the azure authority host config is settled with a best practice for now, at least in live tests. When we onboard samples for net smoke tests, we may open this issue again.
