### ISSUE TITLE
Change Request: Clarify namespace guidelines for all languages

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/azure-sdk#1106]
## The Basics

* Which design guideline is affected?

[Namespaces](https://azure.github.io/azure-sdk/general_design.html#namespaces)

* Which target languages are affected?

All languages

* Describe the change:

Services should not be assigned group namespaces. In other words, every service should have a unique sub-namespace from one of the allowed groups.

## Reasoning

Python imposes some extra challenges on libraries in a "non-leaf" namespaces. From @johanste:

> Two distribution packages can't easily add things to the same "empty" namespace. Only one distribution package owns what you import if you do an from azure.search import *. In other words, we can add a azure-search-nspkg that introduces a azure.search namespace, but it would have to be empty other than for the submodules included by other packages. For example, the azure namespace (in Python) has no classes or functions in it. It only exists so other packages can add modules underneath it. 
>
> The problem is the \_\_init\_\_.py file. Only one distribution package can carry it. 
>
> PEP420 fixed some of these problems, but we can't rely on PEP420 for Python 2.7
>
> We already had this situation for azure.storage.files where we later wanted to add azure.storage.files.shares. Which we did for most languages, but in Python we have azure.storage.fileshares.

However, guidelines should be consistent across languages, so this is a case where the lowest-common-denominator should become the norm.

**Comment by kyle-patterson** [comment]
Scheduled for 4/12

**Comment by kyle-patterson** [comment]
Link to recording (MSFT INTERNAL): https://msit.microsoftstream.com/video/2240a1ff-0400-86e9-7be5-f1ea7e981f89

- Proposal received general agreement
- Remember, there's no concept of namespace in Go or C
--  Hence, addressing lowest-common denominator may not be idiomatic to the language

Suggested guidance:
- DO NOT use service names as second-level namespaces
- If there's need for a specific namespace review, request a board review

**ACTION** @kyle-patterson to submit PR updating general guidelines
