### ISSUE TITLE
Board Review: Azure.Storage.Blobs.Cryptography and Azure.Storage.Queues.Cryptography

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk#1107]
# The Basics

* Service team responsible for the client library: Storage
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/storage/common/storage-client-side-encryption (the end of the document goes into Track 1 SDK exposure)
* Contact email (if service team, provide PM and Dev Lead): jaschrep, amishra

## About this client library

* Name of the client library: Azure.Storage.Blobs.Cryptography, Azure.Storage.Queues.Cryptography
* Languages for this review: C#
* Link to the service REST APIs: N/A, client feature only.

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  NOTE: a multifeature review was scheduled, so these packages will contain changes not-related to this specific feature.
    * [Common. Rev1 against Rev0.](https://apiview.dev/Assemblies/Review/14104fe29b8241adba09333a51c93425?diffRevisionId=8d0d2016948148d8a76d796aff83cc80)
    * [Blobs. Rev1 against Rev0.](https://apiview.dev/Assemblies/Review/12a319943f0a409eb921db377a4a0b54)
    * [Blobs.Cryptography.](https://apiview.dev/Assemblies/Review/1d35cec745a4439ea8bc9fc78411c5cb) Whole package is new.
    * [Queues. Rev1 against Rev0.](https://apiview.dev/Assemblies/Review/ee23fe63c8aa4e1d8747609a461a97fa?diffRevisionId=bc517e7163bc4d4683c84f3f10170aed)
    * [Queues.Cryptography.](https://apiview.dev/Assemblies/Review/119361d3de21495eb61270759e069bdd) Whole package is new.
* Link to samples for champion scenarios: N/A. This is just another client option to set, but with extra details to support it.

Note that the API presented in the views contains more than just `ClientSideEncryptionOptions` and a new extension method for each of `BlobClientOptions` and `QueueClientOptions`. Blobs and Queues each define an upload and download transform class in their Azure.Storage.Xyz.Models namespace. These classes support the minimum possible feature set for client-side encryption to work, though they are presented in a generic way. These classes are what get injected into client options behind the scenes, and it is necessary to expose them publicly for our external crypto dll to function.

## Champion Scenarios

* Champion Scenario 1:
    * Get a blob client with clientside encryption.
    * No way of currently knowing. But big customers, internal and external, require it.
```csharp
public void BlobSample1(ClientsideEncryptionOptions encryptionOptions, Uri blobUri, TokenCredential credential)
{
    var clientOptions = new BlobClientOptions(); // initialize as one normally would
    clientOptions.AddClientSideEncryption(encryptionOptions); // extension to add encryption
    BlobClient blob = new BlobClient(blobUri, credential, clientOptions);
    // use blob client as you normally would
}
```
```csharp
public void BlobSample2(ClientsideEncryptionOptions encryptionOptions, Uri accountUri, string containerName, stringBlobName, TokenCredential credential)
{
    var clientOptions = new BlobClientOptions(); // initialize as one normally would
    clientOptions.AddClientSideEncryption(encryptionOptions); // extension to add encryption

    // encryption options transfer across clients like other options, even though they are only useful on blob clients
    BlobClient blob = new BlobServiceClient(accountUri, credential, clientOptions)
        .GetContainerClient(containerName)
        .GetBlobClient(blobName);
    // use blob client as you normally would
}
```

* Champion Scenario 2:
    * Send/receive a queue message using clientside encryption.
    * No way of currently knowing. But big customers, internal and external, require it.
```csharp
public void QueueSample1(ClientsideEncryptionOptions encryptionOptions, Uri queueUri, TokenCredential credential)
{
    var clientOptions = new QueueClientOptions(); // initialize as one normally would
    clientOptions.AddClientSideEncryption(encryptionOptions); // extension to add encryption
    QueueClient queue = new QueueClient(queue, credential, clientOptions);
    // use queue client as you normally would
}
```
```csharp
public void QueueSample2(ClientsideEncryptionOptions encryptionOptions, Uri accountUri, string queueName, TokenCredential credential)
{
    var clientOptions = new QueueClientOptions(); // initialize as one normally would
    clientOptions.AddClientSideEncryption(encryptionOptions); // extension to add encryption

    // encryption options transfer across clients like other options, even though they are only useful on queue clients
    QueueClient queue = new QueueServiceClient(accountUri, credential, clientOptions)
        .GetQueueClient(queueName);
    // use queue client as you normally would
}
```

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by kyle-patterson** [comment]
Adding @KrzysztofCwalina for lang-specific guidance. I'll follow up if this needs a deeper board discussion.

**Comment by kyle-patterson** [comment]
Scheduled for 3/25.

**Comment by kyle-patterson** [comment]
Link to recording: (MSFT INTERNAL): https://msit.microsoftstream.com/video/d12aa4ff-0400-86e7-2cb7-f1ea72dada72

Documentation relies on terms server-side encryption and client-side encryption. Client-side documentation refers to the feature as client-side encryption.

**RECOMMENDATION**: Clarify within the client library that it does not touch server-side encryption

Q: Does crypto need to be in a common package, and not in shared source? 
- This is in a public class for the user, which prohibits blobs & queues from being included simultaneously.

Q: Is there a use case for shared client-side encryption on both queues and blobs? Why not data types specific to each? 
- While not currently, future features may be different between libraries, so different data types might help. However, nothing is planned for this currently, so sticking with Storage.Common 

**ACTION**: Rename "Storage.Common.Cryptography" to just be in the root "Storage" library. Leave the class as a common class, rather than creating two different data types.

**ACTION**: @jaschrep-msft to open an issue for implenting Content Range HTTP header within Azure Core

Architects have concerns about supporting client-side encryption (namely, effort and cost) within all tier-1 languages

**Comment by jaschrep-msft** [comment]
Description updated with brand new API views, new samples to accommodate the proposed change in API presentation, and short description of some of the APIs introduced that aren't directly related to encryption.

I noticed upon writing this that the API view for Azure.Storage.Common does not reflect the action item `Rename "Storage.Common.Cryptography" to just be in the root "Storage" library.`. Additionally, the API view reflects a ContentRange property being exposed as a string, which is pending resolution of the `issue for implenting Content Range HTTP header within Azure Core`. These actions will be present in a final product.

**Comment by kyle-patterson** [comment]
Scheduled for 5/13

**Comment by KrzysztofCwalina** [comment]
@jaschrep-msft, could you add a sample showing how to create the ClientsideEncryptionOptions ?

**Comment by jaschrep-msft** [comment]
@KrzysztofCwalina the class is just a collections of properties with public getters and setters, I'm not sure what there is to detail about it's creation. If you're curious about how to get the types necessary for it, users are expected to use the Identity implementation or write their own.

**Comment by KrzysztofCwalina** [comment]
Yeah, It would be good to show how to integrate it with identity APIs.

**Comment by kyle-patterson** [comment]
Link to recording (MSFT INTERNAL): https://msit.microsoftstream.com/video/e624a1ff-0400-96d0-a7fb-f1ea95635a20


### Notes

- Even if ClientsideEncryptionOptions are in a separate assembly, the options class must be included in common as it is a public type

- If there's no external dependency problem now, there are other means of hiding client-side encryption. Introducing a new package may not be the best method
-- Including within Blobs and Queues packages may make maintenance easier

- Users must either use Identity encryption methods (KeyVault) or implement key-management system

Discussion: Inheritence model
- Dangerous if there's another extension, as customers must choose between types
- Could open up with extension methods at that point, once the customer use cases are understood
-- This introduces two mechanisms of doing the same thing

Discussion: Remove visibility in Intellisense (EditorBrowsable.Advanced)
- Users may notice methods are no longer are intellisense and switch to advanced, then not switch back -- which doesn't hide this method any longer
- If a user doesn't see the method in Intellisense, but does see it within docs, they may be frustrated or confused trying to use this method

**Recommendation:** Include extensions within the base assembly, but place them under a different namespace
**Option**: This extension method could also be a helper method

Q: What about using a 'specialized' namespace?
- This creates a pattern for advanced storage usage
- Avoids creating an additional namespace
- Also hides type from visual studio

Provisionally signed off, return with final API design for final approval

### Encryption Versioning
- Create a required parameter (enum) to select version of encryption

Q: How will users know to use the new versions?
- Mix of docs, browser strings, etc

No Objections
