### ISSUE TITLE
Board Review: Azure.Storage.Blobs new transactional hashing API

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk#1109]
## The Basics

* Service team responsible for the client library: Storage
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview
* Contact email (if service team, provide PM and Dev Lead): amishra, jaschrep

## About this client library

* Name of the client library: Azure.Storage.Blobs
* Languages for this review: C#
* Link to the service REST APIs: [Download example.](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob) [Upload example.](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob) Look at headers with "md5" or "crc" in the name.

### .NET
* Link: NOTE that a multi-feature review was scheduled, so these packages will contain changes not related to this specific feature.
    * [Common. Rev6 against Rev5.](https://apiview.dev/Assemblies/Review/b48340c11dab4e88b3b2bd269bc03661?diffRevisionId=aed36a5529a144f09e0881ea731e7ffb) Anything with the name "Sas" in it.
    * [Blobs.](https://apiview.dev/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660?diffRevisionId=556861fd56ac4d1d9ccdbb3c511a2c98) Rev10 against Rev9. Anything with the name "Sas" in it.
* Link to samples for champion scenarios: 
```csharp
public Uri Sample(Uri containerUri, TokenCredential credential, TransactionalHashOptions options, string filePath)
{
    ContainerClient container = new ContainerClient(
        containerUri,
        credential,
        new BlobClientOptions
        {
            TransactionalHashOptions = options
        });
    container.GetBlobClient(filePath).Upload(filePath); // transactional hashes automatically applied
}
```

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario:
    * Use transactional hashes to assure data integrity across a large window of time, not just HTTPS transfer.
    * Sample inline above.

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by kyle-patterson** [comment]
Adding @KrzysztofCwalina for lang-specific guidance. I'll follow up if this needs a deeper board discussion.

**Comment by kyle-patterson** [comment]
Scheduled for 3/25.

**Comment by kyle-patterson** [comment]
Link to recording: (MSFT INTERNAL): https://msit.microsoftstream.com/video/d12aa4ff-0400-86e7-2cb7-f1ea72dada72

Goal: automate transactional hashing, which enables it for multi-part upload/download. 

Q: Why is automateHashing defaulted to true? -
- Users must set options to use the new hashing API (opt-in), but if they do provide options then by default we should do validation (which should be opt-out).
- This would increase computation cost and impact performance. 
- In addition, we need to complete the transaction before checking the hash; maybe this should be left to control of the user. 
- There are a lot of repurcussions that come from this:

**ACTION**: @jaschrep-msft to document/enumerate scenarios and the impact this outcome & impact this change introduces
