### ISSUE TITLE
Review Java package list

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#1117]
Please review the list of libraries/packages:

- [New Libraries](https://azure.github.io/azure-sdk/releases/latest/java.html)
  - Backing csv [data source](https://github.com/Azure/azure-sdk/blob/master/_data/releases/latest/java-packages.csv)
  - There is automation in place to update the versions in this csv file based on release tags in our repos, so ignore the versions. 
  - Please review for any missing packages and any names that that need to be updated.

- [All Libraries](https://azure.github.io/azure-sdk/releases/latest/all/java.html) 
  - Backing csv [data source](https://github.com/Azure/azure-sdk/blob/master/_data/allpackages/java-packages.csv)
  - There is automation in place to query the package manager and add new packages and update versions for any packages published via the azure-sdk account, so ignore those aspects. 
  - Please review for any packages that are missing or any packages we wish to hide (set Hide column to true in csv). 
  - Please review and add notes (set Notes column value in csv) to any older packages that we want to help redirect customers away from or any other notes we want to make about the package.

**Comment by srnagar** [comment]
The list of packages is missing:
Azure Storage File Datalake - https://mvnrepository.com/artifact/com.azure/azure-storage-file-datalake/12.0.1

**Comment by joshfree** [comment]
Thanks @weshaggard.  
> Please review for any missing packages and any names that that need to be updated. 

I see other languages (https://azure.github.io/azure-sdk/releases/latest/dotnet.html) are listing core  packages.  To be consistent we should also list packages under com.azure (https://mvnrepository.com/artifact/com.azure)

1. azure-core
2. azure-core-amqp
3. azure-core-http-netty
4. azure-core-http-okttp

We're also missing

1. azure-storage-common
2. azure-storage-file-datalake
3. azure-search

**Comment by srnagar** [comment]
azure-cosmos also should be included 
https://mvnrepository.com/artifact/com.azure/azure-cosmos/4.0.1-beta.1

**Comment by alzimmermsft** [comment]
Depending on when this was populated: 

Azure Search - https://mvnrepository.com/artifact/com.azure/azure-search/11.0.0-beta.1
Azure Cosmos - https://mvnrepository.com/artifact/com.azure/azure-cosmos/4.0.1-beta.1

**Comment by weshaggard** [comment]
Just a little further clarification. The "New Libraries" is a list we manually created during release notes and automation can only update version info for those libraries that are published from the azure-sdk-for-java repo, thus is usually only track 2. The "All Libraries" is actually queried from maven central and is all the packages that we publish to maven from the azure-sdk account.

**Comment by joshfree** [comment]
@weshaggard do you want us to PR the missing entries for the first csv or did you just want feedback here?

**Comment by weshaggard** [comment]
I'd like one of you guys to submit the PR with the updates as I want you guys to maintain it overtime so it would be good if one of you went through the process.

**Comment by weshaggard** [comment]
We have been actively updating the package list now so we can close this.
