### ISSUE TITLE
Add a common AzureKeyCredential to Azure Core

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk#1142]
Various of the Azure services use a key to authenticate to an Azure service. Currently we have Text Analytics, Form Recognizer and Search.
Each service is doing an implementation for key and a policy to add it's value to each request. Instead, we want to have a common `AzureKeyCredential`  and its policy in Azure Core, following the [auth](https://azure.github.io/azure-sdk/general_design.html#authentication) guidelines of providing an update method to allow user to rotate the key without restarting long lived clients.

- .NET: https://apiview.dev/Assemblies/Review/3f640270a7de4d8e99a5543bf4257e4f?diffRevisionId=39c26b0137be4c77bd73ce7b3a82233f
- Java: https://apiview.dev/Assemblies/Review/e2e4d65e41c543e994c310459a42dbe8?diffRevisionId=47a5dfdefa77472da1e889d30fa88394
- Python: https://github.com/Azure/azure-sdk-for-python/pull/10509
- Javascript: https://github.com/Azure/azure-sdk-for-js/pull/7927

Although the architects have been involved in each language PR, I wanted to get approvals here to make sure we can ship Azure.Core with this change.

cc: @schaabs @KrzysztofCwalina @tg-msft @johanste @bterlson  @JonathanGiles 
FYI @mayurid @alzimmermsft @willmtemple @iscai-msft

**Comment by johanste** [comment]
I have approved the Python PR.

**Comment by KrzysztofCwalina** [comment]
.NET looks good too!

**Comment by JonathanGiles** [comment]
Java looks fine. At some point will a PR be opened with JavaDoc for review on these new types?

**Comment by bterlson** [comment]
JS is G2G.

**Comment by mayurid** [comment]
@mssfang : Can you give ETA for Jonathan's question?

**Comment by mssfang** [comment]
> @mssfang : Can you give ETA for Jonathan's question?

@alzimmermsft  Since you have all the context, do u know the ETA for this?

**Comment by alzimmermsft** [comment]
> 
> 
> > @mssfang : Can you give ETA for Jonathan's question?
> 
> @alzimmermsft Since you have all the context, do u know the ETA for this?

Worked with @JonathanGiles to understand his comment and resolved it, the changes have been merged into master.

**Comment by maririos** [comment]
Thank you all!
