### ISSUE TITLE
Board Review: Search Index Management

### ISSUE THREAD

**Issue by xirzec** [Azure/azure-sdk#1143]
## The Basics

* Service team responsible for the client library: **Azure SDK**
* Link to documentation describing the service: https://azure.microsoft.com/en-us/services/search/
* Contact email (if service team, provide PM and Dev Lead): 

  **Alex Ghiondea** (PM)
  **Jeff Fisher** and **Sarangan Rajamanickam** (JS)
  **Ted Glaza** and **Heath Stewart** (.NET)
  **Sima Zhu** and **Alan Zimmer** (Java) 
  **Bryan Van de Ven** and **Xiang Yan** (Python) 

## About this client library

* Name of the client library: **search-documents**
* Languages for this review: **C#, Java, JavaScript, Python?**
* Link to the service REST APIs: 

  https://docs.microsoft.com/en-us/rest/api/searchservice/

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/d40a51d26cf2444a85d302758ca3a2d1

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link:
https://apiview.dev/Assemblies/Review/7a9064677047411582a12c50f7fe9cd8

### Python

* apiview: https://apiview.dev/Assemblies/Review/2bbd9e7658c047d9bb84cf2fccbce0b3#azure.search.documents.SearchServiceClient

### JavaScript

* Upload output of api-extractor as a Draft PR.  Link to PR:
https://github.com/Azure/azure-sdk-for-js/pull/8154/files

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

The context of all the following scenario is:

> Customer runs a web store.  As part of the store, they have a product search capability.

#### Define a search index to query against

*Customers may wish to programmatically create a new search index.*

* Target audience: basic developers with general needs (~90%)
* Code samples: [**.NET**](TODO) | [**Java**](https://gist.github.com/sima-zhu/44847286cadab79c1b57eed8400fb5d9#1-define-a-search-index-to-query-against) | [**Python**](https://gist.github.com/bryevdv/9498f5bdb0148affc6c8792acad6f54f#1-define-a-search-index-to-query-against) | [**TypeScript**](https://gist.github.com/xirzec/636cd1d7d9010e8ed368deda33126833#1-define-a-search-index-to-query-against)

#### Retrieve an existing index and add a new field to it

*Customers may wish to programmatically extend an existing index.*

* Target audience: basic developers with general needs (~90%)
* Code samples: [**.NET**](TODO) | [**Java**](https://gist.github.com/sima-zhu/44847286cadab79c1b57eed8400fb5d9#2-retrieve-an-existing-index-and-add-a-new-field-to-it) | [**Python**](https://gist.github.com/bryevdv/9498f5bdb0148affc6c8792acad6f54f#2-retrieve-an-existing-index-and-add-a-new-field-to-it) | [**TypeScript**](https://gist.github.com/xirzec/636cd1d7d9010e8ed368deda33126833#2-retrieve-an-existing-index-and-add-a-new-field-to-it)

#### Define a custom analyzer and test its output

*Customers may wish to tweak the indexing process by specifying their own analyzer.*

* Target audience: experienced developer with general needs (~50%)
* Code samples: [**.NET**](TODO) | [**Java**](https://gist.github.com/sima-zhu/44847286cadab79c1b57eed8400fb5d9#3-define-a-custom-analyzer-and-test-its-output) | [**Python**](https://gist.github.com/bryevdv/9498f5bdb0148affc6c8792acad6f54f#3-define-a-custom-analyzer-and-test-its-output) | [**TypeScript**](https://gist.github.com/xirzec/636cd1d7d9010e8ed368deda33126833#3-define-a-custom-analyzer-and-test-its-output)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by kyle-patterson** [comment]
I've scheduled for 4/9. Architects, please take a look at the API changes and provide feedback...
