### ISSUE TITLE
Docs CI Build Should Run On Release Completion

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#1150]
The docs team maintains an _alternate_ webhook host than the standard azure devops. As a result, we have a prebuilt way to trigger individual CI builds within the `Content CI` devops project.

Example for Java:
`<webhookurl>/api/webhooks/incoming/github?path=PROD%5CGitHub_Azure_azure-docs-sdk-java&name=Azure_Azure-sdk-for-java-CI`

Need to add a notification to the above url in the release process after we post to the package manager. 

- [ ] .NET
- [ ] Python
- [ ] Javascript
- [ ] Java
- [ ] C

Here's the key, we need to trigger the appropriate CI for the packages that were onboarded. New Preview? Should trigger the PREVIEW CI. Otherwise trigger PROD.

I figure if we need to automate this for `legacy`, we can begin comparing the version outgoing to the versions that were already present. If OLDER than a an existing release, should trigger the `legacy` pipeline. 

I will work with Robert Outlaw to get the appropriate secret into our keyvault.

**Comment by danieljurek** [comment]
The Docs CI (created by OPS) pipelines run nightly against the `master` branch. To publish the updates today, one must open a PR merging changes from the `master` branch into the `live` branch.

**Comment by danieljurek** [comment]
We're doing this in `docindex` for nightly doc releases. Onboarding is also updated for preview and latest monikers as part of this build. With automated onboarding running daily we effectively have accomplished the goal of this issue.
