### ISSUE TITLE
Change Request: Client parameter validation changes for URI parameters

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk#1199]
Our [current guidelines](https://github.com/Azure/azure-sdk/blob/c7554bbf9605cecd539df799bd2c2bfe6c079b39/docs/general/implementation.md#parameter-validation) state:

> Client parameters are not passed directly to the service, but used within the client library to fulfill the request.

This would seem to imply anything that constructs the request URI, including host, path, and query parameters.

Additionally, it states:

> DO validate client parameters.

Currently, our autorest generators are checking for null for required parameters (any parameters, whether URI-specific or not, at least for autorest.csharp) but we need to also respect any `minLength` property in the swagger and check for an empty string. In Key Vault, for example, if a key name was an empty string, the request `GET /secrets/{key-name}/` becomes `GET /secrets//` which is a list operation and the deserializer will break. Hypothetically, some requests could be destructive if wrong, though that may not be practical.

After internal discussions, we propose that any *required* string parameters as part of the host, path, or query string continue to be checked for null, but if they have a `minLength` property > 0 they also be checked for an empty string, but no more i.e. any value of `minLength` > 1 or any value of `maxLength` will be validating solely by the server.

The guidelines should be updated to reflect this, and bugs opened accordingly on autorest generators.

**Comment by adrianhall** [comment]
Shouldn't the autorest generators respect the minLength?  This would achieve the spirit of the guideline - do validate client parameters - and be correct, without needing an additional change.

**Comment by heaths** [comment]
That's what I'm suggesting, yes. But only doing minimal validation, i.e. checking for empty string. This was a discussion with @johanste, @KrzysztofCwalina, and @pakrym and seems the guidelines need clarification here before we make such a change to the generators across the board.
