### ISSUE TITLE
Board Review: Azure Identity User Authentication API

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk#1215]
# Background
Azure Identity allows applications to authenticate users interactively through credentials that open browsers or prompt users to do so. Today, these credentials immediately begin interactive authentication when they can't provide a cached token. This means an application's users may be surprised by an authentication prompt or browser window at any time. If the application is synchronous, it will block during interactive authentication. Because these credentials don't expose authentication information, an application using them must reauthenticate users each time they run the application.

To improve user experiences, application developers therefore want to control when interactive authentication happens and to persist authentication information across executions. This proposal includes new configuration and methods on interactive credentials to enable that.

# Proposed changes

A new instance method begins interactive authentication when called. It returns a serializable user profile.

Interactive credentials can be initialized with user profiles, and use them to find previously cached tokens.

A new constructor option configures an interactive credential to raise an exception when its cache is insufficient rather than immediately begin interactive authentication.

# Python usage

[apiview](https://apiview.dev/Assemblies/Review/08d829ed43d646949c6b6a09bc057840?diffRevisionId=5f5fe636bdfd4cb6b095d8bfa34abab5)

## Prompt a user to authenticate, store the profile
`authenticate` begins interactive authentication, returns a profile:
```py
credential = InteractiveBrowserCredential()
user_profile = credential.authenticate()
profile_json = user_profile.serialize(keyword='args', serialized='also')

with open(PROFILE_PATH, 'w') as f:
    f.write(profile_json)
```

## Create a credential from an existing profile
```py
with open(PROFILE_PATH, 'r') as f:
    profile_json = f.read()

deserialized_profile = UserProfile.deserialize(profile_json)
credential = InteractiveBrowserCredential(profile=deserialized_profile)
```

## Prevent automatic authentication
`disable_automatic_authentication` configures a credential to raise rather than begin interactive authentication when its cache is insufficient:
```py
credential = InteractiveBrowserCredential(disable_automatic_authentication=True)
try:
    result = service_client.do_something()
except AuthenticationRequiredError as ex:
    requested_scopes = ex.scopes
    credential.authenticate(scopes=requested_scopes)

    result = service_client.do_something()
```

# .NET 

[API View](https://apiview.dev/Assemblies/Review/743c1da3310b466195cec5166aa7713a?diffRevisionId=73f0d21bf3c647d68944f7cba6a6394c)

The API additions in this PR are intended to be used by applications to authenticate users. It adds support for the following:

  - Give application control over when users are prompted to authenticate
    - Add `Authenticate` methods to `InteractiveBrowserCredential` and `DeviceCodeCredential`
    - The option `DisableAutomaticAuthentication` can be specified on credential construction to disable automatic prompting of users when `GetToken` is called.
    - Add `AuthenticationRequiredException` which can be handled to manually prompt users to authenticate.
  - Persist user authentication details between executions
    - The newly added `AuthenticationProfile` is returned from `Authenticate` calls
    - `AuthenticationProfile` supports `Serialize` and `Deserialize`

### Prompt the user to authenticate and store the AuthenticationProfile
~~~ c#
  var credential = new InteractiveBrowserCredential(new InteractiveBrowserCredentialOptions { DisableAutomaticAuthentication = true });

  AuthenticationProfile profile = await credential.AuthenticateAsync();

  using FileStream fileStream = new FileStream("./profile.json", FileMode.Create, FileAccess.Write);

  await profile.SerializeAsync(fileStream);

  await fileStream.FlushAsync();
~~~

### Create a credential from a pre-existing AuthenticationProfile
~~~ c#
  using FileStream fileStream = new FileStream("./profile.json", FileMode.Create, FileAccess.Read);

  AuthenticationProfile profile = await AuthenticationProfile.DeserializeAsync(fileStream);

  var credential = new InteractiveBrowserCredential(new InteractiveBrowserCredentialOptions { DisableAutomaticAuthentication = true, AuthenticationProfile = profile });
~~~

### Using a credential to manually authenticate with a service client and handling AuthenticationRequiredException
~~~ c#
  SecretClient client = new SecretClient(new Uri("https://myvault.vaults.azure.net/"), credential);

  try
  {
      client.GetSecret("secret");
  }
  catch (AuthenticationRequiredException e)
  {
      await credential.AuthenticateAsync(e.TokenRequestContext);
      
      client.GetSecret("secret");
  }
~~~

**Comment by kyle-patterson** [comment]
Scheduled for 4/16.

**Comment by kyle-patterson** [comment]
Link to recording (MSFT Internal): https://msit.microsoftstream.com/video/1f00a4ff-0400-86eb-8100-f1ea802fcb60



Q: Isn't this "disabling the user's automatic interaction mechanism", not actually disabling the authentication mechanism?
**RECOMMENDATION**: Maybe name this "disable_automatic_interaction"
-- This is only a weak concern
-- This doesn't disable interative log-in, just disabling the automatic behavior (allowing for a prescriptive approach)

Q: Can a user hook up a call back to the authentication?
- You would have to accept a block on that callback
- But Try/Catch would be very interweaved in the app
- There already exists a callback for user info (device code, etc)
- Many concerns around customer using callbacks in async (threadsafe, exception handling, etc)

- Could bubble up exception
-- But would then want to continue from location of original exception, which would mean manual "continuation" in every routine
 
Q: What about retrieving the scopes for a credential proactively?
- Currently we don't support that programmatically (in which case, refer to documentation)

- Consider some features to test authentication logic, such as automated cache clearing?

Q: What is the serializer?
- JSON
- If users can serialize/deserialize across languages, that needs to be tested


.NET Review:
Q: Should AuthenticationProfile have public properties, or a collection of private & serialize additional properties?
- If users shouldn't even see the properties, and this will all be within the same assembly (identity) just make them internal
- If they're internal and an app is then locked to a specific tenant, it would not be able to support multiple tenants (switching between them). 
- Public getters would be helpful in logging, or supply a toString()
- Consider renaming AuthenticationProfile to reflect it's just a cache (store) of data ("AuthenticationCacheKey")

Q: What is "AdditionalData"
- Collection of extraneous data that the end user may include
- Reconsider the neccessity of this property

Python Review:
Q: Where do wrapped exceptions go?
- That was moved to a base class

- UserProfile should also be reconsidered, as it's also just a cache key
