### ISSUE TITLE
Releases Submit PR to azure-docs-pr reflecting Updated Packages List

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#1252]
Somewhere on this [page](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-overview?view=azure-python), or a subpage. 

Package List Source is [here](https://azure.github.io/azure-sdk/releases/latest/all/dotnet.html) (follow the github.io location).

This is extremely similar to the #1253, and should share automation scripts.

**Comment by scbedd** [comment]
This is where it should exist in dev center ToC.

![image](https://user-images.githubusercontent.com/45376673/81104320-2f372280-8ec7-11ea-99e0-d3016b3cee08.png)

**Comment by danieljurek** [comment]
I think an example of this is: https://docs.microsoft.com/en-us/azure/developer/python/sdk/storage/overview?view=storage-py-v12

**Comment by danieljurek** [comment]
@scbedd -- Should this still be open?

**Comment by scbedd** [comment]
@weshaggard IIRC we actually sync the releases markdown. I can't recall exactly where, but I think this is actually already happening.

**Comment by weshaggard** [comment]
We have the package index being generated and published, such as https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-library-package-index. Is that the saem thing we are talking about here? If so then yes this work has been done.
