### ISSUE TITLE
Board Review: Event Hubs - Send batch API for collection of events

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk#1259]
## The Basics

* Service team responsible for the client library: Event Hubs
* Link to documentation describing the service: https://azure.microsoft.com/en-us/services/event-hubs/
* Contact email (if service team, provide PM and Dev Lead): SeongJoon Kwak, Javier Fernandez & Shubha Vijayasarathy

## About this client library

* Name of the client library: azure-messaging-eventhub
* Languages for this review: Python, Java, .NET, JS
* Link to the service REST APIs: N/A

## Background and alternatives considered

Event Hub producer client today requires users to create an EventBatch, tryAdd() events to the batch and send the batch when the user is ready or when the next event does not fit into a batch.

While this API is very helpful to ensure we build a batch that would meet the size restrictions of the AMQP link, it is cumbersome for cases where the customer is confident that their set of events does actually fit within the size restrictions. There has also been feedback that the client should be smart enough to do batching on its own without having the customer do it.

We explored a variety of options to provide a smart send feature to the customer which is captured in [this gist](https://gist.github.com/srnagar/8616fede4d53677201e0ba50512a70f9).

We soon realized that each alternative resulted in us foregoing one section of the user base in favor of the other and had us making assumptions regarding the customer use cases. Therefore, we chose to rather provide tools to the customer and trust that they know their application best. 

If they want to ensure that their batch is under the size limit, then they can use `CreateBatch()` that already exists. If they are confident they won't increase the limit, they can use `send()` that takes multiple events and throwing an exception if the batch size indeed increases the limit.

This issue is to propose the introduction of a new API to send events on the producer client that takes multiple events as input and throws an exception if the size of the resulting batch increases the size limits

### Java
* [API review](https://apiview.dev/Assemblies/Review/349e2c72d298444fa873bab68798b42c?diffRevisionId=a14a9e3e21c94c859f08e71d45b7e420)
* [Sample code](https://gist.github.com/srnagar/8616fede4d53677201e0ba50512a70f9#user-code-3)

### Python
* [API with sample code](https://github.com/Azure/azure-sdk-for-python/pull/11021/files)

### JavaScript
* [API with sample code](https://github.com/Azure/azure-sdk-for-js/pull/8470)

### .NET
* [API](https://apiview.dev/Assemblies/Review/ef013a8cb7cc4f4c83cb6d1e64367bd1/122e3a022dd74473997979315d6cf2d5)
* [Sample code](https://gist.github.com/srnagar/8616fede4d53677201e0ba50512a70f9#gistcomment-3267012)

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario: 
    * Describe the champion scenario: Send a list of events that the user knows can fit within a single `EventDataBatch`. 
    * Estimate the percentage of developers using the service who would use the champion scenario: Most developers will use it. We have also received feedback from customers to provide this capability.
    * Link to the [code sample](https://gist.github.com/srnagar/8616fede4d53677201e0ba50512a70f9#user-code-3)

**Comment by JonathanGiles** [comment]
Looks good to me for Java.

**Comment by KrzysztofCwalina** [comment]
Please upload revision with the new PAIs to https://apiview.dev/Assemblies/Review/ef013a8cb7cc4f4c83cb6d1e64367bd1

But I took a look at the new API listing, and it looks good.

**Comment by bterlson** [comment]
API listing is good here too.

**Comment by serkantkaraca** [comment]
Looks good for .NET

**Comment by johanste** [comment]
Added some comments to the Python examples. @annatisch, have you also gone over this?

**Comment by annatisch** [comment]
Yup - I've also added a couple of comments, but so far look good to me.

**Comment by annatisch** [comment]
@johanste - I think the comments have been addressed - I'm good with this.

**Comment by johanste** [comment]
Approved.

**Comment by ramya-rao-a** [comment]
Closing this as the May update has this api shipped across all 4 languages
