### ISSUE TITLE
Integrate Go Modules into SDK List

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#1278]
I was chatting with Joel about Go packaging and it is quite different than the other langs.

So, we will need to plan for how we get Go packages to the SDK list.

I found this helpful.
https://blog.golang.org/using-go-modules

I don’t know if they have an API to pull in package versions and name like we do with other langs.

**Comment by weshaggard** [comment]
Closing in favor of https://github.com/Azure/azure-sdk/issues/1485
