### ISSUE TITLE
Change Request: .NET Framework is not standard for C# anymore

### ISSUE THREAD

**Issue by wiazur** [Azure/azure-sdk#1289]
## The Basics

* Which design guideline is affected?
https://azure.github.io/azure-sdk/dotnet_introduction.html

* Which target languages are affected?
C#

* Describe the change:
Change the SDK from .NET Framework to .NETCore

## Reasoning
I read somewhere that dotnet is changing to focus on .NETCore instead of .NET Framework. I see in Visual Studio now, the default console app will make it in .NETCore. Has this focus changed for Azure SDKs too? If so, then the guide should be updated.

**Comment by kyle-patterson** [comment]
@KrzysztofCwalina can you weigh in?

**Comment by KrzysztofCwalina** [comment]
What specifically should be updated? i.e. the description of the change is not clear. The SDK is not ".NET Framework SDK".

**Comment by wiazur** [comment]
Hi @KrzysztofCwalina , perhaps I misunderstood, in this section is only refers to .NET Framework:

![Capture](https://user-images.githubusercontent.com/38537084/82937777-95064f80-9f45-11ea-829b-913316a7eaaf.JPG)

**Comment by KrzysztofCwalina** [comment]
The section refers to .NET Framework Design Guidelines, not to .NET Framework. The guidelines are applicable to both .NET Framework and .NET Core.
