### ISSUE TITLE
Board Review: Register namespace for .Net mgmt plane

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk#1312]
We're owner of .net mgmt sdk, need to register namespaces for the following services:
### compute

`Azure.Management.Compute`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/compute/resource-manager

### eventhub

`Azure.Management.EventHub`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/eventhub/resource-manager

### keyvault

`Azure.Management.KeyVault`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/keyvault/resource-manager

### monitor

`Azure.Management.Monitor`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/monitor/resource-manager

### network

`Azure.Management.Network`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/network/resource-manager

### resources

`Azure.Management.Resources`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/resources/resource-manager

### storage

`Azure.Management.Storage`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/storage/resource-manager

### app configuration

`Azure.Management.AppConfiguration`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/appconfiguration/resource-manager

cc @allenjzhang

**Comment by kyle-patterson** [comment]
Scheduled a review for 5/20.

**Comment by kyle-patterson** [comment]
There is an ongoing, relevant conversation in #1245 

Notes from the meetings are included there, but link to the recording will be copied here (MSFT INTERNAL): https://msit.microsoftstream.com/video/553aa1ff-0400-96d0-3325-f1ea9aeda3a2

**Comment by erich-wang** [comment]
Arch review board agreed to use Azure.ResourceManager.* as namespace for .net track 2 mgmt sdk:
### compute

`Azure.ResourceManager.Compute`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/compute/resource-manager

### eventhub

`Azure.ResourceManager.EventHubs`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/eventhub/resource-manager

### keyvault

`Azure.ResourceManager.KeyVault`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/keyvault/resource-manager

### monitor

`Azure.ResourceManager.Monitor`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/monitor/resource-manager

### network

`Azure.ResourceManager.Network`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/network/resource-manager

### resources

`Azure.ResourceManager.Resources`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/resources/resource-manager


### storage

`Azure.ResourceManager.Storage`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/storage/resource-manager

### app configuration

`Azure.ResourceManager.AppConfiguration`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/appconfiguration/resource-manager
