### ISSUE TITLE
 Contents of Azure Spring boot starter libraries

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk#1342]
Discuss Contents of Azure Spring boot starter libraries

Link to one of starter modules: https://github.com/Azure/azure-sdk-for-java/tree/feature/spring/sdk/spring/azure-spring-boot-starter-servicebus

Look for all “azure-spring-boot-starter-****” modules.

**Detail about this topic**:

1.Azure Spring boot starter libraries only have a pom file/config and no source code. 
It will be released to maven as library with no source code.
 
The pom refers to “azure-spring-boot” as dependency where source code is. Example : https://github.com/Azure/azure-sdk-for-java/blob/feature/spring/sdk/spring/azure-spring-boot-starter-keyvault-secrets/pom.xml#L35
 
**Conflict with current Azure SDK repo standard**: 

All Azure SDK has its source code / test in it but spring starter libraries does not have source code. 
 
**Argument in favor of starters to following how Spring does**:
 
**From Spring IO**

“Starters are a set of convenient dependency descriptors that you can include in your application. You get a one-stop-shop for all the Spring and related technology that you need, without having to hunt through sample code and copy paste loads of dependency descriptors. For example, if you want to get started using Spring and JPA for database access, just include the spring-boot-starter-data-jpa dependency in your project, and you are good to go.”
 
**Spring documentation on  why starter needed**
 
https://docs.spring.io/spring-boot/docs/1.5.22.RELEASE/reference/html/using-boot-build-systems.html#using-boot-starter

**Question needs answering**

1. How does build system test before releasing `codeless` libraries  Or should `Spring boot starter libraries` be exception to this ?

2. When user land in "Spring boot starter libraries github repo" , they do not find any source code.
    It is how spring community expect but is it fine with Azure sdk point of view ?

3. Not having java doc will fail release step, this will require eng system to change and accept no doc for starter libraries.

**Comment by hemanttanwar** [comment]
@JonathanGiles @JimSuplizio @mitchdenny @jialindai @joshfree    Please provide your comments here

**Comment by hemanttanwar** [comment]
@weshaggard Please provide your comment also.

**Comment by JonathanGiles** [comment]
Ignoring our engineering system, how does Maven Central support javadoc-less releases such as these Spring Boot starters? I always assumed that Maven Central required a javadoc jar file as part of a release.

**Comment by mitchdenny** [comment]
@JonathanGiles I did some background reading on the starters and how they are used. They basically work like a BOM. They just pull in a dependency graph. So let's say you want to use KeyVault with Spring Boot, you add the KeyVault starter and it includes its dependencies which might include other starters, but potentially our track 2 libraries.

I think the only reason we are getting *.jar files produced at all is because there are some loose resources in the module directories ... here is an example for Cosmos:

https://github.com/Azure/azure-sdk-for-java/blob/feature/spring/sdk/spring/azure-spring-boot-starter-cosmosdb/src/main/resources/cosmosdb.enable.config

Note quite sure why those files exists or how they help.

**Comment by JonathanGiles** [comment]
I actually went to look at the pom file above and was surprised I didn't see `<packaging>pom</packaging>` in there. I presume it shouldn't be there, but that is what led me to ask the question.

**Comment by mitchdenny** [comment]
The root ```spring-boot-starter``` is:

![image](https://user-images.githubusercontent.com/513398/82269526-5a387080-99b5-11ea-8d1b-1fc699a9e406.png)

Maybe ours are incorrect?

**Comment by mitchdenny** [comment]
Oh hang on ... thats the parent. Looking through some other starters, it appears that some do contain real Java sources. So perhaps there is no strong convention here that they are POM only, just that the name implies that you should add it as a dependency "for starters :P"

**Comment by hemanttanwar** [comment]
I looked at one of the starter java doc and sources. 
https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-web/2.3.0.RELEASE/

All it has is following files

 META-INF/MANIFEST.MF
 META-INF/NOTICE.txt
 META-INF/LICENSE.txt

Maven documentation on if  we do not have java doc:
https://central.sonatype.org/pages/requirements.html : `If, for some reason (for example, license issue or it's a Scala project), you can not provide -sources.jar or -javadoc.jar , please make fake -sources.jar or -javadoc.jar with simple README inside to pass the checking. We do not want to disable the rules because some people tend to skip it if they have an option and we want to keep the quality of the user experience as high as possible.`

**Comment by hemanttanwar** [comment]
Updating what is action item from today meeting.

@JimSuplizio  will be looking into creating a bare javadoc with just the index.html So that we can publish it to maven central.

**Comment by jialindai** [comment]
Add Spring doc about recommended approach to build auto configuration and starter:
https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/spring-boot-features.html#boot-features-developing-auto-configuration

**Comment by JimSuplizio** [comment]
There was some confusion about the [publishing requirements to sonatype](https://central.sonatype.org/pages/requirements.html). For anything other than a pom file being published, Javadoc and Sources are required. I can produce an "empty" javadoc jar however I'm trying to see if I can't at least get the readme converted to a page that github.io and docs.ms can handle so if we have a doc entry for one of the starters, it'll at least have something.

**Comment by hemanttanwar** [comment]
All the issues are discussed and resolved. I do not see anything pending on this topic now.
So closing it.

**Comment by JimSuplizio** [comment]
I don't believe there's anything left to do with this. We're producing "empty" javadoc and sources jars, with just the README.md as their contents, for libraries that don't have sources which is the recommended action from Maven.
