### ISSUE TITLE
Add Azure Embedded SDK for C to Releases Page

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#1343]
The Embedded SDK for C needs to be added to the releases page.

https://github.com/Azure/azure-sdk-for-c

**Comment by RickWinter** [comment]
@jongio Is there work remaining on this item?

**Comment by jongio** [comment]
It's resolved with your PR right?

**Comment by RickWinter** [comment]
Yes, once you approve.  Wasn't sure if this was that or if you had bigger plans

**Comment by jongio** [comment]
This is complete.
