### ISSUE TITLE
Board Review: Event Hubs - Load balancing options for processor client

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk#1353]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Event Hubs
* Link to documentation describing the service: https://azure.microsoft.com/en-us/services/event-hubs/
* Contact email (if service team, provide PM and Dev Lead): SeongJoon Kwak, Javier Fernandez & Shubha Vijayasarathy

## About this client library

* Name of the client library: azure-messaging-eventhubs
* Languages for this review: Python, Java, .NET, JS
* Link to the service REST APIs: N/A

## Background and alternatives considered

Event Hubs provides message streaming through a partitioned consumer pattern in which each consumer reads a specific subset, or partition, of the message stream. This pattern enables a horizontal scale for event processing and provides other stream-focused features that are unavailable in queues and topics.

To scale your event processing application, you can run multiple instances of Event Processor Client and have it balance the load among themselves. The processor client periodically checks the current state of partition ownership and determines if partitions have to be redistributed among active instances.

In track 2 SDK for Event Processor client, the load balancing task runs at a fixed interval of 10 seconds. When the load is not balanced among active processors, partitions are claimed/stolen one at a time per load balancing loop. This can take a long time for the processors to reach a balanced state. The proposal in this issue is to provide options to configure the load balancer to speed up the process of reaching a stable state. Specifically, we will allow users to customize:
- The time interval for running the load balancer
- The time duration to wait before assuming a partition is orphaned
- The load balancing strategy to use: balanced (default) or greedy.
-- BALANCED: In this mode, one execution of load balancer task will claim at most 1 partition.
-- GREEDY: In this mode, one execution of load balancer task will claim as many partitions required to balance the load.

For details and other options considered, please refer to [this gist](https://gist.github.com/srnagar/366cb66279406db738f8eff82fbfb851).

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* [API view](https://apiview.dev/Assemblies/Review/0b08d992564243ce921b950fd3eacf27?diffRevisionId=85abe1ba41f4439f91c5f4819d748d91)
* [Scenario Samples](https://gist.github.com/srnagar/366cb66279406db738f8eff82fbfb851#gistcomment-3321729)

### Java

* [API view](https://apiview.dev/Assemblies/Review/8af570231c9a423e8aa2fe54a26fffad/25e129f168374ccfac6ce0102f192daa?diffRevisionId=d8c5a8d5745f43239a1fa1a4a3c630b7)
* [Link to samples for champion scenarios](https://gist.github.com/srnagar/366cb66279406db738f8eff82fbfb851#sample-user-code)

### Python

* [API view](https://apiview.dev/Assemblies/Review/fa294a29022e42c9b9b1b4d998e67821/42b3acc686a647a7b9564d0ffe8ebc34)
* [Link to samples for champion scenarios](https://gist.github.com/srnagar/366cb66279406db738f8eff82fbfb851#gistcomment-3320697)

### TypeScript

* Upload output of api-extractor as a Draft PR.  [Link to PR](https://github.com/Azure/azure-sdk-for-js/pull/9140/files?file-filters%5B%5D=.md)
* [Link to samples for champion scenarios](https://gist.github.com/srnagar/366cb66279406db738f8eff82fbfb851#gistcomment-3320626)

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Describe the champion scenario: User has a single instance of Event Processor Client subscribed to an Event Hub with 30 partitions and want to start processing from all partitions with minimum delay. To achieve that, the user can configure the processor client to use `GREEDY` strategy that claims all partitions with no delay when the processor starts.

    * Estimate the percentage of developers using the service who would use the champion scenario - Users who are tolerant to partitions changing ownership frequently at startup before reaching stable state and prefer to start processing from all partitions immediately will use it.

    * Link to the code sample - https://gist.github.com/srnagar/366cb66279406db738f8eff82fbfb851#sample-user-code

* Champion Scenario 2:
 * Describe the champion scenario: User has an Event Hub instance configured with 5 partitions and there are usually 5 instances of Event Processor Clients running. Also, the application requires extensive initialization and cleanup before and after processing a partition. So, the user prefers to not have partitions jumping around when the application starts up. The Event Processor Client can be configured to claim a single partition for each load balancing update interval by using the default `BALANCED` strategy. Moreover, the user can also tune the update interval to suit the application needs.

    * Estimate the percentage of developers using the service who would use the champion scenario - Applications that have expensive initialization and cleanup for processing a partition will prefer to use the default strategy.

    * Link to the code sample - https://gist.github.com/srnagar/366cb66279406db738f8eff82fbfb851#sample-user-code

**Comment by chradek** [comment]
Link to the TypeScript PR for API review: https://github.com/Azure/azure-sdk-for-js/pull/9140

**Comment by ramya-rao-a** [comment]
@kyle-patterson Now that we are done with the meeting for this issue, can we post the conclusions and close it?

**Comment by srnagar** [comment]
This feature is released. Closing the issue.
