### ISSUE TITLE
Change Request: management API within data plane

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk#1360]
## The Basics

* Which design guideline is affected?
This is a request to establish guidelines for the use of management APIs within a data plane library. 
In Service Bus, there is a management client that uses the ATOM XML standard over HTTP. This is separate from the auto-generated ARM client. The ATOM client is scoped to CRUD operations within a particular namespace, whereas ARM can be used across namespaces. Also, the ATOM client allows authenticating with a connection string whereas ARM does not. During the initial implementation of Track 1, there was an attempt to remove the ATOM client (which was around in Track 0), but this was met with much [resistance ](https://github.com/Azure/azure-service-bus-dotnet/issues/65) from the community and it was left in, primarily due to ARM not supporting connection strings. Because of this history, we are planning to go forward with continuing to support the ATOM client in Track 2. 

* Which target languages are affected?
.NET, Java, Python, JS

* Describe the change:
A new guideline that explains under what scenarios management APIs may be included in a data plane library and what conventions should be followed for said management API.
**In particular**:
  * How do we position the real mngmt plane (arm) and such data-plane based mngmt plane APIs?
  * How do we position this new management plance and the data plane?
  * What conventions we would use to communicate to developers the difference in the APIs? E.g. namespace, package, type naming.

## Reasoning
There will likely be other libraries that will want to have management API included in the data plane. It would be good to establish a guideline for how this should be handled to ensure consistency.

**Comment by kyle-patterson** [comment]
Scheduled for 6/1

**Comment by JoshLove-msft** [comment]
The initial outcome of this meeting was that the ARM libraries would append "ARM" into all of their types. After further discussion within the management plane teams, they decided against going with this change as they wanted to maintain continuity with the Track 1 clients. Even if they did change Track 2 to use "ARM", the fact that the Track 1 libraries don't do this could be problematic. Consider the following example within Service Bus. In Track 2, our current data plane "management" client is called `ServiceBusManagementClient`. This is the same exact name as the Track 1 ARM client. If someone is building an app that references both packages, here is what they would see in Intellisense when attempting to new up a client:
![image](https://user-images.githubusercontent.com/54595583/88862341-e7b5ef00-d1b4-11ea-8ecf-c874589730f1.png)

Additionally, users searching the internet for the Track 2 data plane type would find the Track 1 ARM client in the top of the search results for the foreseeable future. 

**As an alternative, I would like to propose that we use "Administration" to name the clients and namespaces for these types of operations that live within the data plane.** For Service Bus, we would end up using the name `ServiceBusAdministrationClient`, and the `Azure.Messaging.ServiceBus.Administration` namespace. Key Vault has taken the lead here in setting this precedent with their new KeyVault Administration [library](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Administration) that lives in the data plane. As more libraries add functionality like this for Track 2, it will be easier for users to transfer knowledge between the Track 2 libraries. Hopefully, we will get to the point where users just expect this convention – Management in the namespace/client name will automatically make them think of ARM, whereas Administration signifies data-plane. This change would mean we would have to be vigilant in preventing `Management` from being used within the data plane for these types of operations. `Manager` could still be used for non-client use cases as in the [StorageManager](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Processor/StorageManager.cs) in Event Hubs (though they should be avoided if possible), or even in the client in cases where the term "management" is idiomatic to the domain (e.g. if it is part of the name of the service).

**Comment by tg-msft** [comment]
I'm personally pushing "Datament plane APIs" for these things that straddle both worlds.  But we've had the same discussions for other services (/cc @christothes as an FYI) and Krzysztof is pushing for "Administration" which I think everyone's leaning toward.

**Comment by johanste** [comment]
`Administration` seem as good as a term as any (unless someone can come up with a shorter name that is not `datament`.

**Comment by bterlson** [comment]
I have no concerns with `Administration` per se, but I'm not sure that another name for management-y operations will reduce confusion for anyone, and could, maybe, add to it.

**Comment by JonathanGiles** [comment]
I'll echo the sentiments from my email here, because they align with Brian's comment above: I worry that a new word is relatively valueless without the context we need to provide to customers to differentiate this from management and non-management libraries. Given the effort of providing this context, I wonder if it just should remain as management? 

However, as Brian also notes, I am not offended by Administration as a name.

**Comment by lilyjma** [comment]
Scheduled for 8/10, 2-2:45.

**Comment by lilyjma** [comment]
[MS internal only][Video](https://msit.microsoftstream.com/video/2540a1ff-0400-a521-b855-f1eadb54ae25)
Conclusion on guidelines: 

1. When possible, add the operations on the data plane client
2. When it's large enough to merit a separate client or assembly, add the operations on a `*AdministrationClient`
3.  No `*ManagementClient` in data planes

**Comment by ramya-rao-a** [comment]
@lilyjma Can you share the notes from this meeting? While the conclusion above helps people who were in the meeting, the notes would help anyone else coming in and trying to understand the discussions we had in the meeting

cc @bterlson because I have a vague recollection that he captured the notes in this meeting

**Comment by lilyjma** [comment]
@ramya-rao-a I think @JoshLove-msft took better notes than I did, so I'm posting them here: 

This issue was discussed with the API review board and here are some of the options that were considered for how to handle this scenario: 
- Keep “Management” but rename the ARM client to “ArmManagement”
    - This is not practical as it would entail changes to an enormous number of existing types for which there is an enormous amount of existing documentation.
- Put these operations on the existing data plane client
    - This is not always practical due to the number of operations and the impact it would have on the API surface of the data plane client
- Use “Administration” in place of “Management”
    - This seems like a decent substitute for Management. The concern is that users will have to learn a new concept, but the alternative of having conflicting names was felt to be even worse.
- Use “Configuration” in place of “Management”
    - There was a concern that this is a bit too narrow and might not give the right impression as to what kind of operations would be available.
 
After discussing this issue, the API review board landed on these guidelines for how to handle management operations within the data plane:
1.	When possible, add the operations on the data plane client
2.	When it's large enough to merit a separate client or assembly, add the operations on a `*AdministrationClient`
3.	No `*ManagementClient` in data planes
