### ISSUE TITLE
Board Review: Tables

### ISSUE THREAD

**Issue by eboyd23** [Azure/azure-sdk#1379]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: TBA
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/storage/tables/
* Contact email (if service team, provide PM and Dev Lead):  tablesdkadp@microsoft.com

## About this client library

* Name of the client library: Tables
* Languages for this review: Java, Python, .NET, JavaScript
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/storageservices/table-service-rest-api

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link: [apiview azure tables](https://apiview.dev/Assemblies/Review/064b274f6dd441e99ced81f2149a9145)
* Link to samples for champion scenarios: [samples](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/tables/azure-data-tables/src/samples/java)

### Python

* Upload the api as a Draft PR.  [Link to PR](https://apiview.dev/Assemblies/Review/011d29dfbc8b4bdcad1cb4f150d50b7b)

* Link to samples for champion scenarios: [samples](https://github.com/LibbaLawrence/azure-sdk-for-python/tree/lilaw_async/sdk/table/azure-table/samples)

## Champion Scenarios
Table Level
* Demonstrate creation and deletion of a table. almost all users
  *  [JavaSync](https://github.com/eboyd23/azure-sdk-for-java/blob/apiView/sdk/tables/azure-data-tables/src/samples/java/TableServiceClientCodeSnippets.java#L23) | [JavaAsync](https://github.com/eboyd23/azure-sdk-for-java/blob/apiView/sdk/tables/azure-data-tables/src/samples/java/TableServiceAsyncClientCodeSnippets.java#L19) | [Python](https://github.com/LibbaLawrence/azure-sdk-for-python/blob/lilaw_table/sdk/table/azure-table/samples/creation_deletion_of_table.py)
*  Demonstrate error handling  existing table. almost all users
    *  [JavaSync](https://github.com/eboyd23/azure-sdk-for-java/blob/apiView/sdk/tables/azure-data-tables/src/samples/java/TableServiceClientCodeSnippets.java#L23) | [JavaAsync](https://github.com/eboyd23/azure-sdk-for-java/blob/apiView/sdk/tables/azure-data-tables/src/samples/java/TableServiceAsyncClientCodeSnippets.java#L19) | [Python](https://github.com/LibbaLawrence/azure-sdk-for-python/blob/lilaw_table/sdk/table/azure-table/samples/table_exists_error_handling.py)
*  Demonstrate listing (I.e. querying) tables. most of users
    *  [JavaSync](https://github.com/eboyd23/azure-sdk-for-java/blob/apiView/sdk/tables/azure-data-tables/src/samples/java/TableServiceClientCodeSnippets.java#L62) | [JavaAsync](https://github.com/eboyd23/azure-sdk-for-java/blob/apiView/sdk/tables/azure-data-tables/src/samples/java/TableServiceAsyncClientCodeSnippets.java#L47) | [Python](https://github.com/LibbaLawrence/azure-sdk-for-python/blob/lilaw_table/sdk/table/azure-table/samples/querying_table.py)
 

Entity Level
* Demonstrate inserting and deleting entity data (including odata types e.g. uuid). almost all users
  *  [JavaSync](https://github.com/eboyd23/azure-sdk-for-java/blob/apiView/sdk/tables/azure-data-tables/src/samples/java/TableServiceClientCodeSnippets.java#L79) | [JavaAsync](https://github.com/eboyd23/azure-sdk-for-java/blob/apiView/sdk/tables/azure-data-tables/src/samples/java/TableServiceAsyncClientCodeSnippets.java#L63) | [Python](https://github.com/LibbaLawrence/azure-sdk-for-python/blob/lilaw_table/sdk/table/azure-table/samples/inserting_deleting_entities.py)
* Demonstrate update/upsert entity data in a table using optimistic concurrency checks. most of users
  *  [JavaSync](https://github.com/eboyd23/azure-sdk-for-java/blob/apiView/sdk/tables/azure-data-tables/src/samples/java/TableServiceClientCodeSnippets.java#L130) | [JavaAsync](https://github.com/eboyd23/azure-sdk-for-java/blob/apiView/sdk/tables/azure-data-tables/src/samples/java/TableServiceAsyncClientCodeSnippets.java#L107) | [Python](https://github.com/LibbaLawrence/azure-sdk-for-python/blob/lilaw_table/sdk/table/azure-table/samples/update_entity.py)
* Demonstrate creating an odata query/listing entities. most of users
  *  [JavaSync](https://github.com/eboyd23/azure-sdk-for-java/blob/apiView/sdk/tables/azure-data-tables/src/samples/java/TableServiceClientCodeSnippets.java#L182) | [JavaAsync](https://github.com/eboyd23/azure-sdk-for-java/blob/apiView/sdk/tables/azure-data-tables/src/samples/java/TableServiceAsyncClientCodeSnippets.java#L157) | [Python](https://github.com/LibbaLawrence/azure-sdk-for-python/blob/lilaw_table/sdk/table/azure-table/samples/create_query_entities.py)

**Comment by lilyjma** [comment]
@eboyd23 : @mayurid  has reached out to request this be scheduled 7/21. Please finish working on the Artifacts Required section as soon as possible so the architects can take a look.

**Comment by lilyjma** [comment]
[MS internal only] [Video](https://msit.microsoftstream.com/video/9013a1ff-0400-a521-bab6-f1eacba2ac99)
