### ISSUE TITLE
Additional spec doc topics

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk#138]
Here is a copy / paste from the common section of the spec doc. Some of these topics are covered, some are not, and there are other topics not listed that need to be covered.

- Tracing
- Versioning
- Authorization (credentials)
- Error/Exception handling
- Packaging (Brian)
- Namespaces (Krzysztof)
- High level structure of APIs (Krzysztof)
- Docs (reference, Samples, Quick Starts) (Jonathan Giles)
- UX Study

- Engineering TOC:
  - Linter
  - Packaging
  - Signing
  - Project Structure
  - Repos
  - License
  - Testing (unit & E2E)
  - Supported versions
  - Platform Support
  - Stress
  - Performance

**Comment by adrianhall** [comment]
These are all included in the general guidelines, or available in a PR at this point.
