### ISSUE TITLE
Request approval to release Text Analytics 1.0.0

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk#1395]
Context:
Service released their 3.0 version API. Our client libraries released a `1.0.0-preview.5` (preview.6 for Python) package on 05/27/2020 with the corresponding changes and support for that service version.

Test have been passing and now we are ready to release `1.0.0`. There are no API changes between releases.

- .NET:
  - [APIView](https://apiview.dev/Assemblies/Review/b196a5e53fa2441f92e3b1accefa35e7)
  - [Readme](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/README.md)
- Java:
  - [APIView](https://apiview.dev/Assemblies/Review/942b652edaf44b7189f41270cf07e54f)
  - [Readme](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/textanalytics/azure-ai-textanalytics/README.md)
- Python:
  - [APIView](https://apiview.dev/Assemblies/Review/f74ef8c4777b408f85dab76b8034cb41)
  - [Readme](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/textanalytics/azure-ai-textanalytics/README.md)
- JS:
  - [APIView](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md)
  - [Draft PR for comments](https://github.com/Azure/azure-sdk-for-js/pull/9304)
  - [Readme](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/textanalytics/ai-text-analytics/README.md)

cc: @KrzysztofCwalina @johanste @bterlson @JonathanGiles
FYI @mayurid @iscai-msft @mssfang @willmtemple

**Comment by bterlson** [comment]
JS looks good! Congratulations for releasing an awesome library! 🎉🎉

**Comment by KrzysztofCwalina** [comment]
Looks good too. Thanks for preparing the library for GA!

**Comment by JonathanGiles** [comment]
Is it 'subcategory' or 'subCategory'? I see differences between the languages: Java and Python are `subcategory` and C# and JS are `subCategory`

**Comment by JonathanGiles** [comment]
In C# I note that the *Input classes derive from `TextAnalyticsInput`, whereas in Java, Python, and JS there is no common type so `Id` and `Text` getters are duplicated on each *Input class. Was there a reason to deviate here?

**Comment by JonathanGiles** [comment]
Other than the comments above and the 'Analyze' typo everywhere (it should obviously be 'Analyse' :-) ), the Java API looks good too.

**Comment by JonathanGiles** [comment]
Oh, and recognize needs changing to recognise too 😄

**Comment by johanste** [comment]
:shipit:

**Comment by JonathanGiles** [comment]
To clarify - nothing I mentioned is ship-blocking, just minor observations and curiosities. And the spelling comments were attempts at humour, not meant to be taken seriously :-)

**Comment by maririos** [comment]
>subcategory and C# and JS are subCategory

Thanks for pointing that out! Will take a look.

> `TextAnalyticsInput` in .NET

We added it after the .NET arch board meeting as an attempt to unify input type. the rest of the v-team didn't feel strongly about this, so we made the change in .NET making sure that user experience across languages is the same.
As an example, if want to detect language in a doc, the input will look like:
```
new DetectLanguageInput("1", "Hello world")
```
[.NET](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/samples/Sample1_DetectLanguage.md#detecting-the-language-of-multiple-documents) - [Java](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/textanalytics/azure-ai-textanalytics/src/samples/java/com/azure/ai/textanalytics/batch/DetectLanguageBatchDocuments.java#L38)

> spelling comments

lol. I actually looked the dictionary wondering if it was one of those instances where my English was wrong :P

=> Thank you!

**Comment by mayurid** [comment]
Thanks board. The crew discussed among themselves as well as based on my chat with Jonathan we decided none of the comments warrant a change late in cycle with the planned GA.
Thank you all for your approval. We will proceed to our release next week

**Comment by maririos** [comment]
Thank you all 😀
