### ISSUE TITLE
Add agent OS verification to all pipelines

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#140]
To prevent accidentally running a build on the wrong agent OS, a step should be added to all jobs which verifies the OS matches what is expected.

One implementation would be a Python script using https://docs.python.org/2/library/sys.html#platform.

**Comment by scbedd** [comment]
`All Pipelines` == "pipelines that have a test strategy involved."

**Comment by mikeharder** [comment]
@scbedd: I would argue the check should be added to every pipeline, unless we really don't care what OS it runs on.  For example, if we want to perform our official builds on Linux, this should be verified in the pipeline.  Otherwise we might unintentionally perform an official build on Windows, which might generate a slightly different package than we intended.

**Comment by scbedd** [comment]
@mikeharder Ok. So on the direct jobs, put the target VM pool in a variable, and refer to it from both there and the `ensure` step? 

Fair enough. I guess that only testing where we've seen issues isn't very proactive. :|

**Comment by chidozieononiwu** [comment]
I created a draft pull request so anyone can look through.
https://github.com/Azure/azure-sdk-for-net/pull/5334

**Comment by weshaggard** [comment]
@mikeharder @scbedd when we were hitting this issue do you know if the predefined variable `Agent.OS` was set correctly? I would hope it is because it is set by the actual agent running on the hosted machine as opposed to the controller that is queuing up the job. If we feel we can trust that I think using that predefined variable in a script and comparing it to our OSName would be the simplest check here.

**Comment by scbedd** [comment]
> @mikeharder @scbedd when we were hitting this issue do you know if the predefined variable `Agent.OS` was set correctly? I would hope it is because it is set by the actual agent running on the hosted machine as opposed to the controller that is queuing up the job. If we feel we can trust that I think using that predefined variable in a script and comparing it to our OSName would be the simplest check here.

Let me see if I I can dig that up on one of the builds that was wonky.

**Comment by mikeharder** [comment]
I would prefer to use an API call at runtime to verify the OS with absolute certainty, rather than relying on a DevOps variable which could be bugged.

**Comment by weshaggard** [comment]
That's fair given the context of what we are trying to guard against we should be careful to trust predefined variables. From a quick set of tests I have at https://dev.azure.com/azure-sdk/playground/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=132 it might be easiest to do this in python, as much as I like powershell the .NET OS detection APIs aren't great. @chidozieononiwu please continue working on the exact script we want to use and I'll work with you on Monday on how to best share it across all our build pipelines.
