### ISSUE TITLE
Board Review: Event Grid

### ISSUE THREAD

**Issue by jfggdl** [Azure/azure-sdk#1405]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Event Grid team.
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/event-grid/ and https://docs.microsoft.com/en-us/azure/event-grid/edge/.
* Contact email (if service team, provide PM and Dev Lead): PM: jafernan@microsoft.com, Dev Lead: rajarv@microsoft.com. Dev: ahamad@microsoft.com 

## About this client library

* Name of the client library:  Event Grid
* Languages for this review: .Net, Java, Python, Node.js, Go.
* Link to the service REST APIs: swagger specs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventgrid/data-plane/Microsoft.EventGrid/stable/2018-01-01/EventGrid.json

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: https://www.nuget.org/packages/Microsoft.Azure.EventGrid/
There are 2 packages under the lib directory:
•	.Net .45.2: Microsoft.Azure.EventGrid.dll
•	Net Standard: Microsoft.Azure.EventGrid.dll

* Link to samples for champion scenarios:
https://docs.microsoft.com/en-us/samples/azure-samples/event-grid-dotnet-publish-consume-events/event-grid-dotnet-publish-consume-events/
https://docs.microsoft.com/en-us/dotnet/api/overview/azure/eventgrid?view=azure-dotnet

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link: https://mvnrepository.com/artifact/com.microsoft.azure/azure-eventgrid
* Link to samples for champion scenarios: https://docs.microsoft.com/en-us/samples/azure-samples/event-grid-java-publish-consume-events/microsoft-azure-event-grid-java-sample/

### Python

* Upload the api as a Draft PR.  Link to PR: 
* Link to samples for champion scenarios: https://docs.microsoft.com/en-us/samples/azure-samples/event-grid-python-public-consume-events/event-grid-python-public-consume-events/

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR:
* Link to samples for champion scenarios: https://docs.microsoft.com/en-us/samples/azure-samples/event-grid-node-publish-consume-events/event-grid-node-publish-consume-events/

## Main customer requirements to be met 
* Cloud event support for publish/consume events.
   Optional fields 
   Added new extension fields by customer
   https://github.com/Azure/azure-sdk-for-net/issues/10684
* Support consuming batch of events, not a single one only.
    https://github.com/Azure/azure-sdk-for-net/issues/10137
* More/update samples:
    https://github.com/Azure-Samples/event-grid-dotnet-publish-consume-events/issues/20
* Improve retry mechanisms for transient failures.
* Leverage the dataplane SDK by 1st party service to publish events based on cert authentication rather than SAS key authentication and have their own http client.
* From a scenario point of view, Event Grid delivers these events to a variety of targets Azure functions,  Event Hubs, Azure queues etc. It would be good to think through on how to leverage these client SDKs inside an azure function to parse http request body and also how this can be used to parse an Event hub event (which is holding a cloud event/grid event json bytes).

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

### Champion Scenario 1: Publish and consume events using (custom) topics.
* Problem statement: How can I publish and/or consume events?
* Description: This scenario covers the way a user meets a common integration requirement in which event needs to be sent by a publisher and being consumed by a client, which in this case is a Azure function.
* Estimate the percentage of developers using the service who would use the champion scenario: 40%+
* Link to the code sample: https://github.com/Azure-Samples/event-grid-dotnet-publish-consume-events. Note: this sample code shows a particular handler (function) of the many supported. Please consult supported handlers. 

### Champion Scenario 2: Publish and consume events using system topics.
* Problem statement: How can I consume control-plane events generated by Azure services?
* Description: This scenario enables end-users to consume events raised by ARM from services that have been integrated (onboarded) to Event Grid. Those services that have been onboarded feature a “Events” blade (bolt icon). An example of a service with this integration is Service Bus. 
* Estimate the percentage of developers using the service who would use the champion scenario: 20%+
* Link to the code sample: Currently there are no samples that showcase the use of Event Grid SDKs to consume events from system topics, but the consumption model of event using system topics is basically the same as custom topic’s webhooks (a type of handler). There is documentation that can shed a light of the value that they provide but the example provided uses Azure Functions and Logic Apps to consume events (not our SDK).

### Champion Scenario 3: Publish and consume events using domain topics.
* Problem statements: How can I publish events to be consumed by a large number of consumers in simple way (one endpoint)? How can I publish events to many consumers who have different selection criteria for those events?
* Description: This scenario enable event-driven architectures at a high-scale by using Event Grid domains which may include many topics that could be published to using a single endpoint: the endpoint of the Event Grid domain.
* Estimate the percentage of developers using the service who would use the champion scenario: 20%+.
* Link to the code sample: https://docs.microsoft.com/en-us/azure/event-grid/how-to-event-domains?tabs=azurecli#publish-events-to-an-event-grid-domain 

### Champion Scenario 4: Consume events using Cloud Events 1.0 schema. 
* Problem statement: How can I consume events using the Cloud Events 1.0 schema?
* Description:  This scenario enable users who favor to use open standards (possibly to communize their implementation among all providers they may use) to consume events using the Cloud Events 1.0 schema.
* Estimate the percentage of developers using the service who would use the champion scenario: 
* Link to the code sample: There are no samples yet as the current SDK is yet to support Cloud Events 1.0 schema.

### Champion Scenario 5: Publish and consume events using partner topics.
* Problem statement: How can I consume events from third-party SaaS providers using Cloud Events specification schema?
* Description:  This scenario allows end-users to consume events generated by third-party publishers using Cloud Events schema 1.0. 
* Estimate the percentage of developers using the service who would use the champion scenario: 
* Link to the code sample: We do not have a specific example, but consuming events from partner topics is similar to consuming events for custom topics. Please see the following documentation that describe how to consume events from Auth0, which is a third-party service. 

### Champion Scenario 6: Handle Dead lettered events.
* Problem statement: How can I process events that were not able to be sent to its destination (dead lettered)?
* Description:  This scenario enables to implement the Dead letter Channel integration pattern.
* Estimate the percentage of developers using the service who would use the champion scenario: 
* Link to the code sample: https://github.com/Azure-Samples/event-grid-dotnet-handle-deadlettered-events

### Champion Scenario 7: Publish and consume events on the edge.

* Problem statement: How can I integrate solutions/modules/services that are deployed in containers?
* Description:  This scenario is used to showcase the way a user can meet requirements to integrate two IoT modules using Event Grid.
* Estimate the percentage of developers using the service who would use the champion scenario: 20%+
* Link to the code sample:  https://github.com/Azure-Samples/azure-iot-edge-event-grid-sample

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by jfggdl** [comment]
By the way, we should include a section for Golang

**Comment by ellismg** [comment]
As part of this introduction, we should try to close on what we believe the namespace will be for this code.  I believe that it will be `Azure.Messaging.EventGrid` (to follow our existing guidelines where we already have a messaging group) but it would be good to close on that so the teams can move forward implementing stuff without having to do a giant re-namspacing later.

**Comment by ellismg** [comment]
In preparation for the today's meeting, I wrote up some of the champion scenarios with examples based on hypothetical designs for a Track 2 in .NET and TypeScript.

https://gist.github.com/ellismg/7e714a574443cdca3d7aa50f9ccfd300
