### ISSUE TITLE
.NET Guidelines TODOs

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk#142]
- [x] Add more justifications and code samples
- [x] Make internal links work
- [x] Principles
- [x] Fold-in general guidelines
- [x] HttpPipeline Usage Guidelines
- [x] Authentication Guidelines
- [x] Packaging Details
- [ ] Compatibility Details

**Comment by Petermarcu** [comment]
@adrianhall is this done?

**Comment by adrianhall** [comment]
Not complete yet - needs more details around compatibility details.

**Comment by adrianhall** [comment]
Actually, this is complete.  #148 has remaining compatibility requirements.
