### ISSUE TITLE
Board Review: Cognitive Search

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk#1428]
*Note: this is a second review after our preview 2, since thenceforth we made many changes - many recommended by the  board.*

## The Basics

* Service team responsible for the client library: Azure SDK team
* Link to documentation describing the service: https://docs.microsoft.com/azure/search/search-what-is-azure-search
* Contact email (if service team, provide PM and Dev Lead): @AlexGhiondea 

## About this client library

* Name of the client library: Cognitive Search
* Languages for this review: .NET, Java, Python, TypeScript
* Link to the service REST APIs: https://docs.microsoft.com/rest/api/searchservice/index-2019-05-06-preview (API will GA as a different version before we do)

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/d40a51d26cf2444a85d302758ca3a2d1
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/search/Azure.Search.Documents/samples

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/8ec9fe08197443d9be23718f8aad5276
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/search/azure-search-documents/src/samples

### Python

* Upload API to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/b8c9d2f3e54d499d80479792af175b1f
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/search/azure-search-documents/samples

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR: https://github.com/sarangan12/azure-sdk-for-js/pull/3
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/search/search-documents/samples

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

*Note: not all languages have all samples yet. We are spending preview 5 getting all these written and unified.*

### Query an index for matching documents
* Target audience: LOG developers (~90%)
* Code samples: [.NET](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/search/Azure.Search.Documents#send-your-first-search-query) | [Java](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/search/azure-search-documents#search-on-hotel-name) | [Python](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/search/azure-search-documents/samples/sample_simple_query.py) | [TypeScript](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/search/search-documents#perform-a-search-on-documents)

### Upload a document to an index
* Target audience: LOB developers (~25%)
* Code samples: [.NET](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/search/Azure.Search.Documents#adding-documents-to-your-index) | [Java](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/search/azure-search-documents#upload-a-document) | [Python](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/search/azure-search-documents#upload-documents-to-an-index) | [TypeScript](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/search/search-documents#upload-documents-into-an-index)

### Create an index
* Target audience: LOG developers (~10%)
* Code samples: [.NET](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/search/Azure.Search.Documents#creating-an-index) | [Java](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/search/azure-search-documents#create-an-index) | [Python](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/search/azure-search-documents#create-an-index) | [TypeScript](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/search/search-documents#create-an-index)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by KrzysztofCwalina** [comment]
.NET looks good. Heath and Ted, thank you for doing great work getting this library shipped!

**Comment by JonathanGiles** [comment]
Java is approved

**Comment by johanste** [comment]
Signed off.

**Comment by heaths** [comment]
@bterlson ?

**Comment by bterlson** [comment]
Signed off for JS as well.

**Comment by heaths** [comment]
Thanks, all!
