### ISSUE TITLE
Board Review: Streaming

### ISSUE THREAD

**Issue by Petermarcu** [Azure/azure-sdk#1431]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Cognitive
* Link to documentation describing the service: NA
* Contact email (if service team, provide PM and Dev Lead): Rob Chambers

This is a high level meeting to raise the boards awareness and discuss streaming as a general concept.

**Comment by robch** [comment]
As requested during meeting... You can find the package locations here: [https://crbn.us/where.md](https://crbn.us/where.md)

**Comment by lilyjma** [comment]
What file: https://crbn.us/what.md

SDK Team Action Items:

1. Language architects take a look at API for what should be changed to accomplish "track 2-ness"
- Example: If don't have Client, still Track 2? What are the trade-offs?
- Define what Track 2 means for library like this in AI space
2. Architects to present some write up
3. Follow up offline to schedule next meeting (tentative date: 7/13/20)

SDK Team needs from Rob's team:
- Pre-Track 2 Layer 2 Carbon Speech SDKs for different languages: direct links to packages in package managers and links to repositories

**Comment by lilyjma** [comment]
Follow up 7/14

[MS internal only] [Video](https://msit.microsoftstream.com/video/1540a1ff-0400-a521-7594-f1eac6268fd1) 

Cognitive Streaming

What "Client" types should library have?
- Consider two layers: lower layer has Client suffix, upper layer with terminology like Recognizer, Synthesizer
- in future, will have option to add low level API
- can start with higher level libraries for the Cognitive streaming space 

If we have no lower level library and completely abstract the networking layer, how will user debug? 
- Currently, there's a Connector object that attempts to solve problem 
- important to have code samples that illustrate error handling and diagnostics, especially in call-back based APIs
- Get more samples of what teams that use APIs like this have done to write resilient code 

JeffR's suggestion -- separation of concerns
1. Client responsible for all network traffic related things 
2. Build richer type on top that might do local operations or might do operations over the network
Could build local operation only type and over the network operation only type and have yet another that abstracts the two away 
Current problem: no library that handles the web socket aspect well (JR, C++ team building that)

HTTP Pipeline 
- think about what features (logging, retries, telemetry, etc.) mean in context of Streaming library and attempt to make them similar to pluggable pipeline 
- JR and KC: need design guidelines for standards web socket operations 

(KC's request to JR: post mortem on MQTT)


**Authentication** 
For cognitive services: some support AAD, some don't
Need Rob to follow up if AAD is a component being worked on as part of the Auth story

**Overall library concerns** 

JS concerns

- Library feels like it's written by C# dev 
- Ryan to sync with Brian on high level issues to make library more JS 
- Avoid native library 

Python concerns

- Big binary dependency/native library 
- Only publish wheels, which means can't use Speech SDK on things like Raspberry pi 
- Eventing not a common pattern 
- No async support 
- Repo unconventional - expected to be able to install from source 
- Looking into supporting WAVE or not 
- Making streams streamlike
- There could be other more pythonic like patterns than callbacks

- Native dependencies
- Seems to be good trade off to share a native library amongst 4 languages, but python and JS don't seem to work well with this 
- Also resource and funding considerations (6 languages and feature adding in future costly)
- To discuss with Johan why native dependency will not make user experience great

C# Concern
- Krzysztof suggests everything be done through message passing except for client connection
    - Recognizer disposable (and maybe Connnection object) but nothing else 
- Speech library in base 64 implementation only, which doesn't provide good ux 
    - Rob confirms plan to do it in any mode 

Separate packaging for xamarin and unity 
- guidelines for this too 

Java concern: 

- package not in maven central
- Plan is to build separate JRE library and Android library
