### ISSUE TITLE
Board Review: Protocol abstraction

### ISSUE THREAD

**Issue by Petermarcu** [Azure/azure-sdk#1432]
Thank you for contributing to the design guidelines for Azure SDKs.  We welcome all discussions and contributions.  Since the design guidelines affect the client libraries for all Azure services, we thoroughly discuss and vet any design guideline changes before we incorporate them into the official guidance.  This process can take some time, so your patience is appreciated.

** Before submitting, ensure you adjust the title of the issue appropriately **

## The Basics

* Which design guideline is affected?
Right now our API's expose the protocol underneath. For certain scenarios, that needs to be swappable or run locally instead of calling the cloud. Cognitive will come and talk about their plans in this context and discuss the best way to give guidelines for this layer.

* Which target languages are affected?
All

Invite Rob Chambers as the presenter.

**Comment by lilyjma** [comment]
What file: https://crbn.us/what.md

SDK Team Action Items:

1. Language architects take a look at API for what should be changed to accomplish "track 2-ness"
- Example: If don't have Client, still Track 2? What are the trade-offs?
- Define what Track 2 means for library like this 
2. Architects present some write up
3. Follow up offline to schedule next meeting (tentative date: 7/13/20)

SDK Team needs from Carbon Team: 
- Track 1 speech libraries for different languages: direct links to packages in package managers and links to repositories

**Comment by robch** [comment]
For these discussions, let's refer to existing speech libraries (aka Carbon Speech SDK) as pre-Track 2 Layer 2, or pre-Track 3.

As requested during meeting... You can find the package locations here: [https://crbn.us/where.md](https://crbn.us/where.md)
