### ISSUE TITLE
Board Review: App service Authentication

### ISSUE THREAD

**Issue by navyasric** [Azure/azure-sdk#1433]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Microsoft.Identity.Web, MS Graph SDK, Azure Identity SDK
* Link to documentation describing the service: [App service authentication](https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization)
* Contact email (if service team, provide PM and Dev Lead): Identity PMs: nacanuma@microsoft.com, jmprieur@microsoft.com, stsoneff@microsoft.com; App service PMs: mahender@microsoft.com; MS Graph SDK PM: Darrel.Miller@microsoft.com; Azure SDKs: sschaab@microsoft.com

## About this client library

* Name of the client library: Microsoft.Identity.Web, Azure.Identity, Microsoft.Graph.Core
* Languages for this review: .NET
* Link to the service REST APIs: [API mocks deck](https://microsoft.sharepoint.com/:p:/t/activedirectory/EcJ1tTNo5BZIt78bBUkE3ngBsZeYznKEiB_XN2j-AOzqeA?e=Nn9j37)

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link:
* Link to samples for champion scenarios: [API mocks deck](https://microsoft.sharepoint.com/:p:/t/activedirectory/EcJ1tTNo5BZIt78bBUkE3ngBsZeYznKEiB_XN2j-AOzqeA?e=Nn9j37)
[Sample to call Microsoft Graph from Webapp using App service auth](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/WebAppCallsMicrosoftGraph)

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link:
* Link to samples for champion scenarios:

### Python

* Upload the api as a Draft PR.  Link to PR:
* Link to samples for champion scenarios:

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR:
* Link to samples for champion scenarios:

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

**Champion Scenario 1: Get claims for user signed in with App service authentication in a webapp**
    * App Service passes user claims to your application by using special headers. External requests aren't allowed to set these headers, so they are present only if set by App Service. Code that is written in any language or framework can get the information that it needs from parsing these headers.
    * Problem: There is support for .NET framework to populate an object with the claims from the header. The same experience is missing for .NET core and other languages(Java, Python, Node...). The proposal is for Microsoft.Identity.Web SDK for .NET core to detect the App service authentication and populate the object. 
    * Estimate the percentage of developers using the service who would use the champion scenario: 
    * Link to the code sample: https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-auth-aad

**Champion Scenario 2: Access Microsoft Graph API (and other APIs) from App service webapp as the signed in user**
    * Technically it is possible to use the token passed by App Service in special headers to call MS Graph. The developer needs to extract the token from header and add it as bearer to the HTTP request to Graph API. .
    * Problem: No well documented pattern exists of calling the MS Graph API from an App Service. There is no library or middleware supporting this. Proposal is to provide this integration through Microsoft.Identity.Web for ASP.NET and later extend the patterns to other languages. 
    * Estimate the percentage of developers using the service who would use the champion scenario
    *  Link to the code sample: https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-auth-aad

**Champion Scenario 3: Access Azure APIs(ex: Azure Storage) and Microsoft Graph API as the App service webapp using Managed Identities**
    * The pattern using DefaultAzureCredential in Azure.Identity SDK is already used and adopted by Azure services such as Storage, KeyVault, etc. 
    * Problem: Use of managed identities to get tokens for MS Graph API is not documented and no SDK pattern exists. Proposal is to use the above pattern with Graph SDK.
    * Estimate the percentage of developers using the service who would use the champion scenario
    * Link to the code sample: https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi#net-code-example-create-a-block-blob

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
[Microsoft Internal only] https://msit.microsoftstream.com/video/71e9a3ff-0400-a521-231e-f1eabb20aa12

Follow ups: 
- How is EasyAuth like if developer runs service locally?
- Dependency injection support in Graph SDK in relation to ASP.NET, align with pattern on Azure SDK side 
- Timeline of Azure Identity to support what App Authentication supports. 
    - What's not supported now: KeyVault token provider; SQL provider; Windows integrated auth
- Scenario: app accessing on behalf of user vs app accessing as itself 
   - User impersonation credential -- would this be part of default azure credential? 
   - Consider to separate: unclear what default azure credential should do in case of having a managed identity assigned to app service but user also signs in

**Comment by lilyjma** [comment]
@navyasric: is it okay to close this?
