### ISSUE TITLE
Board Review: Using Antlr4.Runtime.Standard as a Cosmos dependency for .NET

### ISSUE THREAD

**Issue by bchong95** [Azure/azure-sdk#1435]
## The Basics

Cosmos would like to add Anltr's runtime as a dependency for .NET.

* Service team responsible for the client library: Cosmos
* Link to documentation describing the service: https://www.nuget.org/packages/Antlr4.Runtime.Standard/
* Contact email (if service team, provide PM and Dev Lead): Cosmos

## Champion Scenarios

* Query Planning
    * Describe the champion scenario: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1609
    * Estimate the percentage of developers using the service who would use the champion scenario : 50%
    * Link to the code sample : https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1609

**Comment by tg-msft** [comment]
Can you look into the versioning history and breaking change policies of the Antlr4.Runtime.Standard library so we can get a better understanding of how this would impact versioning of the Cosmos client library?  And check for any other popular projects that use Antlr4.Runtime.Standard?  I'd like to make sure we're not signing ourselves up for a diamond dependency problem in the future.

**Comment by bchong95** [comment]
They haven't had a breaking change in the last 2 years:

https://www.nuget.org/packages/Antlr4.Runtime.Standard/4.8.0

I am also okay with pinning Cosmos Client to a particular version for the rest of it's life, since I don't for see needing new features on a parser (kind of solved problem). 

Antlr 4 is a very popular parser library:

https://github.com/antlr/antlr4

Here is the github list of places it is used by:

https://github.com/antlr/antlr4/network/dependents?package_id=UGFja2FnZS0xNjE2OTk4Ng%3D%3D

**Comment by lilyjma** [comment]
@bchong95 : is it okay to close this?
