### ISSUE TITLE
Change Request: Exposing information about the authentication method when a library supports many

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk#1436]
## The Basics

* _Which design guideline is affected?_

  [The authentication guideline that says:](https://azure.github.io/azure-sdk/general_implementation.html#authentication)

  > **DO NOT** persist, cache, or reuse security credentials. Security credentials should be considered short lived to cover both security concerns and credential refresh situations.

  Is what I consider the basis of why we don't expose credentials on clients.

* _Which target languages are affected?_

  All.

* _Describe the change:_

  For client libraries that support different authentication methods and certain operations that are only relevant with a subset of authentication methods, we should have a uniform approach to communicating how the client is authenticating so customers can write general purpose code [using the tester-doer pattern.](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-versioning-feature-flags)

## Reasoning

We're uncomfortable having Storage clients generate signed SAS tokens because it's only valid if they're using Shared Key.  If they're using AAD, they'll have to make a request to get a delegation key first.  If they're using SAS or Anonymous auth, it's an error.  So we feel like we can't solve the problem generally and it's up to customers.

But how do our libraries help customers do that themselves?  `BlobServiceClient.GetUserDelegationKeyAsync` only makes sense when you're using AAD.  General purpose code can't tell whether it's safe to call that method without doing private reflection on `BlobServiceClient` or sending the request and waiting for an error.  Instead we should provide a `public enum BlobClientAuthentication { Anonymous  = 0, SharedKey, Token, SharedAccessSignature}`.  It doesn't expose the credential or violate the Authentication guideline but allows us to use the tester-doer pattern with auth-specific operations.

I think we should come up with a pattern for exposing the authentication method on clients that allow multiple forms.  For .NET, I would expect an enum named `FooClientAuthentication` that matched `FooClientOptions` and one entry in the enum per allowed credential type.  The names of enum values should be `Bar` when the customer uses a `BarCredential` for that authentication method.

If we add this support, it would be good to reconsider the ability to sign SAS tokens in our Storage libraries.  Instead of throwing with a message that's not useful, we could throw and tell customers they need to check their `ClientAuthentication` property because only `SharedKey` allows you to sign SAS tokens.

**Comment by seanmcc-msft** [comment]
Related - https://github.com/Azure/azure-sdk-for-net/issues/12891

**Comment by tg-msft** [comment]
After discussing with the Arch Board, we've decided instead to use the [tester/doer pattern](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-versioning-feature-flags) for authentication related capabilities.  Rather than an auth enum where customers have to associate auth to operations, we'll provide flags like `CanGenerateSasUri` or `CanCallGetUserDelegationKey` that are specific to methods like `GenerateSasUri` or `GetUserDelegationKey`.

@amnguye has a great plan to make this work for signing SAS tokens from a `BlobClient`.
