### ISSUE TITLE
Update repo structures

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#144]
See https://github.com/Azure/adx-documentation-pr/pull/134 where I've put together a proposal once that has general agreement I'll file individual issues in each repo to make the changes.

**Comment by weshaggard** [comment]
https://github.com/Azure/azure-sdk/pull/186

**Comment by weshaggard** [comment]
The repo structure outline can be found at https://github.com/Azure/azure-sdk/blob/master/docs/engineering-system/repo-structure.md

**Comment by kurtzeborn** [comment]
This is done!!!
