### ISSUE TITLE
Replace whitelist term for allowList in c and go documentation

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk#1442]
I put them together as the same sentence is in both:
- golang: https://github.com/Azure/azure-sdk/blob/master/docs/golang/design.md#logging
- clang: https://github.com/Azure/azure-sdk/blob/master/docs/clang/implementation.md#logging

**Comment by JeffreyRichter** [comment]
@barcharcraz : I fixed the golang logging. Can you fix the C guideline docs. For C, please remove the guideline bullet entirely about white list. And the other bullets about Warning & error don't make sense for us either. Can you update the guidelines to match what we actually do in C? See https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/core/az_core/inc/az_log.h.

Feel free to discuss with me or someone else on the Azure C SDK team on how best to write the logging guidelines if you'd like help.

Thanks.
