### ISSUE TITLE
Change Request: Release notes policy to re-arrange the headers

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk#1448]
## The Basics

* Which design guideline is affected?
Release notes policy

* Which target languages are affected?
All

* Describe the change with reasoning:
  - Use  `Breaking changes since last preview` instead of `Breaking changes`, the former sounds less alarming.
  - Have `New features` appear first before breaking changes. 
     - Convince the user why they should upgrade first and then tell them the breaking changes they should look out for if they choose to upgrade.
  - Have a one liner under each service calling out whether the release is a first time GA, or another preview or an update over a GA. 
    - We do call this out in the beginning. But, people who would generally skip the initial wall of text and go to the headers would have nothing in the individual section telling them whether it is a preview or not.

Please provide any additional detail or reasoning for the request.

**Comment by ramya-rao-a** [comment]
cc @adrianhall as you wrote the initial release notes policy :)

**Comment by ramya-rao-a** [comment]
cc @czubair

**Comment by czubair** [comment]
This is fine Ramya on my end, @ramya-rao-a.
