### ISSUE TITLE
Board Review: Azure.Core.Experimental Spatial, Serialization, and BinaryData features for .NET

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk#1454]
## The Basics

We've got experimental features for Azure.Core that we'd like to review.

* Service team: The ADP .NET folks
* ApiView: https://apiview.dev/Assemblies/Review/8f2e023e377f4627a4ec815f6e11d013
* Contact: @pakrym, @JoshLove-msft, and @KrzysztofCwalina 

#### Expose spatial computing types
Services like Search, Tables, and Cosmos support spatial data in a the standard GeoJSON format.  Search needs to be able to have Points as members of its models and allow Polygons for submitting queries like "find all documents whose location property is in this polygon."  The [Azure.Core.Spatial namespace](https://apiview.dev/Assemblies/Review/8f2e023e377f4627a4ec815f6e11d013#Azure.Core.Spatial) provides these types.

#### Allow custom serializers
We’re introducing a Bring Your Own Serializer model because there a lot of customers who wont come to Track 2 without it.  [`ObjectSerializer`](https://apiview.dev/Assemblies/Review/8f2e023e377f4627a4ec815f6e11d013#Azure.Core.ObjectSerializer) is the base abstraction.  We’re shipping [`JsonObjectSerializer : ObjectSerializer`](https://apiview.dev/Assemblies/Review/8f2e023e377f4627a4ec815f6e11d013#Azure.Core.JsonObjectSerializer) to wrap using `System.Text.Json`.  As a customer you’ll still use all the `System.Text.Json` attributes, naming policies, options, documentation, etc., for your type `T`.  You’ll just tell our client libraries which serializer you’re using via `clientOptions.Serializer = new JsonObjectSerializer(new System.Text.Json.JsonSerializerOptions(...))` and we’ll use it for all your custom model types in our clients.  [You can see more example usage in the tests.](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core.Experimental/tests/JsonObjectSerializerTest.cs)

#### Add a BinaryData abstraction
In Service Bus, in order to specify the body of the message, the user passes in a `ReadOnlyMemory<byte>` to the constructor of `ServiceBusMessage`.  Based on our UX study feedback, users expected to be able to create a message from a `string` as well.  In order to support this in Service Bus and potentially other libraries, we are trying out a [`BinaryData`](https://apiview.dev/Assemblies/Review/8f2e023e377f4627a4ec815f6e11d013#Azure.Core.BinaryData) type that holds binary data and can support moving data to/from `string`s, `byte[]`s, or custom user types `T`.  [You can see more example usage in the tests.](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core.Experimental/tests/BinaryDataTests.cs)

**Comment by tg-msft** [comment]
+@alzimmermsft who's looking at the same areas from the Java side

**Comment by JonathanGiles** [comment]
Can you give more detail about the intended support level and lifetime of code that is in the experimental namespace? My assumption would be that there is no guarantee of no breaking changes and that features will move in and out of the package at will. This would also imply there is no intention for a deprecation or support policy of this namespace. Does that match up with your thinking?

**Comment by tg-msft** [comment]
Azure.Core.Experimental is the neverland of packages where every API refuses to grow up and stays in Preview forever.  When we think we've vetted an API well enough, we'll move it into Azure.Core as GA.  This avoids customer confusion around simultaneously shipping GA and Preview versions of Azure.Core with different sets of features available.

This review is about moving Spatial types, ObjectSerializer, and BinaryData from Azure.Core.Experimental into Azure.Core.  Spatial types are the top priority because they're limiting very important Search scenarios.

**Comment by lilyjma** [comment]
[Microsoft Internal Only] https://msit.microsoftstream.com/video/79c8a3ff-0400-a521-bad4-f1eabbef2db9

Follow ups coming up soon...
