### ISSUE TITLE
Create distribution lists for build results per language

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#146]
Create a distribution list to receive email build results for each language.  People can join the mailing list(s) for the build results they're interested in.

**Comment by kurtzeborn** [comment]
This issue mentions build contact lists, but the same lists should be used for build and test I think.

**Comment by danieljurek** [comment]
Closing this issue, we have alerts for nightly live test pipeline failures in place today. 

We can revisit this if we need to alert on nightly unified pipeline build/test failures as well.
