### ISSUE TITLE
MSDocs links don't point preview content

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#1472]
For Azure.Identity we have 1.2.0-preview.4, but when I click on the related MS Docs link, it takes me to 1.1.1.

It should take me to the preview docs.

![image](https://user-images.githubusercontent.com/2163001/85208236-8f511f00-b2e3-11ea-9656-67e4ba95c8fe.png)

https://docs.microsoft.com/en-us/dotnet/api/overview/azure/Identity-readme?view=azure-dotnet

![image](https://user-images.githubusercontent.com/2163001/85208243-97a95a00-b2e3-11ea-9e3e-94b1282407d6.png)

This should be true for all langs.

azsdke2e

**Comment by weshaggard** [comment]
@scbedd @maggiepint please correct me if I'm wrong but as far as I know the msdocs are not versioned even though they have the version number in the readme there isn't any great way for me to generate a versioned link to get the correct content correctly.

**Comment by scbedd** [comment]
Actually. We can point to the preview readmes except for .NET. .NET MAY be possible but I don't know how to abuse the docs.ms publishing/pipelines to get what we want. 

For Java, JS, and Python. You absolutely can. The trick is to 1) tag in the preview moniker 2) mention `-pre`

Example: https://docs.microsoft.com/en-us/javascript/api/overview/azure/identity-readme-pre?view=azure-node-preview

For each language, the preview moniker is:
- Java - `azure-java-preview`
- Python - `azure-python-preview` 
- JS - `azure-node-preview`

We're gonna be missing a lot _right now_, but I have scripts to enable us to fill these in.

**Comment by weshaggard** [comment]
Ok I can definitely point preview packages at the preview URL's and the GA at the GA URL's however there is still no guarantee that the versions on each match what is in the package index.

**Comment by scbedd** [comment]
That is true. It will be eventually consistent though. I'll ping you later today to have a quick discussion.

**Comment by weshaggard** [comment]
Assigned to you @scbedd as you are working on it in https://github.com/Azure/azure-sdk/pull/1495.
