### ISSUE TITLE
Automatically Filed PRs should tag the PRs with the user who started release

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#1494]
OR at the very least, we should be tagging the users onto the submitted readmes. Whether that it's:

- `ServiceDirectory` of the release, combined with `CodeOwners`
- The One who queued the release
    - If can take advantage of the same methodology that @danieljurek uses to resolve ms to github ID this is the best option

**Comment by danieljurek** [comment]
It'd be easy enough to query in the other direction (from the Microsoft alias of the person who started the request to their GitHub alias) ... 

Here's where we do it for resolving aliases to synchronize into contact groups: 
https://github.com/Azure/azure-sdk-tools/blob/master/tools/notification-configuration/github-codeowner-subscriber/GitHubNameResolver.cs

**Comment by scbedd** [comment]
[Reference](https://github.com/Azure/azure-sdk-tools/blob/master/eng/pipelines/notifications.yml) For appropriate reference material on org side.
