### ISSUE TITLE
Add Verification to Docs CI to detect Un-referenced readme files

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#1509]
Working through the missing links discovered [here](https://github.com/Azure/azure-sdk/pull/1495)

I have discovered that just because a readme is _present_ doesn't necessarily mean that it exists _attached to the ToC_. It's very possible to load the readme, but then the ToC does not render properly. [Here's an example.](https://docs.microsoft.com/en-us/java/api/overview/azure/core-readme?view=azure-java-stable)

### Jobs For Updates 

- [ ] Python
   - [ ] Latest
   - [ ] Preview
- [ ] Java
- [ ] .NET
- [ ] JavaScript
   - [ ] Latest
   - [ ] Preview

**Comment by danieljurek** [comment]
Orphan README files break context in the ToC. This tool should help make sure that all README files are attached to the ToC.

Checking unified might not be enough... may need to check latest and preview.
