### ISSUE TITLE
Extend Readme Automation to include Service Level Readmes

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#1510]
From a discussion with @ramya-rao-a 

> For example, in case of Event Hubs in JS,  https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/eventhub/event-hubs/README.md is the read me for the package and https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/eventhub/README.md is the readme one level above.

Currently the latter case does not happen. Need to crib off of `serviceDirectory` and check for a readme there to replace the `<service>-index.md` in the doc repo.

**Comment by sima-zhu** [comment]
Looking into the issue.

**Comment by sima-zhu** [comment]
We currently only update the readme in sdk package when release. We are not able to find the service level readme from published artifact. Have to think about how to put service directory readme into artifacts.

**Comment by danieljurek** [comment]
We are working on a service-level overview page format with Grouped ToC work in JS.
