### ISSUE TITLE
Update All Releases Page to include links to Source and Docs

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#1538]
Right now, this page https://azure.github.io/azure-sdk/releases/latest/all/index.html and all other "all" pages, don't have links to source and docs.  We have a customer request to add source and docs links there. 

This would be good to include from the perspective of an Azure developer, they want to find packages, source, and docs for all SDKs, no just the new ones.

This will be a manual task and can be pulled from the SDK inventory work that we have done.

Tasks: 

- [x] 1. Merge both "all" and "latest" into a single csv file solution and type each item with Data, Mgmt, or blank. @weshaggard 

- [ ] 2. Manually update the "non New" SDKs with links to source and docs pulled from SDK Inventory. @tzhanl 

azsdke2e

**Comment by weshaggard** [comment]
Task 1 done with https://github.com/Azure/azure-sdk/pull/1591.

**Comment by jongio** [comment]
This is complete.
