### ISSUE TITLE
API Proposal: Add DeviceStream APIs to IoT Hub SDKs (.NET)

### ISSUE THREAD

**Issue by wickste** [Azure/azure-sdk#154]
# Overview
Azure IoT Hub device streams facilitate the creation of secure bi-directional TCP tunnels for a variety of cloud-to-device communication scenarios. A device stream is mediated by an IoT Hub streaming endpoint which acts as a proxy between your device and service endpoints. This setup is especially useful when devices are behind a network firewall or reside inside of a private network. As such, IoT Hub device streams help address customers' need to reach IoT devices in a firewall-friendly manner and without the need to broadly opening up incoming or outgoing network firewall ports. Using IoT Hub device streams, devices remain secure and will only need to open up outbound TCP connections to IoT hub's streaming endpoint over port 443. Once a stream is established, the service-side and device-side applications will each have programmatic access to a WebSocket client object to send and receive raw bytes to one another. The reliability and ordering guarantees provided by this tunnel is on par with TCP.

# Device Stream Workflow
A device stream is initiated when the service requests to connect to a device by providing its device ID. This workflow particularly fits into a client/server communication model, including SSH and RDP, where a user intends to remotely connect to the SSH or RDP server running on the device using an SSH or RDP client program.
The device stream creation process involves a negotiation between the device, service, IoT hub's main and streaming endpoints. While IoT hub's main endpoint orchestrates the creation of a device stream, the streaming endpoint handles the traffic that flows between the service and device.
## Device stream creation flow
Programmatic creation of a device stream using the SDK involves the following steps:
1. The device application invokes the async method to receive a new device streaming request. Internally this causes the device client to establish the AMQP links or subscribe to the MQTT topic for stream requests if they have not been established yet.
2. The service-side program initiates a device stream when needed by providing the device ID (not the IP address).
3. IoT hub notifies the device-side program by invoking the callback registered in step 1. The device may accept or reject the stream initiation request. This logic can be specific to your application scenario. If the stream request is rejected by the device, IoT Hub informs the service accordingly; otherwise, the steps below follow.
4. The device creates a secure outbound TCP connection to the streaming endpoint over port 443 and upgrades the connection to a WebSocket. The URL of the streaming endpoint as well as the credentials to use to authenticate are both provided to the device by IoT Hub as part of the request sent in step 3.
5. The service is notified of the result of device accepting the stream and proceeds to create its own WebSocket client to the streaming endpoint. Similarly, it receives the streaming endpoint URL and authentication information from IoT Hub.

In the handshake process above:
* The handshake process must complete within 60 seconds (step 2 through 5), otherwise the handshake would fail with a timeout and the service will be notified accordingly.
* After the stream creation flow above completes, the streaming endpoint will act as a proxy and will transfer traffic between the service and the device over their respective WebSockets.
* Device and service both need outbound connectivity to IoT Hub's main endpoint as well as the streaming endpoint over port 443. The URL of these endpoints is available on Overview tab on the IoT Hub's portal.
* The reliability and ordering guarantees of an established stream is on par with TCP.
* All connections to IoT Hub and streaming endpoint use TLS and are encrypted.

## Termination Flow
An established stream terminates when either of the TCP connections to the gateway are disconnected (by the service or device). This can take place voluntarily by closing the WebSocket on either the device or service programs, or involuntarily in case of a network connectivity timeout or process failure. Upon termination of either device or service's connection to the streaming endpoint, the other TCP connection will also be (forcefully) terminated and the service and device are responsible to re-create the stream, if needed.

# SDK Availability
Two sides of each stream (on the device and service side) use the IoT Hub SDK to establish the tunnel. During public preview, customers can choose from the following SDK languages:
* The C and C# SDK's support device streams on the device side.
* The Node.js and C# SDK support device streams on the service side.

# Sample Code (C#)
This echo sample demonstrates programmatic use of device streams to send and receive bytes between service and device applications.

## Service Sample Code (C#)
Full sample project [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Quickstarts/device-streams-echo/service)

**Prerequisite** (using the existing API): Create a ServiceClient instance using your IoTHub connection string and desired transport type: 
```C#
using (ServiceClient serviceClient = ServiceClient.CreateFromConnectionString(s_connectionString, s_transportType))
{
    var sample = new DeviceStreamSample(serviceClient, s_deviceId);
    sample.RunSampleAsync().GetAwaiter().GetResult();
}
```

Sample code for new Device Stream functionality ([DeviceStreamingCommon ](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Quickstarts/common/DeviceStreamingCommon.cs)is a convenience helper in the sample app):
```C#
public async Task RunSampleAsync()
{
    try
    {
        DeviceStreamRequest deviceStreamRequest = new DeviceStreamRequest(streamName: "TestStream");

        DeviceStreamResponse result =
          await _serviceClient.CreateStreamAsync(_deviceId, deviceStreamRequest).ConfigureAwait(false);

        Console.WriteLine("Stream response received: Name={0} IsAccepted={1}",
                          deviceStreamRequest.StreamName, result.IsAccepted);

        if (result.IsAccepted)
        {
            using (var cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromMinutes(1)))
            using (var stream = await DeviceStreamingCommon.GetStreamingClientAsync(
                                             result.Url,
                                             result.AuthorizationToken,
                                             cancellationTokenSource.Token).ConfigureAwait(false))
            {
                byte[] sendBuffer = Encoding.UTF8.GetBytes("Streaming data over a stream...");
                byte[] receiveBuffer = new byte[1024];

                await stream.SendAsync(sendBuffer,
                                       WebSocketMessageType.Binary,
                                       true,
                                       cancellationTokenSource.Token).ConfigureAwait(false);

                Console.WriteLine("Sent stream data: {0}",
                                  Encoding.UTF8.GetString(sendBuffer, 0, sendBuffer.Length));

                var receiveResult =
                    await stream.ReceiveAsync(receiveBuffer, cancellationTokenSource.Token).ConfigureAwait(false);

                Console.WriteLine("Received stream data: {0}",
                                  Encoding.UTF8.GetString(receiveBuffer, 0, receiveResult.Count));
            }
        }
        else
        {
            Console.WriteLine("Stream request was rejected by the device");
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine("Got an exception: {0}", ex);
        throw;
    }
}
```

## Device Sample Code (C#)
Full sample project [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Quickstarts/device-streams-echo/device)

**Prerequisite** (using the existing API): Create a DeviceClient instance using your device connection string and desired transport type: 
```C#
using (DeviceClient deviceClient = DeviceClient.CreateFromConnectionString(s_deviceConnectionString, s_transportType))
{
    var sample = new DeviceStreamSample(deviceClient);
    sample.RunSampleAsync().GetAwaiter().GetResult();
}
```

Sample code for new Device Stream functionality ([DeviceStreamingCommon ](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Quickstarts/common/DeviceStreamingCommon.cs)is a convenience helper in the sample app):
```C#
public async Task RunSampleAsync(bool acceptDeviceStreamingRequest)
{
    byte[] buffer = new byte[1024];

    using (var cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromMinutes(5)))
    {
        DeviceStreamRequest streamRequest =
          await _deviceClient.WaitForDeviceStreamRequestAsync(cancellationTokenSource.Token).ConfigureAwait(false);

        if (streamRequest != null)
        {
            if (acceptDeviceStreamingRequest)
            {
                await _deviceClient.AcceptDeviceStreamRequestAsync(
                            streamRequest,
                            cancellationTokenSource.Token).ConfigureAwait(false);

                using (ClientWebSocket webSocket = await DeviceStreamingCommon.GetStreamingClientAsync(
                                              streamRequest.Url,
                                              streamRequest.AuthorizationToken,
                                              cancellationTokenSource.Token).ConfigureAwait(false))
                {
                    WebSocketReceiveResult receiveResult =
                      await webSocket.ReceiveAsync(new ArraySegment<byte>(buffer, 0, buffer.Length),
                                                   cancellationTokenSource.Token).ConfigureAwait(false);
                    Console.WriteLine("Received stream data: {0}",
                                      Encoding.UTF8.GetString(buffer, 0, receiveResult.Count));

                    await webSocket.SendAsync(new ArraySegment<byte>(buffer, 0, receiveResult.Count),
                                              WebSocketMessageType.Binary,
                                              true,
                                              cancellationTokenSource.Token).ConfigureAwait(false);
                    Console.WriteLine("Sent stream data: {0}",
                                      Encoding.UTF8.GetString(buffer, 0, receiveResult.Count));

                    await webSocket.CloseAsync(WebSocketCloseStatus.NormalClosure,
                                               String.Empty,
                                               cancellationTokenSource.Token).ConfigureAwait(false);
                }
            }
            else
            {
                await _deviceClient.RejectDeviceStreamRequestAsync(streamRequest, cancellationTokenSource.Token).ConfigureAwait(false);
            }
        }

        await _deviceClient.CloseAsync().ConfigureAwait(false);
    }
}
```
# New API Surface added (C#)
## IoTHub Service SDK
Note: [ServiceClient ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.serviceclient?view=azure-dotnet)is an existing type. The below APIs are the new additions to this type.
```C#
namespace Microsoft.Azure.Devices {
  public class DeviceStreamRequest {
    public DeviceStreamRequest(string streamName);
    public TimeSpan ConnectionTimeout { get; }
    public TimeSpan ResponseTimeout { get; }
    public string StreamName { get; }
  }
  public class DeviceStreamResponse {
    public DeviceStreamResponse(string streamName, bool isAccepted, string authorizationToken, Uri streamingGatewayUri);
    public string AuthorizationToken { get; }
    public bool IsAccepted { get; }
    public string StreamName { get; }
    public Uri Url { get; }
  }
  public abstract class ServiceClient : IDisposable {
    public abstract Task<DeviceStreamResponse> CreateStreamAsync(string deviceId, DeviceStreamRequest deviceStreamRequest);
    public abstract Task<DeviceStreamResponse> CreateStreamAsync(string deviceId, DeviceStreamRequest deviceStreamRequest, CancellationToken cancellationToken);
    public abstract Task<DeviceStreamResponse> CreateStreamAsync(string deviceId, string moduleId, DeviceStreamRequest deviceStreamRequest);
    public abstract Task<DeviceStreamResponse> CreateStreamAsync(string deviceId, string moduleId, DeviceStreamRequest deviceStreamRequest, CancellationToken cancellationToken);
  }
}

```

## IoTHub Device SDK
Note: [DeviceClient ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.deviceclient?view=azure-dotnet)and [ModuleClient ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.moduleclient?view=azure-dotnet)are existing types. Below APIs are the new additions to these types.
```C#
namespace Microsoft.Azure.Devices.Client {
  public sealed class DeviceClient : IDisposable {
    public Task AcceptDeviceStreamRequestAsync(DeviceStreamRequest request);
    public Task AcceptDeviceStreamRequestAsync(DeviceStreamRequest request, CancellationToken cancellationToken);
    public Task RejectDeviceStreamRequestAsync(DeviceStreamRequest request);
    public Task RejectDeviceStreamRequestAsync(DeviceStreamRequest request, CancellationToken cancellationToken);
    public Task<DeviceStreamRequest> WaitForDeviceStreamRequestAsync();
    public Task<DeviceStreamRequest> WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken);
  }
  public sealed class DeviceStreamRequest {
    public DeviceStreamRequest(string requestId, string name, Uri url, string authorizationToken);
    public string AuthorizationToken { get; }
    public string Name { get; }
    public string RequestId { get; }
    public Uri Url { get; }
  }
  public sealed class DeviceStreamResponse {
  }
  public sealed class ModuleClient : IDisposable {
    public Task AcceptDeviceStreamRequestAsync(DeviceStreamRequest request, CancellationToken cancellationToken);
    public Task RejectDeviceStreamRequestAsync(DeviceStreamRequest request, CancellationToken cancellationToken);
    public Task<DeviceStreamRequest> WaitForDeviceStreamRequestAsync();
    public Task<DeviceStreamRequest> WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken);
  }
}
```

**Comment by ewertons** [comment]
> The device application registers a callback in advance to be notified of when a new device stream is initiated to the device. This step typically takes place when the device boots up and connects to IoT Hub.

We have moved away from the concept of callbacks in the Azure IoT Client C# SDK. 
It now uses TPL.

This should be: "The device application invokes the async method to receive a new device streaming request. Internally this causes the device client to establish the AMQP links or subscribe to the MQTT topic for stream requests if they have not been established yet."

**Comment by wickste** [comment]
Thanks @ewertons - updated the wording.

**Comment by ewertons** [comment]
In "New API surface added", the section for IoTHub Device SDK should be followed by the ModuleClient as well, which is an additional surface.

**Comment by wickste** [comment]
@ewertons ModuleClient API additions are listed. Which ones are missing?

**Comment by ewertons** [comment]
Oh, indeed they are on the list. No action on that one. Thanks @wickste

**Comment by ewertons** [comment]
Also, the samples shown above are outdated. They have been reworked and simplified a little. Please refer to: https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Samples/device/DeviceStreamingSample/DeviceStreamSample.cs

**Comment by wickste** [comment]
Accidentally closed - reopening

**Comment by wickste** [comment]
> The device application registers a callback in advance to be notified of when a new device stream is initiated to the device. This step typically takes place when the device boots up and connects to IoT Hub.
> 
> We have moved away from the concept of callbacks in the Azure IoT Client C# SDK.
> It now uses TPL.
> This should be: "The device application invokes the async method to receive a new device streaming request. Internally this causes the device client to establish the AMQP links or subscribe to the MQTT topic for stream requests if they have not been established yet."

Updated with suggested wording for .NET SDK.

**Comment by wickste** [comment]
> Also, the samples shown above are outdated. They have been reworked and simplified a little. Please refer to: https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Samples/device/DeviceStreamingSample/DeviceStreamSample.cs

@ewertons Not seeing any differences, other than whitespaces. Let me know if I am looking at the wrong file somehow.

**Comment by adrianhall** [comment]
I think this one is done at this point as well.  Closing for lack of action.

**Comment by suneetnangia** [comment]
Will ModuleClient get stream feature as well, looks like from the APIs but doesn't work atm, is this in progress?

**Comment by wickste** [comment]
@suneetnangia I believe this is being addressed, but I don't have the details. It would be best to raise an issue on the corresponding product repo and track it there. If you are using the .NET SDK, the right repo would be https://github.com/Azure/azure-iot-sdk-csharp
