### ISSUE TITLE
Board Review: Form Recognizer

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk#1548]
## The Basics

* Service team responsible for the client library: Azure SDK Team
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/cognitive-services/form-recognizer/overview
* Contact email: @mayurid 

## About this client library

* Name of the client library: Form Recognizer
* Languages for this review: Java and Javascript
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/FormRecognizer/preview/v2.0/FormRecognizer.json
and https://westus2.dev.cognitive.microsoft.com/docs/services/form-recognizer-api-v2-preview/operations/AnalyzeWithCustomForm

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### Java

* Upload sources JAR to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/05d0102010704cfa977f9386ce622294/72a1bce26ae14f369f63b7533cd37d5e
* Link to samples for champion scenarios: https://github.com/samvaity/azure-sdk-for-java/tree/update-receipt-formfield/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer

### Javascript

* Upload the api as a Draft PR.  Link to PR: https://github.com/Azure/azure-sdk-for-js/pull/10129/files
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/formrecognizer/ai-form-recognizer/samples/typescript/src

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

#### Recognize and extract field values from custom forms

* Target audience: LOB developers (~90%)
* Code samples: [**Java**](https://github.com/samvaity/azure-sdk-for-java/blob/update-receipt-formfield/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer/RecognizeCustomFormsFromUrl.java) | [**JS**](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/recognizeCustomForm.ts) 

#### Recognize and extract field values from Receipt documents

* Target audience: Day 0 developers, LOB developers (~30%)
* Code samples: [**.Java**](https://github.com/samvaity/azure-sdk-for-java/blob/update-receipt-formfield/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer/RecognizeReceipts.java) | [**JS**](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/recognizeReceipt.ts) 

#### Recognizing/Extracting strongly typed receipt fields from RecognizedForm
* Target audience: Day 0 developers, LOB developers (~30%)
* Code samples: [**.Java**](https://github.com/samvaity/azure-sdk-for-java/blob/update-receipt-formfield/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer/StronglyTypedRecognizedForm.java) | [**JS**](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/stronglyTypingRecognizedForm.ts) 

#### Recognize and extract OCR Content and Tables from Forms

* Target audience: LOB developers (~20%)
* Code samples: [**.Java**](https://github.com/samvaity/azure-sdk-for-java/blob/update-receipt-formfield/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer/RecognizeContent.java) | [**JS**](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/recognizeContent.ts) 

#### Train a model from custom forms

* Target audience: Data Scientists (~50%)
* Code samples: [**Java**](https://github.com/samvaity/azure-sdk-for-java/blob/update-receipt-formfield/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer/TrainModelWithoutLabels.java) | [**JS**](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/trainUnlabeledModel.ts)

#### Manage custom models

* Target audience: Data Scientists (~50%)
* Code samples: [**Java**](https://github.com/samvaity/azure-sdk-for-java/blob/update-receipt-formfield/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer/ManageCustomModels.java) | [**JS**](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/formrecognizer/ai-form-recognizer/samples/typescript/src/customModelManagement.ts) 

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet the quality bar.

**Comment by willmtemple** [comment]
@lilyjma Updated to include link to JavaScript API listing (draft PR on azure-sdk-for-js repo).

**Comment by lilyjma** [comment]
[MS internal only] Video [part1](https://web.microsoftstream.com/video/2b00a1ff-0400-a521-b41d-f1eacd33f964), [part2](https://web.microsoftstream.com/video/8a32a1ff-0400-a521-07ad-f1eacd2ca029)

**Comment by lilyjma** [comment]
(Thanks to Maggie and Kyle for the notes!)

## Java
- Last meeting, want to have options parameter be the only param on the overload
- FieldText model has been changed to FieldData
                - Decided to rename to call it FieldData because it has more elements than just the text in the field, this is consistent with Python naming

#### FormRecognizerAsyncClient
- Added overload to pass in buffer type to PollerFlux
- Parameter order question - should order be (String modelId, formUrl)

__ACTION__: All languages look at parameter order on FormRecognizerAsyncClient.PollerFlux 

__FOLLOW UP__: Look into lightening up the model package by moving account related model properties apart from training based models

__FOLLOW UP__: Look into IOException usage

__FOLLOW UP__: RecognizerOptions has a naming concern, does this fit with other languages?


## JS/TS
- Same renames as Java above
- Decided not to do a table-indexer, instead use flat cells array to be consistent with other languages and service
                - Could add convenience functions later, if necessary

__FOLLOW UP__: JS uses "valueType", should python be doing the same thing?
