### ISSUE TITLE
Board Review: Text Analytics - Opinion Mining

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk#1549]
## The Basics

* Service team responsible for the client library: Azure SDK Team
* Link to documentation describing the service: This meeting is for the opinion mining feature for sentiment analysis in Text Analytics. Documentation link [here](https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/how-tos/text-analytics-how-to-sentiment-analysis?tabs=version-3#opinion-mining)
* Contact email (if service team, provide PM and Dev Lead): @mayurid 
* We would like to schedule the meeting around the end of July

## About this client library

* Name of the client library: Text Analytics (opinion mining feature)
* Languages for this review: Python, .NET, Java, and JS. We'll try to get to all of the languages. If we can't, we'll schedule another one
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.1-preview.1/TextAnalytics.json

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.dev/Assemblies/Review/b196a5e53fa2441f92e3b1accefa35e7?diffRevisionId=b3605f7e99b744ba8175087b0c933fe2)
* Link to samples for champion scenarios: https://github.com/maririos/azure-sdk-for-net/blob/opinionmining/sdk/textanalytics/Azure.AI.TextAnalytics/samples/Sample2_AnalyzeSentimentOfHotelWithDetails.md

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link:  https://apiview.dev/Assemblies/Review/942b652edaf44b7189f41270cf07e54f?diffRevisionId=97ab113ca5094b278cc5605e03cab8df
* Link to opinion mining sample: https://gist.github.com/mssfang/5e04ce1a695223ddf91f297d33f0bbe2
### Python

* Upload the api as a Draft PR.  Link to PR: https://apiview.dev/Assemblies/Review/f74ef8c4777b408f85dab76b8034cb41/5c5ae05321de468aa1c749de2b44e74a?diffRevisionId=86e49dc083f14c55a13f47bb8e769937
* Link to opinion mining sample: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment_with_opinion_mining.py
### TypeScript

* Upload output of api-extractor to [apiview](https://apiview.azurewebsites.net). Link:
https://apiview.dev/Assemblies/Review/8754191c44914b7e88232f8aba5073de?diffRevisionId=5e88908f10cf4fd8894812b55e324291
* Link to opinion mining sample: https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/textanalytics/ai-text-analytics/samples/typescript/src/analyzeSentimentWithOpinionMining.ts

## Champion Scenarios (in this case, how a user would use aspect based sentiment analysis)

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* **Opinion mining**:
    * Opinion mining, known more commonly as aspect-based sentiment analysis in NLP, provides more granular information about the sentiments in text
    * Estimate the percentage of developers using the service who would use the champion scenario: current usage is around 3% (was just introduced mid-May)
    * One scenario is word clouds: [Python](https://github.com/iscai-msft/azure-sdk-for-python/blob/word_cloud_sample/sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment_with_opinion_mining.py
)

Examples of good scenarios are technology agnostic (i.e. the customer can do the same thing in multiple ways), and are expected to be used by > 20% of users:

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by mayurid** [comment]
Please make sure @assafi is invited to the review

**Comment by lilyjma** [comment]
scheduled for 8/3

**Comment by lilyjma** [comment]
[MS Internal Only] [Video](https://msit.microsoftstream.com/video/a8e5a3ff-0400-a520-5093-f1eaddb693ba)

## ACTION ITEMS: 
@iscai-msft @maririos @mssfang @deyaaeldeen 

## .Net API
- `Text` property of `AspectSentiment{}`
    - Maybe consider let people specify utf8 or utf16; user might want to do something immediately with the results and also want to save them in db as utf8
- Expose this simple overload `public virtual Response<DocumentSentiment> AnalyzeSentiment(string document, string language);`
    - `AnalyzeSentiment(string document, string language = null, AnalyzeSentimentOptions options = null, CancellationToken cancellationToken = default)`
    - If don't want to mine opinions, users don't want to see the option param 
-  `public class AnalyzeSentimentOptions : TextAnalyticsRequestOptions {}`
    - Consider flags enum
- `MinedOpinion{}`
    - Krzysztof: `MinedOpinions` a singular noun phrase has multiple properties is slightly weird?
    - come up with another name 


## Java API

- `TextAnalyticsRequestOptions{}` consider remove the `final` from class 
    - if choose to do this, override all setters of this type otherwise the return type will be `TextAnalyticsRequestOptions` and users won't be able to do fluent chaining of operations
    - make sure to setters return `AnalyzeSentimentOptions` rather than the default `TextAnalyticsRequestOptions` 
    - clarify with Jonathan offline 
- Naming should stay consistent with other languages 

## Python API 

- Add expected output of sample as comments, because helps to "get the feel of what the code does"
- `analyze_sentiment{}`
    - why isn't `show_opinion_mining` not on by default? Assaf: Cost is a consideration
    - architects agree that it won't be a problem if service decides to turn it on for Python, JS, .Net, and Java

## TS API

- `Type DocumentSentimentLabel = "positive" | "neutral" | "negative"| "mixed"`
    - don't return aspects that don't have sentiment; not interesting
    - just make type that's accurate; remove "neural" if not interesting 
- `interface SentenceSentiment{}`
    - remove the ? in `minedOpinions? MinedOpinion[]`
    - if it's initialized all the time, don't need generic  
- `isNegated` property in `interface OpinionSentiment{}` 
    - maybe not be the best name but can't come up with better now
    - Johan's proposal `isTextNegated`

Timeline for service: 
First week of Sept, release offset support, Version 3.1 preview 2
