### ISSUE TITLE
Board Review: EventGrid [TypeScript/Python]

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-sdk#1553]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Event Grid team.
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/event-grid/ and https://docs.microsoft.com/en-us/azure/event-grid/edge/.
* Contact email (if service team, provide PM and Dev Lead): PM: jafernan@microsoft.com, Dev Lead: rajarv@microsoft.com. Dev: ahamad@microsoft.com 

## About this client library

* Name of the client library:  Event Grid
* Languages for this review: .Net, Java, Python, Node.js, Go.
* Link to the service REST APIs: swagger specs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventgrid/data-plane/Microsoft.EventGrid/stable/2018-01-01/EventGrid.json

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### Python

* Upload the api as a Draft PR.  Link to PR: https://apiview.dev/Assemblies/Review/4a06ad32c7074a1e880da31116dfd0e8
* Link to samples for champion scenarios: See below

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR: https://github.com/Azure/azure-sdk-for-js/pull/10059
* Link to samples for champion scenarios: See bellow

### TypeScript
```typescript
import { AzureKeyCredential, EventGridPublisherClient } from "@azure/eventgrid";
import { v4 as uuidv4 } from "uuid";

const topicEndpoint =  "https://<YOUR-TOPIC-NAME>.<REGION-NAME>-1.eventgrid.azure.net/api/events";
const topicKey =  "<YOUR-TOPIC-KEY>";

const client = new EventGridPublisherClient(topicEndpoint, new AzureKeyCredential(topicKey))

await client.sendEvents([
  {
    id: uuidv4(),
    eventTime: new Date(),
    eventType: "Contoso.Items.ItemReceived",
    data: {
        itemSku: "Contoso Item SKU #1"        
    },
    subject: "Door1",
    dataVersion: "2.0"
  }
]);

```

### Python

```python
from azure.eventgrid import EventGridPublisherClient, EventGridEvent
from azure.core.credentials import AzureKeyCredential

topic_hostname = "<YOUR-TOPIC-NAME>.<REGION-NAME>-1.eventgrid.azure.net"
topic_key = "<YOUR-TOPIC-KEY>"

credential = AzureKeyCredential(topic_key)
client = EventGridPublisherClient(topic_hostname, credential)

client.send([
	EventGridEvent(
		event_type="Contoso.Items.ItemReceived",
		data={
			"itemSku": "Contoso Item SKU #1"
		},
		subject="Door1",
		data_version="2.0"
	)
])

```

## Champion Scenario 2: Publish custom events to a domain topic

Event Grid exposes the concept of a "domain" which gives a single endpoint to multiple topics.  When publishing to a domain, the `topic` property of `EventGridEvent` must be set.  We do not expose seperate clients for EventGrid Topics and EventGrid Domains.

### TypeScript

```typescript
import { AzureKeyCredential, EventGridPublisherClient } from "@azure/eventgrid";
import { v4 as uuidv4 } from "uuid";

const topicEndpoint =  "https://<YOUR-TOPIC-NAME>.<REGION-NAME>-1.eventgrid.azure.net/api/events";
const topicKey =  "<YOUR-TOPIC-KEY>";

const client = new EventGridPublisherClient(topicEndpoint, new AzureKeyCredential(topicKey))

await client.sendEvents([
  {
    topic: "MyCustomDomainTopic",
    id: uuidv4(),
    eventTime: new Date(),
    eventType: "Contoso.Items.ItemReceived",
    data: {
        itemSku: "Contoso Item SKU #1"        
    },
    subject: "Door1",
    dataVersion: "2.0"
  }
]);

```

### Python

```python
from azure.eventgrid import EventGridPublisherClient, EventGridEvent
from azure.core.credentials import AzureKeyCredential

topic_hostname = "<YOUR-DOMAIN-TOPIC-NAME>.<REGION-NAME>-1.eventgrid.azure.net"
topic_key = "<YOUR-TOPIC-KEY>"

credential = AzureKeyCredential(topic_key)
client = EventGridPublisherClient(topic_hostname, credential)

client.send([
	EventGridEvent(
		topic="MyCustomDomainTopic",
		event_type="Contoso.Items.ItemReceived",
		data={
			"itemSku": "Contoso Item SKU #1"
		},
		subject="Door1",
		data_version="2.0"
	)
])

```

## Champion Scenarion 3: Consume system events

Event Grid can deliver event payloads to a variety of destinations, like Azure Functions, Event Hubs, Service Bus, Storage Queues and WebHooks.

### TypeScript

```typescript
import { EventGridConsumer } from "@azure/eventgrid"
import { ReceivedMessageWithLock } from "@azure/service-bus";

const consumer = new EventGridConsumer();

async function processMessage(message: ReceivedMessageWithLock): Promise<void> {
  // When delivering to a Service Bus Queue or Topic, EventGrid delivers a single event per message.
  // so we just pluck the first one.
  const event = (await consumer.deserializeEventGridEvents(message.body))[0];

  if (isContainerRegistryImagePushedEvent(event)) {
    console.log(
        `${event.eventTime}: Container Registry Image Pushed event for image ${
          event.data!.target!.repository
        }:${event.data!.target!.tag}`
    );
  } else {
    console.log(`${event.eventTime}: Ignoring event of type ${event.eventType}`);
  }

  await message.complete();
}
```

### Python

Sample EventGridEvent JSON, with System Event data
```json
{
    "specversion": "1.0",
    "type": "Microsoft.Storage.BlobCreated",  
    "source": "/subscriptions/{subscription-id}/resourceGroups/{resource-group}/providers/Microsoft.Storage/storageAccounts/{storage-account}",
    "id": "9aeb0fdf-c01e-0131-0922-9eb54906e209",
    "time": "2019-11-18T15:13:39.4589254Z",
    "subject": "blobServices/default/containers/{storage-container}/blobs/{new-file}",
    "dataschema": "#",
    "data": {
        "api": "PutBlockList",
        "clientRequestId": "4c5dd7fb-2c48-4a27-bb30-5361b5de920a",
        "requestId": "9aeb0fdf-c01e-0131-0922-9eb549000000",
        "eTag": "0x8D76C39E4407333",
        "contentType": "image/png",
        "contentLength": 30699,
        "blobType": "BlockBlob",
        "url": "https://gridtesting.blob.core.windows.net/testcontainer/{new-file}",
        "sequencer": "000000000000000000000000000099240000000000c41c18",
        "storageDiagnostics": {
            "batchId": "681fe319-3006-00a8-0022-9e7cde000000"
        }
    }
}

```

Code sample
```python
import os
from azure.eventgrid import EventGridConsumer

req = os.environ.get("HTTP_REQUEST")
consumer = EventGridConsumer()

# returns List[DeserializedEvent]
deserialized_events = consumer.deserialize_events(req)

# EventGridEvent schema, Storage.BlobCreated event
for event in deserialized_events:

    # both allow access to raw properties as strings
    time_string = event.event_time
    time_string = event["event_time"]

    # model returns EventGridEvent object
    event_grid_event = event.model

    # all model properties are strongly typed
    datetime_object = event.model.time
    storage_blobcreated_object = event.model.data

```

### TypeScript

```typescript
import { EventGridConsumer } from "@azure/eventgrid"
import { ReceivedMessageWithLock } from "@azure/service-bus";

interface ContosoItemReceivedEventData {
  itemSku: string;
}

function isContosoItemReceviedEvent(
  event: EventGridEvent<unknown>
): event is EventGridEvent<AzureSdkDemoEventData> {
  return event.eventType === "Contoso.Items.ItemReceived";
}

const consumer = new EventGridConsumer();

async function processMessage(message: ReceivedMessageWithLock): Promise<void> {
  // When delivering to a Service Bus Queue or Topic, EventGrid delivers a single event per message.
  // so we just pluck the first one.
  const event = (await consumer.decodeEventGridEvents(message.body))[0];

  if (isContosoItemReceviedEvent(event)) {
    console.log(
      `${event.eventTime}: Item recevied event for SKU: ${event.data.itemSku}`
    );
  } else {
    console.log(
      `${event.eventTime}: Ignoring event of type ${event.eventType}`
    );
  }

  await message.complete();
}
```

### Python

Sample EventGridEvent JSON, with Custom Event data
```json
{
  "topic": "customeventexample.eastus-1.eventgrid.azure.net",
  "subject": "Door1",
  "eventType": "Contoso.Items.ItemReceived",
  "eventTime": "2017-06-26T18:41:00.9584103Z",
  "id": "831e1650-001e-001b-66ab-eeb76e069631",
  "data": {
      "itemSku": "Contoso Item SKU #1"
  },
  "dataVersion": "2.0",
  "metadataVersion": "1"
}

```

Sample code
```python
import os
from azure.eventgrid import EventGridConsumer

req = os.environ.get("HTTP_REQUEST")
consumer = EventGridConsumer()

# returns List[DeserializedEvent]
deserialized_events = consumer.deserialize_events(req)

# EventGridEvent schema, with custom event type
for event in deserialized_events:

    # both allow access to raw properties as strings
    time_string = event.event_time
    time_string = event["event_time"]

    # model returns EventGridEvent object
    cloud_event = event.model

    # returns "{ 'itemSku': 'Contoso Item SKU #1' }"
    data_string = event.data

    # custom event not pre-defined in system event registry, returns None
    returns_none = event.model.data

```

## Champion Scenario 5: Publish events using Cloud Events 1.0 schema

EventGrid supports the CNCF Cloud Events 1.0 schema for publishing events. When creating a topic, it can be configured to use the Cloud Events 1.0 schema.  The `EventGridPublisherClient` type has seperate methods for sending events in using the Cloud Events 1.0 schema.

### TypeScript

```typescript
import { AzureKeyCredential, EventGridPublisherClient } from "@azure/eventgrid";
import { v4 as uuidv4 } from "uuid";

const topicEndpoint =  "https://<YOUR-TOPIC-NAME>.<REGION-NAME>-1.eventgrid.azure.net/api/events";
const topicKey =  "<YOUR-TOPIC-KEY>";

const client = new EventGridPublisherClient(topicEndpoint, new AzureKeyCredential(topicKey));

await client.sendCloudEvents([
  {
    type: "contoso.items.itemreceived",
    source: "/contoso/items",
    id: uuidv4(),
    time: new Date(),
    data: {
        itemSku: "Contoso Item SKU #1"        
    },
    subject: "Door1",
  }
]);
```

### Python

```python
from azure.eventgrid import EventGridPublisherClient, CloudEvent
from azure.core.credentials import AzureKeyCredential

topic_hostname = "<YOUR-TOPIC-NAME>.<REGION-NAME>-1.eventgrid.azure.net"
topic_key = "<YOUR-TOPIC-KEY>"

credential = AzureKeyCredential(topic_key)
client = EventGridPublisherClient(topic_hostname, credential)

client.send([
    CloudEvent(
        type="Contoso.Items.ItemReceived",
        source="/contoso/items",
        data={
            "itemSku": "Contoso Item SKU #1"
        },
        subject="Door1"
    )
])

```

### TypeScript

```typescript
const consumer = new EventGridConsumer();

async function processMessage(message: ReceivedMessageWithLock): Promise<void> {
  // When delivering to a Service Bus Queue or Topic, EventGrid delivers a single event per message.
  // so we just pluck the first one.
  const event = (await consumer.deserializeCloudEvents(message.body))[0];

  if (isContainerRegistryImagePushedEvent(event)) {
    console.log(
        `${event.time}: Container Registry Image Pushed event for image ${
          event.data!.target!.repository
        }:${event.data!.target!.tag}`
    );
  } else {
    console.log(`${event.time}: Ignoring event of type ${event.type}`);
  }

  await message.complete();
}
```

### Python

Sample CloudEvent JSON, with System Event data

```json
{
    "specversion": "1.0",
    "type": "Microsoft.Storage.BlobCreated",  
    "source": "/subscriptions/{subscription-id}/resourceGroups/{resource-group}/providers/Microsoft.Storage/storageAccounts/{storage-account}",
    "id": "9aeb0fdf-c01e-0131-0922-9eb54906e209",
    "time": "2019-11-18T15:13:39.4589254Z",
    "subject": "blobServices/default/containers/{storage-container}/blobs/{new-file}",
    "dataschema": "#",
    "data": {
        "api": "PutBlockList",
        "clientRequestId": "4c5dd7fb-2c48-4a27-bb30-5361b5de920a",
        "requestId": "9aeb0fdf-c01e-0131-0922-9eb549000000",
        "eTag": "0x8D76C39E4407333",
        "contentType": "image/png",
        "contentLength": 30699,
        "blobType": "BlockBlob",
        "url": "https://gridtesting.blob.core.windows.net/testcontainer/{new-file}",
        "sequencer": "000000000000000000000000000099240000000000c41c18",
        "storageDiagnostics": {
            "batchId": "681fe319-3006-00a8-0022-9e7cde000000"
        }
    }

```

```python
import os
from azure.eventgrid import EventGridConsumer

req = os.environ.get("HTTP_REQUEST")
consumer = EventGridConsumer()

# returns List[DeserializedEvent]
deserialized_events = consumer.deserialize_events(req)

# CloudEvent schema
for event in deserialized_events:

    # both allow access to raw properties as strings
    time_string = event.time
    time_string = event["time"]

    # model returns CloudEvent object
    cloud_event = event.model

    # all model properties are strongly typed
    datetime_object = event.model.time
    storage_blobcreated_object = event.model.data

```

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by ellismg** [comment]
Because of the staggers start of our interns, we are only ready to do architecture board reviews of the dynamic languages (Python and JavaScript).

**Comment by lilyjma** [comment]
[MS internal only] [Video](https://msit.microsoftstream.com/video/68cca3ff-0400-a521-8a77-f1eacc6f5c41)

@ellismg, @t-swpill

**Python**

ACTION ITEMS:

- AzureKeyCredential(topic_key)
    - Not a `topic_key`, a domain key 


- Majority of users using `CloudEventSchema`? Might not be true. Currently if dict obj passed into `EventGridPublisherClient.send()`, it'll be interpreted as `CloudEventSchema`. Service team believes diff event types should be treated differently instead 
    - change the current approach
    - option: let user set an option to specify event type if pass in dict 


- Explore existing pattern for building batch/batch operations
    - follow up with service team about size limit and how to approach this 

- send code to Raja on "magic" behind `consumer.deserialize_events(req)`


- Scenario 4 
    - data is not a string, but an object; also the return shouldn't be a string, maybe a bug in the publisher 
    - Avoid using `CustomEvents`


- Scenario 5
    - Explore how to inject trace as property for `CloudEvents` 


- Scenario 6
    - Talk with service team on how to approach sending in binary mode 


**API**

- `EventGridPublisherClient`
    - `send() `remove dict

- Shouldn't be using `TokenCredential` (generalizing for OAuth credential) in constructor 2:51
   - Come up with another and rename it to prevent confusion with `TokenCredential` from Azure Core 


- `EventGridConsumer`
    - Shouldn't have dependencies on Service Bus and Event Hubs 


**JS**
 
Action Items:

- Scenario 2
    - Change to `domainEndpoint` and `domainKey` since it's sample for domain
    - Publishing endpoint is a domain endpoint, change URI
    - maybe URI builder will be helpful 

- Scenario 3
    - Share with Brian larger sample to show how `processMessage()` is hooked up 

- Scenario 5
    - change the return value to be some type we own and add property requested in future 

**API**

```
export interface CloudEvent<T>{
    datacontenttype?: string; 
}
```

- casing to match spec here, but unsure how to approach it (get Service Team opinion)

`export type ContainerRegistryChartDeletedEventData = ContainerRegistryArtifactEventData & {}`

- too many exports for top level, if have another 100 of these
- follow up with Brian 

`export interface ContainerRegistryEventRequest{
    addr?: string;
}`

- follow up with name change
- pretti-fy the names in swagger? Service team's thought is not to change names when possible


`EventGridPublisherClient{}`
- move `generateSharedAccessSignature()` to top level (double check if this is done by Storage)

**Comment by lilyjma** [comment]
@ellismg please let me know when this issue can be closed
