### ISSUE TITLE
Update Releases Page with Latest Releases

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#1556]
We have https://aka.ms/azsdk/releases to show all of the packages that have been released.

The initial “New” list is manual entry and then it gets auto-updated by a script for subsequent releases.

Please go through your languages packages and ensure that the "New" list contains all of the new packages that are in Preview or GA.

The data is sourced here: https://github.com/Azure/azure-sdk/tree/master/_data/releases/latest

@AlexGhiondea @joshfree @ramya-rao-a @mayurid @weshaggard @czubair

**Comment by jongio** [comment]
@AlexGhiondea - Can you please have a look for .NET?

For example, Azure.Search.Documents does not appear in the new list, but it does appear in the "all" list.

![image](https://user-images.githubusercontent.com/2163001/88577421-d8d80c80-cffb-11ea-91d2-b38c4627249d.png)

**Comment by joshfree** [comment]
@samvaity can you please spot check https://azure.github.io/azure-sdk/releases/latest/index.html#java
