### ISSUE TITLE
Board Review: Webjobs Storage Extension track 2 - Initial Discussion

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk#1563]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Storage
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started
* Contact email (if service team, provide PM and Dev Lead): kasobol@

## About this client library

* Name of the client library: Azure.WebJobs.Extensions.Storage (TBD). This is going to be a port of existing extension onto track 2 SDK
* Languages for this review: .NET only
* Link to the service REST APIs: N/A, based on Storage SDK

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link:
Existing extension public surface has been extracted here: https://apiview.dev/Assemblies/Review/7ad2c307b9af432a95c4963d3c2c3f59
* Link to samples for champion scenarios:
https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started
https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-how-to
https://github.com/kasobol-msft/azure-sdk-for-net/tree/feature/storage/webjobs/sdk/storage/Azure.Storage.Webjobs.Extensions/samples/SampleHost

Initial extract of Storage Extension from webjobs repo: https://github.com/Azure/azure-sdk-for-net/pull/13452 (baseline for this work).

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

Setting up
```
builder.ConfigureWebJobs(b =>
                {
                    b.AddAzureStorageCoreServices();
                    b.AddAzureStorage();
                });
```

Queue trigger
```
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;

namespace WebJobsSDKSample
{
    public class Functions
    {
        public static void ProcessQueueMessage([QueueTrigger("queue")] string message, ILogger logger)
        {
            logger.LogInformation(message);
        }
    }
}
```

Input bindings
```
public static void ProcessQueueMessage(
    [QueueTrigger("queue")] string message,
    [Blob("container/{queueTrigger}", FileAccess.Read)] Stream myBlob,
    ILogger logger)
{
    logger.LogInformation($"Blob name:{message} \n Size: {myBlob.Length} bytes");
}
```

Output bindings
```
public static void ProcessQueueMessage(
    [QueueTrigger("queue")] string message,
    [Blob("container/{queueTrigger}", FileAccess.Read)] Stream myBlob,
    [Blob("container/copy-{queueTrigger}", FileAccess.Write)] Stream outputBlob,
    ILogger logger)
{
    logger.LogInformation($"Blob name:{message} \n Size: {myBlob.Length} bytes");
    myBlob.CopyTo(outputBlob);
}
```

Queue trigger configuration
```
static async Task Main()
{
    var builder = new HostBuilder();
    builder.ConfigureWebJobs(b =>
    {
        b.AddAzureStorageCoreServices();
        b.AddAzureStorage(a => {
            a.BatchSize = 8;
            a.NewBatchThreshold = 4;
            a.MaxDequeueCount = 4;
            a.MaxPollingInterval = TimeSpan.FromSeconds(15);
        });
    });
    var host = builder.Build();
    using (host)
    {
        await host.RunAsync();
    }
}
```

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
[Microsoft Internal Only][Video](https://msit.microsoftstream.com/video/b12ea1ff-0400-a521-74ba-f1ead6a04b5a)

**Action Items:** 

Figure out whether to create a new parallel feature or reuse part of feature by refactoring assembly into 2
- sync up with Matt, Peter and Functions team 
- Pavel will start a thread

Krzysztof proposes hybrid: brand new surface area + try to change existing code that don't depend on Client to start using Track 2

Shouldn't break ppl who reference Track 1 Client functions (Krzysztof) 
But this means we'll have to continously support Track 1--when to stop? (Pavel)

Pavel's other question: What if we want to ship new feature, but it's a breaking change? 

Krzysztof: What if attributes have different params that allows you to switch to diff versions?
