### ISSUE TITLE
Add github owners to email notifications

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#1568]
Currently there is a static list of people that the issue notifications are sent to.  This issue is tracking the need to add owners of the issues to the to: or cc: line for these notifications.

**Comment by mitchdenny** [comment]
Just wanted to clarify this. Did you want to send the issue list for the entire repository to anyone with an active issue, or did you want to send a list tailored to each user?

**Comment by kurtzeborn** [comment]
@AlexGhiondea, can you clarify the ask here?

**Comment by AlexGhiondea** [comment]
We should send the email to anyone who has an issue assigned to them that is flagged in any report.

At the core, this is about figuring out how to map GitHub handles to email aliases. Once we can do that we should be able to construct the list of recipients to which to send the email.

**Comment by weshaggard** [comment]
>At the core, this is about figuring out how to map GitHub handles to email aliases. Once we can do that we should be able to construct the list of recipients to which to send the email.

We already have code that does this in our pipeline notifications tool https://github.com/Azure/azure-sdk-tools/blob/master/tools/notification-configuration/common/Helpers/GitHubNameResolver.cs. We should try to reuse that.

**Comment by mitchdenny** [comment]
@weshaggard ... yep, I saw that. Probably obvious but I'm assuming this notification mechanism is to overcome people disabling the built-in GitHub notification mechanism? :)

There are also a few reliability issues in GitHub Issues with rate limiting at the moment: https://github.com/Azure/azure-sdk-tools/issues/818

**Comment by mitchdenny** [comment]
As part of some preparation for implementing some features like this I've done some restructuring of the GitHub Issues code base:

https://github.com/Azure/azure-sdk-tools/pull/842

**Comment by mitchdenny** [comment]
I am closing this. Why do you ask?

The Java team recently adopted a pattern where they added one of their team aliases to the configuration so that anyone on the team gets a notification when the report is run. Given that we don't do personalized reports per person based on the paths being modified in PRs, this is probably sufficient to make sure that the right group of people that do triage get the report.

@AlexGhiondea do you agree?
