### ISSUE TITLE
Board Review: Azure Storage Blob NIO

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk#1575]
## The Basics

* Service team responsible for the client library: Azure Blob Storage
* Link to documentation describing the service: https://azure.microsoft.com/en-us/services/storage/blobs/
* Contact email (if service team, provide PM and Dev Lead): frley@microsoft.com amishra@microsoft.com

## About this client library

* Name of the client library: Azure Storage Blob NIO
* Languages for this review: Java
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/storage-dataplane-preview/specification/storage/data-plane

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/7afaef0b130546fcb6a95076ca7e543f
* Link to samples for champion scenarios: https://gist.github.com/rickle-msft/71bb85115fa2e867841b83bf5df814a9

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Describe the champion scenario:
      * A customer has a file containing a sequenced genome. They open the file, read a relevant portion of it, perform some analysis on the data they read, and write the results to an output directory. 
    * Estimate the percentage of developers using the service who would use the champion scenario
      * 100%: As far as we know, everyone who has requested this product has use for this exact scenario
    * Link to the code sample
      * https://gist.github.com/rickle-msft/71bb85115fa2e867841b83bf5df814a9

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
[MS internal only][Video](https://msit.microsoftstream.com/video/0f21a1ff-0400-a521-5951-f1ead7674a33)

**Action Items:** 

Champion Scenario:
- possible to try-catch that does auto close? Use that in champion scenario if possible 

Consider edge cases difficult to code for: 
- Open same file twice for reading 
    - Whichever string gets closed, gets committed, which invalidates the block list from the other. Second write throws 
    - But this way of handling isn't what's normally expected for file system
- e-tags could change between reads, which will throw if customer doesn't know, 
    - document the assumption that nothing else is modifying on the file while operating on it
- In general, document what limitations, assumptions, etc. there are 

Consider how pluggable this is into existing code

How to get back/access to Blob client? 
- Consider how we want to approach this if customers want it in long run
- Jeff's concern: Exposing this would give customer opportunity to do something risky. Ex: doing something to blob that changes e-tag, they'll no longer able to read. "I'd be cautious about it." 
- Ted's suggestion: Could we do something like `AzureBlobFileSystem.GetBlobClient(URI path)` that returned a client so you could just take your path and jump into our world?

SDK team to come up with way to name the package, especially for tools that are not truly client libraries but will be placed in SDK repos
- be sure to go through the name of this (Azure Storage Blob NIO) before GA

Jonathan is okay with the APIView
- Only need good java docs! 

**Next Steps:**

- Path to GA: nothing urgent here yet; focusing on iterating based on customer feedback 
- Follow up with Jonathan to get something blogged
