### ISSUE TITLE
Board Review: ObjectSerializer C#

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk#1578]
Extracted from https://github.com/Azure/azure-sdk/issues/1454

## The Basics

We'd like to add ObjectSerializer abstraction and Syste.Text.Json-based implementation for .NET.

* Service team: The ADP .NET folks
* ApiView: https://apiview.dev/Assemblies/Review/8f2e023e377f4627a4ec815f6e11d013#Azure.Core.ObjectSerializer
* Contact: @pakrym, and @KrzysztofCwalina 

## Champion Scenarios

We’re introducing a Bring Your Own Serializer model because there a lot of customers who wont come to Track 2 without it.  [`ObjectSerializer`](https://apiview.dev/Assemblies/Review/8f2e023e377f4627a4ec815f6e11d013#Azure.Core.ObjectSerializer) is the base abstraction.  We’re shipping [`JsonObjectSerializer : ObjectSerializer`](https://apiview.dev/Assemblies/Review/8f2e023e377f4627a4ec815f6e11d013#Azure.Core.JsonObjectSerializer) to wrap using `System.Text.Json`.  As a customer you’ll still use all the `System.Text.Json` attributes, naming policies, options, documentation, etc., for your type `T`.  You’ll just tell our client libraries which serializer you’re using via `clientOptions.Serializer = new JsonObjectSerializer(new System.Text.Json.JsonSerializerOptions(...))` and we’ll use it for all your custom model types in our clients.  [You can see more example usage in the tests.](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core.Experimental/tests/JsonObjectSerializerTest.cs)

### Using clients with a custom model and default serializer

``` C#
class MyModel
{
     public string Name { get; }
}

SearchClient client = new SearchClient(new Uri("<endpoint>"), "<index>", new AzureKeyCredential("<key>"));
Response<SearchResults<MyModel>> results = client.Search<MyModel>("search text");
```

### Using clients with a custom model with System.Text.Json attributes and default serializer

``` C#
class MyModel
{
     [JsonPropertyName("name")]
     public string Name { get; }
}

SearchClient client = new SearchClient(new Uri("<endpoint>"), "<index>", new AzureKeyCredential("<key>"));
// client.Search<MyModel> would deserialize `Name` property from `name` JSON property.
Response<SearchResults<MyModel>> results = client.Search<MyModel>("search text");
```

### Using clients with a custom model with customized default serializer

``` C#
class MyModel
{
     public string Name { get; }
}

var searchClientOptions = new SearchClientOptions();

// configure the serializer
searchClientOptions.ObjectSerializer = new JsonObjectSerializer(new JsonSerializerOptions()
{
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase
});

SearchClient client = new SearchClient(new Uri("<endpoint>"), "<index>", new AzureKeyCredential("<key>"), searchClientOptions);

// client.Search<MyModel> would deserialize `Name` property from `name` JSON property (because of naming policy).
Response<SearchResults<MyModel>> results = client.Search<MyModel>("search text");
```

### Using clients with a custom model with Newtonsoft.Json serializer

``` C#

// Existing customer model from Track 1 library
class MyModel
{
     // Newtonsoft-specific attribute
     [JsonProperty("name")]
     public string Name { get; }
}

var searchClientOptions = new SearchClientOptions();

// configure the serializer
// NOTE: we don't ship NewtonsoftJsonObjectSerializer yet
searchClientOptions.ObjectSerializer = new NewtonsoftJsonObjectSerializer();

SearchClient client = new SearchClient(new Uri("<endpoint>"), "<index>", new AzureKeyCredential("<key>"), searchClientOptions);

// client.Search<MyModel> would deserialize `Name` property from `name` JSON property (because NewtonsoftJsonObjectSerializer knows about it).
Response<SearchResults<MyModel>> results = client.Search<MyModel>("search text");
```

**Comment by pakrym** [comment]
C# API Approved by @KrzysztofCwalina post review-board review.

**Comment by ramya-rao-a** [comment]
@bterlson, @johanste, @JonathanGiles, We won't be having a separate meeting to review this API.
Since it is already been approved by the .Net architect @KrzysztofCwalina, can the rest of you take a look and provide your approval if you have no concerns with the proposed design?

Please note that this is being shipped in less than 2 weeks

**Comment by ramya-rao-a** [comment]
cc @annatisch, @srnagar, @xirzec

**Comment by JonathanGiles** [comment]
What level of confidence is there that this API will be sufficient to also support the JSON.net?

**Comment by pakrym** [comment]
We have an implementation. The level of confidence is high.

**Comment by johanste** [comment]
I have no concerns about the C# design.

**Comment by bterlson** [comment]
I also have no concerns about the C# design.
