### ISSUE TITLE
Should we use cryptographically signed git tags (“git tag -s”)?

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk#1583]
... when releasing the Azure SDK for Embedded C, or for that matter, any of the language SDKs that ships artifacts like sources hosted on GitHub?

There is a [FOSS CII body from Linux Foundation/Harvard](https://bestpractices.coreinfrastructure.org/en) that provides certain recommendations/guidelines for open source projects and they mentioned using signed tags in their checklist.

Here is the specific guidance from them around secure releases that mentions signing tags:
https://github.com/coreinfrastructure/best-practices-badge/blob/6a1a6c18858cdcf3849f04fdd048109f4c5a86e1/doc/other.md#secure-release

> Rationale: This provides protection from compromised distribution systems.

cc @weshaggard, @danieljurek, @RickWinter

**Comment by kurtzeborn** [comment]
What does it take to sign all of our release tags and will it cause any problems with our current system and workflow?

**Comment by mitchdenny** [comment]
Looks like it just uses GPG to sign the commit (we use GPG already as part of the Java release process to sign packages). We could potentially use the same signing key for consistency.

**Comment by weshaggard** [comment]
@mitchdenny does it add any resistance for consumers of our release tags if they are signed? Does git automatically verify or do folks need to setup something?

**Comment by mitchdenny** [comment]
I think it is seamless. I've used repos with people that use verified commits/tags and don't notice anything. Will experiment though.

**Comment by weshaggard** [comment]
OK if it is seamless lets do it for all the release tags across languages. Lets see if we can figure out a good way to do the gpg signing in the open engineering system instead of requiring azure-sdk-internal-tools if possible.

**Comment by ahsonkhan** [comment]
@mitchdenny - do we have any updates to this effort?

**Comment by mitchdenny** [comment]
No updates at this stage.

**Comment by mitchdenny** [comment]
Had a look at this. Currently we create our releases/tags using the REST API. In this scenario the tag is signed, but it is signed using the GitHub key because we've authenticated to GitHub using credentials that they validate.

So the point of difference between where we are today, and this proposal is that we could swap over to using our own GPG key to sign the commit. This would require us to change our current mechanism to clone the repository, add a tag using our GPG key and then push it to the origin (and then call the REST API to create a release).

Practically I'm not sure that this buys us a lot in terms of additional confidence. I'm closing this down, but if you want to make the case for going further than what we already have feel free to open it up and we can continue discussing.

**Comment by ahsonkhan** [comment]
Thanks @mitchdenny for the deep dive. You are right, the intention/benefit for this is primarily around defense-in-depth and working in a partial-to-zero trust environment, rather than relying only on the source code host like GitHub. There is certainly a spectrum, and most solutions aren't completely secure/fool proof, but if the steps you laid out aren't overly cumbersome or costly to implement, we should consider signing the tags, and then go further to assert the validity of the commit graphs too. There is still _some_ value in signing just the tag and assume the commits are trusted for now (though unlikely today, it potentially helps detect and mitigate the risk of MITM).

Here's a fun read on the topic: https://mikegerwitz.com/2012/05/a-git-horror-story-repository-integrity-with-signed-commits

**Comment by mitchdenny** [comment]
Hey @ahsonkhan, at this point I'm included not to implement signing but I've reached out to some of our OSS champs to get a sense of what other MS-maintained OSS repositories are doing. In fact I'm not event certain how we would get GitHub to allow us to use our own keys when we are merging PRs (and if we can't do that we haven't really moved the needle at all).

Do you have an example of an OSS project hosted on GitHub which is signing their commits/tags using an external GPG key?
