### ISSUE TITLE
Board Review: Tables

### ISSUE THREAD

**Issue by meanjeekim** [Azure/azure-sdk#1589]
## The Basics

* Service team responsible for the client library:
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/storage/tables/
* Contact email (if service team, provide PM and Dev Lead): tablesdkadp@microsoft.com

## About this client library

* Name of the client library: Tables
* Languages for this review: .NET, Javascript
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/storageservices/table-service-rest-api

### .NET

* [APIView](https://apiview.dev/Assemblies/Review/5eec924756264faab7ce2eb54d630fb3)
* [Samples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/tables/Azure.Data.Tables/tests/samples)

### TypeScript

* [API Extractor](https://github.com/mahdiva/azure-sdk-for-js/pull/1)
* [Samples](https://github.com/mahdiva/azure-sdk-for-js/blob/tables-api-review/sdk/tables/azure-tables/samples/typescript/src/TableServiceClientSamples.ts)

## Champion Scenarios

Table Level

* Demonstrate creation and deletion of a table
  * Almost all users
  * [.NET Sync](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/tests/samples/Sample1_CreateDeleteTable.cs) | [.NET Async](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/tests/samples/Sample1_CreateDeleteTableAsync.cs) | [Javascript](https://github.com/mahdiva/azure-sdk-for-js/pull/1/files?file-filters%5B%5D=.ts#diff-34dd59109b4c0b1237b82fb8d1c0f460R33-R39)
* Demonstrate error handling  existing table
  * Almost all users
  * [.NET](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/tests/samples/Sample1_CreateDeleteTableErrors.cs) | [Javascript](https://github.com/mahdiva/azure-sdk-for-js/pull/1/files?file-filters%5B%5D=.ts#diff-34dd59109b4c0b1237b82fb8d1c0f460R41-R57)
* Demonstrate listing (I.e. querying) tables
  * Most users
  * [.NET Sync](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/tests/samples/Sample3_QueryTables.cs) | [.NET Async](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/tests/samples/Sample3_QueryTablesAsync.cs) | [Javascript](https://github.com/mahdiva/azure-sdk-for-js/pull/1/files?file-filters%5B%5D=.ts#diff-34dd59109b4c0b1237b82fb8d1c0f460R59-R65)
 
Entity Level

* Demonstrate inserting and deleting entity data (including odata types e.g. uuid)
  * Almost all users
  * [.NET Sync](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/tests/samples/Sample2_CreateDeleteEntities.cs) | [.NET Async](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/tests/samples/Sample2_CreateDeleteEntitiesAsync.cs) | [Javascript](https://github.com/mahdiva/azure-sdk-for-js/pull/1/files?file-filters%5B%5D=.ts#diff-34dd59109b4c0b1237b82fb8d1c0f460R82-R100)
* Demonstrate update/upsert entity data in a table using optimistic concurrency checks
  * Most users
  * [.NET Sync](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/tests/samples/Sample5_UpdateUpsertEntities.cs) | [.NET Async](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/tests/samples/Sample5_UpdateUpsertEntitiesAsync.cs) | [Javascript](https://github.com/mahdiva/azure-sdk-for-js/pull/1/files?file-filters%5B%5D=.ts#diff-34dd59109b4c0b1237b82fb8d1c0f460R102-R122)
* Demonstrate creating an odata query/listing entities
  * Most users
  * [.NET Sync](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/tests/samples/Sample4_QueryEntities.cs) | [.NET Async](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/tests/samples/Sample4_QueryEntitiesAsync.cs) | [Javascript](https://github.com/mahdiva/azure-sdk-for-js/pull/1/files?file-filters%5B%5D=.ts#diff-34dd59109b4c0b1237b82fb8d1c0f460R124-R140)

**Comment by lilyjma** [comment]
scheduled for 7/29. Please include link to output of api-extractor as a Draft PR @meanjeekim

**Comment by lilyjma** [comment]
@meanjeekim please submit the PR ASAP because architects need time to review it before discussion.

**Comment by meanjeekim** [comment]
@mahdiva Please put your links in!

**Comment by lilyjma** [comment]
[MS Internal Only] [Video](https://msit.microsoftstream.com/video/0d42a1ff-0400-a521-a5b4-f1ead1f077df)

ACTION ITEMS:

**.Net** 

_**Table**_ 

In _CreateDeleteTableAsync.cs_ sample: 

Creating a table with a name that already exists
- either add `createIfNotExist` or create an exception 
- need to be clear about why exception is thrown (might not be b/c table name exists)
- use unambiguous response code 

For `DeleteTable` if exists, close the discussion with architects @johanste @KrzysztofCwalina 

`QueryTablesAsync()`
- change label to something else; make other changes needed
- keep in mind, customers might copy paste samples, so make it reliable 

@KrzysztofCwalina: discuss with other architects on how to make samples reliable 

**Entity**

In _CreateDeleteEntitiesAysnc.cs_ sample: 

According to guideline, if something is called client, must have constructor 
- add constructor to Table client

@johanste, @KrzysztofCwalina, @JeffreyRichterMS, @bterlson, @JonathanGiles: discuss serialization of bring your own type; Partition key name casing

@meanjeekim: Look at Krzysztof's comment in API view on verbs


**APIView**

`SetAccessPolicyAsyc()`
- inconsistent with sync version
- get rid of `tableAcl = null` in sync version 

`DynamicTableEntity()` 
- make default entity without partition key and row key (most common case they'd have unique identity)

`public override string eTag {get; set;}`
- maybe don't need setter
- @meanjeekim follow up with @KrzysztofCwalina 

`TableSasIPRange `
- @KrzysztofCwalina: follow up with other architects about this name 


**JS**

JS sample: 

`async function CreateEntity()`
- are concern about `PartitionKey` and `RowKey` in Pascal case for JS devs? 
- recase them b/c confusing, in addition to the reason above 
    - (but this could cause confusing in serialization)
- js-js roundtriping should work; input output should be same type
    - option: have what int64Prop has for int32Prop

@bterlson to follow up with other architects: 
- int32Prop and how service infers it; depends on serializer 

`deleteEntity()`
- star is confusing; should be default

Generally: 
- entity operations shouldn't be on service client; need table client
- this is skipping two levels, but shouldn't 

`getEntity()`
put entities on top level
use _ to pack other info away 

@mahdiva follow up off-line with @bterlson on APIView
