### ISSUE TITLE
Update docfx.yml for identical markdown naming across monikers

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#1590]
@ramya-rao-a brought up an extremely good point that the transition between monikers is pretty much impossible from the `overview` selection.

Right now, `docs-ref-services/<target>.md` is referred to by all 3 of the monikers. This is configured in the `docfx.yml`. This means that a readme for `preview` HAS to have a different name than a readme for `latest`.

We should instead duplicate the `docs-ref-services` (or add subfolders) that can be named _the same_. Then, in the `docfx.yml`, we copy the source folder for the moniker _only_ to the target platform. This will allow each moniker to refer to the "same path", but have different published content.

I'm about 50/50 on whether the docs publishing will consume handle the above appropriately. Will need to prototype before we do this full scale.

**Comment by ramya-rao-a** [comment]
Closing in favor of #1825
