### ISSUE TITLE
Update Text Analytics package version 1 to 5 references

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk#1592]
**Java** 

- [x] [Quickstart](https://github.com/MicrosoftDocs/azure-docs-pr/blob/master/articles/cognitive-services/text-analytics/includes/quickstarts/java-sdk.md) Quote (dependency): 
```xml
<artifactId>azure-ai-textanalytics</artifactId>
<version>1.0.0</version>
```
- [x] [Quickstart](https://github.com/MicrosoftDocs/azure-docs-pr/blob/master/articles/cognitive-services/text-analytics/includes/quickstarts/java-sdk.md) Quote (underlying package link): `| Package |`  

- [x] [Quickstart](https://github.com/MicrosoftDocs/azure-docs-pr/blob/master/articles/cognitive-services/text-analytics/includes/quickstarts/java-sdk.md) Quote (underlying package link): `syntax for other build tools online`

- [x] [README](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/textanalytics/azure-ai-textanalytics/README.md)
Quote (dependency): 
```xml
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-ai-textanalytics</artifactId>
    <version>1.0.1</version>
</dependency>
```

**Python**

nothing 🎉

**C#**

- [x] [Quickstart](https://github.com/MicrosoftDocs/azure-docs-pr/blob/master/articles/cognitive-services/text-analytics/includes/quickstarts/csharp-sdk.md) Quote: `Select version 1.0.0, and then Install`

**JS**

- [x] [Quickstart](https://github.com/MicrosoftDocs/azure-docs-pr/blob/master/articles/cognitive-services/text-analytics/includes/quickstarts/nodejs-sdk.md) Quote: `npm install --save @azure/ai-text-analytics@1.0.0`

- [x] [Quickstart](https://github.com/MicrosoftDocs/azure-docs-pr/blob/master/articles/cognitive-services/text-analytics/includes/quickstarts/nodejs-sdk.md) Quote: 
```
> [!NOTE]
> In version `3.0-preview`:
```

**General**

- [x] [TOC](https://github.com/MicrosoftDocs/azure-docs-pr/blob/master/articles/cognitive-services/text-analytics/toc.yml) Quote (should change the name and the link): 
```xml
  - name: Text Analytics API
    items:
      - name: v3.0-preview
        href: https://westus.dev.cognitive.microsoft.com/docs/services/TextAnalytics-v3-0-Preview-1
```
Link should be `https://westus.dev.cognitive.microsoft.com/docs/services/TextAnalytics-v3-0/operations/Languages`

- [x] [TOC](https://github.com/MicrosoftDocs/azure-docs-pr/blob/master/articles/cognitive-services/text-analytics/toc.yml) Quote (should change the name): 

```xml
  - name: SDKs
    items:
    - name: v3.0-preview
```

- [ ] Ref docs should be re-released (together with the updated READMEs)

**Comment by maririos** [comment]
@kaerm  do you know who owns the TOC documents?

**Comment by kaerm** [comment]
Normally the content team, but I submitted a PR for this https://github.com/MicrosoftDocs/azure-docs-pr/pull/124240 and just waiting for @aahill to review.

**Comment by aahill** [comment]
Thanks @kaerm the PR looks good, and should be merged soon. It'll go live today w/ the 4pm publish.

**Comment by kaerm** [comment]
Great! I am closing this issue then
