### ISSUE TITLE
Setup Storage CI to run against Azurite

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#1596]
Let's get our CI setup to run the following libs against [Azurite](https://github.com/Azure/Azurite/) (Cross Platform Azure Storage Emulator) instead of the live service.
- Blob
- Queue
- Table (coming soon)

You need to start Azurite with `--oauth basic` and HTTPS cert/key combo.  You can find more here: https://github.com/Azure/Azurite/#azure-sdks

**Comment by kurtzeborn** [comment]
@jongio, are you talking about setting up a new CI pipline for simplified scenarios, or for all of our live tests for these services to use Azureite instead?  We definitely discussed the latter before and determined it wasn't possible because Azurite tends to trail the service (and the SDK libraries) as new features are added.  This means that we'd have new features added to the SDK libraries (and their live tests) often months before Azurite adds support for them.

CC: @pemari-msft, @amishra-dev, @vinjiang

**Comment by jongio** [comment]
The goal is to understand and document which SDK capabilities work or do not work when run against Azurite.  Very similar to how we run our tests against Cosmos Emulator.  @danieljurek has info.

**Comment by kasobol-msft** [comment]
I have a bunch of test for Storage Webjobs extension that I converted from running against handcrafted "Storage Fake" to run against Azurite. See https://github.com/Azure/azure-sdk-for-net/pull/13691 for reference. This works pretty well as Webjobs don't use all Storage features so Azurite lagging behind isn't a big issue.
@danieljurek @jongio The tests against Cosmos Emulator - do you run them as a part of CI build(s) ? if so - could you point me to how this is set up? I'd like to run webjobs tests against Azurite as part of Storage CI at some point. I.e. I'd need Azurite installed on agents and have access to it's location.

**Comment by danieljurek** [comment]
We have 3 examples of the cosmos emulator running in our CI builds today. For reference the term "CI" means many things to many people but for our purposes it means "tests which we can run quickly against PRs and which do not communicate with live resources" 

Python: https://github.com/Azure/azure-sdk-for-python/blob/master/eng/pipelines/templates/stages/cosmos-sdk-client.yml

Java: https://github.com/Azure/azure-sdk-for-java/blob/master/eng/pipelines/templates/stages/cosmos-sdk-client.yml

JS: https://github.com/Azure/azure-sdk-for-js/blob/master/eng/pipelines/templates/stages/cosmos-sdk-client.yml

In these cases we install the emulator on the machine, set some environment variables, and run the tests.

**Comment by danieljurek** [comment]
I should also caution from above that the storage emulator is not an accurate representation of APIs available in production for storage services so your tests will need to take this into account.

**Comment by christothes** [comment]
What's the latest on this capability becoming available in our CIs? I believe azurite is close to adding full support for Tables and it would be nice to add it as an additional endpoint to run the test suite against.

**Comment by kasobol-msft** [comment]
@christothes  You may find this useful:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/tests/Shared/AzuriteNUnitFixture.cs

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/tests/Shared/AzuriteFixture.cs

https://github.com/Azure/azure-sdk-for-net/blob/9375591437bd8d6e71c9178199caf504ffa12856/sdk/storage/ci.yml#L55

https://github.com/Azure/azure-sdk-for-net/blob/9375591437bd8d6e71c9178199caf504ffa12856/sdk/storage/tests.yml#L24

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/tests-install-azurite.yml
