### ISSUE TITLE
Tool to bootstrap new data plane library

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#160]
We currently have templates for each language ([.Net example](https://github.com/Azure/azure-sdk-for-net/tree/master/src/SDKs/Template/data-plane)) but for someone to start a new library they have to copy/paste the template and rename a bunch of things.  Inevitably, someone will forget to generate new solution guids or other things that need to be created fresh.

# Goal
Write a tool to copy the template for each language, ask a few questions about what's being created (class names, etc.) and do all of the renaming, guid generation, etc. to set up the project.

**Comment by Petermarcu** [comment]
Lets not create our own templating engine :)

**Comment by kurtzeborn** [comment]
We already have a template for each language and on-boarding documentation.  These should be sufficient for anyone needing to perform the rare task of creating a library in the repo.
