### ISSUE TITLE
Board Review: FieldBuilder for Azure Cognitive Search SDK (.NET, Java)

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk#1601]
## About this client library

* Name of the client library: Azure.Search.Documents
* Languages for this review: C#, Java
* Link to the service REST APIs: N/A

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/d40a51d26cf2444a85d302758ca3a2d1#Azure.Search.Documents.Indexes.FieldBuilder
* Link to samples for champion scenarios: https://github.com/heaths/azure-sdk-for-net/pull/3/files#diff-ef10b1756fdcd3e70f5773a94a804420R209-R217

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  [Link](https://apiview.dev/Assemblies/Review/8b261dc63f3e4ed3afe0c8a73b513e3c)
* Link to samples for champion scenarios: [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/FieldBuilderExample.java)

### Champion Scenario 1

`FieldBuilder` is a static method that takes a model and generates fields from that model using the `ObjectSerializer` the user specified (defaulting in .NET to `System.Text.Json`). The goal, along with #1586, is to use the same logic as the serializers to get field names (Search indexes are case-sensitive) and types to use for fields. This ensures that when the users de/serialize the models, they work correctly with the index they created from the models.

Conceptual example:
```csharp
var index = SearchIndex("hotels")
{
  Fields = FieldBuilder.Build(typeof(Hotel))
}
client.CreateIndex(index);

var hotels = new[]
{
  Hotel("1", "Foo"),
  Hotel("2", "Bar")
]
client.UploadDocuments(hotels);
```

This also includes 2 attributes (.NET; in Java, annotations) to set Search-specific field properties like so:

```csharp
class Hotel
{
  [SimpleField(IsKey = true)]
  public string Id {get; set;}

  [SearchableField(IsFilterable = true, AnalyzerName = LexicalAnalyzerName.AsString.EnLucene)]
  public string Name {get;set;}
}
```

**Comment by lilyjma** [comment]
@heaths I recall that there was a meeting about this. Can this issue be closed now?
