### ISSUE TITLE
Change Request: Versioning for Java, ARM (Azure resource manager) SDK (fully generated)

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk#1612]
Thank you for contributing to the design guidelines for Azure SDKs.  We welcome all discussions and contributions.  Since the design guidelines affect the client libraries for all Azure services, we thoroughly discuss and vet any design guideline changes before we incorporate them into the official guidance.  This process can take some time, so your patience is appreciated.

** Before submitting, ensure you adjust the title of the issue appropriately **

(Currently apply to fully generated Java ARM SDK)

## The Basics

* Which design guideline is affected?
Versioning for ARM (Azure resource manager) SDK
https://azure.github.io/azure-sdk/java_design.html#versioning

* Which target languages are affected?
Java

* Describe the change:
Guidance on semantic version for breaking changes.

## Reasoning

Facts:
1. ARM swagger spec upgrades api-version frequently, and often api-version upgrade is accompanied by breaking changes.
2. There is small change that breaking changes happens within same api-version (mostly due to bug fixes).
3. Many ARM SDK is automatic generated (Java, .NET, Python, etc), it is often not feasible to provide backwards compatibility, when swagger spec breaks.

Request:
1. Whether it is worthwhile for Arch board to provide guideline for versioning on Java ARM SDK.
2. If yes, discussion and design of the guideline.
3. Would it help to sync with .NET and Python.

Our proposal:

Plan is to follow semantic versioning.
1. If there is no breaking changes on latest stable service spec, SDK would increment minor version if new api-version, or increment patch version if same api-version.
2. If there is breaking changes on latest stable service spec, SDK would increment major version.
3. If there is breaking changes on non-latest stable service spec (and the next major version is already occupied by a later-version stable service spec), we might first push back the request. If we had to release a patch, SDK only incremental patch version (and try to explain the breaking changes elsewhere, in description etc.).
4. For non-stable service spec, we only release beta versioned SDK as preview.

Above is similar to what Python ARM SDK is doing currently.

There is one major difference between Java ARM SDK and Python ARM SDK. Python ARM SDK releases in multi-api mode (that one package contains code on multiple api-versions), while Java ARM SDK releases single api-version.

@JonathanGiles @yungezz @allenjzhang

**Comment by yungezz** [comment]
ping. HI @kyle-patterson , what's next step for this review? Will there be a meeting or email reviewing? thanks.

**Comment by lilyjma** [comment]
@weidongxu-microsoft, @yungezz : I understand that this has been reviewed. Please feel free to reopen the issue if there's any open question/follow up. Thanks!
