### ISSUE TITLE
Releases page: Track 1 GA versions

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#1613]
Some langs have Track 1 GA versions, some don't

![image](https://user-images.githubusercontent.com/2163001/89196689-6917d380-d55f-11ea-9781-51614996f2cb.png)

**Comment by weshaggard** [comment]
The only cases that should have track 1 versions are the ones where the package name doesn't change (i.e. js and python). While I can do something special and block those I don't think it is worth the effort as they will disappear as soon as we GA the track 2 version.

**Comment by weshaggard** [comment]
I'm going to close this as I don't think it is worth the efforts to fix. Please re-open if you feel differently.
