### ISSUE TITLE
Board Review: Introduction to Application Insights

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk#1621]
Thank you for starting the process for approval of the client library for your Azure service.  A thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Reiley Yang (@reyang)
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview
* Contact email (if service team, provide PM and Dev Lead): Reiley Yang (@reyang)

## About this client library

* Name of the client library: **Azure Monitor Exporters for OpenTelemetry**
* Languages for this review: All languages (this is an introductory session)
* Link to the service REST APIs:
    * The existing API is called `Breeze`. It is very old and strictly speaking not RESTful at all. The current document is [here](https://github.com/microsoft/ApplicationInsights-Home/tree/master/EndpointSpecs).
    * There has been discussion to move to a new ingestion API (which is under construction), it will not be ready by end of 2020. So we'll be focusing on Breeze at this moment.

[OpenTelemetry](https://opentelemetry.io) is a project under [CNCF](https://www.cncf.io), according to its own definition "OpenTelemetry provides a single set of APIs, libraries, agents, and collector services to capture distributed traces and metrics from your application".

The components being reviewed are called `Exporters` in OpenTelemetry term. Exporters have different types, each dealing with certain type of telemetry data (e.g. traces, metrics, logs). Here goes the spec for [trace/span exporter](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#span-exporter)

The components being reviewed are vendor specific plugins developed and maintained by Microsoft, which subscribe the data from OpenTelemetry SDK, convert and send the data to Azure Monitor via Breeze. Here goes a concrete example of the [Azure Monitor Exporters for OpenTelemetry Python](https://github.com/microsoft/opentelemetry-azure-monitor-python).

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Send tracing data to Azure Monitor for troubleshooting and business analytics.
    * >50% of the user would enable this feature.
    * Link to the code sample: https://github.com/microsoft/opentelemetry-azure-monitor-python#trace

* Champion Scenario 2:
    * Send metrics data to Azure Monitor and set alerting rules based on the metrics.
    * >50% of the user would enable this feature.
    * Link to the code sample: https://github.com/microsoft/opentelemetry-azure-monitor-python#metrics

* Champion Scenario 3:
    * Send correlated logs (log entries that have distributed tracing information/context associated) for troubleshooting.
    * >50% of the user would enable this feature.
    * Link to the code sample: N/A (currently under construction)

* Champion Scenario 4:
    * Turn on the [Live Stream](https://docs.microsoft.com/en-us/azure/azure-monitor/app/live-stream) and see near-realtime telemetry from Azure Portal.

Examples of good scenarios are technology agnostic (i.e. the customer can do the same thing in multiple ways), and are expected to be used by > 20% of users:

* Upload a file
* Update firmware on the device
* Recognize faces in an uploaded image

Examples of bad scenarios:
* Create a client (it's part of a scenario, and we'll see it often enough in true champion scenarios)
* Send a batch of events (again, part of the scenario)
* Create a page blob (it's not used by enough of the user base)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
scheduled for 8/20

**Comment by lilyjma** [comment]
@srnagar @reyang : please include champion scenario code for all languages. If you have API Listings, include them as well at least 5 business days before the review; architects will need some time to look through them before the review.

**Comment by lilyjma** [comment]
Hi Architects @KrzysztofCwalina @bterlson @JonathanGiles @johanste @JeffreyRichter, I've confirmed with the issue creator that this review is purely an introductory one--the team doesn't have API to review yet.

**Comment by srnagar** [comment]
Closing this issue in favor of https://github.com/Azure/azure-sdk/issues/1975
