### ISSUE TITLE
Update to Release Folder Pipeline

### ISSUE THREAD

**Issue by czubair** [Azure/azure-sdk#1623]
Request to split the release folder pipeline into two parts: one that creates the release folder structure and one that adds it to the sidebar

Goal: to be able to publish the release folder so out-of-band release can add release notes but the sidebar is published separately

**Comment by weshaggard** [comment]
By default running the pipeline will have PublishRelease set to false and it will only generate the folder structure and placeholder release note pages. When you are ready to publish you run the pipeline again ans set PublishRelease to true and it will only do the generation of the sidebar to publish the release.
