### ISSUE TITLE
Update Azure SDK site landing page

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#1627]
We have a blog here: https://aka.ms/azsdk/blog
All of that content is duplicated here: https://azure.github.io/azure-sdk/

Duplicated content hurts SEO.

Remove the content from the GH site.

Update the landing page to read from the devblogs RSS feed.

**Comment by jongio** [comment]
@weshaggard 

We need to update the landing page to pull from RSS feed: https://devblogs.microsoft.com/azure-sdk/feed/

We can do this server or client side:

## Server
1. Jekyll/Liquid only supports JSON, YML, or CSV as data files.
1. We need to convert the RSS/XML feed to one of the supported formats and put in the _data folder.
1. We need to convert the landing page to render the data from that _data folder.
1. We need to set that pull and conversion to run on a regular basis (daily).

## Client
1. We could update the landing page to pull the RSS feed via JavaScript. 
1. This is less engineering and since it is only a small blurb of the items and not needed for SEO. It might be the better option.

Thoughts?

**Comment by weshaggard** [comment]
Do you think we really need to integrate the blog content? What about just making the landing page show all the releases and have a link to the blog?

**Comment by jongio** [comment]
@Petermarcu - Are you okay with having the root of our site https://aka.ms/azsdk be the releases list and not the recent blog summary?  I like it. But, I wasn't around when those decisions were made, so want to make sure you are okay with it.

**Comment by Petermarcu** [comment]
I dont know that any decisions were actually made. I'm ok either way on this right now.

**Comment by jongio** [comment]
Here's what we should do for now: 

1. auto-redirect the current index page to /releases
2. remove the blog content from the sdk site - we'll need to figure out how to best do this.

**Comment by jongio** [comment]
We'll likely need to move our blog content to a different private repo, that way it is not duplicated on GH pages site and WP site. Still researching.

**Comment by weshaggard** [comment]
We can exclude parts of the repo from jekyll view, like https://github.com/Azure/azure-sdk/blob/master/_config.yml#L30.

**Comment by jongio** [comment]
Right, but Google will still index the repo, which we don't want for blog.  We only want the WP site to be indexed.
