### ISSUE TITLE
API Proposal: Add DeviceStream APIs to IoT Hub Device SDK (C)

### ISSUE THREAD

**Issue by wickste** [Azure/azure-sdk#163]
# Overview
Azure IoT Hub device streams facilitate the creation of secure bi-directional TCP tunnels for a variety of cloud-to-device communication scenarios. A device stream is mediated by an IoT Hub streaming endpoint which acts as a proxy between your device and service endpoints. This setup is especially useful when devices are behind a network firewall or reside inside of a private network. As such, IoT Hub device streams help address customers' need to reach IoT devices in a firewall-friendly manner and without the need to broadly opening up incoming or outgoing network firewall ports. Using IoT Hub device streams, devices remain secure and will only need to open up outbound TCP connections to IoT hub's streaming endpoint over port 443. Once a stream is established, the service-side and device-side applications will each have programmatic access to a WebSocket client object to send and receive raw bytes to one another. The reliability and ordering guarantees provided by this tunnel is on par with TCP.

# Device Stream Workflow
A device stream is initiated when the service requests to connect to a device by providing its device ID. This workflow particularly fits into a client/server communication model, including SSH and RDP, where a user intends to remotely connect to the SSH or RDP server running on the device using an SSH or RDP client program.
The device stream creation process involves a negotiation between the device, service, IoT hub's main and streaming endpoints. While IoT hub's main endpoint orchestrates the creation of a device stream, the streaming endpoint handles the traffic that flows between the service and device.
## Device stream creation flow
Programmatic creation of a device stream using the SDK involves the following steps:
1. The device application registers a callback in advance to be notified of when a new device stream is initiated to the device. This step typically takes place when the device boots up and connects to IoT Hub.
2. The service-side program initiates a device stream when needed by providing the device ID (not the IP address).
3. IoT hub notifies the device-side program by invoking the callback registered in step 1. The device may accept or reject the stream initiation request. This logic can be specific to your application scenario. If the stream request is rejected by the device, IoT Hub informs the service accordingly; otherwise, the steps below follow.
4. The device creates a secure outbound TCP connection to the streaming endpoint over port 443 and upgrades the connection to a WebSocket. The URL of the streaming endpoint as well as the credentials to use to authenticate are both provided to the device by IoT Hub as part of the request sent in step 3.
5. The service is notified of the result of device accepting the stream and proceeds to create its own WebSocket client to the streaming endpoint. Similarly, it receives the streaming endpoint URL and authentication information from IoT Hub.

In the handshake process above:
* The handshake process must complete within 60 seconds (step 2 through 5), otherwise the handshake would fail with a timeout and the service will be notified accordingly.
* After the stream creation flow above completes, the streaming endpoint will act as a proxy and will transfer traffic between the service and the device over their respective WebSockets.
* Device and service both need outbound connectivity to IoT Hub's main endpoint as well as the streaming endpoint over port 443. The URL of these endpoints is available on Overview tab on the IoT Hub's portal.
* The reliability and ordering guarantees of an established stream is on par with TCP.
* All connections to IoT Hub and streaming endpoint use TLS and are encrypted.

## Termination Flow
An established stream terminates when either of the TCP connections to the gateway are disconnected (by the service or device). This can take place voluntarily by closing the WebSocket on either the device or service programs, or involuntarily in case of a network connectivity timeout or process failure. Upon termination of either device or service's connection to the streaming endpoint, the other TCP connection will also be (forcefully) terminated and the service and device are responsible to re-create the stream, if needed.

# SDK Availability
Two sides of each stream (on the device and service side) use the IoT Hub SDK to establish the tunnel. During public preview, customers can choose from the following SDK languages:
* The C and C# SDK's support device streams on the device side.
* The Node.js and C# SDK support device streams on the service side.

# Sample Code (C)
This echo sample demonstrates programmatic use of device streams to send and receive bytes between service and device applications. To execute the scenario end to end, use the corresponding C# or Node.js sample for the service side.

## Device Sample Code (C)
Full sample project [here](https://github.com/Azure/azure-iot-sdk-c/tree/public-preview/iothub_client/samples/iothub_client_c2d_streaming_sample)

Creating the device client using your device connection string and desired protocol (existing APIs): 
```C
// Used to initialize IoTHub SDK subsystem
(void)IoTHub_Init();

IOTHUB_DEVICE_CLIENT_HANDLE device_handle;

// Create the iothub handle here
device_handle = IoTHubDeviceClient_CreateFromConnectionString(connectionString, protocol);
```

Listening for device stream requests (new APIs):
```C
if (IoTHubDeviceClient_SetStreamRequestCallback(device_handle, streamRequestCallback, NULL) != IOTHUB_CLIENT_OK)
{
    (void)printf("Failed setting the stream request callback");
}
else
{
    do
    {
        if (g_uws_client_handle != NULL)
        {
            uws_client_dowork(g_uws_client_handle);
        }

        ThreadAPI_Sleep(100);
    } while (g_continueRunning);
}
```

Handling the stream request callback (new APIs):
```C
static DEVICE_STREAM_C2D_RESPONSE* streamRequestCallback(DEVICE_STREAM_C2D_REQUEST* stream_request, void* context)
{
    (void)context;

    (void)printf("Received stream request (%s)\r\n", stream_request->name);

    g_uws_client_handle = create_websocket_client(stream_request);

    return stream_c2d_response_create(stream_request, true);
}
```

# New API Surface added (C)
Reference to existing IoTHub client APIs [(link)](https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-client-h)
## IoTHub Device SDK additions
```C
typedef struct DEVICE_STREAM_C2D_REQUEST_TAG
{
    /**
    * @brief    Name of the stream. This is a null-terminated string.
    */
    char* name;
    /**
    * @brief    Websockets URL to connect to the streaming gateway. This is a null-terminated string.
    */
    char* url;
    /**
    * @brief    Authorization token to be provided to the streaming gateway upon connection. This is a null-terminated string.
    */
    char* authorization_token;
    /**
    * @brief    Request ID used to correlate requests and responses. Do not modify its value.
    */
    char* request_id;
} DEVICE_STREAM_C2D_REQUEST;

typedef struct DEVICE_STREAM_C2D_RESPONSE_TAG
{
    /**
    * @brief    Indicates if the stream request was accepted or rejected by the local endpoint. Use true to accept, or false to reject.
    */
    bool accept;
    /**
    * @brief    Request ID used to correlate requests and responses. Do not modify its value.
    */
    char* request_id;
} DEVICE_STREAM_C2D_RESPONSE;

/**
* @brief     Callback invoked for new cloud-to-device stream requests.
* @param     request         Contains the basic information to connect to the streaming gateway, as well as optional custom data provided by the originating endpoint.
* @param     context         User-defined context, as provided in the call to *_SetStreamRequestCallback.
* @return    An instance of DEVICE_STREAM_C2D_RESPONSE indicating if the stream request is accepted or rejected.
*/
typedef DEVICE_STREAM_C2D_RESPONSE* (*DEVICE_STREAM_C2D_REQUEST_CALLBACK)(DEVICE_STREAM_C2D_REQUEST* request, void* context);

DEVICE_STREAM_C2D_RESPONSE* stream_c2d_response_create(DEVICE_STREAM_C2D_REQUEST* request, bool accept);

IOTHUB_CLIENT_RESULT IoTHubDeviceClient_SetStreamRequestCallback(IOTHUB_DEVICE_CLIENT_HANDLE iotHubClientHandle, DEVICE_STREAM_C2D_REQUEST_CALLBACK streamRequestCallback, void* context);
IOTHUB_CLIENT_RESULT IoTHubModuleClient_SetStreamRequestCallback(IOTHUB_MODULE_CLIENT_HANDLE iotHubModuleClientHandle, DEVICE_STREAM_C2D_REQUEST_CALLBACK streamRequestCallback, void* context);
```

**Comment by adrianhall** [comment]
This has now been open for 8 weeks.  Any further action required on this?

**Comment by adrianhall** [comment]
Closing for lack of movement.
