### ISSUE TITLE
Specify Additional Documentation Files in Artifacts

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#1634]
@schaabs has a feature ask.

What if we have some conceptual documentation that we ALSO want to keep updated? In the example that I was given, we want to keep some additional detailed documentation for `azure-identity` up to date. This means that we want these additional markdowns to be copied over along with the formatted readme. I believe a good place to define this as an additional array of paths associated with the artifact. Call it `AdditionalDocuments` or the like, and make them relative paths to the `ServiceDirectory`.

You could think of the `Service` level readme as a specific implementation of this generic feature. I'm fairly confident I will approach it that way and end up closing the `service` readme issue as duplicate.

**Comment by scbedd** [comment]
Additional request that [plays into this issue](https://github.com/Azure/azure-docs-sdk-java/pull/1121#issuecomment-674712226).

**Comment by danieljurek** [comment]
Handwritten docs that live in the docs repo and are not automatically published should be associated with docs generated by a package release. This way changes to handwritten docs will release when a package is published.

**Comment by kurtzeborn** [comment]
We're no longer supporting handwritten docs outside of our repos.  Sima sent mail announcing that we were dropping support on these months ago.
