### ISSUE TITLE
Board Review:  new Search Index Document Batching Client feature

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk#1637]
## The Basics

* Service team responsible for the client library: Azure Cognitive Search 
* Link to documentation describing the service:  https://docs.microsoft.com/en-us/azure/search/
* Contact email (if service team, provide PM and Dev Lead): 
brjohnst@microsoft.com
maheff@microsoft.com

## About this client library

* Name of the client library: azure-search-documents
* Languages for this review: Python
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/search/data-plane/Azure.Search/preview/2020-06-30-Preview

### Python

* [apiview](https://apiview.dev/Assemblies/Review/b8c9d2f3e54d499d80479792af175b1f?diffRevisionId=3870e79f67004bfaa7acef476f07bac8)
* Upload the api as a Draft PR.  Link to PR: https://github.com/Azure/azure-sdk-for-python/pull/12622
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/search/azure-search-documents/samples/sample_batch_client.py

### Java

* [APIView](https://apiview.dev/Assemblies/Review/f8224ac5afc64604ac98249cefa0c7f7?diffRevisionId=c7993ee3b51048868babb09cc48e1413)
* [Draft PR](https://github.com/Azure/azure-sdk-for-java/pull/14190)
* Samples (to be done)

### C#
* [ApiView](https://apiview.dev/Assemblies/Review/cff09959425c4673b22c4a5816cd927a?diffRevisionId=72dc3ae1bb234830b505210ddbecff85)
* [Champion Scenarios](https://gist.github.com/tg-msft/e8dd0d07f22578ea2c8fde083932f9b9)

**Comment by lilyjma** [comment]
scheduled for 8/18

**Comment by xiangyan99** [comment]
Done.
