### ISSUE TITLE
API Proposal: Add DeviceStream APIs to IoT Hub Service SDK (Node.JS)

### ISSUE THREAD

**Issue by wickste** [Azure/azure-sdk#164]
# Overview
Azure IoT Hub device streams facilitate the creation of secure bi-directional TCP tunnels for a variety of cloud-to-device communication scenarios. A device stream is mediated by an IoT Hub streaming endpoint which acts as a proxy between your device and service endpoints. This setup is especially useful when devices are behind a network firewall or reside inside of a private network. As such, IoT Hub device streams help address customers' need to reach IoT devices in a firewall-friendly manner and without the need to broadly opening up incoming or outgoing network firewall ports. Using IoT Hub device streams, devices remain secure and will only need to open up outbound TCP connections to IoT hub's streaming endpoint over port 443. Once a stream is established, the service-side and device-side applications will each have programmatic access to a WebSocket client object to send and receive raw bytes to one another. The reliability and ordering guarantees provided by this tunnel is on par with TCP.

# Device Stream Workflow
A device stream is initiated when the service requests to connect to a device by providing its device ID. This workflow particularly fits into a client/server communication model, including SSH and RDP, where a user intends to remotely connect to the SSH or RDP server running on the device using an SSH or RDP client program.
The device stream creation process involves a negotiation between the device, service, IoT hub's main and streaming endpoints. While IoT hub's main endpoint orchestrates the creation of a device stream, the streaming endpoint handles the traffic that flows between the service and device.
## Device stream creation flow
Programmatic creation of a device stream using the SDK involves the following steps:
1. The device application registers a callback in advance to be notified of when a new device stream is initiated to the device. This step typically takes place when the device boots up and connects to IoT Hub.
2. The service-side program initiates a device stream when needed by providing the device ID (not the IP address).
3. IoT hub notifies the device-side program by invoking the callback registered in step 1. The device may accept or reject the stream initiation request. This logic can be specific to your application scenario. If the stream request is rejected by the device, IoT Hub informs the service accordingly; otherwise, the steps below follow.
4. The device creates a secure outbound TCP connection to the streaming endpoint over port 443 and upgrades the connection to a WebSocket. The URL of the streaming endpoint as well as the credentials to use to authenticate are both provided to the device by IoT Hub as part of the request sent in step 3.
5. The service is notified of the result of device accepting the stream and proceeds to create its own WebSocket client to the streaming endpoint. Similarly, it receives the streaming endpoint URL and authentication information from IoT Hub.

In the handshake process above:
* The handshake process must complete within 60 seconds (step 2 through 5), otherwise the handshake would fail with a timeout and the service will be notified accordingly.
* After the stream creation flow above completes, the streaming endpoint will act as a proxy and will transfer traffic between the service and the device over their respective WebSockets.
* Device and service both need outbound connectivity to IoT Hub's main endpoint as well as the streaming endpoint over port 443. The URL of these endpoints is available on Overview tab on the IoT Hub's portal.
* The reliability and ordering guarantees of an established stream is on par with TCP.
* All connections to IoT Hub and streaming endpoint use TLS and are encrypted.

## Termination Flow
An established stream terminates when either of the TCP connections to the gateway are disconnected (by the service or device). This can take place voluntarily by closing the WebSocket on either the device or service programs, or involuntarily in case of a network connectivity timeout or process failure. Upon termination of either device or service's connection to the streaming endpoint, the other TCP connection will also be (forcefully) terminated and the service and device are responsible to re-create the stream, if needed.

# SDK Availability
Two sides of each stream (on the device and service side) use the IoT Hub SDK to establish the tunnel. During public preview, customers can choose from the following SDK languages:
* The C and C# SDK's support device streams on the device side.
* The Node.js and C# SDK support device streams on the service side.

# Sample Code (Node.js)
This echo sample demonstrates programmatic use of device streams to send and receive bytes between service and device applications. To execute the scenario end to end, use the corresponding C or C# sample for the device side.

## Service Sample Code (Node.js)
Full sample project [here](https://github.com/Azure-Samples/azure-iot-samples-node/tree/streams-preview/iot-hub/Quickstarts/device-streams-service)

```JavaScript
var websocket = require('websocket-stream')
var ServiceClient = require('azure-iothub').Client;

var streamInit = {
  streamName: 'TestStream',
  connectTimeoutInSeconds: 30,
  responseTimeoutInSeconds: 30,
}

var client = ServiceClient.fromConnectionString(process.env.IOTHUB_CONNECTION_STRING);

console.log('initiating stream');
client.initiateStream(process.env.STREAMING_TARGET_DEVICE, streamInit, function(err, result) {
  if (err) {
    console.error(err.toString());
    process.exit(-1);
  } else {
    console.log(JSON.stringify(result, null, 2));

    var ws = websocket(result.uri, { headers: { 'Authorization': 'Bearer ' + result.authorizationToken} });
    process.stdin.pipe(ws);
    ws.pipe(process.stdout);
  }
});
```

# New API Surface added (Node.js)
## IoTHub Service SDK
Existing API reference [here](https://docs.microsoft.com/en-us/javascript/api/azure-iothub/?view=azure-node-latest )  
```JavaScript
initiateStream(deviceId: string, streamInitiation: StreamInitiation, callback: (err: Error, result?: StreamInitiationResult) => void): void;

export interface StreamInitiation {
  streamName: string;
}

export class StreamInitiationResult {
  authorizationToken: string;
  isAccepted: boolean;
  streamName?: string;
  uri: string;
}
```

**Comment by bterlson** [comment]
Bits of feedback:

* Adjust terminology where appropriate ([guidelines](https://azuresdkspecs.z5.web.core.windows.net/#sec-terminology), specifically prefer "client library" over "SDK")
* Async via node callback patterns are out-dated. All async JS APIs must provide promise-based asynchrony ([guidelines](https://azuresdkspecs.z5.web.core.windows.net/#sec-modern-idiomatic-javascript)).

**Comment by pierreca** [comment]
@bterlson absolutely agree on the comment about promises. Our SDKs have undergone promisification at the same time as the device streams preview work so the branches crossed without touching and we still need to add the promise API but it'll be there.

**Comment by pierreca** [comment]
Here's the full API including the promisified version:
```typescript
initiateStream(deviceId: string, streamInitiation: StreamInitiation): Promise<StreamInitiationResult>;
initiateStream(deviceId: string, streamInitiation: StreamInitiation, callback: (err: Error, result?: StreamInitiationResult) => void): void;
```

and the sample:
```typescript
import * as websocket from 'websocket-stream';
import { Client as ServiceClient } from 'azure-iothub';

const streamInit = {
  streamName: 'TestStream'
};

const client = ServiceClient.fromConnectionString(process.env.IOTHUB_CONNECTION_STRING);

const result = await client.initiateStream(process.env.STREAMING_TARGET_DEVICE, streamInit);
console.log(JSON.stringify(result, null, 2));

const ws = websocket(result.uri, { headers: { 'Authorization': 'Bearer ' + result.authorizationToken} });
process.stdin.pipe(ws);
ws.pipe(process.stdout);
```

**Comment by bterlson** [comment]
* Does the sample need to rename the Client import to ServiceClient?
* For readme purposes, wrapping the code in an async function main enables copy-pastability (await is not allowed at the top level unfortunately).
* Sample needs to enable esModuleInterop (`import * as websocket` is non-standard syntax that will cause significant interop issues, I have a [draft gist](https://gist.github.com/bterlson/017de02afd30fd98ab321f892a32f343) I never got around to polishing that might explain the issue some).
* Are browsers supported? This authorization scheme will be difficult to work with there if so - you can't actually set headers for the websocket's handshake.
* Asking users to set headers might be too low-level, so could consider doing that work for users. That said, it's important to support a variety of web socket implementations so maybe this is impossible in practice...

**Comment by pierreca** [comment]
> * Does the sample need to rename the Client import to ServiceClient?

copy/pasta snafu. no need, i removed this.

> * For readme purposes, wrapping the code in an async function main enables copy-pastability (await is not allowed at the top level unfortunately).

sure - usually we structure our samples so that they run directly from the command line. will update this.

> * Sample needs to enable esModuleInterop (`import * as websocket` is non-standard syntax that will cause significant interop issues, I have a [draft gist](https://gist.github.com/bterlson/017de02afd30fd98ab321f892a32f343) I never got around to polishing that might explain the issue some).

will take a look.. went with old typescript habits rather than es6 purity, I'm not familiar with the problem you're talking about.

> * Are browsers supported? This authorization scheme will be difficult to work with there if so - you can't actually set headers for the websocket's handshake.

Browsers are not supported. this is a long term goal but for now we have dependencies on core node packages so we don't support browsers. If you have a suggestion to future-proof this API for browsers, I'd happily integrate this to boot.

> * Asking users to set headers might be too low-level, so could consider doing that work for users. That said, it's important to support a variety of web socket implementations so maybe this is impossible in practice...

the thing I wanted to avoid here is to force the users into a particular websocket/stream implementation/library dependency. it's just an example on how to set up stdin/stdout piping from the terminal. again, i'm open to suggestions on how to better demonstrate the websocket and "standard" streaming part of it.

**Comment by bterlson** [comment]
> went with old typescript habits rather than es6 purity, I'm not familiar with the problem you're talking about.

Let me know if the blog helps or doesn't!

> core node packages so we don't support browsers. If you have a suggestion to future-proof this API for browsers, I'd happily integrate this to boot.

Core node packages aren't necessarily a blocker - shims exist that re-implement node APIs in the browser. But some things can't be implemented uniformly, and in such cases you end up having separate node and browser implementations. So in general, future proofing means: avoiding built-in Node APIs where possible, and being aware of equivalent browser APIs and limitations thereof (e.g. WebSocket is a thing, but you can't set headers).

**Comment by pierreca** [comment]
@bterlson one of the feedback/discussion that we have gone through and where we'd gladly take feedback is whether this API should expose the websocket or a stream object...

**Comment by bterlson** [comment]
Can I see an example of what either would look like in situ?

**Comment by pierreca** [comment]
we have 2 examples/quickstarts, maybe that'll give more context?

- [echo](https://github.com/Azure-Samples/azure-iot-samples-node/blob/streams-preview/iot-hub/Quickstarts/device-streams-service/echo.js): this just pipes stdin/stdout through the websocket
- [proxy](https://github.com/Azure-Samples/azure-iot-samples-node/blob/streams-preview/iot-hub/Quickstarts/device-streams-service/proxy.js): this basically creates a small client that pipes anything (like: an SSH connection) from one socket through the websocket.

more explanations and steps for these in the [public docs](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-streams-overview)

Generally speaking it's about giving the user the most generic "pipe" possible to send/receive bytes.

**Comment by bterlson** [comment]
Gah looks like I didn't reply with my thoughts on streams vs. sockets. I think you can't get away from node streams with this kind of API - users will want to .pipe() like your samples show. This also allows you to be agnostic as to which websocket implementation users bring to the table.

Let me know if there's new stuff you'd like me to take a look at, otherwise I think we can close this.

**Comment by pierreca** [comment]
Thanks @bterlson 
I'm not sure I understand what you're saying: given the communication with the service happens over websockets, I can either:
1. provide a stream API and "Force" a dependency on a specific websocket implementation
2. provide a stream API and let the user inject their own websocket implementation (i'd have to see how that works...)
3. provide a websocket URI and samples to show how to turn that into a stream (what I'm doing now)

Which one are you advocating for?

**Comment by bterlson** [comment]
Definitely not 1 (can't force a websocket impl). 3 seems fine to me, but 2 seems friendliest if you can get there eventually. As an example, you can look at how [rhea handles this](https://github.com/amqp/rhea/blob/master/lib/ws.js) (rhea is used by service bus/event hub clients). Users can provide their own websocket constructor and rhea will new it up when it's needed.

**Comment by pierreca** [comment]
Thanks!! I'll definitely look into it. the feature is being delayed for a bit so I think we can close this for now @adrianhall

**Comment by adrianhall** [comment]
Awesome.  Re-engage if you need another API review of this.
