### ISSUE TITLE
Board Review: Event Grid [.NET/Java]

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-sdk#1645]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Event Grid team.
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/event-grid/ and https://docs.microsoft.com/en-us/azure/event-grid/edge/.
* Contact email (if service team, provide PM and Dev Lead): PM: jafernan@microsoft.com, Dev Lead: rajarv@microsoft.com. Dev: ahamad@microsoft.com 

## About this client library

* Name of the client library:  Event Grid
* Languages for this review: .Net, Java
* Link to the service REST APIs: swagger specs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventgrid/data-plane/Microsoft.EventGrid/stable/2018-01-01/EventGrid.json

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* API View: https://apiview.dev/Assemblies/Review/0e10b868b64345a1bb6558c08759e32a
* Champion scenarios: https://gist.github.com/kerri-lee/eead058755113edaae31ef948d47d725

### Java

* API View: https://apiview.dev/Assemblies/Review/85a811c75f714c65bf0a31575f432a6d
* Champion scenarios: https://gist.github.com/Soreloser2/dd0f34c66114114181250cd99bc788f1

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by ellismg** [comment]
This is for the initial review of the Event Grid APIs for .NET and Java.  We previously reviewed Python and TypeScript.

**Comment by lilyjma** [comment]
[MS internal only][Video](https://msit.microsoftstream.com/video/f003a4ff-0400-8385-da4a-f1eaed7055da)
