### ISSUE TITLE
Board Review: IotHub

### ISSUE THREAD

**Issue by vinagesh** [Azure/azure-sdk#1646]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: aziotjavacsharpsdk@microsoft.com
* Link to documentation describing the service: 
    https://docs.microsoft.com/en-us/azure/iot-hub/about-iot-hub
    https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins
    https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-management-overview
* Contact email (if service team, provide PM and Dev Lead): prmathur@microsoft.com, sejal.sharma@microsoft.com, vinagesh@microsoft.com

## About this client library

* Name of the client library: IotHub
* Languages for this review: C#
* Link to the service REST APIs: https://msazure.visualstudio.com/DefaultCollection/One/_git/Azure-IoT-Hub-Main?path=%2Fswagger%2F2020-03-13%2FService_2020-03-13.json

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/de72d4ed7a14476bb7b7df2b65d08be5
* Link to samples for champion scenarios:

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Provision and retire a device or module
    * https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/samples/IotHubClientSamples/DeviceIdentityLifecycleSamples.cs#49
    * https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/samples/IotHubClientSamples/ModuleIdentityLifecycleSamples.cs#L90
    * https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/samples/IotHubClientSamples/DeviceIdentityLifecycleSamples.cs#L228
    * https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/samples/IotHubClientSamples/ModuleIdentityLifecycleSamples.cs#L282

* Champion Scenario 2:
    * Configure software running on device/module
    * https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/samples/IotHubClientSamples/DeviceIdentityLifecycleSamples.cs#L182
    * https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/samples/IotHubClientSamples/ModuleIdentityLifecycleSamples.cs#L240

* Champion Scenario 3:
    * Configure device/module status
    * https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/samples/IotHubClientSamples/DeviceIdentityLifecycleSamples.cs#L116
    * https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/samples/IotHubClientSamples/ModuleIdentityLifecycleSamples.cs#L180

* Champion Scenario 4:
    * Invoke methods on a device/module
    * Reboot

* Champion Scenario 5:
    * Report status or progress of actions
    * https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/samples/IotHubClientSamples/DeviceIdentityLifecycleSamples.cs#L153
    * https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/samples/IotHubClientSamples/ModuleIdentityLifecycleSamples.cs#L214

* Champion Scenario 6:
    * Import/Export devices from one IoTHub to another

* Champion Scenario 7:
    * Schedule actions and property updates on device/module

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
scheduled for 8/19
