### ISSUE TITLE
Investigate using the common build template for Cosmos 

### ISSUE THREAD

**Issue by KarishmaGhiya** [Azure/azure-sdk#1650]
- Cosmos sdk pipeline doesn't use the common build template. Need to investigate if we need to add some more extension points that is better then duplicating the build template. This is true for javascript, python and java.

**Comment by weshaggard** [comment]
In particular we should look to remove these file:

https://github.com/Azure/azure-sdk-for-js/blob/master/eng/pipelines/templates/stages/cosmos-sdk-client.yml
https://github.com/Azure/azure-sdk-for-java/blob/master/eng/pipelines/templates/stages/cosmos-sdk-client.yml
https://github.com/Azure/azure-sdk-for-python/blob/master/eng/pipelines/templates/stages/cosmos-sdk-client.yml

Instead use the standard client yml templates. If needed we can add more extension points to enable any special cosmos scenarios but we need to remove the duplicated root templates. In the past release cycle there were at least 2 cases (https://github.com/Azure/azure-sdk-for-js/pull/10546/ and https://github.com/Azure/azure-sdk-for-js/pull/10550) were we missed updating these duplicated templates which caused cosmos builds to fail.

**Comment by kurtzeborn** [comment]
@sima-zhu, you'll want to work with @weshaggard to understand what's needed here.
