### ISSUE TITLE
Change Request: explicitly allow names like az_X_create() in C guidelines

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk#1651]
In C guidelines, we allow names like `az_X_create_Y()`. But nowhere specifically we say that the names like `az_X_create()` is ok. So, it is unclear, whether the naming should be `az_X_create()`,or `az_X_create_X()`. Everyone in our team agrees that in some cases `az_X_create()` totally makes sense, and @barcharcraz in a conversation confirmed that he is ok with the naming, but still, formally it is not very clear that you can end function names with `create`, without specifying what actually function creates right after the `create` verb.

Examples: `az_span_create()`, `az_span_create_from_str()`, `az_context_create_with_expiration()`, `az_context_create_with_value()`.

[
We do NOT want them to be `az_span_create_span()`, `az_span_create_span_from_str()`, `az_context_create_context_with_expiration()`, `az_context_create_context_with_value()`.

But sometimes we DO use "create_X" form: `az_keyvalut_create_key_options()`
]

https://github.com/Azure/azure-sdk-for-c/issues/999

**Comment by barcharcraz** [comment]
so according to the guidelines, or at least my intention for them. az_span_create_span should be az_create_span, because it's not doing something _with_ a span, it's making a new one.

**Comment by barcharcraz** [comment]
similarly az_create_span_from_string instead of az_span_create_from_str

The overall rule is that you list the thing name before the verb name if the thing is the first parameter, otherwise you just list the verb (create_span)
