### ISSUE TITLE
Board Review: Azure DigitalTwins

### ISSUE THREAD

**Issue by zolvarga** [Azure/azure-sdk#1652]
### The Basics
Responsible service team: Azure Digital Twins

- Link to documentation describing the service:
https://github.com/Azure/azure-digital-twins/blob/private-preview/Documentation/overview.md
- API surface: https://github.com/zolvarga/azure-sdk-for-js/blob/digitaltwins/sdk/digitaltwins/digitaltwins/review/digitaltwins.api.md
- Product Manager contact email: Elena.Horton@microsoft.com (elhorton)
- Dev Lead contact email: Jelani.Brandon@microsoft.com (jebrando)
- 

## About this client library

* Name of the client library: @azure/digitaltwins
* Languages for this review: Typescript
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/digitaltwins/data-plane/Microsoft.DigitalTwins/preview/2020-05-31-preview/digitaltwins.json

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR:
https://github.com/Azure/azure-sdk-for-js/pull/10560
* Link to samples for champion scenarios:
https://github.com/zolvarga/azure-sdk-for-js/blob/digitaltwins/sdk/digitaltwins/digitaltwins/samples/Readme.md

### Manage model lifecycle
Models represent some physical or logical entity, such as an IoT device, a room it is in, or a building that room is in. They are the cornerstone of digital twins. Each type of entity should be modeled using the DTDL schema. Once a schema is documented in the service, it can be known to other clients so when a digital twin is loaded, a program unfamiliar with that digital twin could interact with it in a dynamic way (e.g. UI created from a model to enable an operator to interact with the digital twin).

Note: this API is only available for bulk creation at this time. When multiple models are included, the service will validate any internal references and reject the request (think transaction) if the validation fails. Without that validation, one would need to create all the models in a specific order to avoid bad references.

- Create models in bulk
- List models
- Decommission a model
- Delete a model

### Digital twins
Digital Twins are the entities in ADT that represent physical or logical devices. They can be created, updated, read, and deleted.

- CRUD
- Query for digital twins

### Relationships
Based on the models applied to a digital twin, it can have relationships to other digital twins. Those relationships are managed independent of the digital twin (they aren't properties directly on the twin), and are 1-way (that is, a relationship created from A->B only appears on A and not on B).

- Link a digital twins to another via a relationship
- List relationships on a digital twin
- List incoming relationships (made by other digital twins targeting this one)
- Delete a relationship

### Telemetry
Digital twins that aren't physical devices may need telemetry sent on their behalf. The service SDK provides an avenue for that.

- Publish telemetry for a digital twin, or a component on a digital twin

### Event routes
An event route lets you send event data from digital twins in Azure Digital Twins to custom-defined endpoints in your subscriptions. Three Azure services are currently supported for endpoints: Event Hub, Event Grid, and Service Bus. Each of these Azure services can be connected to other services and acts as the middleman, sending data along to final destinations such as TSI or Azure Maps for whatever processing you need.

- CRUD

**Comment by lilyjma** [comment]
Content looks good! Thanks @zolvarga

**Comment by lilyjma** [comment]
(Thanks to @meeraharidasa for the notes!)

[MS Internal only] [Video](https://msit.microsoftstream.com/video/22f5a3ff-0400-8385-978b-f1eae263a112)

1.	Context
- Node SDK 1st review 
    - All comments have been addressed by Zoltan 
- Changes made by Zoltan since last meeting:
    - OperationOptions is clean now 
    - API has the same option handling (fixed by the generator mostly) 
    - Pipeline creation was made more advanced 
    - Client shape is the same 
- Breaking the Client vs. keeping it Flat?
    - This is a task for the swagger team 
    - Brian suggests: break out the client to different swagger 
    - Comparing against c# (flat structure) - Keep this consistent across JS and C#
    - If we wanted to split it would be : Event Routes, relationships, Models, Twins
    - If you want multiple clients together and there is more variation some things might be lost (ex: Storage)
    - Query would worry the most - used in conjunction with other things (would need all clients parallel) 
    - Telemetry - either you want it or not (not a big deal if it gets lost) 
2.	OperationOptions
- Question: Is there a way to abort interation operator if its in the middle of an io? 
    - **Action:** `listIncomeRelationships` needs to take options 
    - Brian said he will take this offline with Zoltan
3.	Samples (Notes)
- Scenario 1 (DigitalTwins)
    - Question: The Id's are constant strings that have been hard coded - is there a specific way the customers should name their models? 
        - The underlying philosophy is that customers can use anything they like, some use GUID and some use naming systems that they come from ADT 
        - Customers wanted the ability to define their own - tried and tested. 
    - Question: Why is there an @ line 141 $ Line 151
        - It's coming from the dtdl model 
        - In the json that’s returned from the service they have $ in front of them they are metadata items 
        - Metadata are always $ prefixed 
        - **Important:** Documented in the DT documentation 
4.	Future Plans 
- **Action:** Fix the few remaining issues then ready for release 
- The API is ready to release, except for a few minor changes
- Everyone is comfortable w preview 
    - Hoping for early release for ADT customers
    - Cadence: every month we release packages at the same time
    - **Action:** Brian will get in touch with the engineering system folks to get the preview rolling 
 
**Action Items:** 
 
- Consider the fact that: If you want multiple clients together and there is more variation some things might be lost for a flat strcuture 
- @zolvarga  to follow up on items above
- @bterlson  to follow up with engineering teams for preview
