### ISSUE TITLE
Add Client Pipeline Badges to the readme for all repos

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#166]
Add a reference to build badge to each of the languages repos.

See https://github.com/Azure/azure-sdk-for-java/commit/a6fa31f1d06d38ce6de7aaca51f4bb784e89f85e#diff-04c6e90faac2675aa89e2176d2eec7d8 as an example:

- [X] Java
- [ ] .NET
- [X] JS
- [ ] Python

**Comment by KarishmaGhiya** [comment]
Pull request:
https://github.com/Azure/azure-sdk-for-net/pull/5253

**Comment by weshaggard** [comment]
For consistency we need to also update the Java and JS badges as they currently point at the old build definitions. I suggest having them with the format:

```
[![Build Status](https:/dev.azure.com/azure-sdk/public/_apis/build/status/[definitionId]?branchName=master)](https://dev.azure.com/azure-sdk/public/_build/latest?definitionId=[definitionId]&branchName=master)
```
