### ISSUE TITLE
Android repo link checker running against entire repo

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk#1660]
https://github.com/Azure/azure-sdk-for-android/pull/283#pullrequestreview-465433101

Android repo currently only runs against the service repo instead of the entire repo. We might leave some files unchecked in CI, like README.md under root repo.

Have the issue to track the issue.

Options:
1. Have an aggregator-report pipeline similar pipelines. 
2. Running entire repo in core pipeline.

@weshaggard @mitchdenny

**Comment by mitchdenny** [comment]
I prefer one of the two options, depending on speed:

1. Check all links on all pipeline runs.
2. Check all links under [service directory] based on the pipeline being run.

I think that the aggregate-reporting pipeline model should be a last resort for things that just don't behave. The reality is that aggregate reports won't get the attention of someone submitting a PR which breaks a link.

**Comment by weshaggard** [comment]
>I think that the aggregate-reporting pipeline model should be a last resort for things that just don't behave. The reality is that aggregate reports won't get the attention of someone submitting a PR which breaks a link.

I agree that aggregate reports pipeline often gets ignored, we should try to fix that, however I also agree that if someone changes a link in a PR in they might not be notified that it is broken. It might be worth adding having the verify links pipeline check any modified MD files in a given PR.

**Comment by sima-zhu** [comment]
We currently fixed this by running entire repo when check links. Will fix the workflow once it introduced too much burden in future.
Close the issue as the code has checked in: https://github.com/Azure/azure-sdk-for-android/commit/51a8f23abf47d087c9db54afddd91884f14cb0da

**Comment by weshaggard** [comment]
@sima-zhu can you file a follow-up issue in the azure-sdk repo which will filter the link checker to only run against MD files that are changed in a PR.
