### ISSUE TITLE
Board Review: Storage STG74 features 

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk#1666]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Storage
* Link to documentation describing the service: [STG74 Overview](https://microsoft.sharepoint.com/:o:/r/teams/AzureStorage/_layouts/15/WopiFrame.aspx?sourcedoc={918fdd3d-aa62-45a7-8c9e-a4b208d9867e}&action=edit&wd=target%28STG%2074%2Eone%7C4B42E778%2D12E7%2D40B1%2DACDE%2D3FCC233F7EE3%2FSTG%2074%20Overview%7C01F32635%2D230D%2D4725%2DA680%2D5A4F44D0762B%2F%29)
* Contact email (if service team, provide PM and Dev Lead): seanmcc@microsoft.com

## About this client library

* Name of the client library: Storage
* Languages for this review: .NET, Java
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/storage-dataplane-preview/specification/storage/data-plane

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* [Blobs](https://apiview.dev/Assemblies/Review/fb1717502e524a2fbc51282822154a88)
* [File Share](https://apiview.dev/Assemblies/Review/f467df53d8844006b169b82b3376cba9)
* [Data Lake](https://apiview.dev/Assemblies/Review/8f4e48ded89d4711aa2a6be6488207ad)

### Java

* [Common](https://apiview.dev/Assemblies/Review/216abe5d5c1a41739d3d426bdd43411a?diffRevisionId=24a0104874ec442091ec114f9c8d19c9).
* [Blobs](https://apiview.dev/Assemblies/Review/3a3f0b1874a34245b585919bbcb15a43?diffRevisionId=9907152510214be78e91c739c2f7a051).
* [Blob Changefeed](https://apiview.dev/Assemblies/Review/234d552d3ffc4e12a94a047dc491afd0?diffRevisionId=98588cb70b2042eaa5996651cb67e8de) (just covers adding some APIs that were asked to be added in the STG 73 review before GA)
* [File Datalake](https://apiview.dev/Assemblies/Review/4961a7fa0b1741d3b2e814aecccbaa88?diffRevisionId=2e22c9debe454ba4a3b7fc7ec91b94be).
* [File Share](https://apiview.dev/Assemblies/Review/3c788060d3ef44a5b629653545710cc6?diffRevisionId=dee1beb277324b0082eef52b5421e505).
* [Queue](https://apiview.dev/Assemblies/Review/ee63f616819e428e83ffad0b36d48177?diffRevisionId=e98e1e75d2cc470eac828c9ac7352043).

### Python

* [azure-storage-blob](https://apiview.dev/Assemblies/Review/5f53b3f2e2e8453eb4cd81cb48d16620?diffRevisionId=cae36f5439684bc8a0f0b382a9f18f6b)
* [azure-storage-file-share](https://apiview.dev/Assemblies/Review/27d251c31d924249a26cb294cc62eb8c?diffRevisionId=5d5b42739c674f9fbf423ecde8bb24fe)
* [azure-storage-file-datalake](https://apiview.dev/Assemblies/Review/b09bb14da49e4f9c82787cd62f90fada?diffRevisionId=b6ce2f8183574f58aacb55433aa672e0)

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR: Coming soon.

**Comment by lilyjma** [comment]
Scheduled for 8/24 @seanmcc-msft. Please have all API Listings posted at least 5 workdays before the review. Thanks!

**Comment by seanmcc-msft** [comment]
To clarify, we are not looking for an SDK review.  This is introducing the STG 74 features for the arch board that we would like to review in a few weeks.

**Comment by lilyjma** [comment]
**Action Items/Notes**

Context: 
- Can't really change the already designed features 
- Features under "GA features" section are expected to come out in Sept

Features: 
- Quick Query
    - Ted: what should the default experience be for something like Quick Query? 
- Share Snapshot Lease 
    - 2:17 change exceptions  
    - Matt: Do we want to expose some SDK operations for operations that may/may not work depending on input 2:19
- Ted: add AAD support for Files? --> No plan exposed yet 
-  Set Share Tier
    - decide what to do with `ShareClient.SetQuota()` and `ShareClient.SetTier()`, i.e. what/how to expose

**Comment by kurtzeborn** [comment]
Closing this issue since the preliminary review was completed on Aug. 24th.  The API signature review is being tracked here: https://github.com/Azure/azure-sdk/issues/1795
