### ISSUE TITLE
[github.io] Selecting a Previous Version on a New API 404s

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#1668]
Let's say you're browsing the `Azure.Core` documentation. Specifically the `serialization` namespace.

https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Core/1.4.0/api/Azure.Core.Serialization.html

![image](https://user-images.githubusercontent.com/45376673/90049563-d2979080-dc89-11ea-9bb9-10b73720a755.png)

You click the drop-down, and select a version before `1.4.0`. `404 page not found`.

This is not a BUG. This namespace simply didn't exist on those previous versions of the package. We need to add some static redirect or some other error-handling to direct these 404 accesses to a default error page _for the specific package_.

**Comment by sima-zhu** [comment]
Looking into this. 
We can direct the page to upper level if failed to retrieve the page.

**Comment by sima-zhu** [comment]
Issue fixed in .net

**Comment by sima-zhu** [comment]
Closed as issue has been resolved.
