### ISSUE TITLE
Bug: Resource Group Name incorrect population in Rest API "Try It"

### ISSUE THREAD

**Issue by mrpt1** [Azure/azure-sdk#1672]
When using the "Try It' feature of the rest API calls to interact with any Azure resources (I have tested 2 different ones, [this](https://docs.microsoft.com/en-us/rest/api/storagerp/blobcontainers/deleteimmutabilitypolicy) is one of them), if the Resource Group name is ending with a dash and a single character (-1 or -a etc) it considers the value as null and so the URI will have %7BresourceGroupName%7D instead of the Resource Group name. 
<img width="646" alt="Screen Shot 2020-08-13 at 2 43 46 pm" src="https://user-images.githubusercontent.com/27760627/90095798-0c919100-dd75-11ea-9088-c039e9deb737.png">
<img width="662" alt="Screen Shot 2020-08-13 at 2 44 31 pm" src="https://user-images.githubusercontent.com/27760627/90095812-161af900-dd75-11ea-8659-c3d87464f195.png">

**Comment by markjulmar** [comment]
Thanks for the report, we'll investigate.

**Comment by markjulmar** [comment]
This has been fixed. Thanks for reporting it!
