### ISSUE TITLE
Request approval to release Form Recognizer 3.0.0

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk#1676]
Service released its 2.0 version API. Our client libraries released a 3.0.0-preview.1 (beta.1 for Java) package on 08/12/2020 with the corresponding changes and support for that service version.

We are still waiting on the service for a few hotfix deployments but there shouldn't be any API changes. The tests are all green and we are in a ready state to release `3.0.0` as soon as we get a Go from the service team.

- .NET:
  - [APIView](https://apiview.dev/Assemblies/Review/cf2c57b3d4c44ef08c2e8284f7441a2d)
  - [Readme](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/README.md)
- Java:
  - [APIView](https://apiview.dev/Assemblies/Review/05d0102010704cfa977f9386ce622294)
  - [Readme](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/README.md)
- Python:
  - [APIView](https://apiview.dev/Assemblies/Review/36ac7c8c633d4bf6a45ee8672243f195)
  - [Readme](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/README.md)
- JS:
  - [APIView](https://apiview.dev/Assemblies/Review/0a96f968aa144a479d63d56a169c9d05)
  - [Readme](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/formrecognizer/ai-form-recognizer/README.md)

cc: @KrzysztofCwalina @johanste @bterlson @JonathanGiles
FYI @mayurid @kinelski @maririos @kristapratico @mssfang @willmtemple

**Comment by johanste** [comment]
Python :shipit:

**Comment by JonathanGiles** [comment]
Java :shipit:

**Comment by kristapratico** [comment]
GA Released!
