### ISSUE TITLE
Release Notes Process Improvements

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#1694]
Right now collecting release notes from all the various teams, languages, services, etc is time consuming and manual.  It would be great if we could figure out an automated process to generate release notes from PRs.  For example, setting up a policy on PR title or a specific text in the PR description, that could then be extracted and included in a format that can be consumed on the Releases page on GH, the Release notes pages, and the blog.

**Comment by weshaggard** [comment]
While I like the idea of having a policy and trying to enforce clean commit history that will always be a challenge but perhaps we could start to use the ChangeLog information as the source for the release notes we publish. We could then slowly start to have some process and tools that update the changelogs based on changes coming into the repo.

**Comment by jongio** [comment]
@weshaggard - My suggestion would be to start with consistent and enforced PR titles and then use the PR titles in the release notes.  I know the Azure CLI does this.

**Comment by weshaggard** [comment]
Thanks for the pointer I just had a quick read through https://github.com/Azure/azure-cli/blob/1cf3072bb2e3af3db4f9b3dffc575c7e2c46efc9/doc/authoring_command_modules/README.md#format-pr-title. Using the PR titles could work but there are still a lot of things and structure that would need to be figured out before we could make that work. For example what if a PR (or a commit for that matter) crosses multiple packages? Also I think having a committed CHANGELOG is still something we should do so we would need to figure out a workflow that would also update that.

We should also try to figure out what we are trying to ultimately get to. Is this only about our github release pages or our release documents we generate in this repo, or both? 

I know that @pakrym has recently submitted https://github.com/Azure/azure-sdk-for-net/pull/14680 to help improve generating release information for .NET. Perhaps generalizing that for the other languages might also be a good stepping stone and help us figure out what pieces we need to improve to automate this E2E process.

**Comment by pakrym** [comment]
One thing the script can do is to add release notes to the release tracking issues. After that, we can have another automation that would pick it up and format the centralized notes.

**Comment by pakrym** [comment]
I'm making the change to add release notes to the tracking issue: https://github.com/Azure/azure-sdk-for-net/pull/14782

**Comment by weshaggard** [comment]
This work has been completed now.

**Comment by jongio** [comment]
Amazing!  Thank you
