### ISSUE TITLE
Change Request: Add guidedance for defining data strutures for C

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk#1696]
Make the expected data structure definition to be:
`typedef struct {} TypeT`

Make TypeS-TypeT definition an `avoid`
`typedef struct TypeS {} TypeT`

**Comment by ahsonkhan** [comment]
cc @barcharcraz

**Comment by vhvb1989** [comment]
this needs to be updated:
https://azure.github.io/azure-sdk/clang_design.html#structs

Guideline is actually asking to name typedef and structure.
This would require all the SDK code to be updated since it's not following this guide.

This also creates a duplicated documentation for the data structure (one as a typedef and another as a data structure)
