### ISSUE TITLE
Use a markdown linter for all READMEs and docs across various SDKs and languages

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk#1698]
We started using [this](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) markdown linter in the repo for the Embedded C SDK (VS Code extension) and fixed up a variety of consistency, formatting, and spacing issues.

https://github.com/Azure/azure-sdk-for-c/pull/959
https://github.com/Azure/azure-sdk-for-c/pull/1012

As Wes suggested, consider doing the same for other markdown files.
https://github.com/Azure/azure-sdk-for-c/pull/1012#discussion_r468213514

For context, here's the C99 issue: https://github.com/Azure/azure-sdk-for-c/issues/459

cc @weshaggard, @danewalton, @danieljurek, @RickWinter

**Comment by weshaggard** [comment]
@sima-zhu can you have a look at this linting tool to see if we can easily plug it into all our pipelines?

**Comment by sima-zhu** [comment]
Tested in pipeline and plug into all pipeline is doable.
https://dev.azure.com/azure-sdk/playground/_build/results?buildId=500656&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=40b1ee41-44d6-5bba-aa04-4b76a5c732e5

Will prepare the script for the task.
