### ISSUE TITLE
Unlist and hide obsolete/abandoned packages

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk#1705]
https://github.com/Azure/azure-sdk/blob/master/_data/releases/latest/dotnet-packages.csv contains some package names that were used in previews but changed later, we should hide them from 
https://azure.github.io/azure-sdk/releases/latest/all/dotnet.html and unlist from nuget.

cc @AlexGhiondea

**Comment by Petermarcu** [comment]
@jsquire do we know the list for this?

**Comment by jsquire** [comment]
@Petermarcu: Not to my knowledge; I don't believe this was part of the deprecation/retirement efforts.   @lfraleigh may have mor insight.

If not, we'll need to go through one-by-one and figure out what is obsolete.

**Comment by Petermarcu** [comment]
I did a spot check for packages that never GA'd in our client library list and didn't see anything obvious. I'm going to close this.
