### ISSUE TITLE
Board Review: Region Move Serivce - Public Preview

### ISSUE THREAD

**Issue by ajaygit158** [Azure/azure-sdk#1720]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Azure Region Move Service
* Link to documentation describing the service: 
https://review.docs.microsoft.com/en-us/azure/resource-mover/about-move-process?branch=pr-en-us-126996
https://review.docs.microsoft.com/en-us/rest/api/regionmove/movecollections?branch=regionmove 

* Contact email (if service team, provide PM and Dev Lead): 
**Dev Leads:** ajgupt@microsoft.com, pravk@microsoft.com, hsingh@microsoft.com
**PM Lead:** rajanaki@microsoft.com, prkazasr@microsoft.com

## About this client library

* Name of the client library: RegionMove
* Languages for this review: .NET, Python, GO
* Link to the service REST APIs: https://review.docs.microsoft.com/en-us/rest/api/regionmove/movecollections?branch=regionmove,
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/regionmove/resource-manager/Microsoft.Migrate/preview/2019-10-01-preview/regionmovecollection.json

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/eb2d8988ecbe493ca4b4058d28640b8f
* Link to samples for champion scenarios: The PR contains the .NET SDK tests which covers all the scenarios.
https://github.com/ajaygit158/azure-sdk-for-net/blob/ajgupt/RegionMoveSdk/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link: We are currently  working on Public Preview and our service does not require a data plane SDK. Java SDK is not a public preview requirement. hence, skipping this. 
* Link to samples for champion scenarios:

### Python

* Upload the api as a Draft PR.  Link to PR: The Python SDK PR is in review: https://github.com/Azure/azure-sdk-for-python/pull/13249
* Link to samples for champion scenarios: Not available as of now. Will work on this if mandatory.

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR: Not a Public Preview requirement for Management plance SDK. Skipping this.
* Link to samples for champion scenarios:

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Scenario: Create a move collection.
    * Percentage of developers using the service who would use the champion scenario: 100%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L44

* Champion Scenario 2:
    * Scenario: Update a move collection.
    * Percentage of developers using the service who would use the champion scenario: 40%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L73

* Champion Scenario 3:
    * Scenario: Get a move collection.
    * Percentage of developers using the service who would use the champion scenario: 90%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L100

* Champion Scenario 4:
    * Scenario: Delete a move collection.
    * Percentage of developers using the service who would use the champion scenario: 50%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L118

* Champion Scenario 5:
    * Scenario: Create or Update a Move Resource.
    * Percentage of developers using the service who would use the champion scenario: 100%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L139

* Champion Scenario 6:
    * Scenario: Get move resource.
    * Percentage of developers using the service who would use the champion scenario: 100%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L185

* Champion Scenario 7:
    * Scenario: Delete a move resource.
    * Percentage of developers using the service who would use the champion scenario: 80%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L205

* Champion Scenario 8:
    * Scenario: List move resources in a move collection.
    * Percentage of developers using the service who would use the champion scenario: 50%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L226

* Champion Scenario 9:
    * Scenario: Get unresolved dependencies.
    * Percentage of developers using the service who would use the champion scenario: 100%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L257

* Champion Scenario 10:
    * Scenario: Resolve Dependencies.
    * Percentage of developers using the service who would use the champion scenario: 100%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L274

* Champion Scenario 11:
    * Scenario: Prepare move resources.
    * Percentage of developers using the service who would use the champion scenario: 100%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L330

* Champion Scenario 12:
    * Scenario: Initiate Move for move resources.
    * Percentage of developers using the service who would use the champion scenario: 100%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L401

* Champion Scenario 13:
    * Scenario: Initiate Discard for move resources.
    * Percentage of developers using the service who would use the champion scenario: 20%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L472

* Champion Scenario 14:
    * Scenario: Initiate Commit for move resources.
    * Percentage of developers using the service who would use the champion scenario: 90%
    * Link to the code sample: https://github.com/ajaygit158/azure-sdk-for-net/blob/22f58fc672333cd80f29df0a59e5ba14820da2c4/sdk/regionmove/Microsoft.Azure.Management.Migrate/tests/ScenarioTests/RegionMoveTests.cs#L544

Examples of good scenarios are technology agnostic (i.e. the customer can do the same thing in multiple ways), and are expected to be used by > 20% of users:

* Upload a file
* Update firmware on the device
* Recognize faces in an uploaded image

Examples of bad scenarios:
* Create a client (it's part of a scenario, and we'll see it often enough in true champion scenarios)
* Send a batch of events (again, part of the scenario)
* Create a page blob (it's not used by enough of the user base)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
@ajaygit158 : I'm closing it per our conversation about these management plane SDKs. Please reach out if you have questions. Thanks!
