### ISSUE TITLE
Link to an "internal DevOps wiki" is 401 Not Authorized

### ISSUE THREAD

**Issue by arschles** [Azure/azure-sdk#174]
The wiki page appears to go to https://aka.ms/azure-sdk-devops-wiki and I can't access it. Is it possible to move relevant information into this repository, possibly as another Markdown file that the README links to?

**Comment by Petermarcu** [comment]
Is there some information you were looking for? We do want to make sure everything that people need is public. Much of the stuff in that internal repo isn't interesting for people that don't have admin access to the repo anyways.

**Comment by Petermarcu** [comment]
@arschles let us know if there was information you were looking for that you couldn't find. I'm going to close this for now.
