### ISSUE TITLE
Per-Service Doc Repos - Transition Documentation and Scripts

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#1746]
Dina has a large document written to assist vendors with the work necessary to move from the single gigantic doc repo to service-specific doc repositories.

So far, the document is based on [azure-cognitive-services](https://github.com/MicrosoftDocs/azure-cognitive-services-js) transition, for the language `JavaScript`. `scbedd` needs to work through Java, .NET, and python.

Outcomes:
 - [ ] Audit of ops.microsoft.com API surface. Can we get access and automate the "create CI" side that the UI is utilizing? It is a nice abstraction of the webhook additions, permissions, repo default settings, etc. If this is possible, a pshell to create the doc repo and docset would also be valuable.
 - [ ] A script to deploy and customize the azure-sdk version of the docs CI jobs for any doc repo
 - [ ] A script that can do the bulk of the work for configuring `docfx.json` and `.openpublishing.config`. 
 - [ ] A working example repository for Python, Java, .NET (hopefully built by the above)
 - [ ] Relevant gotchas for each language documented in Dina's PR.

**Comment by diberry** [comment]
Tracking...

**Comment by scbedd** [comment]
Have a working prototype [here.](https://github.com/scbedd/service-repo-generator) Working through final gotchas, then populating help documents next.

**Comment by diberry** [comment]
Congrats!!!!!!

**Comment by scbedd** [comment]
Closing as duplicate to Azure/azure-sdk-tools#1742.

We aren't going to stand up a repo per service.
