### ISSUE TITLE
Proxy Policy

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-sdk#175]
### Background

Users need to be able to use Azure libraries and services from behind proxies. Some languages and environments, e.g. Python's `urllib.request` and web browsers, have in-built support for proxies. Others, including Node, have no in-built support and so we must provide it.

HTTP proxying is relatively straightforward and commonly acheived. However, users of alternative protocols such as AMQP will still require proxy support somehow even if it requires setup on their end.

Below are two proposals that are not mutally exclusive.

### Proposal 1

Azure libraries auto-detect proxy settings based on the presence of environment variables:

* HTTP_PROXY: proxy for http requests
* HTTPS_PROXY: proxy for https requests
* NO_PROXY: a comma-separated list of hostnames that bypass the proxy

These environment variables are already in wide use in the *nix ecosystem - Python's urllib.request, tools like Curl, and browsers on Linux and possibly Mac OS respect these environment variables. It may be nice for us to use them when we find them without any interaction from the user.

### Proposal 2

Azure libraries are configured via a proxy parameter to the pipeline. ms-rest implements this already for http clients, and this is similar to how AWS and GCP get support for HTTP proxies in Node (GCP seems to have a configuration parameter, AWS asks you to override the HTTP Agent with a proxying agent).

This option would also allow a user to override their system settings if proposal 1 is accepted.

For non-HTTP services, proxying is less straightfoward as it is a protocol-specific activity. I think there are a couple options:

* Allow for configuring protocol-specific proxies via hostname + port similar to HTTP, so if a user has e.g. [amqproxy](https://github.com/cloudamqp/amqproxy) running someplace they can use it with minimal configuration
* Do not support programmatic proxying of non-http protocols and rely on e.g. SSH tunneling instead

I like proposal 2 (with support for configuring non-HTTP proxies via options). Proposal 1 I'm not sure about and am curious what others thoughts are.

**Comment by adrianhall** [comment]
Proxy requirements were added to the general guidelines.
