### ISSUE TITLE
Service-level README.md consistency

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk#1757]
I have noticed that in a number of repositories, for some services we have a ```README.md``` file as the service directory level (e.g. ```sdk/keyvault/README.md```. This isn't consistent. I think we need to decide whether we do this consistently or not. I know that the Spring team in the Java repository makes good use of ```sdk/spring/README.md``` file to help find the various spring packages, so I think that the README.md files at this level could be useful.

It could also service as a way of connecting the management plane and data plane worlds for our customers where a customer who is using KeyVault is likely to want to use both sets of libraries. I think a ```README.md``` file that covers both helps us avoid shipping our org chart.

I think we would want to come up with a consistent format for these ```README.md``` so that they are all uniform and can be validated by Doc Warden.

**Comment by weshaggard** [comment]
The service level readme is supposed to become a high level overview and inventory of the different packages for that service, see https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/README.md as an example. I believe @kaerm was working with the service teams to create that at some point.

**Comment by kaerm** [comment]
I don't think anything came out of it. I generally agree this is needed and once we have a consistent format we could use them to add as service overview pages on reference docs on docs.microsoft.com 

//cc @czubair @maggiepint

**Comment by mitchdenny** [comment]
I'm putting this on the backlog for now. Seems like we should keep it open, but not sure when it'll be prioritized.

**Comment by mitchdenny** [comment]
@scbedd should I assign this to you if you are going to be talking to folks about the service-level READMEs? I created this this issue when I noticed an inconsistency and have been holding it since.

**Comment by scbedd** [comment]
@mitchdenny absolutely. Go ahead.
