### ISSUE TITLE
Board Review: SearchBatchClient for .net/Java/Python

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk#1769]
## The Basics

* Service team responsible for the client library: Azure Cognitive Search 
* Link to documentation describing the service:  https://docs.microsoft.com/en-us/azure/search/
* Contact email (if service team, provide PM and Dev Lead): 
brjohnst@microsoft.com
maheff@microsoft.com

## About this client library

* Name of the client library: azure-search-documents
* Languages for this review: Python
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/search/data-plane/Azure.Search/preview/2020-06-30-Preview

### Python

* [apiview](https://apiview.dev/Assemblies/Review/b8c9d2f3e54d499d80479792af175b1f?diffRevisionId=3870e79f67004bfaa7acef476f07bac8)
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-python/blob/search_batch_client_sample/sdk/search/azure-search-documents/samples/sample_batch_client.py
* Demo code: https://gist.github.com/xiangyan99/696264f315f2bcd78b3e35522142340b

### Java

* [APIView](https://apiview.dev/Assemblies/Review/f8224ac5afc64604ac98249cefa0c7f7?diffRevisionId=2ebc4e1b254a4cd0ba11358f66936805)
* [Champion Scenarios](https://gist.github.com/alzimmermsft/2b5a11204ac1908d09f02ec342918cca)

### C#
* [ApiView](https://apiview.dev/Assemblies/Review/cff09959425c4673b22c4a5816cd927a?diffRevisionId=72dc3ae1bb234830b505210ddbecff85)
* [Champion Scenarios](https://gist.github.com/tg-msft/67e34adafa5b136f2583f0e234691832)

**Comment by lilyjma** [comment]
scheduled for 9/15

**Comment by lilyjma** [comment]
[MS internal only][Video](https://web.microsoftstream.com/video/8632a1ff-0400-96f3-21d1-f1eaf7aa2da5)

**Comment by xiangyan99** [comment]
Done.
