### ISSUE TITLE
Feedback for the Typescript Design Guidelines

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk#177]
@bterlson I took a look at https://azuresdkspecs.z5.web.core.windows.net/TypeScriptSpec.html and below are some observations and feedback.

Note the numbers point to the section numbers in the document

- 1: Introduction doesn’t make sense. It refers to "this section" being typescript specific as well whats right after it as "common guidelines". 
- 3: Why point to Java repo, use js or node
- 3: Whats with the grey check box
- 3.1: Link to template readme needed
- 3.1: Why are we talking about Maven?
- 3.2 Avoid pasting text when you can give link
- 3.3 Link to sample MIT license would be helpful
- 3.3 License files are usually not a markdown file.
- 4: Language independent guidelines… well everything above this was language independent as well
- 4.1 Heading says "General guidelines", but text says "language specific gudelines"
- 4.1 Why are we talking about other languages here?
- 4.2: Provide a link to Anne's telemetry doc perhaps?
- 4.2: User Agent should be `azure-sdk-for-js/azure-<package-name>/<package-version> (NODE-VERSION <node-version>; <os-type> <os-version>)`
- 4.2 What is the guidance for when we allow customers to prepend/append to our user agent? Length restrictions?
- 4.3: More details on pluggable loggers needed
- 4.5: Best practices around cancellation or sample code will be very helpful
- 4.6: Dependencies/Versioning: This whole point doesn’t seem very applicable to the js world
- 4.6: "YOU SHOULD NOT be dependent on any other packages" : Not applicable for js
- 5: Typescript specific guidelines: Wasn’t this whole doc suppose to be just for Typescript?
- 5.3.1 is already covered in earliar sections. Why repeat?
- 5.3.3: 
	○ DO NOT have a pre-release version or any additional build metadata. Previews are pre-release versions arent they? What build meta data are we talking about? Especially in the same sentence as "pre-release" version. 
	○ Also the very next point after the above is about preview and pre-release… confusing…
- 5.3.4: Folder structure doesnt have entries for samples, test-dist and typings
- 5.3.5: 
	○ Repo should be azure-sdk-for-js
	○ Name should be all lower case, with - between words. 
	○ Add a note for homepage
	○ A link to learn more about side effects can help
	○ "test" script. We might want to have 2 scripts here. 1 to run as part of CI for each commit/PR. The other for live tests that we run internally
- 5.3.7 We had a README section in 3.1 as well. Why repeat?
- 5.3.7 Need for Contributing.md file is repeated
- 5.3.8 We had a section on contributing in 3.2 as well. Why repeat?
- 5.3.9 This asks you to look at 6.1, but there is no 6.1. Also see 3.3. Again repetittion
- 5.5 A section on common modules that should be avoided if we want to browserify will be helpful
- 5.7 Use azure-sdk-for-js and not azure-sdk-for-node
- 5.8.3: API Docs. Add links to https://aka.ms/publish-on-docs and https://review.docs.microsoft.com/en-us/help/onboard/admin/reference/js-ts/road-to-docs?branch=master
- 5.8.3 Speak of Preview vs Latest vs Versions

cc @AlexGhiondea

**Comment by bterlson** [comment]
- 1: Introduction doesn’t make sense. It refers to "this section" being typescript specific as well whats right after it as "common guidelines".
  - *BT: I didn't realize the artifact you reviewed is a thing. I've organized things better in that document (this fixes many similar issues below).*
- 3: Why point to Java repo, use js or node
  - *BT: just an example. That said, expanded it to include links to all the SDKs.*
- 3: Whats with the grey check box
   - *BT: #212*
- 3.1: Link to template readme needed
- 3.1: Why are we talking about Maven?
   - *BT: #213*
- 3.2 Avoid pasting text when you can give link
   - *BT: I'm not sure about this, will ponder*
- 3.3 Link to sample MIT license would be helpful
   - *BT: Added.*
- 4: Language independent guidelines… well everything above this was language independent as well
- 4.1 Heading says "General guidelines", but text says "language specific gudelines"
- 4.1 Why are we talking about other languages here?
    - *BT: Things should be more clear with things better organized, but there are general guidelines that apply across languages, and guidelines which apply to just JS/TS. Rather than rewrite the general guidelines in a specific way for each language, we're including the general content as-is.*
- 4.2: Provide a link to Anne's telemetry doc perhaps?
- 4.2: User Agent should be `azure-sdk-for-js/azure-<package-name>/<package-version> (NODE-VERSION <node-version>; <os-type> <os-version>)`
- 4.3: More details on pluggable loggers needed
   - *BT: #12*
- 4.5: Best practices around cancellation or sample code will be very helpful
   - *BT: #16*
- 4.6: Dependencies/Versioning: This whole point doesn’t seem very applicable to the js world
- 4.6: "YOU SHOULD NOT be dependent on any other packages" : Not applicable for js
   - *BT: These are applicable. Yes, JS has a module and packaging system mostly capable of dealing with an ecosystem with rich dependency graphs, but that doesn't mean they don't bring along the same concerns as other platforms. Compatibility e.g. is a key one - if browser support is on the radar, taking the wrong dep early can set you up for failure down the road.*
- 5: Typescript specific guidelines: Wasn’t this whole doc suppose to be just for Typescript?
- 5.3.1 is already covered in earliar sections. Why repeat?
- 5.3.3: 
	○ DO NOT have a pre-release version or any additional build metadata. Previews are pre-release versions arent they? What build meta data are we talking about? Especially in the same sentence as "pre-release" version.
	○ Also the very next point after the above is about preview and pre-release… confusing…
    - *BT: Build metadata is a semver spec term, and might be a incremental build counter or a build timestamp. These should not be included, but a preview version specifier is fine. I've cleared this up some in 3bf02a823a52f45b3dac18e341413ecff8149b85*
- 5.3.5: 
	○ Repo should be azure-sdk-for-js
	○ Name should be all lower case, with - between words. 
	○ Add a note for homepage
	○ A link to learn more about side effects can help
	○ "test" script. We might want to have 2 scripts here. 1 to run as part of CI for each commit/PR. The other for live tests that we run internally
- 5.3.7 We had a README section in 3.1 as well. Why repeat?
- 5.3.7 Need for Contributing.md file is repeated
- 5.3.8 We had a section on contributing in 3.2 as well. Why repeat?
- 5.3.9 This asks you to look at 6.1, but there is no 6.1. Also see 3.3. Again repetittion
- 5.5 A section on common modules that should be avoided if we want to browserify will be helpful
- 5.7 Use azure-sdk-for-js and not azure-sdk-for-node
- 5.8.3: API Docs. Add links to https://aka.ms/publish-on-docs and https://review.docs.microsoft.com/en-us/help/onboard/admin/reference/js-ts/road-to-docs?branch=master
- 5.8.3 Speak of Preview vs Latest vs Versions

**Comment by bterlson** [comment]
These are all fixed now.
