### ISSUE TITLE
Board Review: Azure-DigitalTwins-Core for Java

### ISSUE THREAD

**Issue by azabbasi** [Azure/azure-sdk#1789]
Requesting an architectural review for a client library that targets a preview Azure service.

## The Basics

* Service team responsible for the client library: Azure DigitalTwins
* Link to documentation describing the service:
    - https://review.docs.microsoft.com/en-us/azure/digital-twins/?branch=master
    - https://github.com/Azure/azure-digital-twins/blob/private-preview/Documentation/overview.md
* API surface: https://apiview.dev/Assemblies/Review/b6ca1e24411349658b47a22abc87bbaa
* Product Manager contact email: sejsha
* Dev Lead contact email: drwill

## About this client library

* Name of the client library: azure-digitaltwins-core
* Languages for this review: Java
* Link to the service REST APIs: https://msazure.visualstudio.com/One/_git/Azure-IoT-DigitalTwins-Main?path=%2Fproducts%2Fswagger%2Fexternal-data-plane%2Fpreview%2F2020-05-31-preview
* Link to several samples: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/digitaltwins/azure-digitaltwins-core/src/samples/java/com/azure/digitaltwins/core

## Artifacts required (per language)
https://apiview.dev/Assemblies/Review/b6ca1e24411349658b47a22abc87bbaa

## Champion Scenarios
> See samples at <https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/digitaltwins/azure-digitaltwins-core/src/samples/java/com/azure/digitaltwins/core>

### Manage model lifecycle

Models represent some physical or logical entity, such as an IoT device, a room it is in, or a building that room is in. They are the cornerstone of digital twins. Each type of entity should be modeled using the [DTDL](https://github.com/Azure/azure-digital-twins/blob/private-preview/DTDL/DTDL-spec-v2.md) schema. Once a schema is documented in the service, it can be known to other clients so when a digital twin is loaded, a program unfamiliar with that digital twin could interact with it in a dynamic way (e.g. UI created from a model to enable an operator to interact with the digital twin).

> Note: this API is only available for bulk creation at this time. When multiple models are included, the service will validate any internal references and reject the request (think transaction) if the validation fails. Without that validation, one would need to create all the models in a specific order to avoid bad references.

- Create models in bulk
- List models
- Decommission a model
- Delete a model

### Digital twins

Digital Twins are the entities in ADT that represent physical or logical devices. They can be created, updated, read, and deleted.

- CRUD
- Query for digital twins

### Relationships

Based on the models applied to a digital twin, it can have relationships to other digital twins. Those relationships are managed independent of the digital twin (they aren't properties directly on the twin), and are 1-way (that is, a relationship created from A->B only appears on A and not on B).

- Link a digital twins to another via a relationship
- List relationships on a digital twin
- List incoming relationships (made by other digital twins targeting this one)
- Delete a relationship

### Telemetry

Digital twins that aren't physical devices may need telemetry sent on their behalf. The service SDK provides an avenue for that.

- Publish telemetry for a digital twin, or a component on a digital twin

### Event routes

An event route lets you send event data from digital twins in Azure Digital Twins to custom-defined endpoints in your subscriptions. Three Azure services are currently supported for endpoints: Event Hub, Event Grid, and Service Bus. Each of these Azure services can be connected to other services and acts as the middleman, sending data along to final destinations such as TSI or Azure Maps for whatever processing you need.

- CRUD

## Agenda for the review
The Azure Digital Twins Core for .NET has already been reviewed by the board a few months back. So the board is familiar with the service and the champion scenarios. 
The agenda for this review is to go through the API designs and the implementation for the Java SDK.

**Comment by lilyjma** [comment]
scheduled for 9/17

**Comment by lilyjma** [comment]
[MS internal only][Video](https://msit.microsoftstream.com/video/2d42a1ff-0400-96f3-c83b-f1eaf93175b5)

**Comment by azabbasi** [comment]
Digital twins Java Azure SDK review action items:
- Update samples of query to do while loop rather than look at just one page
- Remove APIs that take/give string in favor of the strongly typed APIs only. The clazz can be a string to give the same functionality
- Use Iterable<T> rather than List<T> for createModels APIs. Service team doesn't guarantee any ordering in this collection.
- In builder, rename .httpPipeline() to .pipeline()
- Take reference from search SDK on how to allow customers to set custom JsonSerializer
    https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/indexes/SearchIndexClientBuilder.java#L189

- There is an autorest flag that makes required params be taken at constructor time. Srikanta will work offline with Tim to help him get this done.

- Alan Zimmer offered to follow up on an Azure Core Json Patch class which is still in progress in Java's Azure Core. Ideally we'd have this class available before GA
    https://github.com/Azure/azure-sdk-for-java/issues/14491
    
- Rename "RequestOptions" to "DigitalTwinRequestOptions" to be less generic
    C# and Java
    
- Rename "ModelData" to "DigitalTwinModelData" in swagger
    Johan says it should be safe to change this in the swagger since the only available SDKs are in preview.
    Need to notify scripting SDK team about this upcoming change
