### ISSUE TITLE
Board Review: Azure.Core JsonPatch support 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk#1810]
## The Basics

* Service team responsible for the client library: Azure Core
* Link to documentation describing the service: http://jsonpatch.com/
* Contact email (if service team, provide PM and Dev Lead): @pakrym

## About this client library

* Name of the client library: Azure.Core
* Languages for this review: C#

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/e7879c2a02fb45a2a28b463103262615#Azure.Core.JsonPatchDocument

## Champion Scenarios

Some services operate on large customer-provided JSON and would like to be able to update them without having do download/modify/upload the entire entity, using the JSON Patch instead.

The type being reviewed is a strongly typed representation of a JSON Patch document builder.

``` C#
var client = new DigitalTwinClient();
var jsonPatch = new JsonPatchDocument();
jsonPatch.AppendAddRaw("/twin/events", "{ \"id\": 1, "data": [] }");
jsonPatch.AppendReplace("/twin/active", true);

await client.UpdateDigitalTwinAsync("<my-twin-id>", jsonPatch);
```

@alzimmermsft @drwill-ms @srnagar

**Comment by lilyjma** [comment]
scheduled for 10/13

**Comment by johanste** [comment]
`jsonPatch.AppendReplace("/twin/active", "true");` => `jsonPatch.AppendReplace("/twin/active", true);` in order to set the value to a boolean value, I assume. 

Or else, how to I change the value to a new string value? `jsonPatch.AppendReplace("/twin/active", "\"true\"");`?

**Comment by pakrym** [comment]
Sorry, the sample should've been updated to be in sync with latest API changes.

Change to a bool:
```C#
jsonPatch.AppendReplace("/twin/active", true); or 
jsonPatch.AppendReplaceRaw("/twin/active", "true");
```

Change to a string:
```C#
jsonPatch.AppendReplace("/twin/active", "true");
jsonPatch.AppendReplaceRaw("/twin/active", "\"true\"");
```

**Comment by johanste** [comment]
Does this mean that I have to use the *Raw methods to provide an object (in json lingo) to the API? I know that at least one of the reasons that the DT team used json-patch rather than json-merge-patch was that they needed the ability to replace items in an array/list. I'd assume that it is not a perfect experience to have to escape the string yourself...

**Comment by pakrym** [comment]
No, generic overloads take any value and serialize them.

```
MyCoolModel model = new MyCoolModel()
{
   Name = "Yes"
};

jsonPatch.AppendReplace("/twin/thing", model);
```

**Comment by johanste** [comment]
Ok - that makes sense. I guess I should have looked at the apiview link.
