### ISSUE TITLE
Feedback on the releases pages for Python

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk#1814]
Customer feedback from https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-library-package-index
`Why not show that actual pip install for each of these, e.g. "pip install azure-storage-file-share" Instead of having the user search the links under "Storage - File Shares" (which does not correspond to the actual module name`

cc: @jongio

**Comment by weshaggard** [comment]
The pip install command is just one link away by clicking the pypi link next to the library. The table is already pretty large so I'm not sure putting the full command there is helpful because it will add a lot more noise. We could put the package name instead of the display name in the table though if that is helpful for people.

**Comment by weshaggard** [comment]
@kaerm let me know if the link the source readme is enough here as I'd like to avoid adding a lot more data to an already busy table.

**Comment by jongio** [comment]
I think it would be cool to have a way for them to copy the pip command.  Maybe we consider moving to a drop down for each package with all the various commands.

**Comment by weshaggard** [comment]
If we can come up with some scenarios and ideas on how to display them I'm open but as it is I don't think we should add any extra columns to the table because it is already overflowing with data.

**Comment by kaerm** [comment]
I agree about not adding columns, the tables are already (too) rich with content. I have no good ideas for now, would need to spend some time looking for inspiration on good display options. Adding @lmazuel in case of any thoughts on this

**Comment by lmazuel** [comment]
As @weshaggard was saying, when you click on the pypi link you get your command with a copy/paste button:

![image](https://user-images.githubusercontent.com/1050156/97898055-314e3280-1cec-11eb-94c4-9b4714558301.png)

Though I could understand if this not discoverable enough (hence the feedback), so I'm unsure myself how to improve it :/

**Comment by weshaggard** [comment]
Closing this issue as we don't want to add the full install commands in the index but we have recently included the package name in the index.
