### ISSUE TITLE
Add a `packages.md` file to root of each repo as part of documentation scanning

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#182]
`packages.md` should be of the following format, and contain a listing of every package within the repo.
| Service Name | Package Name as a link to the package | current version | link to source folder |

The "package name as a link to the package" should be a link out to the appropriate package manager. (maven, nuget, pypi, npm, etc)

**Comment by Petermarcu** [comment]
@JonathanGiles as well. 

I was wondering if we should actually have the build produce some of this information like the package name and version as part of an svg image and the table could just link to that. This would prevent the need to have it updated with the version all the time. The only time this would need to be updated would be if a service is added or removed.

**Comment by Petermarcu** [comment]
Thinking about it more. The same image could be used on the readme specific to the library as well. I set up build processes before that basically update the svg with the latest build number and upload that to a known location for everything to reference as a "Status badge".

**Comment by scbedd** [comment]
I really like the concept of the SVG keeping the version up to date, etc.

Pulling this work in, instead of pulling in the release notes, we will place a link (with SHA of the build artifacts) to this `packages.md` file. We will link directly to an anchor tag for the deploying package id. Then, from there, we'll look at the readme content to get the relative url.
