### ISSUE TITLE
Board Review: Azure DigitalTwins - Python SDK

### ISSUE THREAD

**Issue by zolvarga** [Azure/azure-sdk#1822]
### The Basics
Responsible service team: Azure Digital Twins

- Link to documentation describing the service:
https://github.com/Azure/azure-digital-twins/blob/private-preview/Documentation/overview.md
- API surface: 
- Product Manager contact email: Elena.Horton@microsoft.com (elhorton)
- Dev Lead contact email: Jelani.Brandon@microsoft.com (jebrando)
- 

## About this client library

* Name of the client library: azure-digitaltwins
* Languages for this review: Python
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/digitaltwins/data-plane/Microsoft.DigitalTwins/preview/2020-05-31-preview/digitaltwins.json

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### Python

* Upload the api as a Draft PR.  Link to PR:
https://github.com/Azure/azure-sdk-for-python/pull/13852
* Link to API review tool output:
https://apiview.dev/Assemblies/Review/cc173aeec2b94586a53054e71b4c9544
* Link to samples for champion scenarios:
https://github.com/zolvarga/azure-sdk-for-python/blob/digitaltwins/sdk/digitaltwins/azure-digitaltwins/samples/Readme.md

### Manage model lifecycle
Models represent some physical or logical entity, such as an IoT device, a room it is in, or a building that room is in. They are the cornerstone of digital twins. Each type of entity should be modeled using the DTDL schema. Once a schema is documented in the service, it can be known to other clients so when a digital twin is loaded, a program unfamiliar with that digital twin could interact with it in a dynamic way (e.g. UI created from a model to enable an operator to interact with the digital twin).

Note: this API is only available for bulk creation at this time. When multiple models are included, the service will validate any internal references and reject the request (think transaction) if the validation fails. Without that validation, one would need to create all the models in a specific order to avoid bad references.

- Create models in bulk
- List models
- Decommission a model
- Delete a model

### Digital twins
Digital Twins are the entities in ADT that represent physical or logical devices. They can be created, updated, read, and deleted.

- CRUD
- Query for digital twins

### Relationships
Based on the models applied to a digital twin, it can have relationships to other digital twins. Those relationships are managed independent of the digital twin (they aren't properties directly on the twin), and are 1-way (that is, a relationship created from A->B only appears on A and not on B).

- Link a digital twins to another via a relationship
- List relationships on a digital twin
- List incoming relationships (made by other digital twins targeting this one)
- Delete a relationship

### Telemetry
Digital twins that aren't physical devices may need telemetry sent on their behalf. The service SDK provides an avenue for that.

- Publish telemetry for a digital twin, or a component on a digital twin

### Event routes
An event route lets you send event data from digital twins in Azure Digital Twins to custom-defined endpoints in your subscriptions. Three Azure services are currently supported for endpoints: Event Hub, Event Grid, and Service Bus. Each of these Azure services can be connected to other services and acts as the middleman, sending data along to final destinations such as TSI or Azure Maps for whatever processing you need.

- CRUD

**Comment by lilyjma** [comment]
scheduled for 10/6
