### ISSUE TITLE
Board Review: Azure Device Update Public Preview launch 

### ISSUE THREAD

**Issue by ValOlson** [Azure/azure-sdk#1838]
###Context
This is a follow up review for Azure Device Update Rest API’s and Swagger with Peter Marcu and Johan Stenberg's feedback

###The Basics

- Service team responsible for the SDK library: COSINE > EDS team working on Azure Device Update for IOT Devices
- Link to documentation describing the service:
- [ADU Architecture.docx](https://microsoft.sharepoint.com/:w:/r/teams/specstore/_layouts/15/Doc.aspx?sourcedoc=%7B70DC83D3-7419-4D60-BB9D-D83BD4C5A171%7D)
- [ADU Private Preview GitHub](https://github.com/Azure/adu-private-preview/blob/master/docs/adu-overview.md)
- Contact (if service team, provide PM and Dev Lead):
- PM: Val Olson
- Dev: David Pokluda, Oscar Lee, Jimmi Tirifon

### About this client library and Artifacts

- Name of the service library: Azure Device Update
- Languages for this review:
- <will add new PR's by 9/24>
- Swagger: https://github.com/Azure/azure-rest-api-specs-pr/pull/1978

### Champion Scenarios 
Azure Device Updates (ADU) has few core capabilities and touchpoints for updating IOT devices Over the Air (OTA)
1. Publish new update
2. retrieve the newly imported update
3. wait for update to be installable to our device
4. create deployment to deploy our new update to our device
5. check deployment status until it's completed
6. retrieve device properties to check installed update present
7. retrieve all updates installed on the device
8. delete the update
9. retrieve the deleted update and check that it no longer exists

The above leverages all core API methods and champions main scenarios of Update publishing and Device update deployment.

**Comment by ValOlson** [comment]
+ PR's

.NET: https://apiview.dev/Assemblies/Review/e69a527c94d2444f816d5341759582d8
Python: https://apiview.dev/Assemblies/Review/b4767c5c88b24f788ca10f79aa8f5b1d

**Comment by lilyjma** [comment]
scheduled for 9/30 in case we don't get to SDKs in REST API Review

**Comment by dpokluda** [comment]
I am not sure how to share the sample (champion scenario). Here is the sample project from .NET project:
\\DPOKLUDA\Public\MU\Tasks\Current\AzureSdk\Data\Net\Azure.Iot.DeviceUpdate\samples

**Comment by lilyjma** [comment]
[MS Internal Only][Video](https://msit.microsoftstream.com/video/09fba3ff-0400-9fb2-bfbd-f1eb036d9fd3)
