### ISSUE TITLE
Repo PRs PowerBI report

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#184]
We need a report indicating how we're performing in community PR response times.  This report should be similar the one we have for issues taking into account the following:
- Only report on PRs from the community (where they're not a "member")
- Show a history of our performance against our SLA
- Be able to select subsets of repos

**Comment by kurtzeborn** [comment]
Pretty sure this is done.

**Comment by scbedd** [comment]
I don't believe so. I do believe that this one https://github.com/Azure/azure-sdk-tools/issues/149 is a dup of it though.
