### ISSUE TITLE
Standardize Handling of Anchor Tags Across Github.io

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#1843]
This issue tracks the work that comes out of the discussion on [this PR](https://github.com/Azure/azure-sdk-for-net/pull/15352).

Essentially. In our markdown, we will define anchor tags that MATCH targeted headers further down in the document. [here is a specific example are the bullet points directly below the linked location.](https://github.com/Azure/azure-sdk-for-net/blob/master/README.md#packages-available)

The header is defined as `Client: New Releases`, but the generated _anchor_ is `#client-new-releases`. This is a mismatch! In HTML, the anchor ids are case sensitive.

Need to standardize this. Options discussed so far.

1. Lowercase the anchor targeting in the links WE define in the repo
2. Add JS to all github.io that can handle these weird casing issues ourselves (like github does)
3. Insert our own anchors with matching capitalization.

**Comment by sima-zhu** [comment]
We currently have several places which turn md to html:
1. Github IO root readme file. (Docfx generated)
1. Github IO readme of every artifacts (Depends on langs)
1. Doc.MS (docs.microsoft.com can render markdown file directly from their page)

Currently, #1 and #3 both populate the anchor link id as lowercase connect by `-`. To make the link direct to the right place, we'd better to use link-verification to do lower-case check.

#2, the anchor link failed to direct the the right place for java no matter what format we are using. We have to fix it by standardize the way of converting markdown to html. Could fix by https://github.com/Azure/azure-sdk-tools/issues/929

The very first step I will preform is to fix the link-verification scripts and fixed the anchor link for each repo.
