### ISSUE TITLE
Setup a MD link scanning pipeline once the changes are outside of sdk scope.

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk#1851]
We are currently lack of the ability to catch the invalid link when the PR has diff outside of sdk/ folder. 
We failed the aggregate-report once it checked in, which needs two steps to fix it. This is inefficient.

Example PRs: 
https://github.com/Azure/azure-sdk-for-python/pull/13813
https://github.com/Azure/azure-sdk-for-net/pull/13019

Options:
1. (Optimal) Setup a new pipeline to do MD file link verification once the diff is outside of sdk. This is light-weighted. 
We can have link-verification step to scan against any MD files among the diff.
2. Trigger the aggregate-report pipeline when change is outside of the sdk scope. Not very ideal, as aggregate-report is a little heavy as check too many unrelated stuff.

**Comment by weshaggard** [comment]
One option we should consider is adding a "link-checker" or "MD checker" pipeline that will check the links of any MD files that are part of the pull request. If we have this it will optimize the link checking in one pipeline so we can remove it form the others and it will also optimize such that we only verify files that have changed instead of all files (although we might still want to check all files nightly in case some links start failing later).

**Comment by mitchdenny** [comment]
I wonder if this is a good opportunity to use GitHub actions. GitHub actions allows glob based filters which might be really good for this.

**Comment by weshaggard** [comment]
I'm OK testing out github actions, especially if they provide a nice file filtering mechanism.

**Comment by sima-zhu** [comment]
I can look into Github action for the issue.

**Comment by sima-zhu** [comment]
Tested the workflow: https://github.com/Azure/azure-sdk-for-java/runs/1184517668?check_suite_focus=true
Working for current usage.

**Comment by mitchdenny** [comment]
Excellent. I guess we need to come up with a convention for the check names and locations of files etc.

**Comment by weshaggard** [comment]
Yes and we need to understand what other, if any, implications there are with starting to depend on Github Actions. Things like where do we get the machine resources and other such things, is the free tier enough or do we need to pay for more resources, etc. While I'm Ok with experimenting with github actions here we do need to think it all the way through.

**Comment by sima-zhu** [comment]
To minimize the billing of github actions. 
Several way of optimization: 
1. We can trigger the actions once path includes *.md files.
2. Use Linux runner instead of windows.

**Comment by sima-zhu** [comment]
The issue has been resolved to scan changed files or sdk folder respectively to PR or Ci.
