### ISSUE TITLE
[Monikerization] [.NET Docs Repo] Update docfx. Files can share path across monikers

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#1857]
.NET needs a bit more additional work here. It doesn't currently have a fusionToCConfig or real monikers to speak of right now. Need to add that before we can make further progress on the docfx.

- [ ] .NET Repo [monikerized](https://ceapex.visualstudio.com/Engineering/_queries/edit/267447/?triage=true)
- [ ] DocFX Updated to allow identically named files across monikers
- [ ] CI Updated If Necessary
- [ ] Necessary Changes to targeting are merged in archetype--release stage

See parent epic for details.

**Comment by danieljurek** [comment]
Approaches to fix: 

* Split the .NET ref docs into separate repos by moniker (legacy, latest, preview)
* Feature work from the ref docs team

**Comment by scbedd** [comment]
@danieljurek we are currently hard blocked on getting updates from the ref docs team. I don't believe multiple monikers with separate generations are possible w/ .NET.

[Issue filed for Tianqi and co.](https://dev.azure.com/ceapex/Engineering/_workitems/edit/371059)

**Comment by danieljurek** [comment]
Chatted w/ @maggiepint -- This work can be done as part of Grouped ToC onboarding.

**Comment by danieljurek** [comment]
Docs internal feature for this: https://dev.azure.com/ceapex/Engineering/_workitems/edit/657647

**Comment by sima-zhu** [comment]
Monikerization work is done. https://learn.microsoft.com/en-us/dotnet/api/overview/azure/?view=azure-dotnet&branch=main
The issue could close. Will move to .NET Docs.Ms automation.
