### ISSUE TITLE
Board Review: azure-core JsonPatch Support

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk#1861]
## The Basics

* Service team responsible for the client library: Azure Core
* Link to documentation describing the service: http://jsonpatch.com/
* Contact email (if service team, provide PM and Dev Lead): @alzimmermsft 

## About this client library

* Name of the client library: azure-core
* Languages for this review: Java

### Java

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/6327470e8c834d42920649124a0b9c12#com.azure.core.experimental.jsonpatch.JsonPatchDocument

## Champion Scenarios

Some services operate on large customer-provided JSON and would like to be able to update them without having do download/modify/upload the entire entity, using the JSON Patch instead.

The type being reviewed is a strongly typed representation of a JSON Patch document builder.

```java
DigitalTwinsClient client = new DigitalTwinsClientBuilder().build();
JsonPatchDocument jsonPatchDocument = new JsonPatchDocument();
jsonPatch.AppendAdd("/twin/events", "{ \"id\": 1, "data": [] }");
jsonPatch.AppendReplace("/twin/active", "true");

client.updateDigitalTwin("<my-twin-id>", new ArrayList<Object>(jsonPatchDocument.getJsonPatchOperations()));
```

@pakrym @srnagar

**Comment by lilyjma** [comment]
scheduled for 10/13

**Comment by alzimmermsft** [comment]
This has been approved and shipped.
