### ISSUE TITLE
Update automated release notes script to with tag "major"

### ISSUE THREAD

**Issue by czubair** [Azure/azure-sdk#1873]
Change the automated script that copies the changelog into the release notes to only pick up items that the devs have tagged "major" in the changelog. This is in line with the release notes policy that only critical/developer impacting changes should go in release notes (i.e., it is not a copy of the changelog). https://azure.github.io/azure-sdk/policies_releasenotes.html

**Comment by czubair** [comment]
After speaking with a few people, there may be better ways to update the script so it is not a copy of the changelog. @heaths  suggested adding a "highlights" section to the changelog and this is what is copied into release notes.

@Ted.Glaza and @KieranBrantnerMagee note that adding a tag "major" would not allow bullet points to be summarized or made less terse between changelog and relnotes.

@weshaggard let's sync before you start working on this.

**Comment by weshaggard** [comment]
Yes I think using a new sections like "Highlights" would make the most sense and would allow us to have any formatted text we want for the library.

**Comment by weshaggard** [comment]
@czubair has a PR for updating these guidelines https://github.com/Azure/azure-sdk/pull/2613

**Comment by heaths** [comment]
While we're at it, we should really emphasize consistency with headers. There is a published spec (I'd have to dig it up, which is part of the problem - it's not that discoverable with all the doc sites we have) but many SDKs don't follow it, making for very inconsistent CHANGELOGs. Maybe we even go so far as to change all the previous entries. I think a lot of this stems from people seeing it one way in an older SDK, copying that going forward, and bring that style to their new SDKs they work on.

**Comment by weshaggard** [comment]
As part of this effort we plan to also have the automatic version bumping PR generate a stubbed out changelog entry that follows our guidelines but just has empty sections. That will help folks have more of a fill in the blank experience when writing the change log entries.

**Comment by weshaggard** [comment]
This work as now been done.
