### ISSUE TITLE
[Service Bus] Investigate implementation of streaming receiver

### ISSUE THREAD

**Issue by ramya0820** [Azure/azure-sdk#188]
Concerns:
- Error gets eaten up in OnMessage handler if link is closed
- Execution of OnMessage continues even when OnError gets triggered, could lead to potential side-effects

**Comment by ramya-rao-a** [comment]
Issue moved to [Azure/azure-sdk-for-js #1190](https://github.com/Azure/azure-sdk-for-js/issues/1190) via [**ZenHub**](https://www.zenhub.com/)
