### ISSUE TITLE
Autogen package listing - please add release notes link

### ISSUE THREAD

**Issue by diberry** [Azure/azure-sdk#1880]
@weshaggard Please add release notes to autogen.

Either as a separate include with month over month or as current release notes.

**Comment by weshaggard** [comment]
I'm going to need a little more information for this request. Are you meaning just the MD files we have for our month releases? Or are you meaning change log information for every package?

**Comment by diberry** [comment]
When [this](https://github.com/Azure/azure-sdk/pull/1878) is filled in, can it go into the autogen package for the dev center?

**Comment by weshaggard** [comment]
OK Yes I can add it do you want the file to be named a particular way and or structured in a particular way? Also is this something we want for all the languages or just JS?

**Comment by diberry** [comment]
@weshaggard Is this a new thing or is there a very for last month I could look at? Also probably all languages as an include.

**Comment by weshaggard** [comment]
We have been collecting these monthly notes for a while see the sidebar on https://azure.github.io/azure-sdk/releases/latest/ or at https://github.com/Azure/azure-sdk/tree/master/releases.

**Comment by weshaggard** [comment]
@diberry closing this issue but please let me know if there is something else you think we can help with.
