### ISSUE TITLE
Board Review: Form Recognizer V2.1 Service Introduction Meeting

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk#1881]
## The Basics

* Service team responsible for the client library: Form Recognizer
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/cognitive-services/form-recognizer/overview
* Contact email (if service team, provide PM and Dev Lead): Sandeep Parab (@ramparab), Neta Haiby (don't know her @, sorry), Xin Zou (@xinase)

## About this client library

* Name of the client library: **Form Recognizer**
* Languages for this review: All languages (this is an introductory session)
* Link to the service REST APIs: [This](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/FormRecognizer/preview/v2.1-preview.1/FormRecognizer.json) is a link to the 2.1-preview.1 swagger

FR is a library that "... is a cognitive service that lets you build automated data processing software using machine learning technology". We have already GA'd a client SDK with the service's 2.0 API endpoint. In this meeting, the service team will introduce us to the new features they hope to introduce in 2.1. The main additions are listed below:
- Prebuilt model to analyze business cards
- Compose multiple custom models into one model
- Ability to analyze receipts from multiple locales (previously it just analyzed receipts from the US)

## Champion Scenarios 
**TODO: (@ramparab @xinase can your team fill this section out, for an ex, see [this](https://github.com/Azure/azure-sdk/issues/1621) issue's Champion Scenarios section)**
A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Describe the champion scenario
    * Estimate the percentage of developers using the service who would use the champion scenario
    * Link to the code sample

_ Repeat for each champion scenario _

Examples of good scenarios are technology agnostic (i.e. the customer can do the same thing in multiple ways), and are expected to be used by > 20% of users:

* Upload a file
* Update firmware on the device
* Recognize faces in an uploaded image

Examples of bad scenarios:
* Create a client (it's part of a scenario, and we'll see it often enough in true champion scenarios)
* Send a batch of events (again, part of the scenario)
* Create a page blob (it's not used by enough of the user base)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
scheduled for 10/8

**Comment by xinase** [comment]
Champion Scenario 1: **Model Compose**
**Describe the champion scenario**
A user had created 100 models for 100 different types of documents.  Now for each incoming document, which model should the user route the document to extract key/value?  Currently, a user has to classify the documents using self-built methods which are costly and inaccurate.   with **Model Compose**  feature,  they could let Form Recognition Services do the classification and expect a high quality result with similar analyze() call to the composed model.  

Expect: Form Services should support such scenario in our API:  

- User could create a collection of models by calling  Compose() 
- This model collection would react to the Analyze() call with the best result returned, the same ways as we call a single model.  
- 

Estimate the percentage of developers using the service who would use the champion scenario
- about 30% of customers would run into "how to classify different models" problem,  Model Compose could be their solution. 
Link to the code sample
- tbd

**Comment by TFR258** [comment]
# Champion Scenario 2: Analyze Business Card (it also applies to Analyze Id Document, Receipts, and Invoice)
## Describe the champion scenarios
A customer has collected many business cards during a work event and would like to extract all the relevant information to potentially feed it to a contact list, or an automated distribution list to thank the hosts and organize follow-ups. With the Analyze Business Card operation , extracting the key information from business cards in the form of key/value pairs
## Estimate the percentage of developers using the service who would use the champion scenario
This Operation is quite specialized and doesn't offer many more scenarios
## Link to the code sample
We don't have sample code just yet.

**Comment by lilyjma** [comment]
[Video](https://web.microsoftstream.com/video/d72ca4ff-0400-9fb3-7f8a-f1eb09b2cba2) [MS internal only]
