### ISSUE TITLE
Board Review: metrics advisor (Java & JS/TS)

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk#1883]
## The Basics

* Service team responsible for the client library: **Metrics Advisor**
* Link to documentation describing the service:  https://docs.microsoft.com/en-us/azure/cognitive-services/metrics-advisor/
* Product Manager contact: **Mayuri**
* Dev contact: **Anu Thomas Chandy, Jeremy Meng**
* Service team contacts: bix@microsoft.com, bowgong@microsoft.com (dev), quying@microsoft.com (PM)

## About this client library

* Name of the client library: azure-ai-metricsadvisor
* Languages for this review: Java/JS
* Link to the service REST APIs:
https://github.com/bowgong/azure-rest-api-specs/blob/metricsadvisor-preview/specification/cognitiveservices/data-plane/MetricsAdvisor/preview/v1.0/MetricsAdvisor.json
https://westus2.dev.cognitive.microsoft.com/docs/services/MetricsAdvisor/operations/createDataFeed

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net))

### Java

* Upload JAR to [apiview](https://apiview.dev/Assemblies/Review/63bc3e4d0f8f410d96012e9f373fb082).
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-java/tree/renames-ma/sdk/metricsadvisor/azure-ai-metricsadvisor/src/samples

### TypeScript

* Upload the JSON output of api-extractor to [apiview](https://apiview.dev/Assemblies/Review/567be6b0c991415c88056dff5cd54af1)
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/metricsadvisor/ai-metrics-advisor/samples

## Champion Scenarios

Context: Customer runs a global retail chain. They utilize the service to monitor their key metrics daily

| timestamp  | city    | category      | cost | revenue |
|------------|---------|---------------|------|---------|
| 08/20/2020 | Chicago | Toy           | ...  | ...     |
| 08/20/2020 | Chicago | Home & Garden | ...  | ...     |
| 08/20/2020 | Tokyo   | Toy           | ...  | ...     |
| 08/20/2020 | Tokyo   | Home & Garden | ...  | ...     |
| ...        | ...     | ...           | ...  | ...     |

#### DataFeed creation
    
The customer can onboard their data by creating a data feed.

* Code samples: [Java](https://gist.github.com/anuchandy/e43b4435ce653b5e4e7619d8dfde9c84#1a-creating-datafeed) | [TS](https://gist.github.com/jeremymeng/7eee97dfb65db46569ae16ef4f9195fd#1a-create-data-feed)
    
#### Query Anomalies detected, Incidents and RootCauses
    
Service produces the time series for the data feed, and detect any anomalies in the data.
    
* Code samples: [Java](https://gist.github.com/anuchandy/e43b4435ce653b5e4e7619d8dfde9c84#scenario-2-query-anomalies-detected-incidents-rootcauses-1) | [TS](https://gist.github.com/jeremymeng/7eee97dfb65db46569ae16ef4f9195fd#scenario-2-query-anomalies-detected-incidents-and-their-root-causes)

#### Configure alerts and get Incidents notifications using a hook.

Customers can create alert configurations to receive Incident alerts (notifications) through email or webhook.

* Code samples
[Java](https://gist.github.com/anuchandy/e43b4435ce653b5e4e7619d8dfde9c84#scenario-3-configure-alerts-and-get-incidents-notifications-using-a-hook-1) | [TS](https://gist.github.com/jeremymeng/7eee97dfb65db46569ae16ef4f9195fd#scenario-3-configure-alerts-and-get-incidents-notification-using-a-hook)

#### Enumerate Alerts, alerted Incidents and Anomalies
    
In addition to receiving alerts through email or webhook, customers can also enumerate alerts using API.

* Code samples: [Java](https://gist.github.com/anuchandy/e43b4435ce653b5e4e7619d8dfde9c84#scenario-4-enumerate-alerts-alerted-incidents-and-anomalies) | [TS](https://gist.github.com/jeremymeng/7eee97dfb65db46569ae16ef4f9195fd#scenario-4-enumerate-alerts-alerted-incidents-and-anomalies)
    
#### Submit Feedbacks to service
    
If customer finds that some of the identified anomalies are not accurate then he can submit feedback, that will be taken into account for later data points.
   
* Code samples: [Java](https://gist.github.com/anuchandy/e43b4435ce653b5e4e7619d8dfde9c84#scenario-5-submit-feedbacks-to-service) | [TS](https://gist.github.com/jeremymeng/7eee97dfb65db46569ae16ef4f9195fd#scenario-5-provide-feedback-to-service)
    

#### Plot time-series and enriched time-series
   
If a customer wants to build a custom dashboard (similar to MA workspace) to display time-series, he can query the service for time-series data points. 

* Code samples: [Java](https://gist.github.com/anuchandy/e43b4435ce653b5e4e7619d8dfde9c84#scenario-6-plot-time-series-and-enriched-time-series-1) | [TS](https://gist.github.com/jeremymeng/7eee97dfb65db46569ae16ef4f9195fd#scenario-3-plot-time-series-and-enriched-time-series)
   
### additional scenarios

* Code samples: [Java](https://gist.github.com/anuchandy/e43b4435ce653b5e4e7619d8dfde9c84#additional-scenarios-1) | [TS](https://gist.github.com/jeremymeng/7eee97dfb65db46569ae16ef4f9195fd#additional-scenarios)

#### Create clients and authenticate with the service

* Code samples: [Java](https://gist.github.com/anuchandy/e43b4435ce653b5e4e7619d8dfde9c84#creating-the-metricsadvisor-clients) | [TS](https://gist.github.com/jeremymeng/7eee97dfb65db46569ae16ef4f9195fd#creating-metrics-advisor-clients)

**Comment by lilyjma** [comment]
scheduled for 10/14

**Comment by anuchandy** [comment]
Here we quickly go through the major service concepts to help with domain knowledge.

### Metric, Dimensions and Time-Series:

The service can connect to various data sources. Consumers specify the "metrics" in the data-source that they want service to monitor and the "dimensions" of the metric. Service produces "time-series" for each metric across "dimensions".

<img width="667" alt="image" src="https://user-images.githubusercontent.com/1471612/90358092-ea647100-e009-11ea-93a4-8077752c9218.png">

### Anomaly:

An "anomaly" is an abnormal data point in the "time-series".


<img width="1147" alt="Screen Shot 2020-08-16 at 9 50 34 PM" src="https://user-images.githubusercontent.com/1471612/90358356-9d34cf00-e00a-11ea-90c5-fd0fd9adb415.png">


### Anomaly Detection:

Consumers can specify the "anomaly detection configurations" for the "metric" and "time-series", which will be used to detect the abnormal data point (i.e. anomalies)

<img width="874" alt="image" src="https://user-images.githubusercontent.com/1471612/90358447-de2ce380-e00a-11ea-9531-065d3d0d0b6a.png">


### Alerting:

The "alerting configuration" can be used to combine multiple "anomaly detection configurations" and produce alerts.

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1471612/90358632-7aef8100-e00b-11ea-818b-63877c677dab.png">

### Incident:

When anomalies appear for a long period of time or show some pattern, then service treats it as an incident."Alerting configuration" can have hooks attached to it and alert will be sent to the hook. The support hooks are - email and webhook.

<img width="981" alt="Screen Shot 2020-08-16 at 10 03 39 PM" src="https://user-images.githubusercontent.com/1471612/90358970-724b7a80-e00c-11ea-8e6b-7e294bf0bd42.png">

### Notes:

Service also supports "querying" for alerts, incidents, various configurations through REST API. The high-level components of the service look like:

<img width="974" alt="Screen Shot 2020-08-16 at 10 06 45 PM" src="https://user-images.githubusercontent.com/1471612/90359098-d110f400-e00c-11ea-89a0-898ab3ef43da.png">

**Comment by lilyjma** [comment]
[Recording](https://web.microsoftstream.com/video/7bf1a3ff-0400-9fb2-6eca-f1eb0e71395d)[MS INTERNAL ONLY)

**Comment by xiangyan99** [comment]
Done.
