### ISSUE TITLE
Board Review: Azure Identity Fe GA

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk#1889]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library:
* Link to documentation describing the service:
* Contact email (if service team, provide PM and Dev Lead):

## About this client library

* Name of the client library:
* Languages for this review:
* Link to the service REST APIs:

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* [apiview](https://apiview.dev/Assemblies/Review/d94ce821604344f1b34d5c8e70cf7808?diffRevisionId=b0b44e840b4641168d25ddf6df6a32f7&doc=False)
* [champion scenarios](https://gist.github.com/schaabs/f7b4b1706bf30ded8077b031caeaa88c)

### Java

* [apiview](https://apiview.dev/Assemblies/Review/93d80a6ca2d94b32ad37981fb4d3c8cf?diffRevisionId=de1eb7505801414a9efeca73d08d3362&doc=False)
* [champion scenarios](https://gist.github.com/g2vinay/106bfeef382680d659856a17413fe8ff)

### Python

* [apiview](https://apiview.dev/Assemblies/Review/bfbdf1e3d0a54ee8bcb20678d2fae993?diffRevisionId=2d0fea77e8284f3a92d74797b0df8475&doc=False)
* [champion scenarios](https://gist.github.com/chlowell/45aa78ae9499b6acbefe7cbc09a3708a)

### TypeScript

* [api-extractor](https://gist.github.com/jonathandturner/1aa857063f84611c21ba69751703bedb)
* [champion scenarios](https://gist.github.com/sadasant/0c96a332e2f13b0b9fdef2c6b9a7e725):

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Describe the champion scenario
    * Estimate the percentage of developers using the service who would use the champion scenario
    * Link to the code sample

_ Repeat for each champion scenario _

Examples of good scenarios are technology agnostic (i.e. the customer can do the same thing in multiple ways), and are expected to be used by > 20% of users:

* Upload a file
* Update firmware on the device
* Recognize faces in an uploaded image

Examples of bad scenarios:
* Create a client (it's part of a scenario, and we'll see it often enough in true champion scenarios)
* Send a batch of events (again, part of the scenario)
* Create a page blob (it's not used by enough of the user base)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
scheduled for 10/20

**Comment by lilyjma** [comment]
[Video](https://web.microsoftstream.com/video/5acea3ff-0400-9fb2-415c-f1eb132833b7)[MS internal only]
