### ISSUE TITLE
Board Review: metrics advisor (Python & .net)

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk#1892]
## The Basics

* Service team responsible for the client library: Metrics Advisor
* Link to documentation describing the service:  https://docs.microsoft.com/en-us/azure/cognitive-services/metrics-advisor/
* Contact email (if service team, provide PM and Dev Lead):
bix@microsoft.com, bowgong@microsoft.com (dev)
quying@microsoft.com (PM)

## About this client library

* Name of the client library: azure-ai-metricsadvisor
* Languages for this review: .net/Python
* Link to the service REST APIs:
https://github.com/bowgong/azure-rest-api-specs/blob/metricsadvisor-preview/specification/cognitiveservices/data-plane/MetricsAdvisor/preview/v1.0/MetricsAdvisor.json
https://westus2.dev.cognitive.microsoft.com/docs/services/MetricsAdvisor/operations/createDataFeed

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* [APIView](https://apiview.dev/Assemblies/Review/8caf3dd1661c45228d8081a536cca3bc)
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/samples/README.md

### Python

* [APIView](https://apiview.dev/Assemblies/Review/6acc354ec6c5421b82a081a07b481df0)
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/metricsadvisor/azure-ai-metricsadvisor/samples

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1: 
    * Describe the champion scenario: create a data feed to ingest data
    * Estimate the percentage of developers using the service who would use the champion scenario
    * Link to the code samples: [Python](https://gist.github.com/xiangyan99/6c367d45168294b043b2f5685d57f584#create-data-feed) | [.NET](https://gist.github.com/kinelski/c072790394398c37d186df611f6bea44#scenario-1-datafeed-creation)

* Champion Scenario 2: 
    * Describe the champion scenario: create a configuration to let service know whether a point is anomaly
    * Estimate the percentage of developers using the service who would use the champion scenario
    * Link to the code samples: [Python](https://gist.github.com/xiangyan99/6c367d45168294b043b2f5685d57f584#create-detection-configuration) | [.NET](https://gist.github.com/kinelski/c072790394398c37d186df611f6bea44#2d-applyingtuning-anomaly-detection)

* Champion Scenario 3: 
    * Describe the champion scenario: configure the service when to trigger an alert
    * Estimate the percentage of developers using the service who would use the champion scenario
    * Link to the code samples: [Python](https://gist.github.com/xiangyan99/6c367d45168294b043b2f5685d57f584#config-alert-configuration) | [.NET](https://gist.github.com/kinelski/c072790394398c37d186df611f6bea44#scenario-3-configure-alerts-and-get-incidents-notification-using-a-hook)

* Champion Scenario 4: 
    * Describe the champion scenario: query anomalies & alerts
    * Estimate the percentage of developers using the service who would use the champion scenario
    * Link to the code samples: [Python](https://gist.github.com/xiangyan99/6c367d45168294b043b2f5685d57f584#query-anomalies-for-alert-configuration) | [.NET](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/README.md#query-detected-anomalies-and-triggered-alerts)

**Comment by anuchandy** [comment]
Here we quickly go through the major service concepts to help with domain knowledge.

### Metric, Dimensions and Time-Series:

The service can connect to various data sources. Consumers specify the "metrics" in the data-source that they want service to monitor and the "dimensions" of the metric. Service produces "time-series" for each metric across "dimensions".

<img width="667" alt="image" src="https://user-images.githubusercontent.com/1471612/90358092-ea647100-e009-11ea-93a4-8077752c9218.png">

### Anomaly:

An "anomaly" is an abnormal data point in the "time-series".


<img width="1147" alt="Screen Shot 2020-08-16 at 9 50 34 PM" src="https://user-images.githubusercontent.com/1471612/90358356-9d34cf00-e00a-11ea-90c5-fd0fd9adb415.png">


### Anomaly Detection:

Consumers can specify the "anomaly detection configurations" for the "metric" and "time-series", which will be used to detect the abnormal data point (i.e. anomalies)

<img width="874" alt="image" src="https://user-images.githubusercontent.com/1471612/90358447-de2ce380-e00a-11ea-9531-065d3d0d0b6a.png">


### Alerting:

The "alerting configuration" can be used to combine multiple "anomaly detection configurations" and produce alerts.

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1471612/90358632-7aef8100-e00b-11ea-818b-63877c677dab.png">

### Incident:

When anomalies appear for a long period of time or show some pattern, then service treats it as an incident."Alerting configuration" can have hooks attached to it and alert will be sent to the hook. The support hooks are - email and webhook.

<img width="981" alt="Screen Shot 2020-08-16 at 10 03 39 PM" src="https://user-images.githubusercontent.com/1471612/90358970-724b7a80-e00c-11ea-8e6b-7e294bf0bd42.png">

### Notes:

Service also supports "querying" for alerts, incidents, various configurations through REST API. The high-level components of the service look like:

<img width="974" alt="Screen Shot 2020-08-16 at 10 06 45 PM" src="https://user-images.githubusercontent.com/1471612/90359098-d110f400-e00c-11ea-89a0-898ab3ef43da.png">

**Comment by lilyjma** [comment]
[Video](https://msit.microsoftstream.com/video/2242a1ff-0400-9fb2-21c1-f1eb17e0375f) [MS Internal Only]

**Comment by xiangyan99** [comment]
Done.
