### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - Calling

### ISSUE THREAD

**Issue by tophpalmer** [Azure/azure-sdk#1894]
## The Basics

* Responsible service team: Azure Communication Services (SPOOL)
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/communication-services/
* Product Manager contact email: Nikolay Muravlyannikov, nmurav@microsoft.com, FTE
* Dev Lead contact email: Marius Ungureanu, mariusu@microsoft.com, FTE

## About this client library

* Name of the client library: Azure Communication Calling
* Languages for this review: TypeScript, iOS (Obj-C\Swift) and Android (Java)
* Link to the service REST APIs: [common identifier types](https://github.com/Azure/azure-rest-api-specs/blob/ad9b8f9c7b2be812e2787430ee09626c7f9c13fb/specification/communication/data-plane/Microsoft.CommunicationServicesCommon/preview/2020-11-19-preview1/common.json)
* Link to Conceptual Docs: [Calling Library Overview](https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features), [Voice And Video Concepts](https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/about-call-types), [Teams Interop](https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/teams-interop)

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### Java (Android)

* [APIView](https://apiview.dev/Assemblies/Review/f64c586922b649ef8f6dd659b78b6be9).
* Link to samples for champion scenarios: [QuickStart](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-android)

### iOS

* [APIView](https://apiview.dev/Assemblies/Review/f64c586922b649ef8f6dd659b78b6be9).
* Link to samples for champion scenarios: [QuickStart](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-ios)

### TypeScript

* [ApiView](https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8/b211560343ed47b585a49f5b6792807c?doc=False)
* Link to samples for champion scenarios: [QuickStart](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-web)

## Champion Scenarios

Core scenarios and flows documentation can be found here:
*[Client Server Architecture](https://docs.microsoft.com/en-us/azure/communication-services/concepts/client-and-server-architecture)
*[Call Flows](https://docs.microsoft.com/en-us/azure/communication-services/concepts/call-flows)
*[Client Server Architecture](https://docs.microsoft.com/en-us/azure/communication-services/concepts/client-and-server-architecture)
*[Core Usage](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/calling-client-samples?pivots=platform-web)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
scheduled for 1/25

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/c5dfa3ff-0400-9887-6ccc-f1eb5f68f2e1)[MS INTERNAL ONLY)

**Comment by lilyjma** [comment]
Mobile review scheduled for 2/15

**Comment by lilyjma** [comment]
iOS and Android: [Recording](https://msit.microsoftstream.com/video/0863a1ff-0400-85a8-5eb7-f1eb717c7cfe?referrer=https:%2F%2Fstatics.teams.cdn.office.net%2F)
