### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - Phone Number Administration

### ISSUE THREAD

**Issue by tophpalmer** [Azure/azure-sdk#1897]
## The Basics

* Responsible service team: Azure Communication Services (SPOOL)
* Link to documentation describing the service:
* Product Manager contact email: Chris Palmer, chpalm@microsoft.com, @tophpalmer
* Dev Lead contact email: Reza Jooyandeh, rejooyan@microsoft.com, @RezaJooyandeh

## About this client library

* Name of client library: Azure.Communication.Administration
* Target language for this review: Java, C#, JS, Python
* Link to the service REST APIs: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/b5811b8612b712777578b5eabdd4494c7aae427d/specification/communication/data-plane/Microsoft.CommunicationServicesAdministration/preview/2020-11-01-preview3/phonenumbers.json

The Azure.Communication.Administration package provides the capabilities related to phone numbers and identity management. This review is specifically for Phone Numbers Administration. The primary scenario is around searching, acquiring and managing phone numbers which could be eventually used within the communication resource for calling and SMS.

At a high level, buying new phone numbers is a 2-step process. The first step involves specifying the search criteria, which will primarily include the country, the phone number type, capabilities, assignment type (to a person an application), and the quantity of phone numbers. Once the search results are available, the numbers could be purchased. The capabilities of an acquired phone number can be updated as long as the number is not released. Once a phone number is no longer needed, it could be released.

All of Search, Purchase, Update and Release are Long Running Operations which can be queried using the OperationId.

## Artifacts required (per language)

> ⚠ APIViews have changed since we had the review, latest links here:

* [.NET APIView](https://apiview.dev/Assemblies/Review/b32afd45c457422992f506154f376d68)
* [Java APIView](https://apiview.dev/Assemblies/Review/300aa54ba60742b4890c4a0a0853fad9)
* [JS APIView](https://apiview.dev/Assemblies/Review/317956c6833a462aa5478ade5dbde602/3031489d478c4e22a0ae0de8d8cecf08?doc=False)
* [Python APIView](https://apiview.dev/Assemblies/Review/c9c41d6a4fe84b7d8d912041087f6e56)

### .NET

* Link: https://apiview.dev/Assemblies/Review/b32afd45c457422992f506154f376d68
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-net/blob/26422e5c2c435dd2c10a1b0af547ea861711d4ab/sdk/communication/Azure.Communication.Administration/tests/samples/Sample1_PhoneNumberClient.cs

### Java

* Link: https://apiview.dev/Assemblies/Review/f5795186f9864e7aa21ea10b1bc670ee
* Link to samples for champion scenarios: https://github.com/ankitarorabit/azure-sdk-for-java/blob/phonenumber-redesign/sdk/communication/azure-communication-administration/src/samples/java/com/azure/communication/administration/ReadmeSamples.java

### Python

* Link: https://apiview.dev/Assemblies/Review/52482dd7517d4bf1a200a9283f49b039#azure.communication.administration.PhoneNumberAdministrationClient
* Link to samples for champion scenarios: https://github.com/ankitarorabit/azure-sdk-for-python/blob/phonenumber-redesign/sdk/communication/azure-communication-administration/samples/phone_number_redesign_sample.py

### TypeScript

* Link: https://apiview.dev/Assemblies/Review/87a620312ca243cfaaa7bbe1c08c4d16
* Link to samples for champion scenarios: https://github.com/DominikMe/azure-sdk-for-js/blob/communication-phonenumbers-redesign/sdk/communication/communication-administration/samples/typescript/src/basicPhoneNumbers.ts

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

#### Java
```Java
  String countryCode = "US";
  SearchCapabilities searchCapabilities = new SearchCapabilities()
      .setSms(CapabilityValue.OUTBOUND)
      .setCalling(CapabilityValue.INBOUND_OUTBOUND);

  SearchRequest searchRequest = new SearchRequest()
      .setNumberType(PhoneNumberType.GEOGRAPHIC)
      .setAssignmentType(AssignmentType.APPLICATION)
      .setAreaCode("425")
      .setCapabilities(searchCapabilities)
      .setQuantity(2);

  SyncPoller<Operation,SearchResult> syncPoller = phoneNumberClient
      .beginSearchPhoneNumber(countryCode, searchRequest);

  syncPoller.waitForCompletion();
  SearchResult searchResult = syncPoller.getFinalResult();

  System.out.println("SearchId: " + searchResult.getId());
  System.out.println("Monthly Rate: " + searchResult.getMonthlyRate().getValue());
  for (String phoneNumber : searchResult.getPhoneNumbers()) {
      System.out.println("Available Phone Number: " + phoneNumber);
```
#### C#
```C#
  string connectionString = "CONNECTION_STRING";
  PhoneNumberClient phoneNumberClient = new PhoneNumberClient(connectionString);

  var searchPhoneNumberOperation = await phoneNumberClient.StartSearchAvailablePhoneNumbersAsync(
      countryCode: "US",
      numberType: PhoneNumberType.Geographic,
      assignmentType: AssignmentType.Application,
      capabilities: new CapabilitiesRequest()
      {
            Sms = CapabilityValue.Outbound,
            Calling = CapabilityValue.InboundOutbound,
      },
      areaCode: "425",
      quantity: 2);

  await searchPhoneNumberOperation.WaitForCompletionAsync().ConfigureAwait(false);
  SearchResult searchResult = searchPhoneNumberOperation.Value;

  Console.WriteLine("SearchId: " + searchResult.Id);
  Console.WriteLine("Monthly Rate: " + searchResult.MonthlyRate.Value);
  Console.WriteLine("Expires by: " + searchResult.SearchExpiresBy.ToString());

  foreach (var phoneNumber in searchResult.PhoneNumbers)
  {
      Console.WriteLine("Available Phone Number: " + phoneNumber);
  }
```
#### TypeScript
```typescript
  const client = new PhoneNumberAdministrationClient(connectionString);

  const searchPoller = await client.beginSearchAvailablePhoneNumbers("US", {
    numberType: "geographic",
    assignmentType: "application",
    capabilities: {
      sms: "outbound",
      calling: "inbound+outbound"
    },
    areaCode: "425"
  });

  const searchResult = await searchPoller.pollUntilDone();

  console.log(`SearchId: ${searchResult.id}`);
  console.log(`Found numbers: ${searchResult.phoneNumbers}`);
  console.log(`Expires by: ${searchResult.searchExpiresBy}`);
  console.log(
    `Monthly cost: ${searchResult.monthlyRate.currency} ${searchResult.monthlyRate.value}`
  );
```
#### Python
```Python
  country_code = "US"
  search_capabilities = SearchCapabilities(
    sms="outbound",
    calling="inbound+outbound"
  )

  search_phone_numbers_poller = phone_number_administration_client.begin_search_phone_numbers(
    country_code=country_code,
    number_type="geographic",
    assignment_type="application",
    capabilities=search_capabilities,
    area_code="425",
    quantity=2
  )

  search_result=search_phone_numbers_poller.result()
  print('SearchId: ', search_result.id)
  print('Monthly Rate: ', search_result.monthly_rate.value)
  for phoneNumber in search_result.phone_numbers:
    print('Available Phone Number: ', phoneNumber)
```

#### Java
```Java
  String searchId = "SEARCH_ID";

  SyncPoller<Operation, SearchResult> syncPoller = phoneNumberClient.beginPurchasePhoneNumber(searchId);
  syncPoller.waitForCompletion();

  System.out.println("Purchase Completed for the Search: " + searchId);
```
#### C#
```C#
  string searchId = "SEARCH_ID";
  var purchasePhoneNumberOperation = await phoneNumberClient.StartPurchasePhoneNumbersAsync(searchId);
  await purchasePhoneNumberOperation.WaitForCompletionAsync().ConfigureAwait(false);
  SearchResult searchResult = purchasePhoneNumberOperation.Value;

  Console.WriteLine("Purchase completed for the search:" + searchResult.Id);
```
#### TypeScript
```typescript
  const purchasePoller = await client.beginPurchasePhoneNumbers(searchResult.id);
  const purchaseResult = await purchasePoller.pollUntilDone();

  console.log("Purchase succeeded");
```
#### Python
```Python
  search_id = "SEARCH_ID"
  purchase_phone_numbers_poller = phone_number_administration_client.begin_purchase_phone_numbers(
    search_id=search_id
  )

  search_result=purchase_phone_numbers_poller.result()
  print('Purchase completed for the search: ', search_result.id)
```
#### Java
```Java
  String phoneNumber = "PHONE_NUMBER";
  Capabilities capabilities = new Capabilities()
      .setSms(CapabilityValue.INBOUND_OUTBOUND)
      .setCalling(CapabilityValue.INBOUND_OUTBOUND);

  AcquiredPhoneNumberUpdate acquiredPhoneNumberUpdate = new AcquiredPhoneNumberUpdate()
      .setCapabilities(capabilities)
      .setApplicationId("1dcb5bde-f5f5-4195-a1c1-43f157688769")
      .setCallbackUrl("https://contoso.com/webhooks/phone");

  SyncPoller<Operation, AcquiredPhoneNumber> syncPoller = phoneNumberClient
       .beginUpdatePhoneNumber(phoneNumber, acquiredPhoneNumberUpdate);

  AcquiredPhoneNumber acquiredPhoneNumber = syncPoller.getFinalResult();
  System.out.println("Updated SMS: " + acquiredPhoneNumber.getCapabilities().getSms().toString());
  System.out.println("Updated Calling: " + acquiredPhoneNumber.getCapabilities().getCalling().toString());
```
#### C#
```C#
 var updatePhoneNumberOperation = await phoneNumberClient.StartUpdatePhoneNumberAsync(
     "PHONE_NUMBER",
      callbackurl:  "https://contoso.com/webhooks/phone",
      applicationId: "1dcb5bde-f5f5-4195-a1c1-43f157688769",
      capabilities: new CapabilitiesRequest() { Sms = CapabilityValue.InboundOutbound }
);
await updatePhoneNumberOperation.WaitForCompletionAsync().ConfigureAwait(false);
AcquiredPhoneNumber acquiredPhoneNumber = updatePhoneNumberOperation.Value;

Console.WriteLine("Updated Application Id:" + acquiredPhoneNumber.ApplicationId.ToString());
Console.WriteLine("Updated Callback Url:" + acquiredPhoneNumber.CallbackUrl.ToString());
Console.WriteLine("Updated SMS:" + acquiredPhoneNumber.Capabilities.Sms.ToString());
```
#### TypeScript
```typescript
  const updatePoller = await client.beginUpdatePhoneNumber("+1412555000", {
    applicationId: "1dcb5bde-f5f5-4195-a1c1-43f157688769",
    callbackUrl: "https://contoso.com/webhooks/phone",
    capabilities: {
      sms: "inbound+outbound"
    }
  });

  const updatedPhoneNumber = await updatePoller.pollUntilDone();
  console.log("New applicationId: ", updatedPhoneNumber.applicationId);
  console.log("New callbackUrl: ", updatedPhoneNumber.callbackUrl);
  console.log("New capabilities: ", updatedPhoneNumber.capabilities);
```
#### Python
```Python
  phone_number = "PHONE_NUMBER"
  capabilities = Capabilities(
    sms="inbound+outbound" 
  )

  update_phone_number_poller = phone_number_administration_client.begin_update_phone_number(
    phone_number=phone_number,
    callback_url = "https://contoso.com/webhooks/phone",
    application_id = "1dcb5bde-f5f5-4195-a1c1-43f157688769",
    capabilities = capabilities
  )

  update_result=update_phone_number_poller.result()
  print("Updated Application Id:" + update_result.application_id)
  print("Updated Callback Url:" + update_result.callback_url)
  print("Updated SMS:" + update_result.capabilities.sms)
```
#### Java
``` Java
  String phoneNumber = "PHONE_NUMBER";

  SyncPoller<Operation, Void> syncPoller = phoneNumberClient.beginReleasePhoneNumber(phoneNumber);
  syncPoller.waitForCompletion();

  System.out.println("Released Phone Number: " + phoneNumber);
```
#### C#
```C#
  string phoneNumber = "PHONE_NUMBER";
  var releasePhoneNumberOperation = await phoneNumberClient.StartReleasePhoneNumberAsync(phoneNumber);
  await releasePhoneNumberOperation.WaitForCompletionAsync().ConfigureAwait(false);

  Console.WriteLine("Release succeeded for phone number: " + phoneNumber);
```
#### TypeScript
```typescript
  const releasePoller = await client.beginReleasePhoneNumber("+1412555000");
  const releaseResult = await releasePoller.pollUntilDone();

  console.log("Release succeeded");
```
#### Python
```Python
  phone_number = "PHONE_NUMBER"
  release_phone_number_poller = phone_number_administration_client.begin_release_phone_number(
    phone_number=phone_number
  )

  release_phone_number_poller.result()
  print('Release succeeded for phone number: ', phone_number)
```
#### Java
```Java
  PagedIterable<AcquiredPhoneNumber> acquiredPhoneNumbers = phoneNumberClient.listAcquiredPhoneNumbers();

  System.out.println("Displaying all acquired phone numbers");
  for (AcquiredPhoneNumber acquiredPhoneNumber : acquiredPhoneNumbers) {
      System.out.println(acquiredPhoneNumber.getPhoneNumber());
  }
```
#### C#
```C#
Pageable<AcquiredPhoneNumber> acquiredPhoneNumbers = phoneNumberClient.ListPhoneNumbers();

foreach (AcquiredPhoneNumber acquiredPhoneNumber in acquiredPhoneNumbers)
{
    Console.WriteLine("Phone number: " + acquiredPhoneNumber.PhoneNumber);
    Console.WriteLine("Purchase date: " + acquiredPhoneNumber.PurchaseDate.ToString());
}
```
#### TypeScript
```typescript
  for await (const phoneNumber of client.listPhoneNumbers()) {
    console.log("phone number: ", phoneNumber.phoneNumber);
    console.log("properties: ", phoneNumber);
  }
```
#### Python
```Python
  acquired_phone_numbers = phone_number_administration_client.list_acquired_phone_numbers()
  print('Displaying all acquired phone numbers')
  for acquired_phone_number in acquired_phone_numbers:
    print(acquired_phone_number.phone_number)
```

**Comment by RezaJooyandeh** [comment]
@kyle-patterson is there an issue with ApiView, we have been unable to upload the ApiView for Python. We posted the link to the commit that has the API though above

**Comment by annatisch** [comment]
@ankitarorabit, @RezaJooyandeh - could we please get the APIview for Python?

**Comment by RezaJooyandeh** [comment]
@annatisch We keep getting an error when we try to create the APIView for Python.

**Comment by RezaJooyandeh** [comment]
@annatisch can we use the links posted above in the issue for now?

**Comment by annatisch** [comment]
@RezaJooyandeh - the links above don't allow us to leave comments and record feedback. The links also only show the client, not models or other public API surface.
Could you try [these instructions](https://github.com/Azure/azure-sdk-pr/blob/ad7021442b0886b85c82c4296fcb3ffbd8169a60/training/azure-sdk-apis/tutorials/api-design-intro/review-the-api/review-the-api-python.md#generating-an-api-stub) to do the stub gen locally? This should help show what error the parser is hitting.

**Comment by RezaJooyandeh** [comment]
@annatisch looking into it. In the meantime, I made a PR so you can have leave comments on: https://github.com/Azure/azure-sdk-for-python/pull/15593/files#diff-59a84260af57e4ac15fb000a458fe6ebdd100b5710a3e41a697db67ea7619c07L4

**Comment by RezaJooyandeh** [comment]
@annatisch we did it!
https://apiview.dev/Assemblies/Review/52482dd7517d4bf1a200a9283f49b039#azure.communication.administration.PhoneNumberAdministrationClient

**Comment by lilyjma** [comment]
[MS Internal Only] [Recording](https://microsoft-my.sharepoint-df.com/:v:/p/rejooyan/EcCSl_kkXPRAstsGYXljdoQBHIqypQFNLY8el_ckJjPLKA)

**Comment by RezaJooyandeh** [comment]
Already approved and released
