### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - SMS

### ISSUE THREAD

**Issue by tophpalmer** [Azure/azure-sdk#1898]
## The Basics

* Responsible service team: Azure Communication Services (SPOOL)
* Link to documentation describing the service: 
* Product Manager contact email: Chris Palmer, chpalm@microsoft.com, @tophpalmer 
* Dev Lead contact email: Ankit Arora, ankita@microsoft.com, @ankitarorabit  
* Expected code complete date: Feb 7
* Expected release date: Mar 7 (GA)

## About this client library

* Name of the client library: Azure.Communication.Sms
* Languages for this review: C#, Java, JS and Python
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/pull/12406/files#diff-96292c049d9b2917fcf044e28a2f2999bfc05f87dde870a1b98ad3d8205c80df

The Azure.Communication.Sms package provides the capabilities of sending SMS message from an ACS Phone Number to any other phone number. Till now, this capability was limited to sending messages to a single phone number but this change adds the capability of sending SMS to multiple phone numbers. The backend restricts that number to 100 as of today but this limit is expected to increase in future.

This change also brings consistency across the languages and we will represent Phone Numbers as String instead of an identifier object. The reason is that this package deals with only one type of communication object (Phone Number) and identifying it as an identifier is just an added complexity for developers.

```typescript
  const from = "+1425551111";
  const to = ["+14255552222", "+14255553333", "+14255554444"];
  const message = "Hello Everyone!";

  // Send SMS message
  client.send({ from, to, message });
```

Separately, this change also adds support for a custom tag that could be used by Contoso to track their requests. This tag is returned along with the delivery receipt and therefore helps Contoso track the completion of their requests. Other than this the Rest API also adds support for repeatability parameters to support idempotency but the SDK will not expose them to Contoso and use them internally to ensure idempotency within in the SDK implementation.

```typescript
  // Send SMS message
  client.send({ from, to, message }, { enableDeliveryReport: true, tag: "customTag" });
```

If the delivery reports are enabled, the delivery events are emitted by the Event Grid. Contoso can look these up by subscribing to the Microsoft.Communication.SMSDeliveryReportReceived event. The delivery report contains message metadata such as sender and receiver numbers, message status, delivery timestamps etc. and would now also contain the custom tag that is passed by Contoso to correlate with the request on their side.

```Json
[
    {
        "id": "20201203031538e714b9ab-d2d0-4299-a8e0-422f510b06fe",
        "topic": "/subscriptions/50ad1522-5c2c-4d9a-a6c8-67c11ecb75b8/resourcegroups/emissary-rg/providers/microsoft.communication/communicationservices/emissary-sms-proxy",
        "subject": "/phonenumber/18332143356",
        "data": {
            "messageId": "20201203031538e714b9ab-d2d0-4299-a8e0-422f510b06fe",
            "from": "14255551111",
            "to": "18332153344",
            "deliveryStatus": "Success",
            "deliveryStatusDetails": "Message sent successfully",
            "tag":"customTag",
            "receivedTimestamp": "2020-12-03T03:15:38.96Z",
            "deliveryAttempts": [
                {
                    "timestamp": "2020-12-03T03:15:38.96Z",
                    "segmentsSucceeded": 1,
                    "segmentsFailed": 2
                },
                {
                    "timestamp": "2020-12-03T03:15:38.96Z",
                    "segmentsSucceeded": 1,
                    "segmentsFailed": 0
                }
            ]
        },
        "eventType": "Microsoft.Communication.SMSDeliveryReportReceived",
        "dataVersion": "1.0",
        "metadataVersion": "1",
        "eventTime": "2020-12-03T03:15:39Z"
    }
]
```

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Link: https://apiview.dev/Assemblies/Review/cfcdb4ffe0e24019ab11b82716e51409
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-net/pull/18178/files#diff-c2109537939d921821e7fc6fdf9f0bff9d6e702f507696950ca9fc416f0b03ac

### Java

* Link: https://apiview.dev/Assemblies/Review/1733781fe2584c6a989468dce3e74356
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-java/pull/18770/files#diff-f1feb2cf8c580e052d3ab56b68407c35444f3606111b0ae30fffa853d68399f8

### Python

* Link: https://apiview.dev/Assemblies/Review/f5d7cd8246734532ac59a09de84660a9
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-python/pull/16325/files#diff-56027717a58084d7501144e5ac7a64a92130dfc43e7b1a0863957f3745351d29

### TypeScript

* Link: https://apiview.dev/Assemblies/Review/427f3a68a7e54fa484af4e35e80e7e88
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-js/pull/13421/files#diff-56f732bc0570f0af100281139d6febc0b1085f4b93936d962e8a738c03b86ceb

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

#### Java
```Java
  // to enable a delivery report to the Azure Event Grid
  SendSmsOptions options = new SendSmsOptions();
  options.setEnableDeliveryReport(true);

   // Send an sms to multiple phone numbers
  List<String> toMultiplePhones = new ArrayList<String>();
  toMultiplePhones.add("<to-phone-number1>");
  toMultiplePhones.add("<to-phone-number2>");

  // Send the message to a list of  phone Numbers and check the response for a messages ids
  PagedIterable<SendSmsResponseItem> responseMultiplePhones = smsClient.send(
      "<leased-phone-number>",
      toMultiplePhones,
      "your message",
      options /* Optional */);

  for (SendSmsResponseItem messageResponseItem
      : responseMultiplePhones) {
      System.out.println("MessageId sent to " + messageResponseItem.getTo() + ": " + messageResponseItem.getMessageId());
  }
```
#### C#
```C#
  string connectionString = "YOUR_CONNECTION_STRING";
  smsClient client = new SmsClient(connectionString);

   /// send an sms to multiple recipients
  Pageable<SendSmsResult> results = smsClient.Send(
      from: "<leased-phone-number>",
      to: new[] { "<to-phone-number-1>", "<to-phone-number-2>", "<to-phone-number-3>" },
      message: "<group-message-to-send>",
      sendSmsOptions: new SendSmsOptions // OPTIONAL
      {
           EnableDeliveryReport = true,
           Tag = "<custom-tags>",
      });
  foreach (SendSmsResult result in results)
  {
      Console.WriteLine($" MessageId: {result.MessageId} Sent to: {result.To}");
  }
```
#### TypeScript
```typescript
  // Your E.164 formatted phone number used to send SMS
  const from = "<leased-phone-number>",

  // The list of E.164 formatted phone numbers to which message is being send
  const to = ["<to-phone-number-1>", "<to-phone-number-2>", "<to-phone-number-3>"],

  // The message being sent
  const message = "Hello World via SMS!";

  // Send SMS message
  const sendResults = client.send(
    { from, to, message },
    { enableDeliveryReport: true, tag: "customTag" }
  );

  for await (const sendResult of sendResults) {
    console.log(`MessageId: ${sendResult.messageId} Sent to: ${sendResult.to}`);
  }
```
#### Python
```Python
  sms_results = sms_client.send(
      from_phone_number="<leased-phone-number>",
      to_phone_numbers=["<to-phone-number-1>", "<to-phone-number-2>", "<to-phone-number-3>"],
      message="Hello World via SMS",
      enable_delivery_report=True, # optional property
      tag="custom-tag") # optional property

  for sms_result in sms_results:
      print(sms_result)
```

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
scheduled for 1/27

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/8f36a4ff-0400-9887-4802-f1eb60fbf88d?referrer=https:%2F%2Fstatics.teams.cdn.office.net%2F)MS INTERNAL ONLY

**Comment by RezaJooyandeh** [comment]
Already approved and released last year
