### ISSUE TITLE
Connect issues in a service to the service support channels

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#190]
This issue is to track the investigation and implementation of a system to connect issues opened in our GitHub repos with the service team support channels for that service.  While something already exists to bubble them up as Service 360 items, we’ve been asked to not drive the KPI through S360 anymore.  Instead we want to connect GitHub issues with the Teams support channels that are being set up and just measure and report on the github issues themselves. This is a recent change in how service teams are measuring their support commitments.

**Comment by maggiepint** [comment]
Note - James Casey from the ADX team is working on a process for this. Should piggyback on whatever they do.
