### ISSUE TITLE
Board Review: Form Recognizer 3.1.0 beta 1 (.NET & Python)

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk#1905]
## The Basics

* Service team responsible for the client library: Form Recognizer
* Link to documentation describing the service: https://docs.microsoft.com/azure/cognitive-services/form-recognizer/overview
* Contact email (if service team, provide PM and Dev Lead): Sandeep Parab (@ramparab)

## About this client library

* Name of the client library: azure.ai.formrecognizer
* Languages for this review: .NET and Python
* Link to the service REST APIs: https://westcentralus.dev.cognitive.microsoft.com/docs/services/form-recognizer-api-v2-1-preview-1/operations/AnalyzeBusinessCardAsync

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* APIView Link:  https://apiview.dev/Assemblies/Review/cf2c57b3d4c44ef08c2e8284f7441a2d?diffRevisionId=714267e3f977493fa2690daf64c2df11&doc=False
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/formrecognizer/Azure.AI.FormRecognizer/samples

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/36ac7c8c633d4bf6a45ee8672243f195?diffRevisionId=26737bcc186542c69b0ac35155d27181&doc=False
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/samples

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

**Champion Scenario 1: Model Compose**
* Describe the champion scenario
A user had created 100 models for 100 different types of documents. Now for each incoming document, which model should the user route the document to extract key/value? Currently, a user has to classify the documents using self-built methods which are costly and inaccurate. with Model Compose feature, they could let Form Recognition Services do the classification and expect a high quality result with similar analyze() call to the composed model.

Expect: Form Services should support such scenario in our API:

User could create a collection of models by calling Compose()
This model collection would react to the Analyze() call with the best result returned, the same ways as we call a single model.

* Estimate the percentage of developers using the service who would use the champion scenario
most enterprise customers would run into "how to classify different models" problem, Model Compose could be their solution.
Link to the code sample

* Link to the code sample
**.NET** - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/samples/Sample8_ModelCompose.md
**Python** - https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_create_composed_model.py

**Champion Scenario 2: Business Cards**

* Describe the champion scenario
A customer has collected many business cards during a work event and would like to extract all the relevant information to potentially feed it to a contact list, or an automated distribution list to thank the hosts and organize follow-ups. With the Analyze Business Card operation , extracting the key information from business cards in the form of key/value pairs

* Estimate the percentage of developers using the service who would use the champion scenario
This Operation is quite specialized and doesn't offer many more scenarios

* Link to the code sample
**.NET** - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/samples/Sample9_RecognizeBusinessCards.md
**Python** - https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_business_cards.py

**Champion Scenario 3: Selection Marks**

* Describe the champion scenario
Identify selection marks like radio buttons or checkboxes on forms and whether they are selected or not selected.

* Estimate the percentage of developers using the service who would use the champion scenario
Not sure.

* Link to the code sample
**.NET** - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/samples/Sample1_RecognizeContentFromFile.cs#L55-L63
**Python** - https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_content.py

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service: (**Scheduled for 10/8 - Issue** #1881 )
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
scheduled for 10/21

**Comment by lilyjma** [comment]
[Recording](https://login.microsoftonline.com/common/oauth2/authorize?client_id=cf53fce8-def6-4aeb-8d30-b158e7b1cf83&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dAQAAAAIAAAAJLnJlZGlyZWN0Smh0dHBzOi8vd2ViLm1pY3Jvc29mdHN0cmVhbS5jb20vdmlkZW8vMGE0NGExZmYtMDQwMC05ZmIyLWJlZDgtZjFlYjE4YTVhM2Y5CG5vbmNlS2V5mwFVcGJsLWtRZHBMYkpfX1pCcE51Qm9aaDFjdGMxdUxvdWdOZDBRalZmX2pvS2NHQ3dWZXM2d29IUFpOMk10anZHVDNaZUFvOWFEMXZXcThyTnAyc1daUnVHZFhuTVQ3NWxuYWJzTWl0Mng2SzFHcWlCclZ3OW0taHpSeHNHWlNUQklwOXotOTdsM1hGeHp1eVJYTWlUeGp3QlhhWQ&nonce=637394356518520880.NzEyNmE1ODgtZWU1MC00NjgyLWExYzctMzFhZDkxM2ZmYTcyODNhNTRkOTItOWJhOS00ZThiLWFkZGYtNzk4YmZiMjVkZTBh&nonceKey=OpenIdConnect.nonce.CL8OffJo1upTe4nAmJOTNqZ0tEAeZykGXnDAhv4i5Lc%3d&site_id=500453&redirect_uri=https%3a%2f%2fweb.microsoftstream.com%2f&post_logout_redirect_uri=https%3a%2f%2fproducts.office.com%2fmicrosoft-stream&msafed=0&prompt=none&sso_reload=true)[MS Internal Only]
