### ISSUE TITLE
Automate Azure Arc testing

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk#1908]
Tracking issue for step-by-step instructions for how to manually run e2d tests for Azure Arc hosted environments for each of the azure-sdk-for-* languages.  This issue will be used by our Vendor team for manually running tests in this scenario, and will eventually be referenced by Central-EngSys for adding this environment to our automated test runs.

Assigning to @catalinaperalta who will create the initial instructions specific to Azure SDK for Go.  Other SDK languages will be appended to this issue as comments.

**Comment by catalinaperalta** [comment]
# Testing Azure Identity in Azure Arc Environments

## Prerequisites 
1. A non-Azure Windows VM with Azure Arc installed on it. (See <b>Installing Azure Arc on the VM</b> on steps to follow)
2. Administrator privileges on the VM.

### Installing Azure Arc on the VM

***Please note, you must be in your VM to install Azure Arc.***

1. Create an Azure Arc service instance on Azure Portal.
2. Click on your Azure Arc service instance and on the main page, under the "Getting Started" tab select <b>Add</b> in the "Add your existing infrastructure" section.
3. On the next page click on <b>Add</b> under "Servers".
4. When configuring the Arc server, on the "Resource Details" tab  select the right resource group, region and operating system for your specific VM. 
5. No other configuration is necessary. You can go to the "Download and run script tab" and click on <b>Download</b>. This will download the installation script. 
6. Once the script has been downloaded, run the script on your machine with administrator privileges. 
7. Installation should be complete at this point. You might have to close and reopen your terminal or Powershell window to get the new configuration. 
8. Check your installation by checking for the `IDENTITY_ENDPOINT`. (In Powershell on Windows: `echo $env:IDENTITY_ENDPOINT`). The output should be similar to: `http://localhost:40342/metadata/identity/oauth2/token`.

## Run the Azure Identity Test on the Azure Arc VM

***The following steps are specific to Go***

### Install Go 
1. Download and run the Go installer for Windows at https://golang.org/dl/. 
2. In a Powershell window run `go version` to check Go installation.

### Download the repo and run the test
1. In a Powershell window run: `git clone --single-branch --branch addAzureArcAuthentication https://github.com/Azure/azure-sdk-for-go.git`.
2. Change directory to the azidentity package: `cd azure-sdk-for-go/sdk/azidentity`.
3. Open a new Powershell window as Administrator.
4. Run the test: `go test -run TestManagedIdentityCredential_GetTokenInAzureArcLive`
5. Expected output: `PASS`

**Comment by mccoyp** [comment]
# Testing azure-identity in Azure Arc (in Python)

## Prerequisite tools

1. A non-Azure Windows or Linux VM.
2. Administrator privileges on the VM.
3. An Azure Key Vault.
4. Python 2.7 and 3.5+

### Install Azure Arc on the VM

> **Note:** You must be in your VM to install Azure Arc.

1. Create an Azure Arc server resource on the [Azure Portal](https://portal.azure.com) (at the time of writing, the
resource is named "Servers - Azure Arc").
2. Choose to add an existing server using an interactive script.
3. When creating the resource, fill in your desired subscription, resource group, and region for the VM. Choose the 
operating system of your existing VM.
4. No other configuration is necessary. You can go to the "Download and run script" tab and download the script shown.
5. Once the script has been downloaded, run the script on your machine with administrator privileges.
6. If using a Linux VM, run the following commands (using your user name for `<user>`) to gain necessary privileges:
```
sudo usermod -a -G himds <user>
sudo setfacl -m "g:himds:r-x" /var/opt/azcmagent/tokens/
sudo setfacl -m "g::r-x" /var/opt/azcmagent/tokens/
```
7. Arc setup should now be complete. Restart your VM to finalize your environment setup.
8. After restarting, check your environment by searching for environment variables named `IDENTITY_ENDPOINT` and 
`IMDS_ENDPOINT`. If they are not present, or don't resemble `http://localhost:40342/metadata/identity/oauth2/token` and 
`http://localhost:40342` respectively, you may need to wait a short while or try restarting the VM again.

## Give the Azure Arc VM access to the key vault

For the tests to pass, the VM will need secret management permissions in your key vault. 

1. Go to your key vault resource in the [Azure Portal](https://portal.azure.com).
2. Go to the vault's "Access policies" page, and click "Add Access Policy". 
3. Using the secret management template, select your Arc VM resource as the principal. 
4. Click "Add".
5. Don't forget to click "Save" at the top of the access policies page after the policy is added.

## Run the azure-identity Tests on the Azure Arc VM

> **Note:** The following steps are specific to Python.

In a terminal window, run:
```
git clone https://github.com/Azure/azure-sdk-for-python --single-branch --branch master --depth 1
cd azure-sdk-for-python/sdk/identity/azure-identity/tests/managed-identity-live
```
Set the environment variable `AZURE_IDENTITY_TEST_VAULT_URL` to the vault URI of your key vault.

Install `requirements.txt`:
```
pip install -r requirements.txt
```
Run the managed identity tests, using the below command once with Python 2.7 and once with Python 3.5+:
```
pytest -k managed_identity_live
```
Expected output for each: `passed` for all tests run.

**Comment by JosueJoshua** [comment]
Hi @catalinaperalta ,the branch addAzureArcAuthentication cannot be found in the repo 'azure-sdk-for-go'.

**Comment by catalinaperalta** [comment]
@JosueJoshua I fixed the instructions, you can simply clone the repo and use the content that's in master now. Thanks!

**Comment by sadasant** [comment]
# Testing azure-identity in Azure Arc (in JavaScript)

## Prerequisite tools

1. A non-Azure Windows or Linux VM.
2. Administrator privileges on the VM.
3. An Azure Key Vault.
4. NodeJS 8 or higher.

### Install Azure Arc on the VM

> **Note:** You must be in your VM to install Azure Arc.

1. Create an Azure Arc server resource on the [Azure Portal](https://portal.azure.com) (at the time of writing, the
resource is named "Servers - Azure Arc").
2. Choose to add an existing server using an interactive script.
3. When creating the resource, fill in your desired subscription, resource group, and region for the VM. Choose the 
operating system of your existing VM.
4. No other configuration is necessary. You can go to the "Download and run script" tab and download the script shown.
5. Once the script has been downloaded, run the script on your machine with administrator privileges.
6. If using a Linux VM, run the following commands (using your user name for `<user>`) to gain necessary privileges:
```
sudo usermod -a -G himds <user>
sudo setfacl -m "g:himds:r-x" /var/opt/azcmagent/tokens/
sudo setfacl -m "g::r-x" /var/opt/azcmagent/tokens/
```
7. Arc setup should now be complete. Restart your VM to finalize your environment setup.
8. After restarting, check your environment by searching for environment variables named `IDENTITY_ENDPOINT` and 
`IMDS_ENDPOINT`. If they are not present, or don't resemble `http://localhost:40342/metadata/identity/oauth2/token` and `http://localhost:40342` respectively, you may need to wait a short while or try restarting the VM again.

## Give the Azure Arc VM access to the key vault

For the tests to pass, the VM will need secret management permissions in your key vault. 

1. Go to your key vault resource in the [Azure Portal](https://portal.azure.com).
2. Go to the vault's "Access policies" page, and click "Add Access Policy". 
3. Using the secret management template, select your Arc VM resource as the principal. 
4. Click "Add".
5. Don't forget to click "Save" at the top of the access policies page after the policy is added.

## Run the azure-identity Tests on the Azure Arc VM

> **Note:** The following steps are specific to JavaScript.

Create a new folder for the identity test:

    mkdir identity-test

Change directory to that folder with `cd identity-test`, then copy the following content in a file named `package.json`:

```json
{
  "name": "identity-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@azure/identity": "1.2.0",
    "@azure/keyvault-keys": "4.1.0",
  }
}
```

Then, copy the following code in a file named `index.js` (Make sure to replace `key-vault-name` with the name of your Key Vault):

```js
const { ManagedIdentityCredential } = require("@azure/identity");
const { KeyClient } = require("@azure/keyvault-keys");

async function main() {
  const credential = new ManagedIdentityCredential();
  const keyVaultUrl = `https://key-vault-name.vault.azure.net`;
  const client = new KeyClient(keyVaultUrl, credential);

  // Retrieving the properties of the existing keys in that specific Key Vault.
  // This might log empty if no keys have been created in the given Key Vault.
  console.log(await client.listPropertiesOfKeys().next());

  console.log("Test succeeded!");
}
main().then(console.log).catch((e) => console.error(e));
```

With the `package.json` and the `index.js`, you'll be able to install the dependencies with: `npm install` in that directory, then run the test by executing `node index.js`. If you see `Test succeeded!` in the console, then Identity has successfully authenticated for your VM through Azure Arc.

**Comment by JosueJoshua** [comment]
Hi @sadasant , it's using secret management template to add access policy in the third step, perhaps it should use key management template.

**Comment by sadasant** [comment]
@JosueJoshua that is true! thank you!

**Comment by sadasant** [comment]
I updated it!

**Comment by maorleger** [comment]
# Testing Identity in Azure Arc (Latest JavaScript instructions)

> These instructions are also available [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/identity/identity/test/manual-integration/AzureArc/INSTRUCTIONS.md)

## Prerequisites

- A non-Azure Windows or Linux virtual machine with NodeJS, NPM, and git installed.
- Administrator privileges on the VM.
- An Azure Key Vault.

### Install Azure Arc on the VM

> **Note:** You must be in your VM to install Azure Arc.

1. Create an Azure Arc server resource on the [Azure Portal](https://portal.azure.com) (at the time of writing, the
   resource is named "Azure Arc").
2. Choose to add an existing server using an interactive script.
3. When creating the resource, fill in your desired subscription, resource group, and region for the VM. Choose the
   operating system of your existing VM.
4. No other configuration is necessary. You can go to the "Download and run script" tab and download the script shown.
5. Once the script has been downloaded, run the script on your machine with administrator privileges.
6. If using a Linux VM, run the following commands (using your user name for `<user>`) to gain necessary privileges:

```
sudo usermod -a -G himds <user>
sudo setfacl -m "g:himds:r-x" /var/opt/azcmagent/tokens/
sudo setfacl -m "g::r-x" /var/opt/azcmagent/tokens/
```

7. The Azure Arc setup should now be complete. Restart your VM to finalize your environment setup.
8. After restarting, check your environment by searching for environment variables named `IDENTITY_ENDPOINT` and
   `IMDS_ENDPOINT`. If they are not present, or don't resemble `http://localhost:40342/metadata/identity/oauth2/token` and
   `http://localhost:40342` respectively, you may need to wait a short while or try restarting the VM again.

## Give the Azure Arc VM access to the key vault

For the tests to pass, the VM will need secret management permissions in your key vault.

1. Go to your key vault resource in the [Azure Portal](https://portal.azure.com).
2. Go to the vault's "Access policies" page, and click "Add Access Policy".
3. Using the secret management template, select your Arc VM resource as the principal.
4. Click "Add".
5. Don't forget to click "Save" at the top of the access policies page after the policy is added.

## Run the azure-identity Tests on the Azure Arc VM

> **Note:** The following steps are specific to JavaScript.

In a terminal window, run:

```bash
git clone https://github.com/Azure/azure-sdk-for-js --single-branch --depth 1
cd azure-sdk-for-js/sdk/identity/identity/test/manual-integration/AzureArc
```

Set the environment variable `KEYVAULT_URI` to the vault URI of your key vault.

Install dependencies:

```bash
npm install
```

Compile the test file using TypeScript:

```bash
npm run build
```

Run the test file:

```bash
node dist/index.js
```

**Comment by antkmsft** [comment]
### Testing ManagedIdentityCredential in Azure Arc (in C++)

Set up a VM, Azure Resources, and Azure Arc just as you would for Go, Python, or JavaScript.

run Visual Studio Installer
Press Modify
Select "Desktop development with C++"
Go to Individual Components tab
search for "git"
Select "Git for Windows"
Press Modify, wait for installation to finish, close the Installer

Open x64 Native Tools Commond Prompt
```cmd
cd /D %USERPROFILE%
git clone https://github.com/microsoft/vcpkg.git
cd vcpkg
bootstrap-vcpkg.bat
vcpkg install curl:x86-windows openssl:x86-windows libxml2:x86-windows curl:x64-windows openssl:x64-windows libxml2:x64-windows curl:x64-windows-static openssl:x64-windows-static libxml2:x64-windows-static
```
Wait for the installation to finish (about 20 minutes)

```cmd
cd ..
git clone https://github.com/Azure/azure-sdk-for-cpp.git
cd azure-sdk-for-cpp
cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=%USERPROFILE%\vcpkg\scripts\buildsystems\vcpkg.cmake -DBUILD_TESTING=ON
cmake --build build
```

```cmd
build\sdk\identity\azure-identity\test\e2e\Debug\azure-identity-e2e-test.exe
```

Watch the output. It will either print "OK" + print "SUCCESS" in large letters, or it will print error details + the relevant environment.

Successful executions are usually instant, in case of failures the test may wait for up to a minute before printing the error details. This is caused by the credential going through retries before finally giving up.

**Comment by AFengKK** [comment]
Hi, @mccoyp
When test the Testing azure-identity in Azure Arc (in Python) and run the `pytest -k managed_identity_live` command, it displays the error :
![image](https://user-images.githubusercontent.com/80307197/153565500-d3759426-1334-47c7-a034-21180f5e6b86.png)

Through the investigation , the token cannot be obtained. I tried to delete the 'tenant_id' parameter of the code `self.authorize_request(request, scope, tenant_id=challenge.tenant_id)` in the [challenge_auth_policy.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L102), and it works normally. Can you provide some help on this issue?

**Comment by zzkaii** [comment]
Hi,@joshfree
When test the  Testing azure-identity in Azure Arc(in go) nd run the go test -run TestManagedIdentityCredential_AzureArc command,it display the error:
![image](https://user-images.githubusercontent.com/87058034/154901215-4e40edf8-31de-4269-a7f3-0d858aa4f5eb.png)

Through the investigation , I tried to use [internal](https://github.com/Azure/azure-sdk-for-go/tree/b509a3746c241234ddf116193fa9979cae667a3c/sdk/internal) v0.8.2, it works normally. But use [internal](https://github.com/Azure/azure-sdk-for-go/tree/b509a3746c241234ddf116193fa9979cae667a3c/sdk/internal) v0.8.3 and later version, it can't work. Can you provide some help on this issue?

**Comment by AFengKK** [comment]
Hi, @mccoyp, Thank you for your help. The test can pass with the stable version of azure-keyvault-secrets (4.3.0). In addition, if the bug is fixed, please let me know.

**Comment by joshfree** [comment]
@zzkaii I filed https://github.com/Azure/azure-sdk-for-go/issues/17143 in the Go repo to track the issue / question.

**Comment by mccoyp** [comment]
Hi @AFengKK, the latest stable release of `azure-identity` ([1.8.0](https://pypi.org/project/azure-identity/1.8.0/)) is now available and has a fix for the ManagedIdentityCredential issue you discovered -- thank you again! This new version of `azure-identity` should be compatible with any version of `azure-keyvault-secrets`. Please let me know if you run into any other issues!

**Comment by chlowell** [comment]
# Testing azidentity on Azure Arc (latest Go instructions)

## Prerequisites
* A non-Azure Windows or Linux VM with Go and git installed
* Administrator privileges on the VM

### Install Azure Arc on the VM

1. Create an Azure Arc server resource on the [Azure Portal](https://portal.azure.com) (at the time of writing, the resource is named "Servers - Azure Arc")
1. Choose to generate a script for a single server
1. Run the script on the VM with administrator privileges
1. If using a Linux VM, run the following commands (substituting your user name for `<user>`) to gain necessary privileges:
```
sudo usermod -a -G himds <user>
sudo setfacl -m "g:himds:r-x" /var/opt/azcmagent/tokens/
sudo setfacl -m "g::r-x" /var/opt/azcmagent/tokens/
```

5. Restart your VM to finalize setup
1. Check your environment variables `IDENTITY_ENDPOINT` and `IMDS_ENDPOINT`. If they aren't set, you may need to wait a short while or restart the VM again.

## Run the test on the Azure Arc VM

In a terminal window, run:

```
git clone https://github.com/Azure/azure-sdk-for-go --single-branch --depth 1
cd azure-sdk-for-go/sdk/samples/azidentity/manual-tests/managed-identity/general
go run main.go
```

Expected output: `Success! Token received.`

**Comment by v-jiaodi** [comment]
Hi, @mccoyp. We have two problems when test the Testing azure-identity in Azure Arc (in Python).

1.When test the Testing azure-identity in Azure Arc (in Python) and run the `pytest -k managed_identity_live` command, it displays the error :

![image](https://user-images.githubusercontent.com/80496810/186310221-b62e3af0-a77b-4501-9713-f6f4282c6384.png)

In order to install  `tools_testutils`, I try to add code as follow to [requirements.txt](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/tests/managed-identity-live/requirements.txt).
```
../../../../../tools/azure-devtools
../../../../../tools/azure-sdk-tools
```
I suggest sending a PR to fix it.

2.Rerun ` pytest -k managed_identity_live`  and get a new error as follow：

![image](https://user-images.githubusercontent.com/80496810/186380066-dc41c2a7-56cb-4e86-8f79-aa429d6e215c.png)

Through the investigation, I found that we need to configure the **test-proxy** to pass the test. It is suggested to add relevant descriptions in the test process.

**Comment by mccoyp** [comment]
Hi @v-jiaodi, thank you for the summary! I'm sorry about the delayed response.

Getting the test proxy set up in the test environment may be possible, but it would likely be more difficult than is worth attempting. I created a tracking issue (https://github.com/Azure/azure-sdk-for-python/issues/26237) to address this and can update this thread when it's completed.

**Comment by Menghua1** [comment]
Hi @antkmsft. Following the steps above, while testing ManagedIdentityCredential in Azure Arc (in C++), we encountered an error after executing the command:
```
build\sdk\identity\azure-identity\test\e2e\Debug\azure-identity-e2e-test.exe
```
The detailed error information is as follows:
![image](https://github.com/Azure/azure-sdk/assets/111940661/3f29a38f-7b1a-44d3-b500-566aaab4805c)
Could you help to check and resolve the error?

**Comment by v-xuto** [comment]
@joshfree This issue has been closed. Do we need to continue testing this `Automate Azure Arc testing`?
