### ISSUE TITLE
Update .NET Guidelines to represent common verbs

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#1917]
We received this question on our .NET Teams channel:

_What is the general guidance for the verb to use when creating a .NET API for createOrUpdate HTTP put calls? I see in the app configuration SDK that "Add" is used, but a preview version of my team's Digital Twins library shipped with the verb "Create" instead of "Add" and we didn't receive any pushback during API review._

It would be great to update the guidelines so that they are self-explanatory with regard to this.

@tg-msft, @KrzysztofCwalina

**Comment by timtay-microsoft** [comment]
My team is looking for the same basic guidance for Java as well.

**Comment by annelo-msft** [comment]
For Java this is here: https://azure.github.io/azure-sdk/java_design.html#common-service-client-patterns

If this is insufficient for your team's needs, please let us know how we can improve them.  FYI: @JonathanGiles

**Comment by timtay-microsoft** [comment]
Those guidelines would suggest that we use "Upsert" which doesn't feel appropriate to Java either, so we'd like confirmation on that one in particular

**Comment by tg-msft** [comment]
.NET doesn't have guidance set in stone, but I'd suggest `Upsert` by default.

`TableClient.UpsertAsync(...)` and `CosmosContainer.UpsertItemAsync(...)` follow the pattern for other languages.

We've gone with more verbose operation-specific names like `SearchClient.MergeOrUploadDocumentsAsync(...)` for some services where we thought it would be helpful.
