### ISSUE TITLE
Board Review: Key Vault Administration

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk#1920]
## The Basics

* Service team responsible for the client library: Key Vault
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/key-vault/managed-hsm/overview
  * [Backup / Restore](https://docs.microsoft.com/en-us/azure/key-vault/managed-hsm/backup-restore) 
  * [RBAC](https://docs.microsoft.com/en-us/azure/key-vault/managed-hsm/role-management)
* Contact email (if service team, provide PM and Dev Lead): rich.randall@microsoft.com, jack.lichwa@microsoft.com

## About this client library

* Name of the client library: Azure.Security.KeyVault.Administration
* Languages for this review: .NET, Java, Python, Typescript
* Link to the service REST APIs: [backup/restore](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/backuprestore.json), [RBAC](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/rbac.json)

### .NET

* [apiview](https://apiview.dev/Assemblies/Review/fdeebdac9acf4e8f932b64aede1b8d55)

### Java

* [apiview](https://apiview.dev/Assemblies/Review/a222939d49b14d4299442822f069705d)

### Python

* [apiview](https://apiview.dev/Assemblies/Review/38bca7b54bbc4e9fbb6c73012a6335d6)

### TypeScript

* [Api-extractor](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-admin/review/keyvault-admin.api.md)
* [apiview](https://apiview.dev/Assemblies/Review/bcf274b6c9374875bd7aa2868431f468)

### Full Key Backup:
Create a full backup of the entire contents of the Managed HSM including all keys, versions, attributes, tags, and role assignments. The backup is encrypted with cryptographic keys associated with the HSM's security domain.

#### Sample code
[.NET](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Administration/samples/Sample1_BackupHelloWorldAsync.md#performing-a-full-key-backup)
[Java]()
[Python](https://github.com/Azure/azure-sdk-for-python/blob/a10d9cbbcf8735de60bb648d412bf5ff25dcbaff/sdk/keyvault/azure-keyvault-administration/tests/test_backup_client.py#L43-L44)
[Typescript](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-admin/samples/typescript/src/backupRestoreHelloWorld.ts#L19-L26)

### Full Key Restore:
Completely restore the contents of the Managed HSM with a previous backup, including all keys, versions, attributes, tags, and role assignments. Everything currently stored in the HSM will be wiped out, and it will return to the same state it was in when the source backup was created.

#### Sample code
[.NET](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Administration/samples/Sample1_BackupHelloWorldAsync.md#performing-a-full-key-restore)
[Java]()
[Python](https://github.com/Azure/azure-sdk-for-python/blob/a10d9cbbcf8735de60bb648d412bf5ff25dcbaff/sdk/keyvault/azure-keyvault-administration/tests/test_backup_client.py#L57)
[Typescript](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-admin/samples/typescript/src/backupRestoreHelloWorld.ts#L28-L36)

### Role Based Access List Role Definitions
List all the roles available for assignment.

### Sample code
[.NET](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Administration/samples/Sample1_RbacHelloWorldSync.md#listing-all-role-definitions)
[Java]()
[Python](https://github.com/Azure/azure-sdk-for-python/blob/a10d9cbbcf8735de60bb648d412bf5ff25dcbaff/sdk/keyvault/azure-keyvault-administration/tests/test_access_control.py#L61-L62)
[Typescript](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-admin/samples/typescript/src/accessControlHelloWorld.ts#L28-L29)

### Role Based Access Create, Get, and Delete a role assignment
Basic CRUD operations for a role assignment.

### Sample code
[.NET](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Administration/samples/Sample1_RbacHelloWorldSync.md#creating-a-role-assignment)
[Java]()
[Python](https://github.com/Azure/azure-sdk-for-python/blob/a10d9cbbcf8735de60bb648d412bf5ff25dcbaff/sdk/keyvault/azure-keyvault-administration/tests/test_access_control.py#L69-L89)
[Typescript](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-admin/samples/typescript/src/accessControlHelloWorld.ts#L31-L44)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

## Thank you for your submission

**Comment by lilyjma** [comment]
scheduled for 11/2

**Comment by JonathanGiles** [comment]
The Java code sample links above don't go anywhere. Do code samples exist for Java somewhere @vcolin7? The only content I can find is [here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-administration), but I'm not sure if that is what you plan to cover at arch board or not.

**Comment by vcolin7** [comment]
Hi @JonathanGiles, we do have an [open PR](https://github.com/Azure/azure-sdk-for-java/pull/16964) for the samples waiting to be merged. You can find them [here](https://github.com/vcolin7/azure-sdk-for-java/tree/keyvault-administration-samples/sdk/keyvault/azure-security-keyvault-administration/src/samples/java/com.azure.security.keyvault.administration) in the meantime.

**Comment by lilyjma** [comment]
[Recording][MS internal only](https://msit.microsoftstream.com/video/0a25a1ff-0400-9fb2-8e7b-f1eb1df84217?list=studio)
