### ISSUE TITLE
Board Review: Azure DigitalTwins - .NET GA SDK

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-sdk#1932]
## The Basics

* Service team responsible for the client library: Azure Digital Twins
* Link to documentation describing the service: https://github.com/Azure/azure-digital-twins/blob/private-preview/Documentation/overview.md
* Contact email (if service team, provide PM and Dev Lead): Brian Crawford (Brian.Crawford@Microsoft.com) and Christian Schormann (cschorm@Microsoft.com)

## About this client library

* Name of the client library: Azure.DigitalTwins.Core
* Languages for this review: .NET
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/digitaltwins/data-plane/Microsoft.DigitalTwins/stable/2020-10-31/digitaltwins.json

## Artifacts required (per language)

* API View Link: https://apiview.dev/Assemblies/Review/acca04f4eec643a08b3b4c7d9180f11f
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/digitaltwins/Azure.DigitalTwins.Core/samples

### Manage model lifecycle
Models represent some physical or logical entity, such as an IoT device, a room it is in, or a building that room is in. They are the cornerstone of digital twins. Each type of entity should be modeled using the DTDL schema. Once a schema is documented in the service, it can be known to other clients so when a digital twin is loaded, a program unfamiliar with that digital twin could interact with it in a dynamic way (e.g. UI created from a model to enable an operator to interact with the digital twin).

Note: this API is only available for bulk creation at this time. When multiple models are included, the service will validate any internal references and reject the request (think transaction) if the validation fails. Without that validation, one would need to create all the models in a specific order to avoid bad references.

- Create models in bulk
- List models
- Decommission a model
- Delete a model

[Sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/digitaltwins/Azure.DigitalTwins.Core/samples/DigitalTwinsClientSample/ModelLifecycleSamples.cs)

### Digital twins
Digital Twins are the entities in ADT that represent physical or logical devices. They can be created, updated, read, and deleted.

- CRUD
- Query for digital twins

[Sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/digitaltwins/Azure.DigitalTwins.Core/samples/DigitalTwinsClientSample/DigitalTwinsLifecycleSamples.cs)

### Relationships
Based on the models applied to a digital twin, it can have relationships to other digital twins. Those relationships are managed independent of the digital twin (they aren't properties directly on the twin), and are 1-way (that is, a relationship created from A->B only appears on A and not on B).

- Link a digital twins to another via a relationship
- List relationships on a digital twin
- List incoming relationships (made by other digital twins targeting this one)
- Delete a relationship

[Sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/digitaltwins/Azure.DigitalTwins.Core/samples/DigitalTwinsClientSample/RelationshipSamples.cs)

### Telemetry
Digital twins that aren't physical devices may need telemetry sent on their behalf. The service SDK provides an avenue for that.

- Publish telemetry for a digital twin, or a component on a digital twin

[Sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/digitaltwins/Azure.DigitalTwins.Core/samples/DigitalTwinsClientSample/PublishTelemetrySamples.cs)

### Event routes
An event route lets you send event data from digital twins in Azure Digital Twins to custom-defined endpoints in your subscriptions. Three Azure services are currently supported for endpoints: Event Hub, Event Grid, and Service Bus. Each of these Azure services can be connected to other services and acts as the middleman, sending data along to final destinations such as TSI or Azure Maps for whatever processing you need.

- CRUD

[Sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/digitaltwins/Azure.DigitalTwins.Core/samples/DigitalTwinsClientSample/DigitalTwinsLifecycleSamples.cs)

**Comment by lilyjma** [comment]
scheduled for 10/27

**Comment by lilyjma** [comment]
[Video](https://msit.microsoftstream.com/video/0d65a1ff-0400-9fb2-c51b-f1eb14bb3e31)[MS INTERNAL ONLY]

**Comment by tg-msft** [comment]
The .NET APIs per https://github.com/Azure/azure-sdk-for-net/blob/4a95f58bc9bad11a1a1507a620ccac5f87261315/sdk/digitaltwins/Azure.DigitalTwins.Core/api/Azure.DigitalTwins.Core.netstandard2.0.cs are approved for GA.  Thank you Digital Twins feature crew!
