### ISSUE TITLE
Storage needs SAS rotation mechanism, cross-language

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk#1942]
When initially developing libraries, the design decision was made that SAS tokens are to be treated as part of the URI always, making the token immutable upon client construction. Since SAS tokens must have an expiration date, this assigns a lifespan to any client created using SAS authorization. This is an issue for long-running services that use the client library. Many developers who have not or cannot move to Identity for their authorization, but want to hand out only specific permissions rather than full account access, use long running SAS authentication with their own refresh mechanisms.

Currently, a user can rotate their shared key within a client, so long as you maintain a reference to the StorageSharedKeyCredential object used to construct the client, and TokenCredential implementations have their own refresh mechanisms. SAS authentication is the only one left out. A mechanism to rotate SAS tokens is needed to meet customer needs, and this would go against the initial architectural decisions of the library.

[There appears to be precedent for this.](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventgrid.eventgridsharedaccesssignaturecredential?view=azure-dotnet-preview) A similar class is wanted for Storage. In keeping with the naming pattern in this precedent, we'd call the new class `StorageSharedAccessSignatureCredential`. I understand there is contention on whether the library should refer to a SAS as a "credential." If that's the case, `StorageSharedAccessSignature` would also likely work, but we'd be going against the naming conventions in EventGrid in that case.

**Comment by tg-msft** [comment]
This makes sense.  I think we should add something like this to `Azure.Storage.Common`:
```C#
namespace Azure.Storage
{
    public class StorageSharedAccessSignatureCredential {
        public StorageSharedAccessSignatureCredential(string signature);
        public void Update(string signature);
        protected static string GetSharedAccessSignature(StorageSharedAccessSignatureCredential credential);
    }
}
```

And then update all of our .ctors to add overloads like:
```C#
public class BlobServiceClient
{
    public BlobServiceClient(
        Uri serviceUri,
        StorageSharedAccessSignatureCredential credential,
        BlobClientOptions options = null) { }
    
    // ...
}
```

**Comment by tg-msft** [comment]
Please see #1954 for a more detailed discussion and resolution.

**Comment by lilyjma** [comment]
[Recording](https://web.microsoftstream.com/video/0a25a1ff-0400-9fb2-9f3b-f1eb196ee5ee) [MS Internal Only]
