### ISSUE TITLE
Board Review: Azure.IoT.DeviceModelsRepository

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-sdk#1948]
## The Basics

* Service team responsible for the client library: Azure IoT Developers and Devices
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/iot-pnp/overview-iot-plug-and-play
* Contact email (if service team, provide PM and Dev Lead): PM @rido-min DevLead @iluican 

## About this client library

* Name of the client library: `Azure.IoT.DeviceModelsRepository`
* Languages for this review: .NET and NodeJs (Python and Java coming later)
* Link to the service REST APIs: There are not REST APIs, just plain HTTP calls using a [path convention](https://github.com/Azure/iot-plugandplay-models-tools/wiki/Resolution-Convention)

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: 
* Link to samples for champion scenarios: https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/samples

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link: 
* Link to samples for champion scenarios: 

### Python

* Upload the api as a Draft PR.  Link to PR:
* Link to samples for champion scenarios:

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR:
* Link to samples for champion scenarios:

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Resolve a Model given it's DTMI:
    * IoT PnP Devices announce the Model ID making it available in the DeviceTwin.
    * Solution developers can retrieve the Model ID
    * To get the actual model (can be one or more DTDL interfaces), the customer will write:

```csharp
ResolverClient rc = new ResolverClient(new Uri("https://devicemodels.azure.com"));
IDictionary<string, string> models = await rc.ResolveAsync("dtmi:com:example:TemperatureController;1");
ModelParser modelParser = new ModelParser();
IReadOnlyDictionary<Dtmi, DTEntityInfo> parseResult = await modelParser.ParseAsync(models.Values.ToArray());
```
## Agenda for the review

I think we only need one initial meeting as the service is straightforward and the API is small.

## Additional Info
We are planning to ship a CLI tool in the form of a `dotnet tool` that will have a different ID: `dmr-client`

**Comment by lilyjma** [comment]
scheduled for 10/29

**Comment by lilyjma** [comment]
[Recording](https://web.microsoftstream.com/video/7317a1ff-0400-9fb2-0817-f1eb1a376e55)[MS internal only]
