### ISSUE TITLE
Board Review: Add SharedKey/SAS Credential types to Azure.Core (all languages)

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk#1954]
We have several services that support Shared Key and SAS credentials with the same API shape and usage:

| Service | Shared Key | Shared Access Signature |
|-|-|-|
| Storage | x | x |
| Event Grid | | x |
| Event Hubs | x | x |
| Service Bus | x | x |

I'd like to discuss adding `AzureSharedKeyCredential` and `AzureSharedAccessSignatureCredential` in Azure.Core so we don't have multiple copies of each.

_(I'll edit in API specifics, a possible plan for refreshing SAS tokens automatically, and a plan for integration with the existing StorageSharedKeyCredential)_

**Comment by tg-msft** [comment]
We should discuss together with https://github.com/Azure/azure-sdk/issues/1942

**Comment by lilyjma** [comment]
scheduled for 10/28

**Comment by avg-msft** [comment]
@lilyjma Can we get a timeline on this, please? We have an SDK upgrade feature that is blocked on this.

**Comment by tg-msft** [comment]
### Shared Key
After discussion, rather than add a specific `AzureSharedKeyCredential` we think
it would make sense to augment `AzureKeyCredential` to allow an optional name:

```diff
 namespace Azure
 {
      public class AzureKeyCredential  {
         public AzureKeyCredential(string key);
+        public AzureKeyCredential(string name, string key);
+        public string Name { get; }
         [EditorBrowsable(EditorBrowsableState.Never)]
         public string Key { get; }
         public void Update(string key);
+        public void Update(string name, string key);
     }
 }

```

Additional topics to discuss:
1. I think of signing with a shared key as slightly safer than passing an API key
   which is why I wanted separate types, but I agree that since it's a huge
   anti-pattern to use HTTP it won't matter to customers.
1. Both values needs to update atomically.  Could consider using a
   `Tuple<string, string>` for a single replacement instead of any synchronization.
1. Storage will not update to derive `StorageSharedKeyCredential : AzureKeyCredential`
   because the property names don't align and there's no meaningful benefit of
   forcing it.
1. EventHubs and ServiceBus should use this credential.
1. Tables should replace its current SharedKey credential with this one.

**Comment by tg-msft** [comment]
### SAS
While Storage currently takes SAS tokens as part of the URI and doesn't
distinguish between anonymous auth and using SAS for auth, customers have found
the inability to roll SAS tokens to be a pain point.  See https://github.com/Azure/azure-sdk/issues/1942
for more discussion about scenarios.  We're proposing an API that looks like:

```C#
namespace Azure
{
    public class AzureSharedAccessSignatureCredential {
        public AzureSharedAccessSignatureCredential(string signature);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string Signature { get; }
        public void Update(string signature);
    }
}
```

Additional topics to discuss:
1. Should we call it `AzureSasCredential` instead?  Storage uses `Sas` for
   everything today.
1. Clients libraries should throw if someone attempts to pass a SAS URI and a
   SAS credential.  It's impossible to get this right in a perfectly forward
   compatible way, but we'll get a pretty clear auth error in the cases it's
   wrong.
1. The exception message should point customers to things like `BlobUriBuilder`
   which makes it easy to remove a SAS token in code.  Similar caveats about
   forward compat apply.
1. We'd create a "shared source" pipeline policy that tacked on a SAS token to
   the URI per call.  Today I think it would work across implementations.
1. While there's not a scenario that requires it today, we can think about
   supporting automatic refresh in a future release.  The pipeline policy would
   listen for 403s on the way back, check if the SAS token expired, raise an
   event (probably sync or async depending on the path), allow the event to
   compute/fetch a new SAS token, and mark the message as retriable so customers
   never notice the expiration.  This could be added without breaking.
1. Storage, EventHubs, and ServiceBus should use this credential.
1. EventGrid should replace its current credential with this one.

**Comment by tg-msft** [comment]
### Base Type
For anyone dealing with multiple types of credentials today, it's annoying that
there's no base type.  We're on the fence about creating something like:


```C#
namespace Azure.Core
{
    public abstract class AzureCredential { }
    public abstract class TokenCredential : AzureCredential { /* ... */ }
}

namespace Azure
{
    public class AzureKeyCredential : AzureCredential { /* ... */ }
    public class AzureSharedAccessSignatureCredential : AzureCredential { /* ... */ }
}
```

Additional topics to discuss:
1. There will be no members.  It's basically only for tagging.
1. Do we want a less discoverable way of creating a client using the base
   `AzureCredential` for customers who are only holding one of these?

**Comment by tg-msft** [comment]
Recording (MS internal): https://msit.microsoftstream.com/video/0a25a1ff-0400-9fb2-9f3b-f1eb196ee5ee

Highlights:
- `AzureSasCredential` makes sense to implement immediately
- We'll see if there's time for a quick UX study around the proposed changes to `AzureKeyCredential` looking at
    - adding `Name` to `AzureKeyCredential`,
    - splitting into a separate `AzureSharedKeyCredential`,
    - or always using dedicated `(Client)SharedKeyCredential` types
- We'll hold off on a base `AzureCredential` type for now and library authors can use `object` internally.  We'll revisit when there's a customer scenario.

**Comment by lilyjma** [comment]
[Recording ](https://web.microsoftstream.com/video/0a25a1ff-0400-9fb2-9f3b-f1eb196ee5ee)[MS Internal Only]

**Comment by lilyjma** [comment]
@avg-msft : Please take a look at Ted's last comment on the priorities we have now.

**Comment by ramya-rao-a** [comment]
I see the PRs in the .Net, Java and Python repo adding both `AzureSasCredential` and `AzureSasCredentialPolicy`. While I see the discussion and conclusion for the former in this issue, I don't see any for the latter. Can anyone shed some light on this?

Also, what is the update on AzureSharedKeyCredential?
