### ISSUE TITLE
Change Request: Azure SDK for Android Guidelines

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk#1961]
## The Basics

* Which design guideline is affected?
General guidelines for mobile

* Which target languages are affected?
Android - Java

* Describe the change:
Introducing draft guidelines for Android

## Reasoning
With the recent preview of Azure Core for Mobile, the mobile team is prepared to introduce the draft guidelines for General and Azure Core

Please provide any additional detail or reasoning for the request. 
Link to Android draft guidelines: https://azure.github.io/azure-sdk/android_introduction.html
API_View_Azure_Core: https://apiview.dev/Assemblies/Review/c7a2c20d22af4bd48d51bfdf0bed02ec

Mobile team will upload API surfaces to introduce the preview of Azure Core, but the focus will be as examples of the guideline implementations.

**Comment by lilyjma** [comment]
scheduled for 11/16. @bsiegel : please remember to have Mobile team upload APIs for Azure Core.

**Comment by waynemo** [comment]
@bsiegel 
As discussed, it might be helpful to document the reasoning for using Java to implement the libraries instead of Kotlin.

**Comment by anuchandy** [comment]
API_View_Azure_Core: https://apiview.dev/Assemblies/Review/c7a2c20d22af4bd48d51bfdf0bed02ec

**Comment by lilyjma** [comment]
[MS INTERNAL ONLY][Recording](https://web.microsoftstream.com/video/47cca3ff-0400-b9eb-40b9-f1eb33684d7b)
