### ISSUE TITLE
Board Review: Document Translator

### ISSUE THREAD

**Issue by krishna-doss-mohan** [Azure/azure-sdk#1968]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library:

* Link to documentation describing the service: 
1. User Documentation: https://microsoft.sharepoint.com/:w:/r/teams/translator/internal/Shared%20Documents/Document%20Translator/User%20Documentation%20-%20Snyder.docx?d=we0ab3acd79134035be30ef45ded71027&csf=1&web=1&e=jDyN8D
2. Swagger: https://mtbatchppefrontendapp.azurewebsites.net/swagger/index.html

* Contact email (if service team, provide PM and Dev Lead): KDoss; VishalC; CPoulain

## About this client library

* Name of the client library:
* Languages for this review:
* Link to the service REST APIs:

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link:
* Link to samples for champion scenarios:

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link:
* Link to samples for champion scenarios:

### Python

* Upload the api as a Draft PR.  Link to PR:
* Link to samples for champion scenarios:

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR:
* Link to samples for champion scenarios:

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

Please find scenario document here: https://microsoft.sharepoint.com/:w:/r/teams/translator/internal/Shared%20Documents/Document%20Translator/User%20Scenarios%20-%20Snyder.docx?d=w9dbdac9d6dbe464194e2c2e047c022df&csf=1&web=1&e=yQ456E 

* Champion Scenario 1: 40% - How to translate documents? 
    * Describe the champion scenario
In Azure blob storage, user creates a container, uploads documents (optionally translation memory files) into it, creates SAS token with READ-only access to the container. User also creates a separate container to store final translated documents, creates SAS token with WRITE-only access to the container.  User shares these SAS tokens as part of request to the service.  User invokes the service with necessary parameters. Snyder returns a job id using which user can poll to find status of documents requested for translation. Snyder translates, and stores translated documents in user shared cloud storage location. Once the service uploads the result blobs to this container, the customer can download the result blobs using any Azure Storage tool (the Portal, AzCopy, Storage Explorer, etc.). 
    * Estimate the percentage of developers using the service who would use the champion scenario
    * Link to the code sample

_ Repeat for each champion scenario _
* Champion Scenario 2: 25% - How to use custom translation models while translating documents? 
User builds custom translation models using existing Custom Translator interface.  Once custom translation model is built, and deployed user get a unique identifier.  This unique identifier is passed as a configuration parameter ‘category ID’ while invoking service request. 
In Azure blob storage, user creates a container, uploads documents (optionally translation memory files) into it, creates SAS token with READ-only access to the container. User also creates a separate container to store final translated documents, creates SAS token with WRITE-only access to the container.  User shares these SAS tokens as part of request to the service.  User invokes the service with necessary parameters and specify the ‘category ID’ obtained for the custom translation model. Snyder returns a job id using which user can poll to find status of documents requested for translation. Snyder translates, and stores translated documents in user shared cloud storage location. Once the service uploads the result blobs to this container, the customer can download the result blobs using any Azure Storage tool (the Portal, AzCopy, Storage Explorer, etc.). 

* Champion Scenario 3: 15% - How to translate single document? 
In Azure blob storage, user creates a container, upload the document (optionally translation memory files) into it, creates SAS token with READ-only access to the file. User also creates a separate container to store final translated document, creates SAS token with WRITE-only access to the container.  User shares these SAS tokens as part of request to the service.  User invokes the service with necessary parameters. Snyder returns a job id using which user can poll to find status of documents requested for translation. Snyder translates, and stores translated document in user shared cloud storage location. Once the service uploads the result blobs to this container, the customer can download the result blobs using any Azure Storage tool (the Portal, AzCopy, Storage Explorer, etc.)

* Champion Scenario 4: 20% - How to translate single document via POST request? (not built yet)
User invokes the service with necessary parameters and submits document via POST request. Snyder returns a job id using which user can poll to find status of documents requested for translation. Snyder translates, stores translated document in service managed cloud storage location and returns URL to download the document with a SAS token. The customer can download the result blobs using any Azure Storage tool (the Portal, AzCopy, Storage Explorer, etc.). 

Examples of good scenarios are technology agnostic (i.e. the customer can do the same thing in multiple ways), and are expected to be used by > 20% of users:

* Upload a file
* Update firmware on the device
* Recognize faces in an uploaded image

Examples of bad scenarios:
* Create a client (it's part of a scenario, and we'll see it often enough in true champion scenarios)
* Send a batch of events (again, part of the scenario)
* Create a page blob (it's not used by enough of the user base)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
scheduled for 11/17.

**Comment by lilyjma** [comment]
[Recording](https://web.microsoftstream.com/video/66efa3ff-0400-b9eb-c2fb-f1eb292fd619)[MS INTERNAL ONLY]
