### ISSUE TITLE
Board Review: Proposed breaking change to DefaultAzureCredential functionality

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk#1970]
## The Problem:

When we originally shipped the `DefaultAzureCredential` the it used the following credentials to authenticate by default.

```
EnvironmentCredential -> ManagedIdentityCredential -> SharedTokenCacheCredential
```
The `SharedTokenCacheCredential` was intended to enable authenticating through Visual Studio and eventually other development tools as they contributed to the shared token cache. However while under certain circumstances the shared token cache contains enough information to authenticate the account used to authenticate in Visual studio, there are some problems with this approach. First if a user logs in with multiple accounts the shared token cache doesn't give any indication of the currently logged in account, so users need to provide additional information to authenticate with `SharedTokenCacheCredential`. 

To alleviate the issue above in Azure.Identity 1.2.0 we introduced the `VisualStudioCredential` which provides tighter integration with Visual Studio using an auth broker which Visual Studio provides. We added the `VisualStudioCredential` to the `DefaultAzureCredential` after the `SharedTokenCacheCredential`. The idea was that the `VisualStudioCredential` would handle the cases where `SharedTokenCacheCredential` did not have the information to select an account and authenticate, but we left `SharedTokenCacheCredential` in the default flow for backwards compatibility.
```
EnvironmentCredential -> ManagedIdentityCredential -> SharedTokenCacheCredential -> VisualStudioCredential -> VisualStudioCodeCredential -> AzureCliCredential
```
However, since we have shipped 1.2.0 users have brought to our attention 2 issues that the `SharedTokenCacheCredential` introduces to the `DefaultAzureCredential` flow. First, if a user signs into Visual Studio with a tenant other than their home tenant the token cache doesn't provide us any indication of that. So if the user doesn't provide us that tenant id through code or through the environment the `SharedTokenCacheCredential` will succeed but will log into the home tenant rather than the tenant they logged into via Visual Studio. This ultimately leads to some cryptic failures when the user attempts to use azure services as the issuer of the token doesn't match what the services expect and they fail with 401/403 depending on the service.

The second issue the `SharedTokenCacheCredential` introduces is related to MSA accounts. In this case older Microsoft applications use a different mechanism to authenticate MSA known as the passthrough tenant. When an application authenticates a through the passthrough tenant, as Visual Studio does, the refresh token associated with that authentication can only be used with the passthrough tenant in the future.  Client which attempt to authenticate the MSA account in the newer way, the 'common' endpoint will fail with a confusing error message. 
```
AADSTS70002: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.
```
The work around for both these issues for customers is to disable the `SharedTokenCacheCredential` with the option `ExcludeSharedTokenCacheCredential` as such.
```c#
var cred = new DefaultAzureCredential(new DefaultAzureCredentialOptions { ExcludeSharedTokenCacheCredential = true });
```
While there is a work around for these issues, they are issues which impact many developers, and the errors don't give any indications which point developers to the work around. Given that the primary intent of the `DefaultAzureCredential` is to provide a quick getting started authentication experience, these issues dramatically detract from that. 

## Proposed "Breaking" Fix:

I propose that essentially remove the `SharedTokenCacheCredential` from the default auth flow of `DefaultAzureCredential` by changing the default value of `ExcludeSharedTokenCacheCredential` to true.

## Impact of "Breaking" Behavior:
This change will essentially change the `DefaultAzureCredential` flow to the following:
```
EnvironmentCredential -> ManagedIdentityCredential -> VisualStudioCredential -> VisualStudioCodeCredential -> AzureCliCredential
```
For most developers this change will have no impact as most cases where the `SharedTokenCacheCredential` was authenticating users locally with the `DefaultAzureCredential` will simply be handled by the `VisualStudioCredential` now instead. There are a couple of edge cases which might break. For instance if a user was previously using the `AZURE_USERNAME` environment variable or `SharedTokenCacheUsername` option to select a **previously** authenticated account that is different from the account that the user is logged into Visual Studio with the `SharedTokenCacheCredential`, this will stop working. 

Users will still have a way to get back to the old behavior by explicitly setting the `ExcludeSharedTokenCacheCredential` to false.
```c#
var cred = new DefaultAzureCredential(new DefaultAzureCredentialOptions { ExcludeSharedTokenCacheCredential = false });
```

**Comment by lilyjma** [comment]
scheduled for 11/5

**Comment by JonathanGiles** [comment]
@schaabs Just to confirm: this is a C#-only issue, correct?

**Comment by lilyjma** [comment]
[Recording](https://web.microsoftstream.com/video/ea24a1ff-0400-9fb2-51e8-f1eb1fbc8b6d)[MS INTERNAL ONLY)
