### ISSUE TITLE
Board Review: Storage Blobs, Files::Shares, Files::DataLake for C++

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk#1983]
## The Basics

* Service team responsible for the client library: Storage
* Link to documentation describing the service:
* Contact email (if service team, provide PM and Dev Lead): vinjiang

## About this client library

* Name of the client library: Azure Storage SDK for C++
* Languages for this review: C++
* Link to the service REST APIs: https://github.com/Azure/azure-sdk-for-cpp/tree/master/sdk/storage

### C++

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link:
  - `Azure::Storage::Blobs`: https://apiview.dev/Assemblies/Review/73f4a17f8dff41dca9762ad38870d475#Azure::Storage::Blobs
  - `Azure::Storage::Files::Shares`: https://apiview.dev/Assemblies/Review/bad44a54910f46bf83dbe3b7a7579f36#Azure::Storage::Files::Shares
  - `Azure::Storage::Files::DataLake`: https://apiview.dev/Assemblies/Review/5aec114a35f946ba9ee31e0955b69fea#Azure::Storage::Files::DataLake
  - Optional ApiViews that are already compiled into the others:
    - `Azure::Storage`: https://apiview.dev/Assemblies/Review/4d54f7a178b2474cb5f1f3646205cd9f#Azure::Storage
    - `Azure::Core`: https://apiview.dev/Assemblies/Review/5930829ad00144218d29ebaf1377d452
* Link to samples for champion scenarios:
  - in the comments

**Comment by lilyjma** [comment]
scheduled for 11/11 3-5PM PST

**Comment by Jinming-Hu** [comment]
Link to samples for champion scenarios:
[Azure Storage C++ Client Library Sample - Upload a Blob](https://gist.github.com/Jinming-Hu/665ae7917473ae560e20db7b9b8cea0a)
[Azure Storage C++ Client Library Sample - Upload a Block Blob](https://gist.github.com/Jinming-Hu/a7efacc4cb0fb4945dff4583fad2aec5)

**Comment by tg-msft** [comment]
Can you also add samples showing enumeration of blobs in a container and parallel upload/download (if you have them and they're separate APIs)?

**Comment by Jinming-Hu** [comment]
> Can you also add samples showing enumeration of blobs in a container and parallel upload/download (if you have them and they're separate APIs)?

done!

**Comment by katmsft** [comment]
[Azure Storage C++ Client Library DataLake service Champion Scenario](https://gist.github.com/katmsft/9eba3994b8670d004c947f5a0a891beb)

[Azure Storage C++ Client Library FileShare service Champion Scenario](https://gist.github.com/katmsft/544e07b148b3d6c653e35c85daa0c9d5)

Done, thanks for the reminder.

**Comment by lilyjma** [comment]
[Recording](https://web.microsoftstream.com/video/66efa3ff-0400-b9eb-0bc4-f1eb24837727) [MS internal only]

**Comment by lilyjma** [comment]
[Recording Part 2 ](https://web.microsoftstream.com/video/0e21a1ff-0400-b9eb-97a0-f1eb2acc664b)[MS INTERNAL ONLY]

**Comment by lilyjma** [comment]
scheduled for 12/9

**Comment by tg-msft** [comment]
Is there any sample code for SetAccessControlRecursive we could look at?

**Comment by katmsft** [comment]
> Is there any sample code for SetAccessControlRecursive we could look at?

https://github.com/Azure/azure-sdk-for-cpp/blob/9d3b48852449c861e0915337ae62a44c6fc67650/sdk/storage/azure-storage-files-datalake/test/datalake_directory_client_test.cpp#L301 We don't currently have a sample code for it, but the test code can be referenced.

**Comment by lilyjma** [comment]
[MS INTERNAL ONLY][Recording](https://msit.microsoftstream.com/video/77f1a3ff-0400-b9eb-c7e2-f1eb3a7ad223)

**Comment by lilyjma** [comment]
1/6/21 Datalake Review 
[Recording](https://web.microsoftstream.com/video/e3fca3ff-0400-a605-6451-f1eb5073b0c4)[MS INTERNAL ONLY]
