### ISSUE TITLE
Board Review: Microsoft Azure Attestation

### ISSUE THREAD

**Issue by LarryOsterman** [Azure/azure-sdk#1985]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Larry Osterman (larryo)
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/attestation/overview#:~:text=%20Azure%20Attestation%20is%20critical%20to%20Confidential%20Computing,parties%20to%20interact%20with%20the%20enclave.%20More%20
* Contact email (if service team, provide PM and Dev Lead): sidittak; anilba - please don't contact anil, he's the dev lead but isn't involved in the API review process except as an informative.

## About this client library

* Name of the client library: Azure.Security.Attestation
* Languages for this review:C#
* Link to the service REST APIs:https://github.com/Azure/azure-rest-api-specs/tree/master/specification/attestation/data-plane

Note: We believe that providing a "quality" SDK for our API surface requires that the runtime for the language support the following capabilities:
- X.509 Certificates as a type, and export those types using Base64.
- RSA Private and Public Keys
- The ability to digitally sign UTF-8 text using RSA private keys.
- Optionally: The ability to verify RSA signatures.
- Optionally: The ability to invoke functions written in C (if we can invoke C functions, we can dramatically reduce the cognitive load for customers using our APIs, since some of the required cryptographic functionality is only available in the form of C libraries).
- It would be nice to have common support for Base64 and Base64Url encoding/decoding, and bidirectional native "string" to UTF8 conversions.
We can create an SDK which does not require these capabilities, but the customer experience will of a lower quality.

A simple example of the kind of scenario we'd like to be able to support which requires crypto support:
The "SetPolicy" REST API takes a JSON Web Token which is a signed document which includes a Base64 encoded X.509 certificate. With crypto support above, we can provide an API which takes a string, a key and a certificate (or a certificate if it includes the private key) and encodes that string appropriately for the service. Without it, we have to push that problem to the customer

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link:https://apiview.dev/Assemblies/Review/dc7f0539105a4910999fa3ab8d7255e2
* Link to samples for champion scenarios:https://github.com/LarryOsterman/azure-sdk-for-net/blob/LarryO-CreateGAApiSDK/sdk/attestation/Azure.Security.Attestation/tests/Samples/AttestationServiceAttestationSamples.cs

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link:
* Link to samples for champion scenarios:

### Python

* Upload the api as a Draft PR.  Link to PR:
* Link to samples for champion scenarios:

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR:
* Link to samples for champion scenarios:

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Describe the champion scenario: Developer wishing to perform a Secure Key Release with the Managed HSM service.
    * Estimate the percentage of developers using the service who would use the champion scenario: 100%. Percentage of developers using any of the Pri 0 SDK languages who would use the champion scenario: Possibly as high as 2%. The champion scenario requires the ability for customers to validate OpenEnclave Reports, and that is only available as a C API.
    * Link to the code sample: https://github.com/LarryOsterman/azure-sdk-for-net/blob/a297bbea48a81797aaef32e8965953659a3aa86a/sdk/attestation/Azure.Security.Attestation/tests/Samples/AttestationServiceAttestationSamples.cs#L119

* Champion Scenario 2:
    * Describe the champion scenario: Tenant administrator wishes to set the attestation policy on the attestation service
    * Estimate the percentage of developers using the service who would use the champion scenario: 1%. Note that again, this champion scenario requires the ability to invoke C APIs.
    * Link to the code sample: https://github.com/LarryOsterman/azure-sdk-for-net/blob/a297bbea48a81797aaef32e8965953659a3aa86a/sdk/attestation/Azure.Security.Attestation/tests/Samples/AttestationServiceAttestationSamples.cs#L139

Examples of good scenarios are technology agnostic (i.e. the customer can do the same thing in multiple ways), and are expected to be used by > 20% of users:

* Upload a file
* Update firmware on the device
* Recognize faces in an uploaded image

Examples of bad scenarios:
* Create a client (it's part of a scenario, and we'll see it often enough in true champion scenarios)
* Send a batch of events (again, part of the scenario)
* Create a page blob (it's not used by enough of the user base)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
scheduled for 11/10 2-4pm PST.

**Comment by lilyjma** [comment]
[Recording](https://login.microsoftonline.com/common/oauth2/authorize?client_id=cf53fce8-def6-4aeb-8d30-b158e7b1cf83&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dAQAAAAIAAAAJLnJlZGlyZWN0Smh0dHBzOi8vd2ViLm1pY3Jvc29mdHN0cmVhbS5jb20vdmlkZW8vOTgzOGE0ZmYtMDQwMC1iOWViLTRjNjItZjFlYjIzYjE3NWEyCG5vbmNlS2V5mwE0bGZsT0ItVEZvUGcyTHRESnNQMy15WG5LUEFHN1JUYWtyTWhHWnhTb1AzTVY4QVVTM2NhbDJ1M2wxMzR3RDFGV0RSUEhDbkl6c3dkQmVzRGNKSEFwc1pzblZidjlacERvRXRBdXp6UEpoTnNCWTdYVF9fVlRzM2Q5LUlVYS03UjNCdmxQNFR4cGtTZjBHWktBSHpQeGFsenBETQ&nonce=637407144894361708.ODliOGMxYzgtODUzYS00MjQwLWFjYzAtMTljODcxODRkMWE2YmUyYWE1ZGEtNDdiOS00ODU5LTkzZmMtNDMzYTAwNDllMzJk&nonceKey=OpenIdConnect.nonce.WCGiXJurZvMhah7OoQnGEusMVDigYF9rz0J916wC5Bw%3d&site_id=500453&redirect_uri=https%3a%2f%2fweb.microsoftstream.com%2f&post_logout_redirect_uri=https%3a%2f%2fproducts.office.com%2fmicrosoft-stream&msafed=0&prompt=none)[MS Internal Only]
