### ISSUE TITLE
[Feature Req] Have a script to extend the excludePackages

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk#1987]
We use excludePackages config in package.json to exclude the unwanted packages.
Two things to consider to make it work better:
1. The config is currently manually updated. People who forget to exclude *implementation packages will leak the internal path to public, which is redundant and waste of resources.
1. We do not support any regex like package name, so some of the packages, like spring, has to exclude a long list of the package name. We'd better to have a script to update reference doc with regex like package name.

**Comment by kurtzeborn** [comment]
Why do we think we should be fixing this downstream in the web-site vs. upstream in JavaDocs.

**Comment by sima-zhu** [comment]
Scott said doc team has some work on this, but we don't want to highly depends on them.

We are exporting all packages namespace inside of packages. This is also handled by docs team. I don't think JavaDocs is able to do anything for hiding the *implementation packages.

Let me know if it doesn't answer your questions.

**Comment by sima-zhu** [comment]
This is done. Also, we can filter out the implementation packages already
