### ISSUE TITLE
Single Post-release script to union changelog entries, update final data/links in Release DevOps

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk#1997]

**Comment by kurtzeborn** [comment]
After our discussion today with the release drivers, this is likely going to be a script that runs in a regularly scheduled pipeline which accumulates entries from the "highlights" section of the changelog and puts them into the release notes.  Then, once all of the packages have released for a give language, the PR can be merged and those become the final release notes for the month.

Then then script would watch for released that occur after the most recent merge to release notes and accumulate a new release notes PR for the next one.
