### ISSUE TITLE
Improvements/simplification to DevOps UI

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk#1998]

**Comment by weshaggard** [comment]
@AlexGhiondea I'm missing some context on this issue. What is this particularly referring to?

**Comment by kurtzeborn** [comment]
Alex created this automatically from the MQ spreadsheet.  This is about following up on the feedback from the release drivers.

**Comment by weshaggard** [comment]
This has already been split up into individual work items so closing this.
