### ISSUE TITLE
Release pipeline improvements (trigger smoke tests after release)

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk#1999]
The goal with this issue is to replicate what most language teams have in their release checklists already.  Specifically, each of these checklists has an item to download the packages they release and validate manually that the packages are valid and that basic scenarios are functioning properly.

The idea here is to leverage the smoke tests to automate this if possible.

Ideally, the way this would work is that one of the last things the release pipeline would do is kick off the smoke test pipeline for that language (in fire-and-forget manner) in such a manner that the smoke tests run against the new packages released.

**Comment by weshaggard** [comment]
@benbp is this done across languages now?

**Comment by benbp** [comment]
@weshaggard I have a branch for java I need to revisit. I can do that this week.
