### ISSUE TITLE
Add max-width to Display Name column on releases page

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#2036]
Let's add max-width here so this column wraps - it currently doesn't wrap which causes horizontal scroll.
![image](https://user-images.githubusercontent.com/2163001/99414975-34c8e880-28ac-11eb-9b57-4b7a6ae9c044.png)

**Comment by vhvb1989** [comment]
@jongio max-width won't make the wrapping. It would just make the text overflow the container and won't be displayed. It would also block the responsiveness of the page on bigger screens.
Using `word-break: break-all;` on the table style should be enough. I will create a PR
