### ISSUE TITLE
Board Review: Microsoft.Azure.WebJobs.Extensions.Storage .NET GA

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk#2038]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Initial discussion: https://github.com/Azure/azure-sdk/issues/1563
* Service team responsible for the client library: storage
* Link to documentation describing the service:  Links available on https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage/README.md
* Contact email (if service team, provide PM and Dev Lead): kasobol@

## About this client library

* Name of the client library:
Microsoft.Azure.WebJobs.Extensions.Storage - metapackage of
Microsoft.Azure.WebJobs.Extensions.Storage.Blobs
Microsoft.Azure.WebJobs.Extensions.Storage.Queues
* Languages for this review: .NET
* Link to the service REST APIs: N/A - based on Storage SDK V12

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link:
[Microsoft.Azure.WebJobs.Extensions.Storage.Blobs](https://apiview.dev/Assemblies/Review/0f2b12af2a1d4562929f8ee3358c304e)
[Microsoft.Azure.WebJobs.Extensions.Storage.Queues](https://apiview.dev/Assemblies/Review/5614fe16ddf7420a8a92c7ac07bc2555)
* Link to samples for champion scenarios:
[Microsoft.Azure.WebJobs.Extensions.Storage.Blobs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs/README.md#examples)
[Microsoft.Azure.WebJobs.Extensions.Storage.Queues](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/README.md#examples)

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

[Microsoft.Azure.WebJobs.Extensions.Storage.Blobs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs/README.md#examples)
[Microsoft.Azure.WebJobs.Extensions.Storage.Queues](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/README.md#examples)
[EventGrid integration](https://github.com/Azure/azure-sdk-for-net/blob/729e4ed9b7f5211997964021b10aa62526eacbe5/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Scenario.Tests/tests/EventGridBlobTriggerEndToEndTests.cs#L177-L197)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by lilyjma** [comment]
scheduled for 1/21

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/6338a1ff-0400-9887-643e-f1eb5c41220a)[MS INTERNAL ONLY]
