### ISSUE TITLE
Package list auto-gen request: fix links without text

### ISSUE THREAD

**Issue by kraigb** [Azure/azure-sdk#2045]
Recent builds are giving these warnings in azure-dev-docs-rpr. Looks like there's just some missing text in the source spreadsheet.

articles/includes/python-all.md
Line 32, Column 1: [Suggestion-link-text-missing] Missing link text for link 'https://pypi.org/project/azure-digitaltwins-core/'. Add appropriate text. NOTE: This Suggestion will become a Warning on 1/29/21.
Line 119, Column 1: [Suggestion-link-text-missing] Missing link text for link 'https://pypi.org/project/azure-mgmt-containerregistry/'. Add appropriate text. NOTE: This Suggestion will become a Warning on 1/29/21.
Line 119, Column 1: [Suggestion-link-text-missing] Missing link text for link 'https://github.com/Azure/azure-sdk-for-python/tree/azure-mgmt-containerregistry_2.8.0/azure-mgmt-containerregistry/'. Add appropriate text. NOTE: This Suggestion will become a Warning on 1/29/21.

articles/includes/python-new.md
Line 32, Column 1: [Suggestion-link-text-missing] Missing link text for link 'https://pypi.org/project/azure-digitaltwins-core/'. Add appropriate text. NOTE: This Suggestion will become a Warning on 1/29/21.
Line 119, Column 1: [Suggestion-link-text-missing] Missing link text for link 'https://pypi.org/project/azure-mgmt-containerregistry/'. Add appropriate text. NOTE: This Suggestion will become a Warning on 1/29/21.
Line 119, Column 1: [Suggestion-link-text-missing] Missing link text for link 'https://github.com/Azure/azure-sdk-for-python/tree/azure-mgmt-containerregistry_2.8.0/azure-mgmt-containerregistry/'. Add appropriate text. NOTE: This Suggestion will become a Warning on 1/29/21.

**Comment by weshaggard** [comment]
Fixed with #2060
