### ISSUE TITLE
[live tests] test-resources.* file location and test parenting should be more flexible 

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk#2050]
Currently the `test-resources.json`, `test-resources-pre.ps1` and `test-resources-post.ps1` files are mapped 1:1 with all tests located within a service directory, and must be located within `sdk/<service>/test-resources.*`. This 1:1 mapping makes it harder to split up resource generation on a more granular basis, such as when there are multiple services per sdk (as is the case with [storage, e.g. blob, batch, datalake, etc.](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage)).

We should perhaps support something like parameterized test-resources file locations or some sort of directory walking (look for files in `sdk/<service>/<sub-service>/*` first. Basically a way to better map resource provisioning to tests per-sdk, when they all exist within one pipeline definition.

**Comment by heaths** [comment]
Supporting nested file paths - much like git and other common file patterns - would be pretty easy to support. Start deep and work up, just like .gitignore files.

**Comment by heaths** [comment]
Another idea that was discussed was first deploy the general service template then, depending on its outputs, you could also go deeper. IMO, if there's no great reason to, not only would this take more time than a combined ARM template set, but would be more confusion for devs to use or probably us to support.

**Comment by benbp** [comment]
Related: https://github.com/Azure/azure-sdk-for-java/pull/18773

**Comment by benbp** [comment]
@heaths I like the nested path, working up model. `ServiceDirectory` can already contain multiple directories (e.g. `identity/some-sub-service`) based on my reading of the code, but adding logic to search up to the base URI segment of the value could eliminate the need for manually specifying the service directory across all repos where there *may* be nested templates or not.

**Comment by heaths** [comment]
Yeah - the subdir resolution was intentional because, at one point in my design, the idea was to support sub-services (but not merging - which I like the idea of we're discussing here).
