### ISSUE TITLE
Enable the public version of CredScan in our Aggregate Reports pipeline

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#2056]
Follow up on details described in this incident: https://portal.microsofticm.com/imp/v3/incidents/details/214723367/home

**Comment by kurtzeborn** [comment]
@weshaggard already has a pipeline he runs manually in this way.  What's needed with this issue: 
1. Schedule the pipeline regularly
   1. Or (better) integrate it into the aggregate reports pipeline that already exists and runs regularly
2. Have it generate delta reports of new secrets that it finds
3. Alert the appropriate language repo owners for follow up
   1. This could be done with an email or by opening issues automatically

**Comment by sima-zhu** [comment]
Looking

**Comment by sima-zhu** [comment]
https://dev.azure.com/azure-sdk/internal/_build?definitionId=1949

Here is the manual run pipeline

**Comment by sima-zhu** [comment]
Will work on adding CredScan step at aggregate-report first.

**Comment by sima-zhu** [comment]
Python, JS, .net have PR ready to merge. 

Java is blocking by Guardian team fix deployment. Will start working on the PR once the deployment succeed.

Java:https://github.com/Azure/azure-sdk-for-java/pull/18505
Python:https://github.com/Azure/azure-sdk-for-python/pull/16136
.NET: https://github.com/Azure/azure-sdk-for-net/pull/17944
JS: https://github.com/Azure/azure-sdk-for-js/pull/13200
