### ISSUE TITLE
Re-enable sovereign cloud environments for azure-sdk-for-net weekly tests

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk#2074]
Tracking issue to re-enable these environments once the tests are stable. See https://github.com/Azure/azure-sdk-for-net/pull/17236

**Comment by weshaggard** [comment]
Given that I expect this to be work for individual service teams we should probably add an opt-in so we can start turning it on incrementally one at a time.

**Comment by benbp** [comment]
This is something we're currently doing on a service by service basis as support is added, and it's tracked by other issues, so I'm going to close this one.
