### ISSUE TITLE
.NET Guidelines: Updates to out of date guidelines

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#2086]
## Description

For the MQ Guidelines effort, update links and guidelines to make them current.

## Details

This includes:
- [x] Link to Framework Design Guidelines on Safari Books Online where called out in TODOs in introduction.md. 

  _This link is aka.ms/fdg3, but may additionally need a sentence description of how to log in the first time (all MS employees have access)._

  - In [Design Principles/Idiomatic](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-principles)
  - In [Service Method Parameters](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-parameters)
  - Under [struct criteria guideline](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-service-models-prefer-structs)

- [x] Link to guidance on contacting arch board where called out in TODOs
  - In [Support for non-HTTP Protocols](https://azure.github.io/azure-sdk/dotnet_introduction.html#support-for-non-http-protocols)

- [x] Update list of namespaces; there is a TODO for this in the [Namespaces](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-namespace-naming) section.
- [ ] Update samples guidance; there is a TODO for this in the [Samples](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-samples) section.
- [x] In [Using HttpPipeline](https://azure.github.io/azure-sdk/dotnet_implementation.html#using-httppipelinepolicy) in implementation.md, do we want to keep the code sample, even though our recommendation is now to use code generation rather than writing these methods by hand?

**Comment by annelo-msft** [comment]
@sameralameer FYI

**Comment by KrzysztofCwalina** [comment]
> In Using HttpPipeline in implementation.md, do we want to keep the code sample, even though our recommendation is now to use code generation rather than writing these methods by hand?

I will keep it and simply add a note that some of this code can be generated.

**Comment by KrzysztofCwalina** [comment]
For samples I filed a separate issue #2141. This is a large workitem.
