### ISSUE TITLE
Post-MQ Guidelines Updates

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#2118]
## Phase 2 Updates

The following is a list of proposals for future phases of guidelines updates, following the [MQ Updates](https://github.com/Azure/azure-sdk/issues?q=is%3Aissue+label%3A%22ArchBoard+Guidelines%22+label%3AMQ).  These remain to be triaged and prioritized.

- Add new guidance that has been decided in arch board but not yet documented in the guidelines
- Clearly differentiate which guidelines apply to both HTTP and non-HTTP based services
- Fully reconcile with the general guidelines
- Link out to further information such as concepts, repo docs, or implementation source in a consistent way
- Full consistency of structure such that readers can see clearly how the same problems are solved by the different languages
- A full discussion of Azure Core and how its types are used in public API design and implementation
- Guidelines for implementation that match each of the API design sections, where relevant
- Writing style: add short framing introduction and section transitions
- Understanding of who is the Guidelines reader and what are their needs that goes beyond "a person designing Azure SDK APIs for a given language"
- More in-depth discussion of guidelines, possibly separated inline from the guidelines with a UI affordance
- Jekyll issues such as 1) search - scoped to a given language guidelines, 2) showing the guideline when you follow the href to it directly.
- Address desire to use browser search on a single page
- Address [this comment](https://github.com/Azure/azure-sdk/pull/2103/files#r537761487) consistently -- reference HTTP rather than REST.
- Consistency of principles across language guidelines

**Comment by annelo-msft** [comment]
FYI @salameer @JonathanGiles @bterlson @johanste @KrzysztofCwalina @JeffreyRichter @bsiegel @tg-msft @schaabs 

Feel free to add suggestions in the comments of this issue.

**Comment by vhvb1989** [comment]
> Full consistency of structure such that readers can see clearly how the same problems are solved by the different languages

@JeffreyRichter  this is actually related to what I was telling you the other day. 
Not only end-users but also new Azure SDK team members (devs) and contributors would benefit of having an easy way to compare across languages how some specific problems have been solved/implemented.
Sometime is only about describing a pattern and linking to the github source that implement it
Sometime is actually about comparing the language implementation detail.

I would be happy to help on this point whenever it comes to the sprint plan

**Comment by annelo-msft** [comment]
@RickWinter  FYI

**Comment by annelo-msft** [comment]
Shared observation: 

> "I note the .NET design principles at the top of the design doc are shortened compared to what was drafted a very long time ago. We should probably work to standardise our principles text again"

Let's look at this as part of the general guidelines reconcile.  I think it makes sense to be consistent, but also to tailor the discussion of what the principles mean to a given language.  We can consider leveraging some of the work we did to interpret the principles for the Tier 1 languages in the partner trainings, while still targeting the goal to keep the intro nice and short.

**Comment by annelo-msft** [comment]
@KrzysztofCwalina suggested filling gaps that aren't covered by the .NET FDG in a later phase as well.

**Comment by ahsonkhan** [comment]
From https://github.com/Azure/azure-sdk/issues/2194#issuecomment-754855304 and https://github.com/Azure/azure-sdk/pull/2180#issuecomment-748388329

For topics that are common across all languages but have nuanced differences, I suggest we use a general title that can be applied for consistency across all the languages and ToC (for easier navigation and search), rathe than than removing the section or having custom names per languages. For example:
- `Exceptions` -> `Error handling and exceptions` - By making it incorporate other language aspects like C, which doesn't have exceptions, this section becomes more generic but also more detailed
- `Service Client  Constructors` -> `Service Client  Creation`  - Java doesn't have ctors and uses a builder/factory pattern. Changing to `Creation` or `Construction` across all languages has limited impact on .NET, and the body of the section can state the nuanced approach being taken for that particular language.

We can use our judgement for when not to apply the above recommendation, but I think many of the section titles can be updated without much loss to the "idiomatic nature of each language".

**Comment by annelo-msft** [comment]
Great, thanks for the suggestion, @ahsonkhan !  We can look at prioritizing this against other suggestions on the post MQ list once the MQ updates are complete.
