### ISSUE TITLE
Should requirement checkbox rendering inconsistent across platforms

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-sdk#212]
In #177 @ramya-rao-a asks what's up with the grey checkbox. Looking at [emojipedia](https://emojipedia.org/ballot-box-with-check/) looks like it's the "should" checkbox that is blue for us on Windows.

I think we should strive to have similar look and feel across the different platforms so e.g. nobody says "blue checkbox" and causes confusion.

@KrzysztofCwalina I think you originated the current styles. Have you a preference for how to fix this or not? I can make us custom SVG icons if we like!

**Comment by KrzysztofCwalina** [comment]
Yeah, if possible we should choose icons that render the same in all readers/contexts.

**Comment by adrianhall** [comment]
Suggestion: Use different icons, colors and words:

✔️ YOU MUST
⛔️ YOU MUST NOT
🆗 YOU SHOULD
☢️ YOU SHOULD NOT
🔆 CONSIDER
⚠️ AVOID

**Comment by KrzysztofCwalina** [comment]
I think .net guidelines should use the regular .net wording (DO, DO NOT, AVOID, CONSIDER). I care much less about the icons.

**Comment by adrianhall** [comment]
.NET has two levels (MUST / SHOULD) - our guidelines right now have three (MUST / SHOULD / MAY).

To my mind, AVOID / CONSIDER is in line with our semantic meaning for MAY.  DO / DO NOT is in line with MUST.

What would the wording be for SHOULD?

**Comment by adrianhall** [comment]
We've done a change to include ARIA tags (thanks @thedanfernandez) - so the applicability of this issue is resolved, I believe.  Please re-open if you dis-agree.
