### ISSUE TITLE
Board Review: LVA C#/Python review

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#2131]
## The Basics

* Service team responsible for the client library: LVA Media
* Link to documentation describing the service: https://azure.microsoft.com/en-us/services/media-services/live-video-analytics/
* Contact email (if service team, provide PM and Dev Lead): Girish Akasapu <giakas@microsoft.com>

## About this client library

* Name of the client library: Azure.Media.LiveVideoAnalytics.Edge
* Languages for this review: C#/Python
* Link to the service REST APIs:

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/dd437143e5e64d1f81b7121703bff224
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-net/pull/17289

### Python

* Upload the api as a Draft PR.  Link to PR: https://apiview.dev/Assemblies/Review/2da269f7a5d449d98e9298adab5392a9
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-python/pull/15375

## Champion Scenarios

Some context from @JeffreyRichter 

> I think their best architectural choice is to define some JSON payloads in some language (like Swagger) and then they want model types generated.
> Customers can then create the model type in their language of choice, initialize it, and then pass it (or perhaps the JSON-serialized version of it to a function that already exists the IOT client libraries to send the JSON payload to iot hub.
>  
> Their SDK doesn’t perform any I/O operations at all. They just want to simply the creation/parsing of JSON payloads that get passed to/from iot hub using already-existing functionality.
>  
> One of the reason [...] suggesting this approach is because of dependency conflicts. If a customer wants to use Version x.y of the IoT Devices library, and if we have a dependency on a.b version of devices library, that will cause issues to the customer, so he is suggesting we don't have any dependency on Devices library and let customer use IoT SDK to make direct method calls, and we support helper methods to construct the body for direct method.

# C# 

```csharp
private async Task<CloudToDeviceMethodResult> invokeDirectMethodHelper(OperationBase bc) 
{
    var directMethod = new CloudToDeviceMethod(bc.MethodName);
    directMethod.SetPayloadJson(bc.GetPayloadAsJSON());
    return await _serviceClient.InvokeDeviceMethodAsync(_deviceId, _moduleId, directMethod);
}
 
// create a graph
var graphTopology = Build();
var result = await invokeDirectMethodHelper(new MediaGraphTopologySetRequest(graphTopology));
 
// get all graphs
var getAllResult = await invokeDirectMethodHelper(new MediaGraphTopologyListRequest());
var getAllGraphs = MediaGraphTopologyCollection.Deserialize(getAllResult.GetPayloadAsJson());
 
 // get a graph
var getResult = await invokeDirectMethodHelper(new MediaGraphTopologyGetRequest(graphTopology.Name));
var resultGraph = MediaGraphTopology.Deserialize(getResult.GetPayloadAsJson());
```

https://github.com/Azure/azure-sdk-for-net/blob/4a93ae0df9e862346dfcae4a9a3115cb6d2162a7/sdk/mediaservices/Azure.Media.LiveVideoAnalytics.Edge/samples/LiveVideoAnalyticsSample.cs

# Python

https://github.com/Azure/azure-sdk-for-python/blob/2cd1cd7d41b4c02b9708fc6e216b3cc38bf6d9b5/sdk/media/azure-media-livevideoanalytics-edge/samples/sample_lva.py

**Comment by lilyjma** [comment]
scheduled for 12/8

**Comment by tg-msft** [comment]
There's not enough time to really review the API, but we should talk about:
- The namespace and future plans in this space
- Where/how customers typically construct these graphs?
- The sample code makes me think there's a corresponding lightweight client somewhere?
- Whether this should make use of BinaryData instead of string?
- If all the polymorphism is necessary?
- If the base classes are usable or should be abstract?

**Comment by lmazuel** [comment]
Current recommendation for Python:
- Distribution package: azure-media-videoanalytics-edge
- Namespace: azure.media.videoanalyticsedge

**Comment by lilyjma** [comment]
[Recording](https://web.microsoftstream.com/video/51f7a3ff-0400-b9eb-80d7-f1eb39b43fca)[MS INTERNAL ONLY]
