### ISSUE TITLE
Package in java-package.csv is not displayed in azure.github.io

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk#2147]
I found that some Spring related packages declared in java-package.csv with ServiceName as `Spring Boot` or `Spring Cloud` are not displayed in https://azure.github.io/azure-sdk-for-java/springcloud.html or https://azure.github.io/azure-sdk-for-java/springboot.html.
For example, there is `azure-servicebus-jms-spring-boot-starter` in [java-package.csv](https://github.com/Azure/azure-sdk/blob/0b5c0ac6d26a09fd4a347e55607679c1d855f62e/_data/releases/latest/java-packages.csv#L356), but nothing is on https://azure.github.io/azure-sdk-for-java/springboot.html.
And another example is that some packages on Spring Cloud page only shows GA version regradless of preview version, e.g., `spring-cloud-azure-eventhubs-stream-binder` in https://azure.github.io/azure-sdk-for-java/springcloud.html only has **1.2.8** while in [java-package.csv](https://github.com/Azure/azure-sdk/blob/0b5c0ac6d26a09fd4a347e55607679c1d855f62e/_data/releases/latest/java-packages.csv#L397) it has both **1.2.8** and **2.0.0-beta.1**.

Could someone help to solve the problem of missing Spring packages on https://azure.github.io/azure-sdk-for-java/ ?
Thanks

**Comment by weshaggard** [comment]
@sima-zhu can you please investigate.

**Comment by sima-zhu** [comment]
Looking

**Comment by sima-zhu** [comment]
@yiliuTo In our release pipeline, if there is no index.html under documentation package, we will not upload to blob storage. 
This is the necessary step for Github IO to fetch the versioned doc. 

The behavior is expected. If we want to support more, we need to clarify on how to build your documentation package.

blob storage [link](https://ms.portal.azure.com/#blade/Microsoft_Azure_Storage/ContainerMenuBlade/overview/storageAccountId/%2Fsubscriptions%2Fa18897a6-7e44-457d-9260-f2854c0aca42%2FresourceGroups%2Fazure-sdk-artifacts%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fazuresdkdocs/path/%24web/etag/%220x8D75824EBE716A9%22/defaultEncryptionScope/%24account-encryption-key/denyEncryptionScopeOverride//defaultId//publicAccessVal/Container)

**Comment by sima-zhu** [comment]
I can see the spring-cloud-azure-eventhubs-stream-binder of version 1.2.8 has the index.html. But I am not able to verify if the 2.0.0-beta.1 has the index.html in doc package. @yiliuTo Are you able to generate the javadoc and verify?

**Comment by yiliuTo** [comment]
@sima-zhu , thanks for the information, we will check it.

**Comment by yiliuTo** [comment]
Hi @sima-zhu , Your explanation helps me resolves most of the missing packages! Now there are only two packages still having trouble displaying: [azure-spring-integration-eventhubs](https://github.com/Azure/azure-sdk/blob/master/_data/releases/latest/java-packages.csv#L435) and [azure-spring-integration-servicebus](https://github.com/Azure/azure-sdk/blob/master/_data/releases/latest/java-packages.csv#L437), they both have `index.html` in the javadoc, see of their maven links: [servicebus](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-integration-servicebus/2.0.0-beta.1) and [eventhubs](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-integration-eventhubs/2.0.0-beta.1).

**Comment by sima-zhu** [comment]
I am not sure how the eventbus and servicebus got updated. I checked the release pipeline. The one below seems related, but we don't publish these two packages successfully. 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=624077&view=results

We can only update the github io doc through our pipeline.

**Comment by yiliuTo** [comment]
@sima-zhu I see, thanks. I will wait for the next release to check it.
