### ISSUE TITLE
[TS] Document how to on-board with preview packages

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-sdk#215]
And requirements around same (e.g. version selector?). Docs currently link to the on-boarding form but could say more about what the requirements are for preview package on-boarding.

See also: 56bc304f7f8722bd90d35bb2529e5a815474308f.

/cc @mmacy

**Comment by adrianhall** [comment]
I'm thinking this is going to be covered by a combination of the preview release guidelines and the release guidelines (both of which are owned by @maggiepint )

**Comment by maggiepint** [comment]
https://github.com/Azure/azure-sdk/blob/master/docs/engineering-system/releases.md
