### ISSUE TITLE
As a contributor looking to update the guidelines, there should be public and easy to follow steps in the contributing guide on how to make and view changes

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk#2165]
There should be simple steps that showcase the workflow of how to make and self-review changes to the SDK language guidelines, especially around how the guidelines will render as a result of the PR.

The guide [here](https://github.com/Azure/azure-sdk#contributing) primarily points to an internal wiki which doesn't help answer some of the questions like:
- How can I see the final rendering of the guidelines when making changes **locally**, to have a tight inner dev loop?
  - Just looking at the raw markdown file, I see metadata tags like `{% include requirement/MUST id...`, so I want to make sure I don't have typos or mistakes with those by reviewing the expected outcome side-by-side, maybe in VS Code.
  - **Starting point for an answer (courtesy of Anne):**
    - azure-sdk holds a Jekyll site at the top level.  If you'd like you can run a local instance - I found the instructions here helpful: https://jekyllrb.com/docs/
    - You can also fork the azure-sdk repo and push to a `gh-pages` branch in your fork, and GitHub will render it for you.
- Similarly, what CI pipelines do I need to run on a guidelines change PR, to see what the generated artifacts will look like?
  - **Starting point for an answer (courtesy of Anne):**
    - `azure-sdk - ci` is what runs on the PR guidelines changes: https://github.com/Azure/azure-sdk/pull/2095/checks
    - This takes ~30 minutes because of all the link checking it does - this can be improved in the future
- After my PR/change is merged, how long after will I see the guidelines changes "go-live"?
  - **Starting point for an answer (courtesy of Anne):**
    - The underlying mechanism is GitHub pages. It should take less than 30 minutes depending on the size of the site.

The suggested improvements and answers to questions should be added to the existing doc here: https://github.com/Azure/azure-sdk/blob/master/CONTRIBUTING.md#azure-sdk-contribution-guide

cc @annelo-msft, @weshaggard, @RickWinter

**Comment by annelo-msft** [comment]
@salameer FYI, and if you have further site guidance

**Comment by ahsonkhan** [comment]
There is some good information here, so the suggested improvements and answers to questions should be added here: https://github.com/Azure/azure-sdk/blob/master/CONTRIBUTING.md#azure-sdk-contribution-guide

**Comment by kurtzeborn** [comment]
So @weshaggard has changed/improved this process quite a bit since December when this was opened, so I'm closing this.  Answers to the specific points brought up in this issue...

- The answer to the first question is covered in the "Full Local Setup" section of CONTRIBUTING.md for the repo.  
- The second question (view the results from a PR) is not supported right now.  However, the 30 minutes problem you mention has been addressed.  It's much faster now.
- The answer to your third question is within 2-3 minutes you'll see your changes go live after merging.

If you have further questions, go ahead and reactivate or open a new issue.
