### ISSUE TITLE
Board Review: Introducing Purview's Scanning Service

### ISSUE THREAD

**Issue by parvsaxena** [Azure/azure-sdk#2166]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library:
* Main contacts:
Parv Saxena: parv.saxena@microsoft.com
Justin Dellamore: Justin.Dellamore@microsoft.com
(EM) Ivy Liu: Ivy.Liu@microsoft.com
(PM) Naga Krishna Yenamandra: naga.yenamandra@microsoft.com
* Expected GA date for this library:

## About the Service 

* Link to documentation introducing/describing the service:https://docs.microsoft.com/en-us/azure/purview/
* Link to the service REST APIs: https://github.com/parvsaxena/azure-rest-api-specs-pr/tree/pasaxena/purview-scanning-service/specification/purview/data-plane/Microsoft.Purview/preview/2018-12-01-preview
* Is the goal to release a Public Preview, Private Preview, or GA? Public Preview (The service went into Public Preview on Dec 3rd, 2020)

## About the client library

* Name of client library: Purview's Scanning Service
* Link to library reference documentation:https://docs.microsoft.com/en-us/azure/purview/
* Is there an existing SDK library? If yes, provide link: 

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
4. How does the **authentication** workflow look? 
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

Champion Scenarios for service here: https://github.com/parvsaxena/azure-rest-api-specs-pr/tree/pasaxena/champion-scenarios/specification/purview/data-plane/Microsoft.Purview/samples

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 

* Create a new resource
* Read the resource
* Modify the resource
* Delete the resource
* Error handling 
* Handling race conditions/concurrency issues

**Comment by lilyjma** [comment]
scheduled 1/7

**Comment by lilyjma** [comment]
[Recording](https://web.microsoftstream.com/video/3627a4ff-0400-a605-3431-f1eb5140807f)[MS INTERNAL ONLY]
