### ISSUE TITLE
Support Custom Release Phases

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#2171]
We currently store all the supported release phases in the [archetype-<language>-release file.](https://github.com/Azure/azure-sdk-for-js/blob/master/eng/pipelines/templates/stages/archetype-js-release.yml)

However, what if a given dev needs custom tasks _for their service specifically?_

To support this, we should support insertion of release phases as a parameter to the release yaml. It's the same concept as what we do with [BeforeTestPhases](https://github.com/Azure/azure-sdk-for-python/blob/master/eng/pipelines/templates/jobs/archetype-sdk-client.yml#L169) in python.

Add parameter "AdditionalReleasePhase" which supports a array of tasks that will be invoked. Each within it's own release phase.

Ideally, we support _multiple_ additional definitions, but I'm not certain how we'll actually do that in the build yml.

**Comment by mitchdenny** [comment]
YAML now supports typed parameters, so we could look at supporting a ```jobList``` or ```stepList```:

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#types

I think we've got a few different approaches we could take here. I'm tempted to add a whole new stage AFTER the Release stage in which to insert these jobs so that they are totally isolated from our core release process. But other options include injecting a job INTO the release stage (after our jobs) or appending steps within existing jobs.

**Comment by kurtzeborn** [comment]
This seems like it dovetails nicely with the matrix generation work @benbp is already doing actually.

@benbp, when you're ready to work on this, @weshaggard, @mitchdenny, and I should meet with you to talk about strategy here.

**Comment by benbp** [comment]
One way this is done, in .net, is by having pre and post steps as a template parameter (example [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/tests.yml#L20-L39), [underlying](https://github.com/Azure/azure-sdk-for-net/blob/master/eng/pipelines/templates/stages/archetype-sdk-tests.yml#L125-L130). They aren't specifically declared via the stepList type, but probably should (I think there's a reason it doesn't work in this case).

One addition I set up, as you'll see on the condition declarations, is you can have different extra steps/phases that only apply for certain platforms. I don't know if you'll want this scenario too, but thinking of a user-friendly way to link it with the matrix generation will be good to do.

I think partly what you're talking about (correct me if I'm wrong), is actual release stages being inserted as well (not just extra job steps). We should be able to pass in stage definitions via parameters, but there are probably some pre-requisites to get the python release definition in the format I've been modeling in .net. I think making python the second repo we standardize is a good idea for this and other reasons. 

There are some annoyances with passing in stages and jobs down as parameters, mainly that template compilation errors from the API get obfuscated and it's really hard to debug, FYI.
