### ISSUE TITLE
Board Review: Introducing azure-ml

### ISSUE THREAD

**Issue by luigiw** [Azure/azure-sdk#2172]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Azure Machine Learning Dev Platform team
* Main contacts: @hancwang @paulsh (MS alias)
* Expected GA date for this library: N/A

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/machine-learning/
* Link to the service REST APIs: https://master.api.azureml-test.ms/mferp/swagger/index.html
* Is the goal to release a Public Preview, Private Preview, or GA? Private preview

## About the client library

* Name of client library: azure-ml
* Link to library reference documentation: N/A for now
* Is there an existing SDK library? If yes, provide link: https://docs.microsoft.com/en-us/python/api/overview/azure/ml/?view=azure-ml-py

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
4. How does the **authentication** workflow look? 
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1
    * Link to library’s sample folder: https://msdata.visualstudio.com/Vienna/_git/sdk-cli-v2?path=%2Fsamples%2Fcurated_sdk
* Champion scenario 2
    * Link to library’s sample folder:
* …
* Champion scenario n
    * Link to library’s sample folder:

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 

* Create a new resource
* Read the resource
* Modify the resource
* Delete the resource
* Error handling 
* Handling race conditions/concurrency issues

**Comment by luigiw** [comment]
Hello, we (Azure ML team) is redesigning our python SDK from scratch, and would like to start a thread to get review feedback from the SDK design board.

**Comment by lilyjma** [comment]
scheduled for 1/12

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/0625a1ff-0400-9887-7c63-f1eb553349a5)[MS INTERNAL ONLY]
