### ISSUE TITLE
Move automation resource group to SDK Engineering System Subscription

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#218]
This includes:
 * usage database
 * function app
 * remove application insights in favor of a common `sdk-bi` one in the Engineering System 

We want our data to be centralized, not spread out. Both usage and impression data should exist in the same resource group in the same subscription. If they can exist in the same Log Analytics workspace that would be good as well.

**Comment by scbedd** [comment]
This task will be deprecated. Right now, the `usage database` has definitely moved to the appropriate location, but the `function app`  and the `appinsights` used by the function app pulling from the billing API daily have not.

We are going to swap over to leverage the cost management APIs instead. Much better view of the world, even if the `service` classifiers are a bit rougher without the `RateCard` data giving details on resources.

As a result, we are going to use Data Factory to move the latest version of the daily MTD dump from the cost management APIs. Least effort, lowest maintenance cost, and we will match the azure UI exactly!

**Comment by danieljurek** [comment]
@scbedd -- Should this still be open?

**Comment by scbedd** [comment]
@danieljurek yes. We haven't shut down pixel server, and that's where this lives.

**Comment by Petermarcu** [comment]
@scbedd does this still need to be open? Should we close this old issue and open new issues to track whatever work is left to be done?

**Comment by scbedd** [comment]
Honestly. This doesn't even exist on my radar anymore given where the resources are stored.

Leaving links for easy reference later.

- [automation](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/2cd617ea-1866-46b1-90e3-fffb087ebf9b/resourceGroups/automation/overview)
- [sdk-bi-data](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/a18897a6-7e44-457d-9260-f2854c0aca42/resourceGroups/sdk-bi-data/overview)
