### ISSUE TITLE
Board Review: Text Analytics

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk#2188]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Text Analytics
* Main contacts: Shawn Fang
* Expected code complete date: Feb 05, 2021
* Expected release date: Feb 10, 2021

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/how-tos/text-analytics-for-health?tabs=relation-extraction
* Link to the service REST APIs:  https://westus2.dev.cognitive.microsoft.com/docs/services/TextAnalytics-v3-1-preview-3/operations/Health
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Text Analytics
* Languages for this review: Java/JS

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: 
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/329cfc783b474d97891a5349e705feb4?diffRevisionId=2d29649d53c4457c97f7e4e5870d04fc&doc=False#com.azure.ai.textanalytics.models.CategorizedEntitiesRecognition
* Link to Champion Scenarios/Quickstart samples: https://github.com/mssfang/azure-sdk-for-java/tree/TA-API-Design/sdk/textanalytics/azure-ai-textanalytics/src/samples/java/com/azure/ai/textanalytics/lro

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/8754191c44914b7e88232f8aba5073de/e54f62c8f97d4fe793379be5e8509f82?diffRevisionId=2c0a26254a524f45bf18cdfb36479cf8&doc=False
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled 1/11

**Comment by lilyjma** [comment]
[Recording](https://web.microsoftstream.com/video/10daa3ff-0400-9887-4246-f1eb54667670)[MS INTERNAL ONLY]
