### ISSUE TITLE
Treat Warnings as Errors in Build

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#219]
Enable "warnings as errors" for all code, and verify the errors cause build failures.  We want to ensure all repos are free of all warnings and errors, and any new warnings or errors introduced will cause build breaks.

- [ ] azure-sdk-for-java
- [ ] azure-sdk-for-js
- [x] azure-sdk-for-net
- [ ] azure-sdk-for-python

**Comment by weshaggard** [comment]
I've submitted https://github.com/Azure/azure-sdk-for-net/pull/5351 to enable this for the .NET repo.

**Comment by kurtzeborn** [comment]
[Our Azure Devops Job isn't correctly reporting as failed](https://github.com/Azure/azure-sdk-for-java/issues/2880) is tracking this work for azure-sdk-for-java.

**Comment by kurtzeborn** [comment]
We now do this where we want to.  It's also up to each language team at this point on whether they want to do this.  For example, .NET does this today.  We don't need a general issue tracking this anymore.
