### ISSUE TITLE
C++ Guidelines: Small structure tweaks

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#2194]
See comments on PR #2178

It looks like you copied most of the TOC headers verbatim ... I may have miscommunicated the intention here was to have the sections needed for the language named in a way that makes sense to the language.  To that end, I'm not sure what extent you support mocking in C++ libraries, or whether you need all three sections for those ... in .NET our support for mocking has implications for the public API in several areas, which is why we have multiple different sub-sections on Mocking.  You should do what makes most sense for C++, using the .NET TOC as the bones of the structure.

Here are some suggestions:
- [ ] https://github.com/Azure/azure-sdk/pull/2178#discussion_r551525981
- [ ] https://github.com/Azure/azure-sdk/pull/2178#discussion_r551526734
- [ ] https://github.com/Azure/azure-sdk/pull/2178#discussion_r551529451
- [ ] https://github.com/Azure/azure-sdk/pull/2178#discussion_r551531578
- [ ] https://github.com/Azure/azure-sdk/pull/2178#discussion_r551537969
- [ ] https://github.com/Azure/azure-sdk/pull/2178#discussion_r551538531

In addition, some existing content might be better categorized in other sections:
- [ ] https://github.com/Azure/azure-sdk/pull/2178#discussion_r551527967
- [ ] https://github.com/Azure/azure-sdk/pull/2178#discussion_r551539936
- [ ] https://github.com/Azure/azure-sdk/pull/2178#discussion_r551540297
- [ ] https://github.com/Azure/azure-sdk/pull/2178#discussion_r551543309

**Comment by RickWinter** [comment]
@annelo-msft It wasn't clear to me if we needed to keep all the topics or were free to rename them.  Part of the problem I see with renaming and removing is the inconsistencies of finding things when moving language to language.  IMO, the freedom to create unique TOC is what led the previous guidelines to becoming a mess.  For that reason I was hesitant to remove/rename any of the guidelines.

Note, if we keep the TOC's all the same then someone can jump language to language with anchor tags by only changing the language sub-portion of the link

**Comment by annelo-msft** [comment]
So, I expect us to do another pass over this and we can iterate on it if needed.  The thinking behind the current approach is that the guidelines will be idiomatic to the reader's (the API designer) language, and can stand-alone if need be; the commonalities across languages are carried through in the high-level structure and organization.  I think Jonathan did a really nice job with this in the [Java guidelines](https://azure.github.io/azure-sdk/java_introduction.html)... for example they have a guideline that you don't use constructors to create service clients -- it wouldn't really make sense to have that in a section called Constructors.  They also have different guidelines for sync and async clients, so they called those out into separate sections.  

![image](https://user-images.githubusercontent.com/21269347/103690660-e8b03100-4f49-11eb-90b0-982415c175d4.png)

The high-level organization still lets you compare .NET to Java, and this will let API Designers interested in cross-language comparisons make those connections, but anyone reading just the Java guidelines wouldn't have to scratch their heads so much.  

The alternative is to come up with quite general terms that better convey the general concepts and then use more language-specific terminology in subsections, but that would take effort outside the scope of MQ.  (Feel free to add any thoughts you have on this to the [guidelines post-MQ issue](https://github.com/Azure/azure-sdk/issues/2118).)  Pushing through the TOC section headers that we have for .NET currently would make things look .NET-centric in a way that would contradict our Idiomatic design principle.  I was hoping we could align in our judgment here and let language guideline writers provide their language-specific expertise.  Let me know if you have further questions on this - happy to chat!

**Comment by annelo-msft** [comment]
I'm also ok if you want to leave in section headers for areas that are not applicable to the language and say "this is a standard SDK feature and we don't support it in this language because ...."  This is particularly relevant for the SDK feature sections in implementation.

**Comment by ahsonkhan** [comment]
I proposed an alternative where we make some of the headings more generalized so that we can keep the same heading title in the ToC for navigation:
https://github.com/Azure/azure-sdk/issues/2118#issuecomment-756436796
