### ISSUE TITLE
Configure doc repos to file customer issues to Azure/azure-sdk-for-X repos

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#2197]
This is a metadata change in the docfx yaml.

Complete set of mapping changes.

- [x] `Azure/azure-docs-sdk-Java` -> [`Azure/azure-sdk-for-java`](https://github.com/Azure/azure-docs-sdk-java/pull/1637)
- [x] `Azure/azure-docs-sdk-dotnet` -> [`Azure/azure-sdk-for-net`](https://github.com/Azure/azure-docs-sdk-dotnet/pull/1731)
- [x] `MicrosoftDocs/azure-docs-sdk-node` -> [`Azure/azure-sdk-for-js`](https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/1007)
- [x] `MicrosoftDocs/azure-docs-sdk-python` -> [`Azure/azure-sdk-for-python`](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1120/files)

**Comment by sima-zhu** [comment]
Java changes here: https://github.com/Azure/azure-docs-sdk-java/pull/1636

**Comment by scbedd** [comment]
@sima-zhu let's confirm that clicking `leave feedback` at the base of a page properly opens a `new issue` interface on the correct repo, then merge!

**Comment by sima-zhu** [comment]
> @sima-zhu let's confirm that clicking `leave feedback` at the base of a page properly opens a `new issue` interface on the correct repo, then we can merge!

OK, then I have to push the changes to origin. Will change the PR.

**Comment by sima-zhu** [comment]
New PR for validation purpose.: https://github.com/Azure/azure-docs-sdk-java/pull/1637

**Comment by sima-zhu** [comment]
Tested in review site feature branch. It is redirected to the azure sdk repo as expected.

**Comment by scbedd** [comment]
Alrighty! Merge it! I'll do the same with the others.

**Comment by scbedd** [comment]
All merged to `master`.
