### ISSUE TITLE
Smoke test track 2 packages against live Azure

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#22]
## Requirements
- Create a smoke test in each supported language
- Use the latest public release of the SDK for each supported service 
- Use the Mgmt SDK to create resources to test against and to clean up after
- Execute a single request against each supported live service in public Azure

## Languages
- [x] .NET
- [ ] Java
- [ ] Python
- [ ] JavaScript

**Comment by kurtzeborn** [comment]
Closing this Epic.  Smoke tests created and running regularly.  We have another epic (#586) tracking further integration.
