### ISSUE TITLE
When going to home web page, there are language latest releases missing.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk#2215]
When navigating to: https://azure.github.io/azure-sdk/
There is no data for C++, C, iOS and Android.

User need to go to https://azure.github.io/azure-sdk/releases/latest
Then the data for C++, C, Android and iOS is populated.

The root cause is that we have two different pages populating the language's latest releases data, and we need to maintain both.
Right now, they are not showing the same info.

**Comment by ahsonkhan** [comment]
Nice catch!

> There is no data for C++, C, iOS and Android.

Well, we can't have that! :)
