### ISSUE TITLE
[SDK Review] Custom Vision

### ISSUE THREAD

**Issue by areddish** [Azure/azure-sdk#222]
Opening an issue to track reviewing custom vision.

Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/5164

**Comment by adrianhall** [comment]
@areddish - this has now been open over a month.  Any movement on when you will be ready for a review?

**Comment by adrianhall** [comment]
Closing since it has been 2 months without a response.  If you need a review, then please open a new review request.
