### ISSUE TITLE
Board Review: Introducing Azure Object Anchors

### ISSUE THREAD

**Issue by jastenze** [Azure/azure-sdk#2231]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: **Azure Object Anchors**
* Main contacts: **rgarcia, virivera, arrezaie, ariye, crtreasu, jastenze**
* Expected GA date for this library: **March 1st, 2020**

## About the Service 

* Link to documentation introducing/describing the service: **https://review.docs.microsoft.com/azure/object-anchors?branch=release-preview-aou**
* Link to the service REST APIs: **https://github.com/Azure/azure-rest-api-specs-pr/pull/2658/files , https://github.com/Azure/azure-rest-api-specs-pr/pull/2532**
* Is the goal to release a Public Preview, Private Preview, or GA? **Public Preview**

## About the client library

* Name of client library: **Azure Object Anchors**
* Link to library reference documentation: **https://review.docs.microsoft.com/azure/object-anchors?branch=release-preview-aou**
* Is there an existing SDK library? If yes, provide link: **Yes, https://dev.azure.com/microsoft/Analog/_git/mr.cloud.objectunderstanding.sdk**

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
4. How does the **authentication** workflow look? 
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* **Upload a model for ingestion**
    * `IngestionJobResponse response = await CreateJobAsync(new IngestionJobRequest(new AssetConfiguration(gravityVector, scale), inputFilePath));`
* **Get status of ingestion job**
    * `IngestionJobResponse response = await GetJobAsync(jobId);`
* **Download ingestion results**
    * `IngestionJobResponse response = await DownloadAsync(outputFilePath, ingestionJobResponse);`

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 

* Create a new resource
* Read the resource
* Modify the resource
* Delete the resource
* Error handling 
* Handling race conditions/concurrency issues

**https://review.docs.microsoft.com/en-us/azure/object-anchors/quickstarts/get-started-model-ingestion?branch=release-preview-aou**

**Comment by lilyjma** [comment]
scheduled for 2/2 2-3PM

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/fe22a1ff-0400-b564-0e36-f1eb65a7494d)[MS INTERNAL ONLY]
