### ISSUE TITLE
Board Review: Discuss autogenerated APIView approval workflow

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk#2266]
APIView has a new feature that creates review automatically from master branch as part of scheduled run. We have created base line reviews using last published GA packages. CI creates a new revision for each package if it finds a difference in API surface level and these revisions need to be approved by architects. We are planning to enforce API review approval before releasing a GA package from Feb release onwards and this meeting is to discuss API approval workflow to get these auto generated APIs approved.

**Comment by lilyjma** [comment]
scheduled for 1/20 2-3pm

**Comment by lilyjma** [comment]
rescheduled to 1/26 3-4pm pst

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/7557a1ff-0400-9887-2ba9-f1eb60331bc4)[MS INTERNAL ONLY]
