### ISSUE TITLE
Perf/Stress Test Infrastructure

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#227]
## Goal
Establish an automated testing system which reports performance numbers (RPS and resource (memory, proc) usage for example) on a per library/language basis which can be used as a baseline to track and detect performance degradation (large and small movements) going forward.

**Comment by kurtzeborn** [comment]
Converting this to be an epic since this is a much larger body of work and largely unrelated to the smoke test project.

**Comment by benbp** [comment]
Moving the stress test infrastructure work into its own epic: https://github.com/Azure/azure-sdk/issues/3025
