### ISSUE TITLE
Board Review: Azure Mixed Reality Authentication client library

### ISSUE THREAD

**Issue by archanaiyer** [Azure/azure-sdk#2280]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: ou-servicesdkdev@microsoft.com
* Main contacts: crtreasu, virivera, rgarcia, ariye
* Expected code complete date: 01/29
* Expected release date: 03/01/2021

## About the Service 

This particular client is meant to handle authentication for Mixed Reality client libraries. Mixed Reality uses a custom STS service to exchange account credentials for access tokens and that's what this library does.

* Link to documentation introducing/describing the service: https://docs.microsoft.com/azure/spatial-anchors/concepts/authentication
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/mixedreality/data-plane/Microsoft.MixedReality/preview/2019-02-28-preview 
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/2005 

## About the client library

* Name of the client library: Azure Mixed Reality Authentication
* Languages for this review: **JavaScript**, **Java**, **Python**

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET
n/a already completed
* APIView Link: 
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/f3a4bb684ffd4badada05eff7de952d5
* Link to Champion Scenarios/Quickstart samples: See [here](https://github.com/craigktreasure/azure-sdk-for-java/blob/craig/mr-authentication-lib/sdk/mixedreality/azure-mixedreality-authentication/README.md).

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/986545855b9c499faeff72b25115ab96
* Link to Champion Scenarios/Quickstart samples: See [here](https://github.com/craigktreasure/azure-sdk-for-python/blob/craig/mr-authentication-lib/sdk/mixedreality/azure-mixedreality-authentication/README.md).
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/4917626415bc448c8e2534e00c6f3a17
* Link to Champion Scenarios/Quickstart samples: See [here](https://github.com/craigktreasure/azure-sdk-for-js/blob/craig/mr-authentication-lib/sdk/mixedreality/mixed-reality-authentication/README.md).

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 2/3

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/331fa4ff-0400-b564-cf88-f1eb6672569a)[MS INTERNAL ONLY]
