### ISSUE TITLE
Board Review: Event Grid GA SDK

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#2292]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Event Grid team.
* Main contacts: PM: jafernan@microsoft.com, Dev Lead: rajarv@microsoft.com. Dev: ahamad@microsoft.com 
* Expected code complete date:
* Expected release date: Expected GA in March release cycle

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/event-grid/ and https://docs.microsoft.com/en-us/azure/event-grid/edge/.
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/1645

## About the client library

* Name of the client library: azure-eventgrid / azure-messaging-eventgrid
* Languages for this review: C#/Java/Python/Typescript

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/1b1c0fbd41e849debdeede261e859b1c
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventgrid/Azure.Messaging.EventGrid/samples

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/87a3eeeee87d4e4c8f644baaf2dde00d
* Link to Champion Scenarios/Quickstart samples: https://github.com/YijunXieMS/azure-sdk-for-java/tree/eg-beta4/sdk/eventgrid/azure-messaging-eventgrid/src/samples/java/com/azure/messaging/eventgrid/samples

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/8be4727a09b8411bbc05b588b750bcc8
* Link to Champion Scenarios/Quickstart samples: https://github.com/rakshith91/azure-sdk-for-python/blob/arch_preview_feedback/sdk/eventgrid/azure-eventgrid/samples/champion_scenarios.md
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/209978255b1a436694d518838e2a9454
* Link to Champion Scenarios/Quickstart samples: https://github.com/ellismg/azure-sdk-for-js/tree/ellismg/event-grid-api-updates/sdk/eventgrid/eventgrid/samples

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 2/1

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/ed47a1ff-0400-9887-1007-f1eb64e87e71)[MS INTERNAL ONLY]

**Comment by lilyjma** [comment]
Java, Python, JS: [Recording](https://msit.microsoftstream.com/video/c54ba1ff-0400-b564-3ac2-f1eb67440e54)[MS INTERNAL ONLY]
