### ISSUE TITLE
updates to https://github.com/Azure/azure-sdk/tree/master/_data/releases/latest structure

### ISSUE THREAD

**Issue by elraikhm** [Azure/azure-sdk#2293]
Based on the releases page user study https://microsoft-my.sharepoint.com/:x:/p/elraikhm/EX0oLo9BwolIrffKdM2gIygBTYdL2dt2wt8k6gJO4RAhHg?e=NfUpvA 

please consider the following updates to the CSV structure:
-Add a column to keep the library status: preview, active, maintained, deprecated
-Add a column with the library release date

On the releases page https://azure.github.io/azure-sdk/releases/latest/index.html, please add
-Color schema description (blue/grey)
-Show version release dates column
-Show library status column
-Rename "Notes" to "Legacy library names"
-If possible, freeze the table header (make it visible when the user scrolls down)

**Comment by weshaggard** [comment]
I believe our latest updates covered all these requests.
