### ISSUE TITLE
Create flat folder of all SDK packages and binaries

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#23]
## Requirements
- Collect the latest version of all SDK packages into a flat folder
- Extract the raw binaries (e.g. DLLs for .NET) into a flat folder, for customers who prefer to avoid package managers

## Languages
- [ ] .NET
- [ ] Java
- [ ] Python
- [ ] JavaScript

**Comment by kurtzeborn** [comment]
Closing this.  We have already created some of the "release only" pipelines where teams give us their built packages and we release them through our system.  That is the plan going forward as tracked by other issues.
