### ISSUE TITLE
Board Review: Introducing FarmBeatsClient

### ISSUE THREAD

**Issue by agniveshadhikari** [Azure/azure-sdk#2327]
_This is just to initiate an early review to avoid any breaking change later on. A couple of specifics haven't been completely chalked out yet._

## Contacts and Timeline

* Service team responsible for the client library: Azure Global - AgFood Platform
* Main contacts: Agnivesh Adhikari (agadhika) and Karthik R G (karrg)
* Public Preview Date: First Week of May 2021
* Expected GA date for this library: October 2021

## About the Service 
Please ping karrg to get access to this page if you don't have access.
* Link to documentation introducing/describing the service: https://github.com/MicrosoftDocs/Azure-FarmBeats/tree/main/documentation 
* Link to the service REST APIs: https://github.com/MicrosoftDocs/Azure-FarmBeats/tree/main/documentation/swagger
* Is the goal to release a Public Preview, Private Preview, or GA?
A: The goal is to release Public Preview SDKs (Early May 2021)

## About the client library

* Name of client library: FarmBeatsClient
* Link to library reference documentation: NA
* Is there an existing SDK library? No, this is a v1.

## Step 1: Champion Scenarios
[Link to doc](https://microsoft.sharepoint.com/:w:/t/MCAP/Eb1f6KwfNThHmkrPY_l-F_IB4A7WKQVHywIZNeF6iHiFBw?e=v5Sxkj)

### Additional Links:
* [Link to apiview for python](https://apiview.dev/Assemblies/Review/f6a63c66d94b4dd3afdd8e53278044ce)
* [Link to PR for python](https://github.com/Azure/azure-sdk-for-python/pull/17337)

**Comment by lilyjma** [comment]
scheduled for 2/24 10-11AM PST

**Comment by lilyjma** [comment]
rescheduled for 3/1 6-7PM PST

**Comment by tg-msft** [comment]
> We don't have a repo for our library yet.

You should use one of our monorepos like `azure-sdk-for-<lang>`.  In the meantime, can you upload your APIs to http://apiview.dev/?  You can upload a .dll/.nupkg for .NET, .jar for Java, etc.

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/a30da4ff-0400-85a8-6910-f1eb7b0390b1)[MS INTERNAL ONLY]

**Comment by lilyjma** [comment]
scheduled for 3/29 8-9AM PST

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/b02ea1ff-0400-94b1-6cc2-f1eb91715cbc)[MS INTERNAL ONLY]
