### ISSUE TITLE
Board Review: Azure::Keyvault::Keys for C++

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk#2331]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team:
* Main contacts: @vhvb1989  @RickWinter 
* Expected code complete date:  4/2/21
* Expected release date: 4/6/21

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: azure-security-keyvault-keys
* Languages for this review: C++

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### C++

* APIView Link: 
  * https://apiview.dev/Assemblies/Review/da8d0ecdf87c49238b75fee069413029
* Link to Champion Scenarios/Quickstart samples:
  * hello-world: https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/keyvault/azure-security-keyvault-keys/samples/sample1_hello_world.md
  * backup and restore: https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/keyvault/azure-security-keyvault-keys/samples/sample2_backup_and_restore.md
  * list keys: https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/keyvault/azure-security-keyvault-keys/samples/sample3_get_keys.md

**Comment by lilyjma** [comment]
scheduled for 4/5

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/ccdd0840-98dc-94b1-7606-f1eb9660f573)[MS INTERNAL ONLY]

**Comment by vhvb1989** [comment]
@lilyjma at what point do we usually close this issue?  The preview version reviewed here was now shipped.
