### ISSUE TITLE
Board Review: Azure Object Anchors

### ISSUE THREAD

**Issue by jastenze** [Azure/azure-sdk#2335]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: **Azure Object Anchors**
* Main contacts: **rgarcia, virivera, arrezaie, ariye, crtreasu, jastenze**
* Expected code complete date: **February 9th, 2021**
* Expected release date: **March 2nd, 2021**

## About the Service 

* Link to documentation introducing/describing the service: **https://review.docs.microsoft.com/azure/object-anchors?branch=release-preview-aou**
* Link to the service REST APIs: **https://github.com/Azure/azure-rest-api-specs-pr/pull/2658/files (To be iterated upon)**
* Link to GitHub issue for previous review sessions, if applicable:  **https://github.com/Azure/azure-sdk/issues/2231**

## About the client library

* Name of the client library: **Azure.MixedReality.ObjectAnchors**
* Languages for this review: **.NET**

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: **https://apiview.dev/Assemblies/Review/1fdf4c5c1109482ca6316d34319903e9/cfce16a525b64ef3ad30242940eba71b?doc=False**
* Link to Champion Scenarios/Quickstart samples: **(Not yet tested, https://github.com/jastenze/azure-sdk-for-net-pr/blob/user/jastenze/aoa-data-sdk/sdk/mixedreality/Azure.MixedReality.ObjectAnchors/tests/Samples/IngestionProcessSample.cs)**

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 2/9

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/f603a4ff-0400-b564-fe5b-f1eb6b2e4cd0)[MS INTERNAL ONLY]

**Comment by tg-msft** [comment]
[Notes](https://github.com/Azure/azure-sdk-pr/blob/master/archboard/2021/02/2021-02-09-Object-Anchors-NET.md) [MS INTERNAL ONLY]
