### ISSUE TITLE
Broken URLs in Java package index "all"

### ISSUE THREAD

**Issue by KarlErickson** [Azure/azure-sdk#2336]
Some URLs in the package index contain unescaped spaces. The problem is most easily seen by navigating [here](https://docs.microsoft.com/en-us/azure/developer/java/sdk/azure-sdk-library-package-index#all-libraries) and searching for "msi auth token". The raw Markdown is visible, causing the table column to be extra wide.

**Comment by weshaggard** [comment]
Thanks for reporting this. I fixed it in our underlying data source with https://github.com/Azure/azure-sdk/commit/18f760d982313f5e350a6000707eb66968524db3. The next set of automation that triggers will have an update for this.

**Comment by JonathanGiles** [comment]
When would we expect to see this updated on the live site? Thanks!

**Comment by weshaggard** [comment]
The docs PR with the fix got merged https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/1511 and so it looks like it is live now.

**Comment by JonathanGiles** [comment]
There might be a similar problem with the "Event Hubs - Databricks" table row?

**Comment by weshaggard** [comment]
Thanks for pointing that one out. I fixed the underlying data with https://github.com/Azure/azure-sdk/commit/36c6faa57177413716096104cada87e9a9cdc115 it should flow through to the docs in the coming days.
