### ISSUE TITLE
Board Review: Microsoft.Azure.WebJobs.Extensions.EventHubs GA

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk#2346]
## Contacts and Timeline

* Responsible service team: ADP
* Main contacts: @pakrym @JoshLove-msft 

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs
* Link to the service REST APIs: N/A

## About the client library

* Name of the client library: Microsoft.Azure.WebJobs.Extensions.EventHubs
* Languages for this review: .NET

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/baa01eaa859b4d169a781df9517f80e9
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/README.md

**Comment by lilyjma** [comment]
scheduled for 2/23

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/ab0da4ff-0400-85a8-ec59-f1eb762ef8a7)[MS INTERNAL ONLY]
