### ISSUE TITLE
Create an azure-sdk-tools consumption story

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#235]
As we need more tools in the various build pipelines we need to come up with a strategy for publishing and consuming these tools in our various pipelines. 

A few options:

1) git clone a the azure-sdk-tools repo as a step in the build pipeline and then use any scripts or tools.
2) create a package and host it on a public package manager (i.e. pypi, nuget, etc) and restore/install the package as a build step and then use the tool(s).
3) create a zip file containing the tools and scripts we need to use and then and download that using something like curl as a build step and then use the tool(s). 

I'm currently leaning towards option (3) as it allows us to bundle multiple different types of tools and scripts together without tying us to one particular language/package manager, drawback of (2), and without requiring is to download more then we need, drawback of (1).

As we do this work we also need to be sure that we version our tools and have our build pipelines download a particular version, as opposed to always latest, otherwise we will have some difficulties if we ever fork to do a hotfix/servicing release of an older commit.

cc @scbedd

**Comment by chidozieononiwu** [comment]
@weshaggard For the option 3, where should the zip files be stored, in the individual language repos or should they all be in azure-sdk-tools repo, or something like a blob storage?

**Comment by weshaggard** [comment]
We should explore possibly using a DevOps feed but if that doesn't work for whatever reason we can setup a blob storage account directly instead.

**Comment by chidozieononiwu** [comment]
The build pipeline has a step called template which is basically another yaml file (consisting of jobs, steps, variables e.t.c) which is loaded and ran as a single step. There is also a feature called resources which allows you to load the templates from other repos using a service connection.

What I have done is to isolate the python script for verifying the agent OS into a template which I stored in the azure-sdk-tools repo. This can then be loaded into any of the other repos with the OSName from the strategy matrix passed as parameter. The eliminates the need for blob storage or DevOps feed.

**Comment by weshaggard** [comment]
That is an interesting idea but I'm not sure it will work for all our different tool needs. Also I'd like to understand if we use this approach if it actually clones the entire repo to get the one file or does it simply pull individual files.
