### ISSUE TITLE
Board Review: Introducing Azure SDK and Graph SDK integration

### ISSUE THREAD

**Issue by navyasric** [Azure/azure-sdk#2352]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: MSAL SDK, Azure SDK, MS Graph SDK teams
* Main contacts: Navya Canumalla, Steven Soneff, Scott Schaab, Darrel Miller
* Expected GA date for this library: TBD 

## About the Service 

* Link to documentation introducing/describing the service: https://microsoft-my.sharepoint-df.com/:p:/p/nacanuma/ES_3rG4JOd9CjCFfpASEuw8BaFmD9afbO7BltV49VpSoNw?e=7bCcgQ
* Link to the service REST APIs: 
* Is the goal to release a Public Preview, Private Preview, or GA? Public Preview

## About the client library

* Name of client library: Azure SDK, Graph SDK
* Link to library reference documentation:
* Is there an existing SDK library? If yes, provide link: https://github.com/Azure/azure-sdk-for-net, https://github.com/microsoftgraph/msgraph-sdk-dotnet

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library? Web service or daemon app hosted on App service
2. Who is the end-user of the application (the developer's customer)? No end-user. This is an app only auth scenario.
3. What features of the API need to be explained in the sample so that someone could use this API in real app? managed identities, application client credentials, Graph API access, access token acquisition
4. How does the **authentication** workflow look?   Auth flows using application identities such as managed identities and client credentials(secrets/certificates).
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1: Access MS Graph from Azure web app using application identity
    * Link to library’s sample folder: 
    ``` 
       using Azure.Identity;​
       using Microsoft.Graph.Core;​

       async static Task GraphApiCall()​
      {​
          // Create the Graph service client with the Azure SDK Credential API which gets an access token using the available Managed Identity​
          var tokenCredential = new DefaultAppCredential();
          var client = GraphClientFactory.Create(new TokenCredentialAuthProvider(tokenCredential));​
          var graphServiceClient = new GraphServiceClient(client);​
          var groups= await graphServiceClient.Groups.Request().GetAsync();​
      }​
   ```
* Champion scenario 2
    * Link to library’s sample folder:
* …
* Champion scenario n
    * Link to library’s sample folder:

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 

* Create a new resource
* Read the resource
* Modify the resource
* Delete the resource
* Error handling 
* Handling race conditions/concurrency issues

**Comment by lilyjma** [comment]
scheduled for 2/22 2-3pm pst

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/2363a1ff-0400-85a8-0ae5-f1eb75616d74)[MS INTERNAL ONLY]
