### ISSUE TITLE
Test Proxy Service

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#2366]
Goals:
1.	For performance testing, isolate our SDKs from service randomness to allow for better measurement of SDK performance and not live service performance.
2.	Expand to become a language agnostic proxy solution that could be used to mock out live service responses for general test automation scenarios.
3.	[stretch] Generalize the above solution and make it open source and a value add for customers using track 2 versions of the SDKs.

**Comment by vhvb1989** [comment]
@nguerrera  isn't this proxy server something similar to what you were doing to replace the record&playback tests?

**Comment by nguerrera** [comment]
Yes, I think so. @scbedd and @kurtzeborn are taking it from here. You can see all of my handoff notes linked in the chat thread we had about this. :)

**Comment by scbedd** [comment]
Closing epic in favor of labelled issues in github project!
