### ISSUE TITLE
Reconcile the 2 different release notes and change log guidelines policy docs

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#2377]
We have https://azure.github.io/azure-sdk/policies_releasenotes.html which is more about our monthly release notes and we have https://azure.github.io/azure-sdk/policies_releasenotes.html which is more about our change log entries for individual libraries. 

Given we have plans to automatically generate the release notes from the change log entries we should merge these guidelines such that it is clear how they relate to one another.

I suggest we add something akin to a "Highlights" which we can easily pull into the release notes so that section in particular should follow the unique guidelines at https://azure.github.io/azure-sdk/policies_releasenotes.html (but be merged into the change log guidelines).

**Comment by weshaggard** [comment]
@salameer assigning to you to take the first steps.

**Comment by jsquire** [comment]
Please also consider formalizing a means to offer acknowledgement/credit for community members contributing to a release, which isn't discussed in either of our current sets of guidelines.  For illustration, the messaging libraries have been using [this](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/CHANGELOG.md#520-2020-09-08) format in change logs and summarizing to just the inline mention in the change details for release notes:

## 5.2.0 (2020-09-08)

### Acknowledgments

Thank you to our developer community members who helped to make the Event Hubs client libraries better with their contributions to this release:

- Daniel Marbach _([GitHub](https://github.com/danielmarbach))_

### Changes

#### Key Bug Fixes

- The underlying AMQP library has been enhanced for more efficient resource usage; this will result in a noticeable reduction in memory use in common consuming scenarios.  (A community contribution, courtesy of _[danielmarbach](https://github.com/danielmarbach))_

**Comment by weshaggard** [comment]
@jsquire there has been some thoughts about figuring out a way to use the git commit history to pull in the change list and the contributors of those contributions automatically. Do you think that would be interesting and potentially helpful? We could consider doing it as a seeding step in the Prepare-Release scripts we have been working on.

**Comment by jsquire** [comment]
@weshaggard:  I think there would be value in automating that, sure!.   I'd ask that we have control for manual review and tweaks, just in case we're doing something like incorporating a contributor's idea/sample/feedback from a comment or source other than a PR contribution.

**Comment by weshaggard** [comment]
I've been wanting to experiment with some support for that. I filed https://github.com/Azure/azure-sdk-tools/issues/1392 to track that as separate concern.

**Comment by heaths** [comment]
Changelogs contain a rather technical roll-up of commits - less in-depth than a commit history (and filtered of commit descriptions like "more updates"), but more in-depth than release notes. I don't think making both changelogs and release notes the same level are beneficial. For most projects, their changelogs are typically just their commit history (akin to `git log --oneline`). Release notes tend to highlight the bigger changes. Why should they have the same level of detail?

**Comment by weshaggard** [comment]
This work has now been done.
