### ISSUE TITLE
Board Review: Introducing Azure Container Registry (ACR)

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#2384]
## Contacts and Timeline

* Service team responsible for the client library: **Tejaswini Duggaraju**, **Toddy Mladenov**, **Yugang Wang**, **Sajay Antony**
* Main contacts: The above service team contacts as well as Azure SDK team contacts: Tech Lead **Anne Thompson**, Engineering Lead **Alex Ghiondea**, PM **Elena Raikhman**
* Expected GA date for this library: June 2021

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/container-registry/
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/containerregistry/#data-plane-rest-operation-groups-preview
* Is the goal to release a Public Preview, Private Preview, or GA?  We will start with public previews and plan to GA by the end of the semester.

## About the client library

**Note:** This arch board meeting is an initial introduction to the service and will be focused primarily on introducing the service.  In addition, we will present a prototype client ACR API in .NET to gather early feedback from architects.

**Track 1 Library**

* Name of client library:  https://www.nuget.org/packages/Microsoft.Azure.ContainerRegistry/1.0.0-preview.1
* Link to library reference documentation: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/containerregistry/Microsoft.Azure.ContainerRegistry/tests/Tests
* Is there an existing SDK library? If yes, provide link:  https://www.nuget.org/packages/Microsoft.Azure.ContainerRegistry/1.0.0-preview.1

**Track 2 Libraries** (prototypes for discussion)

  - **Azure.Containers.ContainerRegistry** | [ApiView](https://apiview.dev/Assemblies/Review/ba57bf904e524ce3bf647dad124ddc7c)
  - **Azure.Containers.ContainerRegistry.ResumableStorage** | [ApiView](https://apiview.dev/Assemblies/Review/0dc8793c0a8c45c89ceb64df32a97659)

## Step 1: Customer Scenarios 

**Managing a registry**
_e.g. “I’d like to create a script that scans all ACR repositories and deletes all the old docker images, while only keeping the latest three images”_

- Target audience: basic developers with general needs (~90%)
- Code samples: [**.NET**](https://gist.github.com/annelo-msft/e0d4976b029e8815dcbcf5faf449db32#1-customer-would-like-to-create-a-script-that-scans-all-acr-repositories-and-deletes-all-the-old-docker-images-while-only-keeping-the-latest-three-images)

**Setting permissions on images**
_e.g. “I’d like to lock this image’s tag so no one can update it while I’m deploying it to many different global datacenters, because this can take days.”_

- Target audience: basic developers with general needs (~90%)
- Code samples: [**.NET**](https://gist.github.com/annelo-msft/e0d4976b029e8815dcbcf5faf449db32#2-make-tagged-image-read-only)

**Using multi-architecture images**
_e.g. “I’d like to store a collection of images for the same app that run on different platforms and be able to treat it like a single image.”_

- Target audience: basic developers using "manifest lists" (<10%, but expected to grow with adoption of this type of image)
- Code samples: [**.NET**](https://gist.github.com/annelo-msft/e0d4976b029e8815dcbcf5faf449db32#3-select-image-for-a-given-architecture-from-a-manifest-list)

**Handling OCI Artifacts**
_e.g. “I’d like to store Bicep files to manage Azure resources in my registry, so I can have all my deployment artifacts in one place.”_

- Target audience: tool developers building command line tools for OCI Artifacts (<10%, but expected to grow with adoption of OCI Artifacts)
- Code samples: [**.NET**](https://gist.github.com/annelo-msft/e0d4976b029e8815dcbcf5faf449db32#7-store-and-retrieve-an-oci-artifact-rather-than-a-docker-image)

**Comment by lilyjma** [comment]
scheduled for 3/2

**Comment by annelo-msft** [comment]
FYI @AlexGhiondea @jeremymeng @pallavit @seankane-msft

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/e949a1ff-0400-85a8-dcdd-f1eb7d461ef1)[MS INTERNAL ONLY]
