### ISSUE TITLE
API Proposal: Add Security Message API to IoTHub Device SDK (C)

### ISSUE THREAD

**Issue by wickste** [Azure/azure-sdk#239]
# Overview
The Security message feature will provide the user with the ability to send a security message to the Azure Security Team’s system to identify and attempt to mitigate potential security threats.  The security messages will not be directly viewable by the end customers, they will be routed to an Event Hub owned by the Azure Security Team and processed there. 

The Security messages will be normal IoTHub messages with special system properties that identify them as Security messages.  There will be a method on the Message Object/Class to mark the messages as security messages which will set the proper system properties on the message.   

# SDK Availability
This API will be added to IoTHub Device SDKs for C, C#, Java and Node.js

# Sample Code (C)

Full sample project [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample.c)

```C
while(g_continueRunning)
{
    // Construct the iothub message
    telemetry_temperature = 20.0f + ((float)rand() / RAND_MAX) * 15.0f;
    telemetry_humidity = 60.0f + ((float)rand() / RAND_MAX) * 20.0f;

    sprintf(telemetry_msg_buffer, "{\"temperature\":%.3f,\"humidity\":%.3f,\"scale\":\"%s\"}", 
                telemetry_temperature, telemetry_humidity, telemetry_scale);

    message_handle = IoTHubMessage_CreateFromString(telemetry_msg_buffer);

    // Set Message property
    (void)IoTHubMessage_SetMessageId(message_handle, "MSG_ID");
    (void)IoTHubMessage_SetCorrelationId(message_handle, "CORE_ID");
    (void)IoTHubMessage_SetContentTypeSystemProperty(message_handle, "application%2fjson");
    (void)IoTHubMessage_SetContentEncodingSystemProperty(message_handle, "utf-8");

    // Add custom properties to message
    (void)IoTHubMessage_SetProperty(message_handle, "property_key", "property_value");

    // Set this as security message
    (void)IoTHubMessage_SetAsSecurityMessage(message_handle);

    // check if message is security message
    bool isSecurityMessage = IoTHubMessage_IsSecurityMessage(message_handle);

    (void)printf("\r\nSending message %d to IoTHub\r\nMessage: %s\r\n", (int)(messagecount + 1), 
            telemetry_msg_buffer);
    IoTHubDeviceClient_SendEventAsync(device_handle, message_handle, send_confirm_callback, NULL);

    // The message is copied to the sdk so the we can destroy it
    IoTHubMessage_Destroy(message_handle);
    messagecount = messagecount + 1;

    ThreadAPI_Sleep(g_interval);
 }
```

# New API Surface added (C)
Reference to existing IoTHub client APIs [(link)](https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-client-h)
## IoTHub Device SDK additions
```C
IOTHUB_MESSAGE_RESULT IoTHubMessage_SetAsSecurityMessage(IOTHUB_MESSAGE_HANDLE iotHubMessageHandle); 
bool IoTHubMessage_IsSecurityMessage(IOTHUB_MESSAGE_HANDLE iotHubMessageHandle);
```

**Comment by adrianhall** [comment]
Arch. Board Review feedback:

* Revisit message construction (set structure and have one API call to construct the message)
* Consider having bit flag based approach of representing different types of messages in Message APIs
* There might be too many mallocs happening in the messaging API (i.e. are we creating content copies and asking client to hold onto their payload as well for the duration of the API call?)
* There might be perf hits due to the lengthy call stack of each messaging API call
* We should convert our names like "securitymessage" into a list of flags that can be set or get on a higher level concept like "Message"
* For non-OS devices, what should the buffer management usage look like?
