### ISSUE TITLE
Board Review: AppConfiguration new features

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk#2393]
## Contacts and Timeline

* Responsible service team: ADP
* Main contacts: @pakrym 
* Expected code complete date: N/A
* Expected release date: N/A

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/azure-app-configuration/overview
* Link to the service REST APIs: https://docs.microsoft.com/en-us/azure/azure-app-configuration/rest-api

## About the client library

* Name of the client library: Azure.Data.AppConfiguration
* Languages for this review:

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/9b8b99e6d6544ea0b0eb4d4a92c2c09c/d921121d178f4925a27a9b430dd4e490?diffRevisionId=04b0e0d66aef4de38b0448b0672ac7fa&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples:
	https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/samples/Sample8_ChangeNotification.md
	https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/samples/Sample9_FeatureFlags.md 	
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/samples/Sample10_SecretReference.md

	https://gist.github.com/pakrym/5904304c62d5003fc75d5abbaf145b76

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 3/3 2-3PM PST

**Comment by richardpark-msft** [comment]
(Not .net, but I did take a stab at adding in some models for the various filter types in JS)

[JS apiview](https://apiview.dev/Assemblies/Review/9b8b99e6d6544ea0b0eb4d4a92c2c09c?diffRevisionId=04b0e0d66aef4de38b0448b0672ac7fa&doc=False&diffOnly=False)

I still need to go through and give the fields the proper naming treatment (currently they're reflecting the exact structure of the underlying JSON) but it can illustrate what they look like.

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/ec45a1ff-0400-85a8-05e1-f1eb7c7d7033)[MS INTERNAL ONLY]

**Comment by lilyjma** [comment]
scheduled for 3/16

**Comment by seankane-msft** [comment]
[Python APIView](https://apiview.dev/Assemblies/Review/bd84b4a794864b39ae24b0eb4251e6cf?diffRevisionId=115eb2f51fba449c8007d8d997892211&doc=False&diffOnly=False)

[Python samples](https://gist.github.com/seankane-msft/96fd8611d3093a8682f19e5d7457de26)

**Comment by richardpark-msft** [comment]
JavaScript:
* [APIView](https://apiview.dev/Assemblies/Review/d89b0cb38b474b07ad545fd89df0a4a2)
* [Samples](https://github.com/Azure/azure-sdk-for-js/blob/99924261f62f5ba8fc5f2dc262116b152c106d21/sdk/appconfiguration/app-configuration/test/samplesForApiReview.ts)

**Comment by mssfang** [comment]
Java:
[API-view](https://apiview.dev/Assemblies/Review/38400afa13344c8092775e62caba40d3?diffRevisionId=d51c0661443e49508df2e8a99b189c47&doc=False&diffOnly=False#com.azure.data.appconfiguration.models.ConfigurationSetting)
[Sample](https://gist.github.com/mssfang/fdf2370a91651e13056ab488ee8eff83)

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/1627a4ff-0400-85a9-a209-f1eb86aa6640)[MS INTERNAL ONLY]
