### ISSUE TITLE
API Proposal: Add Custom Data API to Azure Device Provisioning Service SDK 

### ISSUE THREAD

**Issue by wickste** [Azure/azure-sdk#242]
# Overview
The driver of this feature is to provide a mechanism for clients to send custom data to the provisioning service to be used by web hook developers to have insight in the device attempting to register.  The programming flow for this would be as follows: 

1. The developer will create a provisioning handle as detailed in the existing samples 
2. After receiving the provisioning handle, the user will call the Prov_Device_LL_SetProvisioningData with the json that need to be transmitted 
3. Once the device is registered with DPS and receives the IoTHub credentials the user can call Prov_Device_LL_GetProvisioningData to get back the custom data from the Service if any. 

By design the custom data that is sent must be sent as json.  Due to the json parser paradigm the SDK must validate this to ensure it is valid json.  No other validation shall be done by the SDK, any other validation, schema or otherwise, will be done by the Provisioning service. 

# Sample Code (C)

```C
PROV_DEVICE_LL_HANDLE handle = Prov_Device_LL_Create(global_prov_uri, id_scope, prov_transport)); 
if (handle != NULL) 
{ 
    // Set the custom data to be used in the registration 
    Prov_Device_LL_SetProvisioningData(handle, "{ \"iotcModelId\": \"myTemplateId\" }"); 
    Prov_Device_LL_Register_Device(handle, register_device_callback, &user_ctx, registation_status_callback, &user_ctx) 
    do 
    { 
        Prov_Device_LL_DoWork(handle); 
    } while(not_registered); 
 
    const char* dps_custom_data = Prov_Device_LL_GetProvisioningData(handle); 
    if (dps_custom_data != NULL) 
    { 
    // Process data 
    } 
    Prov_Device_LL_Destroy(handle); 
} 
```

# New API Surface added (C)
Reference to existing Device Provisioning Service client APIs [(link)](https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/prov-device-ll-client-h)
## DPS client SDK additions
```C
/*
* Handle – The provisioning device handle that is
* dataField – The json data that is sent to the DPS Service
* return: The result of the operation 
*/
PROV_DEVICE_RESULT Prov_Device_LL_SetProvisioningData(PROV_DEVICE_LL_HANDLE handle, const char* dataField); 

/*
* Handle – The provisioning device handle that is  
* return: The resulting json that was specified by the service 
*/
const char* Prov_Device_LL_GetProvisioningData(PROV_DEVICE_LL_HANDLE handle); 
```

**Comment by adrianhall** [comment]
Arch. Board Review feedback:

* Change API naming / signature to be clear that this requires JSON
* Naming for methods should have each verb separated in the API naming (e.g. Set_Provisioning_Data, Register_Device)
* Consider taking binary data in Set_Provisioning_Data
