### ISSUE TITLE
Messaging - Event Grid (January-June 2021)

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk#2427]
This tracks the work for Messaging - Event Grid

**Comment by lmazuel** [comment]
End of March 2021 status:

- EventGrid SDK went GA track2 in March release cycle (as 4.0.0 cross-language)
- Did an off-cycle 4.1.0 for ACS team mid-March
- Service team expected features to come in Cobalt:
  - AAD support (waiting on service team dogfooding env)
  - EG on K8 (testing in progress by Matt Ellis)
  - AMQP (still in design, might slip to next semester)
  - Binary support (still in design, might slip to next semester)
- ADP work in progress:
  - Work with EG PM on event update process criteria and deadline
  - Work to make event update more scalable cross-language (May)
  - Waiting on Function Extension update to track2 (talked with Pavel/Alex, it's on their radar)
  - Email in progress with Kyle to get UserAgent telemetry for the "send" endpoint
