### ISSUE TITLE
Board Review: Introducing Storage Data Movement Library (DMLib) Track 2

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk#2444]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Storage
* Main contacts: @amnguye @gapra-msft @xiafu-msft  
* Expected GA date for this library: TBD (Q3)

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-data-movement-library
* Link to the service REST APIs: N/A based on storage SDK
* Is the goal to release a Public Preview, Private Preview, or GA? Public Preview

## About the client library

* Name of client library: Azure.Storage.Blobs.DataMovement, Azure.Storage.DataMovement (TBD)
* Languages for this review: .NET, Java, Python
* Is there an existing SDK library? If yes, provide link: https://github.com/azure/azure-storage-net-data-movement

## Step 1: Champion Scenarios 

Champion scenario - Single Blob Upload:
Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L81
Champion scenario - Single SMB File Upload:
Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L117
Champion scenario - Single Blob Download Sample:
Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L200
Champion scenario - Single Download Sample:
Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L200
Champion scenario - Single Download to Stream Sample:
Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L281
* Champion scenario - Single Blob Directory Upload Sample:
   Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L348
* Champion scenario - Single Blob Directory Copy Sample:
    Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L451
 * Champion scenario - Single Blob Directory Copy Sample:
    Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L451

**Comment by lilyjma** [comment]
scheduled for 3/1

**Comment by lilyjma** [comment]
rescheduled for 3/9 2-4PM PST

**Comment by lilyjma** [comment]
[recording](https://msit.microsoftstream.com/video/9636a4ff-0400-85a8-b2b6-f1eb8133f62f)[MS INTERNAL ONLY]
