### ISSUE TITLE
Board Review: Document Translation (Python & .NET)

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk#2448]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: ADP/translation team
* Main contacts: @mayurid 
* Version: 1.0.0-beta.1
* Expected code complete date: April 2nd
* Expected release date: April 6th

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/cognitive-services/translator/document-translation/overview
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/TranslatorText/preview/v1.0-preview.1/TranslatorBatch.json
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/1968

## About the client library

* Name of the client library: azure-ai-documenttranslation, Azure.AI.DocumentTranslation
* Languages for this review: Python and .NET

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

The main points we would like to discuss are
### Design approach: LRO or non-LRO

  | LRO implementation |   | No LRO |  
-- | -- | -- | -- | --
User scenario | [.NET](https://apiview.dev/Assemblies/Review/46373cdd5bff4c86aeef03d3b8f79d50) | [Python](https://apiview.dev/Assemblies/Review/019355482c6245a5a404eef64740da1e) | [.NET](https://apiview.dev/Assemblies/Review/373de26cd8564491a4bf25442d6d1957) | [Python](https://apiview.dev/Assemblies/Review/019355482c6245a5a404eef64740da1e/4bf67430f61f483ea6508cd1267d6c74?doc=False)
Execute translation and wait until it is done (only recommended if the number and length of documents is not big)* *Service is still figuring out limits and adjusting their resources. Large documents can take up to 3 min and max number of documents allowed is 1000 | [Sample](https://github.com/maririos/azure-sdk-for-net/blob/withLro/sdk/documenttranslation/Azure.AI.DocumentTranslation/tests/samples/Sample_TranslateOperationAsync.cs) | [Sample](https://github.com/Azure/azure-sdk-for-python/blob/761b70f48d153499fd0c6f14829fdf9ec0f68c08/sdk/documenttranslation/azure-ai-documenttranslation/samples/arch-board/sample_batch_translation.py)  | [Sample](https://github.com/maririos/azure-sdk-for-net/blob/noLro/sdk/documenttranslation/Azure.AI.DocumentTranslation/tests/samples/Sample_TranslateJobAsync.cs) | [Sample](https://github.com/kristapratico/azure-sdk-for-python/blob/align-samples-for-arch/sdk/documenttranslation/azure-ai-documenttranslation/samples/sample_batch_translation.py)
Execute translation and print/get the specific document that finished the translation instead of waiting for all documents to be done | [Sample](https://github.com/maririos/azure-sdk-for-net/blob/withLro/sdk/documenttranslation/Azure.AI.DocumentTranslation/tests/samples/Sample_DocumentStatusAsync.cs) | [Sample](https://github.com/Azure/azure-sdk-for-python/blob/761b70f48d153499fd0c6f14829fdf9ec0f68c08/sdk/documenttranslation/azure-ai-documenttranslation/samples/arch-board/sample_translation_status_checks.py)  | [Sample](https://github.com/maririos/azure-sdk-for-net/blob/noLro/sdk/documenttranslation/Azure.AI.DocumentTranslation/tests/samples/Sample_DocumentStatusAsync.cs) | [Sample](https://github.com/kristapratico/azure-sdk-for-python/blob/align-samples-for-arch/sdk/documenttranslation/azure-ai-documenttranslation/samples/sample_translation_status_checks.py)
Get historic data of completed translation operations/jobs in the resource. Used for graphics/ UI interface | [Sample](https://github.com/maririos/azure-sdk-for-net/blob/withLro/sdk/documenttranslation/Azure.AI.DocumentTranslation/tests/samples/Sample_OperationsHistoryAsync.cs) | [Sample](https://github.com/Azure/azure-sdk-for-python/blob/761b70f48d153499fd0c6f14829fdf9ec0f68c08/sdk/documenttranslation/azure-ai-documenttranslation/samples/arch-board/sample_list_all_submitted_translations.py)  | [Sample](https://github.com/maririos/azure-sdk-for-net/blob/noLro/sdk/documenttranslation/Azure.AI.DocumentTranslation/tests/samples/Sample_JobsHistoryAsync.cs) | [Sample](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/documenttranslation/azure-ai-documenttranslation/samples/sample_list_all_submitted_jobs.py)

PROs to LRO:
- Established pattern in python/.NET SDKs
- We can expose the "translation status" on the poller itself and have the end result return the pageable of documents' statuses
- [Python] We can expose the batch ID as a property on poller so people are still able to pass ID into the document status checking or cancel client methods

CONs to LRO
- [Python] Keeping poller object around in very long LRO may be issue (we can implement to rehydrate with ID, but this scenario is not so easy / intuitive in python)
- Calling .result() on large job may not make sense

PROs to no-LRO
- Kicking off translation job could take a long time (Large documents can take up to 3 min and max number of documents allowed is 1000). Calling .result() on a large job may not make sense -> polling service every 30s if job will take hour(s)?
- Poller object might not be around for this long and/or user who kicked off job might not be the same person as the one checking the results of job (but can "wait until done" on ID or cancel by ID if needed)
- Ability to list all jobs (running and completed) and "wait" until finished with ID

CONs to no-LRO
- Departure from common poller pattern we use with other LROs in services
- User must poll themselves for status if they want to look at documents/progress

### Input convenience method:
Sample for complex type in .NET => https://github.com/a-noyass/azure-sdk-for-net/blob/document-translation/sdk/documenttranslation/Azure.AI.DocumentTranslation/tests/samples/Sample_TranslateOperationComplex.cs

### If time allows:
- Namespace
- Get Supported methods in or out of client

**Comment by lilyjma** [comment]
scheduled for 3/16

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/7115a4ff-0400-85a8-7585-f1eb82a49588)[MS INTERNAL ONLY]
