### ISSUE TITLE
Board Review: JS core-https new Pipeline model

### ISSUE THREAD

**Issue by xirzec** [Azure/azure-sdk#2451]
This is a review of the new Pipeline model added to the JS core. It's mostly informational for other languages, but the JS crew would love any feedback/thoughts the board has.

## Contacts and Timeline

* Responsible service team: ADP JS Crew
* Main contacts: jeffish, brterlso
* Expected code complete date: Already code complete
* Expected release date: March

## About the client library

* Name of the client library: core-https
* Languages for this review: JS

### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/cfe31fd1f2e84233affec5ccd2643a80
* Link to Champion Scenarios/Quickstart samples:   https://gist.github.com/xirzec/0a8f2ab0f15eb1419126bae7672fd569
* General README: https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/core/core-https/README.md#pipelines

**Comment by lilyjma** [comment]
scheduled for 2/24 2-3PM

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/c10fa4ff-0400-85a8-053d-f1eb76f4e5bc)[MS INTERNAL ONLY]
