### ISSUE TITLE
Board Review: Introducing BinaryData in Storage Blobs SDK (.NET, Java)

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk#2453]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: storage
* Main contacts: kasobol

## About the client library

* Name of client library: Storage Blobs SDK

### .NET
1st proposal: [APIView](https://apiview.dev/Assemblies/Review/4b2c38f32096473bb5ce573aae36c84d?diffRevisionId=c7c54da9cea649a1b9355639ed0343a7&doc=False&diffOnly=True )

2nd proposal:
```csharp
public class DownloadResponse<T> : Response<T>
{
    // public T Value { get; }
    // public Response GetRawResponse();
    public DownloadDetails Details { get; }
}
 
public class BlobBaseClient
{
    // Unchanged
    public virtual Response DownloadTo(Stream destination);
    public virtual Response DownloadTo(string path);
 
    // New
    public virtual DownloadResponse<BinaryData> DownloadData(...) { ... }
    public virtual DownloadResponse<Stream> DownloadRaw(...) { ... }
 
    // Hiding
    [EditorBrowsable(Never)]
    public virtual Task<Response<BlobDownloadInfo>> Download(...) =>
        ReshapeSlightly(DownloadRaw());
}

```

Usage:
```
BinaryData data = blob.DownloadData();
var response = blob.DownloadData();
Fruit fruit = response.Value.ToObjectFromJson<Fruit>();
ETag stillEdible = response.Details.ETag;

```

### Java
[APIView](https://apiview.dev/Assemblies/Review/aeff86082f38417bb2783dac25b9c51b?diffRevisionId=a06e1bb30b4a4f9386ba0f802b9eb1ae&doc=False&diffOnly=True)

Usage:
```java
        BlobClient blobClient;
        BinaryData data = blobClient.downloadContent();
        String dataAsString = data.toString();
        byte[] dataAsArray = data.toBytes();
        Foo dataAsFoo = data.toObject(Foo.class);
```

```java
        BlobClient blobClient;

        BlobDownloadContentResponse blobDownloadContentResponse = blobClient.downloadContentWithResponse(
            new DownloadRetryOptions(), new BlobRequestConditions(), Duration.ofSeconds(20), new Context("foo", "bar"));

        BinaryData data = blobDownloadContentResponse.getValue();
        String dataAsString = data.toString();
        byte[] dataAsArray = data.toBytes();
        Foo dataAsFoo = data.toObject(Foo.class);

        BlobDownloadHeaders downloadHeaders = blobDownloadContentResponse.getDeserializedHeaders();
        BlobType blobType = downloadHeaders.getBlobType();

```

**Comment by lilyjma** [comment]
scheduled for 3/9

**Comment by lilyjma** [comment]
rescheduled for 3/1, 2-3 PM PST

**Comment by JonathanGiles** [comment]
Using the latest BinaryData APIs, the last line in the first Java code block can change to the following:

```java
Foo dataAsFoo = data.toObject(Foo.class);
```

**Comment by tg-msft** [comment]
We should also discuss `Content-Type` as it relates to `BinaryData` and `Upload` in today's meeting.

**Comment by kasobol-msft** [comment]
The `Upload` is in the APIViews. I thought it's simple enough to not produce sample - `await blobClient.UploadAsync(BinaryData.FromString("foo"));`

**Comment by kasobol-msft** [comment]
```
public abstract class DownloadResultBase<T>
{
    public T Content { get; }
    public DownloadDetails Details { get; }
}

public class DownloadDataResult : DownloadResult<BinaryData> { }
public class DownloadRawResult : DownloadResult<Stream> { }

public class BlobBaseClient
{
    // Unchanged
    public virtual Response DownloadTo(Stream destination);
    public virtual Response DownloadTo(string path);

    // New
    public virtual Response<DownloadDataResult> DownloadData(...) { ... }
    public virtual Response<DownloadRawResult> DownloadRaw(...) { ... }

    // Hiding
    [EditorBrowsable(Never)]
    public virtual Task<Response<BlobDownloadInfo>> Download(...) =>
        ReshapeSlightly(DownloadRaw());
}
```

**Comment by kasobol-msft** [comment]
Java:
- introduce downloadStreaming
- document that download will get deprecated (but not deprecating yet)

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/cd28a1ff-0400-85a8-c7ba-f1eb7ae1e40e)[MS INTERNAL ONLY]
