### ISSUE TITLE
Board Review: Identity client side user authentication and token cache persistence

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk#2457]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Identity feature team
* Main contacts: sschaab@microsoft.com
* Expected code complete date: 3/5
* Expected release date: 3/12 (GA 4/9)

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Azure.Identity
* Languages for this review: All lanaguages

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/e397947f4107429b8613399d3cf223ab?diffRevisionId=675786f279ea4698808baed788e142c9&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples:
  * [Client side user authentication](https://github.com/christothes/azure-sdk-for-net/blob/users/chriss/TokenCache_POC/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md)
  * [Persisting the credential TokenCache](https://github.com/christothes/azure-sdk-for-net/blob/users/chriss/TokenCache_POC/sdk/identity/Azure.Identity/samples/TokenCache.md)

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/4a20c92e936b41b4913844900fd3962e?diffRevisionId=cbae7e7ae4c745fb8c1d12d050e5a65f&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/ea45744de66a40ef9674d3f692a7cd72?diffRevisionId=c1944bff3efc4b27841258d35e80172e&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples:
  * [Persisting the credential TokenCache](https://gist.github.com/schaabs/6a5ba90099550a44e26ddf944b949258)
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/a2585328b538444cb4a2b883516ffeda?diffRevisionId=7f4cc70bcbce449081104564310668bd&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 3/3 3-4PM PST

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/ec45a1ff-0400-85a8-05e1-f1eb7c7d7033)[MS INTERNAL ONLY]
