### ISSUE TITLE
Why is Microsoft.Azure.ServiceBus not marked as deprecated?

### ISSUE THREAD

**Issue by sander1095** [Azure/azure-sdk#2463]
Hello!

I have been working with some Azure SDK's but it is a bit confusing to find out which one should be used.

I need to use a servicebus and I found out 2 _modern_ SDK's exists:

- [Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/)
- [Azure.Messaging.ServiceBus](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/)

Only on [this quickstart page](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues) have I found out that the `Microsoft.*` one is old. 

Why is the old not marked as deprecated? Recently I was updating my Storage SDK's to the new `Azure.*` ones and there the old ones are deprecated:

- [Microsoft.Azure.Storage.Blob](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob) (**Deprecated**)
- [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs)

**Comment by jongio** [comment]
@AlexGhiondea @ramya-rao-a

**Comment by ramya-rao-a** [comment]
Hey @sander1095 

Thanks for sharing the feedback

The new `Azure.Messaging.ServiceBus` package does not have complete feature parity with `Microsoft.Azure.ServiceBus` yet. One of the features that we are still working on are [Cross Entity Transactions](https://github.com/Azure/azure-sdk-for-net/issues/17355). Once feature parity is reached, we start looking at the process of marking older packages with appropriate messaging pointing to the new package like how you see with Storage

cc @elraikhm

**Comment by sander1095** [comment]
Alright, thanks for your quick reply.

Might I suggest that the docs and microsoft nuget package get updated to reflect this? 

If the docs could clearly say that Azure.* is the future but there is no parity yet (and I mean this as it being displayed in a more prominent page like the introduction, instead of quickstarts) that would make it easier to discover!

If the package also says this we could prevent users from setting up the old package and then getting a deprecation warnings a few months later. 

This comment goes for all sdk's that were first a Microsoft.* Package and now an Azure.* Package :)!

**Comment by sander1095** [comment]
And perhaps a quick OT question: how would I peek multiple messagea of a  DLQ of a queue with the new Azure package? First of all, I cant find the FormatDeadLetterPath method from the old package, and secondly, if I just append "/deadletter" (or whatever the right bit of text was, i am on my phone currently) I get an error (which I sadly currently also cant show because I am on my phone).

**Comment by ramya-rao-a** [comment]
>If the docs could clearly say that Azure.* is the future but there is no parity yet (and I mean this as it being displayed in a more prominent page like the introduction, instead of quickstarts) that would make it easier to discover!

> If the package also says this we could prevent users from setting up the old package and then getting a deprecation warnings a few months later.

That definitely sounds helpful

Looping in @elraikhm who is currently working on the process of marking packages deprecated and what kind of messaging should be used at what time

> how would I peek multiple messagea of a DLQ of a queue with the new Azure package

You would create a receiver as usual using the `ServiceBusClient.CreateReceiver()` method, but pass in the sub queue type in the [options](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceiveroptions?view=azure-dotnet). This reminds me that we should add this to our migration guide. Logged https://github.com/Azure/azure-sdk-for-net/issues/18921

**Comment by sander1095** [comment]
Thank you very much! You're super helpful!

Perhaps we could also mention this migration guide in the docs? Perhaps as a new "high level" page? 

My experience so far is that the docs and github repo sometimes are a bit out of sync. I'd always check the docs first but I never saw something about a migration guide, if this was mentioned in the docs that would be good too?

**Comment by ramya-rao-a** [comment]
Looping in @spelluru who manages our pages in docs.microsoft.com

@spelluru, perhaps we can use that "Important" section to include a note on the migration guide?

![image](https://user-images.githubusercontent.com/16890566/108759682-857e5c00-7501-11eb-9ac0-42c92f6077fa.png)

**Comment by spelluru** [comment]
@ramya-rao-a - Sure. I will add a link to the migration guide in this note. Thanks.
