### ISSUE TITLE
Board Review: Introducing <Unified Language CogS>

### ISSUE THREAD

**Issue by nawanas** [Azure/azure-sdk#2468]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Language Cognitive Service
* Main contacts: Nayer Wanas (nayer.wanas@microsoft.com)
* Expected GA date for this library: 10/21

## About the Service 

* Link to documentation introducing/describing the service: [QuestionAnsweringTrack2SDK.docx](https://microsoft.sharepoint.com/:w:/t/QnAMaker27/EQjkyybYDWtEghGtd0bwn14Bn_xr9ZNmZZA9_0vlGTLcsQ?e=YDqKUf)

* Link to the service REST APIs: [QNAMaker](https://github.com/Azure/azure-rest-api-specs/blob/772c440159d9ab5775c80e304f7e803cae84aa7d/specification/cognitiveservices/data-plane/QnAMaker/preview/v5.0-preview.1/QnAMaker.json#L687)
* 
* Is the goal to release a Public Preview, Private Preview, or GA? Private Preview in build 21

## About the client library

* Name of client library: Text Analytics
* Link to library reference documentation:
* Is there an existing SDK library? If yes, provide link: yes, [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/textanalytics/Azure.AI.TextAnalytics)

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
4. How does the **authentication** workflow look? 
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1
    * Customer support agent assist: NL insights can play a major role in helping enterprises deliver enhanced customer service. Language service capabilities built into contact center solutions for example, can assist customer support agents with real time insights from knowledge bases and provide multi-lingual support to identify intents and entities from multi-lingual speakers. Our capabilities can also help contact center administrators with real-time insights into customer call sentiment to mitigate customer issues quickly. 

* Champion scenario 2
    * In an Enterprise setting, a developer would want to categorize an incoming short text (such as emails, social feeds, etc..), identify key phrases and extract entities (generic, custom or compounded) to automate backend processes. 
    
* Champion scenario 3
    * An enterprise running a social media campaign/chatbot is interested to identify and understand the responses from their users through getting the sentiment and opinions on their products for visualization and analyze deeper the  customer issues to continue to improve their products/chatbot. 

* Champion scenario 4
    * Enterprise interested in processing its legal documents and contracts to identify sections and chuck the documents in to logical segments, identify key elements through extracting important clauses defining policies, categorize and tag the document to compare and search through the document set to find the answer to a question. 

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 

* Create a new resource
* Read the resource
* Modify the resource
* Delete the resource
* Error handling 
* Handling race conditions/concurrency issues

**Comment by deyaaeldeen** [comment]
I wonder whether this was discussed at all. If so, do we have a recording?
