### ISSUE TITLE
Discuss autogenerated APIView approval workflow

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk#2469]
Discuss about automatic approval workflow and use cases based on the suggestions from previous arch board meeting

**Comment by lilyjma** [comment]
scheduled for 2/24 3-4pm

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/bd0da1ff-0400-85a8-a107-f1eb76fcfe38)[MS INTERNAL ONLY]
