### ISSUE TITLE
Investigate whether ACR errors will fit into the standard API paradigm

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#2479]
The different Tier-1 languages handle errors slightly differently:
- .NET is the most different: https://azure.github.io/azure-sdk/dotnet_introduction.html
- Java, Python, and JS/TS all have error hierarchies (IIRC)

We'll want to look through the possible errors returned by each operation and understand whether the existing patterns for Track 2 libraries will work for ACR, or whether any additional design work will be needed (for example, will we want to keep the AcrErrors and AcrErrorInfo types or use standard Azure SDK types?  Do these follow the standard [MS REST API convention for errors](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses), and if so, is there anything common we can use from Azure.Core?

**Comment by annelo-msft** [comment]
@AlexGhiondea FYI

**Comment by AlexGhiondea** [comment]
@seankane-msft could you take a look at this?

**Comment by AlexGhiondea** [comment]
Closing this as we did the investigation and we believe we can correctly map the service errors to our Track 2 error model.
