### ISSUE TITLE
Work out Track 2 implementation of client-internal ACR auth flows

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#2480]
In our ACR libraries, we'll need to handle:
- Authentication with AAD
- Authentication with Admin username and password
- Anonymous access

These have largely been designed for the public API: https://apiview.dev/Assemblies/Review/ba57bf904e524ce3bf647dad124ddc7c
But what hasn't been done is working out the HTTP pipeline policies we'll need for ACR's challenge-based authentication, and no one has yet implemented a library with functional authentication in any language.

We'd like to let one language create the first implementation in a Track 2-compliant way, so each of the other languages can mostly copy them for efficiency.

Resources:
- ACR Service Auth Docs: https://github.com/Azure/acr/blob/main/docs/AAD-OAuth.md
- Anne's best-effort at a [sequence diagram of ACR's AAD auth flow](https://mermaid.ink/img/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgQUNSXG4gICAgcGFydGljaXBhbnQgQ2xpZW50XG4gICAgcGFydGljaXBhbnQgU1RTXG4gICAgXG4gICAgQ2xpZW50LT4-U1RTOiBQT1NUIC9vYXV0aDIvZXhjaGFuZ2UgPGJyPiBncmFudF90eXBlPWFjY2Vzc190b2tlbiA8YnI-IHNlcnZpY2U9PGFjcj4uYXp1cmVjci5pbyA8YnI-IHRlbmFudD08dGVuYW50X2lkPiA8YnI-IGFjY2Vzc190b2tlbj08YWFkX2FjY2Vzc190b2tlbj5cbiAgICBTVFMtPj5DbGllbnQ6IDIwMCBPSyA8YnI-IHJlZnJlc2hfdG9rZW49PGFjcl9yZWZyZXNoX3Rva2VuPlxuXG4gICAgQ2xpZW50LT4-QUNSOiBHRVQgLzxyZWdpc3RyeT4vdjIvX2NhdGFsb2dcbiAgICBBQ1ItPj5DbGllbnQ6IDQwMSBVbmF1dGhvcml6ZWQgPGJyPiBXd3ctQXV0aGVudGljYXRlOiBCZWFyZXIgPGJyPiByZWFsbT1odHRwczovLzxhY3I-L29hdXRoMi90b2tlbjxicj4gc2VydmljZT08YWNyPiA8YnI-IHNjb3BlPXJlZ2lzdHJ5OmNhdGFsb2c6KlxuICAgIENsaWVudC0-PlNUUzogUE9TVCAvb2F1dGgyL3Rva2VuIDxicj4gZ3JhbnRfdHlwZT1yZWZyZXNoX3Rva2VuIDxicj4gc2VydmljZT08YWNyPiA8YnI-IHNjb3BlPXJlZ2lzdHJ5OmNhdGFsb2c6KiA8YnI-IHJlZnJlc2hfdG9rZW49PGFjcl9yZWZyZXNoX3Rva2VuPlxuICAgIFNUUy0-PkNsaWVudDogMjAwIE9LIDxicj4gYWNjZXNzX3Rva2VuPTxhY3JfYWNjZXNzX3Rva2VuPlxuXG4gICAgQ2xpZW50LT4-QUNSOiBHRVQgLzxyZWdpc3RyeT4vdjIvX2NhdGFsb2cgPGJyPiBBdXRob3JpemF0aW9uOiBCZWFyZXIgPGFjcl9hY2Nlc3NfdG9rZW4-XG4gICAgQUNSLT4-Q2xpZW50OiAyMDAgT0sgPGJyPiB7IFwicmVwb3NpdG9yaWVzXCIsIFwiaGVsbG8td29ybGRcIiwgXCI8aW1hZ2UyPlwiIH1cbiAgICBcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9).
- The Docker auth flow that ACR implements: https://docs.docker.com/registry/spec/auth/token/

Existing Azure SDK work on Challenge-Based Auth:
- **Java** https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-experimental/src/main/java/com/azure/core/experimental/http/policy/BearerTokenAuthenticationChallengePolicy.java
- **.NET** https://github.com/Azure/azure-sdk-for-net/pull/19215

**Comment by annelo-msft** [comment]
@AlexGhiondea  FYI

**Comment by AlexGhiondea** [comment]
@pallavit could you take a look at this?

**Comment by AlexGhiondea** [comment]
Closing this as @pallavit did a great job getting the auth flow figured out!
