### ISSUE TITLE
Board Review: LVA Typescript review 

### ISSUE THREAD

**Issue by hivyas** [Azure/azure-sdk#2481]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: LVA Azure Media Services
* Main contacts: Girish Akasapu giakas@microsoft.com, Himani Vyas hivyas@microsoft.com
* Expected code complete date: 2/25
* Expected release date: 3/12

## About the Service 

* Link to documentation introducing/describing the service: https://azure.microsoft.com/en-us/services/media-services/live-video-analytics/
* Link to the service REST APIs: n/a This is a models only sdk
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/2131

## About the client library

* Name of the client library: media-analytics-edge
* Languages for this review: Typescript

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/c775a4d7552f40c6a94f45a2493978e6
* Updated APIView Link: https://apiview.dev/Assemblies/Review/16efd85fc34b4df4b471be0142a39cb1
* Link to Champion Scenarios/Quickstart samples: https://github.com/hivyas/azure-sdk-for-js/blob/c1aa4d9836b7b3851b4ba7b11925e96df239e518/sdk/videoanalyzer/media-video-analyzer-edge/samples/typescript/src/lvaInvokeModuleSample.ts

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

Some context from @JeffreyRichter (Also included in [last review](https://github.com/Azure/azure-sdk/issues/2131) )

> I think their best architectural choice is to define some JSON payloads in some language (like Swagger) and then they want model types generated.
> Customers can then create the model type in their language of choice, initialize it, and then pass it (or perhaps the JSON-serialized version of it to a function that already exists the IOT client libraries to send the JSON payload to iot hub.
>  
> Their SDK doesn’t perform any I/O operations at all. They just want to simply the creation/parsing of JSON payloads that get passed to/from iot hub using already-existing functionality.
>  
> One of the reason [...] suggesting this approach is because of dependency conflicts. If a customer wants to use Version x.y of the IoT Devices library, and if we have a dependency on a.b version of devices library, that will cause issues to the customer, so he is suggesting we don't have any dependency on Devices library and let customer use IoT SDK to make direct method calls, and we support helper methods to construct the body for direct method.

**Comment by hivyas** [comment]
@lilyjma Hi there, was wondering if we could schedule a time to meet with the review board

**Comment by lilyjma** [comment]
scheduled for 3/24

**Comment by hivyas** [comment]
@lilyjma Hey looks like there are some changes happening to our swaggers in the next couple weeks so it makes sense to release this sdk a bit later. Can we please reschedule this a bit further out?

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/92e5a3ff-0400-94b1-cf65-f1eb9330b4b5?referrer=https:%2F%2Fstatics.teams.cdn.office.net%2F) [MS INTERNAL ONLY]
Due to outage, only 17 min of the meeting was recorded :(
