### ISSUE TITLE
Board Review: Models Repository SDK for .NET

### ISSUE THREAD

**Issue by azabbasi** [Azure/azure-sdk#2483]
Requesting an architectural review for a client library that targets a preview Azure SDK.

## Contacts and Timeline

* Responsible service team: Azure Models Repository
* Main contacts: Paymaun.Heidari@microsoft.com, azabbasi@microsoft.com
* Expected code complete date: 2021_03_03
* Expected preview release date: 2021_03_05 if no significant API changes are required.

## About the Service 

* Link to documentation introducing/describing the service: 
        - https://docs.microsoft.com/en-us/azure/iot-pnp/concepts-model-repository
        - https://github.com/Azure/azure-iot-digitaltwin-libraries
        - https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet
* Link to the service REST APIs: N/A - No swagger document
* Link to GitHub issue for previous review sessions, if applicable:  N/A

## About the client library

* Name of the client library: Azure.Iot.ModelsRepository
* Languages for this review: .NET

### .NET

* APIView Link: 
    - https://apiview.dev/Assemblies/Review/0ab580f8c9094794a38449ec5c08762c
* Link to Champion Scenarios/Quickstart samples: 
    - https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/modelsrepository/Azure.Iot.ModelsRepository/samples

**Comment by lilyjma** [comment]
scheduled for 3/8 2-4pm

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/a60fa4ff-0400-85a8-1967-f1eb80631f6a?referrer=https:%2F%2Fstatics.teams.cdn.office.net%2F)[MS INTERNAL ONLY]
