### ISSUE TITLE
Add a Spring Tab to the Java Releases Page

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk#2506]
Spring is one of the most popular frameworks in the Java ecosystem and Azure SDK releases libraries supporting it. Due to this we should make it easier to find and list all the libraries released supporting Spring. So, the [Java releases](https://azure.github.io/azure-sdk/releases/latest/java.html) page should have another tab added alongside `Client Libraries`, `Management Libraries`, and `All` called `Spring Libraries` containing all Spring libraries Azure SDK releases in an easy to view list.

**Comment by weshaggard** [comment]
@samvaity and I chatted about this one and at the time I suggested we avoid it unless we find that it is valuable enough to make a special case for it. If you guys feel it is interesting then we can add it. Pull requests appreciated :)

**Comment by lfraleigh** [comment]
Spring libraries are now listed on the page (and can be easily searched).
