### ISSUE TITLE
Doc-Warden: Support content RegEx checks

### ISSUE THREAD

**Issue by docs-product** [Azure/azure-sdk#251]
This request covers the need to include rules about the content of the README files. For example, if we need to define rules for checking links to be absolute and not relative, this would go beyond header constraints.

Additional rules that we might want to include:

* Image definitions need to have `alt` text.
* Code snippets need to have a colorizer defined.

**Comment by scbedd** [comment]
@dendeli-msft Code snippets need to have a colorizer defined.

When you talk about `Code snippets` do you mean something along the lines of what I found [here.](https://raw.githubusercontent.com/MicrosoftDocs/azure-docs-sdk-python/master/docs-ref-conceptual/python-sdk-azure-samples-monitor-vms.md)

```
```python
import datetime

# Get the ARM id of your resource. You might chose to do a "get"
# using the according management or to build the URL directly
# Example for a ARM VM
... rest of markdown
```
