### ISSUE TITLE
Extend "Resolve Queuing User" to eliminate any extraneous identifiers.

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#2510]
During [this release](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=766482&view=logs&j=464b686b-5c11-57e4-a7e5-38206fa0be76&t=e6ad5839-92e0-5a1f-2576-d3e5e6dd2de4) we were unable to resolve the AAD Identity `Richard Park (DEVDIV)` to the appropriate github identity in the `employeelink` kusto table.

This is likely caused by the fact that the `Name` in the lookup table does not include the `(DEVDIV)` suffix. We should see about omitting this type of content from the request to the kusto table.

**Comment by weshaggard** [comment]
I hope this can be resolved once we switch away from direct Kusto queries.

**Comment by kurtzeborn** [comment]
The same solution should fix this and https://github.com/Azure/azure-sdk-tools/issues/1169

**Comment by kurtzeborn** [comment]
It's also likely that once https://github.com/Azure/azure-sdk/issues/2470 is fixed, this issue will be obsolete.
