### ISSUE TITLE
Board Review: Improved error handling for Track 2 client libraries (Tier 1)

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk#2517]
## Contacts and Timeline

* Service team responsible for the client library: **ADP**
* Main contacts: @tg-msft 
* Expected GA date for this library: **this semester**

## About the Client Library

* Name of client library: **Azure.Core and Azure.Storage.Blobs** (to start, but eventually everything)

  We want to improve the developer experience around handling errors returned from Azure services by
  * linking customers directly to troubleshooting guides,
  * proactively communicating what might go wrong in their code, and
  * making it easier to write correct, robust applications with declarative error handling.

* Updates and resources will be collected at https://aka.ms/azsdk/errors

## Optional Background Reading
While not required, the following material provides helpful background context.
- Joe Duffy's [The Error Model](http://joeduffyblog.com/2016/02/07/the-error-model/) blog post describing lessons learned from Midori _(estimated 90 minute read)_
- [_Transaction Processing_](https://www.amazon.com/Transaction-Processing-Concepts-Techniques-Management/dp/1558601902) chapter 3 or [_Designing Data-Intensive Applications_](https://www.amazon.com/Designing-Data-Intensive-Applications-Reliable-Maintainable/dp/1449373321) chapter 8 for a primer on failures in distributed systems

## Champion Scenarios
1. Tell customers how to fix errors
2. Show customers what errors might happen
3. Declarative error handling

Here are the [ApiView listing](https://apiview.dev/Assemblies/Review/a61d7b9446eb4aaeb9afc9cf408098a2?diffRevisionId=979ebc8a94b640db8469691490b578e6&doc=False&diffOnly=True) and [Champion Scenarios](https://gist.github.com/tg-msft/396d6e1a432b067a16c8c368c3446a80) for RecoverableAction, but the board review is about the end to end experience rather than sign off on these APIs.

**Comment by lilyjma** [comment]
scheduled for 3/18

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/fb45a1ff-0400-85a8-af1f-f1eb8b606ec5)[MS INTERNAL ONLY]
