### ISSUE TITLE
Smoke Tests and Aggregate Reports should have a way to configure who gets failure notifications

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#2525]
Ideal outcome: we have a folder in the CODEOWNERS file that people can add their GitHub ID to and subscribe to the failure notifications.  This would mirror how @danieljurek set up the failure notifications for all the other live test pipelines.

**Comment by danieljurek** [comment]
Assigning to @weshaggard who can close this. it was addressed in his PR -- https://github.com/Azure/azure-sdk-tools/pull/1749

**Comment by weshaggard** [comment]
Yes the support is there and I have added owners for the aggregate-reports pipelines, I believe we already added them for smoke-tests before.
