### ISSUE TITLE
Update Generate-ReleaseNotes.ps1 logic

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk#2539]
Update `Generate-ReleaseNotes.ps1` logic to include the following features.
- [x] Prevent duplicate entries in the `GA`, `Updates` and `Beta` sections of the `releases/yyyy-MM/{Language}.md` files.
- [x] Sort package listings in each of the release notes sections.
- [x] Collect Changelog from branches other than master.
     - [x] Merge `generate-releasenotes.yml` into `version-updater.yml`
     - [x] Pull changelogs directly from GitHub using the information from the version updater.
- [x] Pull specific sections as shown in the https://azure.github.io/azure-sdk/policies_releases.html#change-logs
- [x] Packages released in the second half of the day (after 12:30PM) are not picked up due to how `lastupdated` date is set on every run. Fix this logic to ensure that all the packages released is always picked up.
- [x] Run the update automation more often, especially during release week. 
- [x] Feature request: Group the packages by Service
- [x] If there is not existing Release PR, automation should delete existing `CreateOrUpdateReleaseNotesFor` branch for that language.

**Comment by weshaggard** [comment]
These are all done now.
