### ISSUE TITLE
Change Request: REST Models for C++

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk#2565]
### Update the C++ Guidelines for Model types

- Optional query parameters & request headers are in an XxxOptions struct and all fields are nullable.
  - If passing null or the default value results in the same service behavior, the field can be by-value

- Response headers in the “base version” are in a model as value types.
  - Autorest Reality: These are all nullable
  - If the service returning null is semantically equivalent to the field’s default value, the field can be by-value

- Response headers added after the “base version” are nullable.
  - Autorest Reality: These are all nullable
  - If passing null or the default value results in the same service behavior, the field can be by-value

- Input-only bodies mandatory fields are by value; optional fields and nullable.
  - Autorest Reality: We can do this: Mandatory fields are defined by “required” swagger 

- Output-only bodies always-returned fields are by-value; optional fields and fields introduced after the “base version” are nullable.
  - Autorest Reality: We can do this: Optional fields are defined by “ms-x-nullable” autorest extension; in Go, we made everything nullable

- Input/output bodies:
  - If PATCH with JSON Merge Patch; then all fields are nullable.
    - NOTE: If PATCH isn’t there today but is added in the future, this breaks! 
  - If PATCH not supported (and never will be) then fields in the “base version” that are always required on input and returned on output are by-value; otherwise nullable.
    - Autorest Reality: We can do this: autorest modeler returns this information. In Go, all fields are nullable.

“base version”: Lowest api-version supported by the client library.

**Comment by katmsft** [comment]
Storage is choosing 2019-07-07 as the base version for now.
