### ISSUE TITLE
Board Review: Azure IoT Models Repository Client (Python)

### ISSUE THREAD

**Issue by cartertinney** [Azure/azure-sdk#2569]
## Contacts and Timeline

* Responsible service team: Azure IoT Portal & UX
* Main contacts:
    * Developer: carter.tinney@microsoft.com
    * Product Manager: ricardo.minguez@microsoft.com
    * Dev Lead: paymaun.heidari@microsoft.com
* Expected code complete date: March 17 2020
* Expected release date: (Unknown - This is a preview version of a package)

## About the Service 

* Link to documentation introducing/describing the service: N/A
* Link to the service REST APIs: N/A
* Link to GitHub issue for previous review sessions, if applicable:  N/A

## About the client library

* Name of the client library: Azure Iot Models Repository (azure-iot-modelsrepository)
* Languages for this review: Python

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/d043acebf7b7407fb4533d9814d1e334
* Link to Champion Scenarios/Quickstart samples: [Link to samples](https://github.com/cartertinney/azure-sdk-for-python/tree/master/sdk/iot/azure-iot-modelsrepository/samples)
* PR: https://github.com/Azure/azure-sdk-for-python/pull/17180

**Comment by lilyjma** [comment]
reviewed with Java library 3/29
