### ISSUE TITLE
Planning for moving Azure SDK Training into the SDK Guidelines

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#2584]
Make a plan of action for moving implementation and testing sections of the Azure SDK training into the SDK Guidelines.

Will likely include:
- Convert tutorials to "docs" form
- Fill content gaps in implementation (i.e. more pages like the cross-language pageable page that explains the guideline concept and links to track 2 implementations to copy)
- Unify with existing implementation and testing documentation in the language repos.

**Comment by backwind1233** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [shi](https://trello.com/c/K73ZqGO1/8-shi)
