### ISSUE TITLE
[ACR] List of questions/topics to discuss with ArchBoard

### ISSUE THREAD

**Issue by jeremymeng** [Azure/azure-sdk#2588]
1. when sending PATCH request with an empty body to update repository properties. The service return back an error
![image.png](https://images.zenhubusercontent.com/5c51efcef73cf865af8994d5/7573b955-dfc4-46d4-826c-79430c362aae)
 would it be helpful to provide a better error in SDK libraries? Concern: general guideline recommends against validating service parameters because there might be service behavior change in the future.

**Comment by AlexGhiondea** [comment]
@jeremymeng for #1 any reason to not follow the guidelines?

**Comment by jeremymeng** [comment]
@AlexGhiondea I feel the error message could be more specific in this case.

**Comment by annelo-msft** [comment]
@jeremymeng, Krzysztof has suggested for other libraries in the past that we can rewrite error messages in our client libraries to improve the customer experience.  Is that something you could do in TS as well?

**Comment by AlexGhiondea** [comment]
@jeremymeng that makes sense -- we can consider this as a fit and finish item to improve the error message!

**Comment by jeremymeng** [comment]
no longer applies
