### ISSUE TITLE
Board Review: Storage Blob Go SDK

### ISSUE THREAD

**Issue by zezha-msft** [Azure/azure-sdk#2596]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Storage
* Main contacts: zezha
* Expected code complete date: 04/30
* Expected release date: 05/14

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/storageservices/operations-on-blobs
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: azblob
* Languages for this review: Golang

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Golang

* APIView Link: https://apiview.dev/Assemblies/Review/42d4c83ec51242129d9808b39e99732f
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-go/blob/track2-storage/sdk/storage/azblob/zt_examples_test.go

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 4/7

**Comment by lilyjma** [comment]
rescheduled to 4/14

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/f6bf0840-98dc-94b1-0856-f1eb9d58c256)[MS INTERNAL ONLY]
