### ISSUE TITLE
Board Review: Models Repository SDK for Java

### ISSUE THREAD

**Issue by azabbasi** [Azure/azure-sdk#2604]
Requesting an architectural review for a client library that targets a preview Azure SDK.

## Contacts and Timeline

* Responsible service team: Azure Models Repository
* Main contacts: Paymaun.Heidari@microsoft.com, azabbasi@microsoft.com
* Expected code complete date: 2021_03_23
* Expected preview release date: 2021_03_30 if no significant API changes are required.

## About the Service 

* Link to documentation introducing/describing the service: 
        - https://docs.microsoft.com/en-us/azure/iot-pnp/concepts-model-repository
        - https://github.com/Azure/azure-iot-digitaltwin-libraries
        - https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet
* Link to the service REST APIs: N/A - No swagger document
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/2483

## About the client library

* Name of the client library: azure-iot-modelsrepository
* Languages for this review: Java

### Java

* APIView Link: 
    - https://apiview.dev/Assemblies/Review/06d793070da448cfa88598049efbcb35
* Link to Champion Scenarios/Quickstart samples: 
    - https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/modelsrepository/azure-iot-modelsrepository/src/samples

**Comment by lilyjma** [comment]
scheduled for 3/29

**Comment by srnagar** [comment]
Recording available here - https://msit.microsoftstream.com/video/92e5a3ff-0400-94b1-21ef-f1eb90e150a8
