### ISSUE TITLE
Run Managed HSM tests only in the weekly pipeline

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk#2618]
After we GA the Key Vault SDK introducing support for Managed HSM (service version 7.2, most SDK versions 4.2) we should consider running Managed HSM tests weekly only. Managed HSMs are particularly expensive and if we're not making frequent changes, we probably don't need to run these nightly.

/cc @benbp

**Comment by kurtzeborn** [comment]
We now have support for weekly pipelines, so if you have the tests ready to go, you now have a place to run them.  Please work with @benbp to get any questions you have answered about how to do this.

**Comment by benbp** [comment]
@kurtzeborn We already run HSM tests in the weekly. This issue is a reminder to remove them from the nightly after release to reduce our azure spend.

**Comment by benbp** [comment]
This issue title could probably be slightly changed to reflect ^^
