### ISSUE TITLE
Board Review: LLC first preview for Purview and Document Translator

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#2640]
As part of the first preview releases for Purview and Document Translator as LLC, we want to make an archboard to review what we are about to release and discuss if it meets the bar for the first release.

This will cover C#/Java/TS/Python, though Document Translator for Py/C# is NOT tied to any release, but pure LLC consistent discussion (they have their own release with conveninence layer).

### .NET

* APIView Link Purview Scanning: https://apiview.dev/Assemblies/Review/33a53748d3554822b348523449e74a33
* APIView Link Purview Catalog: https://apiview.dev/Assemblies/Review/1315a4d5cf1943f2b349c6cc40d2568f
* APIView Link Document Translator LLC:  https://apiview.dev/Assemblies/Review/881fbc79c5c14ac3b611d03d8cf4373d
* .NET Design: https://gist.github.com/KrzysztofCwalina/e3419dcc74d5d087ed6cfba843a0d71f

### Java

* APIView Link Purview Scanning: https://apiview.dev/Assemblies/Review/44b87f07449245d19bd12e56a340b3cc
* APIView Link Purview Catalog: https://apiview.dev/Assemblies/Review/d53f033c685d48f0b17be0473a82302d
* APIView Link Document Translator LLC: https://apiview.dev/Assemblies/Review/48a39946f7844fb49359c42f17904487
* Java Design: https://gist.github.com/jianghaolu/c07c06db9251077b5fd42a933916aff7

### Python

* APIView Link Purview Scanning: https://apiview.dev/Assemblies/Review/6abafb3120fb4063b09df0f2303a4ef9
* APIView Link Purview Catalog: https://apiview.dev/Assemblies/Review/a27d09d22cd645c88074035a88aa5fd7
* APIView Link Document Translator LLC: https://apiview.dev/Assemblies/Review/f5b60eff158941d4802f9e4a5bd3baec
* Sphinx docs: https://github.com/iscai-msft/azure-sdk-for-python/releases/tag/purviewllc
* General Python LLC docs: https://github.com/iscai-msft/azure-sdk-for-python/wiki/Low-Level-Client
  
### TypeScript

* APIView Link Purview Scanning: https://apiview.dev/Assemblies/Review/4be173241acc4e76957d748bfcd02556
* APIView Link Purview Catalog: https://apiview.dev/Assemblies/Review/05c3319a58124e0ca8a0390df7b26883
* APIView Link Document Translator LLC: https://apiview.dev/Assemblies/Review/745c3080cfda44cca14c17ca39e1d366
* Typedocs: https://github.com/joheredi/azure-sdk-for-js/releases/tag/docs
* General Typescript LLC docs (WIP): https://github.com/joheredi/azure-sdk-for-js/wiki/Rest-Level-Client

**Comment by lilyjma** [comment]
scheduled for 4/7

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/12860840-98dc-94b1-bc0e-f1eb97f63522?referrer=https:%2F%2Fstatics.teams.cdn.office.net%2F)[MS INTERNAL ONLY]
