### ISSUE TITLE
Board Review: Introducing Confidential Ledger

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk#2646]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Azure Confidential Ledger
* Main contacts: lyshi@microsoft.com
* Expected GA date for this library: December 2021

## About the Service 

* Link to documentation introducing/describing the service: Azure Confidential Ledger is a confidential computing service running in SGX enclaves that provides customers with an immutable, tamper-proof ledger for saving data. Write transactions, once durably saved to the ledger, may be cryptographically verified with a receipt at any time. The service is built on Microsoft Research's [Confidential Consortium Framework](https://microsoft.github.io/CCF/main/overview/index.html).
* Link to the service REST APIs:  https://github.com/Azure/azure-rest-api-specs/pull/13613
* Is the goal to release a Public Preview, Private Preview, or GA? Public Preview

## About the client library

* Name of client library: azure-confidential-ledger
* Link to library reference documentation: N/A
* Is there an existing SDK library? If yes, provide link: No

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
4. How does the **authentication** workflow look? 
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1: Writing to the Ledger, retrieving previously written data, and getting a receipt for past writes.
The customer has a service that is producing logs they wish to store in an immutable, tamper-proof manner. When they have a log entry to emit, they call the Confidential Ledger service (`POST /app/transactions`) with said data. The service returns a value in the header, `x-ms-ccf-transaction-id`, that indicates when the write will be durably saved to the ledger. The customer may continue writing ledger entries, or poll the Confidential Ledger service until the previous write becomes durable. Durably written data may be retrieved at any time with `GET /app/transactions/{transactionId}`.
```
# The TLS certificate for Confidential Ledger is self-signed, so we retrieve the certificate from the Identity Service to use for HTTPS verification in the ConfidentialLedgerClient.
identity_service_client = IdentityServiceClient()
ledger_identity = identity_service_client.get_ledger_identity(ledger_id)

confidential_ledger_client = ConfidentialLedgerClient(url=ledger_url, tls_certificate=ledger_identity.tls_certificate, credential=ConfidentialLedgerCertificateCredential("/path/to/client/cert.pem"))  # Here, we use cert-based mutual TLS authentication.
write_response = confidential_ledger_client.append_to_ledger("Hello World")

confidential_ledger_client.wait_until_durable(write_response.transaction_id)  # Blocking call
assert confidential_ledger_client.get_ledger_entry(write_response.transaction_id).contents == "Hello World"

receipt = confidential_ledger_client.get_receipt(write_response.transaction_id).receipt
# The receipt may be parsed and validated as described here: https://microsoft.github.io/CCF/main/use_apps/verify_tx.html#transaction-receipts
```

* Champion scenario 2: Manage users for the ledger.
An Administrator user, added via ARM at the time of Confidential Ledger creation, may `GET/PATCH/DELETE` other users. New users may have the following roles: Reader (read-only), Contributor (read-write), Administrator (read-write and modify users).
```
identity_service_client = IdentityServiceClient()
ledger_identity = identity_service_client.get_ledger_identity(ledger_id)

admin_client = ConfidentialLedgerClient(url=ledger_url, tls_certificate=ledger_identity.tls_certificate, credential=ConfidentialLedgerAadCredential(admin_aad_object_id)  # Clients may also authenticate with the Confidential Ledger using AAD Bearer tokens.

# User IDs may be the following:
#   1. AAD Object Id
#   2. PEM certificate fingerprint
admin_client.patch_user(reader_object_id, ConfidentialLedgerUserRole.READER)
admin_client.patch_user(contributor_cert_fingerprint, ConfidentialLedgerUserRole.CONTRIBUTOR)

# Now, clients that authenticate with the user identity `reader_object_id` can read, and clients that authenticate with a certificate matching `contributor_cert_fingerprint` may read and write.

admin_client.get_user(contributor_cert_fingerprint)  # Get details about this user.
admin_client.delete_user(contributor_cert_fingerprint)  # Revoke permissions for this user.
```

* Champion scenario 3: Validate details about the Confidential Ledger.
Since the Confidential Ledger's TLS certificate is self-signed, a customer might want to validate information about the Ledger before writing data. Details we make available at the moment include [enclave quotes](https://microsoft.github.io/CCF/main/use_apps/verify_quote.html), [consortium members](https://microsoft.github.io/CCF/main/governance/index.html) (identities with permissions to modify the Confidential Ledger, such as adding nodes to the Ledger or upgrading the enclave code), and the [constitution](https://microsoft.github.io/CCF/main/overview/constitution.html) (a script run in the Confidential Consortium Framework that assesses member actions).
```
identity_service_client = IdentityServiceClient()
ledger_identity = identity_service_client.get_ledger_identity(ledger_id)

confidential_ledger_client = ConfidentialLedgerClient(url=ledger_url, tls_certificate=ledger_identity.tls_certificate, credential=ConfidentialLedgerCertificateCredential("/path/to/client/cert.pem"))

enclave_quotes = confidential_ledger_client.get_enclave_quotes()  # type: List[EnclaveQuote]
for quote in enclave_quotes:
    # Code to validate the quote
    pass

constitution = confidential_ledger_client.get_constitution()
print(constitution.script)

consortium = confidential_ledger_client.get_consortium()
for member in consortium.members:
    print(member.certificate)
```

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 

* Create a new resource
* Read the resource
* Modify the resource
* Delete the resource
* Error handling 
* Handling race conditions/concurrency issues

**Comment by lilyjma** [comment]
scheduled for 4/8

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/12860840-98dc-94b1-98be-f1eb98ba1b7e)[MS INTERNAL ONLY]
