### ISSUE TITLE
Upload Relevant Artifacts to GitHub Release Automatically

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#265]
Right now, we examine the artifacts to figure out what `<packagename>_<packageversion>` tag to create. 

In addition to this, we should also upload the artifacts as a post step to each releases's creation.

**Comment by scbedd** [comment]
Progress is stored at tag `artifact-upload-progress-marker` as part of the `scbedd/release-testing` repository. Direct link to [progress](https://github.com/scbedd/release-testing/blob/b4ef987d31496b393e6157f5fadb05b1e2e61d6d/eng/create_tags_and_git_release.ps1)

**Comment by kurtzeborn** [comment]
After talking to the architecture board, we decided not to put any artifacts in the GitHub release.  The one lingering possibility was the browser bundle .zip file, but we've decided not to release that in this manner either.  If we ever have something that we need to release in this manner (attached to GitHub releases) in the future, we can revisit this.
