### ISSUE TITLE
Board Review: Azure.Security.Attestation - C#

### ISSUE THREAD

**Issue by LarryOsterman** [Azure/azure-sdk#2652]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Microsoft Azure Attestation
* Main contacts: Larry Osterman (LarryO), Anil Bazaz 
* Expected code complete date: 4/15/2021
* Expected release date:5/4/2021 (May SDK release)

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/attestation/
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/attestation/
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Microsoft Azure Attestation
* Languages for this review:C#

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/b117b54c7e254957ac125800419bde88/7ccc874dc92547bf935bd1d5b72671ad?doc=False
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/attestation/Azure.Security.Attestation

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 4/19 2-4pm pst

**Comment by KrzysztofCwalina** [comment]
I think the API link is: https://apiview.dev/Assemblies/Review/b117b54c7e254957ac125800419bde88

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/3fd50840-98dc-94b1-2d3b-f1eba160eb54)[MS INTERNAL ONLY]
