### ISSUE TITLE
Board Review: @azure/communication-ui

### ISSUE THREAD

**Issue by JamesBurnside** [Azure/azure-sdk#2669]
## Contacts and Timeline

* Responsible service team: n/a (no service)
* Main contacts: @alkwa-msft (alkwa), @ddematheu2 (dademath), @JamesBurnside (jaburnsi)
* Expected code complete date: 2021-05-26
* Expected release date: 2021-09-30

## About the Service
* Link to documentation introducing/describing the service: [UI Toolkit Storybook](https://azure.github.io/communication-ui-sdk/?path=/story/introduction--page)
* Link to the service REST APIs: n/a
* Link to GitHub issue for previous review sessions, if applicable: n/a

### Short Description
This is a React UI component library designed for building javascript/typescript communication web apps.
View the component storybook here: https://azure.github.io/communication-ui-sdk/?path=/story/introduction--page

This is one npm package in a series of npm packages that provide a complete toolkit for a consumer to build an ACS powered web app. These packages will doing the heavy lifting for consumers by providing UI components and business logic that integrate with the [@azure/communication-* JavaScript SDKs](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/communication). _This review is just for the UI component package not for the whole toolkit_. For more information see: https://docs.microsoft.com/en-us/azure/communication-services/concepts/ui-framework/ui-sdk-overview

## About the client library

* Name of the client library: @azure/communication-ui
* Languages for this review: Typescript

### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/1979979669814848a818d17b9aea6a76
* Link to Champion Scenarios/Quickstart samples:
  * Use Cases: https://azure.github.io/communication-ui-sdk/?path=/story/use-cases--page
  * UI Component Quick Start: https://azure.github.io/communication-ui-sdk/?path=/story/quickstarts-get-started-with-ui-components--page
  * UI Components:
    Component | Preview | Docs | Demo
    ------------- | -------- | ----- | ----
    Control Bar | ![image](https://user-images.githubusercontent.com/2684369/113533613-2e00f080-9583-11eb-8a25-a3767e320231.png) |  https://azure.github.io/communication-ui-sdk/?path=/docs/ui-components-controlbar--control-bar-component | https://azure.github.io/communication-ui-sdk/?path=/story/ui-components-controlbar--control-bar-component
    ErrorBar | ![image](https://user-images.githubusercontent.com/2684369/113533661-48d36500-9583-11eb-836c-ab3d31f09f10.png) | https://azure.github.io/communication-ui-sdk/?path=/docs/ui-components-errorbar--error-bar-component | https://azure.github.io/communication-ui-sdk/?path=/story/ui-components-errorbar--error-bar-component
    Grid Layout | ![image](https://user-images.githubusercontent.com/2684369/113533683-5e488f00-9583-11eb-8371-a82328d1ec25.png) | https://azure.github.io/communication-ui-sdk/?path=/docs/ui-components-gridlayout--grid-layout-component | https://azure.github.io/communication-ui-sdk/?path=/story/ui-components-gridlayout--grid-layout-component
    Message Thread | ![image](https://user-images.githubusercontent.com/2684369/113533738-8637f280-9583-11eb-9f61-b231e66d0328.png) | https://azure.github.io/communication-ui-sdk/?path=/docs/ui-components-messagethread--message-thread-component | https://azure.github.io/communication-ui-sdk/?path=/story/ui-components-messagethread--message-thread-component
    Participant Item | ![image](https://user-images.githubusercontent.com/2684369/113533877-e3cc3f00-9583-11eb-8dfc-fcd3d40e21e8.png) | https://azure.github.io/communication-ui-sdk/?path=/docs/ui-components-participantitem--participant-item-component | https://azure.github.io/communication-ui-sdk/?path=/story/ui-components-participantitem--participant-item-component
    Read Receipt | ![image](https://user-images.githubusercontent.com/2684369/113533809-b41d3700-9583-11eb-915f-a2f189f7379f.png) | https://azure.github.io/communication-ui-sdk/?path=/docs/ui-components-readreceipt--read-reciept-icon-component | https://azure.github.io/communication-ui-sdk/?path=/story/ui-components-readreceipt--read-reciept-icon-component
    Send Box | ![image](https://user-images.githubusercontent.com/2684369/113533890-f0509780-9583-11eb-874b-629e8276d5b1.png) | https://azure.github.io/communication-ui-sdk/?path=/docs/ui-components-sendbox--send-box-component | https://azure.github.io/communication-ui-sdk/?path=/story/ui-components-sendbox--send-box-component
    Typing Indicator | ![image](https://user-images.githubusercontent.com/2684369/113533908-01010d80-9584-11eb-9e3b-e324bea4725f.png) | https://azure.github.io/communication-ui-sdk/?path=/docs/ui-components-typingindicator--typing-indicator-component | https://azure.github.io/communication-ui-sdk/?path=/story/ui-components-typingindicator--typing-indicator-component
    Video Tile | ![image](https://user-images.githubusercontent.com/2684369/113533925-0fe7c000-9584-11eb-81cf-daaa46a795ee.png) | https://azure.github.io/communication-ui-sdk/?path=/docs/ui-components-videotile--video-tile-component | https://azure.github.io/communication-ui-sdk/?path=/story/ui-components-videotile--video-tile-component
    Incoming Call Toast | ![image](https://user-images.githubusercontent.com/2684369/113533960-2a219e00-9584-11eb-86d6-5e62406c385e.png) | https://azure.github.io/communication-ui-sdk/?path=/docs/examples-incomingcallalerts--incoming-call-toast-component | https://azure.github.io/communication-ui-sdk/?path=/story/examples-incomingcallalerts--incoming-call-toast-component

**Comment by lilyjma** [comment]
scheduled for 4/26

**Comment by lilyjma** [comment]
[Recording](https://web.microsoftstream.com/video/54ba0840-98dc-a7ab-8bb8-f1eba6e1d633)[MS INTERNAL ONLY]
