### ISSUE TITLE
Board Review: Tables GA Tier 1 languages

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk#2713]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: SDK team
* Main contacts: Anna Tisch, Christopher Scott 
* Expected code complete date: April 30th 2021
* Expected release date: May 7th 2021

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/storage/tables/
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/storageservices/table-service-rest-api
* Link to GitHub issue for previous review sessions, if applicable: https://github.com/Azure/azure-sdk/issues/1589

## About the client library

* Name of the client library: Azure Tables
* Languages for this review: .Net, Java, Python, JS

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: [link](https://apiview.dev/Assemblies/Review/5eec924756264faab7ce2eb54d630fb3)  (latest [Transaction updates](https://apiview.dev/Assemblies/Review/5eec924756264faab7ce2eb54d630fb3?diffRevisionId=ba8c122343ea4d848a489bdb55d913d5&doc=False&diffOnly=True))
* Link to Champion Scenarios/Quickstart samples: [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/tables/Azure.Data.Tables/samples)

### Java

* APIView Link: [link](https://apiview.dev/Assemblies/Review/a63158b7fcd44a21bd532264b6cd659f)
* Link to Champion Scenarios/Quickstart samples: [link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/tables/azure-data-tables/src/samples)
    * [Basic operations](https://github.com/Azure/azure-sdk-for-java/blob/04e49780ebd37d9e8f8db92da6a1eb3a837cfc5b/sdk/tables/azure-data-tables/src/samples/java/com/azure/data/tables/HelloWorld.java)
    * [Batch operations](https://github.com/Azure/azure-sdk-for-java/blob/a73d2cc5431bd826db2cc98a2620d6a06db13bd0/sdk/tables/azure-data-tables/src/samples/java/com/azure/data/tables/TableBatchOperations.java)

### Python

* APIView Link: [link](https://apiview.dev/Assemblies/Review/011d29dfbc8b4bdcad1cb4f150d50b7b?diffRevisionId=dd3c6c99e14a48f185e591c0cc21cc2e&doc=False&diffOnly=False)
* Link to Champion Scenarios/Quickstart samples: [link](https://gist.github.com/seankane-msft/9a8beebd7693f9f6c95901b82d5767a6)
  
### TypeScript

* APIView Link: [link](https://apiview.dev/Assemblies/Review/1f149f5ca5a04bd7ba81a17ae4023f72?diffRevisionId=e80ddc06d1d5474394a754f992466255&doc=False&diffOnly=False)
* Link to Champion Scenarios/Quickstart samples: [link](https://github.com/joheredi/azure-sdk-for-js/tree/tables-cleanup/sdk/tables/data-tables/samples/v12/typescript)

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 4/22

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/63dd0840-98dc-94b1-9ec7-f1eba3be31a4)[MS INTERNAL ONLY]
Java review scheduled for 4/28

**Comment by lilyjma** [comment]
[Java Review Recording](https://msit.microsoftstream.com/video/f3960840-98dc-a7ab-5f27-f1eba873afb3)[MS INTERNAL ONLY]
