### ISSUE TITLE
Board Review: Unifying our LLC story

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk#2734]
I'd like to discuss our LLC story and how it will work in practice across languages.  I understand the goal to be: **Deliver cost-effective but usable low-level experiences today that we can evolve into high-level experiences over time**.  Here’s what I think that looks like if I break down [last week’s review](https://github.com/Azure/azure-sdk/issues/2640) across those two dimensions.

<table style="width:100%">
  <tr>
    <th>&nbsp;</th>
    <th>LLC Design Requirements</th>
    <th>HLC Evolution</th>
    <th>Links</th>
  </tr>
  <tr>
    <td><b>C#</b></td>
    <td>
        <ul>
        <li><b>Package/Assembly name</b></li>
        <li><b>Namespace name</b></li>
        <li><b>Top-Level Client type name</b></li>
        <li><b> Client .ctors (including auth)</b></li>
        <li><i> Full Client Hierarchy</i></li>
        <li><i> Method names</i></li>
         <li>Maybe Pageable/LRO</li>
         </ul>
    </td>
    <td>
        Additional methods and client types could be <b>layered in easily on top</b> as needed.
    </td>
    <td>
        <ul>
        <li><a href="https://gist.github.com/KrzysztofCwalina/e3419dcc74d5d087ed6cfba843a0d71f">Details</a></li>
        <li><a href="https://apiview.dev/Assemblies/Review/33a53748d3554822b348523449e74a33">Purview Scan</a></li>
        <li><a href="https://apiview.dev/Assemblies/Review/1315a4d5cf1943f2b349c6cc40d2568f">Purview Catalog</a></li>
        <li><a href="https://apiview.dev/Assemblies/Review/881fbc79c5c14ac3b611d03d8cf4373d">Translator</a></li>
        </ul>
    </td>
  </tr>
  <tr>
    <td><b>Java</b></td>
    <td>
        <ul>
        <li><b>Package name</b> <i>(so the <code>-rest</code> package matches the HLC package)</i></li>
        </ul>
    </td>
    <td>
        <b>Does not evolve.</b>  We will just put out a new HLC package/client/models/etc. and leave the generated package.
    </td>
    <td>
        <ul>
        <li><a href="https://gist.github.com/jianghaolu/c07c06db9251077b5fd42a933916aff7">Details</a></li>
        <li><a href="https://apiview.dev/Assemblies/Review/44b87f07449245d19bd12e56a340b3cc">Purview Scan</a></li>
        <li><a href="https://apiview.dev/Assemblies/Review/d53f033c685d48f0b17be0473a82302d">Purview Catalog</a></li>
        <li><a href="https://apiview.dev/Assemblies/Review/48a39946f7844fb49359c42f17904487">Translator</a></li>
        </ul>
    </td>
  </tr>
  <tr>
    <td><b>Python</b></td>
    <td>
        <ul>
        <li><b>Package name</b></li>
        <li><b>Namespace name</b></li>
        <li><b>Top-Level Client type name</b></li>
        <li><b> Client .ctors (including auth)</b></li>
         </ul>
    </td>
    <td>
        Additional methods and client types could be <b>layered in easily on top</b> as needed.
    </td>
    <td>
        <ul>
        <li><a href="https://github.com/iscai-msft/azure-sdk-for-python/wiki/Low-Level-Client">Details</a></li>
        <li><a href="https://apiview.dev/Assemblies/Review/6abafb3120fb4063b09df0f2303a4ef9">Purview Scan</a></li>
        <li><a href="https://apiview.dev/Assemblies/Review/a27d09d22cd645c88074035a88aa5fd7">Purview Catalog</a></li>
        <li><a href="https://apiview.dev/Assemblies/Review/f5b60eff158941d4802f9e4a5bd3baec">Translator</a></li>
        </ul>
    </td>
  </tr>
  <tr>
    <td><b>TypeScript</b></td>
    <td>
        <ul>
        <li><b>Package name</b></li>
        <li><b>Top-Level Client type name</b></li>
        <li><b> Client .ctors (including auth)</b></li>
         </ul>
    </td>
    <td>
        Additional methods and client types could be <b>layered in easily on top</b> as needed.
    </td>
    <td>
        <ul>
        <li><a href="https://github.com/joheredi/azure-sdk-for-js/wiki/Rest-Level-Client">Details</a></li>
        <li><a href="https://apiview.dev/Assemblies/Review/4be173241acc4e76957d748bfcd02556">Purview Scan</a></li>
        <li><a href="https://apiview.dev/Assemblies/Review/05c3319a58124e0ca8a0390df7b26883">Purview Catalog</a></li>
        <li><a href="https://apiview.dev/Assemblies/Review/745c3080cfda44cca14c17ca39e1d366">Translator</a></li>
        </ul>
    </td>
  </tr>
</table>

I’d love to get to a consistent set of LLC design requirements and HLC evolution plan.  What do you think about the following?
- **Python**
  - Keep what you’ve got
  - Add response helper methods that can make Pageable/LROs easy to use (i.e., a build_submit_batch_response_poller to create a poller that invokes build_get_operation_status_request) when the swagger is appropriately annotated
- **C#**
  - Instead of designing the entire client hierarchy, just focus on the top-level client because that’s easier to get right without significant design effort
  - Add support for Pageable and LROs when the swagger is appropriately annotated.  I’m not sure what we’d use as the instance types (maybe a derived BinaryData holding a JSON object by default?) but we could figure that out.
- **TypeScript**
  - Keep the REST Level Client
  - Adopt Python’s build* methods as an alternate LLC using the same client type (in a way that customers could optionally not pull in if they don’t want the extra code)
  - Add support for Pageable and LROs to the LLCs that would ideally work with the RLCs too
- **Java**
  - Copy what Python is doing with a single top level client, .ctor, send/sendAsync methods
  - Create a .Rest namespace full of builders creating either HttpRequests or HttpPipelineCallContexts used with your send methods
  - Invest in whatever build tooling we need to make customization much easier (maybe something that effectively gives us partial classes in Java?)

Then the common LLC design/Arch Board review would require us settling on:
- Package/assembly/namespace name
- Top-level client name
- Client .ctor (including auth)

And the common HLC evolution is:
- Adding methods making use of models to that top level client class.
- Adding the rest of the client hierarchy (or leaving it flat in Python) with methods making use of models.
- Customers will stop using the .Rest/.Protocol namespace and forget any of those types exist.

**Comment by lilyjma** [comment]
scheduled for 4/21

**Comment by tg-msft** [comment]
So we'll add a new "Arch Board Light Review" where we decide on:
- Package/assembly/namespace name
- .ctors/auth story
- Client hierarchy
- Method names
- LRO/Pageable

The evolution to HLC:
- Add strongly typed HLC overloads on those same clients
- Existing Track 2 versioning story (multiple service versions in one client)

Follow-up actions from today's meeting:
- Figure out how we turn OperationId into a proper client hierarchy
- A plan to make Java easier to customize
- Look at what it'll take to setup swagger reviews
- More design work on Pageable/LRO helpers
- An LLC plan for JS
- Clarify evolution plan for JS/Python
- Laurent's LLC document

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/3fd50840-98dc-94b1-f7d3-f1eba2f5f2fd)[MS INTERNAL ONLY]

**Comment by annelo-msft** [comment]
@tg-msft, does the table in the description still reflect the latest thinking on LLC reviews?

**Comment by tg-msft** [comment]
The table in the issue is probably very out of date.  I'd recommend checking with the LLC architects.

**Comment by lmazuel** [comment]
Update on the actions that were decided by order from @tg-msft last post
- https://github.com/azure/autorest.csharp/issues/1527
- https://github.com/Azure/autorest.java/issues/1099
- LLC APIView was done during summer 2021
- Pageable/LRO has been added cross-language
- JS is not at this point considering LLC, and stick to RLC
- Evolution for JS after a RLC is regular autorest+convenience layer. For Python, we grow in place on the generated client (I won't detail here, ping Johan for detail)
- WIP with Mike now that we have Mike
