### ISSUE TITLE
Board Review: Microsoft.Azure.WebJobs.Extensions.ServiceBus GA

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk#2741]
## Contacts and Timeline

* Responsible service team: ADP
* Main contacts: @JoshLove-msft @pakrym @AlexGhiondea 

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus
* Link to the service REST APIs: N/A
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Microsoft.Azure.WebJobs.Extensions.ServiceBus
* Languages for this review: .NET

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/88f79b19a3894a748e3f4f367ea363ab
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/README.md

**Comment by JoshLove-msft** [comment]
@lilyjma just wanted to check in on this

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/cadd0840-98dc-a7ab-4528-f1ebb43906ac)[MS INTERNAL ONLY]
