### ISSUE TITLE
Board Review: Microsoft.Azure.WebJobs.Extensions.EventGrid GA

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk#2742]
## Contacts and Timeline

* Responsible service team: ADP
* Main contacts: @pakrym @JoshLove-msft @AlexGhiondea 

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid
* Link to the service REST APIs: N/A
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Microsoft.Azure.WebJobs.Extensions.EventGrid
* Languages for this review: .NET

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/2bc333c1b0554f508761c8eab7681021
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventgrid/Microsoft.Azure.WebJobs.Extensions.EventGrid/README.md

**Comment by JoshLove-msft** [comment]
Since the API is very small for EG, it would be good if we could review this together with the Service Bus extensions - https://github.com/Azure/azure-sdk/issues/2741

**Comment by JoshLove-msft** [comment]
@lilyjma just wanted to check in on this

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/cadd0840-98dc-a7ab-4528-f1ebb43906ac)[MS INTERNAL ONLY]
