### ISSUE TITLE
Board Light Review: Purview Scanning LLC

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#2744]
This is a LLC review for naming only. We will use one language as a guinea pig of showing the names (this is NOT a language review)

### Swagger

* https://github.com/Azure/azure-rest-api-specs/pull/14021
* Swagger UI view:
   * [purviewScanning.zip](https://github.com/Azure/azure-sdk/files/6380998/purviewScanning.zip)
   * https://lmazueltemp.z13.web.core.windows.net/

### .NET

* APIView Link Purview Scanning: https://apiview.dev/Assemblies/Review/33a53748d3554822b348523449e74a33

### Java

* APIView Link Purview Scanning: https://apiview.dev/Assemblies/Review/44b87f07449245d19bd12e56a340b3cc

### Python

* APIView Link Purview Scanning: https://apiview.dev/Assemblies/Review/6abafb3120fb4063b09df0f2303a4ef9
  
### TypeScript

* APIView Link Purview Scanning: https://apiview.dev/Assemblies/Review/4be173241acc4e76957d748bfcd02556

**Comment by lilyjma** [comment]
scheduled for 4/27
