### ISSUE TITLE
Board Review: Introducing Azure Communication Services (SPOOL) - Networking

### ISSUE THREAD

**Issue by ajpeacock0** [Azure/azure-sdk#2770]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Azure Communication Services (SPOOL)
* Main contacts: 
  - Andrew Peacock, anpea@microsoft.com, ajpeacock0
  - Ari Zavala, arzavala@microsoft.com, AriZavala2
* Expected GA date for this library: September 2021

## About the Service

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/communication-services/
* Link to the service REST APIs: [CommunicationTurn.json](https://github.com/Azure/azure-rest-api-specs/blob/15267a1eafe1fb01e77d2b5b022c3143aede36ce/specification/communication/data-plane/Microsoft.CommunicationServicesTurn/preview/2021-02-22-preview1/CommunicationTurn.json)
* Is the goal to release a Public Preview, Private Preview, or GA? Public Preview

## About the client library

* Name of client library: Azure Communication Networking
* Link to library reference documentation: N/A

### C#

* Is there an existing .NET SDK library? If yes, provide link: No
* .NET APIView: https://apiview.dev/Assemblies/Review/7fe28e9a183e4df1b249c35d6e8d2876

### TS

* Is there an existing TypsScript SDK library? If yes, provide link: No
* TypsScript APIView: https://apiview.dev/Assemblies/Review/e9e542c6a16d4e769a08d804bb38b65d

## Step 1: Champion Scenarios

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
4. How does the **authentication** workflow look?

See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

#### C#

```csharp
    string connectionString = "CONNECTION_STRING";
    CommunicationIdentityClient identityClient = new CommunicationIdentityClient(connectionString);
    Response<CommunicationUser> communicationUser = identityClient.CreateUser();

    CommunicationNetworkingClient networkingClient = new CommunicationNetworkingClient(connectionString);
    Response<CommunicationTurnCredentialsResponse> turnCredentialsResponse = networkingClient.GetTurnCredentials(communicationUser);

    DateTimeOffset turnTokenExpiresOn = turnCredentialsResponse.Value.ExpiresOn;
    IReadOnlyList<CommunicationTurnServer> turnServers = turnCredentialsResponse.Value.TurnServers;

    Console.WriteLine($"Expires On: {turnTokenExpiresOn}");

    foreach (CommunicationTurnServer iceServer in turnServers)
    {
        foreach (string url in iceServer.Urls)
        {
            Console.WriteLine($"TurnServer Url: {url}");
        }
        Console.WriteLine($"TurnServer Username: {iceServer.Username}");
        Console.WriteLine($"TurnServer Credential: {iceServer.Credential}");
    }
```

#### TS

```javascript
const connectionString = "COMMUNICATION_CONNECTION_STRING"

const identityClient = new CommunicationIdentityClient(connectionString);
const user = await identityClient.createUser();

const client = new CommunicationNetworkingClient(connectionString);

console.log(`Created user with id: ${user.communicationUserId}`);

const turnCredentialResponse  = await client.getTurnCredentials(user);
const turnTokenExpiresOn = turnCredentialResponse.expiresOn;

console.log(`Turn token expires on: ${turnTokenExpiresOn}`);

const turnServers = turnCredentialResponse.TurnServers;

for (var iceServer of turnServers)
{
    for(var url of iceServer.Urls)
    {
        console.log(`TurnServer Url: ${url}`);
    }

    console.log(`TurnServer Username: ${iceServer.Username}`);
    console.log(`TurnServer Credential: ${iceServer.Credential}`);
}
```

#### C#

```csharp
    Response<CommunicationTurnCredentialsResponse> turnCredentialsResponse = await networkingClient.GetTurnCredentials(communicationUser);
    IReadOnlyList<CommunicationTurnServer> turnServers = turnCredentialsResponse.Value.TurnServers;

    var rtcIceServers = new List<RTCIceServer>();
    foreach (CommunicationTurnServer iceServer in turnServers)
    {
        rtcIceServers.Add(new RTCIceServer
        {
            Urls = iceServer.Urls,
            TurnUserName = iceServer.Username,
            TurnUserName = iceServer.Credential,
        });
    }

    RTCConfiguration config = new RTCConfiguration();
    config.IceTransportPolicy = RTCIceTransportPolicy.All;
    config.IceServers = rtcIceServers;

    PeerConnection = new RTCPeerConnection(config);
```

## Step 2: Quickstart Samples

Private Preview Samples: https://github.com/Azure/azure-sdk-for-net/tree/feature/communciation/turn_api_private_preview/sdk/communication/Azure.Communication.Identity/samples

### Create a `CommunicationNetworkingClient`

To create a new `CommunicationNetworkingClient` you need a connection string to the Azure Communication Services resource that you can get from the Azure Portal once you have created the resource. The `CommunicationNetworkingClient` can be used to create users and get tokens and credentials.

```C# Snippet:CreateCommunicationIdentityClient
// Get a connection string to our Azure Communication resource.
var connectionString = "<connection_string>";
var client = new CommunicationNetworkingClient(connectionString);
```

Or alternatively using the endpoint and access key acquired from an Azure Communication Resources in the [Azure Portal][azure_portal].

```C# Snippet:CreateCommunicationIdentityFromAccessKey
var endpoint = new Uri("https://my-resource.communication.azure.com");
var accessKey = "<access_key>";
var client = new CommunicationNetworkingClient(endpoint, new AzureKeyCredential(accessKey));
```

Clients also have the option to authenticate using a valid Active Directory token.

```C# Snippet:CreateCommunicationIdentityFromToken
var endpoint = new Uri("https://my-resource.communication.azure.com");
TokenCredential tokenCredential = new DefaultAzureCredential();
var client = new CommunicationNetworkingClient(endpoint, tokenCredential);
```

### Generate TURN credentials

The example code snippet below shows how to generate TURN credentials. A set of STUN/TURN addresses are returned, along with a set of credentials.

The `CommunicationTurnServer` class matches the [WebRTC IceServer](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer) standard so that it can be easy passed into the configuration of a WebRTC connection. Every set of TURN credentials has an expiry date and time stamped on it. Once the credentials have expired, you must request new credentials.

```C# Snippet:CreateTURNToken
Response<CommunicationTurnCredentialsResponse> turnCredentialsResponse = client.GetTurnCredentials();

DateTimeOffset turnTokenExpiresOn = turnCredentialsResponse.Value.ExpiresOn;
IReadOnlyList<CommunicationTurnServer> turnServers = turnCredentialsResponse.Value.TurnServers;

Console.WriteLine($"Expires On: {turnTokenExpiresOn}");
foreach (CommunicationTurnServer iceServer in turnServers)
{
    foreach (string url in iceServer.Urls)
    {
        Console.WriteLine($"TURN Url: {url}");
    }
    Console.WriteLine($"TURN Username: {iceServer.Username}");
    Console.WriteLine($"TURN Credential: {iceServer.Credential}");
}
```

**Comment by lilyjma** [comment]
scheduled for 5/12

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/ef7f0840-98dc-a7ab-bc0c-f1ebb3710dec)[MS INTERNAL ONLY]
