### ISSUE TITLE
Board Review: @azure/communication-stateful

### ISSUE THREAD

**Issue by JamesBurnside** [Azure/azure-sdk#2775]
## Contacts and Timeline

* Responsible service team: (no service)
* Main contacts: @alkwa-msft (alkwa), @ddematheu2 (dademath), @PorterNan (jinan),  @JamesBurnside (jaburnsi)
* Expected code complete date: 2021-05-26
* Expected release date: 2021-09-30

## About the Service 

* Link to documentation introducing/describing the service: https://azure.github.io/communication-ui-sdk/?path=/story/quickstarts-get-started-with-stateful-client--page
* Link to the service REST APIs: n/a
* Link to GitHub issue for previous review sessions, if applicable:  Related (but no previous) session: https://github.com/Azure/azure-sdk/issues/2669

## About the client library

* Name of the client library: @azure/communication-stateful
* Languages for this review: Typescript

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### TypeScript

* APIView Link:
  * Stateful-clients Packlet: https://apiview.dev/Assemblies/Review/f64b58adfedf4c37a4cb1c0577303d4d
  * Component-Bindings Packlet: https://apiview.dev/Assemblies/Review/2bfbe658723b49a6b946018434e86178
  * For reference: 
    * React-components Packlet: https://apiview.dev/Assemblies/Review/1979979669814848a818d17b9aea6a76
    * React-composites Packlet: https://apiview.dev/Assemblies/Review/9d126968725c4f6bb0acf75d1947b0eb
    * @azure/communication-react Package: https://apiview.dev/Assemblies/Review/a0645994be9e4deeb3cfc0d58e41c0ab
* Link to Champion Scenarios/Quickstart samples: https://azure.github.io/communication-ui-sdk/?path=/story/quickstarts-get-started-with-stateful-client--page

**Comment by lilyjma** [comment]
scheduled for 5/10

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/70910840-98dc-a7ab-aa01-f1ebb1e43d09)[MS INTERNAL ONLY]
