### ISSUE TITLE
Board Light Review: Confidential Ledger

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#2777]
This is a LLC review for naming only. We will use one language as a guinea pig of showing the names (this is NOT a language review)

### Swagger

* https://github.com/Azure/azure-rest-api-specs/pull/13613
* Swagger UI view: https://lmazuelclreview.z13.web.core.windows.net/

### .NET

* APIView : https://apiview.dev/Assemblies/Review/fa1a313d94974a7bb3aacc1107a8c0f6

### Java

* APIView : https://apiview.dev/Assemblies/Review/d97ba32c81d842a69b0e4e8a262ceef9

### Python

* APIView : https://apiview.dev/Assemblies/Review/b7abeb7876884e3aa42cf8784c3bdf8b
  
### TypeScript

* APIView : https://apiview.dev/Assemblies/Review/8450ac12a5ee47d6b2553f43e17db4c5

**Comment by lilyjma** [comment]
scheduled for 5/3

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/39890840-98dc-a7ab-840e-f1ebac5c7932)[MS INTERNAL ONLY]
