### ISSUE TITLE
Board Review: Introducing Azure Monitor Logs and Metrics query

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk#2783]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: SDK team
* Main contacts: Josh Free, Srikanta Nagaraja, Pavel Krymets, Rakshit Bhyravabhotla, Richard Park, Karishma Ghiya
* Expected GA date for this library: September 2021

## About the Service 

* Link to documentation introducing/describing the service: 
https://docs.microsoft.com/en-us/azure/azure-monitor/overview
https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/data-platform-metrics
https://docs.microsoft.com/en-us/azure/azure-monitor/logs/data-platform-logs

* Link to the service REST APIs: 
  - [Logs](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/operationalinsights/data-plane/Microsoft.OperationalInsights/stable/v1/OperationalInsights.json)
  - [Metrics](https://editor.swagger.io/?url=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/ca0869b49176e7bc3866debbab9d32999661c4cb/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-01-01/metrics_API.json)
  - [Metrics Definitions](http://editor.swagger.io/?url=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/cf33826d06605cde127d2241e54dd6df55e9145f/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-01-01/metricDefinitions_API.json)
  - [Metrics Namespaces](https://editor.swagger.io/?url=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/cf33826d06605cde127d2241e54dd6df55e9145f/specification/monitor/resource-manager/Microsoft.Insights/preview/2017-12-01-preview/metricNamespaces_API.json)

* Is the goal to release a Public Preview, Private Preview, or GA? 
Public Preview

## About the client library

* Name of client library: Azure Monitor Log and Metrics Query
* Link to library reference documentation: 
* Is there an existing SDK library? If yes, provide link: 

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
4. How does the **authentication** workflow look? 
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1
Make a simple query to the service "requests | summarize count() by bin(timestamp, 1h)", "timestamp = P1D"
   - Get the results in tabular form
   - Get the results in key-value form

* Champion scenario 2
Run 5 queries in 1 api call
  - Get the results in tabular form
  - Get the results in key-value form

* Champion scenario 3
Run a complex query that requires a longer duration to complete and extend server timeout (default 3 minutes) to allow query execution to complete.

* Champion scenario 4
Query metrics for an Azure resource id.

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: [link](https://apiview.dev/Assemblies/Review/f50c27920f774c4ab6ca1f9b279683d0)
* Link to Champion Scenarios/Quickstart samples: [link](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/monitor/Azure.Monitor.Query/README.md#examples)

### Java

* APIView Link: [link](https://apiview.dev/Assemblies/Review/6a68e77d395046a8a0df8621ef3f07b7)
* Link to Champion Scenarios/Quickstart samples: [link](https://github.com/srnagar/azure-sdk-for-java/tree/ux-study/sdk/monitor/azure-monitor-query#examples)

### Python

* APIView Link: [link](https://apiview.dev/Assemblies/Review/5ccb5dc8cc68463cabe6a920587399ed)
* Link to Champion Scenarios/Quickstart samples: [link](https://github.com/rakshith91/azure-sdk-for-python/blob/2monarch/sdk/monitor/azure-monitor-query/samples/champion_scenarios.md)
  
### TypeScript

* APIView Link: [link](https://apiview.dev/Assemblies/Review/23c04df42f764b1c9b14ed9271a5191a)
* Link to Champion Scenarios/Quickstart samples: [link](https://github.com/KarishmaGhiya/azure-sdk-for-js/tree/ux-study-monitor/sdk/monitor/monitor-query#examples)

**Comment by lilyjma** [comment]
scheduled for 5/6

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/69a80840-98dc-a7ab-819f-f1ebb2acfec2)[MS INTERNAL ONLY]

**Comment by lilyjma** [comment]
scheduled for 8/24 2-4pm pst

**Comment by srnagar** [comment]
Closing this issue as the Azure Monitor Query library is now GA in all tier-1 languages.
