### ISSUE TITLE
Board Light Review: Purview Catalog LLC

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#2784]
This is a LLC review for naming only. We will use one language as a guinea pig of showing the names (this is NOT a language review)

### Swagger

* https://github.com/Azure/azure-rest-api-specs/tree/6201f0ba800aae592e3efe70d73338787b674efe/specification/purview/data-plane/Azure.Purview.Catalog/preview/2020-12-01-preview/purviewcatalog.json

* Swagger UI view: https://lmazuelcatalog.z13.web.core.windows.net/

### .NET

* APIView Link Purview Catalog: https://apiview.dev/Assemblies/Review/c1ba2047951d4709bd527f8d59640b50

### Java

* APIView Link Purview Catalog: https://apiview.dev/Assemblies/Review/d53f033c685d48f0b17be0473a82302d

### Python

* APIView Link Purview Catalog: https://apiview.dev/Assemblies/Review/a27d09d22cd645c88074035a88aa5fd7
  
### TypeScript

* APIView Link Purview Catalog: https://apiview.dev/Assemblies/Revisions/05c3319a58124e0ca8a0390df7b26883

**Comment by lilyjma** [comment]
scheduled for 5/5

**Comment by annatisch** [comment]
@lmazuel - will there be a Python APIview for today?

**Comment by lmazuel** [comment]
@annatisch updated, thanks!

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/d7fc99ff-0300-a7ab-4378-f1ebadf65640)[MS INTERNAL ONLY]

**Comment by yifan-zhou922** [comment]
Hi, I notice that the link for the swagger ( https://github.com/Azure/azure-rest-api-specs/tree/6201f0ba800aae592e3efe70d73338787b674efe/specification/purview/data-plane/Azure.Purview.Catalog/preview/2020-12-01-preview/purviewcatalog.json ) is not the latest version. This is updated version for Catalog swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/purview/data-plane/Azure.Purview.Catalog/preview/2021-05-01-preview/purviewcatalog.json

Also, the APIView Link for Java & .NET are not the latest as well. We have already fixed the name like getById2(), etc.
