### ISSUE TITLE
Board Review: Introducing Time Series Insights

### ISSUE THREAD

**Issue by barustum** [Azure/azure-sdk#2788]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library:
Implementation was done by the Azure IoT Managed SDK team. The owning team for the client library will be the Time Series Insights service team
* Main contacts: Managed SDK team contacts: Basel Rustum <Basel.Rustum@microsoft.com> and Binal Kamani <Binal.Kamani@microsoft.com>. Time Series Insights service team contacts: Raghav Sidhanti <rasidhan@microsoft.com> and Dmitry Denisov <dmden@microsoft.com>
* Expected GA date for this library: GA is end of June 2021

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/time-series-insights/quickstart-explore-tsi
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/timeseriesinsights/data-plane/Microsoft.TimeSeriesInsights/stable/2020-07-31/timeseriesinsights.json
* Is the goal to release a Public Preview, Private Preview, or GA? Public Preview first, targeting first week of May. GA end of June.

## About the client library

* Name of client library: [TimeSeriesInsightsClient](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/timeseriesinsights/Azure.IoT.TimeSeriesInsights/src/TimeSeriesInsightsClient.cs)
* Link to library reference documentation:
* Is there an existing SDK library? If yes, provide link: 

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
4. How does the **authentication** workflow look? 
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1
    * Link to library’s sample folder: 
* Champion scenario 2
    * Link to library’s sample folder:
* …
* Champion scenario n
    * Link to library’s sample folder:

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 

* Create a new resource
* Read the resource
* Modify the resource
* Delete the resource
* Error handling 
* Handling race conditions/concurrency issues

**Comment by lilyjma** [comment]
scheduled for 5/6 2-4pm PST

**Comment by barustum** [comment]
Link to API View: https://apiview.dev/Assemblies/Review/7c98651d1d704d33a0b7f1bcb171d1a6

Champion Scenarios coming soon.

**Comment by barustum** [comment]
Sample scenarios: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/timeseriesinsights/Azure.IoT.TimeSeriesInsights/samples/Readme.md

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/abb40840-98dc-a7ab-63fb-f1ebaec2d760)[MS INTERNAL ONLY]
