### ISSUE TITLE
Update ACR Swagger to accomodate new m4 validations

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#2803]
m4 added a validation to ensure multiple items aren't defined in the swagger's `security` block.  ACR does this, and so generation will fail if the generator is using the latest version fo m4.

We'll need to update the swagger to prevent this issue in C#, which is using the latest verion of m4, and to prevent the issue from happening in other languages when they upgrade.

Details of change can be found in this transform: https://github.com/Azure/azure-sdk-for-net/pull/20833

We will make the change directly to the swagger.

After the swagger is updated, the transform in azure-sdk-for-net must be removed.

**Comment by annelo-msft** [comment]
@chamons @AlexGhiondea FYI

**Comment by timotheeguerin** [comment]
As explain on this issue, this was actually a issue in autorest. This should have been a warning not an error.

https://github.com/Azure/azure-sdk/issues/2805

 Modelerfour has a hot fix https://github.com/Azure/autorest/pull/4110 published

**Comment by annelo-msft** [comment]
@timotheeguerin, thanks for the heads-up!

@chamons, how soon will we take the fix in the C# generator?

**Comment by chamons** [comment]
So the transform + generator with the unnecessary error is in today. 

I'm working on bumping it again today.

**Comment by annelo-msft** [comment]
Won't fix.
