### ISSUE TITLE
Update Azure.AI.MetricsAdvisor Swagger to accomodate new m4 validations

### ISSUE THREAD

**Issue by chamons** [Azure/azure-sdk#2805]
Near copy of https://github.com/Azure/azure-sdk/issues/2803.

m4 added a validation to ensure multiple items aren't defined in the swagger's security block. Azure.AI.MetricsAdvisor does this, and so generation will fail if the generator is using the latest version of m4.

We'll need to update the swagger to prevent this issue in C#, which is using the latest verion of m4, and to prevent the issue from happening in other languages when they upgrade.

Details of change can be found in this transform: https://github.com/Azure/azure-sdk-for-net/pull/20833

After the swagger is updated, the transform in azure-sdk-for-net must be removed.

**Comment by chamons** [comment]
FYI @AlexGhiondea @ShivangiReja @kinelski

**Comment by chamons** [comment]
Hey @timotheeguerin can you comment on ^

**Comment by timotheeguerin** [comment]
Hhm, yeah this is correct providing multiple is a `AND`, this should actually be a warning instead of an error like the other warnings if not using one of the known schemes. I'll make a fix.

@kinelski how are you using some security schemes? Is it just there for reference as autorest used to not do anything with it?

**Comment by kinelski** [comment]
> how are you using some security schemes? Is it just there for reference as autorest used to not do anything with it?

You're right. We're not using them. Our code inserts the security headers manually.

**Comment by timotheeguerin** [comment]
Merged PR https://github.com/Azure/autorest/pull/4110, hot fix version 4.19.1 should be available soon

**Comment by kinelski** [comment]
AutoRest has been updated. No swagger changes are required. (https://github.com/Azure/azure-sdk-for-net/pull/20869).
