### ISSUE TITLE
Board Review: Azure Container Registry (C#, TypeScript, Java, Python)

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#2832]
# Context for Arch Board Review Meeting

We plan to treat our ACR Beta 3 release -- i.e. the libraries we publish in the June sprint -- as release candidates ready to GA.  (The service team has not yet set a GA date for ACR data-plane, but we are working with them on that.)  As such, our goal is to get architect approval on the APIs for the four Tier-1 languages, or feedback that will help us get to approval **by the end of the June sprint**.

## Contacts and Timeline

* Main contacts: @annelo-msft @AlexGhiondea @mnltejaswini 
* Expected code complete date: **05/27/2021**
* Expected release date:  **06/01/2021**
* Please include: @sajayantony @northtyphoon @toddysm @elraikhm @jeremymeng @pallavit @seankane-msft 

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/container-registry/
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/containerregistry/#data-plane-rest-operation-groups-preview
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/2384

## About the client library

* Name of the client library:
  - .NET: **Azure.Containers.ContainerRegistry.1.0.0**
  - TypeScript: **@azure/container-registry 1.0.0**
  - Java: **azure-containers-containerregistry 1.0.0**
  - Python: **azure-containerregistry 1.0.0**
* Languages for this review: **C#, TypeScript, Java, Python**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/ba57bf904e524ce3bf647dad124ddc7c
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/blob/1c5008f7b03c25d10d8516f4740a16d54ad88d97/sdk/containerregistry/Azure.Containers.ContainerRegistry/README.md#examples

### Python

* APIView Link: [link](https://apiview.dev/Assemblies/Review/650de6788f554625945810ab074e8d4c)
* Link to Champion Scenarios/Quickstart samples: [link](https://gist.github.com/seankane-msft/6eced145bc0c5695aba750f518960972) 
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/a760e3c78cbd4543b93f6a6897e1a9b6
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-js/blob/7f9afa11b08fac0c65305fa6ac5de29ada7711e5/sdk/containerregistry/container-registry/README.md#examples

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/5d0e057991274e1bb7d7ffae4ff0302b
* Link to Champion Scenarios/Quickstart samples: https://github.com/pallavit/azure-sdk-for-java/blob/pallavit/acrbeta3/sdk/containerregistry/azure-containers-containerregistry/README.md

**Comment by lilyjma** [comment]
scheduled for 5/11

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/ef7f0840-98dc-a7ab-618c-f1ebb82d544d)[MS INTERNAL ONLY]

**Comment by annelo-msft** [comment]
Summary of action items for feature crew:
- Rename `GetTagProperties` to `GetTag` (or language appropriate)
- Remove `LoginServer` and `Name` properties from `ContainerRegistryClient`
- Come up with better name for `ArtifactManifestReference`
- Remove the `DeleteRepositoryResult` type, and return a success result from `DeleteRepository` operation even when a 404 is received.
- Evaluate `FullyQualifiedName` with regard to 1) what we do in other Track 2 libraries wrt to the qualified name concept and 2) what this is commonly called in the Docker/containers community.
- Ensure functional parity of Python library with others
- Rename PATCH service methods from `Set..` to `Update..`
- Discuss parallelizing the delete sample across languages
