### ISSUE TITLE
Board Review: Attestation - Python

### ISSUE THREAD

**Issue by LarryOsterman** [Azure/azure-sdk#2889]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Attestation
* Main contacts: larryo@microsoft.com, @azattestft@microsoft.com
* Expected code complete date:5/18/2021
* Expected release date:6/8/2021

## About the Service 

* Link to documentation introducing/describing the service:https://azure.microsoft.com/en-us/services/azure-attestation/
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/attestation/data-plane/Microsoft.Attestation/stable/2020-10-01/attestation.json
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/2652

## About the client library

* Name of the client library: azure-security-attestaiton
* Languages for this review:Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/5210fb6aa28542e4ad65c13a44c2b9d6
* Link to Champion Scenarios/Quickstart samples:https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/attestation/azure-security-attestation/samples

Note: There are no real champion scenarios, however there are several quickstart samples showing the use of the API surface.
  
### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 6/1 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/a5b40840-98dc-869d-d9b3-f1ebc32dfd05)[MS INTERNAL ONLY]
