### ISSUE TITLE
Integrate Pagination Guidelines into Python, Java, Dotnet

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-sdk#293]
Just a tracking issue, as I added a new section and am not sure where y'all want it in your lang-specific specs.

**Comment by bterlson** [comment]
See: #231.

**Comment by JonathanGiles** [comment]
Added to the next draft of my Java spec - thanks.

**Comment by adrianhall** [comment]
I've seen this in all guidelines now, so closing.
