### ISSUE TITLE
Naming convention for partial result types

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk#298]
In restful queries, a 'list' request often returns a partial result that lacks the full information that would be returned via a 'get' request. 

In Java, we might have a `Flux<FooInfo> listFoo()` operation on the list operation, but a `Mono<Response<Foo>> getFoo(id)` operation for the get operation. What is relevant here is that `FooInfo` contains some subset of information that `Foo` contains, and we should make it clear that they are different types through some consistent naming pattern.

Furthermore, for the sake of developer experience, this is something that all languages (where practicable) should standardise on. Two possible options might be `<Noun>Info` or `<Noun>Attributes`. This issue therefore is to track a discussion on the topic of what naming pattern should be used.

**Update from Key Vault UX study:** We found that Java users were confused by the `SecretAttributes` class. They did not realise that this was the parent class of `Secret`, and so all API that accepted an argument type of `SecretAttributes` did not immediately make sense to them. On the second day of UX studies, having renamed `SecretAttributes` to `Secret`, and the relevant methods from, e.g. `updateSecretAttributes` to `updateSecret`, we found that users had far better understanding of the relationship between the `SecretBase` class and the `Secret` class.

**Comment by adrianhall** [comment]
Board decision is that we don't want to be prescriptive about this.  Closing with no action at this time.
