### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - SIP routing

### ISSUE THREAD

**Issue by jiriburant** [Azure/azure-sdk#3010]
## Contacts and Timeline

* Service team responsible for the client library: ACS PSTN
* Main contacts: acs-pstn@microsoft.com, jiriburant@microsoft.com, jannovak@microsoft.com, tomasmachala@microsoft.com
* Timeline for delivery: short term after "Azure Communication Services - Direct Routing" Public Preview (June 30)

## About the Service

* Link to documentation introducing/describing the service: [create communication service] (https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/create-communication-resource?tabs=windows&pivots=platform-azp)
* Link to the service REST APIs: [json] (https://spoolgw-int-01-telephonyservice-01.westus.cloudapp.azure.com/swagger/SipConfigurationApiSpecification/swagger.json)
* Link to SIP service description:
https://docs.microsoft.com/en-us/azure/communication-services/concepts/telephony-sms/sip-interface-infrastructure

### .NET
APIview Link: https://apiview.dev/Assemblies/Review/54c975fb0a80468cbf6437c4cbb05e32
### Java
APIview Link: https://apiview.dev/Assemblies/Review/7d1b1f88431044edbbf1c873d345e3eb
### Python
APIview Link: https://apiview.dev/Assemblies/Review/ac82228b44a145048324d3ae9b99153c
Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-python/tree/81c6f3f9252222c75175cf15197a3a1d2f55e813/sdk/communication/azure-communication-siprouting/samples
## About the client library

* Name of client library: Azure Communication SIP routing
* Link to library reference documentation:  N/A

The goal is to provide a client that is able to retrieve SIP routing configuration of the service and modify the configuration with new SIP trunks settings and new SIP routes settings.
There are four public methods in the client, serving 4 scenarios.

There is option to:

- Retrieve SIP configuration
- Update SIP configuration with trunks and routes
- Update just SIP trunks
- Update just SIP routes

### Champion scenario 1: Use SIP routing client to get SIP routing configuration
Python:
```python
client = SIPRoutingClient.from_connection_string(<communication_connection_string>)
try:
  configuration = client.get_sip_configuration()

  for trunk in configuration.trunks:
    print(f"Sip trunk - name: {trunk}: {trunks[trunk].sip_signaling_port}")
  for route in configuration.routes:
    print(f"Sip route - name: {route.name}: {route.description}")
except HttpResponseError, e:
  print(e)
```

C#:
```C# Snippet:GetSipConfiguration
var clientOptions = new SipRoutingClientOptions();
var client = new SipRoutingClient(<communication_connection_string>, clientOptions);

var configuration = client.GetSipConfiguration();

foreach (var trunk in configuration.trunks)
{
    Console.WriteLine($"Sip trunk is set with {trunk.Key} and port {trunk.Value.SipSignalingPort}");
}

foreach (var route in configuration.routes)
{
    Console.WriteLine($"{route.Name}: {route.Description}");
}
```

### Champion scenario 2: Use SIP routing client to update SIP routing configuration
Python:
``` python
client = SIPRoutingClient.from_connection_string(<communication_connection_string>)
try:
  new_configuration = client.update_sip_configuration(<new_trunks>,<new_routes>)

  for trunk in new_configuration.trunks:
    print(f"Sip trunk - name: {trunk}: {trunks[trunk].sip_signaling_port}")
  for route in new_configuration.routes:
    print(f"Sip route - name: {route.name}: {route.description}")
except HttpResponseError, e:
  print(e)
```

C#:
```C# Snippet:UpdateSipConfiguration
var clientOptions = new SipRoutingClientOptions();
var client = new SipRoutingClient(<communication_connection_string>, clientOptions);

var configuration = client.UpdateSipConfiguration(<new_trunks>,<new_routes>);

foreach (var trunk in configuration.trunks)
{
    Console.WriteLine($"Sip trunk is set with {trunk.Key} and port {trunk.Value.SipSignalingPort}");
}

foreach (var route in configuration.routes)
{
    Console.WriteLine($"{route.Name}: {route.Description}");
}
```

### Champion scenario 3: Use SIP routing client to update only SIP trunks configuration
Python:
``` python
client = SIPRoutingClient.from_connection_string(<communication_connection_string>)
try:
  new_configuration = client.update_sip_trunks(<new_trunks>)

  for trunk in new_configuration.trunks:
    print(f"Sip trunk - name: {trunk}: {trunks[trunk].sip_signaling_port}")
except HttpResponseError, e:
  print(e)
```

C#:
```C# Snippet:UpdateSipTrunks
var clientOptions = new SipRoutingClientOptions();
var client = new SipRoutingClient(<communication_connection_string>, clientOptions);

var newConfiguration = client.UpdateSipTrunks(<new_sip_trunks>)

foreach (var trunk in newConfiguration.trunks)
{
    Console.WriteLine($"Sip trunk is set with {trunk.Key} and port {trunk.Value.SipSignalingPort}");
}
```

### Champion scenario 4: Use SIP routing client to update only SIP routes configuration
Python:
``` python
client = SIPRoutingClient.from_connection_string(<communication_connection_string>)
try:
  new_configuration = client.update_sip_routes(<new_routes>)

  for route in new_configuration.routes:
    print(f"Sip route - name: {route.name}: {route.description}")
except HttpResponseError, e:
  print(e)
```

C#:
```C# Snippet:UpdateSipRoutes
var clientOptions = new SipRoutingClientOptions();
var client = new SipRoutingClient(<communication_connection_string>, clientOptions);

var newConfiguration = client.UpdateSipRoutes(<new_sip_routes>)

foreach (var route in newConfiguration.routes)
{
    Console.WriteLine($"Sip route- name: {route.Name}: {route.Description}");
}
```

**Comment by lilyjma** [comment]
scheduled for 6/22 9-11am PST

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/53850840-98dc-b561-b004-f1ebd37c2479)[MS INTERNAL ONLY]
