### ISSUE TITLE
Board Review: Azure::KeyVault::Keys::CryptoClient for C++

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk#3040]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team:  @RickWinter 
* Main contacts: @vhvb1989 
* Expected code complete date:  7/1/21
* Expected release date: 7/7/21

## About the Service 

* Link to documentation introducing/describing the service: 
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/keyvault
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/2331

## About the client library

* Name of the client library: azure-security-keyvault-keys
* Languages for this review: C++

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### C++

* APIView Link: 
  * https://apiview.dev/Assemblies/Review/2b96c2a3509844fcaf0106f1af1d43f1
* Link to Champion Scenarios/Quickstart samples:
  * Encrypt/Decrypt: https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/keyvault/azure-security-keyvault-keys/test/samples/sample4-encrypt-decrypt/sample4_encrypt_decrypt.cpp
  * Sign/Verify: https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/keyvault/azure-security-keyvault-keys/test/samples/sample5-sign-verify/sample5_sign_verify.cpp
  * Wrap/Unwrap: https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/keyvault/azure-security-keyvault-keys/test/samples/sample6-wrap-unwrap/sample6_wrap_unwrap.cpp

**Comment by lilyjma** [comment]
scheduled for 6/24

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/4adb0840-98dc-b561-4a3c-f1ebd53acf7b)[MS INTERNAL ONLY]
