### ISSUE TITLE
Board Review: Question Answering, .Net and Python

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk#3089]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Carol Hanna, Somi Reddy Satti, Rohan Kulkarni
* Main contacts: Heath Stewart, Anna Tisch
* Expected code complete date: 7/1
* Expected release date: 7/7

## About the Service 
**Note**
- This first preview will only contain the inference/query APIs, not the knowledgebase authoring APIs.
- The first preview will be mostly autorest generated

* Link to documentation introducing/describing the service: https://docs.microsoft.com/azure/cognitive-services/qnamaker/overview/overview
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/cognitiveservices-qnamaker/

## About the client library

* Name of the client library: azure.ai.language.questionanswering
* Languages for this review: .NET, Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/c894a6ac975847949cae932b43c45df6
* Link to Champion Scenarios/Quickstart samples: In comment below.

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/0c741e45ab504c499f95a7206e079ce1
* Link to Champion Scenarios/Quickstart samples: In comment below.
  

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 6/30 9am pst

**Comment by annatisch** [comment]
# Champion Scenarios
- query text to answer a question
- query a knowledgebase to answer a question
- query a knowledgebase with a followup/continuation

### Query text to answer a question
```csharp
TextQueryOptions options = new(
    "How long it takes to charge surface?",
    new TextInput[]
    {
        new("1", "Power and charging. It takes two to four hours to charge the Surface Pro 4 battery fully from an empty state. " +
                 "It can take longer if you’re using your Surface for power-intensive activities like gaming or video streaming while you’re charging it."),
        new("2", "You can use the USB port on your Surface Pro 4 power supply to charge other devices, like a phone, while your Surface charges. "+
                 "The USB port on the power supply is only for charging, not for data transfer. If you want to use a USB device, plug it into the USB port on your Surface."),
    }
);

Response<TextAnswers> response = await Client.QueryTextAsync(options);

Assert.That(response.GetRawResponse().Status, Is.EqualTo(200));
Assert.That(response.Value.Answers.Count, Is.EqualTo(3));

IList<TextAnswer> answers = response.Value.Answers.Where(answer => answer.ConfidenceScore > 0.9).ToList();
Assert.That(answers, Has.Count.AtLeast(2));
Assert.That(answers, Has.All.Matches<TextAnswer>(answer => answer.Id == "1" && answer.AnswerSpan.Text == "two to four hours"));
```
### Query a knowledgebase to answer a question
```csharp
 KnowledgebaseQueryOptions options = new("How long should my Surface battery last?")
{
    Top = 3,
    UserId = "sd53lsY=",
    ConfidenceScoreThreshold = 0.2,
    AnswerSpanRequest = new()
    {
        Enable = true,
        ConfidenceScoreThreshold = 0.2,
        TopAnswersWithSpan = 1,
    },
    IncludeUnstructuredSources = true,
};

Response<KnowledgebaseAnswers> response = await Client.QueryKnowledgebaseAsync(TestEnvironment.ProjectName, options, TestEnvironment.DeploymentName);

Assert.That(response.GetRawResponse().Status, Is.EqualTo(200));
Assert.That(response.Value.Answers.Count, Is.EqualTo(3));
```
### Query a knowledgebase to answer a followup question
```csharp
KnowledgebaseQueryOptions options = new("How long it takes to charge Surface?")
{
    Top = 3,
    UserId = "sd53lsY=",
    ConfidenceScoreThreshold = 0.2,
    Context = new(27)
    {
        PreviousUserQuery = "How long should my Surface battery last?",
    },
    AnswerSpanRequest = new()
{
        Enable = true,
        ConfidenceScoreThreshold = 0.2,
        TopAnswersWithSpan = 1,
    },
    IncludeUnstructuredSources = true,
};

Response<KnowledgebaseAnswers> response = await Client.QueryKnowledgebaseAsync(TestEnvironment.ProjectName, options, TestEnvironment.DeploymentName);

Assert.That(response.GetRawResponse().Status, Is.EqualTo(200));
Assert.That(response.Value.Answers.Count, Is.EqualTo(3));
```

**Comment by srnagar** [comment]
[Arch board recording](https://msit.microsoftstream.com/video/ba9c0840-98dc-b561-5710-f1ebd9c4abee)
