### ISSUE TITLE
[JS] Preview Versioning Scheme

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#312]
The spec currently states:

> DO give preview packages a pre-release version of the format `1.0.0-Preview-XX` where `XX` is an integer. Pre-release package versions should not have additional build metadata.
> 
> https://azuresdkspecs.z5.web.core.windows.net/TypeScriptSpec.html#ts-versioning-preview

However, we are currently using a slightly different scheme `1.0.0-preview.X`, for example:

> https://www.npmjs.com/package/@azure/amqp-common/v/1.0.0-preview.2

Differences between these schemes:

1. Spec uses `Preview` while current packages use `preview`
2. Spec uses `-XX` as suffix while current packages use `.X`

I don't feel strongly either way, but we should finalize the decision in the spec and align to it for all packages going forward.  The scheme `1.0.0-preview.X` was chosen to be similar to `typescript` which uses `1.0.0-dev.YYYYMMDD`:

> https://www.npmjs.com/package/typescript/v/3.5.0-dev.20190416

**Comment by adrianhall** [comment]
See docs/engineering-systems/releases.md as well.

**Comment by adrianhall** [comment]
This is fixed in PR #537 - the guidelines were updated to match the releases.md
