### ISSUE TITLE
Board Review: Azure.AI.Personalizer

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk#3124]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: @orenmichaely
* Main contacts: @Mohit-Chakraborty
* Expected code complete date: 07/28/2021
* Expected release date: 08/10/2021

## About the Service 

* Link to documentation introducing/describing the service:
  * https://docs.microsoft.com/en-us/azure/cognitive-services/personalizer/what-is-personalizer
  * https://docs.microsoft.com/en-us/azure/cognitive-services/personalizer/how-personalizer-works
  * https://docs.microsoft.com/en-us/azure/cognitive-services/personalizer/how-to-multi-slot?pivots=programming-language-csharp
* Link to the service REST APIs: https://westus2.dev.cognitive.microsoft.com/docs/services/personalizer-api-v1-1-preview-1
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Azure.AI.Personalizer
* Languages for this review: C#

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/09e2c48254c04858be88a9c4cfed6dbb
* Link to Champion Scenarios/Quickstart samples:
  * [Key parts of single-slot quick-start](https://gist.github.com/orenmichaely/755654ab0b03c3a2d8ed99e617c183b2)
  * [Key parts of multi-slot quick-start](https://gist.github.com/orenmichaely/20fa730c5192f6d56e0fb2740b959cbe)
  * [Personalizer Track 2 SDK Single Slot Quickstart](https://gist.github.com/orenmichaely/9bbe1a1d632949661293a77f0eb6f52e)
  * [Personalizer Track 2 sdk multi slot quickstart](https://gist.github.com/orenmichaely/f1faf248f3a4cc78fab3a59a6f13776c)

**Comment by Mohit-Chakraborty** [comment]
WIP. Need to fill in the details.

**Comment by orenmichaely** [comment]
> Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure.
> 
> **The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue.
> 
> Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.
> 
> To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together. In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.
> 
> For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.
> 
> **Before submitting, ensure you adjust the title of the issue appropriately.**
> 
> **Note that the required material must be included before a meeting can be scheduled.**
> 
> ## Contacts and Timeline
> * Responsible service team: @orenmichaely
> * Main contacts: @Mohit-Chakraborty
> * Expected code complete date:
> * Expected release date:
> 
> ## About the Service
> * Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/cognitive-services/personalizer/what-is-personalizer, https://docs.microsoft.com/en-us/azure/cognitive-services/personalizer/how-personalizer-works, https://docs.microsoft.com/en-us/azure/cognitive-services/personalizer/how-to-multi-slot?pivots=programming-language-csharp
> * Link to the service REST APIs: https://westus2.dev.cognitive.microsoft.com/docs/services/personalizer-api-v1-1-preview-1/operations/get-status 
> * Link to GitHub issue for previous review sessions, if applicable:
> 
> ## About the client library
> * Name of the client library: Azure.AI.Personalizer
> * Languages for this review: C#
> 
> ## Artifacts required (per language)
> Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**
> 
> ### .NET
> * APIView Link: TODO I do not have access to the apiview.dev yet. 
> * Link to Champion Scenarios/Quickstart samples: We have quickstarts written using the new track 2 sdk, but they are not published yet. We can review them in the meeting.
> 
> ### Java
> * APIView Link:
> * Link to Champion Scenarios/Quickstart samples:
> 
> ### Python
> * APIView Link:
> * Link to Champion Scenarios/Quickstart samples:
> 
> ### TypeScript
> * APIView Link:
> * Link to Champion Scenarios/Quickstart samples:
> 
> For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.
> 
> ## Thank you!

**Comment by lilyjma** [comment]
scheduled for 7/19 12-2pm

**Comment by KrzysztofCwalina** [comment]
How was the library created? Is it generated? Where are the sources?

**Comment by orenmichaely** [comment]
> How was the library created? Is it generated? Where are the sources?

https://github.com/Azure/azure-rest-api-specs/pull/15052

This is the Swagger we used to generate the library

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/7aac0840-98dc-b561-907e-f1ebe8f46479)[MS INTERNAL ONLY]
