### ISSUE TITLE
Board Review: Azure.ResourceManager.Core

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk#3142]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: .NET management sdk
* Main contacts: Michael Nash
* Expected code complete date: mid July
* Expected release date: end of July

## About the Service 

* Link to documentation introducing/describing the service: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager.Core/README.md
* Link to the service REST APIs: We are taking a few of the apis from [Resources](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2021-04-01/resources.json) and one from [ManagementGroup](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/managementgroups/resource-manager/Microsoft.Management/stable/2021-04-01/management.json) and moving them to the core package since they are common across all other RPs
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Azure.ResourceManager.Core
* Languages for this review: dotnet

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: WIP https://apiview.dev/Assemblies/Review/65070aab206846e380ea0e17bf9c5b6e
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/resourcemanager/Azure.ResourceManager.Core/samples

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 7/20 and 7/21

**Comment by tg-msft** [comment]
[7/20 Recording](https://msit.microsoftstream.com/video/63d50840-98dc-b561-1eff-f1ebe9b0c237)[MS INTERNAL ONLY]

**Comment by tg-msft** [comment]
[7/21 Recording](https://msit.microsoftstream.com/video/4db40840-98dc-b561-1cdb-f1ebea7a0232)[MS INTERNAL ONLY]
