### ISSUE TITLE
Board Review: Storage Data Movement (DMLib) Track 2 API review (.NET)

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk#3144]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Storage
* Main contacts: @amnguye 
* Expected code complete date: September 2021
* Expected release date: TBD Q4

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-data-movement-library
* Link to the service REST APIs:  N/A based on storage SDK
* Link to GitHub issue for previous review sessions, if applicable:
* Introductory session: https://github.com/Azure/azure-sdk/issues/2444

## About the client library

* Name of the client library: Azure.Storage.DataMovement
* Languages for this review: .NET

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: 
Azure.Storage.Blobs (Contains BlobDirectoryClient changes)- https://apiview.dev/Assemblies/Review/06c0eac8cadd4fb8881ada2cb925fedb?diffRevisionId=73b83e11a5c448d18b8e06d1fa863934&doc=False&diffOnly=true
Azure.Storage.DataMovement - https://apiview.dev/Assemblies/Review/aa3951bfc6e043edb08e18b844c62a21
* Link to Champion Scenarios/Quickstart samples:
Champion scenario - Single Blob Upload:
Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L81
Champion scenario - Single SMB File Upload:
Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L117
Champion scenario - Single Blob Download Sample:
Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L200
Champion scenario - Single Download Sample:
Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L200
Champion scenario - Single Download to Stream Sample:
Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L281

Champion scenario - Single Blob Directory Upload Sample:
Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L348
Champion scenario - Single Blob Directory Copy Sample:
Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L451
Champion scenario - Single Blob Directory Copy Sample:
Track 1 Sample: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L451

Track 2 sample:
Scheduling Jobs:
```
StorageTransferOptions options = new StorageTransferOptions(){MaximumConcurrency = 4};
StorageTransferManager transferManager = new StorageTransferManager(transferOptions: options);

// Schedule Single Blob Upload Job
transferManager.ScheduleUploadAsync(sourceLocalPath, destinationBlobClient1, transferOptions, uploadOptions, cancellationToken);
// Schedule Single Blob Download Job
transferManager.ScheduleDownloadAsync(sourceClient, destinationLocalPath, transferOptions, cancellationToken)
// Schedule Blob Directory Upload Job
transferManager.ScheduleUploadDirectoryAsync(sourceLocalDirectoryPath, destinationBlobDirectoryClient, transferOptions, uploadOptions, cancellationToken)
// Schedule Blob Directory Download Job
transferManager.ScheduleDownloadDirectoryAsync(sourceDirectoryClient, destinationFolderPath, transferOptions, cancellationToken)

// Pause Transfers
transferManager.PauseTransfers();
```
TODO: point to samples within feature/storage/data-movement
Upload Single Blob: https://github.com/amnguye/azure-sdk-for-net/blob/feature/storage/dm-samples/sdk/storage/Azure.Storage.DataMovement/samples/Sample01b_HelloWorldAsync.cs#L26
Download Single Blob: https://github.com/amnguye/azure-sdk-for-net/blob/feature/storage/dm-samples/sdk/storage/Azure.Storage.DataMovement/samples/Sample01b_HelloWorldAsync.cs#L77
Upload Single Directory: https://github.com/amnguye/azure-sdk-for-net/blob/feature/storage/dm-samples/sdk/storage/Azure.Storage.DataMovement/samples/Sample01b_HelloWorldAsync.cs#L77
Download Single Blob Directory: https://github.com/amnguye/azure-sdk-for-net/blob/feature/storage/dm-samples/sdk/storage/Azure.Storage.DataMovement/samples/Sample01b_HelloWorldAsync.cs#L181

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 7/26

**Comment by KrzysztofCwalina** [comment]
Why are the code samples using track 1 APIs?

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/e4a80840-98dc-b561-e534-f1ebee6677ee)[MS INTERNAL ONLY]
