### ISSUE TITLE
Board Review: Attestation - TypeScript

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk#3149]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Microsoft Azure Attestation
* Main contacts: larryo@microsoft.com
* Expected code complete date: 7/4/2021
* Expected release date: 8/5/2021

## About the Service 

* Link to documentation introducing/describing the service: [MAA Service](https://azure.microsoft.com/en-us/services/azure-attestation/)
* Link to the service REST APIs:  [Attestation REST APIs](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/attestation/data-plane/Microsoft.Attestation/stable/2020-10-01/attestation.json)

* Link to GitHub issue for previous review sessions, if applicable:  
[Board Review C#](https://github.com/Azure/azure-sdk/issues/2652)
[Board Review Python](https://github.com/Azure/azure-sdk/issues/2889)

## About the client library

* Name of the client library: Azure-Security-Attestation
* Languages for this review: JavaScript/TypeScript

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/abeaab76f52e4c87af52b8f851eba9ea
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/attestation/attestation/samples-dev

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 7/22

**Comment by srnagar** [comment]
[recording](https://msit.microsoftstream.com/video/12860840-98dc-b562-4d62-f1ebeb3fd398)
