### ISSUE TITLE
[stress testing] Guide + template for building out a stress test

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk#3158]
Each developer on the stress testing v-team will need to:
- [ ] Pick a good scenario for testing (for most, it'll be ensuring that connection recovery works properly over multiple "chaos" sessions with chaos-mesh)
- [ ] Add metrics, events and exception reporting to your application. 
- [ ] Run a sizing experiment with your app to ensure:
   - [ ] Telemetry size makes sense (ie, if you're reporting trace or events ensure you're doing something reasonable)
   - [ ] Telemetry reported is useful and actionable (See #3157)
- [ ] Dockerize your app
- [ ] Kubernetes-ize your app
- [ ] Setup CI for your app

@benbp and @richardpark-msft will get a _very_ short document that guides developers through this process, which will be developed in tandem working with @YijunXieMS  and @yunhaoling.

**Comment by benbp** [comment]
> very short document

I feel attacked 😄

**Comment by richardpark-msft** [comment]
> > very short document
> 
> I feel attacked 😄

My "very short" document is > 2 pages now. Consider it a personal challenge for both of us. :)
