### ISSUE TITLE
Board Review: Azure.ResourceManager.Compute

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk#3162]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: .Net management SDK team
* Main contacts: @ArcturusZhang @m-nash 
* Expected code complete date: 07/28/2021
* Expected release date: 07/30/2021

## About the Service 

* Link to documentation introducing/describing the service: https://github.com/Azure/azure-sdk-for-net/blob/feature/mgmt-track2-compute-2/sdk/compute/Azure.ResourceManager.Compute/README.md
* Link to the service REST APIs: 
    - https://github.com/Azure/azure-rest-api-specs/tree/master/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01
    - https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/disk.json
    - https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30/gallery.json
    - https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30/sharedGallery.json
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: `Azure.ResourceManager.Compute`
* Languages for this review: `.Net`

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/d76d25f493c04772af95076103dca4dc
* Link to Champion Scenarios/Quickstart samples: https://github.com/ArcturusZhang/azure-samples-net-management/blob/compute-sample-update-for-new-track2/samples/compute/create-virtual-machine

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 8/2 4-6pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/63d50840-98dc-b561-9c1b-f1ebf3f75ae7)[MS INTERNAL ONLY]
