### ISSUE TITLE
Board Review: Text Analytics, Extractive summarization 

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk#3167]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Text Analytics
* Main contacts: Deyaaeldeen Almahallawi
* Expected code complete date:  Sep 3rd 2021
* Expected release date: Sep 8th 2021

## About the Service 

* Link to documentation introducing/describing the service: https://review.docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/how-tos/extractive-summarization?branch=pr-en-us-162663
* Link to the service REST APIs:   service is working on it. We might be about to get it before 7/30
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Text Analytics
* Languages for this review: Java/JS,  if time allows, .NET and Python as well

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/b196a5e53fa2441f92e3b1accefa35e7?diffRevisionId=7a2738d1e81f41b78576378c60aa45ec&doc=False&diffOnly=True
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics/samples/Sample8_ExtractSummary.md

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/f62ee261035a44189c597868c7a8a7ee?diffRevisionId=77f323c27c094d4cbf1a0e1234aa62f6&doc=False&diffOnly=True
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/textanalytics/azure-ai-textanalytics/src/samples/java/com/azure/ai/textanalytics/lro/AnalyzeExtractiveSummarization.java

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/f74ef8c4777b408f85dab76b8034cb41?diffRevisionId=5ad3e66d03b7475f984435bcb8dabd25&doc=False&diffOnly=True
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/textanalytics/azure-ai-textanalytics/samples/sample_extract_summary.py
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/8754191c44914b7e88232f8aba5073de?diffRevisionId=ccfa62790be041129639666c88c6da81&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/deyaaeldeen/f0027e710eb71b841ca94cdcdd1f3558

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 8/17

**Comment by maririos** [comment]
[Recording](https://microsoft-my.sharepoint.com/:v:/p/mariari/EWTEfjnXFE5PmRLoPGQOqiIBwVsU5y_FJGNbJPotix61Jw)[MS INTERNAL ONLY]
