### ISSUE TITLE
Board Light Review: Purview Account + Purview Catalog Collection LLC

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#3174]
LLC light review.

# Swagger Purview Account

- https://github.com/Azure/azure-rest-api-specs/tree/master/specification/purview/data-plane/Azure.Analytics.Purview.Account
- Protocol APIView : https://apiview.dev/Assemblies/Review/e7e2c01c655b49fb93fcb6fd814a7063

# Swagger Purview Catalog Collections

- https://github.com/Azure/azure-rest-api-specs/pull/15221
- https://apiview.dev/Assemblies/Review/28d6dbe0a98e4e6d9c9b73700cdcf25f?diffRevisionId=6aaea762ff764a7e85975adbd8ae6ac2&doc=False&diffOnly=True#Azure.PurviewCatalogClientTypesGetTermTemplateDefByGuidoverview

**Comment by lilyjma** [comment]
scheduled for 8/9 3-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/80ba0840-98dc-b561-1139-f1ebf9678e52)[MS INTERNAL ONLY]
