### ISSUE TITLE
Coordinate integration of Cosmos DB emulator for PR validation and CI

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#319]
CosmosDB has an emulator (several of them actually) which runs in a container that we'd like leverage in our PR validation and CI pipelines.  This issue is to track coordinating that work with the libraries team and opening up any follow up work (into new issues) that the engineering system team needs to do.

**Comment by HarshaNalluru** [comment]
Done with https://github.com/Azure/azure-sdk-for-js/pull/4881
