### ISSUE TITLE
[stress testing] Metric naming and design for messages sent and messages received

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk#3200]
As part of the metrics name design for Event Hubs testing, @YijunXieMS found that there were some critical pieces to report for each metric:

- Event Hub (obviously)
- Partition ID (in tests, commonly there at least 3 - is configurable and for some testing, higher is better)
- Consumer Group (generally 1 per app)

@YijunXieMS encoded that information into the metric name itself. This has a nice advantage of making the built-in metrics charting immediately be able to graph all of these metrics together, with the downside that we end up with a lot of separate metrics. 

As we move into the concept of a shared Application Insights cluster we want to make sure we're keeping the advantages of what Yijun came up with while seeing how we can avoid multiplying the number of named metrics.

A suggested design we can try as an alternate:

### MessagesSent

Properties:
* Event Hub
* Partition ID
* Consumer Group

### MessagesReceived

Properties:
* Event Hub
* Partition ID
* Consumer Group 

CC: @jsquire who will have a great amount of interest in what we put in and what we need here.

**Comment by jsquire** [comment]
Here are the things that I'm capturing at the moment, and I think are worthy of consideration for the general case.   Each would ideally have some additional context with it, like a percentage where we can.

### Run Metrics 

- Run Duration _(how long is the scenario configured to run)_
- Elapsed Time _(how long was the scenario running when this snapshot was taken)_
- Total Processor Time _(how much time was spent using CPU resources)_
- Current Memory Use _(memory use right now)_
- Average Memory Use _(average over the duration that the scenario has been running)_
- Peak Memory Use _(the maximum use spike, updated as the scenario runs)_

### Client Health

- Number of Restarts by Client Type_(the number of times an individual client was restarted; broken down by type [producer, processor, consumer, etc])_

### Exception Breakdown

- Total Exceptions for All Operations
- Exceptions for each core activity  _(grouped by type  [publishing, reading, processing])_
- General Exceptions _(exceptions that don't fall into a specific category)_
- Timeout Exceptions
- Operation Canceled Exceptions
- Communication Exceptions
- Service Busy Exceptions

**Comment by jsquire** [comment]
For publishers used in any scenario:

### Publishing Metrics

- Number of Publishers _(the number of producer client instances actively publishing)_
- Concurrent Sends per Publisher
- Target Batch Size _(in bytes)_
- Minimum Message Size _(in bytes)_
- Maximum Message Size _(in bytes)_
- Large Message Factor _(the percentage of messages that use a random size between 80% and 100% of the maximum size)_
- Total Send Attempts
- Total Batches Published _(successful sends)_
- Total Events Published _(successful sends)_
- Average Count of Events per Batch _(successful sends)_
- Average Batch Size _(in bytes; successful sends)_

**Comment by jsquire** [comment]
For consuming scenarios.   Note that I'm assuming that we're tracking the events that we published and are validating them when read to ensure no corruption, that they round-trip in a reasonable period of time, and that they come from the partition we expect them to.

### Processor Metrics

- Number of Processors
- Total Events Read
- Total Events Processed _(successfully by the handler)_
- Event Handler Invocations _(grouped by processor instance)_
- Error Handler Invocations _(grouped by processor instance)_

### Consumer Metrics

- Number of Consumers
- Total Events Read
- Total Events Processed _(successfully)_

### Event Validation Metrics

- Duplicate Events Discarded _(we've seen this event before; not going to validate it)_
- Events Not Read _(we published it, but haven't read it back within some amount of time;  an hour by default)_
- Unexpected Events Read _(we didn't publish it; why is it here?)_
- Events with Invalid Bodies _(the body wasn't in our expected format)_
- Events with Invalid Properties _(the properties didn't match our expectation)_
- Events from the Wrong Partition _(we published to a specific partition; we read this from a different partition)_

**Comment by jsquire** [comment]
This is an example of the metrics output from a processor scenario:

![example](https://user-images.githubusercontent.com/913445/131577419-ac51e58f-5540-4da6-a1da-adc333ad8472.png)
