### ISSUE TITLE
Board Review: Azure-SDK-for CPP Keyvault::Secrets Client 

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk#3204]
Looking for a spot the week of 8/23-8/27

Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: azure-sdk-for-cpp
* Main contacts: Rick Winter , George Arama
* Expected code complete date: 8/23
* Expected release date: Preview 1 in Sept

## About the Service 

* Link to documentation introducing/describing the service:https://github.com/gearama/azure-sdk-for-cpp/blob/main/sdk/keyvault/azure-security-keyvault-secrets/README.md
* Link to the service REST APIs: https://github.com/gearama/azure-sdk-for-cpp/blob/main/sdk/keyvault/azure-security-keyvault-secrets/src/secret_client.cpp
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: azure-sdk-for-cpp
* Languages for this review: CPP

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### CPP 
* APIView Link: https://apiview.dev/Assemblies/Review/d5c322bf55694e7a8587c1afc743d0c7#Azure::Security::KeyVault::Secrets
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/keyvault/azure-security-keyvault-secrets/README.md#examples
### .NET

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/52a90840-98dc-ae70-6de1-f1ec04609733)[MS INTERNAL ONLY]
