### ISSUE TITLE
Change Request: Only require the use of a Client suffix on "entry point" types for C#/All

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk#321]
# Only _require_ the use of a `Client` suffix on "entry point" types

## The Basics

* Which design guideline is affected?
5.2 in the C# section which states 
  > DO name service client types with the Client suffix, e.g. ConfigurationClient.

* Which target languages are affected?
C#, though other languages may want to adopt similar guidance

* Describe the change:
Instead of requiring a `Client` suffix on every type a user can construct to make service calls, we should relax the guideline to only require a `Client` suffix on the types we want to guide users to when getting started.

## Reasoning

The current guideline asserts every type a user can create and use to make service calls should be suffixed with `Client`.  It's a crisp, black and white rule that's easy to follow and enforce from a guidelines perspective.

Some services, like Storage, have an object hierarchy with many similar looking names that can make getting started harder.  If we follow the current guideline, intellisense will be filled with `BlobServiceClient`, `BlobContainerClient`, `BlobClient`, `BlockBlobClient`, `PageBlobClient`, and `AppendBlobClient`.  We want users to start with `BlobServiceClient`.  It's the root of the conceptual hierarchy and works with the connection string provided in the portal.  We've also seen plenty of evidence that developers look for something with the name `Client` when getting started.  Only using the suffix on `BlobServiceClient` and leaving `BlobContainer`, `BlockBlob`, etc., alone sends a very clear message to developers inexperienced with the service.

I propose the following amended guidelines:
  -  DO name service client types with a `Client` suffix if you expect most users to start with them (per connection strings in the portal, via code snippets in your documentation, conceptually if you provide a hierarchy of related services, etc.)
  - CONSIDER adding a `Client` suffix to other service client types if it aids discoverability or comprehension 

Please chime in with suggestions to tighten the language and make it crisper.

**Comment by tg-msft** [comment]
I thought of another way to write the guideline that may work better for everyone:

- Either
  - DO name service client types with a `Client` suffix, e.g. `ConfigurationClient`, or 
  - DO ensure service client types are reachable via `GetFoo(string name)` accessors from a root service client type suffixed with `Client`,
  e.g. a root `BlobServiceClient` with a `GetBlobContainer(string name)` method returning a `BlobContainer` service client type with a `GetBlockBlob(string name)` method returning `BlockBlob` service client type.

This is easy to verify and enforce while still driving customers to the root of a service hierarchy (where their portal connection strings will work, etc.) when that's appropriate for a specific service.

**Comment by KrzysztofCwalina** [comment]
> DO name service client types with a Client suffix, e.g. ConfigurationClient, or

I am not sure if this guideline was meant to accomplish your goal of allowing BlobClient to drop the “client” suffix, but it does not seem to do it. BlobClient is a service client, as today, “service client” is defined as a type that calls into a REST endpoint.

> DO ensure service client types are reachable via GetFoo(string name) accessors from a root service client type suffixed with Client, e.g. a root BlobServiceClient with a GetBlobContainer(string name) method returning a BlobContainer service client type with a GetBlockBlob(string name) method returning BlockBlob service client type.

> This reinforces what I said above, i.e. you call the types returned from these Get methods “service client types”

**Comment by KrzysztofCwalina** [comment]
> DO name service client types with a Client suffix if you expect most users to start with them (per connection strings in the portal, via code snippets in your documentation, conceptually if you provide a hierarchy of related services, etc.)
CONSIDER adding a Client suffix to other service client types if it aids discoverability or comprehension

These are very vague. It's basically equivalent to saying "use client suffix to alert customers that this is a type they should look into"

**Comment by KrzysztofCwalina** [comment]
... and so, what about:

1. There are hierarchical services and "flat" services.
2. Types that call services are call clients. 
3. Client types in flat services must be called with "Client" suffix.
4. Root client types in hierarchical services must be called with "Client" suffix.
5. Non-root client types in hierarchical services TBD (either must or must not).

**Comment by tg-msft** [comment]
Sure, I think that works fine if the 5th line allows us to call it `BlockBlob` instead of `BlockBlobClient` since it's a non-root client type in the conceptual hiearchy.

**Comment by adrianhall** [comment]
Architectural Board Decision: Hold off on this until user study data has confirmed details.

**Comment by adrianhall** [comment]
BOARD DECISION:
- The current guidelines are ok.  (Storage is explicitly ok, per @tg-msft )
- There is an issue around guidelines for things like ChangeFeedProcessor (cosmos) and EventProcessor (event hubs), TransferManager (Storage) that still need to be dealt with.
- We should have a specific issue / discussion on where you CAN call Client
- We should also have a specific issue on what other entry points (non-service-calling) can be called
    - For example, a Spring Repository implementation.
