### ISSUE TITLE
Board Review: ResponseError and DateTimeRange in Azure Core

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk#3221]
## Contacts and Timeline

* Responsible service team: Azure SDK
* Main contacts: @pakrym @rakshith91 @KarishmaGhiya @srnagar 

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Azure Core
* Languages for this review: C#, Java, Python and JS

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Response Error
REST API guideline recommends services to return errors in a standard format - https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#errorresponse--object

In this review, we'll look into creating a type in Azure Core to represent this error. This type can then be used in all services that use this error format.

### DateTimeRange
Introducing a new type in Azure Core to represent a time interval similar to the one defined in ISO 8601.

> A time interval is the intervening time between two time points. The amount of intervening time is expressed by a duration (as described in the previous section). The two time points (start and end) are expressed by either a combined date and time representation or just a date representation.
> 
> There are four ways to express a time interval:
> 
> Start and end, such as "2007-03-01T13:00:00Z/2008-05-11T15:30:00Z"
> Start and duration, such as "2007-03-01T13:00:00Z/P1Y2M10DT2H30M"
> Duration and end, such as "P1Y2M10DT2H30M/2008-05-11T15:30:00Z"
> Duration only, such as "P1Y2M10DT2H30M", with additional context information

### .NET

* Time interval - [API view](https://apiview.dev/Assemblies/Review/b67e68cfee4841bda045f895c90ad383#Azure.Core.DateTimeRange)
* Response error - [API view](https://apiview.dev/Assemblies/Review/b67e68cfee4841bda045f895c90ad383#Azure.Core.ResponseError)

### Java

* Time interval - [API view](https://apiview.dev/Assemblies/Review/4dba784c8ef84375b3736b68cfde3890?diffRevisionId=c7c3ccec0d314d93a5e25a2c18ae8956&doc=False&diffOnly=True)
* Response error - [API view](https://apiview.dev/Assemblies/Review/ce1fd1f49fae4aa7bffc859881c6af0a?diffRevisionId=26e416a467e74ce683da912fb13ee5c6&doc=False&diffOnly=True)

### Python

* Time interval - API view
* Response error - [API view](https://apiview.dev/Assemblies/Review/6ae91cfc0084460eb0b0f284b903916e#azure.core.exceptions.ODataV4Format)

Note: no new time interval type for python and an already existing type for response error
  
### TypeScript

* Time interval - API view
* Response error - [API view](https://apiview.dev/Assemblies/Review/cfe31fd1f2e84233affec5ccd2643a80?doc=False)

**Comment by lilyjma** [comment]
SCHEDULED FOR 8/30 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/2bdb0840-98dc-ae76-92f8-f1ec1a3a8ac3)[MS INTERNAL ONLY]

**Comment by srnagar** [comment]
Closing the issue as the review is complete and we have guidance on how to proceed (see recording).
