### ISSUE TITLE
[stress-testing] Review Event Hubs metrics, pass 2

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk#3223]
This is a continuation of the discussion for Event Hubs telemetry, started with #3155.

This second pass will be with @jsquire. All that discussion and design will also end up in the same spot: [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/494/Event-Hubs-Telemetry)

**Comment by jsquire** [comment]
To my knowledge, this is complete;  details can be found in the comments for #3200
