### ISSUE TITLE
[stress-testing] Custom orchestration

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk#3224]
This is a placeholder for what needs to be a larger discussion on writing customer orchestrators. @jsquire brought this up and we want to track this for the longer-term goals of the stress testing project.

Our current stress testing infrastructure currently is not dynamic. The resources (number of pods) is dictated when the pods are launched.

Event Hubs has a custom load balancing algorithm, that coordinates around external storage. This logic is all built into the client SDKs and is something we would like to build additional testing infrastructure around.

The end result of this is that we can dynamically bring up and bring down consumers. 

How "dynamic" this needs to be helps a bit with costing. If we're willing to simply accept a periodic increase and decrease we believe (@benbp to confirm) that we can simply scale up and scale down a [ReplicasSet](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset). 

We can also, as @benbp mentions below, continue to use Jobs, and set their parallelism factor. Both of these are native to Kubernetes, and would require no extra work on our part aside from calling Kubernetes APIs to drive them.

The orchestrator would be similar to what we have for chaos-mesh - a sidecar or external service that has permission to talk to the kubernetes API. 

If we need to drive this more from the individual stress tests we can consider how we want to enable that communication, how much we need, etc...

**Comment by richardpark-msft** [comment]
@benbp:

> Kubernetes jobs DO support scaling, just not via the /scale API. We can edit the parallelism field in the job spec to modify the pod count.

I don't know why I keep forgetting that. That would work just as well as what I suggested and fits in nicely with our templates. I'll update the issue text above.

> I think, in addition to a decision on orchestration, a related decision to make is a recommended approach to IPC (e.g. sockets, http endpoints, etc.)

Let's file a separate issue for that. They can clearly be developed independently of each other, and IPC isn't just an orchestration concern. This will also be a good opportunity to make sure we're taking advantage of Azure primitives to handle this rather than rolling our own thing.

**Comment by benbp** [comment]
> Let's file a separate issue for that. They can clearly be developed independently of each other, and IPC isn't just an orchestration concern.

I'm opening to filing an issue but I think it may be slightly premature. I want to dive in a little more to @jsquire's scenarios first to see what we really need and then inform the design guidance from there.

>  This will also be a good opportunity to make sure we're taking advantage of Azure primitives to handle this rather than rolling our own thing.

My initial response to this is we should prefer Kubernetes primitives where possible for orchestration specific stuff (and by that I really just mean OS and networking), but maybe we're better off just using something like pub/sub with eventhub to get the dogfood value? I do want to be wary of introducing too many cross-SDK dependencies from a stress test isolation standpoint.

**Comment by benbp** [comment]
Closing in favor of language specific issues around orchestration scenarios.
