### ISSUE TITLE
[stress-testing] Windows support

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk#3227]
The current solution for stress testing is a combination of two factors:
- Kubernetes, for hosting and running of containers
- [chaos-mesh](https://chaos-mesh.org/), a system we can run within Kubernetes, to inject faults (network outages)

For Linux, both of these are fully supported (as Linux is a first-class citizen for chaos-mesh).

For Windows we can still _host_ containers (this is supported within AKS) but we don't yet have the ability to inject faults.

From a first release perspective, this seems okay. We haven't prevented Windows testing.

This issue will serve as a unifying spot for us to consider what the costs and pieces we'd need to support Windows containers would be. 

Mid-term, I think we can break this apart into two pieces: hosting within our existing stress test infrastructure and fault injection.

**Comment by benbp** [comment]
My initial inclination here is to add support upstream to chaos mesh for windows. Skimming the repo, they have a daemon that lives on each kubernetes node and talks to the controller via grpc. I assume windows support would involve making sure the daemon can start and run on windows (e.g. any OS-specific setup steps), and then adding new fault/chaos types for windows one by one. Even better would be being able to use the same chaos config for fault types and having some sort of node/OS provider model, but that might be a monumental task depending on the code.

I think it's probably worth taking a day to investigate/scope the work and see if we like the upstream approach. If we do end up going that route, we should reach out to the chaos mesh developers to see if it's already on their roadmap and/or what other design requirements they would have. Depending on the extra work to get it supported upstream, it may be simpler to write a separate chaos controller, but it would be really nice to be able to use the same exact chaos configs to make it easier to stress the same SDK behavior across OSes.

**Comment by richardpark-msft** [comment]
@benbp : I've added it to the backlog milestone for now so we don't forget it. I'm 100% comfortable with waiting until after phase 1 for any work in this area.

**Comment by kurtzeborn** [comment]
No one's asked for windows containers in 2 years (since this was opened).
