### ISSUE TITLE
Release Azure.Core Library

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk#323]
Azure.Core will have sufficient features to support AzConfig, KeyVault and Storage.

### Current status

Item  | .NET | Java | Python | TypeScript 
------------ | ------------- | ------------ | -------------  | ------------- 
In central repo | ✅  | ✅ | 🚧 | ❌ 
API design proposal |   🚧   | 🚧 | 🚧 | 🚧 
API review |  ❌   | ❌  | ❌  | ❌  
Code complete |  ❌   | ❌  | ❌  | ❌  
Docs |  ❌   | ❌  | ❌  | ❌

**Comment by Petermarcu** [comment]
@AlexGhiondea I believe this is complete right?
