### ISSUE TITLE
Board Review: ACS UI Library

### ISSUE THREAD

**Issue by ddematheu2** [Azure/azure-sdk#3231]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: ACS Web UI
* Main contacts: dademath alkwa
* Expected code complete date: 05-26-2021
* Expected release date: 11-03-2021

## About the Service 

* Link to documentation introducing/describing the service: https://azure.github.io/communication-ui-library/
* Link to the service REST APIs: N/A
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/2775

## About the client library

* Name of the client library: communication-react
* Languages for this review: javascript

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/42fe51ace1e24184a42351ff89044352/398758ee1cab4631a5b6070aecf9889e?doc=False
*Diff since last review: https://apiview.dev/Assemblies/Review/42fe51ace1e24184a42351ff89044352/398758ee1cab4631a5b6070aecf9889e?diffRevisionId=3a45d5b187874292a05433238ea15854&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples: 

Core documentation:https://azure.github.io/communication-ui-library/

Composite Scenarios: Calling and Chat
- Enables developers to integrate a full communication experience into their existing application with only a couple lines of code.
- Composite supports core calling and chat use cases including video rendering, call controls, chat sending/receiving. 
- UI Library provides interface for developers to programmatically access composite state and date through Adapter.

UI Component Scenarios: Calling and Chat
-  Discrete components for key pieces of the communication experience
- Developer can arrange/compose components based on their specification
- UI Library provides help stateful client and helper hooks/providers for developer to connect components to the underlying ACS service
-  Stateful client provides developers access to data and state for the components.

Share Scenarios: Theming, Localization, Custom Data Models, Accessibility, Styling
- Developers can provide their own theme parameters based on Fluent UI Themes
- Developers can provide their own localization strings or use pre-generated strings from us
- Developer can inject their own data model for users in the experience including display name and avatar
- Developer can provide styling parameters with custom CSS to modify components to their specification

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 9/16

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/12e10840-98dc-ae70-7d89-f1ec174dd560)[MS INTERNAL ONLY]
