### ISSUE TITLE
Board Review: Introducing ACS Mobile UI Library

### ISSUE THREAD

**Issue by ddematheu2** [Azure/azure-sdk#3232]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: ACS Mobile UI
* Main contacts: dademath mo.wayne
* Expected GA date for this library: H1 2022

## About the Service 

* Link to documentation introducing/describing the service: https://azure.github.io/communication-ui-library/?path=/story/overview--page , this is the documentation for web, but the core context and use cases is very similar.
* Link to the service REST APIs:  N/A
* Is the goal to release a Public Preview, Private Preview, or GA? Public Preview

## About the client library

* Name of client library: ACS Mobile UI Library
* Link to library reference documentation: N/A
* Is there an existing SDK library? If yes, provide link: N/A

## Step 1: Champion Scenarios 
* Champion scenario 1: Add a calling experience to your existing applications
    * See [PPT](https://microsoft-my.sharepoint-df.com/:p:/p/dademath/ESs1PqwzEr9DtL2-KmMoKmcBg_nYGkkWo7XCr18I-0Rngg?e=H22scQ)

## Step 2: Quickstart Samples (Optional)
* See [PPT](https://microsoft-my.sharepoint-df.com/:p:/p/dademath/ESs1PqwzEr9DtL2-KmMoKmcBg_nYGkkWo7XCr18I-0Rngg?e=H22scQ)

**Comment by kyle-patterson** [comment]
Scheduled for 9/21

**Comment by kyle-patterson** [comment]
Rescheduled to 9/28

**Comment by palatter** [comment]
API View for iOS

https://apiview.dev/Assemblies/Review/4213efb995464aa28bb6d2b69cb02156

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/12fd99ff-0300-948e-727d-f1ec20af381c)[MS INTERNAL ONLY]
