### ISSUE TITLE
Board Review: Azure.Identity for Go

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk#3239]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team:
* Main contacts:
* Expected code complete date:
* Expected release date:

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

### Go

* APIView Link: https://apiview.dev/Assemblies/Review/fbb412c44ad249d5a608240c118190c3
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/chlowell/8b50a2904560a041280ead756371656d

**Comment by kyle-patterson** [comment]
Scheduled for 8/31

@RickWinter please make sure the links to the apis and champion scenarios are added

**Comment by kyle-patterson** [comment]
Rescheduled to 9/16

**Comment by kyle-patterson** [comment]
Rescheduled for 9/20

**Comment by kyle-patterson** [comment]
Rescheduled for 10/4

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/ca8b0840-98dc-948e-fabf-f1ec2611a19f)[MS INTERNAL ONLY]
