### ISSUE TITLE
Release Cosmos Track 2 Library

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk#326]
Release CosmosDB Track 2 library for the following:
- [ ] .NET
- [x] Java
- [x] Python
- [x] JS

### Current status

Item  | .NET | Java | Python | TypeScript 
------------ | ------------- | ------------ | -------------  | ------------- 
In central repo |  🚧   | 🚧| 🚧| 🚧
API design proposal |    ❌  |  ❌ | 🚧 |  ❌ 
API review |  ❌   | ❌  | 🚧  | ❌  
Code complete |  ❌   | ❌  | ❌  | ❌  
Docs |  ❌   | ❌  | ❌  | ❌

**Comment by Petermarcu** [comment]
Closing as we are not using this to track the epic anymore
