### ISSUE TITLE
Board Review:  Short LROs

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk#3263]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## About the API

This review concerns the concept of the "short LRO", which is an operation or operation-like service call which will always return a completed operation. 

**The motivation**:
It's not uncommon for either explicitly defined long running operations or "pseduo LROs" to have an expected wait time of less than a few seconds. For these cases Short LROs make it easier to treat these methods more like traditional "immediate" responses where we don't want developers to have to monitor status or poll for completion themselves.

Short LROs are different from typical LROs in the following ways:
- These operations are expected to complete quickly (no more than a few seconds)
- The operation names do not have a "Start" prefix
- The `Operation` instance returned from the method is always complete and does not require the developer to ever wait on a poller.
- ~~Exceptions from Short LROs contain an operationId so that the failed operation can be inspected in failure conditions~~

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: (Core changes) [ApiView](https://apiview.dev/Assemblies/Review/251830024df74a89b8a25e3ead702daa?diffRevisionId=cace76e254e34c47acfc42933d1ba038&doc=False&diffOnly=True) ([and here](https://apiview.dev/Assemblies/Review/24d5afae5f0f42608668471d00d4d5af?diffRevisionId=e9cb51acdf0844119942a29151cfe030&doc=False&diffOnly=True))
* Link to Champion Scenarios/Quickstart samples: [gist](https://gist.github.com/christothes/e17e2aa076bcf5bdfc6b8f7841798eb1)

### Java

* APIView Link: [Confidential ledger API view with short LRO](https://apiview.dev/Assemblies/Review/93ab1eedd0c64de0ac3310ff1c5f134d#59257fbd4a0041cfa42fa303c492cde9)
* Link to Champion Scenarios/Quickstart samples: [Sample](https://github.com/jianghaolu/azure-sdk-for-java/blob/feature/jianghao/lro-confidentialledger/sdk/confidentialledger/azure-security-confidentialledger/src/samples/java/com/azure/security/confidentialledger/PostLedgerEntries.java#L64)

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link: (Text Analytics changes) [ApiView](https://apiview.dev/Assemblies/Review/3cf8eea001ff424686ae9043a0121f04?diffRevisionId=6c8c81238cb64b17a319cf216bd29d3d&doc=False&diffOnly=True)
* Link to Champion Scenarios/Quickstart samples: [Sample](https://github.com/Azure/azure-sdk-for-js/blob/40ea6cabe61b6b69c1ce6664511900b9c4cd9781/sdk/textanalytics/ai-text-analytics/samples/v5/typescript/src/andWait.ts)

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 9/15

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/5c890840-98dc-ae72-1757-f1ec167cb73c)[MS INTERNAL ONLY]
