### ISSUE TITLE
[stress testing] Event Hubs - send and receive for 1 week with network stress

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk#3266]
Send and receive for 1 week, with network stress via chaos-mesh.

This is a very basic test - single program, single process, send and receive. The only goal here is just to make sure that your library can weather the storm of network disconnects and reconnects.

Some bonus points, if you get the first basic bit done:
- [ ] Break out your producer and consumer into separate processes
- [ ] Have your consumers scale up and down on a regular basis (test load balancing)

**Comment by benbp** [comment]
These types of scenarios are completed in the language repos.
