### ISSUE TITLE
Board Review: Introducing Azure Maps library

### ISSUE THREAD

**Issue by daniel-rocha** [Azure/azure-sdk#3271]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Azure Maps (lbsdevs@microsoft.com)
* Main contacts: daroch@, tarasvozniuk@, jsedlak@
* Expected GA date for this library: Q4 CY 21

## About the Service 

* Link to documentation introducing/describing the service: https://azure.microsoft.com/en-us/services/azure-maps/
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/maps/
* Is the goal to release a Public Preview, Private Preview, or GA? GA. The service has existed now for about 5 years, but only recently we have started the work to match the Swagger specs to the actual payloads exchanged by the API, and thus be able to generate REST SDKs for the service.

## About the client library

* Name of client library: Azure Maps Service Library
* Link to library reference documentation: 
* Is there an existing SDK library? If yes, provide link: Not in GA. We have preliminary versions of Track 2 SDKs for all languages, though the samples aren't still completed (specially for C#). 

For all languages, Render and Search are the key scenarios so they should be the focus.

https://github.com/ambientlight/azure-sdk-for-go-samples/tree/feat/maps-samples/maps 
https://github.com/alankashiwa/azure-sdk-for-js/tree/onboard-maps-data-sdk/sdk/maps/maps-search/samples
https://github.com/alextts627/azure-sdk-for-python/tree/maps-sdk-onboard/sdk/maps/azure-maps-samples
https://github.com/daniel-rocha/azure-sdk-for-java/tree/daroch/feature/maps-sdk/sdk/maps/azure-maps-examples

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?

80% of our API calls are in two buckets: Search (street address -> lat, long, lat long -> street address, points of interest, batch search) and Render (get maps tiles, tilesets, attribution data). 

2. Who is the end-user of the application (the developer's customer)?

Enterprise developers that want to use Maps & Geospatial APIs in their application.

3. What features of the API need to be explained in the sample so that someone could use this API in real app?

Render and Search are 80%+ of our calls. Maps Creator is a very small service but also has a little bit of a more complicated flow so it should probably worth explain - but it's not a champion scenario for now.

4. How does the **authentication** workflow look? 

Shared Key and Azure AD authentication are both supported. Fairly standard mechanism described here: https://docs.microsoft.com/en-us/azure/azure-maps/how-to-manage-authentication
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1 - Search APIs
    * Link to library’s sample folder: Links to samples posted above.
* Champion scenario 2 - Render APIs
    * Link to library’s sample folder: Links to samples posted above.

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 

Maps Management API is described here in detail: https://docs.microsoft.com/en-us/rest/api/maps-management/ . This is the control plane for Azure Maps.

Maps Creator API has CRUD operations described here: https://docs.microsoft.com/en-us/rest/api/maps-creator/ but this is still a data-plane API.

Some of the draft SDKs have samples for all scenarios, including control-plane and creator.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/d9a20840-98dc-ae73-5cb2-f1ec0cc96ba2)[MS INTERNAL ONLY]
