### ISSUE TITLE
Board Review: Storage Automated Transactional CRC64

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk#3275]
## Contacts and Timeline

* Responsible service team: Storage DevEx
* Main contacts: @jaschrep-msft @amishra-dev 
* Expected code complete date: Aug
* Expected release date: Sept/Oct

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/rest/api/storageservices/
* Link to the service REST APIs:
  * https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob
  * https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob
  * https://docs.microsoft.com/en-us/rest/api/storageservices/put-block
  * https://docs.microsoft.com/en-us/rest/api/storageservices/put-page
  * https://docs.microsoft.com/en-us/rest/api/storageservices/append-block
  * https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/read
  * https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update
  * https://docs.microsoft.com/en-us/rest/api/storageservices/get-file
  * https://docs.microsoft.com/en-us/rest/api/storageservices/put-range

## About the client library

* Name of the client library: Azure.Storage.Common, Azure.Storage.Blobs, Azure.Storage.Files.DataLake, Azure.Storage.Files.Shares
* Languages for this review: .NET

## Artifacts required (per language)

***IMPORTANT:*** Two API surface options are being presented, as suggested in a preliminary meeting. One where these new options are grouped into an organizational class, and one where they are presented flat on individual method options classes. Rev 0 is baseline, rev 1 is grouped, and rev 2 is flat.
* Grouped
  * Pros:
    * obvious what options are dependent on what other options.
    * we can default users to CRC64 (COGS benefit) when they opt-in to transactional hashing.
  * Con: user will always have access to some flags not all methods can make use of (i.e. methods that abstract away `Response` cannot use `DeferValidation` because the caller cannot access the hash themselves).
* Flat
  * Pro: control exactly when advanced options are presented.
  * Cons:
    * no obvious grouping between linked parameters; we rely on docstrings.
    * We cannot default an opt-in to CRC64; we must use docstrings to guide users there.

### .NET

* APIView Link:
  * [Common](https://apiview.dev/Assemblies/Review/eab10fd410594236a6156d062685041c/838b5540d391484cb6c550c4caff5bcf)
  * [Blobs](https://apiview.dev/Assemblies/Review/ddb677a105e74ec6b6d898899dd6aa3c/a45ecc38d8064bfd92a7d4488e601a7e)
  * [DataLake](https://apiview.dev/Assemblies/Review/004e8a26b3f54b90847d912769d46ee1/51950238ea8d4ea5a5f6d1fcb8544320)
  * [Shares](https://apiview.dev/Assemblies/Review/b681d0a0e8f44cb49ea6b701aa65ef36)
* Link to Champion Scenarios/Quickstart samples: https://microsoft-my.sharepoint.com/:w:/p/jaschrep/EYNAe3vx10NDjoiX5nFIkG0B-BFc2xPjWje-Xoa5LKz7gA?e=BTLPsl (samples section at the bottom with behavioral descriptions; samples written using grouped options)

**Comment by kyle-patterson** [comment]
Scheduled for 9/1

**Comment by tg-msft** [comment]
I'd also love to discuss https://github.com/Azure/azure-sdk-for-net/issues/19384 if there's time in this review as it's trying to solve a similar problem.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/b8920840-98dc-ae70-21f2-f1ec0b729db2)[MS INTERNAL ONLY]
