### ISSUE TITLE
update github.io documentation to show new(track2) libraries first

### ISSUE THREAD

**Issue by elraikhm** [Azure/azure-sdk#3282]
Package indexes show a list of packages in random order, for example,  https://azure.github.io/azure-sdk-for-net/keyvault.html shows an older (track1) package first. We suggest 
1) adding "latest" keyword to the new packages
2) sort packages on the page starting with the latest on top.
3) remove retired/ unsupported packages from the index on the left.

**Comment by kurtzeborn** [comment]
We held this one for a while so we could figure out how to prioritize this vs. docs.micorosft.com which is our preferred way for devs to find docs on our libraries.  For this issue, here's what's needed (following the numbering scheme above):
1. [do nothing] The latest version is already at the top of the lists and uncollapsed.  Adding the word "latest" to these versions as well will add clutter to the page with limited value (it's readily obvious that the highest/latest versions are the ones not collapsed.
2. This is what we want to fix with this issue.  The track 1 packages should separated from track 1 packages.  Let's list the track 2 packages alphabetically and have them listed before any track 1 packages.  Track 1 packages should be at the bottom of the page.  (Note: we may chose to hide the track 1 packages completely at some point in the future)
3. [do nothing] Knowing which packages are fully deprecated in the docs generation process is nearly impossible at this point.  So we're skipping this one for now.

**Comment by danieljurek** [comment]
I believe CSV metadata should have `true` in the `New` column for track 2 packages. Those could be sorted higher first.

**Comment by sima-zhu** [comment]
Working on a fix for this.

**Comment by sima-zhu** [comment]
It is currently listing in order, client, mgmt, track2, track1.

**Comment by sima-zhu** [comment]
Merged the PR. Now it is sorting by track 2 first.
<img width="292" alt="image" src="https://user-images.githubusercontent.com/48036328/163267220-78f03510-0e95-481e-a5b9-8806685b5ea0.png">
Closed the issue. Feel free to reopen if spots any other issue
