### ISSUE TITLE
Change Request: Support Identity-Based Connection Strings for all languages

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk#3288]
## The Basics
 
* Which design guideline is affected?
Not supporting connections strings in general, and connection strings that indicate the use of managed identity for authentication in particular.
 
* Which target languages are affected?
ALL
 
* Describe the change:
We should support constructing clients from connection strings; connection string support should expand from ones based on secrets to ones based on identity (aka secretless connection strings)

**(Existing) secretful connection string**
DefaultEndpointsProtocol=https;AccountName=storagesample;AccountKey=<account-key>

**(New) secretless connection string**
DefaultEndpointsProtocol=https;AccountName=storagesample; Authentication=ActiveDirectoryManagedIdentity [;ClientId=<client-id>]

 
## Reasoning:
 
**The problem**: Current Azure SDK supports identity-based connections to storage and service buses.  But customers must rewrite their code to take advantage – different constructors (from the classical build-the-client-from-a-connection-string constructors); different application settings for applications and libraries.  This issue became pronounced when working on identity-based binding for Azure Functions: we were able to ship an experience, but a lot of extra work was done in the function extension layer to compensate the lack of support; different settings / conventions were introduced; the result is an overall jarring experience and so far the adoption has been low.
 
Prior Art: SQL introduced native support for identity-based connection strings recently (e.g. `Data Source=<>;Initial Catalog = <>; Authentication=ActiveDirectoryManagedIdentity`); this is similar to the Windows integrated-auth that has been in SQL for decades.  Without any code change, the standard SqlConnection constructor just works with this connection string.   Interestingly, this was actually revealed to us via an external contribution to Azure Durable Function, around the time of its GA release; almost without any code change, we got “free” support of secretless connection for the SQL provider!   Previously, Service Bus has a similar support; it was dropped in Track 2 SDK, but a recent scan of Azure Functions revealed that hundreds of currently deployed functions still use this.
 
## Benefits of such identity-based connection strings:
- Better user experience for Azure Functions
  - Easier transition, same set of settings.
  - The familiar (easily-automatable) experience of copying (secretless) connection strings to the app settings stays
  - No need to force customers to think about which storage services (blob? Table? Queue? Files) are at play (implementation details for many services / libraries) or try to derive setting names.  The problem with Track 2 SDK is exemplified by the Azure Function work, where the runtime for various bindings use a collections of different storage services in combination.
- Cleaner architecture for Secretless Azure Functions.
  - No need to do special things in storage extension / invent new convention.
- Wider adoption of managed identities
  - Customer can simply reuse existing code and the familiar constructors (eg new blobClient() ).
- Late Binding / Deployment Time Decision
  - Customer can switch between secretful and secretless at ease.  Easier transition between multiple environments without code change.
- Smoother Upgrade path from Track 1 to Track 2

**Comment by kyle-patterson** [comment]
Scheduled for 9/30

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/bd980840-98dc-948e-a7d8-f1ec22cad681)[MS INTERNAL ONLY]
