### ISSUE TITLE
Board Review: Text Analytics, Custom analysis on entities, single classification and multiple classifications

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk#3294]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Text Analytics
* Main contacts: Deyaaeldeen Almahallawi and Shawn Fang
* Expected code complete date: 10/1/2021
* Expected release date: 10/6/2021

## About the Service 

* Link to documentation introducing/describing the service: https://microsoft.sharepoint-df.com/:w:/r/teams/ALPSAzureLanguagePillars/_layouts/15/guestaccess.aspx?e=HuUZbs&wdLOR=cB49DE9FE-7A4D-40D3-A3F3-53BD341F0F53&share=EfwEUdwXjkFMv9nu4l8Do7UBi0VIFGG0Ygm8_kdeEkJ4Hg
* Link to the service REST APIs:   https://github.com/Azure/azure-rest-api-specs/blob/c46283d507bc79eddc6b5f89f6663ee907bd30de/specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.2-preview.2/TextAnalytics.json
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Text Analytics
* Languages for this review: Java/JS

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/b196a5e53fa2441f92e3b1accefa35e7?diffRevisionId=9b991f39874d424c8040d73c1f69dbfe&doc=False&diffOnly=True
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/f62ee261035a44189c597868c7a8a7ee?diffRevisionId=6a15977bd7974ddca84777f7975941ae&doc=False&diffOnly=True
* Link to Champion Scenarios/Quickstart samples: [Single classification](https://github.com/Azure/azure-sdk-for-java/blob/b36ac03f323601ea3f90217de95d6a47c20b6d4b/sdk/textanalytics/azure-ai-textanalytics/src/samples/java/com/azure/ai/textanalytics/lro/ClassifyDocumentSingleCategory.java), [Multi classification](https://github.com/Azure/azure-sdk-for-java/blob/b36ac03f323601ea3f90217de95d6a47c20b6d4b/sdk/textanalytics/azure-ai-textanalytics/src/samples/java/com/azure/ai/textanalytics/lro/ClassifyDocumentMultiCategories.java), [Custom entities recognition](https://github.com/Azure/azure-sdk-for-java/blob/b36ac03f323601ea3f90217de95d6a47c20b6d4b/sdk/textanalytics/azure-ai-textanalytics/src/samples/java/com/azure/ai/textanalytics/lro/RecognizeCustomEntitiesAction.java)

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/f74ef8c4777b408f85dab76b8034cb41?diffRevisionId=35ba324ebdf74fdfb548334a5f279bf1&doc=False&diffOnly=True
* Link to Champion Scenarios/Quickstart samples: [Single classification](https://github.com/Azure/azure-sdk-for-python/blob/bc032f49b94f6e182ea178e2cc74caf22b290a53/sdk/textanalytics/azure-ai-textanalytics/samples/sample_classify_document_single_category.py), [Multi classification](https://github.com/Azure/azure-sdk-for-python/blob/bc032f49b94f6e182ea178e2cc74caf22b290a53/sdk/textanalytics/azure-ai-textanalytics/samples/sample_classify_document_multi_categories.py), [Custom entities recognition](https://github.com/Azure/azure-sdk-for-python/blob/331233b4823f6609337ca140ea638b029cb2dea4/sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_custom_entities.py)
  
### TypeScript

* APIView Link: [Custom Text API View](https://apiview.dev/Assemblies/Review/8754191c44914b7e88232f8aba5073de?diffRevisionId=1d6eefc1d5554d08bbc44593306c97b2&doc=False&diffOnly=True)
* Link to Champion Scenarios/Quickstart samples: [Custom Text Sample](https://github.com/Azure/azure-sdk-for-js/blob/a8d23ef82c861f2b1143969849ab1d5d16cb3792/sdk/textanalytics/ai-text-analytics/samples/v5/typescript/src/customText.ts)

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 9/23

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/a9b80840-98dc-ae70-6eb6-f1ec1cbf2b22)[MS INTERNAL ONLY]
