### ISSUE TITLE
Prevent merging pull requests until validation build succeeds

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#33]
We should prevent merging GitHub pull requests until the Azure Pipelines validation build succeeds.

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-public?view=vsts&tabs=github#protect-branches-with-validation-builds

## Repos
* [ ] azure-sdk-for-net
* [ ] azure-sdk-for-java
* [ ] azure-sdk-for-python
* [ ] azure-sdk-for-js

**Comment by kurtzeborn** [comment]
We know validation is enabled for all of the repos, and we've now verified that it's required as well.
