### ISSUE TITLE
Board Review: Schema Registry v1.0

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk#3303]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Schema Registry
* Main contacts: @deyaaeldeen 
* Expected code complete date: 10/01/2021
* Expected release date: October milestone

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/event-hubs/schema-registry-overview
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/pull/15855
* Link to GitHub issue for previous review sessions, if applicable:  This package will implement caching so it will also benefit from https://github.com/Azure/azure-sdk/issues/3293.

## About the client library

* Name of the client library: @azure/schema-registry
* Languages for this review: .NET, Java, JavaScript, and Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: 
  [SchemaRegistry](https://apiview.dev/Assemblies/Review/c4afdf3055914defaf3cfeb4492496a0)
  [Avro Serializer](https://apiview.dev/Assemblies/Review/946ec06afc3141dbb8d09712b9276942)
* Link to Champion Scenarios/Quickstart samples:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/schemaregistry/Azure.Data.SchemaRegistry/README.md
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/schemaregistry/Microsoft.Azure.Data.SchemaRegistry.ApacheAvro/README.md

### Java

* APIView Link: 
  * [azure-data-schemaregistry](https://apiview.dev/Assemblies/Review/0615cbf9af5e4f5caa0b113ae279492e)
  * [azure-data-schemaregistry-avro](https://apiview.dev/Assemblies/Review/78411ac51aab4118ae803236fd0f8e8e)
* Link to Champion Scenarios/Quickstart samples:
  * [azure-data-schemaregistry](https://github.com/conniey/azure-sdk-for-java/blob/schema-registry-align/sdk/schemaregistry/azure-data-schemaregistry/README.md)
  * [azure-data-schemaregistry-avro](https://github.com/conniey/azure-sdk-for-java/blob/schema-registry-align/sdk/schemaregistry/azure-data-schemaregistry-avro/README.md)

### Python

* APIView Link:
  - [azure-schemaregistry](https://apiview.dev/Assemblies/Review/21d5a1c19a6845cf9549faf0e30db2e1)
  - [azure-schemaregistry-avroserializer](https://apiview.dev/Assemblies/Review/a235ef6b8d2a4ab1a2c56d76d1a01b87)
* Link to Champion Scenarios/Quickstart samples:
  - [azure-schemaregistry](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/schemaregistry/azure-schemaregistry/samples/sync_samples/schema_registry.py)
  - [azure-schemaregistry-avroserializer](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/schemaregistry/azure-schemaregistry-avroserializer/samples/avro_serializer.py)
  
### TypeScript

* APIView Link:
  - [schema-registry](https://apiview.dev/Assemblies/Review/59ef79b661c14f378a8def1aa599305a?diffRevisionId=46eb44ede88247f880bc6655de40ebc7&doc=False&diffOnly=False)
  - [schema-registry-avro](https://apiview.dev/Assemblies/Review/0ff89eb70d9c4411a6f3a93aa6203bd4?diffRevisionId=e2fe6330804047adb2253fd18c9c44a6&doc=False&diffOnly=False)
* Link to Champion Scenarios/Quickstart samples: 
  - [schema-registry](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/schemaregistry/schema-registry/samples/v1/typescript/src/schemaRegistrySample.ts)
  - [schema-registry-avro](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/schemaregistry/schema-registry-avro/samples/v1/typescript/src/schemaRegistryAvroSample.ts)

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 9/14

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/d0970840-98dc-ae72-4d57-f1ec15b33104)[MS INTERNAL ONLY]
