### ISSUE TITLE
Board Review: Azure Maps Geocoding API v2

### ISSUE THREAD

**Issue by hongweis** [Azure/azure-sdk#3309]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Maps
* Main contacts: hongweis, jsedlak, daroch, evaou
* Expected code complete date: Q2 FY21 
* Expected release date: Q2 FY21

## About the Service 

* Link to documentation introducing/describing the service:  https://azure.microsoft.com/en-us/services/azure-maps/
* Link to the service REST APIs:  https://docs.microsoft.com/en-us/rest/api/maps/
* Link to GitHub issue for previous review sessions, if applicable:  
 
  This is a new major version of API for Azure Maps search service.   We have created swagger file for the API and would like to review with review board.  We will create new version of client library to come with the new API too.

## About the client library

* Name of the client library:  Azure Maps (still in development)
* Languages for this review:

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
As swagger and API design is still in progress, I'm holding on scheduling this review. @hongweis please confirm when the service team is nearing completion and I can schedule, thanks!
