### ISSUE TITLE
Board Review: Microsoft.Azure.WebPubSub.AspNetCore

### ISSUE THREAD

**Issue by JialinXin** [Azure/azure-sdk#3311]
## General description:
The library is a subscriber to help parse upstream request under Service protocols(CloudEvents) and simplify the ability to handle upstream abuse protection request for customers.

----
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure SignalR Service (vscsignalr)
* Main contacts: Jialin Xin(jixin), Liangying Wei(lianwei)
* Expected code complete date: PR ready - [#23385](https://github.com/Azure/azure-sdk-for-net/pull/23385)
* Expected release date: 9/17

## About the Service 

* Link to documentation introducing/describing the service: https://aka.ms/awps/doc
* Link to the service REST APIs: The library is for subscriber that doesn't need public REST API support. REST API is for publisher and already available in package `Azure.Messaging.WebPubSub`.
* Link to GitHub issue for previous review sessions, if applicable: 

## About the client library

* Name of the client library: Microsoft.Azure.WebPubSub.AspNetCore
* Languages for this review: C#

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/57fc8bd7c6bd4479aeb2bcd2367d4717
* Link to Champion Scenarios/Quickstart samples: https://github.com/JialinXin/azure-sdk-for-net/blob/awps-update/sdk/webpubsub/Microsoft.Azure.WebPubSub.AspNetCore/tests/Samples/WebPubSubSample.HelloWorld.cs

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 9/29

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/d1e90840-98dc-948e-678d-f1ec218da9dd)[MS INTERNAL ONLY]
