### ISSUE TITLE
Board Light Review: Purview Metadata Policies

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#3334]
LLC light review.

This is a new package addition to Catalog, Scanning and Account (fourth package).

- https://github.com/Azure/azure-rest-api-specs/pull/14938
- APIView: https://apiview.dev/Assemblies/Review/58cbec03e643445f89e79e4032cbf2ed

We should take this opportunity to review the new APIs in Catalog:
- Catalog: https://apiview.dev/Assemblies/Review/28d6dbe0a98e4e6d9c9b73700cdcf25f?diffRevisionId=bbadbfa8726e48279ade2124bf56b96f&doc=False&diffOnly=False

## Description from service team

Azure Purview moved to support authorization & access control of Purview Studio from IAM (control plane) to Azure Purview Data Plane Metadata Policies is about managing fine grained access control over these collections to users, groups or service principals within your enterprise via Purview APIs.

From Naga as example:
ARM does not have fine grain ACLs.. So I want to assign "Naga" as Data Curator to glossary.finance and "Laurent" as Data Curator to glossary.sales I don't think there is way to handle it in ARM. Another reason I believe is data policies are inside Purview so trying to align metadata policies at the same place.

**Comment by kyle-patterson** [comment]
Scheduled for 9/21

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/37bb0840-98dc-ae70-a968-f1ec1b309465)[MS INTERNAL ONLY]
