### ISSUE TITLE
Board Review: Discussion about breaking changes (Tables)

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk#3356]
Note: This topic shouldn't require a full schedule slot - would it be possible to fit it in after an existing schedule item that may run short?

Across languages in the Tables SDK, [a bug was reported](https://github.com/Azure/azure-sdk-for-python/issues/20301) which causes round-tripping issues for table entities where the `PartitionKey` or `RowKey` values contain a single quote character.

This bug impacts any API where the partition/row key is used to format the URL - i.e. upsert, update and delete (note: not​ create, where these values only live in the payload).

The fix is a simple one - duplicate the single quote character to escape it - however this does not appear to be the documented behavior of the REST API. This behavior is only mentioned in reference to [formatting query strings](https://docs.microsoft.com/en-us/rest/api/storageservices/querying-tables-and-entities#single-quote-).

So the question is whether we should consider this a breaking change - and therefore, whether the fix should be opt-in or opt-out. 

There are currently two groups of customers that could be impacted:
- Customers who hit the error, and worked around it by manually escaping quote characters in their keys. To do this, they would need to have correctly interpreted the somewhat cryptic syntax error, and known that the single quote characters needed to be duplicated (which, as mentioned, does not appear to be documented).
- Customers who were actually using duplicate single quote characters in the keys. This seems like an unlikely scenario - and these customers are likely already broken, as their keys will be assumed by the service to be escaped.

**Comment by kyle-patterson** [comment]
Scheduled for 10/6

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/df8b0840-98dc-948e-c31a-f1ec26f86630)[MS INTERNAL ONLY]
