### ISSUE TITLE
Board Review: Azure-cosmos for Python

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-sdk#336]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

## The Basics

* Service team responsible for the client library: CosmosDB
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/cosmos-db/introduction
* Contact email (if service team, provide PM and Dev Lead): chrande
* Expected code complete date: 5/31
* Expected release date: ~june

## About this client library

* Name of the client library: azure-cosmos
* Target language for this review: Python
* Other languages that are to be targeted:
    *Java, .Net and Javascript
* Link to the service REST APIs:
* Link to the reference documentation:
* Link to several samples:

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Examples might be "Update Firmware", "Download a file", "Recognize faces in a list of pictures".  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Describe the champion scenario
    * Link to the code sample

_ Repeat for each champion scenario _

**Comment by adrianhall** [comment]
Scheduled for 5/10 @ 9:30am

**Comment by adrianhall** [comment]
Feedback from the board review:

[] @christopheranderson to get adparch access to the raw user study data
[] @christopheranderson and @johanste to talk paging offline
[] @christopheranderson to send out what user studies he has planned
[] @adrianhall to set up a discussion on taking dependencies on Azure Core libraries for Cosmos
[] @adrianhall to invite @christopheranderson  to the board meeting for #298 
[] @adrianhall to produce PR conflating README repo and design guidelines links into single table
[] @adrianhall to investigate solutions for design guidelines compliance checking
