### ISSUE TITLE
Board Review: azure-cosmosdb for java

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-sdk#337]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

## The Basics

* Service team responsible for the client library: CosmosDB
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/cosmos-db/introduction
* Contact email (if service team, provide PM and Dev Lead): chrande
* Expected code complete date: 5/31
* Expected release date: ~june

## About this client library

* Name of the client library: azure-cosmosdb
* Target language for this review: Java
* Other languages that are to be targeted:
    * JavaScript Python and .Net.
* Link to the service REST APIs:
* Link to the reference documentation:
* Link to several samples:

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Examples might be "Update Firmware", "Download a file", "Recognize faces in a list of pictures".  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Describe the champion scenario
    * Link to the code sample

_ Repeat for each champion scenario _

**Comment by adrianhall** [comment]
Assigned to 5/14 2pm-4pm slot.

Please ensure the champion scenarios are filled in prior to the meeting.

**Comment by adrianhall** [comment]
Thank you for attending the review.  It looks like good progress has been made, and we look forward to continuing the work together.
