### ISSUE TITLE
Board Review: Azure Cosmos DB Go SDK preview - azcosmos

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-sdk#3379]
First preview of the Azure Cosmos Go SDK.

## Contacts and Timeline

* Responsible service team: Azure Cosmos
* Main contacts: Matias Quaranta
* Expected release date: November 2021 (Ignite)

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/cosmos-db/introduction
* Link to the service REST APIs:  https://docs.microsoft.com/en-us/rest/api/cosmos-db/

## About the client library

* Name of the client library: Azure Cosmos
* Languages for this review: Go

## Artifacts required

* APIView Link: https://apiview.dev/Assemblies/Review/ab1ff440d77c46989cebf3f5d1c1b415
* Examples: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/data/azcosmos/README.md#examples
* More examples: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/data/azcosmos/example_test.go

**Comment by kyle-patterson** [comment]
Scheduled for 10/14
