### ISSUE TITLE
Board Review: Schema Registry Payload Format

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk#3385]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Schema Registry
* Main contacts: @deyaaeldeen 
* Expected code complete date: 10/01/2021
* Expected release date: October milestone

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/event-hubs/schema-registry-overview
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/pull/15855
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/3303

## About the client library

* Name of the client library: @azure/schema-registry
 
We want to discuss how to format the payload sent to and received from the service. Currently, the payload is segmented into three parts, the first 4 bytes contains a format indicator, the next 32 contains the schema ID, and the rest contain the actual data. We would like discuss whether to keep the current format, use [Cloud Events](https://github.com/cloudevents/spec/blob/v1.0.1/spec.md), move some/every thing to be part of the envelope, or pursue another direction entirely.

**Comment by JoshLove-msft** [comment]
[Here](https://gist.github.com/JoshLove-msft/6e7c8824e85d4f57c1560aee21fbf175) is an initial investigation into our various options, starting with the current state and looking at two alternate proposals.

**Comment by kyle-patterson** [comment]
Scheduled for 9/29

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/d1e90840-98dc-948e-f67e-f1ec218d2b27)[MS INTERNAL ONLY]
