### ISSUE TITLE
Release Event Hub Track 2 Library Preview 1

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk#339]
Goal

Release a client library for the following:
- [ ] .NET
- [ ] Java
- [ ] TS
- [ ] Python

### Current status

Item | .NET | Java | Python | TypeScript
-- | -- | -- | -- | --
In central repo | ✅ | ✅ | ✅ | ✅
API design proposal | ✅ | ✅ | ✅ | ✅
API review | ✅ | ✅ | ✅ | ✅
Code complete | ✅ | ✅ | ✅ | ✅
Docs | ✅ | ✅  | ✅ | ✅
Samples | ✅ | ✅ | ✅| ✅

**Comment by ramya-rao-a** [comment]
The first preview has now been released. Details can be found at

https://aka.ms/azure-sdk-preview1-java
https://aka.ms/azure-sdk-preview1-js
https://aka.ms/azure-sdk-preview1-net
https://aka.ms/azure-sdk-preview1-python
