### ISSUE TITLE
Board Review: @azure/keyvault-keys

### ISSUE THREAD

**Issue by maorleger** [Azure/azure-sdk#3396]
## Contacts and Timeline

* Responsible service team: Key Vault / Managed HSM
* Main contacts: @maorleger @heaths @jlichwa @vickm @herveyw-msft
* Expected code complete date: 2021-10-01
* Expected release date: ~2021-11-08~ TBD

## About the Service 

* Link to documentation introducing/describing the service: 
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.3-preview/keys.json
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: @azure/keyvault-keys 
* Languages for this review: C#, Java, Python, TypeScript

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/d2d05cf175c7478184662d580a300e68?diffRevisionId=e229c861eb9940de96b6adc1d5a8e5b1&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Keys/samples/Sample8_KeyRotation.md (links to sync and async sample sources therein)

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/c8986bdf9191490b875c0a925246193d?diffRevisionId=ec4d9dfda8184e3a9f519e5dc459d73b&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples: [sync sample](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/KeyRotation.java), [async sample](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/KeyRotationAsync.java)

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/2fe1d980066340af8e70b56592afe76a?diffRevisionId=a617921fa5c74b1c99d169f84f9ab047&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples: [sync sample](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-keys/samples/key_rotation.py), [async sample](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-keys/samples/key_rotation_async.py)
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/00523582d8434db8a0b8c31319db2dcb?diffRevisionId=0ec6bf9a0c6747e7aecf30987adbc256&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-keys/samples-dev/keyRotation.ts

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/7b7f0840-98dc-948e-9779-f1ec31f52eb3)[MS INTERNAL ONLY]
