### ISSUE TITLE
Board Light Review: Device Update

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#3398]
Review of Swagger for LLC release review

- Swagger: https://github.com/Azure/azure-rest-api-specs-pr/pull/4891
- LLC APIView: https://apiview.dev/Assemblies/Review/b140fe258e3049f8bbe831e65ad8ade2

READ ONLY API VIEW. PLEASE DO NOT COMMENT ON THOSE VIEWS, BUT ON THE LLC VIEW INSTEAD:
- C#: https://apiview.dev/Assemblies/Review/20bfb7d5d6994473b212743f72f3e9b6
- Java: https://apiview.dev/Assemblies/Review/ee953fd28fcb4cc698d28ca1bc331f15
- Python: https://apiview.dev/Assemblies/Review/ddb5a6897dec45dbbee5702b32e1beb2
- JS: https://apiview.dev/Assemblies/Review/cc1b64c29b954dee9e5a4aeaac339977

C# Samples: https://github.com/Azure/azure-sdk-for-net-pr/blob/71828e3ac5ea3cd3ff4215cb27c73159d09d4505/sdk/deviceupdate/Azure.IoT.DeviceUpdate/samples/DeviceUpdateClientSample/ContentFactory.cs

Scheduling: anytime after 10/4

**Comment by kyle-patterson** [comment]
Scheduled for 10/18
