### ISSUE TITLE
Board Review: azservicebus (Azure Service Bus SDK for Go)

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk#3407]
## Contacts and Timeline

* Responsible service team: adpgo
* Main contacts: richardpark-msft
* Expected code complete date: NA
* Expected release date: NA

## About the Service 

* Link to documentation introducing/describing the service: https://azure.microsoft.com/en-us/services/service-bus/
* Link to the service REST APIs: NA
* Link to GitHub issue for previous review sessions, if applicable:  NA

## About the client library

* Name of the client library: github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus
* Languages for this review: Go

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Go

* APIView Link: [link](https://apiview.dev/Assemblies/Review/8016d8f02db04f08a4a9db346cd16918)
* Link to Champion Scenarios/Quickstart samples:
* Samples:
  * [AdminClient](https://github.com/richardpark-msft/azure-sdk-for-go/blob/apigen/sdk/messaging/azservicebus/example_admin_client_test.go)
  * [Receiver](https://github.com/richardpark-msft/azure-sdk-for-go/blob/apigen/sdk/messaging/azservicebus/example_receiver_test.go)
  * [Sender](https://github.com/richardpark-msft/azure-sdk-for-go/blob/apigen/sdk/messaging/azservicebus/example_sender_test.go)
  * [SessionReceiver](https://github.com/richardpark-msft/azure-sdk-for-go/blob/apigen/sdk/messaging/azservicebus/example_session_receiver_test.go)
  * [readme samples](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus#readme-examples)

**Comment by lilyjma** [comment]
scheduled for 11/2 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/f4ae0840-98dc-8491-c62d-f1ec3c3396d2)[MS INTERNAL ONLY]
