### ISSUE TITLE
README.md should include related packages with description of how they are related

### ISSUE THREAD

**Issue by diberry** [Azure/azure-sdk#3418]
The service is split between a minimum of 2 packages (management and data). Some services have more SDKs (azure monitor query) or don't provide SDKS for pre-existing data planes (mongodb). It should be part of the initial information (above the fold) for a customer to understand how the SDK they are looking at is related to other Microsoft/Azure SDKs and SDKs they may be expected to use but provided by other packages. 

@ramya-rao-a Any suggestions?

**Comment by ramya-rao-a** [comment]
That is a fair ask, thanks @diberry!

@lilyjma Can you pick this up with the PM who is handling docs in the team?

**Comment by ramya-rao-a** [comment]
cc @scottaddie
