### ISSUE TITLE
Board Review: Question Answering (inference only)

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk#3419]
## Contacts and Timeline

* Responsible service team: Question Answering service (formerly QnA Maker)
* Main contacts: @rokulka
* Expected code complete date: Early October
* Expected release date: Early October

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/azure/cognitive-services/qnamaker/
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/feature/cognitiveservices/language/specification/cognitiveservices/data-plane/Language/preview/2021-07-15-preview/questionanswering.json
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Azure.AI.Language.QuestionAnswering
* Languages for this review: C#, Python

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/aeb7f6b7027b458e8dddd1d49a5956d9
* Link to Champion Scenarios/Quickstart samples:
  * https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.QuestionAnswering/README.md#examples
  * https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.QuestionAnswering/samples/README.md

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/2a6c2364c93744d4b40796ef482e3833
* Link to Champion Scenarios/Quickstart samples:
  * https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-questionanswering/README.md#examples
  * https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-questionanswering/samples/README.md

/cc @iscai-msft @annatisch @rokulka

**Comment by kyle-patterson** [comment]
Scheduled for 10/19
