### ISSUE TITLE
Azure SDK Perf MQ Work 2021

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk#3421]
This MQ item covers the task to add support for Performance Testing AMQP SDKs in the Performance framework across our tier - 1 languages. 

Achieving this will:
1. Unblock the automation of AMQP Performance tests.

2. Allow to catch any regressions introduced via sensitive code changes (memory management, scheduling etc.) in AMQP SDK codebase. Eliminate Performance hits seen by our customers in the newly shipped  AMQP SDKs.

3.  Write Consistent perf framework backed performance tests for AMQP SDKs across tier-1 languages. Currently the AMQP SDK owners have to write manual standalone application based performance tests which doesn't guarantee consistency across tier-1 languages.

**Comment by kurtzeborn** [comment]
Closing this epic.  All issues except for one ([this one](https://github.com/Azure/azure-sdk-for-java/issues/24454)) are resolved.
