### ISSUE TITLE
Azure.ResourceManager.Resources.SubscriptionData returning wrong values

### ISSUE THREAD

**Issue by amantur** [Azure/azure-sdk#3434]
I am trying to get all the subscriptions defined in my tenant. I'm using the following code:

           var armClient = new ArmClient(new DefaultAzureCredential());

            var subs = armClient.GetSubscriptions();

            await foreach (var s in subs.GetAllAsync())
            {
                Console.WriteLine($"{s.Data.Name} --- {s.Data.SubscriptionGuid}");
            }

But for some reason what is getting printed to console is:

`aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee --- example.sub.1`

It is returning GUID for `Data.Name` property and name for `Data.SubscriptionGuid` property.

I'm using 1.0.0.0-beta.4

**Comment by bunkrur** [comment]
I believe this is fixed : https://github.com/Azure/azure-sdk-for-net/pull/25704
