### ISSUE TITLE
Create/locate a tool for issue migration between repos

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#348]
During migration of, say, `cosmosDB`, we don't want to do this manually.

**Comment by kurtzeborn** [comment]
I found this which is worth looking at: https://github.com/IQAndreas/github-issues-import

**Comment by kurtzeborn** [comment]
Closing this issue.  When we bring code into our mono-repos, we actually don't want to bulk move issues into the repo.  We'd rather someone familiar with the project move them manually and "triage" each one to ensure they still apply to the new project in the new location.
