### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - Auth Custom Teams Endpoint (Java, .NET, JS & Python)

### ISSUE THREAD

**Issue by jorgegarchirota** [Azure/azure-sdk#3480]
- Service team responsible for the client library: **ACS Auth**
- Link to documentation describing the service:
  - [Build a custom Teams endpoint](https://docs.microsoft.com/en-us/azure/communication-services/concepts/teams-endpoint)
    - Quickstart: [Set up and manage Teams access tokens (currently Private Preview)](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/manage-teams-identity) + [PR for Public Preview](https://github.com/MicrosoftDocs/azure-docs-pr/pull/175406/files)
- Contact emails:
  - PM: Tomas Chladek
  - EM: Sofia Rico Sanchez
  - Dev Lead: Jiri Sofka
  - SDKs main point of contact: Petr Svihlik
- Name of the client library: Azure.Communication.Identity
- Languages for this review: C#, JS/TS, Java
- Link to the service REST APIs: [Swagger (related PR)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/Identity/preview/2021-10-31-preview/CommunicationIdentity.json)
- API view artifacts
  - [.NET](https://apiview.dev/Assemblies/Review/290c367d508340a386fc4a42d7474f36?diffRevisionId=9f515894992d4133b7fcfe6231bcba28&doc=False&diffOnly=False)
    - [Private Preview API](https://github.com/Azure/azure-sdk-for-net/blob/b150b82e1ece1452d30e8584f7f4943c2f1ec673/sdk/communication/Azure.Communication.Identity/src/CommunicationIdentityClient.cs#L288-L322) + [Public Preview diff](https://github.com/Azure/azure-sdk-for-net/pull/24665/files), [rename to ExchangeTeamsUserAadToken](https://github.com/Azure/azure-sdk-for-net/pull/24846#issuecomment-948489542), [remove private preview version](https://github.com/Azure/azure-sdk-for-net/pull/24871#pullrequestreview-786597971)
  - [JS/TS](https://apiview.dev/Assemblies/Review/a12adf98a8fa447d96268e4f87ffb1ea?diffRevisionId=c54b4dc6aba6430ca2a95ee5e7971bc6&doc=False&diffOnly=False)
    - [Private Preview API](https://github.com/Azure/azure-sdk-for-js/blob/0afa58e9a8072a4f9a112b4feb37aabcd988e42f/sdk/communication/communication-identity/src/communicationIdentityClient.ts#L254-L283) + [Public Preview diff](https://github.com/Azure/azure-sdk-for-js/pull/18163/files), [rename to exchangeTeamsUserAadToken](https://github.com/Azure/azure-sdk-for-js/pull/18306)
  - [Java](https://apiview.dev/Assemblies/Review/de8c7baf6c554fb9be958ac68eda74cd?diffRevisionId=dd785fda560541f9b520fdb86646d713&doc=False&diffOnly=False)
    - [rename to exchangeTeamsUserAadToken](https://github.com/Azure/azure-sdk-for-java/pull/24949)
  - [Python](https://apiview.dev/Assemblies/Review/391f9f85fa864638bd6b77f1a8333433?diffOnly=True&diffRevisionId=bb059d4c5ac44b588bd5d4248bb02b63)
- Champion scenarios:
  - The main goal of this feature is to allow developers who use ACS (directly or via SDKs) to build and integrate a custom user interface for calling functionality with Microsoft 365 Teams identities.
  - A typical scenario is building an attendant console (e.g. for receptionists to be able to accept incoming calls and redirect them to the right person). All scenarios are described in the [business specification](https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/EYHFHvosgGtKp8jx_BNYeIwB4T_IQ6gBShBXx-DbaN9YPg?e=9AubaT)
  - Developers will use the new API to exchange AAD Access tokens (of AAD users with a Teams license) for Skypetokens. These Skypetokens can then be used to call ACS APIs directly or via SDKs. An example for TS: 
![a](https://user-images.githubusercontent.com/9810625/137179712-f6da5fc9-c303-4ad8-856e-ad1136d1462e.png)
  - The changes we’re making for [Public Preview](https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/EY6jQuuSo9NApQLDLp527mYBDDO17TSe7wMQWAZio5D_zQ?e=Kvcbbx&wdLOR=cE54385A5-8790-4C5F-8346-A21CE3478C5C) are mostly driven by the need of enabling consumption-based billing for scenarios that originate in apps built on top of ACS SDKs. [Public preview doc](https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/EY6jQuuSo9NApQLDLp527mYBDDO17TSe7wMQWAZio5D_zQ?e=u1tvQn)
- Timeline:
  - We are targeting the 31st of October with the SDKs
  - We are targeting December 2021 with the Public Preview of the feature as a whole

**Comment by petrsvihlik** [comment]
- All four API Views were approved
- we also had a follow-up discussion on the overall architecture of the feature and there are no unanswered questions left

--> closing
