### ISSUE TITLE
Add latest git tag for all package releases

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#351]
During our releases we create tags like `<package name>_<package version>` which is great but there are some scenarios were just having a `<package name>` tag which points to the latest version will be useful. For example for links in packages that link back to the location of the source code in the repo would benefit from a latest link so that the link will always work and point to the latest source code for a package if we happen to move the source around in the latest master.

For example:

Instead of:
`https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/servicebus/service-bus`

we would have:
`https://github.com/Azure/azure-sdk-for-js/tree/%40azure/service-bus/sdk/servicebus/service-bus`

We could also use the version tag but that would mean we need to predict the version we are going to release and potentially even duplicate that version in the link and version properties in some languages.

**Comment by weshaggard** [comment]
@scbedd after your other work for generating the "latest" version tags for docs do you still think there are interesting scenarios to have a latest tag as well? I'm kind of leaning towards no as I don't know of any cases were we would actually make use of them at this point.

**Comment by scbedd** [comment]
@weshaggard I am of the belief that we can close this. 

1. We publish `latest` documentation now
2. We have a methodology to _get_ the latest using said published documentation `versions` file

I have not heard a realistic request for the usage of the tag itself.

**Comment by weshaggard** [comment]
OK lets close this and revisit if we end up having a use case for the tag.
