### ISSUE TITLE
Naming convention for service name in our repos

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#356]
As part of the repo structure guidelines we have been hitting a number of questions on what we should exactly name the `<service name>` folders in the guidelines outlined at https://github.com/Azure/azure-sdk/blob/master/docs/engineering-system/repo-structure.md.

Currently the guideline is:

`<service name>` - Should be the short name for the azure service. It will be used to group all the various packages for a given service, including the management and data-plane packages, as well as any multi-api (e.g. or different profile versions (e.g AzureStack). Any shared artifacts like release notes or versions should go into this root repo. These names should match across all the different language repos and by default should be what is in the specification folder in the azure-rest-api-specs repo.

However the names that are in the specification repo and in the different languages currently are not always consistent. In fact other places are also inconsistent like the docs vs the portal. On top of that a lot of the names are all lowercase with no word separators which can make them difficult to read in a number of cases. 

One proposal would be to use the names that we list on our public Azure product page at https://azure.microsoft.com/en-us/services/. They seem to use lower [kebab-casing](https://en.wikipedia.org/wiki/Kebab_case) some examples that keep coming up would be as follows:

- `event-hubs` https://azure.microsoft.com/en-us/services/event-hubs/
- `service-bus` https://azure.microsoft.com/en-us/services/service-bus/
- `cosmos-db` https://azure.microsoft.com/en-us/services/cosmos-db/
- `key-vault` https://azure.microsoft.com/en-us/services/key-vault/
- `storage` https://azure.microsoft.com/en-us/services/storage/

So if we use those names then the root sdk examples for all the languages would be:

```
sdk\event-hubs
sdk\service-bus
sdk\cosmos-db
sdk\key-vault
sdk\stoarge
```

@adrianhall is this a topic we could get into an upcoming review slot?

Arch Board PTAL @KrzysztofCwalina @bterlson @JeffreyRichter @JonathanGiles @johanste

**Comment by KrzysztofCwalina** [comment]
I think .NET developers would prefer .NET casing, i.e. pascal casing.

**Comment by adrianhall** [comment]
The current guideline is:

**Comment by adrianhall** [comment]
The current guideline is:

```
pick a package name that allows the consumer to tie the namespace to the service being 
used.  As a default, use the compressed service name at the end of the namespace.  The 
namespace does **NOT** change when the branding of the product changes, so avoid the 
use of marketing names that may change.  (See below for examples).
```

However, I defer "compressed" to the language-specific guidelines - whether it's camel case or kebab case or snake case or whatever.  I understand that the GitHub repo should be named consistently, so your engineering system guidelines should define what "compressed" means in that context.   That's a job for @maggiepint

**Comment by maggiepint** [comment]
There is I suppose an option where the repo for the language follows the convention that the language follows for packages. Trying to think what the impact of this choice would be on the build system or reporting over time.

**Comment by maggiepint** [comment]
Further thought on this - we have chosen snake case for the names of the repos themselves. I'm pretty sure we're not going to change that, so maybe snake case is the best choice for the subfolders as well? I think it creates consistency across a lot of urls which is always good.

**Comment by JonathanGiles** [comment]
For the Java perspective - I have no opinion nor preference, and I don't believe Java users will either. In this case, I vote for consistency across all languages for the reason Maggie states.

**Comment by adrianhall** [comment]
I believe we are all sold on this now.

Within the repostructure.md file is the following statement:

```
These names should match across all the different language repos and by default should be what is in the specificiation folder in the [azure-rest-api-specs](https://github.com/azure/azure-rest-api-specs) repo.
```

This should cover all the cases.  If not, put in a PR to adjust the repostructure.md (which is moving on Monday to docs/policies/repostructure.md)
