### ISSUE TITLE
Package listings table design

### ISSUE THREAD

**Issue by diberry** [Azure/azure-sdk#3561]
@weshaggard Here is the suggestion I mentioned in email for [package listings](https://docs.microsoft.com/en-us/azure/developer/javascript/azure-sdk-library-package-index) reducing to a single table:

| Name | Package | Docs | Source |
| ---- | ------- | ---- | ------ |
| Anomaly Detector | [@azure/ai-anomaly-detector]() 3.0.0-beta.3 | [Service]() - [API]() | GitHub [3.0.0-beta.3]() |
| *App Configuration | [@azure/app-configuration]() 1.3.0| [Service]() - [API]() | GitHub [1.3.0]() |

* indicates a new service

![image](https://user-images.githubusercontent.com/41597107/140391327-c48ec19a-de9f-44b6-a0aa-1f8d135e44d3.png)

**Comment by vhvb1989** [comment]
is this to update/replace this:
https://vhvb1989.github.io/azure-sdk/releases/latest/js.html ???

**Comment by diberry** [comment]
@vhvb1989 No - this is for a work stream Wes hands off to be included in docs.microsoft.com.

**Comment by weshaggard** [comment]
@diberry correct me if I'm wrong but you are only interested in doing this for JS? Should we do it for .NET, python, and java as well?

**Comment by diberry** [comment]
Yes, but your question makes me think I've missed something. I've looked across the -new and -all files. I think the only thing I would change is the column heading of "Package" to "npm Package" or "NuGet Package" and remove the package name from the rows. 

Is there something else I'm missing?

**Comment by weshaggard** [comment]
The only think that might happen is that the name of some packages in some languages can become pretty long so the column might become pretty long.

**Comment by diberry** [comment]
I think, please correct me if I'm wrong @ramya-rao-a and @weshaggard - the idea was that the customer could see the package name in the table. 

Is there another way to show both package name and service name? 

Or could we, just thinking..., have an H2 for the service name, then the table just cover the package name, not the service name so the table would have 1 fewer columns and the page would have direct links into a section that listed all packages for a service?

**Comment by weshaggard** [comment]
For reference in case you don't already know you can see https://azure.github.io/azure-sdk/ which contains the package index we host. I don't know that I want to fully generate that in MD for the docs site though because that requires more then just MD. Another option would be simply remove the tables from the docs site and replace it with a link to our package index on github.io, although I'm sure how folks on the docs side would like that or not.

**Comment by diberry** [comment]
@weshaggard let me ask my team. If they have no objections, removing it and the maintenance is a good idea.

**Comment by diberry** [comment]
@weshaggard - I'll close this issue as it is outside the scope of the current semester.
