### ISSUE TITLE
Change Request: Remove need for isolatedModules in tsconfig for Typescript

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk#360]
The typescript guidelines suggest to set `isolatedModules` to `true`.
But doing this conflicts with our need to have declarations generated.

See https://github.com/Azure/azure-sdk-for-js/issues/2655#issuecomment-490286162

Therefore, requesting to remove this particular guideline

cc @bterlson

**Comment by bterlson** [comment]
This has been removed!
