### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - Calling SDK  (Android/iOS/JS)  emergency call feature GA review

### ISSUE THREAD

**Issue by jorgegarchirota** [Azure/azure-sdk#3628]
## Contacts and Timeline

* Responsible service team:  marius.ungureanu@microsoft.com
* Main contacts: zehangzheng@microsoft.com, ajaych@microsoft.com, rcole@microsoft.com
* Expected code complete date: Nov 19th 2021
* Expected release date: Dec 10th 2021

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/communication-services/overview
* Link to documentation on how to add PSTN calling to application: https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/pstn-call?pivots=platform-web

## About the client library

* Name of the client library: Communication Calling
* Languages for this review: iOS, Java (Android) & TS/JS

## Change being introduced

This change introduces EmergencyCallOptions property as an `optional` property as part of existing `CallAgentOptions` objects.

The intent of the new property is to signal to the stack what is the end customer current location country. This is needed for regulatory compliance in the case of end customer trying to access Emergency Services using ACS PSTN offering

### Java (Android)

* [APIView Link](https://apiview.dev/Assemblies/Review/9b2892c2377f4d75af411209ad37f6c0?diffRevisionId=44e4d0c55621449da0e3199f89d13a16&doc=False&diffOnly=True)

* Link to Champion Scenarios/Quickstart samples:

-  Purpose is to support E911 calling in client sdk by specifying emergency country code for PSTN calling

```java
CallClient callClient = new CallClient();
EmergencyCallOptions emergencyOptions = new EmergencyCallOptions();
emergencyOptions.setCountryCode("US");
CallAgentOptions callAgentOptions = new CallAgentOptions().setEmergencyCallOptions(emergencyOptions);
callClient.createCallAgent(appContext, tokenCredential, callAgentOptions);
```

### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8/2735de8e636a422485e2c29e51d375aa?doc=False
* Link to Champion Scenarios/Quickstart samples:
-  Purpose is to support E911 calling in client sdk by specifying emergency country code for PSTN calling

```js
const callClientInstance = new CallClient();
const callAgent = callClientInstance .createCallAgent(tokenCredential, {
                emergencyCallOptions: {"countryCode": "US"}
            });
```

### iOS

* [APIView Link](https://apiview.dev/Assemblies/Review/2006b662a3294dd8987344354e7c20ad?diffRevisionId=4590240fe1b441ed9a3dc94123b15827&doc=False&diffOnly=True)
* Link to Champion Scenarios/Quickstart samples:
-  Purpose is to support E911 calling in client sdk by specifying emergency country code for PSTN calling

``` swift
self.callClient = CallClient()
let emergencyOptions = EmergencyCallOptions()
emergencyOptions.countryCode = "US"
let callAgentOptions = CallAgentOptions()
callAgentOptions.emergencyCallOptions= emergencyOptions

self.callClient!.createCallAgent(userCredential: userCredential!,
    options: callAgentOptions)  { (callAgent, error) in
       ...
})


```

**Comment by lilyjma** [comment]
scheduled for 11/30 2-4pm pst

**Comment by tjprescott** [comment]
Is this a "direct-to-GA" release or does this already exist in some preview?

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/2ee10840-98dc-94f4-96a9-f1ec52fb6ac7)[MS INTERNAL ONLY]
