### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - NetworkTraversal (C#, Java, Python, TS)

### ISSUE THREAD

**Issue by ajpeacock0** [Azure/azure-sdk#3641]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure.

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue.

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.**

## Contacts and Timeline

* Responsible service team: Azure Communication Services (SPOOL) - NetworkTraversal
* Main contacts:
  - Andrew Peacock, anpea@microsoft.com, ajpeacock0
  - Ari Zavala, arzavala@microsoft.com, AriZavala2
* Expected code complete date: November 2021
* Expected release date: December 2021

## About the Service

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/communication-services/concepts/network-traversal
* Link to the service REST APIs: [CommunicationNetworkTraversal.json](https://github.com/Azure/azure-rest-api-specs/blob/18479a01a549e9942ea38da8761919066aa87234/specification/communication/data-plane/NetworkTraversal/preview/2021-10-08-preview/CommunicationNetworkTraversal.json)
* Is the goal to release a Public Preview, Private Preview, or GA? GA
* Link to GitHub issue for previous review sessions, if applicable: https://github.com/Azure/azure-sdk/issues/2770

## About the client library

* Name of client library: Azure Communication Service - NetworkTraversal
* Languages for this review: C#, TypeScript, Python, Java
* Link to library reference documentation: https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/relay-token

### C#

* Existing .NET SDK library: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/communication/Azure.Communication.NetworkTraversal
* .NET APIView: https://apiview.dev/Assemblies/Review/54d993788847495b872ad3c60c898497

### JS/TS

* Existing TypeScript SDK library: https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/communication/communication-network-traversal
* TypeScript APIView: https://apiview.dev/Assemblies/Review/d033ef9589384a0cb1283724331b865a

### Python

* Existing Python SDK library: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-networktraversal
* Python APIView: https://apiview.dev/Assemblies/Review/39f6d92be3974ffb92618cea05fb81be

### Java

* Existing Java SDK library: https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/communication/azure-communication-networktraversal
* Java APIView: https://apiview.dev/Assemblies/Review/0d51ce01285041bc87b20595d761fdc4

## Step 1: Champion Scenarios

See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

### Champion Scenario 1: Send client `IceServer` using an identity

This scenario has the Contoso Server using the Identity SDK to create a `CommunicationUser` to track the data relayed using the TURN credentials. The Contoso Server then processes the `CommunicationRelayConfiguration` to return a JSON payload which matches the `IceServer` library the Client uses for WebRTC connections.

#### C#

**Contoso Server:**

```csharp
using Azure;
using Azure.Communication.Identity;
using Azure.Communication.NetworkTraversal;
using Azure.Communication.NetworkTraversal.Models;
using System.Text.Json;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

public ContosoServer()
{
    var acsConnectionString = Environment.GetEnvironmentVariable("ACS_CONNECTION_STRING");
    _identityClient = new CommunicationIdentityClient(acsConnectionString);
    _relayClient = new CommunicationRelayClient(acsConnectionString);
}

public async Task<string> GetIceServers()
{
    var user = (await _communicationIdentityClient.CreateUserAsync()).Value;
    var relayConfiguration = await _communicationRelayClient.GetRelayConfigurationAsync(new GetRelayConfigurationOptions { CommunicationUser = user });

    return JsonSerializer.Serialize(ProcessRelayConfig(relayConfiguration));
}

private List<IceServer> ProcessRelayConfig(CommunicationRelayConfiguration relayConfiguration)
{
    var iceServers = new List<IceServer>();
    foreach (var iceServer in relayConfiguration.IceServers)
    {
        if (turnServer.RouteType == RouteType.Any)
        {
            iceServers.Add(new IceServer
            {
                Urls = (List<string>)iceServer.Urls,
                TurnUserName = iceServer.Username,
                TurnPassword = iceServer.Credential,
            });
        }
    }

    return iceServers;
}
```

**Contoso Client:**

```csharp
public ContosoClientApp()
{
    _webRtcClient = new ContosoWebRtcClient();

    var iceServers = GetIceServersFromServer();
    if (!iceServers)
    {
        return;
    }

    await webRtcClient.OpenDataChannelAsync(iceServers);
}

private async List<IceServer> GetIceServersFromServer()
{
    // Client calls into the server using the method of their choice
    var jsonResponse = await contosoServer.GetIceServers();

    List<IceServer> iceServers;
    try
    {
        // Deserialize the response into the list of IceServers matching the WebRTC library of their choice
        iceServers = JsonSerializer.Deserialize<List<IceServer>>(jsonResponse);
    }
    catch (SerializationException)
    {
        // Log exception
        return null;
    }
}

public class ContosoWebRtcClient
{
    private PeerConnection _peerConnection = new PeerConnection();
    private DataChannel _dataChannel = null;

    public async Task OpenDataChannelAsync(List<IceServer> iceServers, string dataChannel)
    {
        await _peerConnection.InitializeAsync(new PeerConnectionConfiguration { IceServers = iceServers });

        DataChannel dataChannel = await _peerConnection.AddDataChannelAsync(dataChannel);
        _peerConnection.CreateOffer();

        // Wait until DataChannel is opened
        var dataChannelOpenedPromise = new TaskCompletionSource();
        _dataChannel.StateChanged += () => {
            if (_dataChannel.State == ChannelState.Open)
            {
                dataChannelOpenedPromise.TrySetResult();
            }
        };
        await dataChannelOpenedPromise.Task;

        _dataChannel.MessageReceived += (byte[] data) => {
            // handle data
        };
    }

    public void SendMessage(string message)
    {
        if (_dataChannel == null)
        {
            throw new InvalidOperationException("Connection not made");
        }
        var datagram = Encoding.Unicode.GetBytes(message);
        _dataChannel.SendMessage(datagram);
    }
}
```

#### TS

If the client is in JavaScript they can verbatim pass the json into their WebRTC config without deserialization.

**Node.js Server:**

```javascript
const { CommunicationIdentityClient } = require("@azure/communication-identity");
const { CommunicationRelayClient } = require("@azure/communication-network-traversal");

// You will need to set this environment variables or edit the following values
const connectionString =
  process.env["COMMUNICATION_CONNECTION_STRING"] || "<communication service connection string>";

async function getConfig() {
  const identityClient = new CommunicationIdentityClient(connectionString);
  const relayClient = new CommunicationRelayClient(connectionString);

  const user = await identityClient.createUser();
  const config = await relayClient.getRelayConfiguration(user);

  return (await config).iceServers;
}

app.get('/getconfiguration', async function(request, response) {
    const config = await getConfig();
    response.send(config);
  });
```

**WebApp:**

```javascript
fetch(`getcredentials`)
    .then(response => response.json())
    .then(iceServers => {
      // Set up a new RTCPeerConnection using the token's iceServers.
      VideoChat.peerConnection = new RTCPeerConnection(iceServers);

      // Add the local video stream to the peerConnection.
       VideoChat.peerConnection.addStream(VideoChat.localStream);
      // Set up callbacks for the connection generating iceCandidates or
      // receiving the remote media stream.
      VideoChat.peerConnection.onicecandidate = VideoChat.onIceCandidate;
      VideoChat.peerConnection.onaddstream = VideoChat.onAddStream;
      // Set up listeners on the socket for candidates or answers being passed
      // over the socket connection.
      VideoChat.socket.on('candidate', VideoChat.onCandidate);
      VideoChat.socket.on('answer', VideoChat.onAnswer);
      callback();
    }
  );
```

### Champion Scenario 2: Send client `CommunicationRelayConfiguration`

In this scenario, Contoso Server fetches a `CommunicationRelayConfiguration` of a specific route type and
passes the `CommunicationRelayConfiguration` directly to the client app, which uses the NetworkTraversal SDK
to deseralize it and pull out the information needed.

#### C#

**Contoso Server:**

```csharp
public ContosoServer()
{
    var endpoint = new Uri("https://my-resource.communication.azure.com");
    TokenCredential tokenCredential = new DefaultAzureCredential();

    _identityClient = new CommunicationIdentityClient(endpoint, tokenCredential);
    _relayClient = new CommunicationRelayClient(endpoint, tokenCredential);
}


public async Task<string> GetRelayConfiguration() 
    => JsonSerializer.Serialize(await _communicationRelayClient.GetRelayConfigurationAsync(new GetRelayConfigurationOptions { RouteType = RouteType.Any }));
```

**Contoso Client:**

```csharp
private async List<IceServer> GetRelayConfigurationFromServer()
{
    // Client calls into the server using the method of their choice
    var jsonResponse = await contosoServer.GetRelayConfiguration();

    List<IceServer> iceServers;
    try
    {
        // Deserialize the response into the CommunicationRelayClient
        var relayConfig = JsonSerializer.Deserialize<CommunicationRelayConfiguration>(jsonResponse);

        // Ensure there is at least 1 value, but also ensure there the client uses the chosen route type for this scenario
        if (relayConfig.IceServers.Count != 1)
        {
            // Log exception
            return null;
        }

        // Create a IceServer matching the WebRTC library being used
        var iceServer = relayConfig.IceServers.First();
        iceServers.Add(new IceServer
        {
            Urls = (List<string>)iceServer.Urls,
            TurnUserName = iceServer.Username,
            TurnPassword = iceServer.Credential,
        });
    }
    catch (SerializationException)
    {
        // Log exception
        return null;
    }

    return iceServers;
}
```

## Step 2: SDK Samples and Quickstarts

- **.NET Samples:** https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/communication/Azure.Communication.NetworkTraversal/samples
- **JavaScript/TypeScript Samples:** https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/communication/communication-network-traversal/samples-dev
- **Python Samples:** https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/communication/azure-communication-networktraversal/samples
- **Java Samples:** https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/communication/azure-communication-networktraversal/src/samples/java/com/azure/communication/networktraversal

- [JavaScript Quickstart](https://github.com/Azure-Samples/communication-services-javascript-quickstarts/tree/main/network-traversal-get-relay-config)
- [Python Quickstart](https://github.com/Azure-Samples/communication-services-python-quickstarts/tree/main/get-relay-configuration-quickstart)
- [Java Quickstart](https://github.com/Azure-Samples/communication-services-java-quickstarts/pull/22/files)

**Comment by lilyjma** [comment]
scheduled for 12/6 2-4pm pst

**Comment by RezaJooyandeh** [comment]
@ajpeacock0 , why do we need an explicit cast here?
```csharp
iceServers.Add(new IceServer
    {
        Urls = (List<string>)iceServer.Urls,
        TurnUserName = iceServer.Username,
        TurnPassword = iceServer.Credential,
    });
```

**Comment by ajpeacock0** [comment]
> @ajpeacock0 , why do we need an explicit cast here?

The `CommunicationRelayConfiguration` has 
```cs
IReadOnlyList<CommunicationIceServer> Urls
```
which cannot be directly assigned to the `IceServer`
```cs
List<string> Urls
```
You could get around this by having the ContosoServer use a custom `ContosoIceServer` which matches the client library's `IceServer` but uses a `IReadOnlyList` on the `Urls` instead, however then you need to maintain 2 models which are tracking the same json format.

**Comment by DominikMe** [comment]
@ajpeacock0 Why not use `System.Text.JSON`, delete the `ProcessRelayConfig` and directly serialize the ACS relay config?

Also the user is no longer mandatory, so the whole server can become super short:

```c#
public async Task<string> GetIceServers()
 => JsonSerializer.Serialize(await _communicationRelayClient.GetRelayConfigurationAsync());
```

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/a27f0840-98dc-94f4-e904-f1ec56ebd5d5)[MS INTERNAL ONLY]
