### ISSUE TITLE
Board Review: Microsoft.Azure.WebJobs.Extensions.SignalRService

### ISSUE THREAD

**Issue by Y-Sindo** [Azure/azure-sdk#3661]
## Contacts and Timeline

* Responsible service team: `Azure SignalR Service `
* Main contacts: zityang@microsoft.com
* Expected code complete date: `Already completed`
* Expected release date: `December, 2021 - January, 2022`

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-overview
* Link to the service REST APIs: https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md
* Link to GitHub issue for previous review sessions, if applicable:  `N/A`

## About the client library

* Name of the client library: `Microsoft.Azure.WebJobs.Extensions.SignalRService`
* Languages for this review: `.NET`
* Link to the REAEME:  https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/18274553e71a4f44a2f924031f627b14?diffRevisionId=2cfcb5bf94b0487daec57d5e35cb7b0e&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples:
   *   [Quickstart: Create an App showing GitHub star count with Azure Functions and SignalR Service](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-azure-functions-csharp)
    *  [Bidirectional chatroom sample using SignalR trigger](https://github.com/Azure/azure-functions-signalrservice-extension/tree/dev/samples/bidirectional-chat)
    *  [Simple chatroom sample using SignalR input and output binding](https://github.com/Azure/azure-functions-signalrservice-extension/tree/dev/samples/simple-chat)
*  New feature strongly typed serverless hub samples:
    *  [Snippet sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/samples/Sample01_StronglyTypedHub.md) 
    *  [Complete sample src](https://github.com/Y-Sindo/azure-sdk-for-net/tree/e22903c98635a305d9c658c79d5f6f675725deab/sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/sample)
    *  [live demo](https://functionapp20211208195623.azurewebsites.net/api/index)

**Comment by lilyjma** [comment]
scheduled for 12/8 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/0fe90840-98dc-94f4-d4bb-f1ec5887375b)[MS INTERNAL ONLY]
