### ISSUE TITLE
Board Review: Azure Maps Search SDK

### ISSUE THREAD

**Issue by daniel-rocha** [Azure/azure-sdk#3672]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Maps
* Main contacts: daroch, tarasvozniuk
* Expected code complete date: Q1/2022
* Expected release date: Q1/2022

## About the Service 

* Link to documentation introducing/describing the service: Azure Maps - Search APIs is the set of APIs used to do forward and reverse geocoding in Azure Maps. 
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/maps/search
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/3271

## About the client library

* Name of the client library: Azure Maps Search Library 
* Languages for this review:  Java, C#, TypeScript, Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/07d5b915b41147beb1c6c3268f8ae349
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/7126eaeacfe3458da0692fa889d49b40
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/0ab748be5297432eaf27d512e2d1b998
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/737c63ff29ea4eb8ad335ddabb4c382f
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by daniel-rocha** [comment]
•	.NET: 
o	API: https://apiview.dev/Assemblies/Review/07d5b915b41147beb1c6c3268f8ae349
o	Fork: https://github.com/ambientlight/azure-sdk-for-net/tree/feat/maps-search-onboarding/sdk/maps/Azure.Maps.Search
o	Examples: https://github.com/ambientlight/azure-sdk-for-net/tree/feat/maps-search-onboarding/sdk/maps/Azure.Maps.Search/samples

•	Java: 
o	API: https://apiview.dev/Assemblies/Review/7126eaeacfe3458da0692fa889d49b40
o	Fork: https://github.com/daniel-rocha/azure-sdk-for-java/tree/daroch/feature/maps-sdk/sdk/maps/azure-maps-search
o	Examples: https://github.com/daniel-rocha/azure-sdk-for-java/blob/daroch/feature/maps-sdk/sdk/maps/azure-maps-examples/src/main/java/com/azure/maps/examples/SearchSample.java

•	Python: 
o	API: https://apiview.dev/Assemblies/Review/0ab748be5297432eaf27d512e2d1b998
o	Fork: https://github.com/alextts627/azure-sdk-for-python/tree/maps-sdk-onboard-11-11-21/sdk/maps/azure-maps-search
o	Examples: To be added.

•	TypeScript
o	API: https://apiview.dev/Assemblies/Review/737c63ff29ea4eb8ad335ddabb4c382f
o	Fork: https://github.com/alankashiwa/azure-sdk-for-js/tree/onboard-maps-dataplane-sdk/sdk/maps/maps-search
o	Examples: https://github.com/alankashiwa/azure-sdk-for-js/tree/onboard-maps-dataplane-sdk/sdk/maps/maps-search/samples/v1/typescript

**Comment by lilyjma** [comment]
scheduled for 12/9 2-4pm pst

**Comment by tg-msft** [comment]
Please also try to read [Azure Maps REST SDK Conv Layer Design Doc](https://microsoft.sharepoint.com/:w:/t/MicrosoftMapsGeospatialTeam/EZp2qlziS4dBtu0a7le2qs8BX8bKRkRrz-0_UkIZUOKq0A?e=3JpSED&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cteglaza%40microsoft.com) before the meeting if possible.

**Comment by tg-msft** [comment]
@daniel-rocha / @ambientlight - I can't access the samples at https://github.com/ambientlight/azure-sdk-for-net/tree/feat/maps-search-onboarding/sdk/maps/Azure.Maps.Search/samples.  Can you paste them here?

**Comment by ambientlight** [comment]
@tg-msft: the tests are under https://github.com/ambientlight/azure-sdk-for-net/tree/feat/maps-search-onboarding/sdk/maps/Azure.Maps.Search/tests 

I've restructured a bit into tests/ to adhere with guidelines, since I found top-level samples/ used for .md samples and those haven't yet been written.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/4edd0840-98dc-94f4-219d-f1ec5952be19)[MS INTERNAL ONLY]
