### ISSUE TITLE
Verify Changelog in pull request if release date is set

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk#3690]
Changelog validation comes at the end of the release pipeline--just before publishing to maven. This timing is problematic because it is a step which easily fails, so it disrupts the release process significantly.

The Changelogs have a very specific format and must be hand edited. Even with careful editing and review, it is very easy to miss a new line or some other typo, as is always the case with human editing. The mistakes will always cause the step to fail. 

Because this validation step is so late in the release process, release prep Prs have been merged, tests have been run, and likely several other packages are already being published. To make a one line fix, then, requires submission of a new PR, triggering a new pipeline, and waiting for another pipeline. It also then results in duplicate automated version update PRs which must manually be reconciled, introducing more opportunity for human error. In short, the placement of the Changelog validation step means there is an unreasonably high cost to make in a mistake in an area that is very prone to mistakes. 

This could be resolved in one of two ways:

1. Move this step earlier. For reasons that have not been clear to me, there has been resistance to doing this in the past. However, I continue to think it is the most effective solution to this problem. It seems to me it should be added in the first step of a release pipeline when other analytic steps are being performed. 
2. Provide a script which performs the exact function of this step. [This](https://github.com/Azure/azure-sdk-for-java/blob/main/eng/common/scripts/Prepare-Release.ps1) script was described to me as performing this function. However, I ran it before our most recent release and still hit this problem. The script gave a few prompts before running and exiting successfully. The only change it made was to unnecessarily rearrange the history of one of our changelogs in a way that I had to undo. If this script could be fixed to successfully fail when the pipeline step will fail or another script provided to do the same, then that would also be sufficient.

**Comment by weshaggard** [comment]
Thanks for the feedback @rickle-msft. 

1 - The biggest trouble is doing it earlier, such as doing it in the build, would fail in most cases if you don't plan to ship a given package. We have some ideas about validating this during build if you have a release date stamped in your changelog but haven't gone that far yet because Prepare-Release is supposed to handle this.

2- The Prepare-Release script is supposed to be the one doing this validation and warning if your changelog is not valid.  Can you please provide more details on what it did and what issue it didn't catch but you hit during release?

**Comment by weshaggard** [comment]
@chidozieononiwu can you please use this issue to track enabling all changelog verification process during the build when we see the version in the changelog has a date stamped into it? 

Also work with @rickle-msft to see if we can understand why Prepare-Release isn't correctly validating the changelog.

**Comment by rickle-msft** [comment]
Thanks for responding, @weshaggard. I understand from our conversations in the past that there's the problem you mention with adding it to Analyze step or build pipeline in general. I don't fully understand why it can't be added as its own step like signing. It seems like the pipeline dynamically adds some steps based on whether it's release or not. But I'm pretty ignorant of how this system works internally, so if you're saying it's complicated as to not be worth it, I'll take your word for it. 

[Here](https://github.com/Azure/azure-sdk-for-java/pull/25870) is the PR where I tried to use the script. I ran the script before creating the PR (first commit) and then undid some changes (second commit). I then had to open [this](https://github.com/Azure/azure-sdk-for-java/pull/25886) PR to remove the empty section that it missed and the release pipeline failed on. 

I ran the script by going into the eng\common\scripts directory and running it with no args (I was hoping to see a help menu for suggestions on running it since I'm not familiar with powershell), but it just asked for prompts instead, which is fine. I put in the package name (azure-storage-blob), accepted the suggested version. I said I did not want to update the date as I had already changed it, and then it exited. 

I just tried running it from the same commit again to type this out, and I think I may understand better what happened. I ran it on the blobs package, and it printed out a git status report at the end of the script, which I interpreted as a list of files it changed. I assumed it for some reason scanned all the projects related to blobs, too (I probably forgot I had specified blobs and not all of storage), and had modified those as part of its run and that's why it had displayed those. In actuality, I had modified those files before running the script, and it was just showing those modifications I had mad as part of the git status. Running the script again now on the datalake package it looks like it does remove the empty Changelog header like I would expect, so it could have been my incorrect use of the script that caused this issue.

**Comment by weshaggard** [comment]
Thanks for the feedback, we definitely want to help improve this process.

For running the script with PS you can `-?` to see all the options but the prompt will prompt you for all the required parameters which is just the package name in this case.

As for why it reordered things. We try to normalize the changelog entries based on the date they were released and so if you commit that once that shouldn't keep happening. 

As for running this check as part of CI we have wanted to do that for a while so we will use this issue to track adding that extra validation in the Analyze job anytime there an entry has a date stamped in the change log. That should help catch somethings earlier but still not everything. Prepare-Release will help as well but either of those will help catch cases where there is no date stamped in the changelog and you want to do a release, we can only do that after you hit the approve button in the release pipeline unfortunately.

**Comment by weshaggard** [comment]
Reopening since you reverted your change.
