### ISSUE TITLE
Change Request: Update README guidelines to include samples up top

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk#377]
## The Basics

* Which design guideline is affected?
README

* Which target languages are affected?
All

* Describe the change:

We have the below guideline to include 4 important links. Update the same to include a 5th link for "Samples"

![image](https://user-images.githubusercontent.com/16890566/58059030-23204c80-7b20-11e9-97ae-74b140cd1ea3.png)

## Reasoning

The link to samples is at the very bottom i.e. in the `Next Steps` section. A lot of users might want to jump right into code and samples and try out the libraries. We need a link up top within user's first glance and not require user to scroll around

**Comment by adrianhall** [comment]
Not sure we need a board review for this, since it is kind of a "duh".  However, the docs guidelines reference the documentation team guidelines, which are incorporated by reference in the rewrite, so I don't think this changes the actual guidelines.

@mmacy - you own the docs requirements.  Can you make this change unilaterally?

**Comment by ramya-rao-a** [comment]
From my side, I expect changes to https://github.com/Azure/azure-sdk/blob/master/docs/README-TEMPLATE.md and https://github.com/Azure/azure-sdk/blob/master/docs/README-EXAMPLE.md in this repo and an issue for each central repo to update existing readme that already follow the template

**Comment by adrianhall** [comment]
Resolved in PR #379

**Comment by ramya-rao-a** [comment]
@adrianhall The example for readme has been updated, but the [template ](https://github.com/Azure/azure-sdk/blob/master/docs/README-TEMPLATE.md) hasnt
