### ISSUE TITLE
Board Review: Introducing Cognitive Language Text (.NET and Python)

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk#3774]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Cognitive Services Language
* Main contacts: @kristapratico @jsquire 
* Expected code complete date: TBD
* Expected release date: TBD

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/overview
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/pull/16921
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/3089, https://github.com/Azure/azure-sdk/issues/3471

## About the client library

* Name of the client library: Proposal: azure-ai-textanalytics
* Languages for this review: Python, .NET

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Cross-language

* [Text Analytics: Unified Language REST API Support](https://gist.github.com/jsquire/0ba0b529832d3c5525479c880f3cda00)

### .NET

* [API View: Azure.AI.TextAnalytics _(v5.2.0-beta.2)_](https://apiview.dev/Assemblies/Review/2d2a87eaa70a43b8860f1c4e7135494b/f08a286d3f5a43ad9f1c16cad078b5af?diffRevisionId=2c29692c930c4265b8e331816e484495&doc=False&diffOnly=True)  _(for reference only; not intended to review during this session)_

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/d3b9aeb03357454b9e083ef519156a94?diffOnly=True&diffRevisionId=4cfad4949b1c40fdb0c9b437d086f0d0
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/kristapratico/b70f6513e25d4f4af5b9866cf278d240#samples
  
### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 2/28 1-3pm pst
