### ISSUE TITLE
Board Review: Attestation - Java

### ISSUE THREAD

**Issue by LarryOsterman** [Azure/azure-sdk#3781]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

## Contacts and Timeline

* Responsible service team: Azure Attestation Service
* Main contacts: LarryO, AnilBa
* Expected code complete date: 1/10/2022
* Expected release date: 2/1/2022

## About the Service 
* Link to documentation introducing/describing the service:https://azure.microsoft.com/en-us/services/azure-attestation/
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/attestation/data-plane/Microsoft.Attestation/stable/2020-10-01/attestation.json
* Link to GitHub issue for previous review sessions, if applicable: https://github.com/Azure/azure-sdk/issues/2889 https://github.com/Azure/azure-sdk/issues/2652 https://github.com/Azure/azure-sdk/issues/1985

## About the client library

* Name of the client library: Azure Attestation
* Languages for this review: Java

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/7649463a50d54f249be5ad0ee0580b05
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/attestation/azure-security-attestation/src/samples/java/com/azure/security/attestation

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 1/20 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/e6e20840-98dc-a505-8313-f1ec7a4a641c)[MS INTERNAL ONLY]
