### ISSUE TITLE
Move PR triggers from designer into yaml

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#38]
Our PR triggers should be moved from the designer into yaml, once they are supported (https://github.com/Microsoft/azure-pipelines-yaml/issues/38).

According to the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml#pull-request-validation), this is now supported.

## Repos
* [ ] azure-sdk-for-net
* [ ] azure-sdk-for-java
* [ ] azure-sdk-for-python
* [ ] azure-sdk-for-js

**Comment by kurtzeborn** [comment]
This is all done with the transition to unified pipelines.  This included our release pipelines.
