### ISSUE TITLE
Change Request: Setting cognitive service keys per request instead of at client creation

### ISSUE THREAD

**Issue by mhamilton723** [Azure/azure-sdk#3802]
## The Basics

* Which design guideline is affected?

Authentication

* Which target languages are affected?

All but Java is the language I care about

* Describe the change:

the SDK should support different authentication styles on a per-request basis. Currently one needs to mutate a global key before each request which is not thread-safe. Ideally, the key would be an optional parameter when sending requests

## Reasoning

Some people would like to parallelize over multiple services, or run a multi-tenant tool

**Comment by johanste** [comment]
@schaabs, this is something that you may have thoughts on....
