### ISSUE TITLE
Board Review: Schema Registry Encoder

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk#3808]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Schema Registry
* Main contacts: @JoshLove-msft 
* Expected code complete date: March 2022
* Expected release date: March 2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/event-hubs/schema-registry-overview
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/schemaregistry/data-plane/Microsoft.EventHub/stable/2021-10/schemaregistry.json
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/3385

## About the client library

* Name of the client library:
* Languages for this review: .NET, JavaScript, Python, Java

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: 
  * [Avro Schema Registry Encoder](https://apiview.dev/Assemblies/Review/946ec06afc3141dbb8d09712b9276942)
  * [MessageWithMetadata](https://apiview.dev/Assemblies/Review/b67e68cfee4841bda045f895c90ad383#Azure.Messaging.MessageWithMetadata)
  * [EventHubs](https://apiview.dev/Assemblies/Review/e9236fb0f0e34c40bf72df92acddfed3#Azure.Messaging.EventHubs.EventData)
* Link to Champion Scenarios/Quickstart samples:  https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/schemaregistry/Microsoft.Azure.Data.SchemaRegistry.ApacheAvro#encode-and-decode-data-using-the-event-hub-eventdata-model
* Additional samples - https://github.com/appdevgbb/azure-schema-registry/tree/main/samples

### Java

* APIView Link:
  * [azure-core-experimental](https://apiview.dev/Assemblies/Review/ab34038bbd0346c887406dad0aff2b5b?diffRevisionId=3b896e84d4d645a2b25f1e1e09ba1b76&doc=False&diffOnly=False)
  * [azure-messaging-eventhubs](https://apiview.dev/Assemblies/Review/effec47227774f128c8e8fb868f7c42a?diffRevisionId=2e922d5feeb946a08559c376b8b5f907&doc=False&diffOnly=False#com.azure.messaging.eventhubs.EventData)
  * [azure-data-schemaregistry-apacheavro](https://apiview.dev/Assemblies/Review/ddc99fd6dc6546aeb0194d903878fa8d?diffRevisionId=172d3691bd054793acce8fa3457d5ce6&doc=False&diffOnly=False)
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/conniey/d73e98a4a7d01145ab8d86d9d03efc1f

### Python

* APIView Link:
  * [azure-eventhub](https://apiview.dev/Assemblies/Review/408c2d333af84f80a9ca6e6f09272559?diffOnly=True&diffRevisionId=e45f8e657983402a8bf108822be06b39)
  * [azure-schemaregistry-avroencoder](https://apiview.dev/Assemblies/Review/10f749347612495b91bf0aafd96a6565?doc=False)
* Link to Champion Scenarios/Quickstart samples:
  * [Encode and Decode EventData/ServiceBusMessage/CloudEvent](https://gist.github.com/swathipil/9eed26e7f85c6b57d9e788d2691c76de#sample-with-eventdataservicebusmessagecloudevent)
  * [Encode and Decode EventGridEvent](https://gist.github.com/swathipil/9eed26e7f85c6b57d9e788d2691c76de#sample-for-eventgridevent)
  * [Encode with Callback that Creates Message](https://gist.github.com/swathipil/9eed26e7f85c6b57d9e788d2691c76de#samples-with-passing-callbacks)
  
### TypeScript

* APIView Link: 
[`@azure/schema-registry-avro`](https://apiview.dev/Assemblies/Review/0ff89eb70d9c4411a6f3a93aa6203bd4?diffRevisionId=cb281a94109d4c9e8b46553258f0750b&doc=False&diffOnly=False)
[`@azure/event-hubs`](https://apiview.dev/Assemblies/Review/61ca1366e5a149ceac9bfe75583d4c9a?diffRevisionId=290c10f3ae324ee4bf841442c6c4071b&doc=False&diffOnly=True)
[`@azure/eventgrid`](https://apiview.dev/Assemblies/Review/209978255b1a436694d518838e2a9454?diffRevisionId=185a1287959c4c53b9134eb548f42063&doc=False&diffOnly=True)
* Link to Champion Scenarios/Quickstart samples: [Event Hubs Producer](https://github.com/Azure/azure-sdk-for-js/blob/068d9de287ce80e50a3c31470735350a24cc2cf2/sdk/schemaregistry/schema-registry-avro/samples-dev/withEventHubsProducerClient.ts), [Event Hubs Consumer](https://github.com/Azure/azure-sdk-for-js/blob/068d9de287ce80e50a3c31470735350a24cc2cf2/sdk/schemaregistry/schema-registry-avro/samples-dev/withEventHubsConsumerClient.ts), and [Event Grid](https://github.com/Azure/azure-sdk-for-js/blob/068d9de287ce80e50a3c31470735350a24cc2cf2/sdk/schemaregistry/schema-registry-avro/samples-dev/withEventGrid.ts)

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 2/2 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/38b40840-98dc-a505-7a0e-f1ec848e54b2)[MS INTERNAL ONLY]
