### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - Calling Native - Dominant speaker (iOS & Android)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#3814]
# About the Service
Service team responsible for the client library: Azure Communication Services (SPOOL).
Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/communication-services/overview
# Contacts
Service Team :marius.ungureanu@microsoft.com
Dev Lead: jsaurezlee@microsoft.com
# About the client library
Name of the client library: Communication Calling
Languages for this review: iOS and Java (Android)
# Change being introduced
Dominant Speakers is an extended feature of the core Call object that allows the user to monitor the most dominant speakers in the current call. Participants can join and leave the list based on how they are performing in the call.

The main idea is that as participants join, leave, climb up or down in this list of participants, the client application can take this information and customize the call experience accordingly. For example, the client application can show the most dominant speakers in the call in a different UI to separate from the ones that are not participating actively in the call.

Developers can receive updates and obtain information about the most Dominant Speakers in a call.
This information is being a represented as:
- An ordered list of the Remote Participants that represents the Dominant Speakers in the call.
- A timestamp marking the date when this list was last modified.
# Java (Android)
Artifacts per language: [APIView for Android](https://apiview.dev/Assemblies/Review/b09908fb56ab40f0a607df91f2748828)
## How to use
First need to obtain the Dominant Speakers feature API object:
```java
DominantSpeakersFeature dominantSpeakersFeature = call.feature(Features.DominantSpeakers);
```
The Dominant Speakers feature object have the following API structure:
- `OnDominantSpeakersChanged`: Event for listening for changes in the dominant speakers list.
- `getDominantSpeakersInfo()`: Gets the `DominantSpeakersInfo` object. This object has:
    - `getSpeakers()`: A list of participant identifiers representing the dominant speakers list.
    - `getTimestamp()`: The date when the dominant speakers list was updated. 

To subscribe to changes in the Dominant Speakers list:

```java

// Obtain the extended feature object from the call object.
DominantSpeakersFeature dominantSpeakersFeature = call.feature(Features.DominantSpeakers);
// Subscribe to the OnDominantSpeakersChanged event.
dominantSpeakersFeature.addOnDominantSpeakersChangedListener(handleDominantSpeakersChangedlistener);

private void handleCallOnDominantSpeakersChanged(PropertyChangedEvent args) {
    // When the list changes, get the timestamp of the last change and the current list of Dominant Speakers
    DominantSpeakersInfo dominantSpeakersInfo = dominantSpeakersFeature.getDominantSpeakersInfo();
    Date timestamp = dominantSpeakersInfo.getTimestamp();
    List<CommunicationIdentifier> dominantSpeakers = dominantSpeakersInfo.getSpeakers();
}
```
# iOS
Artifacts per language: [APIView for iOS](https://apiview.dev/Assemblies/Review/7d5fe54239254ababca880006444c243)
[APIView with new version of the tool](https://apiview.dev/Assemblies/Review/5a80ea3f7fb2427fa7bcbb47395358b0)
## How to use
First need to obtain the Dominant Speakers feature API object:
```swift
let dominantSpeakersFeature = call.feature(Features.dominantSpeakers)
```
The Dominant Speakers feature object have the following API structure:
- `didChangeDominantSpeakers`: Event for listening for changes in the dominant speakers list.
- `dominantSpeakersInfo`: Which gets the `DominantSpeakersInfo` object. This object has:
    - `speakers`: A list of participant identifiers representing the dominant speakers list.
    - `timestamp`: The date when the dominant speakers list was updated.

To subscribe to changes in the dominant speakers list:

```swift
// Obtain the extended feature object from the call object.
let dominantSpeakersFeature = call.feature(Features.dominantSpeakers)
// Set the delegate object to obtain the event callback.
dominantSpeakersFeature.delegate = DominantSpeakersDelegate()

public class DominantSpeakersDelegate : DominantSpeakersCallFeatureDelegate
{
    public func dominantSpeakersCallFeature(_ dominantSpeakersCallFeature: DominantSpeakersCallFeature, didChangeDominantSpeakers args: PropertyChangedEventArgs) {
        // When the list changes, get the timestamp of the last change and the current list of Dominant Speakers
        let dominantSpeakersInfo = dominantSpeakersCallFeature.dominantSpeakersInfo
        let timestamp = dominantSpeakersInfo.timestamp
        let dominantSpeakersList = dominantSpeakersInfo.speakers
    }
}
```

**Comment by lilyjma** [comment]
scheduled for 1/31 2-4pm pst

**Comment by tjprescott** [comment]
From the APIViews, the desired version numbers for this feature are:
Android: 2.1.0-beta.1
iOS: 2.3.0-beta.1

**Comment by tjprescott** [comment]
You iOS code samples should not use `!` to unwrap optionals because we should not recommend customers do this.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/8dba0840-98dc-a505-d0fa-f1ec82e76a6b)[MS INTERNAL ONLY]
