### ISSUE TITLE
Board Review: Python Event Hubs Preview 1

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk#382]
## The Basics

* Service team responsible for the client library:  **Azure Messaging**  
* Link to documentation describing the service: **[Product Documentation](https://docs.microsoft.com/en-us/azure/event-hubs/)**  
* Contacts: 
    * Javier Fernandez (Service PM),  
    * SeongJoon Kwak (Service Dev Lead)
    * Ramya Rao (ADP team)
* Languages for this review: Python

## Review Resources
To be added

## Champion Scenarios

- send multiple events to no particular partition
- send multiple events to the same partition identified by its id
- send multiple events to the same partition, but don't care which partition
- find metadata of the event hub instance
- get ids of all partitions in the event hub instance
- receive events from a particular partition in a consumer group
- receive events from a particular partition in a consumer group starting from given position 

## Agenda for the review

1. Revisit some of the board suggestions that were made in prior meetings for the same service but other languages for clarification.
2. Review client creations via constructors and static helpers in Python
3. Review champion scenarios in Python

We have had reviews for .Net, Java and Javascript before this point. Below are some board suggestions that were made then that we want to re-open for discussion

- Renaming of `GetEventHubRuntimeInformation` to `GetProperties` on the client
     - `client.GetProperties` would imply one is getting properties of the client. In this case, the information we are getting are the properties of the event hub instance not the client. 
     - We want to propose using the name `getHubProperties` which would make it clear that the properties are of the Event Hub instance that this client represents
     - For more context, the info returned are the date the event hub instance was created on, number of partitions and the ids of each partition.
- Renaming the option that specifies the position in the stream from where to receive events from `EventPosition` to `BeginReceivingAt`
   - This is the only option that sounds like it is telling (literally) the receiver what to do. Other options dont. Example: `ConsumerGroup` is not named `GroupToReceiveFrom`. `ExclusiveReceiverPriority` is not named `SetExclusiveReceiverPriorityTo`.
    - I (personal opinion here from Ramya) would suggest to either not change the name here and keep `EventPosition` or rename to just `Position`.
- `createSender()` doesnt take partitionId, the `send()` methods on the sender takes partitionId
     - We recently discovered that the only way we can send to a partition specified by the id is by creating a dedicated AMQP sender link for the partition. Therefore, this design has been updated such that `createSender()` takes optional partitionId and the send() methods don't
      - If no paritionId is passed, service decides which partition to use
      - No questions here. Just FYI as this was a deviation from what was discussed in prior meetings
- Name of the sender and receiver class
     - Board has suggested `EventSender` and `PartitionReceiver`. The reason being that the client allows sending without specifying partition, but only allows receiving from given partition
     - But, this difference is clear from the arguments that `createSender()` and `createReceiver()` take. We want to suggest using simpler `Sender` and `Receiver` to avoid confusion when 
           - one looks at list of classes in API references documentation
           - or looks at `EventSender` and wonder if they need to work with another class to send to a partition

**Comment by adrianhall** [comment]
Board meeting notes:

* Unify the constructor parameters across languages
* Remove `partition_count` from the result of `get_properties()`
* Remove all the factory methods except for `from_connection_string`.
* Hide `auto_reconnect` and `keep_alive_interval` from kwargs
* In receiver, `consumer_group` should be optional and default to `$default`
* Consider removing `open()` in the receiver and just manage the connection in .receive().  If you opt to keep `.open()`, then also add it to other languages.
* Implement `__repr()` and `__str()` on the events that are received
* Support custom JSON decoders
* Remove the `receiver.subscribe()` for preview - discuss with @johanste about design before inclusion
* Consider hiding `queue_messages()` and `send_pending_messages()` - they are covered by `.send()` already

API approved for preview, pending these changes.

**Comment by ramya-rao-a** [comment]
Can we re-open this to get a resolution on the open items listed in the issue originally? Mainly on the **objections** to the below renames suggested by the board. For details, please see the original issue descriptions above

- `EventPosition` -> `BeginReceivingAt`
-  `Sender` -> `EventSender`
- `Receiver` -> `PartitionReceiver`

**Comment by ramya-rao-a** [comment]
cc @bterlson, @KrzysztofCwalina , @JonathanGiles , @johanste

**Comment by adrianhall** [comment]
I think we are closed on all issues now.  If not, please open new issues with the outstanding issues.
