### ISSUE TITLE
Board Review: Azure.Core LRO polling logic

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk#3841]
### Summary
We got some feedback from an internal customer around the waitForCompletion parameter in LRO for dotnet.  It seems that by doing this we are introducing some situations where we will poll overly aggressive and cause throttling to occur.

Today there are 3 ways to set the polling interval

1. The LRO internal polling code will [honor the Retry-After header](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Azure.Core.Shared/OperationInternalBase.cs#L210) if its present
2. [WaitForCompletion method has an overload](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Operation.cs#L127) allowing you to set it which will be used if Retry-Header is absent
3. There is a [global static default](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Operation.cs#L22) of 1 second

As a side note there appears to be two implementations of GetServerDelay here in [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Operation.cs#L148) and here for [autorest.csharp](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Azure.Core.Shared/OperationInternalBase.cs#L210) as shared internal code.  There is also two definitions for the global default in [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Operation.cs#L22) and [autorest.csharp](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Azure.Core.Shared/OperationInternalBase.cs#L30).  My guess here is Dataplane uses the one from azure-sdk-for-net and mgmt plane uses the other?  Not 100% sure there.

The only one of these visible to the customer is the second one and in the case where you pass in true to an LRO method [we are calling WaitForCompletion without any parameters](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/ResourceGroupCollection.cs#L80) so the second one won't ever get used and when the service does not provide Retry-After we spam a retry every second.

#### New optional parameter
We could add an additional optional Timespan parameter before the CancellationToken which would then internally be used when calling WaitForCompletion.  I don't like the idea of adding yet another parameter to our LRO methods.
#### Global timeout in ClientOptions
We could add a new parameter in the options object to allow customers to override the static 1 second default.  The issue here is there is no good global value as the majority of LROs finish in under 10seconds, but there are many especially in mgmt plane that take 15-60 minutes for common provisioning scenarios.
#### Replace the polling with exponential backoff
If instead of a constant 1 second polling interval we double it until we get to 32 or 64 this would provide a reasonable implementation for almost every scenario and only in rare cases would customers need to control their own polling.  The cases where customers need to do this today are much higher so this is an improvement over todays behavior.  This would also solve the original issue that was raised from our customers of getting throttled due to too many requests.

**Comment by lilyjma** [comment]
scheduled for 2/3 2-4pm pst

**Comment by archerzz** [comment]
For the global timeout, according to the [spec](https://github.com/Azure/azure-resource-manager-rpc/blob/69e229f04cb6b91a82c97fc6f61d56055107c447/v1.0/async-api-reference.md#202-accepted-and-location-headers), it should be 60 sec:

> 3. Clients should wait for the Retry-After interval, if it was specified, or the default of 60 seconds if it was not, before polling again.

But from what I know, Python and Java SDK default to 30 sec.

**Comment by johanste** [comment]
When we last tried (at least the last attempt I'm aware of), exponential backoff did not work well for some important RPs (e.g. compute/vm create). But, yeah, polling with a 1s interval is very likely going to cause quota problems with ARM.

**Comment by KrzysztofCwalina** [comment]
Should we consider client PollingOptions type similar to RetryOptions that would let users control the polling interval?

**Comment by tg-msft** [comment]
It's important to align this across languages, but I think there's also an opportunity here to unify the story across the SDK within each language.  There are several places where we wait across the Azure SDK for .NET with separate implementations and no feature parity.  If I had to rephrase today's proposal in terms of our existing APIs:
- LRO waiting today: `RetryOptions { MaxRetries = int.MaxValue, Delay = TimeSpan.FromSeconds(1), MaxDelay = TimeSpan.FromSeconds(1), Mode = RetryMode.Fixed }`
- Suggested LRO waiting for management libraries: `RetryOptions { MaxRetries = int.MaxValue, Delay = TimeSpan.FromSeconds(0.8), MaxDelay = TimeSpan.FromMinutes(1), Mode = RetryMode.Exponential }`

&nbsp;

## Where the SDK waits today
- Azure.Core's [RetryPolicy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/Internal/RetryPolicy.cs) / [RetryOptions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/RetryOptions.cs)
- Messaging
    - [ServiceBusRetryPolicy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs#L125) / [BasicRetryPolicy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Core/BasicRetryPolicy.cs#L80) / [ServiceBusRetryOptions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryOptions.cs)
    - [EventHubsRetryPolicy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubsRetryPolicy.cs#L21) / [BasicRetryPolicy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/BasicRetryPolicy.cs#L93) / [EventHubsRetryOptions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubsRetryOptions.cs)
- _(The above delays happen intra-pipeline while all the below happen extra-pipeline)_
- Azure.Core's [Operation](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Operation.cs#L148)  **<-- Proposed changes for today's meeting**
- Search's [ManualRetryDelay](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Batching/ManualRetryDelay.cs#L50) / [SearchIndexingBufferedSenderOptions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Batching/SearchIndexingBufferedSenderOptions.cs) for [fancy batching](https://github.com/Azure/azure-sdk/issues/2241#issuecomment-759735302)
- Azure.Core's [RetriableStream](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/RetriableStream.cs) as used by [Blobs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs#L1284) / [Files](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Files.Shares/src/ShareFileClient.cs#L1960) / [ACS CallingServer](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/communication/Azure.Communication.CallingServer/src/Downloader/ContentDownloader.cs#L36)  _(not technically adding any delay, but it's retrying for a constant number of attempts)_
- _???_

&nbsp;

## Making delays first class

### Opportunities
- Sane story for different behavior between data/management plane LRO delays
- Champion Scenario throttling _(when you have to transfer a lot of data to the cloud to get started, but it's very easy to trip over service limits and get throttled)_
    - Uploading documents to an index in Search _(i.e., fancy batching from above)_
    - Creating a bunch of keys at once in KeyVault
    - _???_
- Potentially unify intra/extra pipeline retries/delays
- Delay across resources/clients
    - Optional backpressure when service calls are throttled
    - Circuit-breaker like functionality for network issues

### Rough thoughts
- Add a `Delay` class encapsulating the settings for delay calculation 
    - Make it possible to use with `RetryOptions` for all the different types we have like Messaging/Search _(maybe .ctor overloads, maybe casts, maybe deriving)_
    - Expose default LRO `WaitForCompletionDelay` settings on `ClientOptions` which default to the current data plane settings
        - Override the default settings on `ArmClientOptions` for the management plane settings
        - Consider adding `waitForCompletionDelay` as an optional param on `Operation.WaitForCompletion`
        - Would still be easily changed globally via `ClientOptions.Default`
    - Implement the calculation logic for all the major types of delay including
        - Server delay _(i.e., `Retry-After`)_
        - Linear (+ jitter)
        - Exponential backoff (+ jitter)
- Possibly add a `Waiter` class that generalizes the logic of actually sit there waiting
    - Would do better than `Thread.Sleep` by default, like we do today, but could theoretically be overriden if someone wanted to get nuts for a specific `SynchronizationContext`.
    - Some mechanism for tracking the necessary state that `Delay` needs, in particular the number of failed attempts that we currently get from `HttpMessage` annotations
    - It's possible we want to route the `ResponseClassification` logic through this type so it's possible
    - This is where we could create artificial backpressure, though we'd need a way of exposing observable metrics to customers
    - There's a possibility of aligning some of this with `ResponseClassifier` as well so we could have a service specific notion of throttling behavior _(i.e, `503` makes sense to retry by default, but should it be considered throttling?)_
- Experiment with autoscaling via AIMD, PID controllers, etc.

### My goals for today
- Agreement on what we'd like this experience to look like in a year
- Figure out how to enable the scenario management plane LROs need without doing any of the broader work now but making it possible to slot in later


&nbsp;

## References
- Azure SDK General Guidelines:
  - [Retry Policy](https://azure.github.io/azure-sdk/general_azurecore.html#retry-policy)
    > ✅ DO offer the following configuration settings:
    >   - Retry policy type (exponential or fixed)
    >   - Maximum number of retries
    >   - Delay between retries (timespan/duration; this is the delay for fixed policy, the delay is increased exponentially by this amount for the exponential policy)
    >   - Maximum retry delay (timespan/duration)
    >   - List of HTTP status codes that would cause a retry (default is “all service errors that are retryable”)

    > ✅ DO retry if the service successfully responds indicating that it is throttling requests (for example, with an “x-ms-delay-until” header or similar metadata).

    > ☑️ YOU SHOULD implement a default policy that starts at 3 retries with a 0.8s delay with exponential (plus jitter) backoff.
  - [Long Running Operations](https://azure.github.io/azure-sdk/general_design.html#long-running-operations)
    > ✅ DO represent long-running operations with some object that encapsulates the polling and the operation status. This object, called a poller, must provide APIs for:
    > 
    >   2. requesting an asynchronous notification when the operation has completed

    
    > ✅ DO support the following polling configuration options:
    >  - pollInterval
    > 
    > Polling configuration may be used only in the absence of relevant retry-after headers from service, and otherwise should be ignored.
- Jeff's [Architecting Distributed Cloud Applications](https://www.youtube.com/playlist?list=PL9XzOCngAkqs0Q8ZRdafnSYExKQurZrBY) course
- Retries
    - Azure's [Transient fault handling](https://docs.microsoft.com/en-us/azure/architecture/best-practices/transient-faults) / [Retry Pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/retry) / [Circuit Breaker pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker)
    - AWS's [Exponential Backoff and Jitter](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/) / [Timeouts, retries, and backoff with jitter](https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/) / [Retry, backoff, and jitter section of re:Invent talk](https://www.youtube.com/watch?v=sKRdemSirDM&t=1900s)
    - GCP's guidelines from [_API Design Patterns_](https://learning.oreilly.com/library/view/api-design-patterns/9781617295850/OEBPS/Text/29.htm#heading_id_1)
    - [Take it easy on the automatic retries](https://devblogs.microsoft.com/oldnewthing/20051107-20/?p=33433) / [The waiting is the hardest part](https://www.youtube.com/watch?v=uMyCa35_mOg)
- Autoscaling, backpressure, etc.
    - Azure's [Throttling pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/throttling) /  [Autoscaling Guidance](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/dn589774(v=pandp.10))
    - [Feedback Control for Computer Systems](https://learning.oreilly.com/library/view/feedback-control-for/9781449362638/)
    - [PID Loops and the Art of Keeping Systems Stable](https://www.youtube.com/watch?v=3AxSwCC7I4s) / [Close Loops & Opening Minds: How to Take Control of Systems](https://www.youtube.com/watch?v=O8xLxNje30M)
    - [Backpressure: Resistance is NOT Futile](https://www.youtube.com/watch?v=I6eZ4ZyI1Zg) / [Real-time Insights powered by Reactive Programming](https://www.youtube.com/watch?v=uODxUJ5Jwis)

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/55d70840-98dc-a505-eb9d-f1ec85458524)[MS INTERNAL ONLY]

- .NET's management plane operations will override `WaitForCompletion` and hard code an exponential backoff up to a max of around 30s (TODO: sync with ARM folks for the exact number) for their GA release
- We'll continue to investigate building a general purpose `Delay` abstraction
