### ISSUE TITLE
Reviewing APIView latest designs

### ISSUE THREAD

**Issue by salameer** [Azure/azure-sdk#3844]
Hellooooo

Would love to book sometime with the architects (minimum of an hour) to review the design improvements of the APIView tool.

@weshaggard  @praveenkuttappan @chidozieononiwu @kurtzeborn @mikekistler  as additional attendants

**Comment by lilyjma** [comment]
scheduled for 2/7 2-3pm pst

**Comment by praveenkuttappan** [comment]
@lmazuel fyi since you have asked to be part of this APIView demo

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/6be30840-98dc-a228-7144-f1ec89446893)[MS INTERNAL ONLY]
