### ISSUE TITLE
Update eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1

### ISSUE THREAD

**Issue by czubair** [Azure/azure-sdk#3850]
Add back in automation that changes DevOps work items to "not in release" once a package ships.

Change:
- Stopped changing the state when a package ships or is created
To:
- Change the state when a package ships or is created

https://github.com/Azure/azure-sdk/commit/e0051ac4a28a513b66e6ee480018df692ab79f97

**Comment by weshaggard** [comment]
Fixed with https://github.com/Azure/azure-sdk/commit/24657354811ef7aebfd7f973b8bc153f57fe7b28.
