### ISSUE TITLE
Board Review: Introducing ApiGen

### ISSUE THREAD

**Issue by craigktreasure** [Azure/azure-sdk#3851]
## Context

The topic of ApiGen has come up a few times in our history of doing reviews with the Azure Review Board. It is common in Mixed Reality SDKs and is also used in the ACS SDK. In a recent review with ACS, they (Ted) asked for an informal brief walkthrough of the tool (ApiGen) we use to generate the public surface of our non-open source SDKs for various endpoints. We'll go over what ApiGen is, the problems it attempts to solve, competitors in that space and why we opted for yet another codegen tool, and answer any questions they may have.

## Contacts and Timeline

* Service team responsible for the client library: ApiGen
* Main contacts: @craigktreasure
* Overview and Documentation: https://aka.ms/apigen/docs

**Comment by lilyjma** [comment]
scheduled for 3/1 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/7c830840-98dc-a999-36eb-f1ec99bdb0aa) (MS INTERNAL ONLY)

**Comment by craigktreasure** [comment]
[PowerPoint slides](https://microsoft.sharepoint.com/:p:/t/ApiGenTools/ERmwYqaK3VxDqotBK-twqA4BbAHGO_tACEFRRHNNNN3iLA?e=L6T5Un) (MS INTERNAL ONLY)
