### ISSUE TITLE
Change Request: More prescriptive telemetry client library name guidance for General Guidelines

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk#387]
## The Basics

* Which design guideline is affected?
  [Client Library Usage Telemetry](https://github.com/Azure/azure-sdk/blob/master/docs/design/Telemetry.mdk#L14) and in particular the line
  > `<client_lib> ::=` client library name (all lowercase), e.g. "blobstorage", "keyvault"

* Which target languages are affected?
  All languages

* Describe the change:
  We should be more prescriptive with our client library name guidance so our user agent strings are consistent across languages. 

## Reasoning
We've had `n` developers write the client library name for blobs in `n` different ways.  We should add additional guidance so everyone ends up with the same `client_lib` and user agent format.

Some possible options to help drive discussion:
* The name in the Portal (Storage account > Blobs)
* The name in the official documentation, dropping Azure if present ([Blob Storage](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction) via conceptual docs or [Blob Service](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-rest-api) via REST API)
* The name on the marketing page ([Blob Storage](https://azure.microsoft.com/en-us/services/storage/blobs/))
* The name of the package (varies by language)
* The name of the folder in the repo (tied to the package, which varies by language)
* A fixed list of names in the guidelines, like our [.NET namespace groups](https://github.com/Azure/azure-sdk/blob/master/docs/design/dotnet/DesignGuidelines.mdk#L511)

**Comment by tg-msft** [comment]
Please also see #356 for a related discussion about consistent naming across our repos.

**Comment by adrianhall** [comment]
Discussed over two board meetings and agree this is a requirement for all languages.  The general guidelines have been updated in PR #412 to accomodate these changes.
