### ISSUE TITLE
Board Review: azure-cosmos-encryption

### ISSUE THREAD

**Issue by simplynaveen20** [Azure/azure-sdk#3875]
Please find the below details for the meeting

## Contacts and Timeline

* Responsible service team: Cosmos Java SDK
* Main contacts: Naveen Singh (nakumars@microsoft.com)
* Expected code complete date: 20 Feb
* Expected release date: 1 March

## About the Service 

* https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos/azure-cosmos-encryption#key-concepts

## About the client library

* Name of the client library: azure-cosmos-encryption
* Languages for this review: Java

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/4238bb36455a4b2e91ce78ee66b23c78
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-encryption/src/samples/java/com/azure/cosmos/encryption/Program.java

**Comment by lilyjma** [comment]
scheduled for 2/15 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/72b40840-98dc-a228-7dd5-f1ec8eb4737a)[MS INTERNAL ONLY]

**Comment by kushagraThapar** [comment]
Closing this, as it has been GAed.
