### ISSUE TITLE
Board Review: Small, Targeted Change for Azure.DigitalTwins.Core

### ISSUE THREAD

**Issue by sjiherzig** [Azure/azure-sdk#3876]
We intend to release a new data plane API version - 2021-06-30-preview - that is _identical_ to the current API version 2020-10-31 (for which a GA SDK exists). The only differences are:

 * API version 2021-06-30-preview added
 * src/Models/DigitalTwinPropertyMetadata.cs contains a new _optional_, writeable property `sourceTime`

Link to changes: https://github.com/Azure/azure-sdk-for-net/pull/26495/files . All other changes are a result of auto-generation, adding new API version, recording a set of new service traces for playback when running tests.

We were asked by the architecture review board to introduce a new API version, since PUT / PATCH of a `sourceTime` attribute results in a different response in currently supported API versions.

**Please let us know if a full review is required, or if this can count as a small, targeted change.** We are trying to add this feature in as soon as possible, ideally before February 15th.

## Contacts and Timeline

* Responsible service team: Azure Digital Twins
* Main contacts: @sjiherzig 
* Expected code complete date: 2/7/2022
* Expected release date: 2/15/2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/digital-twins/overview
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/digitaltwins/data-plane/Microsoft.DigitalTwins/preview/2021-06-30-preview/digitaltwins.json
* Link to GitHub issue for previous review sessions, if applicable:  N/A

## About the client library

* Name of the client library: Azure.DigitalTwins.Core
* Languages for this review: .NET

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/a33bab59b8bc43cdb83cf35b366016fa
* Link to Champion Scenarios/Quickstart samples: (unchanged)

**Comment by lilyjma** [comment]
@sjiherzig - does this need a full Board review or are you already working with the respective architects? Thanks
