### ISSUE TITLE
Board Review: Personalizer thick client story

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk#3877]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Personalizer
* Main contacts: @johnhuang01
* Expected code complete date: 02/21/2022
* Expected release date: 02/22/2022

## About the Service 

* Link to documentation introducing/describing the service: 
  * [Thick-client design doc](https://microsoft.sharepoint.com/:w:/t/personalizr/EVXhfzFkZ5RHlLm8SK6C1xwBuUkLQSvDQqwoKuvAAI628Q?e=Oluwcv)
  * [Model Put API](https://microsoft.sharepoint.com/:w:/t/personalizr/Ed0dN7HgEF9EhKj9Bx5BRfkBfu9Q6o9Fw_SeFW9X3F96EQ?e=ZP9W2X&CID=D24A1141-04ED-43CA-8278-74C8AC7BE91B&wdLOR=cC1B79B0D-2E02-47B5-ACAD-32C62A0B2799)
* Link to the service REST APIs:
  * https://github.com/Azure/azure-rest-api-specs/blob/b6f54bbdbb64a9e7d27b49b4e1db5e56e40c310d/specification/cognitiveservices/data-plane/Personalizer/preview/v1.1-preview.3/Personalizer.json
* Link to GitHub issue for previous review sessions, if applicable:
  * https://github.com/Azure/azure-sdk/issues/3124

## About the client library

* Name of the client library: Azure.AI.Personalizer
* Languages for this review: C#

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link:
  * [Azure.AI.Personalizer](https://apiview.dev/Assemblies/Review/5591b4c1c6ef46369ae25ec62bc1d058?diffRevisionId=bc708db2898e475db324fc2d686b1b34&doc=False&diffOnly=False)
  * [Rl.Net](https://apiview.dev/Assemblies/Review/57da3635d2274aef8aad975074c414f7)
* Link to Champion Scenarios/Quickstart samples:
  * [Rank tests](https://github.com/Azure/azure-sdk-for-net/pull/26828/files#diff-8e301e3a408ef4781e8a9f44bdb894dba8d7fc86d43de930e0039a5ccc5ffb32R24)
  * [Model tests](https://github.com/Azure/azure-sdk-for-net/pull/26828/files#diff-1fb0d459778458d60622871caa765d0ff679b52151c2dccd28289cc8c3f1ab21R27)

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by johnhuang01** [comment]
Design doc: 
Thick client:
https://microsoft.sharepoint.com/:w:/t/personalizr/EVXhfzFkZ5RHlLm8SK6C1xwBuUkLQSvDQqwoKuvAAI628Q?e=Oluwcv

Model Put API:
https://microsoft.sharepoint.com/:w:/t/personalizr/Ed0dN7HgEF9EhKj9Bx5BRfkBfu9Q6o9Fw_SeFW9X3F96EQ?e=ZP9W2X&CID=D24A1141-04ED-43CA-8278-74C8AC7BE91B&wdLOR=cC1B79B0D-2E02-47B5-ACAD-32C62A0B2799

Sample Codes:
\azure-sdk-for-net\sdk\personalizer\Azure.AI.Personalizer\src\Samples\SampleCode.cs

**Comment by lilyjma** [comment]
scheduled for 2/17 2-4pm pst

**Comment by johnhuang01** [comment]
Responsible service team: Personalizer
Main contacts: @johnhuang01
Expected code complete date: 2/21/2022
Expected release date: 2/22/2022

Link to the service REST APIs:
https://github.com/Azure/azure-rest-api-specs/blob/b6f54bbdbb64a9e7d27b49b4e1db5e56e40c310d/specification/cognitiveservices/data-plane/Personalizer/preview/v1.1-preview.3/Personalizer.json

**Comment by johnhuang01** [comment]
Microsoft.RL api view:  https://apiview.dev/Assemblies/Review/57da3635d2274aef8aad975074c414f7

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/c47b0840-98dc-a228-b4a7-f1ec904b6de5)[MS INTERNAL ONLY]
