### ISSUE TITLE
Change Request: `inSeconds` suffix for timeouts across all languages

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-sdk#388]
## The Basics

* Which design guideline is affected? **All**
* Which target languages are affected? **All**

* Describe the change: Any parameters and options for timeouts that are specified in seconds should be suffixed with "InSeconds".

## Reasoning

In JS-land, millisecond timeouts are very common so anything else should be named explicitly. Perhaps a similar situation exists in other language ecosystems, so this seems like a good guideline to have.

**Comment by johanste** [comment]
In python land, seconds is often used. The canonical example is `[time.sleep](https://docs.python.org/3.7/library/time.html#time.sleep)`. In #364, I have actually called out to use a suffix if the time is **not** seconds.

**Comment by adrianhall** [comment]
Rejects, per board review.

Brian feels that suffixing the duration in untyped durations is a good idea.  They've gone into the TYpeScript language.
