### ISSUE TITLE
Data-Plane Codegen (April 2022 - September 2022)

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#3910]
10k view: Improve value generated by DPG product, reducing the need for manual grow up

Rough list (needs breakdown as issues):
- New features & implementation:
  - Generate resilient models (C#, Java, Python). 12 weeks per languages.
  - State-aware autorest. 8 weeks.
    - C#: use m4 new feature to import past m4. Will be used in Mgmt as well.
    - Python: _may not_ use m4, but will need some work to reduce the size impact of multi-api support
- Sample & Test generation (C#, Java, Python, TS). 8 weeks.
- Continue working on the automation flow. 4 weeks.
- Docs language specific tooling. 4 weeks.
- Evaluate the need for DPG in JS (User studies? else?). Cost TBD.
- Service release support. 6 weeks.

Roughly, I think we can consider a 46 weeks per languages, where the amount varies per languages. I round it to 56 for C#.

Open question: Go and C++

**Comment by allenjzhang** [comment]
CADL integration is on our Co list. It will be driven from CADL side by requires collaboration from all codegen (mgmt+data) to surface any asks. For example, mgmt already surfaced parent/child, singleton, extension resource asks which we are addressing.

**Comment by lirenhe** [comment]
1.  Document: 
- Docs site: Conceptual Documentation for DPG design, usage pattern, trouble shooting etc.

- Internal:  Docs for onboarding process, grow up story.  

2. Process & tooling improvement:
- Build new tool/improve the existing tooling
    a. breaking change detection
    b. New linter rules for DPG.
    c. etc. 
- Shift Left to detect Swagger/Swagger sample/CodeGen problems at early stage.

3. Telemetry for usage data collection and reporting

4. Sample generation:  from basic sample to hero scenarios if possible. 

5. JS: Validate portal integration for RLC.
