### ISSUE TITLE
Board Review: Final reivew for dotnet Azure.ResourceManager libraries

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk#3937]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: SDK Team
* Main contacts: Michael Nash, Arthur Ma
* Expected code complete date: 2/28
* Expected release date: 3/14

## About the Service 

This is the new generation for dotnet management plane SDKs.  We have incorporated all of the feedback from previous reviews and are looking to do the final review before we GA.

## About the client library

* Name of the client library: Azure.ResourceManager.*
* Languages for this review: Dotnet

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link:
o	[Azure.ResourceManager](https://apiview.dev/Assemblies/Review/f6d0e5c39961448fb07909c216860ffc)
o	[Azure.ResourceManager.KeyVault](https://apiview.dev/Assemblies/Review/31f61775b5ed45fabb419f00f13abad6)
o	[Azure.ResourceManager.Resources](https://apiview.dev/Assemblies/Review/4f2a3b8e84644efcb90f782e63105dfe)
o	[Azure.ResourceManager.Compute](https://apiview.dev/Assemblies/Review/d318255137ee41d994430581f7ee928f)
* Link to Champion Scenarios/Quickstart samples:
https://github.com/Azure/azure-sdk-for-net/blob/f0718b12ea/sdk/resourcemanager/Azure.ResourceManager/README.md
https://github.com/Azure/azure-sdk-for-net/blob/f0718b12ea/sdk/compute/Azure.ResourceManager.Compute/README.md
https://github.com/Azure/azure-sdk-for-net/blob/f0718b12ea/sdk/resources/Azure.ResourceManager.Resources/README.md
https://github.com/Azure/azure-sdk-for-net/blob/f0718b12ea/sdk/keyvault/Azure.ResourceManager.KeyVault/README.md

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 2/24 2-4pm pst

**Comment by m-nash** [comment]
Per @tg-msft we also want to talk about how to represent generic objects in the schema in dotnet.  Right now it is generated as an `object` which is not ideal.  Here is usage today on how a customer can use these objects https://gist.github.com/m-nash/da14d7d7bee8679f281ed963e9ea53d4

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/51db0840-98dc-a228-1dfb-f1ec95cfdbbb)[MS INTERNAL ONLY]
