### ISSUE TITLE
Board Review: @azure/communication-react  -- File Sharing

### ISSUE THREAD

**Issue by anjulgarg** [Azure/azure-sdk#3946]
## Contacts and Timeline

* Responsible service team: [acswebuidev@microsoft.com](mailto:acswebuidev@microsoft.com)
* Main contacts: alkwa, de.david, anjulgarg
* Expected code complete date: March 6th, 2022
* Expected release date: April 1st, 2022 (Public Preview)

## About the Service 

* Link to documentation introducing/describing the service: [UI Library - File Sharing Implementation Guide](https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/ER0ji7YlpopJgIFwcE8Eeg8Bt_hPJj5_TRzaXXktN4j4lg?e=E2eG1G)
* Link to the service REST APIs: N/A
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/3231

## About the client library

* Name of the client library: `@azure/communication-react` -- `File Sharing`
* Languages for this review: TypeScript

## Artifacts required

* APIView Link: [API Diff](https://apiview.dev/Assemblies/Review/a6c94f8d785f47b9b156782e7ec47fd8?diffRevisionId=73a42103253c4a76b62a00ca2d7bfb12&doc=False&diffOnly=True)
* Link to Champion Scenarios/Quickstart samples: [UI Library - File Sharing Implementation Guide](https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/ER0ji7YlpopJgIFwcE8Eeg8Bt_hPJj5_TRzaXXktN4j4lg?e=E2eG1G)
* PPT Presentation: [File Sharing - PPT](https://microsoft.sharepoint-df.com/teams/IC3SDK/_layouts/15/Doc.aspx?sourcedoc=%7B7160C655-6BDF-4F56-8302-4F394FFED34E%7D)

**Comment by lilyjma** [comment]
scheduled for 3/2 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/b4a80840-98dc-a999-6753-f1ec9a8238df) (MS INTERNAL ONLY)
