### ISSUE TITLE
Design Guidelines for Progress Reporting

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk#395]
We need to add design guidelines for APIs that want to expose progress reporting.

**Comment by tg-msft** [comment]
While considering options, please note Storage is already including a version of progress reporting for Upload operations via  https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/src/StorageProgress.cs but I think it would make sense to align on something in Azure.Core if possible.

**Comment by adrianhall** [comment]
Per board discussion, added PR #426 to address
