### ISSUE TITLE
Board Review:  Azure Communication Services (SPOOL) - Auth - Added Proactive Autorefresh (Python)

### ISSUE THREAD

**Issue by petrsvihlik** [Azure/azure-sdk#3954]
## Contacts and Timeline

* Responsible service team: **ASC Auth**
* Main contacts: Petr Svihlik (@petrsvihlik), Aigerim Beishenbekova (@AikoBB)
* Expected code complete date: Feb 2022
* Expected release date: Mar 2022

## About the Service 

* Link to documentation introducing/describing the service: N/A
* Link to the service REST APIs: N/A
* Link to GitHub issue for previous review sessions, if applicable:  we planned to introduce a way to configure the autorefresh interval in all ACS Auth SDKs, however in #3712  we decided not to implement it keep only the autorefresh itself. so we're adding it for python (other languages already have it implemented)

## About the client library

* Name of the client library: azure-communication-chat
* Languages for this review: Python

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/c442ec17a8ee42f09cafffbe24438505?diffOnly=True&diffRevisionId=3f5f1b8655414b00aada13b3fa67c240
* Link to Champion Scenarios/Quickstart samples:
  
## Scenario
From our [docs](https://docs.microsoft.com/en-us/azure/communication-services/concepts/credentials-best-practices?tabs=javascript#proactive-token-refreshing):

> Use proactive refreshing to eliminate any possible delay during the on-demand fetching of the token. The proactive refreshing will refresh the token in the background at the end of its lifetime. When the token is about to expire, 10 minutes before the end of its validity, the Credential will start attempting to retrieve the token. It will trigger the refresher callback with increasing frequency until it succeeds and retrieves a token with long enough validity.
    
This mechanism is common to our JS, .NET, and Java SDKs, we're bringing the Python one on par with the other ones.

**Comment by lilyjma** [comment]
scheduled for 3/3 9-11am pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/2bdb0840-98dc-a999-8eab-f1ec9b3d6a0d) (MS INTERNAL ONLY)

**Comment by petrsvihlik** [comment]
approved by @annatisch in #21834
