### ISSUE TITLE
Board Review: Introducing Load Test service

### ISSUE THREAD

**Issue by ninallam** [Azure/azure-sdk#3956]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Azure Load Testing team
* Main contacts: Abhishek Ranjan (@abranj1219), Nikita Nallamothu (@ninallam) Harshan B (@Harshan01)
* Expected GA date for this library: To be decided

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/load-testing/
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/loadtestservice
* Is the goal to release a Public Preview, Private Preview, or GA?  Public Preview

## About the client library

* Name of client library: Load Test service
* Link to library reference documentation: N/A
* Is there an existing SDK library? If yes, provide link:  No

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library? Internal automated load testing workflows
2. Who is the end-user of the application (the developer's customer)? DevOps teams who require Azure Load Testing
3. What features of the API need to be explained in the sample so that someone could use this API in real app? Creating/updating a Test, and creating/updating a test run and getting test metrics.
4. How does the **authentication** workflow look? OAuth2 token-based authentication from Service Principal credentials
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

* Champion scenario 1
    * Link to library’s sample folder: https://gist.github.com/Harshan01/03d64552dcb7c28b86ebfeb3fc1df953

**Comment by lmazuel** [comment]
I feel important to clarify that Azure Load Test team is going through DPG flow, and having some discussion around names in the API.

**Comment by annelo-msft** [comment]
APIView for .NET: https://apiview.dev/Assemblies/Review/fe482cb7d6b549ee83b36915d9fcd417

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/90830840-98dc-a999-43b3-f1ec9e81f02f) (MS INTERNAL ONLY)
