### ISSUE TITLE
Change Request: Error response deserialization

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk#3959]
## The Basics

* Which design guideline is affected?

  In general, all of [Error handling](https://azure.github.io/azure-sdk/general_implementation.html#error-handling), though specifically to modify:
  * https://azure.github.io/azure-sdk/general_implementation.html#general-errors-include-request-response
  * https://azure.github.io/azure-sdk/general_implementation.html#general-errors-rich-info

* Which target languages are affected?

  All (though not all might require a change to implementation).

* Describe the change:

  We should only deserialize the error response object. Any additional data within the response body could be retrieved via the raw response.

## Reasoning

Error objects maybe logged as-is along with any content in the response.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/51db0840-98dc-a228-a209-f1ec95d06d50)[MS INTERNAL ONLY]
