### ISSUE TITLE
Board Review:  Azure.Identity API Updates for April Release

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk#3965]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team:
* Main contacts: sschaab
* Expected code complete date: 4/1/2022
* Expected release date: 4/5/2022

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## New Feature Champion Scenarios: About the client library

[Account Identifier Logging](https://gist.github.com/sadasant/806dc9751923f2960eaf17f16848643b)
[Identity User Manage Identity by Resource Id](https://gist.github.com/christothes/bf3c9cdcdee2ffdc6335c551ff4e63f6)
[Adding `ClientAssertionCredential` to enable federated token exchange](https://github.com/g2vinay/KVSpec/blob/master/ClientAssertionCredential.md)

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/8eae839add2944468464609a2f1a7cfe/aff06f1bf96741bc96bdd65578655943?diffRevisionId=6361bbf632f8404d9a71ede72582d2c1&doc=False&diffOnly=True
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/1f5d616d078e49cdb94f5683e801d55d?diffRevisionId=679ad38d2d064bd5a4ffa75d6ab630f8&doc=False&diffOnly=False&revisionId=41572c69f35f4864a9160df62fcb7099
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/ee993c29a21746d5b3d98d496b538f93/927c6abbd6814b808cf76faf2e507f61?diffRevisionId=ab94b712f31a4736a71f6590bb236903&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/f1d54ed5f5f64bf1891214127f2df609?revisionId=a5744a6cf4264e09acda6a44f3b8f43e&diffRevisionId=09e41c922fb5462996cc57930fc78875&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 3/10 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/ed7f0840-98dc-997c-e1b3-f1eca47af51a) (MS INTERNAL ONLY)
