### ISSUE TITLE
Board Review: Introducing Azure.Communication.Chat .NET SDK integrate with trouter lib for real-time notifications

### ISSUE THREAD

**Issue by CHILIU-MSFT** [Azure/azure-sdk#3985]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: ACS Chat
* Main contacts: Chi Liu<@CHILIU-MSFT> Andrei Giurgiu <@angiurgiu>
* Expected stable release date for this library: CY2022 Q2

## About the Service 

* Link to documentation introducing/describing the service: https://skype.visualstudio.com/SPOOL/_wiki/wikis/SPOOL.wiki/28863/ACS-Chat-.NET-SDK-Real-time-Notification-Trouter-Integration
* Link to the service REST APIs: No new REST APIs introduced in this change
* Is the goal to release a Public Preview, Private Preview, or GA? Will go Public Preview first, then GA.

## About the client library

* Name of client library: Azure.Communication.Chat
* Link to library reference documentation: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/communication/Azure.Communication.Chat
* Is there an existing SDK library? If yes, provide link: 
Yes. 
This introductory session is to integrate with a new dependency (trouter lib) for enabling real-time notifications in ACS Chat .Net SDK.

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
4. How does the **authentication** workflow look? 
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario
See https://skype.visualstudio.com/SPOOL/_wiki/wikis/SPOOL.wiki/28863/ACS-Chat-.NET-SDK-Real-time-Notification-Trouter-Integration

## **Note**

Please include Trouter team [trouternotify@microsoft.com](mailto:trouternotify@microsoft.com) (Contacts: Jiri <jiri.hruska@microsoft.com> Alexander <alexander.zakharov@skype.net>) in the Arch Board Review meeting. They are the owner of the new dependency and will help answer questions about the dependency lib. Note Trouter team is in Prague. Please schedule the meeting at a Prague friendly time (for example 8 am PST). Thanks!

**Comment by CHILIU-MSFT** [comment]
https://microsoft-my.sharepoint-df.com/:w:/p/lichi/ETkBNF3Wt9xJrWy1ADZhn04B_wcmfSw5uW-68Jv7fpEZ3g?e=nSqAXy
This is the docx format of the Champion Scenarios.

**Comment by srnagar** [comment]
[Recording](https://msit.microsoftstream.com/video/6aae0840-98dc-bd6c-f456-f1ecf89bd545) (MS INTERNAL ONLY)
