### ISSUE TITLE
Board Review:  Azure Communication Services (SPOOL) - SIP routing

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4006]
## Contacts and Timeline

* Responsible service team: 
* Main contacts:
jiriburant@microsoft.com
boris.bazilevskiy@microsoft.com
jannovak@microsoft.com

* Expected code complete date: N/A
* Expected release date: N/A

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/communication-services/concepts/telephony/direct-routing-provisioning
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/communication/data-plane/SipRouting/preview/2021-05-01-preview
* Link to GitHub issue for previous review sessions, if applicable:   https://github.com/Azure/azure-sdk-pr/issues/770

## About the client library

* Name of the client library: Phone Numbers
* Languages for this review: C#, Python, Java, Javascript

### Purpose of the library:
We are adding client allowing user to call two API endpoints for retrieving and setting the SIP routing configuration for a communication resource.

#### Description:
- Each resource has exactly one SIP configuration, containing dictionary of trunks and list of routes. The API provides GET and PATCH endpoints for the whole configuration. The SIP configuration PATCH request may contain full SIP configuration(trunks and routes), or just trunks or just routes.
The trunks allow for partial updates, they are merged with the incoming trunk dictionary. The routes don’t allow for partial updates, the whole list is replaced by the incoming list (if it is present on PATCH request).
- Our proposed SDK allows for changing, adding and deleting a trunk or route separately (separate functions for trunks/routes and operations performed on one item).
It also allows for retrieving all currently configured trunks/routes and replacing the trunks or routes configuration.
- For trunks the identifier is its FQDN, for routes it is its Name.

### Champion scenarios:
1) Retrieve trunks/routes - Returns list of currently configured trunks or routes.
2) Set trunk/route - Changes item in collection if exists, adds new one otherwise
3) Delete trunk/route - Removes specified trunk/route
4) Replace trunks/routes - Overwrites the collection of trunks/routes with the new collection

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/b32afd45c457422992f506154f376d68#Azure.Communication.PhoneNumbers.SipRouting
* Link to Champion Scenarios/Quickstart samples: https://github.com/jiriburant/azure-sdk-for-net/blob/feature/communication-siprouting/sdk/communication/Azure.Communication.PhoneNumbers/tests/SipRouting/samples/Sample_SipRoutingClient.md

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/300aa54ba60742b4890c4a0a0853fad9
* Link to Champion Scenarios/Quickstart samples: https://github.com/jannovak-msft/azure-sdk-for-java/blob/feature/communication-siprouting/sdk/communication/azure-communication-phonenumbers/src/samples/java/com/azure/communication/phonenumbers/siprouting/Example.java

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/b94a4bb2e47040d7a0a36c0f11d88ed3
* Link to Champion Scenarios/Quickstart samples: https://github.com/jiriburant/azure-sdk-for-python/blob/implementing-inputs-from-api-review/sdk/communication/azure-communication-phonenumbers/test/siprouting/champion_scenarios.py
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/abf90e57a8bc41c8be5fae8ed2ec6474
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-js/blob/jannovak/communication-phonenumbers-siprouting/sdk/communication/communication-phone-numbers/samples-dev/siprouting/example.ts
    
ADO link: https://skype.visualstudio.com/SPOOL/_workitems/edit/2785757/

**Comment by lilyjma** [comment]
scheduled for 3/22 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/57ae0840-98dc-997d-a027-f1ecbb669623) (MS INTERNAL ONLY)
