### ISSUE TITLE
Board Review: Introducing Azure Experimentation

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk#4021]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

* Responsible service team: ExP
* Main contacts: [sashank.kolli@microsoft.com](mailto:sashank.kolli@microsoft.com); [aprilk@microsoft.com](mailto:aprilk@microsoft.com); [hengyl@microsoft.com](mailto:hengyl@microsoft.com) ; [smichtch@microsoft.com](mailto:smichtch@microsoft.com) ; [alfabija@microsoft.com](mailto:alfabija@microsoft.com) 

* Expected code complete date:4/15/2022
* Expected release date: 4/30/2022

## About the Service 

* Link to documentation introducing/describing the service:
                [https://eng.ms/docs/products/experimentation-platform](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Feng.ms%2Fdocs%2Fproducts%2Fexperimentation-platform&data=04%7C01%7CJiayi.Ma%40microsoft.com%7C9dffc676910d49a583cd08da03916305%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637826220223098708%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=f%2FvD2I36myDPcWGCl33LstkJ4DG5vw4gBfwUS2aBtD0%3D&reserved=0)
* Link to the service REST APIs: 
                [https://github.com/sakoll/azure-rest-api-specs-pr/blob/sakoll-msft/expDataPlane/specification/experimentation/data-plane/Microsoft.Experimentation/preview/2021-11-01-preview/experimentation.json](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsakoll%2Fazure-rest-api-specs-pr%2Fblob%2Fsakoll-msft%2FexpDataPlane%2Fspecification%2Fexperimentation%2Fdata-plane%2FMicrosoft.Experimentation%2Fpreview%2F2021-11-01-preview%2Fexperimentation.json&data=04%7C01%7CJiayi.Ma%40microsoft.com%7C9dffc676910d49a583cd08da03916305%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637826220223098708%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zYc4MQFLURv13OjBaOk7xgdkRYiujZXrV0vUGIao1B0%3D&reserved=0)
* Is the goal to release a Public Preview, Private Preview, or GA? 

## About the client library

* Name of client library: Azure.Analytics.Experimentation 
* Languages for this review: .NET

### .NET
- [APIView](https://apiview.dev/Assemblies/Review/2bab04a94f5140749f95ecab5eb96f19?revisionId=2cc3d7a036fc48928318f2b26a69780e&doc=False)
- Older version of API View (https://apiview.dev/Assemblies/Review/2bab04a94f5140749f95ecab5eb96f19)

## Step 1: Champion Scenarios 

See here: https://microsoft.sharepoint.com/:w:/t/expshared/EdCTDuOFS5hJoSCntmhEazoBiudRhB-BZo6K-K4jzgl6tQ?e=YmDRNY

**Comment by lilyjma** [comment]
scheduled for 4/4 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/e9e80840-98dc-9982-f0db-f1ecb46e618c) (MS INTERNAL ONLY)
