### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - Calling Native - Raw Video V2 primitives/public preview (Android)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4035]
## Contacts and Timeline

* Responsible service team: Azure Communication Services (SPOOL) Calling Native SDK Team
* Main contacts: gaobob@microsoft.com; yassirb@microsoft.com
* Expected code complete date: 4/29/2022
* Expected release date: 5/6/2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/communication-services/overview

## About the client library

* Name of the client library: com.azure.android:azure-communication-calling
* Languages for this review: Android (Java)

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/6f1ac7159fd34dfeb6d97199adfa1188?revisionId=09e83e6f37f74ea6ba967972af0f12be&diffRevisionId=bb42b150bb0b482394dc53413babed97&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples: https://github.com/MicrosoftDocs/azure-docs/pull/91740/commits/2d12b09e8416542449d1c549ff9a8fba4aeb69b8?short_path=4b76408#diff-4b764082744fc6f32455e9dfbb17bec2e81d4045f8cddbad81a6c49294aa241b

**Comment by lilyjma** [comment]
scheduled for 4/27 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/f4d10840-98dc-b654-b0b4-f1ecc72b72e7) (MS INTERNAL ONLY)
