### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - Mobile UI Library - Localization  (Android & iOS)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4046]
## Contacts and Timeline

* Responsible service team: Mobile UI Team
* Main contacts: Wayne (iOS), James (Android)
* Expected release date: April  4th

## About the Service 

* Link to documentation introducing/describing the service:
- [iOS Localization Concept](https://microsoft.sharepoint-df.com/teams/ACSMobileUI/_layouts/OneNote.aspx?id=%2Fteams%2FACSMobileUI%2FSiteAssets%2FACS+Mobile+UI+Notebook&wd=target%28Release+Features.one%7C3C095CA1-3604-4184-8B89-14311E09EB25%2FLocalization+%28iOS%5C%29%7CAA4B7E72-A31D-4B6B-89B3-9EDC0114D1B6%2F%29&xsdata=MDN8MDF8fDBmYTRjZjQzN2QzYTQxMWU5ZjQ0MWExMTJhMWE3MmEzfDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDB8MHw2Mzc4MzY1NjgyMDE2Njg1NDZ8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT0%3D&sdata=UGxvWGhCV1FsU3h2ZGZjblU3Vm1YVHhVcEV1U3lNZjVaZGNuSVBqTmdYND0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Clongamy%40microsoft.com)
- [Android Localization Concept](https://microsoft.sharepoint-df.com/teams/ACSMobileUI/_layouts/15/Doc.aspx?sourcedoc={3b444519-39b8-45cd-909e-9d05dd59771b}&action=edit&wd=target%28Release%20Features.one%7C%7B3c095ca1-3604-4184-8b89-14311e09eb25%7D%2FLocalization%20%28Android%5C%29%7Cd371d719-9a5c-4f35-b1e9-30e6461eef12%2F%29&wdorigin=703)

## About the client library

* Name of the client library: Mobile UI Library
* Languages for this review: iOS (swift), Android (Java)

### iOS (Swiftt)
* APIView Link:
[AzureCommunicationUI](https://apiview.dev/Assemblies/Review/4213efb995464aa28bb6d2b69cb02156?revisionId=d56e53c4bb374bd7b8012b9b00dadd47&doc=False)

### Android (Java)
* APIView Link:
[azure-communication-ui](https://apiview.dev/Assemblies/Review/6c99f6dc8e134efa8e163d7d941519c7)

## Quickstarts
[Android](https://github.com/Azure/communication-ui-library-android)

[iOS](https://github.com/Azure/communication-ui-library-ios)

**Comment by lilyjma** [comment]
scheduled for 3/23 2-4pm pst. @garchiro7 -- please include APIViews and Champion Scenarios ASAP

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/b3a00840-98dc-997c-7358-f1ecaaf977a7) (MS INTERNAL ONLY)
