### ISSUE TITLE
Board Review: <Azure.Storage.*>

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk#4066]
Discussion is focused on behavior and defaults. Relevant artifacts are performance data, rather than API views.

## Contacts and Timeline

* Responsible service team: Storage Developer Experience
* Main contacts: amishra, jaschrep
* Expected code complete date:
* Expected release date:

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs:  

## About the client library

* Name of the client library: Azure.Storage.*
* Languages for this review: .NET/all

## Topics

* `StorageTransferOptions`
  * Changing defaults
    * 256MB initial transfer size causes problems, and rarely offers any benefits with modern versions
    * Drastically reducing this number is desired
  * Unification across languages
    * sdks have several different behaviors and chosen numbers for this
    * different libraries are making some good optimizations that should inspire other libraries
* Transactional checksum default behavior
  * feature hasn't been released in any form yet
  * apis already approved
  * looking to enable by default on uploads
  * cpu is the only real performance hit when using this feature
* Moving classes like `StorageTransferOptions` or `UploadTransferValidationOptions` to `ClientOptions`
  * Finalizing what does and doesn't make it into clientoptions, method args, or both
  
[Broad stroke topics from Ashish]
* Moving the Java SDK off Maven
* SDK deprecation plan/ideas 
* SDK security vulnerabilities plan

## Performance Measurements

[.NET (MSFT internal only)](https://microsoft-my.sharepoint.com/:x:/p/jaschrep/EZMaEoe4JCRFsPTM6Pa4wmMBDh9setlEyes6HjUTyC-pgw?e=pIfHKN)

## Slide deck

[Here (MSFT internal only)](https://microsoft-my.sharepoint.com/:p:/p/jaschrep/ETrL0hTS6nZNl7K5R-gJlbEBPFex_ZRHxPoQN0rWIfwi2Q?e=Lr4nkN)

**Comment by lilyjma** [comment]
scheduled for 4/12 2-4pm pst

**Comment by tg-msft** [comment]
Linking https://github.com/Azure/azure-sdk-for-net/issues/19384 as an option for how we might enable easy global defaults for behavior like `StorageTransferOptions` and `TransferValidation`.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/a2a80840-98dc-997c-52c4-f1ecbab32771) (MS INTERNAL ONLY)
