### ISSUE TITLE
Auto-merge bot

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#407]
With our mono-repo it would be nice to enable a bot that can automatically merge PRs that meet certain requirements.

1) All required pipelines for the code changes are green. Especially in our mono repo's where we cannot use the required CI legs that github has because we nave a CI leg per service.
2) Required CodeOwners have signed off. 
3) Someone in the codeowners list marks the PR as auto-merge when green.

**Comment by kurtzeborn** [comment]
There are lots of options out there for this.  [Example](https://github.com/bobvanderlinden/probot-auto-merge)

**Comment by weshaggard** [comment]
The first part of this might be covered by https://github.com/azure/azure-sdk/issues/499.

**Comment by kurtzeborn** [comment]
@weshaggard I think this is done, right?

**Comment by weshaggard** [comment]
Yes I think we can close this.
