### ISSUE TITLE
Board Review: Introducing Azure Batch

### ISSUE THREAD

**Issue by wiboris** [Azure/azure-sdk#4083]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Azure Batch
* Main contacts: 
  * Dave Watrous (dawatrou)
  * Mike Pateras (mipatera)
  * Bill Boris (wiboris)
  * Seth Barshay (sethbarshay) 
  * Nicolas Koudsieh(nikoudsi)
  * Rob Futrick (rofutric)
* Expected stable release date for this library: Q3 CY 22

## About the Service 

* Link to documentation introducing/describing the service:
  * [Batch Overview](https://docs.microsoft.com/en-us/azure/batch/batch-technical-overview)
* Link to the service REST APIs: 
  * [Data Plane](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/batch/data-plane/Microsoft.Batch/stable/2022-01-01.15.0/BatchService.json)
  * [Management plane](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/batch/resource-manager/Microsoft.Batch/stable/2022-01-01/BatchManagement.json)
* Is the goal to release a Public Preview, Private Preview, or GA? 
  * Public Preview

## About the client library

* Name of client library: Azure Batch
* Link to library reference documentation:
  * https://docs.microsoft.com/dotnet/api/overview/azure/batch/client?view=azure-dotnet
  * https://docs.microsoft.com/en-us/rest/api/batchservice/
* Is there an existing SDK library? If yes, provide link: 
  * [C#](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/batch)
  * [Java](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/batch)
  * [Python](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/batch)
  * [JS](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/batch)
  * [CLI](https://github.com/Azure/azure-cli/tree/dev/src/azure-cli/azure/cli/command_modules/batch)
  * [Powershell](https://github.com/Azure/azure-powershell/tree/main/src/Batch)

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
4. How does the **authentication** workflow look? 
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

**Champion Scenario 1: Batch Account creation and operations**

Customer creates a batch account and sets up a storage account and application to be used for running tasks.

- Create a batch account.
- Get batch security keys.
- Setup a storage account.
- Assign storage to batch account.
- Add an application to the batch account.
- Checks quota on Batch account.
- List all batch accounts.

C# sample: TBD
Python sample: (Track2) https://github.com/wiboris/BatchChampionScenarios/blob/main/ScenarioA/createbatchaccount.py 

**Champion Scenario 2:  Create tasks using blob as input and output**

Customer creates tasks that utilize blob input files and writes results to the blob when finished.

- Connect to an existing batch account.
- Create a storage account with test input files.
- Link storage account to batch account.
- Create a pool.
- Create a job.
- Create a task using blob test files as inputs and write results to blob as output.
- Monitor task.
- View output from blob.
- Cleanup by deleting tasks, job, and pool.

C# sample: TBD
Python sample: https://github.com/Azure-Samples/azure-batch-samples/blob/master/Python/Batch/sample2_pools_and_resourcefiles.py 

**Champion Scenario 2:   Execute tasks with batch pool setup with autoscale**

Customer creates a pool with an autoscale formula and as they add tasks the pool grows and shrinks as needed.

- Connect to an existing batch account.
- Create a pool 0 nodes initally with autoscale rules.
- Create a job.
- Create a number of tasks.
- Monitor tasks running.
- Verify pool grows.
- verify results.
- Cleanup.

C# sample: https://gist.github.com/paterasMSFT/c2e0173a04745fb94b3c19b9d8734b00 ([SDK test branch](https://github.com/Azure/azure-sdk-for-net/tree/mipatera-newt2/sdk/batch/Azure.Data.Batch))
Python sample: (Track1) https://github.com/wiboris/BatchChampionScenarios/blob/main/ScenarioC/batchautoscalepool.py 
Python sample: (Track2) https://github.com/wiboris/BatchChampionScenarios/blob/main/ScenarioCtrack2/batchautoscalepool.py 

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 

* Create a new resource
* Read the resource
* Modify the resource
* Delete the resource
* Error handling 
* Handling race conditions/concurrency issues

**Comment by lilyjma** [comment]
scheduled for 4/18 2-4pm pst

**Comment by tg-msft** [comment]
The sample links all 404 for me?

I created ApiView listings for Track 1's .NET libraries to get an idea of the scope:
- [Microsoft.Azure.Batch](https://apiview.dev/Assemblies/Review/039c868f2cb24109a8e4793099d0c575)
- [Microsoft.Azure.Batch.FileStaging](https://apiview.dev/Assemblies/Review/7cae2390a929411f996236f7e4d8b269)
- [Microsoft.Azure.Batch.Conventions.Files](https://apiview.dev/Assemblies/Review/e0956862086d44978bce547609894d98)

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/0dc00840-98dc-997f-74fc-f1ecbf6cc7e7) (MS INTERNAL ONLY)
