### ISSUE TITLE
Ensure email is sent for all build breaks

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#41]
We need to ensure email is sent for all build breaks.  Ideally to the eng sys team, plus commits since last successful build.

**Comment by danieljurek** [comment]
@mikeharder and @mitchdenny and I chatted about this today and came up with high level points. The spirit of this work item is to ensure that everyone has appropriate visibility into relevant test failures. 

A few notes: 

* We operate in a manner that is sufficiently like a service so we should consider using infrastructure we have today to alert for service outages as opposed to using emails/teams alerts
* Build and test failures should be routed to the relevant language teams for investigation (as opposed to service teams) 
* Use thresholds to engage EngSys teams
  * A single PR build failure should not trigger an investigation by EngSys, however many CI build failures happening in close succession should be investigated
* Live tests
  * Failures on live tests could mean potential service problems so teams should engage whenever there are problems
  * We may get better response from partner teams if we time the live tests differently from today's configuration

**Comment by danieljurek** [comment]
After some further discussion with @weshaggard we are scoping this work item to: 
* Notify on scheduled builds that have failed (https://github.com/azure/azure-sdk-tools/issues/50)
  * Use existing email notification system in DevOps
* Synchronize ownership information from CODEOWNERS files (https://github.com/Azure/azure-sdk-tools/issues/52)

Closing this as I've opened bugs to track these.
