### ISSUE TITLE
Board Review: package name for management-plane SDK of Microsoft.App

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk#4118]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

### Goal

Decision on package name.

Service requests package name as "app", while Java team feel the name being too generic. The resulted Java package will be named `azure-resourcemanager-app`. Similar for other languages, e.g. `armapp` for Go, `azure-mgmt-app` for Python, `arm-app` for JS.

We might not need an online section. Maybe a vote from each architect on preferred package name would resolve this. And we take the majority vote.

## Contacts and Timeline

* Responsible service team: Microsoft.App
* Main contacts: @weidongxu-microsoft @ruslany
* Expected code complete date:
* Expected release date:

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/azure/container-apps/
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/app/resource-manager
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: this is the target of this review. `armapp`, `azure-mgmt-app` , `arm-app`, `azure-resouremanager-app`
* Languages for this review: Go, Python, JS, Java

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

SDK is not released due to question on package name.
Preview of SDK code can be found at sdkautomation https://github.com/Azure/azure-rest-api-specs/pull/18494#issuecomment-1084095671

### .NET

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/4ce34e7ea2b34245a6866ce78c299ce7
* Link to Champion Scenarios/Quickstart samples:
* PR https://github.com/Azure/azure-sdk-for-java/pull/27900

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by weidongxu-microsoft** [comment]
@ruslany would you provide more info on service, if available?

**Comment by ruslany** [comment]
@weidongxu-microsoft  - here is the description of the sevice:

Azure Container Apps enables you to run microservices, containerized applications and functions on a serverless platform. Azure Container Apps enables executing application code packaged in any container and is unopinionated about runtime or programming model. With Container Apps, you enjoy the benefits of running containers while leaving behind the concerns of managing cloud infrastructure and complex container orchestrators.

**Comment by ruslany** [comment]
@weidongxu-microsoft , @lilyjma , @kyle-patterson -alternative names we are OK with are:

`armcontainerapp`, `azure-mgmt-containerapp` , `arm-containerapp`, `azure-resouremanager-contaienerapp`.

Please let us know if this naming convention is preferrable from the SDK point of view.

**Comment by ruslany** [comment]
We discussed this more within the team and we still prefer to keep the names as "app". This is because it is consistent with the namespace name and because in future we will be adding new resource types to this namespace, such as "functionapp". So naming the package as "containerapp" will cause more confusion

**Comment by lilyjma** [comment]
scheduled for 4/25 4-6pm pst

**Comment by m-nash** [comment]
@ArthurMa1978 add the other mgmt plane package names here that we will need to discuss.

I know of `Dashboard` and `HybridConnectivity` are there any others?

**Comment by ArthurMa1978** [comment]
Here we have 3 new RPs:
- [x] Dashboard -> Grafana
- [ ] HybridConnectivity
- [ ] DesktopVirtualization

**Comment by johanste** [comment]
> We discussed this more within the team and we still prefer to keep the names as "app". This is because it is consistent with the namespace name and because in future we will be adding new resource types to this namespace, such as "functionapp". So naming the package as "containerapp" will cause more confusion

This is what we say publicly about containers (today): https://azure.microsoft.com/en-us/product-categories/containers/. We used to also have azure container services. For  also have azure app service and azure functions. Is the functionapp related to the services? My concern is potential for customer confusion here....

**Comment by weidongxu-microsoft** [comment]
Above page

- Azure Kubernetes Service (AKS)
- Azure Red Hat OpenShift
containerservice

- Azure Container Apps
this one

- Azure Functions
- Web App for Containers
appservice

- Azure Container Instances
containerinstance

- Azure Service Fabric
servicefabric

- Azure Container Registry
containerregistry

**Comment by weidongxu-microsoft** [comment]
related info
list of released management-plane SDKs
java https://azure.github.io/azure-sdk/releases/latest/mgmt/java.html
python https://azure.github.io/azure-sdk/releases/latest/mgmt/python.html
.net https://azure.github.io/azure-sdk/releases/latest/mgmt/dotnet.html
javascript https://azure.github.io/azure-sdk/releases/latest/mgmt/js.html

**Comment by weidongxu-microsoft** [comment]
One suggestion from Ted

```
Azure.Compute.Kubernetes for AKS

Azure.Compute.Containers for ACI

Azure.Compute.VirtualMachines for Classic

Azure.Applications.Functions for Functions

Azure.Applications.Hosted for classic AppService

Azure.Applications.Containers for this service?
```

**Comment by weidongxu-microsoft** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/53292327/164119606-d4b2f078-d6bb-46dd-b3e5-07f9dd8122a1.png)

From Tomer

**Comment by ruslany** [comment]
@weidongxu-microsoft - after reviewing the recommendations with the team we are ok with the proposed name "Application.Containers". Please confirm the naming of the packages for different languages:

Go: `armapplicationcontainers`, 
Phython: `azure-mgmt-applicationcontainers`,
JS:  `arm-applicationcontainers`,
Java: `azure-resouremanager-applicationcontainers`, 
DotNet: `Azure.ResourceManager.Application.Containers`

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/5bae0840-98dc-997d-b114-f1ecc0d5a076) (MS INTERNAL ONLY)

**Comment by weidongxu-microsoft** [comment]
> @weidongxu-microsoft - after reviewing the recommendations with the team we are ok with the proposed name "Application.Containers". Please confirm the naming of the packages for different languages:
> 
> Go: `armapplicationcontainers`, Phython: `azure-mgmt-applicationcontainers`, JS: `arm-applicationcontainers`, Java: `azure-resouremanager-applicationcontainers`, DotNet: `Azure.ResourceManager.Application.Containers`

Loop in arch for confirmation.
@KrzysztofCwalina @tg-msft for .NET
@JonathanGiles @srnagar for Java
@johanste for Python
@bterlson for JS
Do we have anybody on Golang?

**Comment by weidongxu-microsoft** [comment]
Peronally I am fine with it.

Given we had appservice for webapp+function, and appplatform for spring cloud (with .NET as well), I am also good with say appcontainers.

**Comment by ruslany** [comment]
@weidongxu-microsoft - we still prefer the applicationcontainers name. 

If there are no other feedback - how do we proceed to generate the packages with the new names?

Should I update these files to reflect the new package names?

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/app/resource-manager/readme.csharp.md
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/app/resource-manager/readme.python.md
etc.

**Comment by RickWinter** [comment]
@JeffreyRichter Can you review the proposed Go package name:
    Go: armapplicationcontainers,

**Comment by JeffreyRichter** [comment]
We will use "armappcontainers"

**Comment by ruslany** [comment]
@JeffreyRichter - if that is preferred then we can use the same name scheme for all other packages:

Go: `armappcontainers`, Phython: `azure-mgmt-appcontainers`, JS: `arm-appcontainers`, Java: `azure-resouremanager-appcontainers`, DotNet: `Azure.ResourceManager.App.Containers`

**Comment by JeffreyRichter** [comment]
Each language architect must decide what's write for them.
Go and its ecosystem favor brevity, so app is better than application.
But other languages (like C#) favor verbosity.

**Comment by weidongxu-microsoft** [comment]
Confirmed that Java uses `appcontainers`

**Comment by RickWinter** [comment]
@ArthurMa1978 Is there a process in place that prevents releasing a v1 new package w/o the name approved by Architect?
