### ISSUE TITLE
Change Request: Add event guidelines for mobile (iOS/Android)

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk#4127]
Service teams routinely have implementation and design questions around supporting events in mobile. We should provide guidelines for these service teams, including unicast and multicast events.

cc/ @vcolin7, @JonathanGiles, @mpodwysocki

**Comment by tjprescott** [comment]
This is done for iOS.

**Comment by vcolin7** [comment]
I will pick this up for Android next week.
