### ISSUE TITLE
Board Review: azure-ml

### ISSUE THREAD

**Issue by luigiw** [Azure/azure-sdk#4129]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: AzureML SDK team (azuremlsdk@)
* Main contacts: Hanchi Wang (hancwang@)
* Expected code complete date: 4/30/2022
* Expected release date: 5/16/2022

## About the Service 

* Link to documentation introducing/describing the service: https://azure.microsoft.com/en-us/services/machine-learning/
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/pull/17990
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/2172

## About the client library

* Name of the client library: azure-ml
* Languages for this review: Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/5680565ca16b4c65806e9088d28631ff
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azureml-samples-dotnet/blob/main/Program.cs

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/efa30a57a7a94e48825235108e62aec7
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azureml-examples/tree/april-sdk-preview/sdk
  
### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 4/20 4-6pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/5bae0840-98dc-997d-7371-f1ecc110a292) (MS INTERNAL ONLY)
