### ISSUE TITLE
Board Review: Review DPG grow up experiment with Metrics Advisor in Java

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk#4145]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Main contacts: @haolingdong-msft @weidongxu-microsoft @srnagar 
* Expected stable release date for this library: N/A

## About the client library

* Name of client library: Metrics Advisor DPG experiment
* Is there an existing SDK library? If yes, provide link: https://mvnrepository.com/artifact/com.azure/azure-ai-metricsadvisor

## Step 1: Champion Scenarios 

We'll review the APIs of DPG for Metrics Advisor and then discuss the process for growing up the DPG clients to add convenience APIs.  

https://gist.github.com/srnagar/4bc39072f7e262a0c1ae8d296fd4e0bc

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/a77f0840-98dc-b654-974d-f1ecd647e6c0) (MS INTERNAL ONLY)
