### ISSUE TITLE
Board Review: Azure Cognitive Search

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk#4147]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Cognitive Search
* Main contacts: @Mohit-Chakraborty, @alzimmermsft, @sarangan12, @kashifkhan
* Expected code complete date: 05/30/22
* Expected release date: 06/07/22

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/dotnet/api/overview/azure/search.documents-readme
* Link to the service REST APIs: 
  * https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/search/data-plane/Azure.Search/preview/2021-04-30-Preview/searchservice.json
  * https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/search/data-plane/Azure.Search/preview/2021-04-30-Preview/searchindex.json
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Azure Search Documents
* Languages for this review: .NET, Java, TS, Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/f291bdd4488149748454e2e2fa18a821?diffRevisionId=14237a8da91945f687e75413173fd33a&doc=False&diffOnly=False&revisionId=fc56eab346e44539863d39bfca19e8bd
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/db9254e6049441328ddd5e663ceac257?diffRevisionId=4d5f86548d30485e8f1304d3e891b765&doc=False&diffOnly=False&revisionId=b06c323cdf65442ebbd08091df36b134
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/alzimmermsft/0d2b3fb2e4021f41f6c5b305d529bc27

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/ef46bf352f2148c9b3958c3f0b283e0e?diffRevisionId=612ca526379f4faca8e50fa2078edd17&doc=False&diffOnly=False&revisionId=82b6e1dcef54446f98940cdca9db1cd4
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/kashifkhan/b15f715d8feca0f5df5840c1a3e436a9
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/3d5cf36cf6474963b62850383b1829e3?diffRevisionId=043ebc81899e416f89048cf48848e58b&doc=False&diffOnly=False&revisionId=e1b61852a3584ed588f33558fbe68793
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 5/5 2-4pm pst
