### ISSUE TITLE
Board Review: Python DPG client libraries

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk#4153]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team:
* Main contacts: @lmazuel @johanste @iscai-msft @msyyc @changlong-liu 
* Review Date Requirements: Can we meet earliest second week of May? We also need for the meeting to be 4-6 pm to accommodate our developers in China

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: 
* Languages for this review:

## Step 1: Champion Scenarios 

We are mainly going to be reviewing the generated code. We will also be reviewing the grow up story, with a specific example of Metrics Advisor. The issue will be updated with more specific scenarios closer to the release date.

MA apiview diff: https://apiview.dev/Assemblies/Review/b2a28f24a65a4cc282c0568d8dabbd5b?revisionId=273e715f9dab47479d3dbe8e6472584d&diffRevisionId=73b97bf2b7b8488d87f67dc848b2128b&doc=False&diffOnly=False

Archboard HERO scenarios: https://gist.github.com/iscai-msft/47fe6ecbdd06013bb19a2e16f85a0b43

**Comment by lilyjma** [comment]
scheduled for 5/16 4-6pm PST

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/7d7f0840-98dc-b654-a553-f1ecd57ad2e6) (MS INTERNAL ONLY)
