### ISSUE TITLE
Board Review: Azure Container Registry

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk#4161]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Container Registry
* Main contacts: @Mohit-Chakraborty, @pallavit, @timovv, @YalinLi0312
* Expected code complete date: 04/29/22
* Expected release date: 05/03/22

## About the Service 

* Link to documentation introducing/describing the service: https://azure.microsoft.com/en-us/services/container-registry/
* Link to the service REST APIs: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/containerregistry/data-plane/Azure.ContainerRegistry/preview/2019-08-15-preview/containerregistry.json
* Link to GitHub issue for previous review sessions, if applicable: 

## About the client library

* Name of the client library: Azure Containers Container Registry
* Languages for this review: .NET, Java, TS, Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/7ebfcb36ff6149ba96170bd059094513?diffRevisionId=500d32ab2730498084dedadf61d740fc&doc=False&diffOnly=False&revisionId=c062a4ee001f412d81c8eef6a39c16f1
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/7bfe65a4d43a44df831aac7f64d37fca?diffRevisionId=0b7bc3c21f874ce0917a9b128885e658&doc=False&diffOnly=False&revisionId=ab10aba8112c41b1ab2cc66875437e39
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/e77720207ba7448e84cb77859392731d?diffRevisionId=3e2025a817b74f259e1a4774481c43e3&doc=False&diffOnly=False&revisionId=33d60e95c26a4ddab7f7d49ea2d72548
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/c03beeb9ca874c4c9e821bc954dc2055?diffRevisionId=9ccb1c8fa77948d7a6604c69bf2dbcae&doc=False&diffOnly=False&revisionId=dc39a91316ef4c02a72b0b239dfde819
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 4/26 2-4pm pst
