### ISSUE TITLE
Board Review: JavaScript/Typescript Rest Client Libraries

### ISSUE THREAD

**Issue by joheredi** [Azure/azure-sdk#4163]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team:
* Main contacts: @bterlson, @qiaozha, @MaryGao, @joheredi
* Review Date Requirements: Sometime after April 25th. Also, we'd like it to be between 4 and 6 pm to accommodate our team members in China. 

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library:
* Languages for this review:

[Presentation + Scenarios](https://gist.github.com/joheredi/cf919a9f4b344e1fc7074d0ca85aea69)
ApiView: [Farmbeats](https://apiview.dev/Assemblies/Review/945e7ca65f3c44b4b24e0fac024d9b8b), [Synapse Artifacts - Shortcuts](https://apiview.dev/Assemblies/Review/15b394e62e014759938cfd3171f61b92)

## Step 1: Champion Scenarios

The review will be focused on reviewing development experience in the IDE (VsCode) for the champion scenarios. We can spend some time towards the end of the meeting reviewing API View for the paging and LRO helper functions.

#### Developer Experience
- Calling a simple **get** operation
- Calling an operation that needs crafting a request (**PUT/POST**). It may contain a body, headers, query parameters
- Working with the response
- Multiple content type
- LRO
- Paging
- Working with FormData
- Working with Streams (request & response)
- Error handling
- Shortcut methods ( client.path(“/foo”).get() => client.getFoo())
- 
#### Customization
- Custom Authentication
- Helper function for common tasks
- Helper function for data transforms
- How to achieve multi-client packages

**Comment by lilyjma** [comment]
scheduled for 5/16 4-6pm pst

**Comment by joheredi** [comment]
Here is the presentation with hero scenarios [Hero scenarios](https://gist.github.com/joheredi/cf919a9f4b344e1fc7074d0ca85aea69)

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/53ae0840-98dc-b654-7280-f1eccffc2167) (MS INTERNAL ONLY)
