### ISSUE TITLE
Migrate powershell scripts from AzureRM to AzureAz

### ISSUE THREAD

**Issue by raviumishra** [Azure/azure-sdk#4177]
New-AzUpgradeModulePlan -FromAzureRmVersion '6.13.1' -ToAzVersion '6.1.0' -DirectoryPath "dir" -OutVariable Plan
**Errors:** https://github.com/raviumishra/migration-errors/blob/main/error.txt

**Comment by weshaggard** [comment]
@raviumishra I don't think this is the correct repo for this issue. You might try https://github.com/azure/azure-powershell.
