### ISSUE TITLE
Board Review: Azure Maps SDK

### ISSUE THREAD

**Issue by daniel-rocha** [Azure/azure-sdk#4186]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Maps
* Main contacts: daroch@, alan.yang@
* Expected code complete date: May/2022
* Expected release date: June/2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/azure-maps/
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/maps/data-plane
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/3672

**Note**: due to the many adjustments the Swagger files had to go through, our development schedule is late. We would like therefore to speed things up by doing many APIs at once, with the objective of previewing the SDKs with customers as soon as possible. If possible, we would like to schedule a 2 hour meeting with the objective of signing-off on the Search SDK, and doing a thorough review of Route and Render, potentially signing off on both, since they follow the same guidelines. We are very pressed for time and would like to have as much help as possible. 

The .NET SDKs will be reviewed separately - we have a shortage of development time now for it.

## About the client library

* Name of the client library: Azure Maps SDK - Search, Route, Render modules.
* Languages for this review: Java, Python, TypeScript

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

Not to be reviewed this time.

### Java

Search - https://apiview.dev/Assemblies/Review/7126eaeacfe3458da0692fa889d49b40
Route - https://apiview.dev/Assemblies/Review/251e3859259341b29cd7913cbfcb4a29
Render - https://apiview.dev/Assemblies/Review/c37782e6bdd94f71849bae52e7150b92

### Python

Search: [azure-maps-search - azure-maps-search-sdk - apiview.dev] (https://apiview.dev/Assemblies/Review/0ab748be5297432eaf27d512e2d1b998)
Route: [azure-maps-route - azure-maps-route-sdk - apiview.dev](https://apiview.dev/Assemblies/Review/e6fab45424f74dc89b6064001b034713)
Render: [azure-maps-render - azure-maps-render-sdk - apiview.dev](https://apiview.dev/Assemblies/Review/24323deba0df4a188dd7673f3b697e9e)

Fork: [alextts627/azure-sdk-for-python at onboard-maps-search (github.com)](https://github.com/alextts627/azure-sdk-for-python/tree/onboard-maps-search)
  
### TypeScript

Search: [@azure/maps-search - apiview.dev](https://apiview.dev/Assemblies/Review/737c63ff29ea4eb8ad335ddabb4c382f)
Route: [@azure/maps-route - apiview.dev](https://apiview.dev/Assemblies/Review/5e82a4ccfd8e4005a3e6efc53939cfde)
Render: [@azure/maps-render - apiview.dev](https://apiview.dev/Assemblies/Review/4bb0f0200cd44cec9cc40d371ae22df5)
Common: [@azure/maps-common - apiview.dev](https://apiview.dev/Assemblies/Review/e795d46ded314b59841624782046a18a)
Fork: [alankashiwa/azure-sdk-for-js at onboard-maps-search (github.com)](https://github.com/alankashiwa/azure-sdk-for-js/tree/onboard-maps-search)

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by lilyjma** [comment]
scheduled for 5/3 4-6pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/63b40840-98dc-b654-5a6f-f1eccb467be0) (MS INTERNAL ONLY)
