### ISSUE TITLE
Github.IO site doesn't remember or highlight the current selection in the navigation sidebar

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#4188]
If I select a particular section in the navigation bar it doesn't highlight and, in some cases, even collapses the section. 

Examples:
https://azure.github.io/azure-sdk/general_terminology.html
![image](https://user-images.githubusercontent.com/9010698/162798359-9eaa6f84-46b7-4be7-8a8a-2a2246aa899e.png)

I would expect that terminology would be selected in the navigation pane. 

https://azure.github.io/azure-sdk/releases/2022-01/index.html
When I select January 2022 not only does it not highly that subsection it collapses the 2022 releases section as well so you just see:
![image](https://user-images.githubusercontent.com/9010698/162798638-d980f9ad-a01e-4d0c-a43a-cdf607c0fe76.png)

**Comment by vhvb1989** [comment]
The `table of contents` from the right can also highlight an item from the list reacting to the screen scrolling.
For example, for this page: https://azure.github.io/azure-sdk/general_implementation.html, as the use scroll down, the right menu can change and highlight the tittle that user is looking at.

See this page as example: https://www.algolia.com/doc/guides/getting-started/what-is-algolia/#search-as-a-feedback-loop

Note how the floating table of contents from the right changes depending on the content position
https://www.algolia.com/doc/guides/getting-started/what-is-algolia/#search-as-a-feedback-loop
