### ISSUE TITLE
Separate build and test steps in pipeline definitions

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#42]
Currently, our pipelines do the following:

1. In parallel, build and run tests on all OS and language versions, using the same language version to both build and run tests.
2. If all tests pass, create and publish packages.

Instead, we would prefer the following:

1. Using a single language version (and single OS if possible), build both product and test binaries.
2. If build succeeds, copy product and test binaries to an intermediate location.
3. In parallel, using the pre-built product and test binaries, run tests on all OS and language versions.

A few goals of the new system:

* Publish binaries even if tests fail, since they may be useful for dogfooding, unblocking development, etc.
* Build and run using different language versions.  In many languages, this allows using the latest language features in source code while creating packages which can be used from older versions.
* If build step fails, avoid consuming parallel agents for tests which are known to fail.

## Repos
- [ ] dotnet
- [ ] java
- [ ] python
- [ ] js

**Comment by kurtzeborn** [comment]
We've already implemented most of this and the rest is being tracked by separate issues.
