### ISSUE TITLE
Design Guidelines: Obsolete attribute

### ISSUE THREAD

**Issue by jfggdl** [Azure/azure-sdk#420]
Please consider adding guidelines on marking a class member or method obsolete with a resulting warning or error to the user. Please also add guidelines as to the time in which the obsolete property or class member will be removed. This timeline guideline may be included in a platform-agnostic process/guidelines document in addition to the platform/language-specific guidelines documents that contain the idiosyncratic obsolete/deprecation approach for each language.

For .Net you may want to refer to: 
https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute?redirectedfrom=MSDN&view=netframework-4.8

For Java you may want to refer to: 
https://docs.oracle.com/javase/7/docs/technotes/guides/javadoc/deprecation/deprecation.html

**Comment by adrianhall** [comment]
We already have the requirement of "no breaking changes" within the guidelines.  There are no explicit guidelines on application of obsolete attributes, but they aren't banned either.
