### ISSUE TITLE
Board Review: Python/.NET azure-ai-translation-document

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk#4201]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Translator
* Main contacts: @mayurid @kristapratico @maririos 
* Expected code complete date: TBD
* Expected release date: ~End of May for stable versions of the Python/.NET libraries

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/cognitive-services/translator/document-translation/overview
* Link to the service REST APIs: https://docs.microsoft.com/en-us/azure/cognitive-services/translator/document-translation/reference/rest-api-guide
* Link to GitHub issue for previous review sessions, if applicable:  
Intro to service: https://github.com/Azure/azure-sdk/issues/1968
Board review: https://github.com/Azure/azure-sdk/issues/2448

 

## About the client library

* Name of the client library: azure-ai-translation-document
* Languages for this review: Python, .NET

### Context

- The work for this library started around March 2021. The latest major design change happened in September 2021 (renames) after architect’s feedback.
- After September, the changes to the libraries have been updated according to new patterns in both Azure Core and language-specific scenarios.
- At this point, design and property names are locked down unless there is a strong argument for the changes
- Usage of the libraries (# of unique resource IDs calling the client libraries in the last year minus SDK internal subs):
  
  <html xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
  xmlns="http://www.w3.org/TR/REC-html40">
  
  <head>
  
  <meta name=ProgId content=OneNote.File>
  <meta name=Generator content="Microsoft OneNote 15">
  </head>
  
  <body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
  
  
  <div style='direction:ltr'>
  
  
  
  UserAgent | unique_count_AzureResourceId
  -- | --
  PostmanRuntime | 410
  python-requests | 388
  azsdk-net-AI.Translation.Document | 323
  azsdk-python-ai-translation-document | 168
  azure-logic-apps | 93
  Mozilla | 86
  axios | 67
  okhttp | 32
  insomnia | 12
  Thunder   Client (https: | 12
  GuzzleHttp | 9
  vscode-restclient | 9
  
  
  
  </div>
  
  
  </body>
  
  </html>

### Document Translation service

- Link to service intro (Oct 2020): https://github.com/Azure/azure-sdk/issues/1968
- Translator service encompasses **Document Translation**, Text Translation, Custom Translation.
- "The Document Translation API can be used to translate multiple and complex documents across all supported languages and dialects, while preserving original document structure and data format."

The champion scenario for the DT service is to translate the documents in a source container to its corresponding target container in the given language. A source container contains one or more documents and a target container must be supplied per unique language translation.

![image](https://user-images.githubusercontent.com/31998003/170155256-b261af5e-489e-4683-ac86-f9cebf169bc8.png)

Both Python and .NET have specific overloads to optimize for the scenario in (1) and (2, 3). These methods kick off long-running operations which, upon completion, return a pageable of document status result objects for the user to check on the result of each translation and/or use the URL to access the translated document in blob storage.

The client libraries also offer APIs to check on the status of translation operations (including history of past operations), check on status per document, or the ability to cancel the operation. 

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/46373cdd5bff4c86aeef03d3b8f79d50
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/translation/Azure.AI.Translation.Document/samples

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/3fe2d18bbf02471eae4fd292c0d5f36e
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/translation/azure-ai-translation-document/samples

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/9ec90840-98dc-b478-17f9-f1ecdd120f70) (MS INTERNAL ONLY)

**Comment by maririos** [comment]
Notes:
What is the DPG story for the other languages (Java and JS)? When will they GA? Is there an exception for these 2?

Status:
Python: Approved
.NET:
- Confirm namespace selection with @KrzysztofCwalina 
-  https://github.com/Azure/azure-sdk-for-net/issues/28995
