### ISSUE TITLE
Retry Policy implementation

### ISSUE THREAD

**Issue by jfggdl** [Azure/azure-sdk#421]
Regarding Event Hubs' EventHubsClient, its constructor takes EventHubsClientOptions where user can specify, among other things retry options. I saw the implementation of Retry. Two comments:
a.	Can we rename the Retry class to RetryPolicy (I think that is the name we use now). It is not because we use that name now. Retry is too generic. 
b.	The pattern usually calls for defining an interface, then if required, an abstract class with a partial implementation. In the current implementation we just have an abstract class, which is good. Please consider extracting out an interface for opening more implementation possibilities to users.

**Comment by adrianhall** [comment]
I'm reading this as a .NET issue right now - if it isn't a .NET issue, can you please clarify the issue?

**Comment by ramya-rao-a** [comment]
I believe this applies to Java as well
cc @jsquire and @conniey

**Comment by jsquire** [comment]
Closing;  this issue refers to a type that no longer exists in the SDK and options that have already been released to GA where members cannot be renamed without breaking changes.
