### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) DiagnosticsOptions (iOS & Android)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4233]
## Contacts and Timeline
* Responsible service team: Azure Communication Services (SPOOL) Calling Native SDK Team
* Main contacts: gaobob@microsoft.com; xumo1@microsoft.com
* Expected code complete date: 5/13/2022
* Expected release date: 5/20/2022

## About the Service 
* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/communication-services/overview
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library
* Name of the client library: com.azure.android:azure-communication-calling
* Languages for this review: iOS (Objective-C), Android (Java)

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/3b976d629b57481fbfa238e9a033f499?revisionId=19a5c641672c4532a8c0a213f6e62552&diffRevisionId=a152dfb4238141a5b67c664f98b982ac&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples: https://microsoft-my.sharepoint-df.com/:t:/p/xumo1/ERdmHal1c8VMhHYcwW9LdmYBSt0JwZzaYlEHpngT6KkR8A?e=zEiR4j

### Ojective-C

* APIView Link: https://apiview.dev/Assemblies/Review/447d91179dcf4b138086db403f374b41?revisionId=56f50ee63a094ec9bd31c7575ec88a2e&diffRevisionId=4219a59f7d5f4d7ba4cf4e01769a825e&doc=False&diffOnly=False
* Link to Champion Scenarios/Quickstart samples: https://microsoft-my.sharepoint-df.com/:t:/p/xumo1/ERdmHal1c8VMhHYcwW9LdmYBSt0JwZzaYlEHpngT6KkR8A?e=zEiR4j

**Comment by lilyjma** [comment]
scheduled for 5/11 2-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/ad7b0840-98dc-b654-4d53-f1ecd17e88d2) (MS INTERNAL ONLY)
