### ISSUE TITLE
Board Review: .NET DPG Client Libraries

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#4237]
We would like to review the output of the Data Plane Code Generator (DPG) prior to starting to GA DPG Client libraries.

## Contacts and Timeline

* Responsible service team:
* Main contacts: @annelo-msft, @lirenhe, @AlexanderSher, @ShivangiReja, @chunyu3, @pshao25
* Review date requests: Could we meet the third week of May? We also need for the meeting to be 4-6 pm to accommodate our developers in China

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library:
* Languages for this review:

### .NET

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

We will be reviewing the some of the existing DPG library APIs, as well as the grow up story, with a specific example of Metrics Advisor. The issue will be updated with more specific scenarios closer to the release date.

**Comment by lilyjma** [comment]
scheduled for 5/19 4-6pm pst

**Comment by annelo-msft** [comment]
Client-side evolution discussion: https://gist.github.com/annelo-msft/8582310e0aab5c3dfa378de2c11849bb

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/97c90840-98dc-b654-2693-f1ecd85f8e1d) (MS INTERNAL ONLY)
