### ISSUE TITLE
Update Issues for Service Attention PBI Report

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#425]
Add to PowerBI:
Summary by service of 
-	Questions Opened
-	Questions Closed
-	Feature Requests Opened
-	Feature Requests Closed
-	Bugs Opened
-	Bugs Closed
-	Documentation opened
-	Documentation closed
-	Time to assign and time to close for each category

Additional Metric for 6/21:
Time to Service: % of bugs (broken down per service) that have been responded to by the assigned MS person in 72hours.

**Comment by scbedd** [comment]
Work sent for review 6/17

**Comment by scbedd** [comment]
Completed TTS Metric on 6/21. Need to update official PBI report instead of local workspace.

**Comment by maggiepint** [comment]
For now, let's clean up the dashboard to make the 72 hour TTR easy to use. Waiting on further metrics.

**Comment by scbedd** [comment]
Updated. See internal repo `bi-reports` or the `Azure SDK` PBI workspace for 72TTS adjusted to apply.

**Comment by scbedd** [comment]
3 Month view provided. Metrics adjusted for edge cases:

* Updated logic for 72 hour SLA to instead use "3 business day" logic
    * this does not handle holidays currently.
* Instead of looking for only current assigned-to responses, we now look at _all_ people who were ever assigned
* Handling closed issues: if no comment, but closed, we validate SLA against the closed date instead of the non-existent earliest comment time
