### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) Mobile UI Library (iOS)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4251]
Service team responsible for the client library.
ACS- Mobile UI team

Link to documentation describing the service.
[MSDocs](https://docs.microsoft.com/en-us/azure/communication-services/concepts/ui-library/ui-library-overview?pivots=platform-mobile)

[Quickstart](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/ui-library/get-started-composites?tabs=kotlin&pivots=platform-ios)

[GitHub](https://github.com/Azure/communication-ui-library-ios)

Contact email (if service team, provide PM and Dev Lead).

EM: mo.wayne@microsoft.com
PM: jorgegarc@microsoft.com

Name of the client library.
Mobile UI Library

Languages for this review.
Swift

## Theming 

[Theming APIView](https://apiview.dev/Assemblies/Review/4213efb995464aa28bb6d2b69cb02156)

#### Related Information

[FluentUI Button Overview](https://developer.microsoft.com/en-us/fluentui#/controls/ios/button)
[FluentUI Button Code](https://github.com/microsoft/fluentui-apple/blob/main/ios/FluentUI/Button/Button.swift)
[FluentUI ColorProvider Code](https://github.com/microsoft/fluentui-apple/blob/e0d2f34d07d7ccb04d11af9ccc36a6b0db824d2e/ios/FluentUI/Core/Colors.swift)

#### Affected UI

<img width="432" alt="image" src="https://user-images.githubusercontent.com/73612854/169615612-d9e0caea-e453-4337-9369-302948cd6cde.png">

### Champion scenarios

1. Overriding the primary color and associated tints
2. Forcing either dark or light mode

<img width="686" alt="image" src="https://user-images.githubusercontent.com/73612854/169615388-adb90863-1be6-4dc9-a1eb-4f1e5d65655d.png">

#### Define Color Assets

![image](https://user-images.githubusercontent.com/73612854/169615493-98bacc89-4ec5-4aa9-bad0-130f48c75ca4.png)

![image](https://user-images.githubusercontent.com/73612854/169615521-ca824372-6f05-4747-b144-0b67440de486.png)

#### Example

![Simulator Screen Shot - iPhone 13 mini - 2022-05-04 at 15 29 57](https://user-images.githubusercontent.com/73612854/166835905-86fbd938-cc3b-4137-b35b-88900bcb2a49.png)

![IMG_0F046EAF20DB-1 Medium](https://user-images.githubusercontent.com/73612854/170355924-ef3d38df-0d07-44f8-89e5-c874f5a9cfc6.png)

## Image avatar injection 

Champion scenarios Local Avatar Injection:
The UI Library now gives developers the ability to provide a more customized experience. At launch, developers can now inject an optional CallUIOptions. This object can contain a UIImage which represents the avatar to render, and a display name they can optionally display instead. None of this information will be sent to Azure Communication Services and will be only held locally in the UI library.  
Contoso will implement:
```
        let persona = ParticipantViewData(UIImage(named: "cat"), renderDisplayName: "some name")
        let callUIOptions = CallUIOptions(persona)
        let parameters = GroupCallOptions(credential: <SOME TOKEN CREDENTIAL>, groupId: <SOME UUID>,  displayName: getDisplayName())
        callComposite.launch(with: parameters, callUIOptions: callUIOptions)
```
Where DataOptions and persona 
```
public struct CallUIOptions {
    let localPersona: ParticipantViewData

    public init(_ localPersona: ParticipantViewData) {
        self.localPersona = localPersona
    }
}

public struct ParticipantViewData {
    let avatarImage: UIImage?
    let renderDisplayName: String?

    public init(_ avatar: UIImage?,
                renderDisplayName: String? = nil) {
        self.avatarImage = avatar
        self.renderDisplayName = renderDisplayName
    }
}
```

<img width="502" alt="Screen Shot 2022-05-04 at 4 23 10 PM" src="https://user-images.githubusercontent.com/9044372/166840930-5bb8e21d-9d4c-4dd5-8f06-be9ff138a705.png">

Champion scenarios Remote Avatar Injection:
Contoso can subscribe to the new event handler like so:
```
callComposite.setRemoteParticipantJoinHandler(with: didRemoteParticipantsJoin)
let didRemoteParticipantsJoin: ([CommunicationIdentifier]) -> Void = { [weak callComposite] identifiers in
      guard let composite = callComposite else {
                return
      }

      for identifier in identifiers {
            let participantViewData = ParticipantViewData(avatar:<SOME UIIMAGE>, renderDisplayName: <SOME DISPLAY STRING>)
            callComposite.setRemoteParticipantViewData(for: identifier, participantViewData: participantViewData)
      }      
}

```

The new event handler will return Contoso a list of the participants that have just joined the call. 
This participants are returned in a list. Contoso can iterate through the identifiers and set `ParticipantViewData` for each participants individually.

![Screen Shot 2022-05-25 at 1 21 58 PM](https://user-images.githubusercontent.com/9044372/170360618-46300153-b1cc-4ae8-b5b0-83ac5509c1a1.png)

**Comment by kyle-patterson** [comment]
Scheduled for 5/23
