### ISSUE TITLE
Board Review: DPG Preview review for Device Update

### ISSUE THREAD

**Issue by dpokluda** [Azure/azure-sdk#4256]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Device Update for IoT Hub
* Main contacts: David Pokluda (dpokluda)
* Expected code complete date: 6/6
* Expected release date: 7/1 (pre-release); 9/30 (GA)

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/iot-hub-device-update/understand-device-update
* Link to the service REST APIs: specs-pr repo PR - https://github.com/Azure/azure-rest-api-specs-pr/pull/6982
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library:
* Languages for this review: C#, Java, Python, TypeScript

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/693922da0b4a456bb9214567d54b3107
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/tree/f1156c930f189c16dfa3180eb9ddc74a241b826c/sdk/deviceupdate/Azure.IoT.DeviceUpdate/samples
* PR: https://github.com/Azure/azure-sdk-for-net/pull/29157

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/da0da57333ed4ff68f533710ef52cead
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-java/tree/81d06306f9b61925a0fa82ae233446320b308ab3/sdk/deviceupdate/azure-iot-deviceupdate/src/samples
* PR: https://github.com/Azure/azure-sdk-for-java/pull/29288

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/6fddd7d7cde5409b913a96518ba2ca4e
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-python/blob/bc6c31aed643d0c8c71a3d658513099347860c07/sdk/deviceupdate/azure-iot-deviceupdate/samples/
* PR: https://github.com/Azure/azure-sdk-for-python/pull/24752
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/f78eb08291e6437296230eb7a01656a4
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-js/tree/e83faf211ad585286d753674d61a6255a0c5ef19/sdk/deviceupdate/iot-device-update-rest/samples-dev
* PR: https://github.com/Azure/azure-sdk-for-js/pull/22143

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 6/16
