### ISSUE TITLE
Change Request: extract GitHub process from design guidelines

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk#427]
## The Basics

* Which design guideline is affected?

[OpenSource.mdk](https://github.com/Azure/azure-sdk/blob/master/docs/design/general/OpenSource.mdk) in its entirety.

* Which target languages are affected?

All

* Describe the change:

Extract into a separate document and link to it from the various design guidelines.

## Reasoning

GitHub process is a policy thing (and in this case, largely dictated by our corporate and team policies), rather than a design guideline. It should not need to appear specifically in each languages design guide document.

**Comment by adrianhall** [comment]
Makes sense to centralize all policies and processes into a central document.  Extract not only Opensource.mdk - but also the process section and anything else that seems "policy" rather than design.

APPROVED BY THE BOARD

[ ] @adrianhall to integrate this into the general guidelines.

**Comment by adrianhall** [comment]
The open source policy is now in docs/policies/opensource.md and in a separate Policies section on the web site (PR #537 )
