### ISSUE TITLE
Board Review: Authentication Events Trigger Binding for Azure Functions

### ISSUE THREAD

**Issue by ShaneMicro** [Azure/azure-sdk#4270]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: B2C Dublin
* Main contacts: Shane Pennicott (spennicott@microsoft.com)
* Expected code complete date: Completed.
* Expected release date: 31 June 2022

## About the Service 

* Link to documentation introducing/describing the service: https://github.com/Azure/microsoft-azure-webJobs-extensions-authentication-events (Will need required reviewers github accounts to give access)
* Link to the service REST APIs: N/A
* Link to GitHub issue for previous review sessions, if applicable:  N/A

## About the client library

* Name of the client library: Microsoft-azure-webJobs-extensions-authentication-events
* Languages for this review: C#

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/53af8de6e6694fa49f6cb6cc0a0f2c98
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/microsoft-azure-webJobs-extensions-authentication-events/tree/main/samples

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 6/7

**Comment by tg-msft** [comment]
The samples and doc links all 404?  Can you make sure those work or move them somewhere visible?

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/3dc00840-98dc-b478-3397-f1ece68a88c3) (MS INTERNAL ONLY)
