### ISSUE TITLE
Change Request: define "progressive concept disclosure" for all languages

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk#428]
## The Basics

* Which design guideline is affected?

The "Approachable" design principle [here](https://github.com/Azure/azure-sdk/blob/b31d1ae11ab1739344d5ab2991ded7fc3d370776/docs/design/general/DesignPrinciples.mdk#L24)

* Which target languages are affected?

All

* Describe the change:

Add a definition (or a link) for "progressive concept disclosure".

## Reasoning

This is not a standard enough term to simply use it without explaining it. People reading the design guidelines will almost certainly need additional context here.

**Comment by adrianhall** [comment]
Great point - we'll add it to the taxonomy of definitions and link from the design principle

[ ] @adrianhall to add to definition glossary and add link

**Comment by adrianhall** [comment]
Completed and integrated into general guidelines.
