### ISSUE TITLE
Change Request: require source code available for all languages

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk#429]
## The Basics

* Which design guideline is affected?

The "Diagnosable" design principle [here](https://github.com/Azure/azure-sdk/blob/b31d1ae11ab1739344d5ab2991ded7fc3d370776/docs/design/general/DesignPrinciples.mdk#L28)

* Which target languages are affected?

All

* Describe the change:

Add a requirement that source code is made available for diagnostic purposes.

## Reasoning

Given most development will be done on GitHub anyway, this should be trivial. However, given there's still potential for the use of closed-source components (or non-contribution components), we should still try and make the source code available for debugging.

**Comment by rysweet** [comment]
if you mean for SDK only, this makes sense....

**Comment by adrianhall** [comment]
We already say this in Opensource.mdk - requirement #1, so this is not required.

We may need a "how to find the source code for library X.Y.Z" - probably in the README for the client library.  Need to codify within the README section.

[ ] @adrianhall to add "how to find..." to README section.

**Comment by adrianhall** [comment]
source code required is in the open source policy section (see PR #537 )
default README-EXAMPLE and README-TEMPLATE have source code links.
