### ISSUE TITLE
Change Request: Long-Running Operations

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk#4291]
## The Basics

The API Stewardship team will shortly be updating the Azure API Guidelines for long-running operations.

This _should not_ affect the SDK guidelines for LROs but may have some implications on code generation, etc.

In this meeting we'll cover how the API Guidelines will be changing and any impacts we think this may have for SDKs.

## Reasoning

Our current LRO patterns are confusing and unreliable.

**Comment by kyle-patterson** [comment]
Scheduled for 6/9

**Comment by tg-msft** [comment]
Relevant links:
- Proposed Guidelines: https://github.com/microsoft/api-guidelines/pull/353
- Current:
  - Guidelines: https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#long-running-operations--jobs
  - Service Considerations: https://github.com/microsoft/api-guidelines/blob/vNext/azure/ConsiderationsForServiceDesign.md#long-running-operations
- Legacy Guidelines: https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#13-long-running-operations
- LRO flowchart: https://microsoft.sharepoint.com/:u:/t/AzureDeveloperExperience/ERFsgxlpa2tBrRKxceLzB8gB_44VE_Gr-dQdCFwvB2h0GQ
- AutoRest Extensions: https://azure.github.io/autorest/extensions/#x-ms-long-running-operation

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/3dc00840-98dc-b478-67d7-f1ece84af5bf) (MS INTERNAL ONLY)
