### ISSUE TITLE
Change Request: improved language around compatibility for all languages

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk#430]
## The Basics

* Which design guideline is affected?

```
* 99.99% of features and improvements are not worth the time consumers would have to spend reacting to breaking changes.
```

* Which target languages are affected?

All

* Describe the change:

Replace the made up statistic with more of an instruction: "Breaking changes are more harmful to a user's experience than most new features and improvements are beneficial. Incompatibilities should never be introduced deliberately without thorough review and very strong justification."

## Reasoning

The obviously made up statistic is not compelling, and there is no instruction in the statement that can be applied in design discussions.

**Comment by adrianhall** [comment]
Agreed

[ ] @adrianhall will change the wording.

**Comment by adrianhall** [comment]
Completed and integrated into general guidelines.
