### ISSUE TITLE
Board Review: Conversational Language Understanding

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk#4301]
## Contacts and Timeline

* Responsible service team: Cognitive Services
* Main contacts: @heaths @mshaban-msft @kristapratico 
* Expected code complete date: 5/31
* Expected release date: 6/20 or earlier

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/conversational-language-understanding/overview
* Link to the service REST APIs: [Runtime](https://docs.microsoft.com/en-us/rest/api/language/conversation-analysis-runtime) | [Authoring](https://docs.microsoft.com/en-us/rest/api/language/conversational-analysis-authoring)
* Link to GitHub issue for previous review sessions, if applicable: https://github.com/Azure/azure-sdk/issues/3471

## About the client library

* Name of the client library: Azure.AI.Language.Conversations
* Languages for this review: .NET, Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/20a58d7611e845939ebfd25707b16b88?revisionId=b218fb7529c54356a11d99e7e1daa4f5&doc=False
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/tree/1e898355eb851d7058990ea6c5b2c96582741d82/sdk/cognitivelanguage/Azure.AI.Language.Conversations/samples (from a PR; I'll update if it gets merged before this meeting)

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/1d9daf7a5ab248a2b2b0498a96da4b95
* Link to Champion Scenarios/Quickstart samples: https://github.com/kristapratico/azure-sdk-for-python/tree/regen-clu-archboard/sdk/cognitivelanguage/azure-ai-language-conversations/samples

**Comment by kyle-patterson** [comment]
Scheduled for 6/15

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/168f0840-98dc-b478-9dcc-f1eced0ab2b3) (MS INTERNAL ONLY)
