### ISSUE TITLE
Board Review: BearerTokenChallengePolicy in Core [Python]

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk#4302]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

This review is to discuss the addition of a new auth policy for multi-tenant authentication to azure core for Python (other languages may follow). This policy will be consumed by both Keyvault and Tables with potentially more services in future.

A 1-hour slot should be sufficient.

## Contacts and Timeline

* Responsible service team: Python Core team
* Main contacts: McCoy Patiño, Anna Tisch, Laurent Mazuel
* Expected code complete date: 1st June
* Expected release date: 6th June

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: azure-core
* Languages for this review: Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Python

* APIView Link: [link](https://apiview.dev/Assemblies/Review/eed79bfbff2d471c8b7c2212d907f1db?diffRevisionId=cb12cc51ab794665946d9686078d377c&doc=False&diffOnly=True&revisionId=c5a7b30c7ef64f63885d42b36ef1d04a)
* Link to Champion Scenarios/Quickstart samples:
  - PR to introduce policy to Azure Core: [link](https://github.com/Azure/azure-sdk-for-python/pull/24019)
  - PR of Key Vault adoption prototype: [link](https://github.com/mccoyp/azure-sdk-for-python/pull/1)
  - PR that incorporated Tables-internal implementation of proposed policy: [link](https://github.com/Azure/azure-sdk-for-python/pull/24278)
  - `azure-storage-blob`'s current internal challenge auth policy: [link](https://github.com/Azure/azure-sdk-for-python/blob/d1ab444d9be412b9e93aaeb22b7df1f8a765e360/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies.py#L639)
  

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 6/1

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/53dd0840-98dc-b478-9ce6-f1ece1ff2010) (MS INTERNAL ONLY)
