### ISSUE TITLE
Board Review: Introducing Azure Monitor logs collection

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk#4304]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library:  Evgeny Ternovsky and Raji Ramesh
* Main contacts: @rakshith91 @KarishmaGhiya @nisha-bhatia @srnagar 
* Expected stable release date for this library: September 2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/azure-monitor/logs/custom-logs-overview
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/monitor/data-plane/ingestion/preview/2021-11-01-preview
* Is the goal to release a Public Preview, Private Preview, or GA? This is an introductory review meeting and the goal is to release a public preview to begin with and follow up with a GA release later this year.

## About the client library

* Name of client library: Azure Monitor logs collection
* Is there an existing SDK library? If yes, provide link:  None available

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
4. How does the **authentication** workflow look? 
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

[Champion Scenarios](https://gist.github.com/srnagar/c7432f0a8b0e6715d4b983a0d8aea25a)

[Java API view](https://apiview.dev/Assemblies/Review/d736610ac7294beaac72a862ddd5edf6)
[JS API view](https://apiview.dev/Assemblies/Review/8025951aa456467f8aeefbbd2c852490)

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/4cd50840-98dc-b478-e0d0-f1ece3781324) (MS INTERNAL ONLY)
