### ISSUE TITLE
Change Request: clarify the audience for Process section for all languages

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk#431]
## The Basics

* Which design guideline is affected?

The [Process section](https://github.com/Azure/azure-sdk/blob/master/docs/design/general/Process.mdk)

* Which target languages are affected?

All

* Describe the change:

Clarify the target audience. Right now it is the only section in the document that seems to be for _service_ teams rather than _SDK_ teams, which would suggest that it either needs to be reframed or moved to another document.

**Comment by rysweet** [comment]
move to a separate doc, similar to oss

**Comment by adrianhall** [comment]
Useful clarification - although it's for "whoever is writing the client library"

[ ] @adrianhall to adjust accordingly, including separate out into a policies section.

**Comment by adrianhall** [comment]
This has now been moved to the "ReviewProcess" document within the policies section.  No longer in the guidelines (at least from Monday onwards when PR #537 is merged).
