### ISSUE TITLE
Board Review: AzureCommunicationChat IOS SDK

### ISSUE THREAD

**Issue by angellan-msft** [Azure/azure-sdk#4316]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Communication Service - Chat Team
* Main contacts: Angel Lan (angellan@microsoft.com)
* Expected code complete date: 5/13/2022
* Expected release date: 5/29/2022

## About the Service 

* Link to documentation introducing/describing the service: 
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: AzureCommunicationChat
* Languages for this review: Swift (IOS)

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by angellan-msft** [comment]
Please find the APIView for Swift -
https://apiview.dev/Assemblies/Revisions/993b3da970c24d24a05f035d674b7525

**Comment by angellan-msft** [comment]
[ArchBoard Review Materials - ACS Chat SDK IOS.docx](https://github.com/Azure/azure-sdk/files/8694126/ArchBoard.Review.Materials.-.ACS.Chat.SDK.IOS.docx)

Attached please find the Feature Summary which can be a reference to ArchBoard's review.

**Comment by angellan-msft** [comment]
[ArchBoard Review Materials - ACS Chat SDK IOS.docx](https://github.com/Azure/azure-sdk/files/8703540/ArchBoard.Review.Materials.-.ACS.Chat.SDK.IOS.docx)

Attached please find the Feature Summary which can be a reference to ArchBoard's review.

**Comment by angellan-msft** [comment]
[ArchBoard Review Materials - ACS Chat SDK IOS.docx](https://github.com/Azure/azure-sdk/files/8709638/ArchBoard.Review.Materials.-.ACS.Chat.SDK.IOS.docx)

Attached please find the Feature Summary which can be a reference to ArchBoard's review.

**Comment by kyle-patterson** [comment]
Scheduled for 5/25

**Comment by angellan-msft** [comment]
[ArchBoard Review Materials - ACS Chat SDK IOS.docx](https://github.com/Azure/azure-sdk/files/8766348/ArchBoard.Review.Materials.-.ACS.Chat.SDK.IOS.docx)

Attached please find the Feature Summary which can be a reference to ArchBoard's review.

**Comment by angellan-msft** [comment]
[ArchBoard Review Materials - ACS Chat SDK IOS.docx](https://github.com/Azure/azure-sdk/files/8767034/ArchBoard.Review.Materials.-.ACS.Chat.SDK.IOS.docx)
Attached please find the Feature Summary which can be a reference to ArchBoard's review.

**Comment by angellan-msft** [comment]
[ArchBoard Review Materials - ACS Chat SDK IOS.docx](https://github.com/Azure/azure-sdk/files/8767074/ArchBoard.Review.Materials.-.ACS.Chat.SDK.IOS.docx)
Attached please find the Feature Summary which can be a reference to ArchBoard's review.

**Comment by angellan-msft** [comment]
[ArchBoard Review Materials - ACS Chat IOS SDK.docx](https://github.com/Azure/azure-sdk/files/8768887/ArchBoard.Review.Materials.-.ACS.Chat.IOS.SDK.docx)
Attached please find the Feature Summary which can be a reference to ArchBoard's review.

**Comment by angellan-msft** [comment]
Please find the latest APIView -
https://apiview.dev/Assemblies/Revisions/eaa100d11a8a49a59bc77abe4d8731d5

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/68ac0840-98dc-b478-8059-f1ecdc7ffa79) (MS INTERNAL ONLY)
