### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) [Phone Numbers] Operator Connect (JS)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4328]
**Responsible team:** Phone Numbers team

**Contacts:**
vadym.moskalenko@microsoft.com
jiriburant@microsoft.com

**Basic info:**
With the upcoming feature of Operator Connect, it will be possible for a user to purchase numbers not only from Microsoft, but also directly from other operators, but through Azure Portal. For that, UI needs to be able to retrieve information about which operator handles the purchased number.

**Champion scenario:**
-As Portal UI, I need to display information about operator, from whom the number was purchased.

[Presentation](https://microsofteur-my.sharepoint.com/:p:/g/personal/vamoskal_microsoft_com/EaHPaXm8ezFMpVUxFSEfQygBNpNr7BDL2EW-PvoXLygEoQ?e=DlA4JQ&isSPOFile=1)

[Introduction to Operator Connect for Azure Communication Services (OC4ACS) v1.docx](https://microsoft-my.sharepoint-df.com/:w:/p/hranapour/EXx7pc2zpkJFjZvj-BBbuwsBErGRk5hVtHYA-B3--hx-pQ?e=xGzVik&isSPOFile=1)

[Funk Spec](https://microsoft.sharepoint-df.com/:w:/r/teams/IC3SDK/_layouts/15/guestaccess.aspx?e=ikcNmg&%3bisSPOFile=1&%3bparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA0MTIwMTYwMCJ9&%3bshare=EeOMEI3f03ZAipTsJz2ZDr0BXvfyoLiAmgzjgiLECvIctg&isSPOFile=1)

[Private Preview](https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/EXS9nYh5pzJMl-DluHiEoggB5sXCfzv__pQ-aGDDfcdMXQ?e=wBajho&%3bisSPOFile=1&isSPOFile=1)

[Design](https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/EeL0DC0fQxpHh3RZjXMoAA8B9Zh8IgGC1R3huPYlo-Ffbg?e=PHMVju&wdOrigin=TEAMS-ELECTRON.p2p.bim&wdExp=TEAMS-TREATMENT&wdhostclicktime=1650466716185&isSPOFile=1)

**Api Spec:** [azure-rest-api-specs/operatorconnect.json at slpavkov/operatorconnect-review · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/blob/slpavkov/operatorconnect-review/specification/communication/data-plane/OperatorConnect/preview/2022-06-01-preview/operatorconnect.json)

**Sdk view:** [@azure/communication-phone-numbers - apiview.dev](https://apiview.dev/Assemblies/Review/b4273b3b5deb4b61bc3d58ad4d3badc8?diffRevisionId=b8ad502721de45ca89ed5b1034e599ae&doc=False&diffOnly=False&revisionId=746c7b4ac9d14edba596ce8fe7d62d4d)

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/f9cb0840-98dc-b478-3887-f1ecf1834949) (MS INTERNAL ONLY)
