### ISSUE TITLE
Board Review: @azure/ai-text-analytics@6.0.0

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk#4339]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Cognitive Language
* Main contacts: @deyaaeldeen 
* Expected code complete date: August 2022
* Expected release date: August 2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/cognitiveservices-Language-2022-04-01-preview/specification/cognitiveservices/data-plane/Language/preview/2022-04-01-preview/textanalytics.json
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/3774

## About the client library

* Name of the client library: @azure/ai-text-analytics
* Languages for this review: JavaScript

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/553ca3650d3542d4b044c6a2857addfc
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/textanalytics/ai-text-analytics/samples-dev

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 6/20

**Comment by kyle-patterson** [comment]
Rescheduled for 6/23

**Comment by srnagar** [comment]
[Recording](https://msit.microsoftstream.com/video/83ae0840-98dc-b478-b05a-f1ecf3489d9f) (MS INTERNAL ONLY)
