### ISSUE TITLE
Change Request: Typos/updates for JS/TS

### ISSUE THREAD

**Issue by arpanlaha** [Azure/azure-sdk#434]
- Rule ID `ts-error-handling-coersion` is misspelled, should be `ts-error-handling-coercion`
- Rule `ts-node-support` in section 4.3.3 states that LTS versions of Node are 6.x through 11.x - this is out of date as 6.x and 11.x are both in End-of-Life status

**Comment by adrianhall** [comment]
ts-node-support has been updated, and will be merged next week - see #424
