### ISSUE TITLE
Board Review: Introducing Management namespace grouping

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk#4346]
Right now only dataplane libraries are grouped by functional area using [these values here](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-namespaces-approved-list).  @KrzysztofCwalina asked me to explore what it would look like if we did the same for management plane and so I put together [this spreadsheet](https://microsoft-my.sharepoint.com/:x:/p/micnash/EVcsyfQp8Z1AnxtIrjF9cXEB7m3d1BhVR-b1dzuiZw5ExQ?e=SZmMeY) which is not complete yet but at least starts get give an initial picture of what things might look like.  Obviously the namespaces are C# versions but it would be simple enough to apply to other languages.

I think there are a lot of mixed feelings on this and @KrzysztofCwalina  wanted to schedule a meeting to discuss this and make a decision to abandon or move forward.

**Comment by lilyjma** [comment]
scheduled for 5/31 3-4pm pst

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/10a90840-98dc-b478-adb5-f1ece135b67a) (MS INTERNAL ONLY)
