### ISSUE TITLE
Board Review: Java, Python GA version for Cognitive Service - Language(Text Analytics)

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk#4357]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team:  Azure Cognitive Language
* Main contacts: @mssfang @kristapratico
* Expected code complete date: 09/01/2022
* Expected release date: 09/04/2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/Language/stable/2022-05-01/textanalytics.json
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/3774  https://github.com/Azure/azure-sdk/issues/4339

## About the client library

* Name of the client library: Microsoft Cognitive Language Service
* Languages for this review: Java, Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link:
https://apiview.dev/Assemblies/Review/fe6cd393a9bb4a869c220e353b41d4e4?diffRevisionId=e128928e06284db585cc3aecadc53a57&doc=False&diffOnly=False&revisionId=8bb60482875a413ea8fcc3970596107a
* Link to Champion Scenarios/Quickstart samples: 
https://gist.github.com/mssfang/a73b8a7a396300bff8133502a12254d0

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/453e3478565f4bdfb4df7e8ca9b53ba9
* APIView Diff (2022-05-01 vs. 3.1): https://apiview.dev/Assemblies/Review/453e3478565f4bdfb4df7e8ca9b53ba9/a0ca9d65fc02403da0162ba27a7dd08a?diffRevisionId=cd87cd2c0e3e45479938f5182f7a8364&doc=False&diffOnly=True
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/textanalytics/azure-ai-textanalytics/samples
  
### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by mssfang** [comment]
FYI, @deyaaeldeen

**Comment by kyle-patterson** [comment]
Scheduled for 7/14 1p-3p PDT

**Comment by jsquire** [comment]
To my knowledge, .NET is not ready for review and will be delayed.    @pallavit - can you confirm the plan for .NET, please?

**Comment by heaths** [comment]
@jsquire all Text Analytics is delayed till August but, yes, there's no way I'll be ready for this by July 14th.

@mssfang can you update this to specifically say "Text Analytics"? There are lots of Cognitive Service - Language SDKs. It was not clear from the invite or reading through this issue which SDK this was for until I clicked the one (currently) APIView link.

**Comment by kyle-patterson** [comment]
Cancelled scheduled appointment, will reschedule for later in July/August as APIs are ready

**Comment by kyle-patterson** [comment]
Rescheduled for 7/27 1p-3p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/35cc0840-98dc-ae81-bd7b-f1ed0defd311) (MS INTERNAL ONLY)
