### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) [Calling] Raw Audio (Andriod Java) 

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4373]
**Service team responsible for the client library**: Calling Native Team

**API View link**: https://apiview.dev/Assemblies/Review/431f10ace9aa4c389b466e53d6ae0db1?diffRevisionId=a8c81f7f4c8b4c71a8abd37265e5b4e0&doc=False&diffOnly=True&revisionId=12f494ea78434199ac7bfd3c4bb59c29

**Contact email**. => PM: Laith Rodan (Laith.Rodan@microsoft.com), Dev Lead: Sanath Rao (sanath.rao@skype.net), Ze Hang Zheng (zehangzheng@microsoft.com)
**Name of the client library.** => Azure Communication Services Calling SDK
**Languages for this review**. => Android

**Champion scenarios**
## Raw Audio Feature

Raw Audio introduces new APIs that enable customers to receive and send raw audio.

### New classes

1. `RawOutgoingAudioProperties`: Used as a parameter to configure raw outgoing audio. Object has the following structure:
    1. `AudioSampleRate` : Configure Raw Audio Sample Rate. 
    2. `AudioChannelMode` : Configure whether raw audio is mono or stereo.
    3. `AudioFormat`: Configure the format the audio is being sent in (ex. PCR 16 bit).
    4. `OutgoingAudioMsOfDataPerBlock` (Optional Parameter): For outgoing audio, configure how many ms of data per block is being sent.

2.  `RawIncomingAudioProperties`: Used as a parameter to configure raw incoming audio. Object has the following structure:
    1. `AudioSampleRate` : Configure Raw Audio Sample Rate. 
    2. `AudioChannelMode` : Configure whether raw audio is mono or stereo.
    3. `AudioFormat`: Configure the format the audio is being sent in (ex. PCR 16 bit).

2. `OutgoingAudioBuffer`: Used to send audio buffers. Object has the following structure:
    1. `RawAudioProperties` :  Used to configure raw audio

3. `IncomingAudioBuffer`: Used to receive audio buffers. Object has the following structure:
    1. `RawAudioProperties` :  Used to configure raw audio

3. `RawIncomingAudioStream`: Used to setup raw incoming audio. Object has the following structure:
    1. `RawAudioProperties` :  Used to configure raw audio

4. `RawOutgoingAudioStream`: Used to setup raw outgoing audio. Object has the following structure:
    1. `RawAudioProperties` :  Used to configure raw audio

5. `IncomingAudioEvent`: Used to receive audio buffer when incoming audio sends event

6. `LocalOutgoingAudioStream`: Used to setup local (physical) or dummy audio outgoing streams

7. `LocalIncomingAudioStream`: Used to setup local (physical) or dummy incoming audio streams

8. `OutgoingAudioStream`: Abstract parent class for outgoing audio streams

9. `IncomingAudioStream`: Abstract parent class for incoming audio streams

### New APIs
1. `OutgoingAudioBuffer`:
    1. public short[] getData() - Used to get the data of outgoing audio
    2. public OutgoingAudioBuffer setData(byte[] value) - Used to set the data of outgoing audio
    3. public int getDataSize() - Used for outgoing audio to make sure your data you passed in is correct 

2. `IncomingAudioBuffer`:
    1. public short[] getData() - Used to get the data of incoming audio
    2. public IncomingAudioBuffer setData(byte[] value) - Used to set the data of incoming audio
    4. public long getTimestampInTicks() - Used for incoming audio to get timestamp

3. `RawIncomingAudioStream`:
    1. addOnNewAudioBufferAvailableListener(this::handleIncomingAudioBuffer) - Used for receiving incoming audio events and its corresponding audio buffer
4. `RawOutgoingAudioStream`:
    1. addOnAudioStreamReadyListener(this::handleOutgoingAudio) - Used to inform users when raw audio data is ready to be sent

5. `IncomingAudioEvent`:
    1. getAudioBuffer() - Used to retrieve an audio buffer
6. `AudioOptions`:
    1. setRawIncomingAudioStream(incomingAudioStream) - Used to set raw incoming audio stream
    2. setRawOutgoingAudioStream(outgoingAudioStream) - Used to set raw outgoing audio stream

7. `Call`:
    1. startIncomingAudioStream(IncomingAudioStream) - Used to start an incoming audio stream
    2. startOutgoingAudioStream(IncomingAudioStream) - Used to start an outgoing audio stream
    3. stopIncomingAudioStream() - Used to stop current incoming audio stream
    4. stopOutgoingAudioStream() - Used to stop current outgoing audio stream

8. `IncomingAudioStream/OutgoingAudioStream`:
    1. getAudioStreamKind() - Returns the type of audio stream (LOCAL, VIRTUAL)

### RawAudioProperties

This class has enums that you use to initialize raw audio with.

```java
public enum AudioSampleRate {
    SAMPLE_RATE_96000,
    SAMPLE_RATE_88200,
    SAMPLE_RATE_44100,
    SAMPLE_RATE_48000;
}

public enum AudioChannelMode {
    CHANNEL_MODE__MONO,
    CHANNEL_MODE__STEREO;
}

public enum AudioFormat {
    PCM_16__BIT;
}

public enum OutgoingAudioMsOfDataPerBlock {
    MS_20,
    MS_10;
}
```

### Raw Incoming Audio

In order to receive raw incoming audio, create a RawIncomingAudioStream class and pass in RawAudioProperties

```java
RawAudioProperties incomingAudioProperties = new RawIncomingAudioProperties(AudioSampleRate.SAMPLE_RATE_48000, AudioChannelMode.CHANNEL_MODE__STEREO, AudioFormat.PCM_16__BIT);

RawIncomingAudioStream incomingAudioStream = new RawIncomingAudioStream(incomingAudioProperties);
```

Then pass it into audioOptions when you start the call

```java
audioOptions.setIncomingAudioStream(incomingAudioStream);
```
Register a listener to receive each the buffer (example below):

```java
incomingAudioStream.addOnNewAudioBufferAvailableListener(this::handleIncomingAudioBuffer);
```
The Listener:
```java
public void handleIncomingAudioBuffer(IncomingAudioEvent args)
{
    //args will contain AudioBuffer
    byte[] data = args.getIncomingAudioBuffer().getData();
    for (byte s: data)
    {
        //can add to a list or process it  
    }
}
```
### Raw Outgoing Audio
In order to send raw outgoing audio, create a RawOutgoingAudioStream class and pass in RawAudioProperties

```java
RawAudioProperties outgoingAudioProperties = new RawOutgoingAudioProperties(AudioSampleRate.SAMPLE_RATE_48000, AudioChannelMode.CHANNEL_MODE__STEREO, AudioFormat.PCM_16__BIT, OutgoingAudioMsOfDataPerBlock.MS_20);

RawOutgoingAudioStream outgoingAudioStream = new RawOutgoingAudioStream(outgoingAudioProperties);
```

Then pass it into audioOptions when you start the call

```java
audioOptions.setOutgoingAudioStream(outgoingAudioStream);
```
Register a listener to know when to start to send audio data

```java
outgoingAudioStream.addOnAudioStreamReadyListener(this::handleOutgoingAudio);
```
The listener will create a new thread and send in audio in a while loop. AudioBuffer provides a getDataSize() method to inform how large the buffer should be. Determined by the msblocks chosen, thread will need to sleep after sending.
```java
public void handleOutgoingAudio(PropertyChangedEvent args)
{
    Thread thread = new Thread(){
        public void run(){
            AudioBuffer buffer;
            Calendar nextDeliverTime = Calendar.getInstance();
            RawAudioProperties properties = outgoingAudioProperties;
            int currentSampleNumber = 0;
            while (true)
            {
                nextDeliverTime.add(Calendar.MILLISECOND, 20);
                buffer = new AudioBuffer(outgoingAudioProperties);
                byte data[] = new byte[buffer.getDataSize()];
                //modify data array
                buffer.setData(data);
                outgoingAudioStream.sendOutgoingAudioBuffer(buffer);
                long wait = nextDeliverTime.getTimeInMillis() - Calendar.getInstance().getTimeInMillis();
                if (wait > 0)
                {
                    try {
                        Thread.sleep(wait);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }
    };
    thread.start();
}
```

### Start and Stop Audio Streams

Stop current incoming stream and start an incoming audio stream from raw audio device
```java
        try {
            call.stopIncomingAudioStream().get(); // Will switch to a stream of dummy audio by default
            call.startIncomingAudioStream(new LocalIncomingAudioStream(AudioDeviceCategory.DUMMY)).get();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }
````

Stop current outgoing stream and start an outgoing audio stream from raw audio device
```java
        try {
            call.stopOutgoingAudioStream().get(); // Will switch to a stream of dummy audio by default
            call.startOutgoingAudioStream(new LocalOutgoingAudioStream(AudioDeviceCategory.DUMMY)).get();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }
````

**Comment by kyle-patterson** [comment]
Scheduled for 6/29

**Comment by srnagar** [comment]
[Recording](https://msit.microsoftstream.com/video/95db0840-98dc-bd6c-38c9-f1ecf7f62b83)(MS INTERNAL ONLY)

**Comment by raosanat** [comment]
### Start and Stop Audio Streams

Stop current incoming stream and start an incoming audio stream from raw audio device.
Api's have been renamed to match with Video API's and in Web SDK.

https://apiview.dev/Assemblies/Review/431f10ace9aa4c389b466e53d6ae0db1/7437ed62e9c7443b98b18e272f781ee7?diffRevisionId=0b713254bb144a098a8576ca278062ce&doc=False&diffOnly=True

```java
        try {
            // Start sending outgoing audio
            call.startAudio(this, new LocalAudioStream(AudioDeviceCategory.PHYSICAL));
            // Start receiving incoming audio
            call.startAudio(this, new RemoteAudioStream(AudioDeviceCategory.PHYSICAL));
            // Stop the incoming audio
            call.stopAudio(this, MediaStreamDirection.INCOMING);
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }
````

Stop current outgoing stream and start an outgoing audio stream from raw audio device
```java
        try {
            call.stopOutgoingAudioStream().get(); // Will switch to a stream of dummy audio by default
            call.startOutgoingAudioStream(new LocalOutgoingAudioStream(AudioDeviceCategory.DUMMY)).get();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }
````

**Comment by raosanat** [comment]
This is an example how iOS app can mute Speaker which is incoming audio from a Remote participant.
```
func toggleMuteSpeaker() -> Void {
        if !speakerMuted {
            self.call!.stopAudio(mediaStreamDirection: .incoming) { error in
                if (error == nil) {
                    self.incomingAudioStream = RemoteAudioStream(audioDeviceCategory: .dummy)
                    self.call!.startAudio(audioStream: self.incomingAudioStream!) { error in
                        if error == nil {
                            self.speakerMuted = true
                            print("==> Speaker mute passed")
                        } else {
                            print("==> Speaker mute failed")
                        }
                    }
                }
            }
        }
        else
        {
            self.call!.stopAudio(mediaStreamDirection: .incoming) { error in
                if (error == nil) {
                    self.incomingAudioStream = RemoteAudioStream(audioDeviceCategory: .physical)
                    self.call!.startAudio(audioStream: self.incomingAudioStream!) { error in
                        if error == nil {
                            self.speakerMuted = false
                            print("==> Speaker UnMute passed")
                        } else {
                            print("==> Speaker UnMute failed")
                        }
                    }
                }
            }
        }
    }
```
