### ISSUE TITLE
Board Review: Introducing metrics for Azure SDK

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk#4389]
## Contacts and Timeline

* Main contacts: Liudmila Molkova (Azure SDK), Strong Liu (Spring)
* Expected stable release date for this library:
  * Java: Metrics API abstractions and messaging SDKs changes: Aug 2022
  * Java: OTel implementation: 2023+
  * Other languages: 2023+

## Champion Scenarios

1. Users can monitor SDK-specific scenarios in their production apps, alert and scale applications based on it.
Messaging SDK example: number of received/sent messages/batches, prefetch counts, time lag between enqueue and receive time, number of opened and active connections, error/retry rate.

2. When an SDK or Azure service is suspected to be the root cause issue, users can narrow it down to a specific timestamp range, or application instance, correlate by timestamp with network failures, memory, or CPU metrics, and provide this additional context upon request from support or dev team.  Our TSGs can include guidance on how to use metrics to root cause/eliminate. This would not require reproducing the problem with an increased log level. Stress/perf tests would the first user of this feature.
  
There are three different user personas for this feature: client library developers, application developers, and metric plugin developers. 

### Client libraries

Libraries only work with Metrics abstraction in Azure Core, and never work with metric implementations.

```java
// Initialize meters in client constructor
AzureMeterProvider meterProvider = AzureMeterProvider.getDefaultProvider();
AzureMeter meter = meterProvider.createMeter("azure-core-metrics-samples", "1.0.0", clientOptions.getMetricsOptions());

// Possible combination of metric dimensions are created and cached. High-cardinality dimensions are to be avoided.
AzureAttributeCollection successAttributes = meter.createAttributeCollection()
    .add("endpoint", "http://service-endpoint.azure.com")
    .add("status", "ok");

AzureAttributeCollection errorAttributes =  meter.createAttributeCollection()
    .add("endpoint", "http://service-endpoint.azure.com")
    .add("status", "failure");

AzureLongCounter httpConnections = meter.createLongCounter("az.core.http.connections", "Number of created HTTP connections", null);

// then in service call methods (pipelines, etc) we record measurements.
boolean success = false;
try {
    success = connect();
} finally {
    httpConnections.add(1, success ? successAttributes : errorAttributes, currentContext);
}
```

[More samples](https://github.com/lmolkova/azure-sdk-for-java/blob/metrics-core/sdk/core/azure-core/src/samples/java/com/azure/core/util/metrics/MetricsJavaDocCodeSnippets.java)

### Application developers

This includes our stress/perf tests developers. 
App developers should never use azure-core metric abstractions, always use implementations, and are only expected to configure things:

* Application Insights/OpenTelemetry agent users do configuration through config files/env vars/sys properties. It can also be done with OpenTelemetry SDK (as shown in this example)
  ```xml
  <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-core-metrics-opentelemetry</artifactId>
  </dependency>
  ```

  ```java
  // configure OpenTelemetry SDK using OpenTelemetry SDK Autoconfigure
  AutoConfiguredOpenTelemetrySdk.initialize();

  // configure Azure Client, no metric configuration needed
  // client will use global OTel configured by OpenTelemetry autoconfigure package.
  AzureClient sampleClient = new AzureClientBuilder()
      .endpoint("https://my-client.azure.com")
      .build();

  // use client as usual, if it emits metric, they will be exported
  sampleClient.methodCall("get items");
  ```

* Developers can configure a custom pipeline for Azure SDK (usually for tests)

  ```java
  // configure OpenTelemetry SDK explicitly per https://opentelemetry.io/docs/instrumentation/java/manual/
  SdkMeterProvider meterProvider = SdkMeterProvider.builder()
      .registerMetricReader(PeriodicMetricReader.builder(OtlpGrpcMetricExporter.builder().build()).build())
      .build();

  // Pass OTel meterProvider to MetricsOptions.
  MetricsOptions customMetricsOptions = new MetricsOptions()
      .setProvider(meterProvider);

  // configure Azure Client to use customMetricsOptions - it will use meterProvider
  // to create meters and instruments
  AzureClient sampleClient = new AzureClientBuilder()
      .endpoint("https://my-client.azure.com")
      .clientOptions(new ClientOptions().setMetricsOptions(customMetricsOptions))
      .build();

  // use client as usual, if it emits metric, they will be exported
  sampleClient.methodCall("get items");
  ```

* they may use tracing along with metrics and OpenTelemetry would correlate them.

  ```java
  // configure OpenTelemetry SDK using OpenTelemetry SDK Autoconfigure
  AutoConfiguredOpenTelemetrySdk.initialize();

  // configure Azure Client, no metric configuration needed
  AzureClient sampleClient = new AzureClientBuilder()
    .endpoint("https://my-client.azure.com")
    .build();

  Span span = GlobalOpenTelemetry.getTracer("azure-core-samples")
    .spanBuilder("doWork")
    .startSpan();

  try (Scope scope = span.makeCurrent()) {
    // do some work

    // Current context flows to OpenTelemetry metrics and is used to populate exemplars
    // you can also pass OpenTelemetry context explicitly by passing it under PARENT_TRACE_CONTEXT_KEY
    String response = sampleClient.methodCall("get items");
    // do more work
  }

  span.end();
  ```

[More samples](https://github.com/lmolkova/azure-sdk-for-java/blob/metrics-core/sdk/core/azure-core-metrics-opentelemetry/src/samples/java/com/azure/core/metrics/opentelemetry/MetricsJavaDocCodeSnippets.java)

### Metric plugin developers

[Micrometer implementation example](https://github.com/lmolkova/azure-sdk-for-java/blob/metrics-core/sdk/core/azure-core/src/samples/java/com/azure/core/util/metrics/MicrometerMeter.java)

## API

- [azure-core API view](https://apiview.dev/Assemblies/Review/2d337912ebee4dc59d1d103a1c272978)
- [azure-core-metrics-opentelemetry: API view](https://apiview.dev/Assemblies/Review/5ecd7a90083a4e6aa3d949ae67b01578)
- [PR](https://github.com/Azure/azure-sdk-for-java/pull/29086) 

## User experience
Major APM tools are supported both through OTel and Micrometer implementations shipped with Sping. 

The bare-minimum is Azure Monitor and Prometheus.

**Comment by stliu** [comment]
no **Timer**?

is there a way for developer to track how much time it takes to upload a file to azure blob for example, and the P95 / P99?

**Comment by lmolkova** [comment]
@stliu 
[OTel Histograms](https://opentelemetry.io/docs/reference/specification/metrics/datamodel/#histogram) and [Micrometer 
 DistributionSummary](https://www.javadoc.io/doc/io.micrometer/micrometer-core/1.0.5/io/micrometer/core/instrument/DistributionSummary.html) allow getting percentiles out of buckets reported by the metric. 
[Timer](https://www.javadoc.io/doc/io.micrometer/micrometer-core/1.0.3/io/micrometer/core/instrument/Timer.html)  methods to get percentiles are partially deprecated in favor of distribution summary.

If you feel they are not good enough for your case, can you please explain more?

Also, I only added two instruments, for now, to show how this API can grow and picked two that we'll need soon. Number of instruments is likely to grow to support more: UpDownCounters (for active connections) and maybe gauges some day (to report current value of something every once in a while instead of when things happen).

**Comment by kyle-patterson** [comment]
Scheduled for 7/5 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/ae7b0840-98dc-bd6c-a69c-f1ecfd8a43d9) (MS INTERNAL ONLY)
