### ISSUE TITLE
Change Request: Sub-client naming (get vs. create) in light of Event Hubs

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-sdk#440]
At the JS guideline review last week, we re-committed ourselves to a `get` prefix for methods which vend sub-clients, e.g. `getBlockBlobClient()` lives on ContainerClient. The rationale, as I understand it, is that `create` is confusing and users might think they're creating a remote resource of some kind.

Event Hubs, in at least JS and Java, presently use create for things like `createConsumer()` and `createProducer()` which are not creating entities on the remote service per se, but @ramya-rao-a pointed out that these actually do create entities at the protocol level that users may have to pay for on an individual basis (or at least watch their caps).

I want to confirm if we would prefer `getConsumer()` vs. `createConsumer()` for EventHubs. Presumably all languages would want to change at the same time?

/cc @johanste @KrzysztofCwalina @JonathanGiles

**Comment by JonathanGiles** [comment]
This has been in the back of my mind recently too. To me, I feel that the Event Hubs consumer / producer are different than clients, and I therefore assuaged myself of concerns around lack of consistency. I am ok with 'create' here.

**Comment by johanste** [comment]
Pick your poison; `get` implies to me that you get the same instance back and `create` can imply that a resource is created. I personally believe that the existence of both `create_<child>` and `create_<child>_client` on the parent client should clear up any confusion.

**Comment by bterlson** [comment]
@johanste agree that get vs. create from first principles isn't super clear, but we decided on `get` for empirical reasons so I feel a bit bad ultimately making the call with "handwaving".

I think I agree with your last point, but given that the create operation may not make sense every time we have a sub-client for something (EventHubs being a notable example, I suppose), your solution doesn't generalize so I'm a bit reluctant.

**Comment by adrianhall** [comment]
BOARD DISCUSSION:
- There are actually three options: get_NOUN, create_NOUN, NOUN.
- NOUN is not idiomatic in .NET.  .NET would want to reserve create for service operation.
- NOUN "feels right" in JS (Cosmos); Java feels it is also a good thing
- Python uses NOUN for non-validating, get_NOUN for validating
- We should be careful about removing the verb to avoid readability issues
- For JS/Java/Python, it is a stylistic opinion - can be different on different clients

BOARD DECISION:
- MUST NOT use create_<NOUN> unless it creates a resource on the service
- Language guidelines should add no prefix vs. get so client libraries are consistent within the language.
