### ISSUE TITLE
Board Review: Introducing jdbc-identity

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk#4402]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Spring Cloud Azure
* Main contacts: Xiaolu Dai
* Expected stable release date for this library: July 2022

## About the Service 

* Link to documentation introducing/describing the service
  *  [Use Azure Active Directory for authenticating with MySQL](https://docs.microsoft.com/azure/mysql/single-server/concepts-azure-ad-authentication)
  *  [Use Azure Active Directory for authenticating with PostgreSQL](https://docs.microsoft.com/azure/postgresql/single-server/concepts-azure-ad-authentication)
* Link to the service REST APIs: 
  *  N/A
* Is the goal to release a Public Preview, Private Preview, or GA? 
  * GA

## About the client library

* Name of client library: **jdbc-identity**
* Link to library reference documentation: https://github.com/Azure/azure-sdk-for-java/tree/feature/credential-free-jdbc/sdk/spring-experimental/credential-free-jdbc
* Is there an existing SDK library? If yes, provide link: N/A

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?

Users using JDBC drivers in their application, such as MySQL and PostgreSQL, to connect to Azure Databases for MySQL and PostgreSQL. This library will allow them authenticate using Azure AD instead of username/password.

[Video - Delete Passwords - Credential-free connections for Java applications to Azure services](https://www.youtube.com/watch?v=tV8llykK5TI)

3. Who is the end-user of the application (the developer's customer)?
    The developer's customer
5. What features of the API need to be explained in the sample so that someone could use this API in real app?
    None.
7. How does the **authentication** workflow look? 
   ![https://github.com/Azure/azure-sdk-for-java/blob/feature/credential-free-jdbc/sdk/spring-experimental/credential-free-jdbc/design/jdbc-auth-design.png](https://raw.githubusercontent.com/Azure/azure-sdk-for-java/feature/credential-free-jdbc/sdk/spring-experimental/credential-free-jdbc/design/jdbc-auth-design.png)

See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).
Code is appreciated but optional. Pseudocode is fine.  

* Create a JDBC `Connection`
```java

        Connection connection = DriverManager.getConnection("jdbc:mysql://jdbc-dev.mysql.database.azure.com:3306/Db" 
                + "?sslMode=REQUIRED&useSSL=true" 
                + "&defaultAuthenticationPlugin=com.azure.identity.jdbc.extension.mysql.AzureMySqlMSIAuthenticationPlugin"
                + "&authenticationPlugins=com.azure.identity.jdbc.extension.mysql.AzureMySqlMSIAuthenticationPlugin");

        ResultSet queryResult = connection.prepareStatement("SELECT now() as now").executeQuery();
        if (queryResult.next()) {
           result = queryResult.getString("now");
        }
        connection.close();
```

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 
https://github.com/Azure/azure-jdbc-msi-extension/tree/samples/howto-demo/demo

**Comment by kyle-patterson** [comment]
Scheduled for 6/22

**Comment by saragluna** [comment]
After discussion with the arch board: 

- **Service directories** will be `sdk/[jdbc|kafka|redis|mongo|cassandra]`
- **Group ids** will be `com.azure`
- **Artifact names** will be `azure-identity-providers-[jdbc|kafka|redis|mongo|cassandra]`
- **Java packages** will be `com.azure.identity.providers.[jdbc|kafka|redis|mongo|cassandra]`
- **Java classnames** will be `AzureIdentity[Mysql|Postgresql|Kafka|Redis|Mongo|Cassandra]AuthenticationPlugin`
- Use separate artifacts for MySQL and PostgreSQL:
  + azure-identity-providers-jdbc-mysql
  + azure-identity-providers-jdbc-postgresql

**Comment by backwind1233** [comment]
Link PR: https://github.com/Azure/azure-sdk-for-java/pull/30649
