### ISSUE TITLE
Change Request: client cert path env variable for all languages

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk#441]
* _Which design guideline is affected?_
EnvironmentVariables

* _Which target languages are affected?_
All

* Describe the change:
Add an environment variable for AAD authentication via certificate:

environment variable|value|purpose
---|---|---
|AZURE_CLIENT_CERTIFICATE_PATH|local filesystem path of a certificate|AAD

## Reasoning
Azure Identity will accept configuration from environment variables. These should have consistent cross-language names. This one was agreed on during the [board review](https://github.com/Azure/azure-sdk/issues/393).

**Comment by adrianhall** [comment]
Q: Should this be a URL so that we can support other ways of getting certificate.

e.g.
* file://./certs/foo.p12
* keyvault://<something that keyvault understands>

**Comment by chlowell** [comment]
Fetching a URL isn't on the roadmap but some nonlocal paths (e.g. SMB shares) might just work for some language + environment combinations, and we don't want to rule those out. So, a better description for the value could be something like "path of a certificate file".

**Comment by adrianhall** [comment]
Board decision: APPROVED

@adrianhall will add it to the list of approved environment variables.

The team will work on documenting the order of precedence in the case of multiple credential techniques being configured, or make conflicting env. variables throw an error.

**Comment by adrianhall** [comment]
Added via PR #537.
