### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) [Job Router] SDK (JS, Python, Java & .net)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4417]
**ACS Job Router**

**Pint of contacts:**
bo.gao@microsoft.com
rsarkar@microsoft.com

**API View links**

- JS:   https://apiview.dev/Assemblies/Review/1d6c0f3692674b47a50d72d5041b8d1c
- Python:  https://apiview.dev/Assemblies/Review/b28099d071bc46b69e3071538638eff1
- Java:   https://apiview.dev/Assemblies/Review/eb82fdd1b3a24f7b8ae78f40582a52e8
- .NET:   https://apiview.dev/Assemblies/Review/d48afcabc0f04f779df35e0f27d3c6fd
      -(outdated) https://apiview.dev/Assemblies/Review/ee017f13abe04627a360f11b4c46abfa

**Champion Scenarios:**

- JS:
  - Samples:
    - https://github.com/Azure/azure-sdk-for-js/tree/feature/communication-job-router-preview/sdk/communication/communication-job-router/samples
  - README
    - https://github.com/Azure/azure-sdk-for-js/blob/feature/communication-job-router-preview/sdk/communication/communication-job-router/README.md

- Python
  - Samples:
    - https://github.com/Azure/azure-sdk-for-python/tree/restapi_job_router/repo_setup/sdk/communication/azure-communication-jobrouter/samples
  - README
    - https://github.com/Azure/azure-sdk-for-python/blob/restapi_job_router/repo_setup/sdk/communication/azure-communication-jobrouter/README.md

- Java
  - Samples:
    - https://github.com/cparisineti/azure-sdk-for-java/tree/feature/jobrouter-initial-commit/sdk/communication/azure-communication-jobrouter/src/samples/
  - README
    - https://github.com/cparisineti/azure-sdk-for-java/blob/feature/jobrouter-initial-commit/sdk/communication/azure-communication-jobrouter/README.md

- .NET
  - Samples
    - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/communication/Azure.Communication.JobRouter/samples/README.md
    - https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/communication/Azure.Communication.JobRouter/samples
  - README
    - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/communication/Azure.Communication.JobRouter/README.md

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/7acf0840-98dc-bd6c-8900-f1ecfd896793) (MS INTERNAL ONLY)
