### ISSUE TITLE
Release Event Hubs Track 2 Library

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk#442]
# Summary

Azure Event Hubs is a publish-subscribe service that can ingest millions of events per second and stream them into multiple applications.  To ensure that developers around the world have a first-class experience leveraging Azure Event Hubs in their applications, our goal is to create a client library that is developer-friendly, idiomatic to the .NET ecosystem, and as consistent across different languages and platforms as possible.   

The work items linked to this issue herein represent the tasks needed to produce the various previews and the eventual final version for the "track two" Event Hubs client library.

# Goal

Design, develop, and release the multiple previews & then the final version of the Event Hub client library, intended to allow developers to work with it and offer their feedback which we will use to help refine the design.

**Comment by adrianhall** [comment]
This is for the board review of the API changes necessary for preview-2?  It doesn't read that way.

**Comment by ramya-rao-a** [comment]
@adrianhall No, this is the uber epic to track the work across languages for Event Hubs Preview 2. It is similar to what @AlexGhiondea has been creating for Keyvault and Core, see #435 and #436
