### ISSUE TITLE
Board Review: Azure Maps SDK Sing Off

### ISSUE THREAD

**Issue by dubiety** [Azure/azure-sdk#4421]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Maps
* Main contacts: charlie.chen@
* Expected code complete date: July/2022
* Expected release date: July/2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/azure-maps/
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/maps/data-plane
* Link to GitHub issue for previous review sessions, if applicable: #4186 

## About the client library

* Name of the client library: Azure Maps SDK - Search (Java, Python), Route (Java), Render (Java) modules.
* Languages for this review: Java, Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Java

Search - https://apiview.dev/Assemblies/Review/7126eaeacfe3458da0692fa889d49b40
Route - https://apiview.dev/Assemblies/Review/251e3859259341b29cd7913cbfcb4a29
Render - https://apiview.dev/Assemblies/Review/c37782e6bdd94f71849bae52e7150b92

Quick start examples: https://github.com/daniel-rocha/azure-sdk-for-java/blob/maps/onboarding/search-route-render/sdk/maps/azure-maps-search/src/samples/java/com/azure/maps/search/samples/BuilderSamples.java

### Python

Search - https://apiview.dev/Assemblies/Review/0ab748be5297432eaf27d512e2d1b998

Quick start examples: https://github.com/alextts627/azure-sdk-for-python/blob/maps/onboarding/search/sdk/maps/azure-maps-search/samples/search.py

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by dubiety** [comment]
Hi @kyle-patterson ,any update on this?
I haven't heard from you since last time you try to confirm the meeting time with me. Can you give us some updates so we know what we can do next? Thank you very much.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/40a30840-98dc-bd6c-66f2-f1ed0d23a734) (MS INTERNAL ONLY)
