### ISSUE TITLE
Attach client library readme to NuGet packages when releasing

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk#443]
When publishing .NET packages to NuGet, i.e. [Azure.Core](https://www.nuget.org/packages/Azure.Core/1.0.0-preview.5), both `Project Site` and `Source Repository` point to the root of the https://github.com/Azure/azure-sdk-for-net and it would be better if one pointed to the Readme specific to the client library.

It would be great if as part of creating/releasing the package, the build generates the link to the Readme and attaches it to the package.

Things to consider: What happens if the structure of the repo changes? Do we create a new package to update the reference?

**Comment by maririos** [comment]
FYI @AlexGhiondea @KrzysztofCwalina

**Comment by kurtzeborn** [comment]
If we're going to do this we should not have them pointed at the readme in master, but instead point them to the readme for the corresponding tag of the released package.

Master link (we shouldn't use this one): https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/README.md

Tag link (for Azure.Core v1.0.0-preview.5): https://github.com/Azure/azure-sdk-for-net/blob/Azure.Core_1.0.0-preview.5/sdk/core/Azure.Core/README.md

**Comment by chidozieononiwu** [comment]
There are still a number of services with no ReadMe files. Won't it be better to address https://github.com/Azure/azure-sdk-for-net/issues/5499 first

**Comment by chidozieononiwu** [comment]
I am reopening this issue to discuss / finalize on pointing to master vs build commit SHA version of the ReadMe.md. Right now .NET points to the commit SHA, but it was requested to switch to master to match the other repos. Wes noted that pointing to master could eventually result in broken links e.g. after things like repo reorg @kurtzeborn  @weshaggard @Petermarcu @AlexGhiondea

**Comment by weshaggard** [comment]
>There are still a number of services with no ReadMe files. Won't it be better to address Azure/azure-sdk-for-net#5499 first

For the cases without a readme we could condition the link and if it doesn't exist we could not include it. On top of the readme links we should also add a similar link to the changelog.md if it exists.

**Comment by weshaggard** [comment]
>I am reopening this issue to discuss / finalize on pointing to master vs build commit SHA version of the ReadMe.md. Right now .NET points to the commit SHA, but it was requested to switch to master 

I highly recommend we use either a commit sha or release tag for these links in all the languages to avoid broken links for things moving as well as to avoid drift in samples and such overtime from older packages to the latest master information.
