### ISSUE TITLE
Board Review: Updates to Azure Digital Twins Data Plane SDKs (.NET, Java, Python, JS)

### ISSUE THREAD

**Issue by sjiherzig** [Azure/azure-sdk#4440]
**Intended to be a Small, Targeted Change**

Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Digital Twins
* Main contacts: @sjiherzig 
* Expected code complete date: 06/10/2022
* Expected release date: 06/30/2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/digital-twins/
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/pull/18790
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Azure.DigitalTwins.Core
* Languages for this review: .NET, Java, Python, JS

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/291bf8a4879947cdb38fbc47c7fb7224?diffRevisionId=b455b58f8fe541d1a969f878ddbe1a26&doc=False&diffOnly=False&revisionId=a62a2453f71942cc84d00f18232548d5
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/pull/28785/files#diff-4714b93c926ef479d35cd67bc673fe86c575ff7166535bb067a947ca1652cfdc

PR: https://github.com/Azure/azure-sdk-for-net/pull/28785

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/7ae2d85820a04a178fa7e0d5baa5d6d1?diffRevisionId=ecc65f047d9a46019f09f91c18f81c48&doc=False&diffOnly=False&revisionId=ab406df00d284c3d8079e4c9b168f3b9
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-java/pull/29420/files#diff-c2f7c604be6e61a4d4bb3799d4ee0d1dde06815814954d004a3dda3093a45306

PR: https://github.com/Azure/azure-sdk-for-java/pull/29420

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/4f65c4fd0fe646d389f9cf7beee006d3?diffRevisionId=76081d5dbad7467881a6a98f814e1e3f&doc=False&diffOnly=False&revisionId=a66c60cdb1d44426bd059fc9b63a27d8
* Link to Champion Scenarios/Quickstart samples: 

PR: https://github.com/Azure/azure-sdk-for-python/pull/24603
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/3acd8e0438b04a229a35cabb0e57edc8
* Link to Champion Scenarios/Quickstart samples:

Note: I could not find an API view artifact for the current stable release 1.0.3.

PR: https://github.com/Azure/azure-sdk-for-js/pull/22010

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by srnagar** [comment]
[Recording](https://msit.microsoftstream.com/video/d2c50840-98dc-bd6c-8551-f1ecf72c6b48)(MS INTERNAL ONLY)

**Comment by sjiherzig** [comment]
Updated APIViews for .NET and Java:

* .NET: https://apiview.dev/Assemblies/Review/291bf8a4879947cdb38fbc47c7fb7224?diffRevisionId=b455b58f8fe541d1a969f878ddbe1a26&doc=False&diffOnly=False&revisionId=a62a2453f71942cc84d00f18232548d5
* Java: https://apiview.dev/Assemblies/Review/7ae2d85820a04a178fa7e0d5baa5d6d1?diffRevisionId=ecc65f047d9a46019f09f91c18f81c48&doc=False&diffOnly=False&revisionId=ab406df00d284c3d8079e4c9b168f3b9
