### ISSUE TITLE
Board Review: Introducing apimanagement-custom-widget-scaffolder

### ISSUE THREAD

**Issue by JMach1** [Azure/azure-sdk#4442]
## Contacts and Timeline

* Service team responsible for the client library: @Azure/apim-team 
* Main contacts: @JMach1 & @azaslonov
* Expected stable release date for this library: 1st July

## About the Service 

* Link to documentation introducing/describing the service: http://aka.ms/apimdocs/portal/
* Link to the service REST APIs: 
[@azure/api-management-custom-widgets-scaffolder - apiview.dev](https://apiview.dev/Assemblies/Review/6821ffd31d9e4838869133675a130470?revisionId=a0c630e3d835455d850e3c813f80280f&doc=False)
[@azure/api-management-custom-widgets-tools - apiview.dev](https://apiview.dev/Assemblies/Review/d6c66b5b279b466c8b5c6fc928b93fa1?revisionId=f6d28c834c014c5b8e1ff103c3718c50&doc=False)
* Is the goal to release a Public Preview, Private Preview, or GA? GA

## About the client library

* Name of client library: @azure/apimanagement-custom-widget-scaffolder
* Link to library reference documentation: in development, soon accessible on https://aka.ms/apimdocs/portal/customwidgets
* Is there an existing SDK library? If yes, provide link: No

## Step 1: Champion Scenarios 

* Champion scenario 1
    * Customer uses his Developer Portal, which is part of the Azure API Management service.
    * Customer wants to customize it further, beyond what it's allowed now using various common widgets.
    * Customer begins process of creation of a custom widget via their admin interface of their Dev Portal, specifies name of their custom widget and which technology to use: 
    ![image](https://user-images.githubusercontent.com/92859870/173408477-5c91dd59-7ca7-47ad-bd71-5331f7c6090c.png)
    * Customer copies generated `npx` command and runs it locally (example of the generated command: 
    `npx @azure/apimanagement-custom-widget-scaffolder --displayName="Contoso widget" --tech="react" --openUrl="http://localhost:8080" --managementApiEndpoint="management.azure.com" --resourceId="subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.ApiManagement/service/<service-name>"`).
    * NPX command executes this library and creates a scaffold of a custom widget for the custommer.

* Champion scenario 2
    * Customer runs the `npx @azure/apimanagement-custom-widget-scaffolder` command directly and provides answers to all the prompts: ![Animation](https://user-images.githubusercontent.com/92859870/173670061-36c04a69-975e-4ff8-b48e-32cb255cb170.gif) (the exact wording of some of the questions is expected to change)

* Champion scenario 3
    * Programmatically (not expected to be used like this by customers, only by various MS tools, e. g. APIMs' VS Code extension)
    ```
    import { generateProject, TDeployConfig, TWidgetConfig } from "@azure/apimanagement-custom-widget-scaffolder";
    
    async function main(): Promise<void> {
      const widgetConfig: TWidgetConfig = {
          displayName: "Contoso widget",
          tech: "react",
      };
      const deployConfig: TDeployConfig = {
        managementApiEndpoint: "management.azure.com",
        resourceId: "subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.ApiManagement/service/<service-name>",
      };

      return generateProject(widgetConfig, deployConfig)
        .then(() => console.log("Your project has been generated successfully!"))
        .catch(console.error);
    }
    ```

## Step 2: Quickstart Samples (Optional)
* (Optional) Using your APIMs' Developer Portal instance, copy command to scaffold a custom widget with prefilled some of the fields and run it instead of next step
* `npx @azure/apimanagement-custom-widget-scaffolder`
* fill in all the questions asked by the Inquirer

**Comment by kyle-patterson** [comment]
Scheduled for 7/19 9a-11a PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/a5d50840-98dc-bd6c-6e14-f1ed07846b36) (MS INTERNAL ONLY)
