### ISSUE TITLE
Board Review: Azure.Gaming.PlayFab C# client

### ISSUE THREAD

**Issue by jasonsandlin** [Azure/azure-sdk#4444]
## Contacts and Timeline

* Responsible service team:
Azure Gaming Services (AGS)

* Main contacts:
jasonsa; andmcc

* Expected release date:
Add to PlayFab private preview release soon, ship as public preview in Q1 2023, GA release in Q3 2023

## About the Service 

* Link to documentation introducing/describing the service:
https://playfab.com/

* Link to the service REST APIs: 
APIs migrated to Azure so far: https://review.docs.microsoft.com/en-us/rest/api/playfab-rest-api-docs-pr/?branch=main
Full set of legacy AWS based PlayFab APIs: https://docs.microsoft.com/en-us/rest/api/playfab/client/?view=playfab-rest

* Link to GitHub issue for previous review sessions, if applicable:  
Intro meeting: https://github.com/Azure/azure-rest-api-specs-pr/issues/6491

## About the client library

* Name of the client library:
Azure.Gaming.PlayFab

* Languages for this review:
C# & Javascript only.  Other tier 1 languages (Java, Python) in progress

### .NET

* APIView Link:
https://apiview.dev/Assemblies/Review/641137e6ee074d36b72fe14db61aab0d

* Link to Champion Scenarios/Quickstart samples:

See https://github.com/Azure/azure-sdk-for-net-pr/tree/feature/playfab-dataplane/sdk/playfab/Azure.Gaming.PlayFab#examples for examples with code snippets. 

During private preview, we're only offering a limited set of features. More services and features will be added along the way.

### JavaScript

* APIView Link:
https://apiview.dev/Assemblies/Review/188b078cea014eb392ba10cdda95c9cf

**Comment by kyle-patterson** [comment]
Scheduled for 7/21 2p-4p PDT

**Comment by srnagar** [comment]
[Recording](https://msit.microsoftstream.com/video/2bdb0840-98dc-bd6d-527c-f1ed094f8ec9) (MS INTERNAL ONLY)
