### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) [Media streaming] SDK (JS)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4459]
**ACS Calling & Media streaming**

**Point of contacts:**
srahaman@microsoft.com

**Champion scenarios:**
https://skype.visualstudio.com/SCC/_git/client_calling_spool-native?path=/sdk/web/docs/AcsLiveStreaming/AcsLiveStreaming.md&version=GBsrahaman/2860061-live-streaming&_a=preview

**API View Link:** 
https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8/31c71b439dfb4b66a41c1c47cd123e49?diffRevisionId=425abdea698141ba9a1483a7df7c6952&doc=False&diffOnly=True

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/2bdb0840-98dc-bd6c-eee9-f1ed01654913) (MS INTERNAL ONLY)
