### ISSUE TITLE
Board Review: Confidential Ledger

### ISSUE THREAD

**Issue by deer-prudence** [Azure/azure-sdk#4464]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

## Contacts and Timeline

* Responsible service team: Confidential Ledger
* Main contacts: Emily Louden (emilylouden@microsoft.com)
* Expected code complete date: 10 July, 2022
* Expected release date: 19 July, 2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/confidential-ledger/overview
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Confidential Ledger
* Languages for this review: C#, Python, Java, JavaScript

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/7e9dd9920e324259b8a3653c313b0c7f
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/confidentialledger/Azure.Security.ConfidentialLedger/README.md#getting-started

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/54902a162acd43ddbb356e8ad37e0418
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/confidentialledger/azure-security-confidentialledger/src/samples

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/96c571e125784e6bbc46bf7014afb24a
* Link to Champion Scenarios/Quickstart samples: https://github.com/lynshi/azure-sdk-for-python/tree/lyshi/ga-changes/sdk/confidentialledger/azure-confidentialledger/samples
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/e9009116b3a04b0cbfd54377d62d4c27
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/confidentialledger/confidential-ledger-rest/samples-dev

**Comment by deer-prudence** [comment]
Note: We haven't updated the APIView links yet because none of the SDKs are completed yet. We will be updating them as the SDKs are completed. Thank you!!

**Comment by kyle-patterson** [comment]
Scheduled for 7/12 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/17d20840-98dc-bd6c-0f1d-f1ed02376840) (MS INTERNAL ONLY)
