### ISSUE TITLE
[July] Board Review: Azure.Core

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk#4467]
## Contacts and Timeline

* Responsible service team: Azure SDK .NET Team
* Main contacts: @annelo-msft @christothes @JoshLove-msft
* Expected code complete date: 6/27
* Expected release date: 6/29

## About the client library

* Name of the client library: Azure.Core
* Languages for this review: .NET

### APIView Links: 
  * [Client Certificate Auth](https://apiview.dev/Assemblies/Review/7127a49e9e1b4e638d2c99033c814f91/7bc77662f4c34df38fd03b372799f1d9?diffRevisionId=990d973a4b7048339f6c5a2fa53e49de&doc=False&diffOnly=True)
  * [Remove extraction of failure content from ClientDiagnostics](https://apiview.dev/Assemblies/Review/30aab894090c4556a36fd527542b1b0f/357fa7c811bd46f8a91c0a49191d1ce6?diffRevisionId=4e7f9419cb7d42de8c4964a7dc12d09c&doc=False&diffOnly=True) 

### Champion Scenarios:

For custom error creation scenario - see the PR https://github.com/Azure/azure-sdk-for-net/pull/28466

For the client certificate auth - see the Issue https://github.com/Azure/azure-sdk-for-net/issues/28640

**Comment by kyle-patterson** [comment]
Scheduled for 6/27

**Comment by srnagar** [comment]
[Recording](https://msit.microsoftstream.com/video/6aae0840-98dc-bd6c-c741-f1ecf66141b7) (MS INTERNAL ONLY)
