### ISSUE TITLE
Board Review: Introducing OpenEnergyPlatform

### ISSUE THREAD

**Issue by komakkar** [Azure/azure-sdk#4471]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline 

* **Service team responsible for the client library:**  Project Oak Forest
* **Main contacts**: krganesan, komakkar
* **Expected stable release date for this library**: July 30

## About the Service 

* **Link to documentation introducing/describing the service:** [Project Oak Forest Hero Scenario](https://microsoftapc-my.sharepoint.com/:w:/g/personal/komakkar_microsoft_com/EQSB378jpoxFsDM2SAfn0QEB2V9GGx8PYYAExmbmSpOqjg?e=8jGojg) 
* **Link to the service REST APIs:** In the doc. 
* **Is the goal to release a Public Preview, Private Preview, or GA?** Public Preview

## About the client library

* **Name of client library**: Open Energy Platform
* **Link to library reference documentation**: NA
* **Is there an existing SDK library?** If yes, provide link: NA

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library? Developer is creating Applications like [Petrel](https://www.software.slb.com/products/petrel)
2. Who is the end-user of the application (the developer's customer)? OnG companies like Exxon. 
3. What features of the API need to be explained in the sample so that someone could use this API in real app? Find details in the Hero Scenario Doc
4. How does the **authentication** workflow look? Details in Hero scenario doc. 
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).
[Project Oak Forest Hero Scenario](https://microsoftapc-my.sharepoint.com/:w:/g/personal/komakkar_microsoft_com/EQSB378jpoxFsDM2SAfn0QEB2V9GGx8PYYAExmbmSpOqjg?e=8jGojg) 
Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1
    * Link to library’s sample folder: 
* Champion scenario 2
    * Link to library’s sample folder:
* …
* Champion scenario n
    * Link to library’s sample folder:

## Step 2: Quickstart Samples (Optional) - will share in a couple of days. 
Include samples demonstrating how to consume the client library if available: 

* Create a new resource
* Read the resource
* Modify the resource
* Delete the resource
* Error handling 
* Handling race conditions/concurrency issues

**Comment by kyle-patterson** [comment]
Scheduled for 7/18 9a-11a PDT

**Comment by kyle-patterson** [comment]
Cancelled scheduled session at team's request, we will work to reschedule for a later date.
