### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) [ServerCalling] (Java & .NET)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4472]
Service name: ACS Server Calling 

**Key contact for this review:**

- Min Woo Lee minwoolee@microsoft.com
- Richard Cho richardcho@microsoft.com
- Juntu Chen juntuchen@microsoft.com (Java portion)

**Details:**

1. Link to previous API version: [Previous API](https://github.com/richardcho-msft/azure-rest-api-specs-pr/blob/dev-communication-CallingServer-2022-04-07-preview/specification/communication/data-plane/CallingServer/preview/2021-08-30-preview/communicationservicescallingserver.json)
2. Has your service already been deployed? Yes
3. Review material: [ACS Server Calling V3 API Design.docx](https://microsoft.sharepoint-df.com/:w:/t/ServerCalling/ER6bbIzEzchBk63as-GPt8kBYp0EQTIz8zkuEZqxLMKGgA?e=m5ynCJ)
4. Link to swagger: [Latest API](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/communication/Azure.Communication.CallingServer/src/Swagger/2022-04-07.json)

**​Hero scenario**:

1. Katie calls Alaska Airlines  
2. Alaska Airlines answers Katie’s incoming PSTN call 
3. Server calling invites agent to the call, accepts the invitation 
4. Agent talks with Katie
5. Server calling terminates the call after the talk is over

For Hero Scenario details, see Go to [ACS Server Calling V3 API Design.docx (sharepoint-df.com)](https://microsoft.sharepoint-df.com/:w:/t/ServerCalling/ER6bbIzEzchBk63as-GPt8kBYp0EQTIz8zkuEZqxLMKGgA?e=WaNRXi) and go to section Hero Scenario 1: Alaska Airlines Incoming PSTN Call

**APIView**: 
[Azure.Communication.CallingServer (1.0.0.0) - apiview.dev](https://apiview.dev/Assemblies/Review/2640b119c6694c538d782b50f10cf997)

[Java API View](https://apiview.dev/Assemblies/Review/6830305d43d442a8ae2dae3aed73878e)

**Latest feature branch and code for .NET SDK**:
[Github Link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/communication/Azure.Communication.CallingServer)
 
**Latest artifact**: 
[Artifact Link - Look at the Alpha Version](https://dev.azure.com/azure-sdk/public/_artifacts/feed/azure-sdk-for-net/NuGet/Azure.Communication.CallingServer/versions/1.0.0-beta.3)

**Comment by kyle-patterson** [comment]
Scheduled for 7/14 2p-4p PDT

**Comment by juntuchen-msft** [comment]
Latest feature branch and code for JAVA SDK:
https://github.com/Azure/azure-sdk-for-java/tree/feature/communication-InteractionController

**Comment by juntuchen-msft** [comment]
Java SDK apiview:
https://apiview.dev/Assemblies/Review/6830305d43d442a8ae2dae3aed73878e#com.azure.communication.callingserver.models.RecordingStateResponse

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/a0ae0840-98dc-bd6c-4ad5-f1ed03ce23ef) (MS INTERNAL ONLY)
