### ISSUE TITLE
Board Review: Azure Form Recognizer

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk#4496]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team for client libraries: Azure SDK Form Recognizer v-team
* Main contacts: catalina.peralta@microsoft.com, sameeksha.vaity@microsoft.com, witemple@microsoft.com, sai.nalluru@microsoft.com, caio.maia@microsoft.com
* Expected code complete date: August 2022
* Expected release date: TBD (August/September 2022)

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/applied-ai-services/form-recognizer/overview?tabs=v3-0
* Link to the service REST APIs: https://westcentralus.dev.cognitive.microsoft.com/docs/services/form-recognizer-api-2022-06-30-preview/operations/AnalyzeDocument
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: azure.ai.formrecognizer
* Languages for this review: .NET, Java, JS, Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/cf2c57b3d4c44ef08c2e8284f7441a2d
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/samples

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/013380cff6a941219a34457d4195942c
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/36ac7c8c633d4bf6a45ee8672243f195
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/formrecognizer/azure-ai-formrecognizer/samples
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/b414f0cb1f4a472782bb7c88fe239430
* Link to Champion Scenarios/Quickstart samples: https://github.com/witemple-msft/azure-sdk-for-js/tree/b6ab785214fcea2197f2e5a01f87c8cb16f3b603/sdk/formrecognizer/ai-form-recognizer/samples-dev

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 7/20 2p-4p PDT

**Comment by srnagar** [comment]
[Recording](https://msit.microsoftstream.com/video/67d70840-98dc-bd6c-e819-f1ed08d3d4ba) (MS INTERNAL ONLY)
