### ISSUE TITLE
Define strategy for running tests in all environments

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#45]
Define our strategy for running tests in all environments.

## Languages & Versions
- [ ] dotnet
  - [ ] .NET Core 2.2.X
  - [ ] .NET Core 2.1.X
  - [ ] .NET Framework 4.7.X
- [ ] java
  - [ ] 7
  - [ ] 8
  - [ ] 11
- [ ] python
  - [ ] 2.7
  - [ ] 3.5
  - [ ] 3.6
  - [ ] 3.7
- [ ] js
  - [ ] node 6
  - [ ] node 8
  - [ ] node 10
  - [ ] node 11
  - [ ] browser

## Clouds
- [ ] prod
- [ ] national
- [ ] stack
- [ ] simulated (localhost)

## Test Types
- [ ] unit
- [ ] functional

**Comment by kurtzeborn** [comment]
Closing... this is too generic.  We're going to open new issues to be more precise about what we want to do here.
