### ISSUE TITLE
Include additional guidance on logging

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk#450]
## The Basics

* Which design guideline is affected?

  Logging guidelines like [3.2.7](https://azuresdkspecs.z5.web.core.windows.net/#general-logging) (and even [1.1.4](https://azuresdkspecs.z5.web.core.windows.net/#sec-diagnosable) about diagnosable failures) from the General Guidelines, for example.

* Which target languages are affected?

  All languages.

* Describe the change:

  Add additional guidance around logging by default for diagnosing hard to repro problems, where to add that logging, how much to log, how users opt in/out, etc.

## Reasoning

A number of service teams, like Storage, want to enable logging by default to help customers capture and diagnose issues.

**Comment by adrianhall** [comment]
From the architecture board:

* @adrianhall will set up discussions with CXP to determine what happens in the corner cases of IoT, Functions
* @adrianhall will also discuss Functions with the Functions service team to determine if the required information can be logged at all
* @adrianhall will also discuss these requirements with @christopheranderson to determine if there are differences between his supportability requirements and Storage requirements.

In general, the board felt that this was something we should do - it's just a case of defining the feature and putting it in.
