### ISSUE TITLE
Board Review: Introducing WebPubSubClient

### ISSUE THREAD

**Issue by zackliu** [Azure/azure-sdk#4506]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Azure Web PubSub Service (vscsignalr@microsoft.com)
* Main contacts: chenyl@microsoft.com(Chenyang Liu)
* Expected stable release date for this library: Sep.15 2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/azure/azure-web-pubsub/
* Link to the service REST APIs: It's not a REST-style client. Already discussed with API board and API review is not applicable in this case.
* Is the goal to release a Public Preview, Private Preview, or GA?  The service has been already GA.

## About the client library

* Name of client library: WebPubSubClient
* Link to library reference documentation: 
    * Client spec: https://github.com/Azure/azure-webpubsub/blob/main/protocols/client/client-spec.md
    * Wire package:
      * JSON: https://docs.microsoft.com/en-us/azure/azure-web-pubsub/reference-json-reliable-webpubsub-subprotocol
      * Protobuf: https://docs.microsoft.com/en-us/azure/azure-web-pubsub/reference-protobuf-reliable-webpubsub-subprotocol
* Is there an existing SDK library? If yes, provide link:  No public one. But there's a prototype.
  * .net: https://github.com/zackliu/azure-sdk-for-net/tree/wpspubsubclient/sdk/webpubsub/Azure.Messaging.WebPubSub.Client

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library? They use the client library to develop a client app (or webpage) that maintains a websocket connection and pub sub messages.
2. Who is the end-user of the application (the developer's customer)? Developer's customer
3. What features of the API need to be explained in the sample so that someone could use this API in real app? 
  * Connect
  * Disconnect
  * JoinGroup
  * LeaveGroup
  * SendToGroup
  * SendEvent
4. How does the **authentication** workflow look? Client fetch token from negotiation server and then connect to the service.
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1: Construct a client and pub sub messages between clients.
```csharp
  var client = new WebPubSubClient(() => FetchToken());
  client.OnConnected += async() => await client.JoinGroupAsync("group", msg => Console.WriteLine(msg));
  await client.StartAsync();
  await client.SendToGroupAsync("group", message);
  await client.StopAsync();
```

* Champion scenario 2: Construct a client and send/receive events with server
```csharp
  var client = new WebPubSubClient(() => FetchToken());
  client.OnServerMessage += msg => Console.WriteLine(msg)
  await client.StartAsync();
  await client.SendEventAsync(message);
  await client.StopAsync();
```

* Champion scenario 3: Construct a client and idempotent publish message
```csharp
  var client = new WebPubSubClient(() => FetchToken());
  client.OnConnected += async() => await client.JoinGroupAsync("group", msg => Console.WriteLine(msg));
  var ackId = 1;
  var result = await client.SendToGroupAsync("group", message, ackId);
  while (result.Failed)
  {
     result = await client.SendToGroupAsync("group", message, ackId);
  }
  await client.StopAsync();
```

**Comment by kyle-patterson** [comment]
Scheduled for 8/3 4p-6p PDT

**Comment by tg-msft** [comment]
Is https://apiview.dev/Assemblies/Review/39b74bed588e407ca3b06411bf7760e3 the correct ApiView listing for this library?

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/658b0840-98dc-ae81-04c3-f1ed1392075b) (MS INTERNAL ONLY)
