### ISSUE TITLE
Change Request: Long-term support (LTS) for Azure SDKs

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-sdk#451]
## Problem

Versioning problems surfaces across all the SDKs to varying degrees. While this is not a full list of all the versioning related issues, it's a start (roughly in order of impact):

1. "Dependency hell" - this surfaces in two distinct but similar ways:
    1. Platforms that can only load 1 version of a given library. (i.e. JSON.NET or Guava)
    2. SDKs exposing external types publicly on SDKs (i.e. Reactor (3rd party), AAD, Azure.Core libs)
2. Supportability & predictability - when should customers plan on upgrading their SDKs? Ideally they have a long notice and when they upgrade know how long before they have to move again. How long should service teams port patches down to older SDKs?
3. Maturity and feature coverage- semver is a poor communicator of maturity. `3.0.0` is often less stable than `2.15.23`.  `3.0.0` might have less features than `2.15.23` because a feature will be deprecated. `3.0.0` usually has more bugs because it's fresh with lots of changes compared to 23 patches on the `2.x` version
4. Innovation friction - SDK developers struggle to balance innovation of new features with supporting older customers. Current approach requires often times not interacting with bleeding edge. Customers using bleeding edge are often some of the best community members/etc. and prevents our SDK teams (often composed of language experts) from fully engaging with their platforms. 

## Proposed solution

Azure-wide, long term releases with a regular, predictable cadence.

Each LTS would have an agreed upon set of requirements/standards that each Azure SDK would meet before LTS begins. For instance, once "track 2" is stable and GA, I'd propose naming it an LTS. Customers consuming an LTS SDK would have confidence it inter-operates with all other SDKs from that LTS group (same Newtonsoft/AAD/etc.)

### Cadence and support window details

Each LTS would start with a planning period, an active period where it's recommended customers use it and most features get back-ported, a maintenance period with just hotfixes, and a pre-planned EOL.

Current is where we innovate on the next set of requirements and move the line forward. Mostly this would be focused on UX and language platform features, not service features which should exposed in current as well as in most Active stage LTS releases. Customers expecting latest features (Span<T>, AsyncIterators, asyncio, etc.) would use current.

I propose an LTS period of 3 years, with a new LTS being created every year with an active period of 1 year. This would mean that at any given time, an SDK would have 4 supported versions:

1. sunset LTS
2. noon LTS
3. sunrise LTS
4. current

If a hotfix is released, it must be ported to all 4 (if applicable). If a feature is released, it should be in Current and any active LTS releases (my timing means there is only one, but if the periodicity is changed to say 1.5 years, then there would be 2 active releases in parallel).

### Customer experience

New projects should use sunrise LTS by default. Current should be used by folks who want bleeding edge. Folks who are on sunset LTS should move to sunrise LTS. Folks using noon LTS are fine for the time being unless they need new features, but they should never be pressured to update/etc. by support folks/etc.

Organizations would attempt to use the same LTS libraries.

We should provide migration guides to each LTS with any details on how to approach it. There wouldn't be a lot of guides on migrating to current. We set expectations that "current" is a little messy.

### TBDs

- Language by language implementation details
- User research
- Broader buy in from service side

**Comment by massand** [comment]
@christopheranderson Agree generally with an LTS proposal because API versions seem common enough for all services. This proposal should not preclude special agreements to offer extended LTS support (for any SDK) past the sunrise LTS EOL date. Also, all "extended LTS" clients should migrate to latest sunrise LTS as well. This might be worth calling that out under Customer experience.

**Comment by adrianhall** [comment]
Notes from the board meeting:

* General agreement that LTS is "a good thing"
* Need buy-in from all the stake-holders, including CXP and service teams
* Customer validation required for proposed language

Action Items from the board meeting:

1. @adrianhall will propose language as a PR to the engineering systems documentation.
    * Review internally first, then validate with customers
2. Add a "LTS" section to each mono-repo README before GA indicating LTS supported versions.

**Comment by adrianhall** [comment]
Per board - we will revisit this policy in six months.
