### ISSUE TITLE
Change Request: Provide and update guidelines on the design of ServiceVersion as a string within concrete client options

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk#4526]
We prefer the client options to have an `std::string` `ApiVersion` field, with a defaulted single value that is supported. We'd want the guidelines to reflect that, rather than having a dedicated `ServiceVersion` extensible enum class.

Here's an example of how we'd want it going forward:
https://github.com/Azure/azure-sdk-for-cpp/blob/07a56bc5e3e728fbbcf37a84bb9d37fec1ee7efc/sdk/attestation/azure-security-attestation/inc/azure/attestation/attestation_client_options.hpp#L90-L113

This section in the guidelines need to be updated:
https://azure.github.io/azure-sdk/cpp_introduction.html#service-versions

See related conversation, where we updated KeyVault Keys to follow this pattern:
https://github.com/Azure/azure-sdk-for-cpp/pull/3783#issuecomment-1175352089

**Open question:**
Do we want to provide any guidance on whether a constructor is necessary, and if so, what types of options get defaulted in there? And, should the options be a flat structure, rather than having nested structs which group certain options?

For example, this is what we have in blobs today, where options are just a bag of fields:
https://github.com/Azure/azure-sdk-for-cpp/blob/07a56bc5e3e728fbbcf37a84bb9d37fec1ee7efc/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp#L133-L161

cc @LarryOsterman, @JeffreyRichter, @RickWinter

**Comment by JeffreyRichter** [comment]
The XxxOptions struct must be constructable. So, it must have a ctor; either explicitly or implicitly. I think the ctor should be parameterless as all fields are read/write after construction.

The XxxOptions struct mostly has policy options; each policy can have its own option struct and so these fields would be nested inside the policy options struct. Nesting is fine and would encouraged for related fields. It is actually unusual for a service to have service-specific options in the XxxOptions struct - Storage (your example) is unusual.
