### ISSUE TITLE
Change Request: maxRetries parameter naming convention for TS

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-sdk#454]
I need to write guidelines codifying the options that control retry policy. Today we have multiple conventions in use (maxTries, retryCount). I want to standardize on `maxRetries` which seems to be used in many places already, by other languages in our SDK, and libraries in ecosystem.

/cc @ramya0820

**Comment by sadasant** [comment]
Is this about [throttlingRetryPolicy](https://github.com/Azure/azure-sdk-for-js/blob/41e716cbcdead0ef15d4ff744ec9a1d39a24b986/sdk/core/core-http/lib/policies/throttlingRetryPolicy.ts) and [exponentialRetryPolicy](https://github.com/Azure/azure-sdk-for-js/blob/41e716cbcdead0ef15d4ff744ec9a1d39a24b986/sdk/core/core-http/lib/policies/exponentialRetryPolicy.ts)? I'm wondering if we could abstract these into a common API that would be agnostic of headers and status codes? Would that be relevant / desired?

**Comment by ramya-rao-a** [comment]
@bterlson There is also a new ask to allow users to configure the timeout for each attempt. Do you want to use this issue to write the guideline for that or create a new one?
