### ISSUE TITLE
Board Review: CADL+DPG status review

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#4549]
High level schedule:
- 4:05-4:10: Context of the meeting (5 minutes)
- 4:10-4:30: Typescript (20 minutes)
- 4:30-4:55: Python (25 minutes)
- 4:55-5:25: Java (30 minutes)
- 5:25-5:55: C# (30 minutes)
- 5 minutes buffer

Granular schedule:

# Typescript:

- Parity between Swagger input and CADL input (20 minutes)
  - Includes list of blocking issue “DPG Impact” that prevents full parity if any

# Python:

- Parity between Swagger input and CADL input (10 minutes)
  - Includes list of blocking issue “DPG Impact” that prevents full parity if any
- Model generation status check (10 minutes)
  - Explain the design of “hybrid dict / model”
  - Includes list of remaining items necessary to support most common service teams scenarios. Clarify if some are “DPG Impact” if any.
- Integration of models into methods (5 minutes)
  - As Python do not have overload, I don’t expect this part to take time, it’s mostly saying we can dynamically adapt with “duck typing” to customer usage

# Java:
Gist: https://gist.github.com/srnagar/77cf5c1377d6f7119251abbab180a6b6

- Parity between Swagger input and CADL input (10 minutes)
  - Includes list of blocking issue “DPG Impact” that prevents full parity if any
- Model generation status check (10 minutes)
  - Includes list of remaining items necessary to support most common service teams scenarios. Clarify if some are “DPG Impact” if any.
- Convenient methods generation with models (10 minutes)
  - Includes list of remaining items necessary to support most common service teams scenarios. Clarify if some are “DPG Impact” if any.

# C#:

- Parity between Swagger input and CADL input (10 minutes)
  - Includes list of blocking issue “DPG Impact” that prevents full parity if any
- Model generation status check (10 minutes)
  - Includes list of remaining items necessary to support most common service teams scenarios. Clarify if some are “DPG Impact” if any.
- Convenient methods generation with models (10 minutes)
  - Includes list of remaining items necessary to support most common service teams scenarios. Clarify if some are “DPG Impact” if any.

## About the client library

* Name of the client library:
* Languages for this review:

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link:  
  Authoring:  https://apiview.dev/Assemblies/Review/6869b1d9850442c382642a33e3c2e4cf
  ConfidentialLedger: https://apiview.dev/Assemblies/Review/66c4d8047d314d9bbd187287849de031
* Link to Champion Scenarios/Quickstart samples:
    Parity with DPG 1.0:    https://gist.github.com/chunyu3/e6ba945c25377a52a885f809b1beadff
    Model Generation:   https://gist.github.com/archerzz/52572693eaaf80255bb0a933db23edd7
     Convenience Methods:  https://gist.github.com/pshao25/80c8fdbed798d1e677928b2a3b4f5f03

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/953fc91e3ec54be1938cfc6c43ed0ed6)
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/srnagar/77cf5c1377d6f7119251abbab180a6b6

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/ae22a209b3bb43edae4525cb1376ad82
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/iscai-msft/839ca734f593a129ef2fd9d91bf7a84a
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/ace1ed3841954a1d96e739a189371580
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/qiaozha/f838bca10378c5d6d9201fe55fbf6d69

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by annelo-msft** [comment]
Per @lmazuel, each language will show:
- Parity with DPG v1.0 -- i.e. DPG 2.0 can generate the same clients from Cadl that DPG 1.0 could generate from swagger
- Generated convenience methods (.NET and Java only)
- Basic model generation
- Costing of remaining work

**Comment by kyle-patterson** [comment]
Scheduled for 9/12 4p-6p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/8ed70840-98dc-a27a-1732-f1ed338427cc) (MS INTERNAL ONLY)
