### ISSUE TITLE
Board Review: Add `x-ms-app` header to Azure Monitor logs query requests

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk#4570]
## Contacts and Timeline

* Responsible service team: Log Analytics team
* Main contacts: @scottaddie, @joshfree, @KarishmaGhiya, @rakshith91, @nisha-bhatia, @srnagar 
* Expected code complete date: N/A
* Expected release date: N/A

## About the Service 

* Link to documentation introducing/describing the service: [Azure Monitor Logs Query](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/get-started-queries)
* Link to x-ms-app header documentation - https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/request-properties
* Link to the service REST APIs: [REST API](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/operationalinsights/data-plane/Microsoft.OperationalInsights/preview/2021-05-19_Preview/OperationalInsights.json)
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/2783

## About the client library

* Name of the client library: Azure Monitor Query
* Languages for this review: All languages

## Artifacts required (per language)

API views are not applicable for this review.

## Ask from the service team

The service team is requesting the client libraries to include `x-ms-app` header in all requests made to query logs. 

https://github.com/Azure/azure-sdk-for-net/issues/27992
https://github.com/Azure/azure-sdk-for-python/issues/23817
https://github.com/Azure/azure-sdk-for-js/issues/21196
https://github.com/Azure/azure-sdk-for-java/issues/28034

- Should we add a custom header to identify Azure SDK clients?
      - We already have User-Agent header but it contains other details like platform and version information and requires parsing the string to know that it's an Azure SDK client.
- What's the guidance on adding custom headers in Azure SDK that are used by services?

### Background

The Azure Monitor Query client library supports querying metrics and logs from Azure Monitor. Metrics requests go through ARM endpoint while Logs requests have a separate data-plane endpoint. The ask to include this new header is only for querying logs. This header is used by the service to track the caller. 

`User-Agent` header does include the client library details but that string changes between versions, platforms and languages. So, the service prefers to have a consistent value like `AzureMonitorQuerySDK` for all requests coming from Azure SDK.

**Comment by kyle-patterson** [comment]
Scheduled for 8/2 9a-11a PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/afae0840-98dc-ae81-d6d8-f1ed128164fd) (MS INTERNAL ONLY)

**Comment by srnagar** [comment]
After reviewing with the arch board, a decision was made to not make this change. As a workaround, the service team can run a "contains" operation on the user agent string to identify the caller. This workaround has been communicated to Dan Hadari.
