### ISSUE TITLE
Board Review: Azure Maps C# SDK

### ISSUE THREAD

**Issue by dubiety** [Azure/azure-sdk#4572]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Maps
* Main contacts: charlie.chen@
* Expected code complete date: July/2022
* Expected release date:  Aug./2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/azure-maps/
* Link to the service REST APIs:  https://github.com/Azure/azure-rest-api-specs/tree/main/specification/maps/data-plane
* Link to GitHub issue for previous review sessions, if applicable: https://github.com/Azure/azure-sdk/issues/4186

## About the client library

* Name of the client library: Azure Maps SDK - Search, Route, Render, GeoLocation modules.
* Languages for this review: C#

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

Search - https://apiview.dev/Assemblies/Review/0c8fa90052e24a5fb7f7e6b453ea6b10
Route - https://apiview.dev/Assemblies/Review/d3a63b5587724c208e0cfe1dde375581
Render - https://apiview.dev/Assemblies/Review/ec51a1ccfeed4e9ca513f34388275659

Hero scenarios:
Search - [Search an address](https://github.com/khmic5/azure-sdk-for-net/blob/khmic/search/sdk/maps/Azure.Maps.Search/tests/Samples/SearchClientSamples.HelloWorld.cs)
Route - https://github.com/dubiety/azure-sdk-for-net/tree/feature/maps-route/sdk/maps/Azure.Maps.Route#route-directions
Render - https://github.com/dubiety/azure-sdk-for-net/tree/feature/maps-render/sdk/maps/Azure.Maps.Render#render-images

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 8/9 4p-6p PDT

**Comment by KrzysztofCwalina** [comment]
@dubiety, when you say that expected release date is 8/22, do you mean preview or GA?

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/658b0840-98dc-ae81-5626-f1ed18485710) (MS INTERNAL ONLY)

**Comment by dubiety** [comment]
We mean preview here.
