### ISSUE TITLE
Board Review: Azure ML Python GA

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk#4573]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure ML 
* Main contacts: Paul Shealy, Hanchi Wang, Ankit Shinghal, Neehar Duvvuri, Harneet Virk
* Expected code complete date: 1 October 2022
* Expected release date: 1 November 2022
* **Requesting a review slot for beginning of September**

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs: https://docs.microsoft.com/rest/api/azureml/
* Link to GitHub issue for previous review sessions, if applicable:
    * [Introduction to service](https://github.com/Azure/azure-sdk/issues/2172)
    * [Preview API review](https://github.com/Azure/azure-sdk/issues/4129)

## About the client library

* Name of the client library: azure-ai-ml
* Languages for this review: Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/1c0b5fbf39e0441888cf89ae7bc4d669?revisionId=a40c39989b9e418895a043c257e6b913&doc=False
* Link to Champion Scenarios/Quickstart samples:
 

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 8/31 2p-4p PDT

**Comment by kyle-patterson** [comment]
Rescheduled for 9/7 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/6add0840-98dc-a27a-c178-f1ed2f07dcc1) (MS INTERNAL ONLY)
