### ISSUE TITLE
Board Review: Personalizer Java SDK

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk#4583]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Personalizer
* Main contacts: @sharathmalladi 
* Expected code complete date: 08/12/2022
* Expected release date: 09/08/2022

## About the Service 

* Link to documentation introducing/describing the service: 
  * [Model Put API](https://microsoft.sharepoint.com/:w:/t/personalizr/Ed0dN7HgEF9EhKj9Bx5BRfkBfu9Q6o9Fw_SeFW9X3F96EQ?e=ZP9W2X&CID=D24A1141-04ED-43CA-8278-74C8AC7BE91B&wdLOR=cC1B79B0D-2E02-47B5-ACAD-32C62A0B2799)
* Link to the service REST APIs:
  * https://github.com/Azure/azure-rest-api-specs/blob/b6f54bbdbb64a9e7d27b49b4e1db5e56e40c310d/specification/cognitiveservices/data-plane/Personalizer/preview/v1.1-preview.3/Personalizer.json
* Link to GitHub issue for previous review sessions, if applicable: https://github.com/Azure/azure-sdk/issues/3877

## About the client library

Java:
* Name of the client library: azure.ai.personalizer
* Languages for this review: Java

Typescript:
* Name of the client library: @azure-rest/ai-personalizer
* Languages for this review: Typescript/Javascript

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Java
* [APIView Link](https://apiview.dev/Assemblies/Review/428d553679104ed4acf3567594041be4)
* Link to Champion Scenarios/Quickstart samples:
  - [Multi-slot Rank and Reward](https://github.com/Azure/azure-sdk-for-java/blob/68cb6bfd9b48e03a341ab9063e6e9830d242373a/sdk/personalizer/azure-ai-personalizer/src/samples/java/com/azure/ai/personalizer/MultiSlotRankActionsAndRewardEvents.java)
  - [Rank and Reward](https://github.com/Azure/azure-sdk-for-java/blob/68cb6bfd9b48e03a341ab9063e6e9830d242373a/sdk/personalizer/azure-ai-personalizer/src/samples/java/com/azure/ai/personalizer/RankActionsAndRewardEvents.java)

### TypeScript

* [APIView Link](https://apiview.dev/Assemblies/Review/0cce1e8e99214d6f96986c3771adad3a)
* Link to Champion Scenarios/Quickstart samples:
  - [Multi-slot Rank and Reward](https://github.com/Azure/azure-sdk-for-js/blob/9d98e8c487352c0d480baeb6339cc648a24371bb/sdk/personalizer/ai-personalizer-rest/samples-dev/multiSlotRankActionsAndrewardEvents.ts)
  - [Rank and Reward](https://github.com/Azure/azure-sdk-for-js/blob/9d98e8c487352c0d480baeb6339cc648a24371bb/sdk/personalizer/ai-personalizer-rest/samples-dev/rankActionsAndrewardEvents.ts)

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 8/18 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/38db0840-98dc-ae81-a23f-f1ed1f421103) (MS INTERNAL ONLY)
