### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) [Recognize DTMF / Media Streaming] (.Net & Java)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4585]
Service name: **ACS Server Calling**
Key contact for this review: **fmorales**@
Link to previous API version: N/A
Description of the material to be reviewed/changed: C#/Java SDK operations for Recognize DTMF and Media Streaming.
Champion scenarios that briefly explain how developers will use your API: 
Recognize: Contoso app can configure recognition of DTMF (dual-tone multiple-frequency) tones while playing IVR audio and takes necessary actions. [Document link](https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/EWm_myjkxn9MoWUet4zB-IIBsedUYhVL7xmMX7UD7xWNoA?e=TsCP8G) to a broader explanation.
Media Streaming: Contoso can request streaming of call audio (mixed/unmixed). [Document link](https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/EZyuzwMGusZDmCazIb7hiC0B8tA44yalWbFGA03vISaWrg?e=Yw7WoC) to a broader explanation.Languages for this review: C#, Java
**Artifacts per language.**
* [C# API View](https://apiview.dev/Assemblies/Review/0a0257c6bfe5475a91fa71f634133f1b?diffRevisionId=327126c13c754ce6b36157e7c006be6f&doc=False&diffOnly=False&revisionId=a654278934bc4fcc8df0cafbae1fa79e)
* [Java Api View](https://apiview.dev/Assemblies/Review/33dca86e42124cf1874e92a301b78d02?diffRevisionId=33ff01ae94ee41d9b64b5b0bd64160eb&doc=False&diffOnly=False&revisionId=501290571d7a4d87b4839bffd0d25131)

**Comment by kyle-patterson** [comment]
Scheduled for 8/23 2p-4p PDT

**Comment by cochi2** [comment]
Sample code for Media Streaming: 
```c
// Answer Call
var mediaStreamingConfiguration = new MediaStreamingConfigurationDto()
{
    TransportUrl = "wss://testwebsocket.webpubsub.azure.com/client/hubs/media?accesstoken={access_token}",
    ContentType = MediaStreamingContentTypeDto.Audio,
    AudioChannelType = MediaStreamingAudioChannelTypeDto.Unmixed
};
var response = await callingServerClient.AnswerCallAsync(
    incomingCallContext,
    new Uri(callConfiguration.AppCallbackUrl),
    mediaStreamingConfiguration);

// Create Call
var mediaStreamingConfiguration = new MediaStreamingConfigurationDto()
{
    TransportUrl = "wss://testwebsocket.webpubsub.azure.com/client/hubs/media?accesstoken={access_token}",
    ContentType = MediaStreamingContentTypeDto.Audio,
    AudioChannelType = MediaStreamingAudioChannelTypeDto.Unmixed
};


var createCallResult = await client.CreateCallAsync(
        callSource, 
    new List<PhoneNumberIdentifier> { target },                      
    new Uri(callConfiguration.AppCallbackUrl),                    

    mediaStreamingConfiguration)
```

**Comment by cochi2** [comment]
Recognize operations
```c
var recognizeConfigurations = new RecognizeConfigurations
{
    InterruptPromptAndStartRecognition = true,
    InitialSilenceTimeoutInSeconds = TimeSpan.FromSeconds(5),
    TargetParticipant = new CommunicationUserIdentifier("8:acs:<guid>_<guid>"),
    DtmfConfigurations = new DtmfConfigurations
    {
        InterToneTimeoutInSeconds = TimeSpan.FromSeconds(5),
        MaxTonesToCollect = 5,
        StopTones = new List<StopTones> { StopTones.Pound, StopTones.Asterisk }
        },
};
var recognizeOptions = new RecognizeOptions(RecognizeInputType.Dtmf, recognizeConfigurations)
{
    OperationContext = Guid.NewGuid().ToString(),
    Prompt = new FileSource(new Uri(_callConfiguration.AudioFileUrl)),
    StopCurrentOperations = true,
};
var response = await _callConnection.GetCallMedia().RecognizeAsync(recognizeOptions).ConfigureAwait(false);
```

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/42d70840-98dc-ae81-5540-f1ed23c567e9) (MS INTERNAL ONLY)

**Comment by tg-msft** [comment]
See also https://gist.github.com/KrzysztofCwalina/52f7a05ba6e988651d51f3e49d83569e for early thoughts on a webhook listener

**Comment by jasonshave** [comment]
I listened to the recording and wanted to share this approach I took as a helper library for my team's code (Call Automation). 

The library consumes both Event Grid and CloudEvent types, handles deserialization and invocation of C# events. 

Developers only need to wire up their handlers. 

https://github.com/jasonshave/Azure.Communication.Services.EventHandler

**Comment by cochi2** [comment]
Updated sample code for Recognize operation:
```c
var recognizeOptions = new CallMediaRecognizeDtmfOptions(
    targetParticipant: new PhoneNumberIdentifier("<PhoneNumber>"),
    maxTonesToCollect: 5)
{
    InterruptPromptAndStartRecognition = true,
    InitialSilenceTimeout = TimeSpan.FromSeconds(5),
    InterToneTimeout = TimeSpan.FromSeconds(5),
    StopTones = new List<DtmfTone> { DtmfTone.Pound, DtmfTone.Asterisk }
    OperationContext = Guid.NewGuid().ToString(),
    Prompt = new FileSource(new Uri(_callConfiguration.AudioFileUrl)),
    StopCurrentOperations = true,
};
var response = await _callConnection.GetCallMedia().RecognizeAsync(recognizeOptions).ConfigureAwait(false);

**Comment by cochi2** [comment]
New API Views, since we moved from `calling server` to `call automation`:
C# [Api View](https://apiview.dev/Assemblies/Review/b59ab49c63ae4b1e878fe92c902f3efb)

**Comment by cochi2** [comment]
We had a follow up meeting with the following notes:

* We are cleared for our Public Preview for both languages.
* We received comments on the API view that we should consider for GA, but they are not a blocker for Public Preview.
  *    With exception of Tone -> DtmfTone in Java, to keep parity.
