### ISSUE TITLE
Preview releases should have the "Pre-release" marker in the GitHub release

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#459]
When we create a release on GitHub (for a corresponding release to a public feed) and the release/tag contains the word preview in the version (or "b" for Python) we should have the "Pre-release" marker set for the release ([example](https://github.com/Azure/azure-sdk-for-js/releases/tag/%40azure%2Fstorage-queue_12.0.0-preview.1)).  For preview 1 we manually edited the releases and checked the "This is a pre-release" box to accomplish this.

This needs to be done for releases from all 4 repos:
- [x] azure-sdk-for-net
- [x] azure-sdk-for-js
- [x] azure-sdk-for-java
- [x] azure-sdk-for-python

This does not need to be done for the partner release pipelines.

**Comment by chidozieononiwu** [comment]
Resolved with a PR to azure-sdk-build-tools repo
