### ISSUE TITLE
Release tagging needs to better handle rate limiting

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#462]
During our last wave of releases we hit a number of rating limiting issues that causes our github tagging and release process to fail. We should make some improvements to those before the next wave. A couple ideas we could do to improve:

1) We could create another github service account so that the token we are using isn't shared. 
2) Try to use the reset epoch the give in the error to time our retries. Of course if those resets are more than 5 or 10 mins we should probably not wait that long.

**Comment by kurtzeborn** [comment]
@KarishmaGhiya may have bandwidth to help with this.

**Comment by danieljurek** [comment]
The work to create the account and put the PAT into KV was @scbedd 

I've verified that the tagging/release process works in JS, .NET, and Python release pipelines with the new PAT. Java validation is pending correct artifact creation.

**Comment by danieljurek** [comment]
A few other release pipelines (e.g. mgmt plane, docs) were using the old PAT. They have been updated to use the new PAT.
