### ISSUE TITLE
Board Review: @azure/communication-react - CallComposite PSTN & 1:N Calling

### ISSUE THREAD

**Issue by anjulgarg** [Azure/azure-sdk#4634]
## Contacts and Timeline

* Responsible service team: [acswebuidev@microsoft.com](mailto:acswebuidev@microsoft.com)
* Main contacts: anjulgarg, alkwa, de.david
* Expected code complete date: Aug 20, 2022
* Expected release date: Aug 24, 2020

## About the Service 

* Link to documentation introducing/describing the service: https://azure.github.io/communication-ui-library/?path=/story/overview--page
* Link to the service REST APIs: n/a
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/3231

## About the client library

* Name of the client library: @azure/communication-react - CallComposite
* Languages for this review: TypeScript

### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/d729a1015cbb4ccebd14e38dd2247482/8f6d810b27e54afd9f60d0465da8d2e4?diffRevisionId=47a7fbabaa9f40418e58e94710750081&doc=False&diffOnly=True
* Powerpoint detailing changes: https://microsoft-my.sharepoint.com/:p:/p/anjulgarg/EeQ0ah0MCrhClL1bodedm-EBHxNUpauFWPNNbCJfv_nbWg?e=kRfVBz
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/anjulgarg/276e5b59931f31eacdf5ff9ac6082438

**Comment by kyle-patterson** [comment]
Scheduled for 9/15 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/07a90840-98dc-a27a-997d-f1ed3540c2dd) (MS INTERNAL ONLY)
