### ISSUE TITLE
Clear guidance per language repo on binary composition & versioning.

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk#464]
We need to come up with clear guidance for the language teams on how to handle versioning and binary composition together in our repos now that we are releasing packages. The guidance may need to be language tooling specific but during the first release cycle the switch to binary composition crept up on us even though we knew we would need to make a decision about this in the future.

Local developer workflows favor source composition but we need to think about how those changes are deployed to customers and re-integrated into dependent code bases as well.

**Comment by mikeharder** [comment]
Content applicable to all languages and specific to JS has been merged.  Keeping open since content specific to other languages (if any) still needs to be added.

**Comment by kurtzeborn** [comment]
@weshaggard you wanted to integrate this into the document and then work with @danieljurek to expand it for the other 3 languages.
