### ISSUE TITLE
Remove manual configuration/intervention in release process

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk#466]
Our release process is currently structured around having a single CI build that builds a specific set of packages (defined at queue time) and then feeding that into a release pipeline. There is a trade off to be made between having lots of discrete build and release pipelines requiring zero configuration on each run, and requiring manual work to drive a release.

This is a much better conversation that we need to have around the unified pipelines model in Azure Pipelines and the granularity of our CI pipelines.

**Comment by kurtzeborn** [comment]
Pretty sure this issue sort of fades away with the transition do unified pipelines.

**Comment by mitchdenny** [comment]
Yep - closing this since unified pipelines looks to be the right direction (sans a few teething issues around required checks etc).
