### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) [Push Notification] (iOS)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4664]
Service name: Azure Communication Service, Chat Team
Key contact for this review: Angel Lan
Link to previous API version: https://apiview.dev/Assemblies/Review/7b285d2a43b94e83b7adb3681185e7d7
Description of the material to be reviewed/changed: IOS SDK APIs https://apiview.dev/Assemblies/Review/eaa100d11a8a49a59bc77abe4d8731d5/41d6c35099574edab531340858b6fc4a?diffRevisionId=170071434fb3475d8a1c29e05698cc8a&doc=False&diffOnly=True
Champion scenarios that briefly explain how developers will use your API: We will put it in QuickStart - https://docs.microsoft.com/en-us/azure/communication-services/tutorials/add-chat-push-notifications
Languages for this review: swift

**Comment by kyle-patterson** [comment]
Scheduled for 8/22 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/fcbd0840-98dc-ae81-f34f-f1ed22f38c0c) (MS INTERNAL ONLY)
