### ISSUE TITLE
Board Review: Device Update GA

### ISSUE THREAD

**Issue by dpokluda** [Azure/azure-sdk#4688]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Device Update for IoT Hub
* Main contacts: David Pokluda (dpokluda), Esha Shah (eshashah)
* Expected code complete date: 8/12
* Expected release date: 9/2

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/iot-hub-device-update/understand-device-update
* Link to the service REST APIs: https://github.com/dpokluda/azure-rest-api-specs/blob/bbf13b0366e5863ce65f84d588ed5681326af0cb/specification/deviceupdate/data-plane/Microsoft.DeviceUpdate/stable/2022-10-01/deviceupdate.json
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/4256

## About the client library

* Name of the client library:
* Languages for this review: C#, Python, Java, TypeScript

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/66009f420cf045c5b183b3abd2372599
* Link to Champion Scenarios/Quickstart samples: https://github.com/dpokluda/azure-sdk-for-net/tree/11e7049d0866494b6f02252bd3281efc7342f800/sdk/deviceupdate/Azure.IoT.DeviceUpdate/samples
* PR: https://github.com/Azure/azure-sdk-for-net/pull/30523

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/712a65227c1441e8b8feea5411d9dc7c
* Link to Champion Scenarios/Quickstart samples: https://github.com/dpokluda/azure-sdk-for-java/tree/8950147096c061f76ec70d0dd3eeb3d33c42db22/sdk/deviceupdate/azure-iot-deviceupdate/src/samples
* PR: https://github.com/Azure/azure-sdk-for-java/pull/30475

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/d78c12d760ae42c1b1ac1163bf253394
* Link to Champion Scenarios/Quickstart samples: https://github.com/dpokluda/azure-sdk-for-python/tree/60db0737b8de3161596075c0fed041511d60c67a/sdk/deviceupdate/azure-iot-deviceupdate/samples
* PR: https://github.com/Azure/azure-sdk-for-python/pull/25709
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/2400bb0928494483989a2e7f43573036
* Link to Champion Scenarios/Quickstart samples: https://github.com/dpokluda/azure-sdk-for-js/tree/559f996aaa9734a2a5edef686e92e40f0b76e6c8/sdk/deviceupdate/iot-device-update-rest/samples-dev
* PR: https://github.com/Azure/azure-sdk-for-js/pull/22903

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 8/30 2p-4p PDT

**Comment by srnagar** [comment]
[Recording](https://msit.microsoftstream.com/video/05970840-98dc-a27a-30e3-f1ed2974ae2b) (MS INTERNAL ONLY)
