### ISSUE TITLE
Deployment driver rules

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk#469]
During the release cycle that we've just been through it was clear that we needed a few key personnel on deck to drive the release process. Ideally our release pipelines will be self service and fully automated, but we should nominate the minimum staffing levels we need to make sure that we can successfully release libraries when things go wrong:

1. Representative from the engineering systems team (ideally the repo expert).
2. Representative from the language team.
3. Representative from the service team.

Some or all of these folks would be on deck to perform manual validations as the libraries progress through the release pipeline until we are 100% confident that we are automatically catching any issues that can come up.

Within the engineering systems team we should make sure we rotate this responsibility and it would be a good idea to do this on the language teams as well.

**Comment by kurtzeborn** [comment]
We've taken a slightly different approach to this where, for preview 2, we're asking the libraries teams to drive the release of their libraries.  We've created documentation and [this checklist](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki?pagePath=%2FReleasing%20Packages%2FReady%20to%20release%20checklist&pageId=62&wikiVersion=GBwikiMaster) for that purpose.  We may need to revisit, but closing this issue for now.
