### ISSUE TITLE
Board Review: azblob "tiny blob"

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk#4694]
## Contacts and Timeline

* Responsible service team: storage
* Main contacts: mohsha@microsoft.com jhendrix@microsoft.com
* Expected code complete date: 8/19
* Expected release date: 9/5

## About the Service 

The original `azblob` was previously reviewed.  We have since refactored it, separating the specialized blob clients into their respective sub packages.  The root `azblob` package contains what is commonly called "tiny blob" which is a reduced subset of APIs to address the 95% use-case scenarios.

While we can briefly discuss the sub-packages, the main emphasis of this review is the "tiny blob" public surface area.
## About the client library

* Name of the client library: `azblob`
* Languages for this review: Go

https://apiview.dev/Assemblies/Review/ad398a65d5004f9eb78a2f52afc4e113

**Comment by kyle-patterson** [comment]
Scheduled for 8/25 2p-4p PDT.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/79a60840-98dc-a27a-6b75-f1ed27cf4ac1) (MS INTERNAL ONLY)
