### ISSUE TITLE
Board Review: Azure DevCenter

### ISSUE THREAD

**Issue by chrissmiller** [Azure/azure-sdk#4702]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Microsoft.DevCenter
* Main contacts: For SDK generation, chrismiller@microsoft.com, mstark@microsoft.com, maharlan@microsoft.com
* Expected code complete date: Not certain what this refers to, SDK/sample generation is done
* Expected release date: 9/1

## About the Service 

* Link to documentation introducing/describing the service: https://azure.microsoft.com/en-us/services/dev-box/, https://techcommunity.microsoft.com/t5/azure-developer-community-blog/introducing-azure-deployment-environments/ba-p/3412095
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/devcenter/data-plane/Microsoft.DevCenter/preview/2022-03-01-preview
* Link to GitHub issue for previous review sessions, if applicable: Previous intro session on April 20th, but I don't appear to have access to the private sdk repo I can't link the issue

## About the client library

* Name of the client library: Azure DevCenter
* Languages for this review: .NET, Java, Python, JS/TS

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/6d5c661681914116a8c2b4d701be338d
* Link to Champion Scenarios/Quickstart samples: https://github.com/chrissmiller/azure-sdk-for-net/blob/chrismiller/devcenter-net/sdk/devcenter/Azure.DevCenter/tests/Samples/Sample_CreateDeleteDevBoxAsync.cs 

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/fc7e300f8a7c453dbdb6f4c18e175a51 
* Link to Champion Scenarios/Quickstart samples: https://github.com/chrissmiller/azure-sdk-for-java/tree/chrismiller/devcenter-java/sdk/devcenter/azure-devcenter/src/samples

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/b0d3118cb501492c8c87cd84408fbe30
* Link to Champion Scenarios/Quickstart samples: https://github.com/chrissmiller/azure-sdk-for-python/blob/chrismiller/azure-devcenter/sdk/devcenter/samples
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/46682e3fd3144c07acfc71b4d47a1065
* Link to Champion Scenarios/Quickstart samples: https://github.com/chrissmiller/azure-sdk-for-js/tree/chrismiller/dp-devcenter/sdk/devcenter/devcenter-rest/sample

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

## Thank you!
    
 Please let me know if there's anything missing/incorrectly formatted, happy to provide additional information etc.

**Comment by kyle-patterson** [comment]
Scheduled for 9/8 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/d7c50840-98dc-a27a-1029-f1ed30501b6a) (MS INTERNAL ONLY)
