### ISSUE TITLE
Azure Core Fundamentals Python (Zinc October 2022 - March 2023)

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#4705]
Items for Azure-Core:

Expected done in Copper:
- Untangle requests and Azure-Core (required for SAW). Cost: 3 ([issue](https://github.com/Azure/azure-sdk-for-python/issues/23348))

Required:
- https://github.com/Azure/azure-sdk-for-python/issues/22813
- https://github.com/Azure/azure-sdk-for-python-pr/issues/873
- Support generation of SDK that supports Header and AAD auth. Cost 5 ([issue](https://github.com/Azure/azure-sdk-for-python/issues/22789))
- Improve logging scope. Cost 3. ([issue](https://github.com/Azure/azure-sdk-for-python/issues/19552))

Important:
- Implement HTTPX transport. Cost: 3 ([issue](https://github.com/Azure/azure-sdk-for-python/issues/11279))
- CLI calls helper. Cost 3. ([issue](https://github.com/Azure/azure-sdk-for-python/issues/22220))
- Several issues around retry mechanism is not working well. Cost 10.
- Support env variables on AZURE_ as guidelines ask to. Cost 5. ([issue example](https://github.com/Azure/azure-sdk-for-python/issues/13400), there are several)

MQ level (costed as maintenance)
All 50 issues of Azure-Core:
https://github.com/Azure/azure-sdk-for-python/issues?q=is%3Aopen+is%3Aissue+label%3AAzure.Core

**Comment by rohit-ganguly** [comment]
FYI - I'm getting a 404 on https://github.com/Azure/azure-sdk-for-python-pr/issues/873 in the required section.
