### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk#473]
Building on the observation that we should have a process for engaging teams to release (https://github.com/Azure/azure-sdk/issues/469) it makes sense to consider automating the steps that we will be repeating for all releases today and in the future. 

The release manager needed 4 significant pieces of information for all releases from our engineering system: 
* Branch & Commit hash
* Service directory (or, in the case of JS, packages to generate) 
* (Once the build is finished) Artifact URLs to share with the team for review/signoff
* Final signoff from a service/language owner to release (in the case of JS, the packages to be released) (also related: https://github.com/Azure/azure-sdk/issues/463 -- scoping release to service or package)

In all cases the teams had to give me this information and I kicked off builds manually according to each language repo's instructions. I then checked the build periodically until artifacts were available. 

Using Teams was helpful for keeping everyone on the same page with respect to status and ensuring that the process kept forward momentum. It probably makes sense to track future releases in Teams. 

Automating some manual portions of the release engineer's job could make for a tighter process and alerts could engage teams to take action (like sanity check the artifacts or debug a failure in the release pipeline).

**Comment by kurtzeborn** [comment]
While there are many things we can do to help improve the process, for this issue for preview 2, I want to make sure all of the documentation is up-to-date and that we provide a clear checklist to devs doing the releases making it clear for them to confidently release their libraries without the need for engineering team intervention.  These are the docs I'm alluding to ([releases](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki?pagePath=%2FReleasing%20Packages&pageId=8&wikiVersion=GBwikiMaster), [checklist](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki?pagePath=%2FReleasing%20Packages%2FReady%20to%20release%20checklist&pageId=62&wikiVersion=GBwikiMaster)).

**Comment by kurtzeborn** [comment]
@maggiepint this is an old issue at this point.  We no longer track the build and commit hash because we've done work to automate that information getting into the GitHub releases.

If there are other opportunities to automate some of these, we're interested in doing that.  Just let me know.

**Comment by weshaggard** [comment]
Closing this issue as I don't think there is any other actionable work here at this point.
