### ISSUE TITLE
Board Review: Azure Monitor Ingestion

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk#4731]
## Contacts and Timeline

* Responsible service team: Evgeny Ternovsky and Raji Ramesh
* Main contacts: @rakshith91 @KarishmaGhiya @nisha-bhatia @srnagar
* Expected release date: September 2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/azure-monitor/logs/custom-logs-overview
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/monitor/data-plane/ingestion/preview/2021-11-01-preview

## About the client library

* Name of client library: Azure Monitor Ingestion
* Is there an existing SDK library? If yes, provide link:  None available

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/4a60a257fd284ac9b74d9f6c7533496a#Azure.Monitor.Ingestion
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/nisha-bhatia/2fdc7a131973565638beb3a23768b0fe

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/09343c57059a45059d80382dea84f573
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/ki1729/ad1349a8f9f032b2e9797e08669071a3

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/5fbe8b98bd4a4c62be152df0f4abc3d1
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/rakshith91/3e126aa2b2fd25ae4a391f821bf659c0
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/8ff38e561c27416f8b50c7af6e5a274c
* Link to Champion Scenarios/Quickstart samples: https://gist.github.com/timovv/8baa47d6a2d7c7bff5327ab29045c14a

**Comment by kyle-patterson** [comment]
Scheduled for 9/26, 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/c3cb0840-98dc-ade4-8cc0-f1ed3df90007) (MS INTERNAL ONLY)
