### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) Custom Token Expiration GA

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4733]
Complete Internal SDK Review for custom token expiration

**Service name:** ACS Developer Security
**Key contact for this review:** [@Aigerim Beishenbekova](https://skype.visualstudio.com/SPOOL/_dashboards/dashboard/79511244-5783-4bce-accc-d455133e0b9d#) [@Maxim Rytych](https://skype.visualstudio.com/SPOOL/_dashboards/dashboard/79511244-5783-4bce-accc-d455133e0b9d#) 
**Link to previous API version:** 
2021-03-07 [azure-rest-api-specs/CommunicationIdentity.json at main · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/Identity/stable/2021-03-07/CommunicationIdentity.json)
2022-06-01 [azure-rest-api-specs/CommunicationIdentity.json at main · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/Identity/stable/2022-06-01/CommunicationIdentity.json)
**Link to the new API version:** 
2022-10-01 [azure-rest-api-specs/CommunicationIdentity.json at main · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/Identity/stable/2022-10-01/CommunicationIdentity.json)
**Description of the material to be reviewed/changed:**
Adding the ability for customers to issue Communication Identity access token with a custom validity period in the range of [1-24] hours.
**Champion scenarios that briefly explain how developers will use your API:**
The main goal of this feature is to allow developers using ACS via the SDK  to customize Communication Identity access token expiration time. So far, ACS has only allowed customers to generate Communication Identity access token for a predefined period of 24 hours. This feature will provide clients with the ability to generate a Communication Identity access token with a custom expiration period in the range of [1-24] hours. The validity parameter will be optional. Customers who do not want to use this functionality will be able to issue Communication Identity access tokens in the same way as before. No breaking changes will be introduced.  Customers can make requests to issue a Communication Identity access token without specifying an expiration period in the same way as before. In this situation, the Communication Identity access token with a 24-hour expiration time will be generated. The data type of the new parameter is TimeSpan for .Net, Duration for Java, timedelta for Python, number for Typescript. 

For the generation of the Communication Identity access token in our SDK we have two APIs:
`getToken` API to issue or refresh a token for an existing user
`createUserAndToken`  API to create a new user and issue a token in a single request

Right now the Contoso developers are requesting token as follow:

**Getting a token for an existing user**
```csharp
// C#
Response<AccessToken> tokenResponse = await client.GetTokenAsync(user, scopes: new[] { CommunicationTokenScope.Chat });
string token = tokenResponse.Value.Token;
```

```java
// Java
List<CommunicationTokenScope> scopes = Arrays.asList(CommunicationTokenScope.CHAT);
AccessToken userToken = client.getToken(user, scopes);
```

```javascript
// Typescript
let { token } = await client.getToken(user, ["chat"]);
```

```python
# Python
tokenresponse = client.get_token(user, scopes=[CommunicationTokenScope.CHAT])
```

**Creating a user and a token in the same request**
```csharp
// C#
Response<CommunicationUserIdentifierAndToken> response = await client.CreateUserAndTokenAsync(scopes: new[] { CommunicationTokenScope.Chat });
var (user, token) = response.Value;
```

```java
// Java
List<CommunicationTokenScope> scopes = Arrays.asList(CommunicationTokenScope.CHAT);
CommunicationUserIdentifierAndToken result = client.createUserAndToken(scopes);
```

```javascript
// Typescript
let { user, token } = await client.createUserAndToken(["chat"]);
```

```python
# Python
user, tokenresponse = client.create_user_and_token(scopes=[CommunicationTokenScope.CHAT])
```

**With a new feature the Contoso developer can specify custom token expiration as follow:**
```csharp
// C#
TimeSpan tokenExpiresAfter = TimeSpan.FromHours(1);
Response<CommunicationUserIdentifierAndToken> response = await client.CreateUserAndTokenAsync(scopes: new[] { CommunicationTokenScope.Chat }, tokenExpiresAfter);
// or
Response<AccessToken> tokenResponse = await client.GetTokenAsync(user, scopes: new[] { CommunicationTokenScope.Chat }, tokenExpiresAfter);
```

```java
// Java
List<CommunicationTokenScope> scopes = Arrays.asList(CommunicationTokenScope.CHAT);
Duration tokenExpiresAfter = Duration.ofHours(1);
CommunicationUserIdentifierAndToken result = client.createUserAndToken(scopes, tokenExpiresAfter);
// or 
AccessToken userToken = client.getToken(user, scopes, tokenExpiresAfter);
```

```javascript
// Typescript
let tokenExpirationInMinutes = 60;
let { user, token } = await client.createUserAndToken(["chat"], tokenExpirationInMinutes);
// or
let { token } = await client.getToken(user, ["chat"], tokenExpirationInMinutes);
```

```python
# Python
token_expires_after = timedelta(hours=1)
user, tokenresponse = client.create_user_and_token(scopes=[CommunicationTokenScope.CHAT], token_expires_after=token_expires_after)
# or
tokenresponse = client.get_token(user, scopes=[CommunicationTokenScope.CHAT], token_expires_after=token_expires_after)
```
 
**Languages for this review:** .NET, Java, Python, and TypeScript
**Artifacts per language:**
.NET - [Azure.Communication.Identity (1.2.0.0) - Created for PR 29806 - apiview.dev](https://apiview.dev/Assemblies/Review/0dcdf2df81434647a99052cd79bc1e56)
Java -  [azure-communication-identity (version 1.4.0-beta.1) - Created for PR 29981 - apiview.dev](https://apiview.dev/Assemblies/Review/14ee9b90ecae43e7851a885337827fd5)
TypeScript - [@azure/communication-identity(1.1.1) - Created for PR 22623 - apiview.dev](https://apiview.dev/Assemblies/Review/386db32dce9d4d4dbd7c578501982819)
Python - [azure-communication-identity - apiview.dev](https://apiview.dev/Assemblies/Review/cab8292e3225490b885bc6302792ce33)

**Comment by garchiro7** [comment]
#scheduled

**Comment by kyle-patterson** [comment]
Scheduled for 9/13 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/eb9a0840-98dc-a27a-8f15-f1ed33b85ce3) (MS INTERNAL ONLY)
