### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL)  Video effects, background blur [JS]

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4735]
Service name:  ACS Calling
Key contact for this review: [@Prathmesh Kestikar](https://skype.visualstudio.com/SPOOL/_dashboards/dashboard/79511244-5783-4bce-accc-d455133e0b9d#) 
Link to previous API version:  ...
Description of the material to be reviewed/changed: ...
Champion scenarios that briefly explain how developers will use your API: ...
Languages for this review. JavaScript (TypeScript )
Artifacts per language.
 https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8?revisionId=3a33e39d7d544c5fa29d9c095e47de3a&doc=False

**Comment by garchiro7** [comment]
#Scheduled

**Comment by kyle-patterson** [comment]
Scheduled for 9/20 2p-4p PDT

**Comment by pkestikar** [comment]
Update:
Service name: ACS Calling

Key contact for this review: [@Prathmesh Kestikar](https://skype.visualstudio.com/SPOOL/_dashboards/dashboard/79511244-5783-4bce-accc-d455133e0b9d#)

Link to previous API version: ...

Description of the material to be reviewed/changed: 
A new feature video effects feature in the Web SDK, will enable devs to add Background Blur/Background Replacement feature in their calling apps.

Champion scenarios that briefly explain how developers will use your API: 
`
// Import packages
import { LocalVideoStream } from '@azure/communication-calling';
import { 
    BackgroundBlurEffect,
    BackgroundReplacementEffect
 } from '@azure/communication-calling-effects';
`

To start effects:
`
const localVideoStream = new LocalVideoStream(); // Or get it from the call instance

const effectsFeatureApi = localVideoStream.feature(Features.EffectsFeature);

const bgBlurEffect = new BackgroundBlurEffect({});

// Start effects
await effectsFeatureApi.startEffects([bgBlurEffect]);
`

To change effect type (example for background replacement with image):
`
let imageURL = 'https://backgroundimage.com/background1.jpg';
// NOTE: URL access would be the dev's responsibility (CORS issues will result in failure to apply effects).

// To change effect:
const bgReplacementEffect = new BackgroundReplacementEffect({ backgroundImageURL: imageURL });

// Start the new effects
await effectsFeatureApi.startEffects([bgReplacementEffect]);

// To change the background image:
imageURL = 'https://backgroundimage.com/background2.jpg';
await bgReplacementEffect.configure({ backgroundImageURL: imageURL });
`

Stopping effects:
`await effectsFeatureApi.stopEffects();`

If you want to create/use your own custom effects, do it the following way:
`
// Create your frame processing function, following the 'FrameCallback' type,
const frameCallback: FrameCallback = async (inputFrameCanvas, outputFrameCanvas) => {
    // Take frames from the inputFrameCanvas,
    // do your processing on it, tensorflow models to detect stuff, draw stuff, whatever
    // draw that image (frame) back on the outputFrameCanvas
};

// Create a Custom Effect Processor using the method 'createCustomVideoEffect' and passing in your frame callback:
const customEffect = createCustomVideoEffect(frameCallback);

// And then apply the effects in the SDK
await effectsFeatureApi.startEffects([customEffect]);

// To stop
await effectsFeatureApi.stopEffects();
`

Languages for this review. JavaScript (TypeScript )

Artifacts per language.
https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8/efa81a9c6ac546af9ea8f94615008cfc?diffRevisionId=db85d0b440e94933be368663bfa9221d&doc=False&diffOnly=True

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/dacb0840-98dc-a27a-eb91-f1ed390ab3e7) (MS INTERNAL ONLY)
