### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) Navigation Bar - UI Library [iOS, Android]

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4736]
Title composition:
[Team] - ACS Mobile UI Android
[Release Type] - Public Preview
[Feature to be reviewed] - NavigationBarViewData
[DevEx Internal / ARB] - DevEx

Service name: 
Key contact for this review: 
Link to previous API version: 

-Android[azure-communication-ui-calling (version 1.1.0) - apiview.dev](https://apiview.dev/Assemblies/Review/6c99f6dc8e134efa8e163d7d941519c7?revisionId=88de2ff2613c4ce1b197923f8f3b50cf&doc=False)

-iOS https://apiview.dev/Assemblies/Review/1ce5513aaca54e5c8e86f9c982ca3f78?diffRevisionId=9ff82842d8b24a8fb14bebc34160dabb&doc=False&diffOnly=False&revisionId=997b226003c84fa0979d6adb00730799

Description of the material to be reviewed/changed: Call Title and Sub Title to be configured
Champion scenarios that briefly explain how developers will use your API:
Contoso developer is able to set Call Title and Sub Title using public API

Languages for this review: Java
Artifacts per language.
JAVA: [azure-communication-ui-calling (version 1.1.0-beta.1) - apiview.dev](https://apiview.dev/Assemblies/Review/6c99f6dc8e134efa8e163d7d941519c7?revisionId=392175286f874666a92744a8ee1298f9). 

We encourage you to add the meeting notes over the story discussion to track visibility and status of the review. Please keep updated the story.

**Comment by garchiro7** [comment]
#scheduled

**Comment by kyle-patterson** [comment]
Scheduled for 9/15 2p-4p

**Comment by jpeng-ms** [comment]
this is latest api view for iOS: https://apiview.dev/Assemblies/Review/1ce5513aaca54e5c8e86f9c982ca3f78?revisionId=28ead49ea4464398bbd86b23e0035c74&doc=False

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/07a90840-98dc-a27a-997d-f1ed3540c2dd) (MS INTERNAL ONLY)
