### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) Calling Raw Video (JS)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4737]
Service name: ACS Calling Web
Key contact for this review: [@Harman Kharoud](https://skype.visualstudio.com/SPOOL/_backlogs/backlog/ACS%20Calling%20-%20Web/Features/?workitem=2958715#)
Link to previous API version: ...
Description of the material to be reviewed/changed: ..
Champion scenarios that briefly explain how developers will use your API:

For LocalVideoStream:
    /**  
     * OPTION 1:
    */
    const call = new Call();
    const lsv = new LocalVideoStream(deviceInfo);
    const rawStream = lsv.getMediaStream();
    // Modify rawStream to add any effects;
    lsv.setMediaStream(rawStream);
    call.startVideo(lsv);
    /**
     * OPTION 2:
    */
    const call new Call();
    const mediaStream = new MediaStream();
    mediaStream.canvasStream();
    const lsvWithMediaStream = new LocalVideoStream(mediaStream);
    call.startVideo(lsvWithMediaStream);

    
For RemoteVideoStream:
    const call = new Call();  
    const bob_participant = call.getParticipants()[0];
    const remoteVideoStream = bob_participant.videoStreams[0];
    const bob_rawRemoteVideoStream = await remoteVideoStream.getMediaStream();
    // Modify rawRemoteStream
    // render bob's modified stream;
Languages for this review. JavaScript/TypeScript
Artifacts per language. [@skype/spool-sdk - RawVideoStream - apiview.dev](https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8?diffRevisionId=38f96cae117b473098b13572afca581b&doc=False&diffOnly=True&revisionId=c2a1c690a4c54ae3ad44f807acb9fab2)

**Comment by garchiro7** [comment]
#scheduled

**Comment by kyle-patterson** [comment]
Scheduled for 9/19 2p-4p PDT

**Comment by hkharoud** [comment]
Updated:

Service name: ACS Calling Web
Key contact for this review:  [@Harman Kharoud](https://skype.visualstudio.com/SPOOL/_backlogs/backlog/ACS%20Calling%20-%20Web/Features/?workitem=2958715#) 
Link to previous API version:  ...
Description of the material to be reviewed/changed: ..
Champion scenarios that briefly explain how developers will use your API: 
```
For LocalVideoStream:

    /**  
     * FIRST OPTION:
    */
    const call = new Call();
    const lsv = new LocalVideoStream(deviceInfo);
    const rawStream = lsv.getMediaStream();
    // Modify rawStream to add any effects;
    lsv.setMediaStream(rawStream);
    call.startVideo(lsv);
    /**
     * SECOND OPTION:
    */
    const call new Call();
    const mediaStream = new MediaStream();
    mediaStream.canvasStream();
    const lsvWithMediaStream = new LocalVideoStream(mediaStream);
    call.startVideo(lsvWithMediaStream);

    
For RemoteVideoStream:
    const call = new Call();  
    const bob_participant = call.getParticipants()[0];
    const remoteVideoStream = bob_participant.videoStreams[0];
    const bob_rawRemoteVideoStream = await remoteVideoStream.getMediaStream();
    // Modify rawRemoteStream
    // render bob's modified stream;```




Languages for this review. JavaScript/TypeScript
Artifacts per language. [@skype/spool-sdk - RawVideoStream - apiview.dev](https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8?diffRevisionId=38f96cae117b473098b13572afca581b&doc=False&diffOnly=True&revisionId=c2a1c690a4c54ae3ad44f807acb9fab2)

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/79a60840-98dc-a27a-a9a1-f1ed386ea238) (MS INTERNAL ONLY)
