### ISSUE TITLE
Skip PR builds via commit message

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#474]
We should try to add a mechanism to allow skipping PR builds via a commit message, to avoid running unnecessary builds when a change is known to be very low-risk.  DevOps has a built-in feature to do this, but it only works for CI builds, not PR builds:

https://github.com/Microsoft/azure-pipelines-agent/issues/858#issuecomment-500874884
https://github.com/Microsoft/azure-pipelines-agent/issues/1270#issuecomment-486646508

We might be able to implement this using custom code which inspects the commit message and either stops the build or sets a flag which tells other steps to no-op.

**Comment by pllim** [comment]
Please, please, make this happen. I have been waiting for this.

**Comment by jhunkeler** [comment]
Yes, please implement this.

**Comment by mihaimircea** [comment]
This would be useful.

**Comment by chrisevans9629** [comment]
We really need this as well.

**Comment by StephenHodgson** [comment]
any update on this?

**Comment by weshaggard** [comment]
No we don't have much of an update here. We do have some potential ideas to get some level of this functionality but unfortunately we cannot do this completely on our side it would require changes from Azure DevOps which I don't see happening. 

cc @benbp

**Comment by mscheltienne** [comment]
I think MNE has a workaround that enables `[skip azp]` in a PR commit message to skip the Azure CI: https://github.com/mne-tools/mne-python/blob/948f0dc2745ba44d5add4faabc4090075bf1a770/azure-pipelines.yml#L16-L32

**Comment by weshaggard** [comment]
Thanks for the pointer. This is a similar workaround that we have been considering but just haven't implemented it yet.
