### ISSUE TITLE
Board Review: azquery (Monitor Query for Go)

### ISSUE THREAD

**Issue by gracewilcox** [Azure/azure-sdk#4743]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: SDK Team
* Main contacts: Grace Wilcox, Scott Addie
* Expected code complete date:
* Expected release date: GA November 2022

## About the Service 

* Link to documentation introducing/describing the service:
This SDK is already GA in tier one languages.
https://docs.microsoft.com/en-us/azure/azure-monitor/overview
https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/data-platform-metrics
https://docs.microsoft.com/en-us/azure/azure-monitor/logs/data-platform-logs
* Link to the service REST APIs: 
*[Logs](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/operationalinsights/data-plane/Microsoft.OperationalInsights/stable/v1/OperationalInsights.json)
[Metrics](https://editor.swagger.io/?url=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/ca0869b49176e7bc3866debbab9d32999661c4cb/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-01-01/metrics_API.json)
[Metrics Definitions](http://editor.swagger.io/?url=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/cf33826d06605cde127d2241e54dd6df55e9145f/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-01-01/metricDefinitions_API.json)
[Metrics Namespaces](https://editor.swagger.io/?url=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/cf33826d06605cde127d2241e54dd6df55e9145f/specification/monitor/resource-manager/Microsoft.Insights/preview/2017-12-01-preview/metricNamespaces_API.json)
* Link to GitHub issue for previous review sessions, if applicable: 
tier 1 language release
https://github.com/Azure/azure-sdk/issues/2783

## About the client library

* Name of the client library: azquery (Azure Monitor Log and Metrics Query)
* Languages for this review: Go

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Go

* APIView Link: https://apiview.dev/Assemblies/Review/b2356600c37347a0bb38ec187b1b84f1#azquery.Client
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/monitor/azquery#readme

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 9/26, 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/c3cb0840-98dc-ade4-8cc0-f1ed3df90007) (MS INTERNAL ONLY)
