### ISSUE TITLE
Board Review: Introducing Bot Framework ABS packages

### ISSUE THREAD

**Issue by tracyboehrer** [Azure/azure-sdk#4755]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Bot Framework Open Source
* Main contacts: "Tracy Boehrer" <trboehre@microsoft.com>, "John Taylor" <johtaylo@microsoft.com>
* Expected stable release date for this library:  Next quarter.  The Connector and Schema packages, separated from Bot Framework, are already being consumed by Power Virtual Agents.

## About the Service 

* Link to documentation introducing/describing the service: https://dev.botframework.com/, https://github.com/microsoft/botbuilder-dotnet
* Link to the service REST APIs: This is the Connector, Schema, and Streaming packages from Bot Framework SDK.  These were created using the Swagger files for ABS.
* Is the goal to release a Public Preview, Private Preview, or GA? GA, and for use by Power Virtual Agents, and potentially Teams and other Microsoft groups.

## About the client library

* Name of client library: Bot Framework SDK: Connector, Schema, and Streaming
* Link to library reference documentation: 
* Is there an existing SDK library? If yes, provide link:  https://github.com/microsoft/botbuilder-dotnet.  However, we are proposing just a subset of those packages and related samples.

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?  Communication with ABS.  This is just for the lower level packages from Bot Framework to communicate with ABS.  It is the foundation of Bot Framework, upon which anyone creating a bot would require as a start.
3. Who is the end-user of the application (the developer's customer)? Professional developer
4. What features of the API need to be explained in the sample so that someone could use this API in real app?
5. How does the **authentication** workflow look? We support various authentication scenarios, including OAuth.  There are samples that demonstrate its use, but simpler samples would be required that do no depend on higher level Bot Framework packages.
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1
    * [Link to library’s sample folder:](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore) 
* Champion scenario 2
    * Link to library’s sample folder:
* …
* Champion scenario n
    * Link to library’s sample folder:

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 

* Create a new resource
* Read the resource
* Modify the resource
* Delete the resource
* Error handling 
* Handling race conditions/concurrency issues

**Comment by kyle-patterson** [comment]
Scheduled for 9/29 2p-4p PDT

**Comment by tg-msft** [comment]
ApiView listings with the latest NuGet packages for:
- [Microsoft.Bot.Connector](https://apiview.dev/Assemblies/Review/ffe2f402c80d475b96e2d9a141384d81)
- [Microsoft.Bot.Schema](https://apiview.dev/Assemblies/Review/e246d237b3584ccfb1209ee5ac06eae0)
- [Microsoft.Bot.Streaming](https://apiview.dev/Assemblies/Review/e6518fb02c6744dca75893d8f7da593b)

**Comment by tracyboehrer** [comment]
> ApiView listings with the latest NuGet packages for:
> 
> * [Microsoft.Bot.Connector](https://apiview.dev/Assemblies/Review/ffe2f402c80d475b96e2d9a141384d81)
> * [Microsoft.Bot.Schema](https://apiview.dev/Assemblies/Review/e246d237b3584ccfb1209ee5ac06eae0)
> * [Microsoft.Bot.Streaming](https://apiview.dev/Assemblies/Review/e6518fb02c6744dca75893d8f7da593b)

These are the original packages.  However, we have a private GitHub repository that is being used to stage the code.  Unlike the BF SDK versions, autorest is used to generate the models, as well as a number of other changes.  

We would need to add interested parties to that repository manually since it's not public.

**Comment by tg-msft** [comment]
Can you upload APIs from the new private packages to the internal only https://apiview.dev before the meeting so folks can take a look?

**Comment by tracyboehrer** [comment]
[Connector](https://apiview.dev/Assemblies/Review/808372b22a934b50838b6c36b06e11c6)
[Streaming](https://apiview.dev/Assemblies/Review/c3ef9f4303004d63bb48f813f324440b)

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/3f890840-98dc-ade4-bed5-f1ed404a7dc0) (MS INTERNAL ONLY)
