### ISSUE TITLE
SDK treatment of readOnly properties

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk#4772]
We recently had a team come to the Breaking Changes review board that wanted to change a property of a schema in a request body from "readOnly: true" to "readOnly: false" -- allowing users to pass in a value to be set rather than the service choosing it for them. This was flagged as a breaking change by our tooling, and the team questioned why this was not allowed.
 
At the REST API level, this should be non-breaking -- as long as service previously rejected a request that contained this property, as stated the OpenAPI specification, or rejected a request with a different value than present on the server, as the Azure REST API Guidelines recommend.
 
But the Azure SDKs (I believe this is true for at least DotNet, Java, Python, JavaScript, and Go) do some special processing on request body fields that are marked `readOnly: true` -- they silently drop them when serializing an object passed by the user into the request body. So the user "doesn't need to worry" about readOnly fields -- the SDK takes care of it for them.  This behavior was introduced into the Azure SDKs several years back at the request of ARM, because ARM services typically fail requests containing a readOnly property. 
 
This behavior of the SDKs might seem like a nice feature, but it creates a problem for the case of changing a property from readOnly: true to readOnly: false. The problem is that application behavior could change if a user updates to a new version of the SDK that no longer silently drops the now writeable property from the request body. If that property contains a different value than present on the server, the value is updated which is a change from the prior behavior.
 
We could not change this behavior in existing SDKs without the risk of breaking customers, but we should consider whether to carry this forward into new SDKs. At least one SDK Architect (Jeffrey) considers silently dropping properties from an input passed by the user to be the kind of "magic" that should be avoided in our SDKs. This “magic” causes customers to think they are setting some resource properties which are NOT actually applied to the resource if the property happens to be read-only; customers will perceive this as data loss when using our SDKs. And this behavior is contrary to our goal for DPG to be resilient to changes that are non-breaking at the REST API level.
 
One argument for keeping this behavior is that it makes "round-tripping" easier for services that reject any request containing a readOnly property as prescribed by OpenAPI. But round-tripping can be done without dropping the readOnly properties if the service allows them provided that the values don't differ from what is on the server, as recommended by the Azure API Guidelines. But we would have to assess the potential impact to services that strictly disallow readOnly fields in a request, especially the ARM services, and whether we could mitigate that somehow.

**Comment by johanste** [comment]
I would like to see before and after code samples that tries to round-trip data before we make a change to this behavior. Pragmatically speaking, what we have has worked pretty darn well (IMHO). If the change from read-only to read-write is behind a new API version, where is the problem here? This kind of minor behavioral change in a new API Version is expected.

Ultimately, if the user wants to change the value of a read-only property, the question is just where their mistake will be caught – because the service doesn’t allow it. And thus whatever the customer tried to accomplish simply won’t be possible.

**Comment by KrzysztofCwalina** [comment]
Also, are such properties read-only in our "V1" SDKs? If yes, the user would not be able to change the value and presumably "If that property contains a different value than present on the server, the value is updated which is a change from the prior behavior." would never happen.

**Comment by mikekistler** [comment]
For DPG v1 we leave it to users to construct the JSON, so there's nothing preventing them from sending a readOnly property to the service with any value they choose. I should have clarified that by "our current SDKs" I meant our current SDKs that support models.

**Comment by kyle-patterson** [comment]
Scheduled for 9/21 2p-4p PDT

**Comment by kyle-patterson** [comment]
Rescheduled for 10/5 2p-4p PDT

**Comment by joheredi** [comment]
### Typescript

* Rest Level Client (RLC) will send read-only properties in the round-trip scenario.
* Input model type definitions don't include any read-only properties

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/edc30840-98dc-ade4-3155-f1ed452727fc) (MS INTERNAL ONLY)

**Comment by KrzysztofCwalina** [comment]
.NET

Input model type definitions will not have properties marked in CADL as read-only (i.e. properties that should not be send to the server)
Roundtrip and output models will have these properties exposed as getter-only properties, and the property value will not be included when sending the model back to the server.
If for whatever reason a setter already is present in such property, we might obsolete it and/or add client validation to warn the user that such property will be excluded when sent to the server.

**Comment by JeffreyRichter** [comment]
Go/C/C++/Rust

These SDKs will basically ignore property attributes like readonly, required, and nullable and therefore be immune to any changes made by the service or its API contract. This makes the behavior between code gen between models and no models identical. In all these languages, the structure fields are always read/write anyway. We might add to a field's docs whether it is read-only or not and this may change based on service/swagger changes but we would not consider this breaking as it is just docs. We also use the same single model for JSON merge patch too.

**Comment by mikekistler** [comment]
Closing as completed.
