### ISSUE TITLE
Board Review: WebPubSubClient

### ISSUE THREAD

**Issue by zackliu** [Azure/azure-sdk#4790]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team:Azure Web PubSub Service (vscsignalr@microsoft.com)
* Main contacts: Chenyang Liu(chenyl@microsoft.com)
* Expected code complete date: Oct 2022
* Expected release date: TBA

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/azure/azure-web-pubsub/
* Link to the service REST APIs: It's not a REST-style client. Already discussed with API board and API review is not applicable in this case.
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/4506

## About the client library

* Name of the client library: WebPubSubClient
* Languages for this review: C#

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/39b74bed588e407ca3b06411bf7760e3
* Link to Champion Scenarios/Quickstart samples: https://github.com/zackliu/azure-sdk-for-net/tree/wpspubsubclient/sdk/webpubsub/Azure.Messaging.WebPubSub.Client/samples

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/1e2fc418c83c4074ac63997476b16cb1
* Link to Champion Scenarios/Quickstart samples:https://github.com/zackliu/azure-sdk-for-js/tree/webpubsub/sdk/web-pubsub/web-pubsub-client/samples/v1/typescript

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled for 10/10 4p-6p PDT

**Comment by ronniegeraghty** [comment]
@zackliu If there are any updates to the APIviews and Champion scenarios before the follow up meeting on 10/26 please add them to this issue.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/15be0840-98dc-ade4-d4b5-f1ed571c32bc) (MS INTERNAL ONLY)
