### ISSUE TITLE
Board Review: azeventhubs

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk#4802]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Go SDK team
* Main contacts: @richardpark-msft 
* Expected code complete date: (TBD)
* Expected release date: (TBD)

## About the Service 

* Link to documentation introducing/describing the service: [Azure Event Hubs](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-about)
* Link to the service REST APIs: N/A (AMQP API)

## About the client library

* Name of the client library: `github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs` (locally, `azeventhubs`)
* Languages for this review: Go

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Go

* APIView Link: [apiview for azeventhubs](https://apiview.dev/Assemblies/Review/8245669789dd4453bea087a9afaf2705)

#### Link to Champion Scenarios/Quickstart samples: 

* Sending events: [link](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/example_producing_events_test.go#L14)
* Receiving event, basic: [link](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/example_consuming_events_test.go#L15)
* Receiving events, using a processor: [link](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/example_processor_test.go#L17)

## Thank you!

You're welcome.

**Comment by kyle-patterson** [comment]
Scheduled for 9/14 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/e5bf0840-98dc-a27a-12e8-f1ed353f9e71) (MS INTERNAL ONLY)
