### ISSUE TITLE
Change Request: Error Taxonomy for General Guidelines

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-sdk#483]
Java and Python error taxonomies are fairly similar. On the TypeScript side, I am willing to adopt a similar error taxonomy (while JS folks don't have much rigor around exceptions and exception hierarchies, worst case seems to be they just ignore it). Given we are so close to alignment across languages, maybe we can see if we can have a general guideline around which error classes we have.

I don't think we can agree on names necessarily, and inheritance isn't a thing in all languages, but it still seems good to align on the error classes.

**Comment by adrianhall** [comment]
BOARD DECISION:

We agree that we should have a standardized error taxonomy, but we need to understand how to do this in each language (particularly the hierarchy).  @johanste, @schaabs, and @bterlson will meet to discuss.

**Comment by adrianhall** [comment]
BOARD DECISION: This is closed now.
