### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) Cross platform messaging (.net)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4835]
Service name: Cross-platform Messaging
Key contact for this review:  Gloria Li ([geling.li@microsoft.com](mailto:geling.li@microsoft.com))
Link to previous API version: 
Previously the endpoint ("/chat/messages:send") was part of the chat gateway: https://github.com/Azure/azure-rest-api-specs/blob/9b43f4a756a79e05b3bb1dc6bd3ed7a8fd132969/specification/communication/data-plane/Chat/preview/2022-04-21-preview8/communicationserviceschat.json
Now we are moving that messaging endpoint to the Cross-platform messaging service
Description of the material to be reviewed/changed: Add a new messaging endpoint to allow Contoso to send fire and forget/ notification messages to external messaging platforms (e.g. WhatsApp).
Champion scenarios that briefly explain how developers will use your API:
            var messagingClient = new MessagingClient("<connection string>");
            // send a text message
            var options = new SendMessageOptions("d8fbaac7-c949-4bf1-8ba9-29b467d97547", "+1(604)xxx-xxxx", "hiiii");
            SendMessageResponse response = await messagingClient.SendMessageAsync(options);

            // send a media message
            options = new SendMessageOptions("d8fbaac7-c949-4bf1-8ba9-29b467d97547", "+1(604)xxx-xxxx", new Uri("http://image.com/"));
            response = await messagingClient.SendMessageAsync(options);

            // send a template message
            MessageTemplate template = new MessageTemplate("appiontment_reminder", "en", new List<string> { "friday", "10am" });
            options = new SendMessageOptions("d8fbaac7-c949-4bf1-8ba9-29b467d97547", "+1(604)xxx-xxxx", template );
            response = await messagingClient.SendMessageAsync(options);
Languages for this review: .NET
Artifacts per language: https://apiview.dev/Assemblies/Review/06657e2f6b3a40d0b538e04a675fcd6d

**Comment by kyle-patterson** [comment]
Scheduled for 9/22 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/dedd0840-98dc-a27a-9111-f1ed3ac6aba1) (MS INTERNAL ONLY)
