### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) Calling Native SDK RawOutgoingVideo (iOS)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4845]
Service name: Azure Communication Calling SDK
Key contact for this review: [@Luciano Passos Almeida](https://skype.visualstudio.com/SPOOL/_workitems/edit/2986838#) , [@Bob Gao](https://skype.visualstudio.com/SPOOL/_workitems/edit/2986838#) 
Link to previous API version: 
Description of the material to be reviewed/changed: SDK Public API  
Champion scenarios that briefly explain how developers will use your API: https://github.com/lucianopa-msft/azure-docs/blob/lucianopa/raw-outgoing-video-ios/articles/communication-services/quickstarts/voice-video-calling/includes/raw-media/raw-media-access-ios.md
Languages for this review: Objective-C/Swift
Artifacts per language.
https://apiview.dev/Assemblies/Review/aa70a237fdde4c658827f89b0aab1947/3a0f2bc05b33462f8e5887df2503687c?diffRevisionId=95f26536ada946c1a627a7cfc6538ce3&doc=False&diffOnly=True

**Comment by kyle-patterson** [comment]
Scheduled for 10/3 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/fc940840-98dc-ade4-018f-f1ed436c4510) (MS INTERNAL ONLY)
