### ISSUE TITLE
Board Review: Personalizer Client for Python

### ISSUE THREAD

**Issue by sharathmalladi** [Azure/azure-sdk#4847]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Azure Personalizer
* Main contacts: @sharathmalladi 
* Expected code complete date: 09/30/2022
* Expected release date: 11/07/2022

## About the Service 

* Link to documentation introducing/describing the service: This is a new Python SDK for beta release.
  * [Model Put API](https://microsoft.sharepoint.com/:w:/t/personalizr/Ed0dN7HgEF9EhKj9Bx5BRfkBfu9Q6o9Fw_SeFW9X3F96EQ?e=ZP9W2X&CID=D24A1141-04ED-43CA-8278-74C8AC7BE91B&wdLOR=cC1B79B0D-2E02-47B5-ACAD-32C62A0B2799)
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/blob/e24bbf6a66cb0a19c072c6f15cee163acbd7acf7/specification/cognitiveservices/data-plane/Personalizer/preview/2022-09-01-preview/Personalizer.json
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/4583

## About the client library

* Name of the client library: azure-ai-personalizer
* Languages for this review: Python

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Python

* APIView Link: [ApiView Link](https://apiview.dev/Assemblies/Review/cabb174a5027407d84b4d64dd6999b11)
* Link to Champion Scenarios/Quickstart samples: [Samples Link](https://github.com/sharathmalladi/azure-sdk-for-python/tree/personalizersdk2/sdk/personalizer/azure-ai-personalizer/samples)

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by ronniegeraghty** [comment]
Scheduled for 10/12/2022, 2:05PM - 4:00PM

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/28dd0840-98dc-ade4-3e55-f1ed4a811e64) (MS INTERNAL ONLY)
