### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - Video + ScreenShare GA, activeTab API

### ISSUE THREAD

**Issue by akania** [Azure/azure-sdk#4848]
## Contacts and Timeline

Service name: ACS Calling Web
Key contact for this review: Clarence Sandjon
Link to previous API version: ...
Description of the material to be reviewed/changed: ..
Champion scenarios that briefly explain how developers will use your API:

### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by csandjon** [comment]
Detect when SDK is active in multiple tabs:
Usage:
- The following code snippet shows how contoso can check if the SDK is active in multiple tabs of a browser and also listen for changes.

```javascript
const callClient = new CallClient();
const isSdkActiveInAnotherTab = callClient.feature(SDK.Features.BrowserInfo).isSdkActiveInAnotherTab;
...
callClient.feature(SDK.Features.BrowserInfo).on('isSdkActiveInAnotherTabChanged', () => {
    // Callback();
});
...
callClient.feature(SDK.Features.BrowserInfo).off('isSdkActiveInAnotherTabChanged', () => {
    // Callback();
});
```

api description:
https://skype.visualstudio.com/SCC/_git/client_calling_spool-native/pullrequest/671845?view=discussion&_a=files&path=/sdk/web/docs/BrowserInfo/BrowserInfo.md

api view diff:
[@skype/spool-sdk - Detect when SDK is active in multiple tabs - apiview.dev](https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8?diffRevisionId=38f96cae117b473098b13572afca581b&doc=False&diffOnly=False&revisionId=b8321f97dd84475aa36a38a77e590969)

**Comment by csandjon** [comment]
Publish screen sharing + one video local streams simultaneously:
Usage:

The following code snippet shows how contoso can check if the local video is on or off, and also listen for changes.
```js
// Check if local video is on or off
call.isVideoOnn;
...
call.on('isVideoOnChanged', () => {
    // Callback();
});
...
call.off('isVideoOnChanged', () => {
    // Callback();
});
```
api description:
https://skype.visualstudio.com/SCC/_git/client_calling_spool-native/pullrequest/683510?_a=files&path=/sdk/web/docs/LocalVideo_And_ScreenSharing/LocalVideo.md

api view diff:
[@skype/spool-sdk - Detect when SDK is active in multiple tabs - apiview.dev](https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8?diffRevisionId=38f96cae117b473098b13572afca581b&doc=False&diffOnly=False&revisionId=b8321f97dd84475aa36a38a77e590969)

**Comment by kyle-patterson** [comment]
Scheduled for 9/20 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/bea00840-98dc-a27a-92dd-f1ed393dd2b0) (MS INTERNAL ONLY)
