### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - Audio Stream Volume API

### ISSUE THREAD

**Issue by akania** [Azure/azure-sdk#4849]
## Contacts and Timeline

Service name: ACS Calling Web
Key contact for this review: Ankesh Bhoi
Link to previous API version: ...
Description of the material to be reviewed/changed: ..
Champion scenarios that briefly explain how developers will use your API:

### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by ankeshni** [comment]
Raw audio stream volume indicator:
use case: enable Contoso to be able to display volumes of local and remote audio streams to display volume indicators like this one:
https://acs-rp.azurewebsites.net/ankeshbhoi/2920839_microphone_and_speaker_indicator/index.html

api description:
https://skype.visualstudio.com/SCC/_git/client_calling_spool-native/pullrequest/683778?_a=files&path=/sdk/web/docs/VolumeIndicator/volumeIndicator.md
 
api view diff:
https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8/979e48698490493b90820d3543c7116d?diffRevisionId=181c97e6b40b47248f236eae2153a266&doc=False&diffOnly=True

**Comment by kyle-patterson** [comment]
Scheduled for 9/20 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/bea00840-98dc-a27a-92dd-f1ed393dd2b0) (MS INTERNAL ONLY)
