### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - MediaStats, LiveStream stats, Video Constraints

### ISSUE THREAD

**Issue by akania** [Azure/azure-sdk#4850]
## Contacts and Timeline

Service name: ACS Calling Web
Key contact for this review: Enrico Huang
Link to previous API version: ...
Description of the material to be reviewed/changed: ..
Champion scenarios that briefly explain how developers will use your API:

### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by enricohuang** [comment]
Video Constraint Usage:

```
const callOptions = {
    videoOptions: {
        localVideoStreams: [...],
        constraint: {
            send: {
                resolution: {
                   max: 240 
                } 
            }
        }
    },
    audioOptions: {
        muted: false
    }
};
 
//USAGE EXAMPLE 
// make a call
this.callAgent.startCall(identitiesToCall, callOptions);
// join a group call
this.callAgent.join({ groupId }, callOptions);
// accept an incoming call
this.incomingCall.accept(callOptions) 
```

api description: https://skype.visualstudio.com/SCC/_git/client_calling_spool-native/pullrequest/673773?_a=files&path=/sdk/web/docs/MediaConstraint/MediaConstraint.md

apiview diff: https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8?diffRevisionId=181c97e6b40b47248f236eae2153a266&doc=False&diffOnly=False&revisionId=15946194a84f41339fbee445dafb830c

**Comment by kyle-patterson** [comment]
Scheduled for 9/20 2p-4p PDT

**Comment by enricohuang** [comment]
**LiveStream stats**

Livestream stats provides a way for SDK users to get playback stats info.
They can utilize the information for debug purpose, data analysis, or just show stats info on the UI.

Usage:
```
const liveStreamFeature = Call.feature(Features.LiveStreamingCall);
const collector = liveStreamFeature .createCollector({
    aggregationInterval: 10,
    dataPointsPerAggregation: 6
});
collector.on('sample', data: LiveStreamStatsSample => {
    for (const [streamId, stats] of Object.entries(data)) {
        console.log(`stream id = ${streamId} download bitrate = ${stats.downloadBitrate}`);
    }
});
```
api description: https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8?diffRevisionId=8aa8ee51c62b44b9a724a5247b7555c0&doc=False&diffOnly=False&revisionId=7b0387ef3b03417293e345d3533139dd

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/bea00840-98dc-a27a-92dd-f1ed393dd2b0) (MS INTERNAL ONLY)

**Comment by enricohuang** [comment]
update apiview after ARB

MediaStats:
https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8?diffRevisionId=181c97e6b40b47248f236eae2153a266&doc=False&diffOnly=False&revisionId=92569a3514e243a79e36c87820946f3e

Video constraint:
https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8?diffRevisionId=db85d0b440e94933be368663bfa9221d&doc=False&diffOnly=False&revisionId=bed22cbbb92749d6b245799902ae90f8

LiveStream Stats:
https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8?diffRevisionId=8aa8ee51c62b44b9a724a5247b7555c0&doc=False&diffOnly=False&revisionId=83fbd76b991248758ad34047c6a6917d
