### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) Call Recording Status (Android & iOS)

### ISSUE THREAD

**Issue by mbakalov** [Azure/azure-sdk#4861]
## Background

Currently Azure Communication Calling SDKs already expose `bool isRecordingActive` property and a `onIsRecordingActiveChanged` event. This allows client apps to e.g., show "Recording started..." banner to users.

However, the bool property makes it impossible to distinguish between various actual states of the recording lifecycle: "NotStarted", "Started", "Paused", "Ended".

This new API introduces a new enum for `RecordingState` and events for it.

## Contacts and Timeline

* Responsible service team: ACS Call Automation Media
* Main contacts: @chrwhit
* Expected code complete date: TBD
* Expected release date: TBD

## About the Service 

* Link to documentation introducing/describing the service: [Call Recording API Quickstart](https://learn.microsoft.com/azure/communication-services/quickstarts/voice-video-calling/call-recording-sample)
* Link to the service REST APIs: [communicationservicescallingserver.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/CallingServer/preview/2021-08-30-preview/communicationservicescallingserver.json)

## About the client library

* Name of the client library: Azure Communication Calling SDK
* Languages for this review: Android & iOS

### Android

* APIView Link: https://apiview.dev/Assemblies/Review/918d65cb24c94881808cab55548eb186/c855dae7401c4d449ff4bab7397ea371?diffRevisionId=342cd082ae244dfba8308ca1cdc0150b&doc=False&diffOnly=True
* Link to Champion Scenarios/Quickstart samples: TBD

### iOS

* APIView Link: https://apiview.dev/Assemblies/Review/bbe0cc58c12c406997a52650be4975fa/68eb89f66df54eacaa335e11c5a24ceb?diffRevisionId=0e9e0b1262044a1bb29e003611a4281c&doc=False&diffOnly=True
* Link to Champion Scenarios/Quickstart samples: TBD

**Comment by kyle-patterson** [comment]
Scheduled for 10/3 2p-5p PDT

**Comment by mbakalov** [comment]
## Feature Overview

Introduce a new recording state for when the recording is paused. Currently when the recording is paused the state returned is inactive/not recording. The SDK also reports inactive when there is no recording happening. It is impossible for the end user to know if there is no recording, or if the recording is paused.

## Flow Diagrams
![image](https://user-images.githubusercontent.com/46465618/193656003-f7f14f6c-5ddd-4ed4-8b60-499dda73a8c7.png)

![image](https://user-images.githubusercontent.com/46465618/193656135-0c0558ed-88e9-4632-b691-ccf84702e2ef.png)

\* On the initial start recording the status of the recording bot will be “inactive” until the bot actually starts recording. This state is unnecessary, so we will not send an update for it. Immediately after the first status update for the recording bot a second “active” status will be sent when the recording begins. This is when we will send the RecordingsUpdated event. 

** If the status has not changed then the update recording status step will not be required. 

## API Change

### `RecordingCallFeature`

* `RecordingsUpated` **Event**: New Event triggers when a recording is started or stopped. Event calls callback with list of recordingInfos. 

* `Recordings` **Property**: A list of all current recordings, as RecordingInfo. The recordingStateChanged event on the RecordingInfo will be used to get pause/resume state for recordings. ***Recording does not currently support multiple concurrent recordings, but will in the future, so we have added an array of recordings states instead of a single state.** 

```csharp
RecordingCallFeature 
{ 
    // Existing members 
    isRecordingActive: bool; 
    isRecordingActiveChanged: event; 

    // New Members 
    recordings: RecordingInfo[]; 
    recordingsUpdated: event<RecordingsUpdated>; 
} 

// New Object 
RecordingsUpdated 
{ 
    added: RecordingInfo,  // When a recording start 
    removed: RecordingInfo // When a recording ends 
} 
```

### `RecordingState` Enum

New enum. Used to indicate state of a recording. Contains states: Started, Paused, Ended. 
```csharp
{ 
    Started,	// Recording is in progress 
    Paused,	// Recording is paused 
    Ended	// Recording has ended 
}
```

### `RecordingInfo` Class

New Class. Contains the state of an existing recording. This initial implementation of RecordingInfo does not contain the identifier for the recording as we currently only allow one recording at a time, though adding the identifier may be something that we want to do. 

```csharp
{ 
    state: RecordingState, 
} 
```

## Customer Scenarios 
|Scenario|Behavior|
|--|--|
|Contoso wants to use Pause/Resume for recordings. |Contoso can subscribe to the RecordingsUpdated event. Customer will receive all recording Start/End/Pause/Resume events. |

**Comment by xumo-95** [comment]
API usage:

iOS

```swift
// subscribe to RecordingsUpdated event
public func recordingCallFeature(_ recordingCallFeature: RecordingCallFeature, didUpdateRecordings args: RecordingsUpdatedEventArgs) {

        // get updated recording
        let addedRecording = args.addedRecording

        // get state of updated recording
        let state = addedRecording.state

	// get current recordings
	let recordings = recordingCallFeature.recordings
 }
```

Android

```java
// add listener to OnRecordingsUpdated
public void addOnRecordingsUpdatedListener(Call call, RecordingsUpdatedListener listener) {
	try {
            RecordingCallFeature recordingCallFeature = call.feature(Features.RECORDING);
            recordingCallFeature.addOnRecordingsUpdatedListener(listener);
        } catch (Exception e) {
            e.printStackTrace();
        }
}

// subscribe to RecordingsUpdated event
public void onRecordingsUpdated(RecordingsUpdatedEvent args)  {
	
	// get updated recording
	RecordingInfo addedRecording = args.getAddedRecording();

	// get state of updated recording
        RecordingState recordingState = addedRecording.getState();
}	

// get current recordings
public RecordingInfo[] getRecordings(Call call) {
        try {
            RecordingCallFeature recordingCallFeature = call.feature(Features.RECORDING);
            return recordingCallFeature.getRecordings();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
}
```

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/fc940840-98dc-ade4-018f-f1ed436c4510) (MS INTERNAL ONLY)
