### ISSUE TITLE
Board Review: Azure.Analytics.Purview.Share client library

### ISSUE THREAD

**Issue by anniruddh** [Azure/azure-sdk#4870]
Requesting review of Purview Share client library. This is a new sub-package of [Purview](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/purview).
	
## Contacts and Timeline
	
* Responsible service team: Purview Share
* Main contacts: rajarrar@microsoft.com, ankoppal@microsoft.com, sidontha@microsoft.com
* Expected code complete date: 9/30/2022
* Expected release date: 10/7/2022
	
## About the Service 
	
* Link to documentation introducing/describing the service: [Purview Share](https://learn.microsoft.com/en-us/azure/purview/how-to-share-data)
* Link to the service REST APIs: [Share Data Plane](https://learn.microsoft.com/en-us/rest/api/purview/sharedataplane/sent-shares)
* Link to GitHub issue for previous review sessions, if applicable:  N/A
	
	
## About the client library

* Name of the client library: Azure.Analytics.Purview.Share
* Languages for this review: .NET
	
## Artifacts required (per language)
	
Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**
	
### .NET
	
* APIView Link: [.NET_APIView](https://apiview.dev/Assemblies/Review/887ede3c21264d2e99075831b04a86a7)
* Link to Champion Scenarios/Quickstart samples: [Share Samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/purview/Azure.Analytics.Purview.Share/tests/Samples)

### Java

* APIView Link: [JAVA_APIView](https://apiview.dev/Assemblies/Review/bc8ee12ba1574b69b9945f799f7c2c82)
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link: [PYTHON_APIView](https://apiview.dev/Assemblies/Review/37d315c890064880abf4c0551ff07931)
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link: [JS_APIView](https://apiview.dev/Assemblies/Review/d03e24fdc2794f8284d618a3708ccdcf)
* Link to Champion Scenarios/Quickstart samples:

**Comment by ronniegeraghty** [comment]
@kyle-patterson Drafted

**Comment by ronniegeraghty** [comment]
Scheduled for 10/13/2022, 2:05PM - 4:00PM

**Comment by kyle-patterson** [comment]
Rescheduled for 10/13 10a-12p PDT

**Comment by anniruddh** [comment]
Just confirming the updated time is 10:05a - 12:00p on 10/13.

**Comment by ronniegeraghty** [comment]
Confirming the updated time is 10:05AM - 12:00PM on 10/13

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/55b40840-98dc-ade4-4d86-f1ed4b659462) (MS INTERNAL ONLY)
