### ISSUE TITLE
Board Review: AnomalyDetector

### ISSUE THREAD

**Issue by jr-MS** [Azure/azure-sdk#4884]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: **Anomaly Detector**
* Main contacts: Louise Han; **Chunlei Wang**
* Expected code complete date: **10/15/2022**
* Expected release date: **11/1/2022**

## About the Service 

* Link to documentation introducing/describing the service: https://learn.microsoft.com/en-us/azure/cognitive-services/anomaly-detector/overview
* Link to the service REST APIs: https://westus2.dev.cognitive.microsoft.com/docs/services/AnomalyDetector-v1-1-preview-1/operations/DetectAnomaly
* Link to GitHub issue for previous review sessions, if applicable:  NA

## About the client library

* Name of the client library: **AnomalyDetector**
* Languages for this review: **JAVA, JS/TS, .NET, Python**

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

Language | PR link
-- | --
.NET | https://github.com/Azure/azure-sdk-for-net/pull/31837
JS/TS | https://github.com/Azure/azure-sdk-for-js/pull/23517
Python | https://github.com/Azure/azure-sdk-for-python/pull/26783
JAVA | https://github.com/Azure/azure-sdk-for-java/pull/31552

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/254f32d27d48480ba334418e45eb1726 
* Link to Champion Scenarios/Quickstart samples: https://learn.microsoft.com/en-us/azure/cognitive-services/anomaly-detector/quickstarts/client-libraries-multivariate?pivots=programming-language-csharp

### Java

* APIView Link: 
* Link to Champion Scenarios/Quickstart samples: https://learn.microsoft.com/en-us/azure/cognitive-services/anomaly-detector/quickstarts/client-libraries-multivariate?pivots=programming-language-java

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/15eb0388417545a0994a84913b4fc3ce
* Link to Champion Scenarios/Quickstart samples: https://learn.microsoft.com/en-us/azure/cognitive-services/anomaly-detector/quickstarts/client-libraries-multivariate?pivots=programming-language-python
  
### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/49d6966dc650470a8904682cab0e93a4
* Link to Champion Scenarios/Quickstart samples: https://learn.microsoft.com/en-us/azure/cognitive-services/anomaly-detector/quickstarts/client-libraries-multivariate?pivots=programming-language-javascript

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by ronniegeraghty** [comment]
Scheduled 10/18/2022 4:05PM - 6:00PM PST
