### ISSUE TITLE
Board Review: Event Grid new system events

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk#4893]
## Contacts and Timeline

* Responsible service team: Healthcare, APIM
* Main contacts: @JoshLove-msft 
* Expected code complete date: 10/6
* Expected release date: 10/13

## About the Service 

* Link to the service REST APIs: 
https://github.com/Azure/azure-rest-api-specs/pull/21157
https://github.com/Azure/azure-rest-api-specs/pull/20871

### .NET

* APIView Link: To be added

### Java

* APIView Link: To be added

### Python

* APIView Link: N/A
  
### TypeScript

* APIView Link: To be added

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by kyle-patterson** [comment]
Scheduled 10/6 2p-4p PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/42d70840-98dc-ade4-f8e6-f1ed4991d100) (MS INTERNAL ONLY)
