### ISSUE TITLE
A script that pulls release notes into yml does not see different level of bullets

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk#4949]
See, for example, this .yml:
https://github.com/Azure/azure-sdk/blob/000bfda0b100192733b7ca2626465734a40be225/_data/releases/2022-10/cpp.yml#L74-L83

And compare it to the original .md, which has two different levels of bullets:
https://github.com/Azure/azure-sdk-for-cpp/blob/0d6624fdaaeaf5afed2684014021c19d2b876581/sdk/storage/azure-storage-files-datalake/CHANGELOG.md?plain=1#L17-L26

**Comment by weshaggard** [comment]
I suspect it this is a bug at https://github.com/Azure/azure-sdk/blob/main/eng/scripts/Generate-ReleaseNotes.ps1#L85 which trims the lines. We might need to correctly remove the spacing from the from instead of just trimming everything.

**Comment by antkmsft** [comment]
Here is the latest example - bullets nesting is lost, "Other Changes" section is lost:
https://github.com/Azure/azure-sdk/blob/c7c10549eb6f3df34199d0eb86cd06f07875955d/_data/releases/2023-02/cpp.yml#L10-L39 vs https://github.com/Azure/azure-sdk-for-cpp/blob/6a53e4122f74937ff81ef736407128c548e4417c/sdk/core/azure-core/CHANGELOG.md?plain=1#L15-L57
