### ISSUE TITLE
Board Review: package name for ElasticSan management plane SDK

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk#4950]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Storage
* Main contacts: @blueww, @ArthurMa1978, @adarshv98, @yuemlu

## About the Service 

* Link to documentation introducing/describing the service: [Cloud SAN Strategy](https://microsoftapc-my.sharepoint.com/:w:/g/personal/pprahalad_microsoft_com/EYRO1vapxxVAisbPdLzU9FwBpPcrd8MvxeX7Y9MyXaiPEQ?wdOrigin=TEAMS-ELECTRON.p2p.mw&wdExp=TEAMS-TREATMENT&wdhostclicktime=1640235930463&isSPOFile=1), [ElasticSAN design](https://microsoft.sharepoint.com/:w:/t/AzureStorage/EV3yeGDiDw5OhxhAxN_V7WIBfCfdoeaScjJxhyERlHtXPQ?e=UwIcQV&wdOrigin=TEAMS-ELECTRON.p2p.bim&wdExp=TEAMS-TREATMENT&wdhostclicktime=1636563076335&isSPOFile=1)
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs-pr/tree/main/specification/elasticsan/resource-manager
* Is the goal to release a Public Preview, Private Preview, or GA? 
Yes, for Public Preview.

## About the client library

* Name of client library: 

  - .Net: `Azure.ResourceManager.ElasticSan`
  - Java: `com.azure.resourcemanager.elasticsan`
  - Python: `azure.mgmt.elasticsan`
  - Go: `sdk/resourcemanager/elasticsan/armelasticsan`
  - JS: `@azure/arm-elasticsan`

**Comment by ronniegeraghty** [comment]
Working on offline review

**Comment by ArthurMa1978** [comment]
Name `ElasticSan` got approved, we can start the release
