### ISSUE TITLE
Change Request: DataFactoryExpression object for all languages

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk#4964]
For a detailed explanation of the problem and what dotnet was exploring for their solution see this issue https://github.com/Azure/azure-sdk-for-net/issues/31507.

This type is used in synapse data plane, synapse mgmt plane, and datafactory mgmt plane.

There are a few considerations that we might want to align on across languages.

1. Do we want to have a consistent type across languages or across strongly typed langauges?
2. Where should this type live? Azure.Core, Azure.Data.Common?

[dotnet apiview](https://apiview.dev/Assemblies/Review/dcdf37cd89c147a5b7f10d9d7e249a93/58e203e58908457a9769bc9c6adc1cd2?diffRevisionId=0738a0df1d634f9699920f205c8f8707&doc=False&diffOnly=True)

**Comment by ronniegeraghty** [comment]
Drafted

**Comment by ronniegeraghty** [comment]
Scheduled: Oct 22nd, 2022, 2:05PM - 4:00PM PST.

**Comment by ronniegeraghty** [comment]
@m-nash please attach any and all APIviews and champion scenarios to this issue before the day of the review session.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/77a80840-98dc-ade4-5621-f1ed571d15f3) (MS INTERNAL ONLY)
