### ISSUE TITLE
Change Request: Add dependent azure library info for Telemetry policy

### ISSUE THREAD

**Issue by AmyL219** [Azure/azure-sdk#4975]
## The Basics

* Which design guideline is affected?
The Telemetry policy guideline:
https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy

* Which target languages are affected?
All languages 

* Describe the change:
In the Telemetry format `[<application_id> ]azsdk-<sdk_language>-<package_name>/<package_version> <platform_info>`
We need to consider the Telemetry information appended from dependent libraries. For example, if we re-wrote `AzCopy` in javaScript using the library `AzLib` depending on `Azure Blob Storage client library`, what would the format be?

## Details
For the [Telemetry policy format](https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy)
`[<application_id> ]azsdk-<sdk_language>-<package_name>/<package_version> <platform_info>`
 how does the policy handle the scenario that there are multiple azure library being used? Especially in the case that one library is built based on an underlying service azure library.

For example, our **[ACS UI Chat Composite](https://github.com/Azure/communication-ui-library-ios/tree/feature/chat/AzureCommunicationUI/sdk)** is built based on **[Chat SDK](https://github.com/Azure/azure-sdk-for-ios/blob/main/sdk/core/AzureCore/Source/Pipeline/Policies/UserAgentPolicy.swift)**. The **ChatComposite** has no access to Telemetry implementation details and would only pass `application_id` to [ChatSDK API](https://azure.github.io/azure-sdk-for-ios/AzureCore/Structs/TelemetryOptions.html#/s:9AzureCore16TelemetryOptionsV13applicationIdSSSgvp) for logging purpose.

The ChatSDK telemetry info example in user_Agent could be

<application_id> azsdk-js-azure-communication-chat/1.1.0 core-rest-pipeline/1.3.0 OS/Win32

However we want to post our ChatComposite info to the Telemetry. And the only accessible parameter [application_id](https://azure.github.io/azure-sdk-for-ios/AzureCore/Structs/TelemetryOptions.html#/s:9AzureCore16TelemetryOptionsV13applicationIdSSSgvp) should be reserved for our Chat composite customers.

In this scenario, how should the dependent library pass it own telemetry information to the underlying service SDK and let service SDK log the additional telemetry information?

Should the service SDK has additional public API to accept those Telemetry info? Something similar to CallingSDK doing, having additional tags API for Telemetry. And the dependent libraries pass their info through the tags?

![image](https://user-images.githubusercontent.com/75647512/195943192-c798bc6c-71c7-4f36-8c42-e54615160b1c.png)

Please post any thought you have. And reach to @JoshuaLai  (Josh Lai) or @jimchou-dev (Jim Chou) for any question you have. 
Thanks

**Comment by ronniegeraghty** [comment]
Scheduled for Nov 8th, 2022, 2:05PM - 4:00PM PST

**Comment by ronniegeraghty** [comment]
@kyle-patterson I know you said you will be a part of this review. @AmyL219 appears to be on maternity leave so I wanted to see if you knew anyone else who should be invited?

**Comment by jimchou-dev** [comment]
You can invite me and @JoshuaLai

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/2bdd0840-98dc-ac1e-7cb1-f1ed6080e7ec) (MS INTERNAL ONLY)
