### ISSUE TITLE
Board Review: Azure Notification Hubs (JS)

### ISSUE THREAD

**Issue by mpodwysocki** [Azure/azure-sdk#4985]
## Contacts and Timeline

* Responsible service team: Azure SDK for JS Team
* Main contacts: Matthew Podwysocki
* Expected code complete date: October 2022
* Expected release date: November 2022

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/notification-hubs/
* Link to the service REST APIs: https://aka.ms/nh-rest-api
* Link to GitHub issue for previous review sessions, if applicable:  #4489

## About the client library

* Name of the client library: Azure Notification Hubs
* Languages for this review: JavaScript

### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/4f7ee36b2e4d446795d81ce35e1faf42
* Link to Champion Scenarios/Quickstart samples: 
  - Scenarios: https://gist.github.com/mpodwysocki/44633f26eb48f084c615eed8580ac4a6
  - Samples: https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/notificationhubs/notification-hubs/samples-dev

**Comment by ronniegeraghty** [comment]
Scheduled: Oct 20th, 2022, 2:05PM - 4:00PM PST
