### ISSUE TITLE
Board Review: Introducing Azure.Analytics.Purview.Workflow

### ISSUE THREAD

**Issue by CordeliaGrey** [Azure/azure-sdk#5009]
## Contacts and Timeline

* Service team responsible for the client library: Microsoft Purview Workflow Engineering <purview-workflow@microsoft.com>
* Main contacts: Jing Wang <jiwang6@microsoft.com>
* Expected stable release date for this library:  11/30/2022

## About the Service 

* Link to documentation introducing/describing the service: https://learn.microsoft.com/en-us/azure/purview/concept-workflow
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs-pr/blob/1efcea77df58e96308c165c5c0054f602cd758da/specification/purview/data-plane/Azure.Analytics.Purview.Workflow/preview/2022-05-01-preview/purviewWorkflow.json
* Is the goal to release a Public Preview, Private Preview, or GA? GA

## About the client library

* Name of client library: Azure.Analytics.Purview.Workflow
* Link to library reference documentation: https://review.learn.microsoft.com/en-us/rest/api/documentation-preview/approval-request?view=azure-rest-preview&branch=result_03fad3f2-02c9-499d-b4ea-56ca76747c07
  client code link: 
   C#: https://apiview.dev/Assemblies/Review/4254cef7adef46699f52e6ff72055626
   Python: https://apiview.dev/Assemblies/Review/43500e48932045aaa9f0b92e18fab1e5
   Java: https://apiview.dev/Assemblies/Review/a84e1b458c634ac1b0ee7673c4a2538e
   Javascript: https://apiview.dev/Assemblies/Review/6a0c7a03bf834e91a44a63cfaf38919a
* Is there an existing SDK library? If yes, provide link: No

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
4. How does the **authentication** workflow look? 
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1: Create workflow definition, workflow definition could be seen as a flow diagram which define how user want to operate their data entity.
```cs
    WorkflowDefinitionClient client = GetWorkflowDefinitionClient();
    string workflowDefinitionId = Guid.NewGuid().ToString();
    string workflowDefinitionPayload = File.ReadAllText("workflow_definition.json");  
    await client.CreateOrUpdateAsync(workflowDefinitionId, payload);
```
* Champion scenario 2: Trigger workflow run, which could be seen as an running instance of workflow definition.
```cs
    WorkflowRunClient client = GetWorkflowRunClient();
    string workflowRunId = Guid.NewGuid().ToString();
    
      var triggerRunPayload = new
      {
          requestType = "CreateTermRequest",
          payload = new
          {
              name = "sample_term",
              anchor = new
              {
                  glossaryGuid = "41065e8b-80af-4bae-afb8-13856b85444d"
              },
              status = "Draft",
              nickname = "sample_term",
              attributes = new { }
          }
      };
    
    await client.TriggerAsync(workflowRunId, RequestContent.Create(triggerRunPayload));
```
* Champion scenario 3: update workflow request, here is an example of approve approval request(one kind of workflow request)
```cs
      ApprovalRequestClient client = GetApprovalRequestClient();
      string approvalId = "98d98e2c-23fa-4157-a3f8-ff8ce5cc095c";

      var approveReply = new
      {
          comment= "Thanks for raising this!"
      };

      await client.ApproveAsync(approvalId, RequestContent.Create(approveReply));
```

**Comment by ronniegeraghty** [comment]
Drafted

**Comment by CordeliaGrey** [comment]
Hi @ronniegeraghty , I've sent the email to [Architecture Board](mailto:azsdkarch@microsoft.com) to schedule the review meeting two days ago, but didn't received any reply till now, may I ask how soon the meeting will be scheduled? Thanks.

**Comment by ronniegeraghty** [comment]
Hi @CordeliaGrey, the email alias you listed is the list of our SDK Architects, for assistance with scheduling in the future you should contact our [help desk alias](mailto:azsdkarch-help@microsoft.com). Currently the review session is slated for Nov 15th from 2:05PM - 4PM PST. Once the date and time of the session is confirmed you will receive an invite to the review session and a comment will be added to this issue with the text "Scheduled:" followed by the date and time of the session.

**Comment by CordeliaGrey** [comment]
Hi @ronniegeraghty, thanks for your patient explanation, I have few questions hope to get your reply:

1. Do I need to send scheduling meeting email again to [help desk alias](mailto:azsdkarch-help@microsoft.com)?
2. I followed this [guideline](https://azure.github.io/azure-sdk/policies_reviewprocess.html#types-of-review-meetings-and-what-to-prepare) to send the email to [Architecture Board](mailto:azsdkarch@microsoft.com), I didn't find [help desk alias](mailto:azsdkarch-help@microsoft.com) in this guideline, I'm afriad if I missed any other guideline, could you please share it if it does exist?
3. Could we move the review session eariler? As we are targeting release SDK by the end of Nov. I'm afraid Nov 15th is a little bit late and we can't catch up the expected release date. BTW, our local time is UTC+8，the time after 4PM PST would be appriciated.

**Comment by ronniegeraghty** [comment]
> Hi @ronniegeraghty Ronnie Geraghty FTE, thanks for your patient explanation, I have few questions hope to get your reply:
> 
> 1. Do I need to send scheduling meeting email again to [help desk alias](mailto:azsdkarch-help@microsoft.com)?
> 2. I followed this [guideline](https://azure.github.io/azure-sdk/policies_reviewprocess.html#types-of-review-meetings-and-what-to-prepare) to send the email to [Architecture Board](mailto:azsdkarch@microsoft.com), I didn't find [help desk alias](mailto:azsdkarch-help@microsoft.com) in this guideline, I'm afriad if I missed any other guideline, could you please share it if it does exist?
> 3. Could we move the review session eariler? As we are targeting release SDK by the end of Nov. I'm afraid Nov 15th is a little bit late and we can't catch up the expected release date. BTW, our local time is UTC+8，the time after 4PM PST would be appriciated.

1. If your email included any specific requests for your review session, like who should be invited please do forward it to the help desk email. 
2. You are all go for scheduling the review session. The only other thing would be to make sure champion senarios and APIview links for all tier 1 languages (.NET, Java, JavaScript, Python) are added to this issue. Looks like you have all the APIview links, but I just wanted to check and see if the Champion Senarios listed above are generalized pusedo code that will apply to all the languages. If not, you'll need to have Champion Senarios listed for each language. 
3. We just had another group cancel on their review session for Nov 9th. Would Nov 9th from 4:05PM - 6PM PST work for your team. If not, the 15th is the next available date.

**Comment by CordeliaGrey** [comment]
Hi @ronniegeraghty, 
Please let me know if I need to provide other language pusedo code after you checked.
Nov 9th from 4:05PM - 6PM PST work for my team, please help to schedule session at this time.
Thanks for your help!

**Comment by ronniegeraghty** [comment]
Scheduled: Nov 9th from 4:05PM - 6PM PST

**Comment by KrzysztofCwalina** [comment]
I moved the samples to the API view (samples tab). Please add sample comment there

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/cac50840-98dc-ac1e-4fc6-f1ed611b9263) (MS INTERNAL ONLY)
