### ISSUE TITLE
Board Review: Event Grid new system events

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk#5011]
## Contacts and Timeline

* Responsible service team: DataBox, APIM
* Main contacts: @JoshLove-msft 
* Expected code complete date: 11/4
* Expected release date: 11/7

## About the Service 

* Link to the service REST APIs: 
https://github.com/Azure/azure-rest-api-specs/pull/21157
https://github.com/Azure/azure-rest-api-specs/pull/20871

### .NET

* APIView Link: To be added

### Java

* APIView Link: To be added

### Python

* APIView Link: N/A
  
### TypeScript

* APIView Link: To be added

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by ronniegeraghty** [comment]
Scheduled: Oct 31st from 3:05PM - 4:00PM PST

**Comment by JoshLove-msft** [comment]
Have not heard back from service rep for DataBox. APIM rep has said they are not ready to review their events.

**Comment by ronniegeraghty** [comment]
@JoshLove-msft, does this mean the event gird review scheduled for today should be cancelled, or are there other services with events to be reviewed?

**Comment by JoshLove-msft** [comment]
Yes, please cancel the review for today.

**Comment by ronniegeraghty** [comment]
Canceled

**Comment by JoshLove-msft** [comment]
Thanks @ronniegeraghty!
