### ISSUE TITLE
Board Review: .NET Azure.Core 

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk#5014]
## Contacts and Timeline

* Main contacts: @annelo-msft @christothes @JoshLove-msft 
* Expected code complete date: 10/28
* Expected release date: 11/3

## About the client library

* Name of the client library: Azure.Core
* Languages for this review: .NET

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/77bdbcef49a3465fa96fac3fb745bf57/50f15cfb5717421bbac34a28cda326d9?diffRevisionId=31319a8c06624bfd9462431370e5aecf&doc=False&diffOnly=True
* NullableResponse
  * Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/issues/27852
* RetryPolicy
  * Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#setting-a-custom-retry-policy
* RequestUriBuilder
* ResourceIdentifier.TryParse

**Comment by ronniegeraghty** [comment]
Scheduled: Oct 31st 2:05PM - 3:00PM PST

**Comment by JonathanGiles** [comment]
@JoshLove-msft The APIView links don't seem to resolve to a valid page. If you get a chance please can you double check them? Thanks!

**Comment by JoshLove-msft** [comment]
Updated, though I'm not sure why the links keep becoming invalid. I'm linking to the diff in the auto-review.

**Comment by srnagar** [comment]
[Recording](https://msit.microsoftstream.com/video/1f970840-98dc-ac1e-9118-f1ed5a05aaa8) (MS INTERNAL ONLY)
