### ISSUE TITLE
Board Review: NGINX for Azure (Management plane SDK namespace review)

### ISSUE THREAD

**Issue by SpencerOfwiti** [Azure/azure-sdk#5026]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Liftr Nginx
* Main contacts: @SpencerOfwiti @limingu 
* Expected code complete date: Not Applicable
* Expected release date: 11/01/2022

## About the Service 

* Link to documentation introducing/describing the service: https://learn.microsoft.com/en-us/azure/partner-solutions/nginx/
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/nginx/resource-manager/NGINX.NGINXPLUS/stable/2022-08-01
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library:
* Languages for this review:

The SDKs are autogenerated from the swagger, this review is only for namespace approval.

**Comment by ronniegeraghty** [comment]
Drafted

**Comment by SpencerOfwiti** [comment]
- Resource Provider Namespace: NGINX.NGINXPLUS

- Currently used management plane package names in different languages: We have nginx as a common suffix, and the prefix is changed as per the requirements of the language.

```
Python: azure-mgmt-nginx
JS: @azure/arm-nginx
Java: com.azure.resourcemanager.nginx
C#: Azure.ResourceManager.Nginx
Go: armnginx
PowerShell: Az.Nginx
Azure CLI: az nginx
```

We see that for the current management plane namespace we are aligning by the guidelines as per: https://azure.github.io/azure-sdk/general_design.html

**Comment by SpencerOfwiti** [comment]
@ronniegeraghty Could you follow up on this.

**Comment by ronniegeraghty** [comment]
Working on offline review. 
Online review session is set for Nov 22nd from 2:05PM - 4PM PST if the review can not be completed offline.

**Comment by JonathanGiles** [comment]
Java is good

**Comment by JeffreyRichter** [comment]
Go is good

**Comment by SpencerOfwiti** [comment]
@ronniegeraghty What is the status of the offline review?

**Comment by ronniegeraghty** [comment]
@SpencerOfwiti poked the offline review thread. Looks like most languages gave explicit approval. I asked Python and JS to comment today if they have any concerns and if there are no concerns stated today, consider it approved.

**Comment by xirzec** [comment]
JS confirmed good

**Comment by SpencerOfwiti** [comment]
If there are no other concerns, I will close this issue. Feel free to ping me in case of changes.
