### ISSUE TITLE
Update chokidar-cli to use lodash >=4.17.12 due to security vulnerability

### ISSUE THREAD

**Issue by thedanfernandez** [Azure/azure-sdk#503]
When running `npm install` on the project locally, NPM will flag the project as having a "high security vulnerability" due to `chokidar-cli` using an older, vulnerable version of lodash. This is patched in `lodash >=4.17.12`.  

### Repro steps

1. Git clone project
2. Run `npm install`
3. Notice high severity warning and instructions to run `npm audit`

### More info 
- **Advisory**: [NPM Security Advisory](https://www.npmjs.com/advisories/1065)
- **Tracking Issue**: [Chokidar-cli - High severity security advisiory for lodash](https://github.com/kimmobrunfeldt/chokidar-cli/issues/66)
- **NPM Audit**: See below results from running `npm audit` command

_ _ _ _

npm audit security report 

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.12                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ chokidar-cli [dev]                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ chokidar-cli > lodash                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1065                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
**found 1 high severity vulnerability in 2223 scanned packages
  1 vulnerability requires manual review. See the full report for details.**

**Comment by adrianhall** [comment]
Removed reliance on chokidar since we don't actually need file watch.  I will get an alternative if we need file watching.
