### ISSUE TITLE
Board Review: [Azure Core] Add retry policy for regional failover

### ISSUE THREAD

**Issue by joheredi** [Azure/azure-sdk#5032]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: n/a
* Main contacts: @dgetu
* Expected code complete date:
* Expected release date:

## About the Service 

* Link to documentation introducing/describing the service: N/A
* Link to the service REST APIs: N/A
* Link to GitHub issue for previous review sessions, if applicable:  N/A

## About the client library

* Name of the client library: @azure/core-rest-pipeline
* Languages for this review: Typescript

### About the changes:
This is a proposal to design a standard interface for client SDKs to define their failover behavior. This change includes an implementation for Data Tables, allowing users to failover to a Table Storage RA-GRS secondary region or Cosmos georeplicated endpoint.

For more context on the feature request see https://github.com/Azure/azure-sdk-for-js/issues/23098

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link: 
   * [Core] https://apiview.dev/Assemblies/Review/4470b46cde38476bb85426fd00f6ee5c/3a4cd678b20340899a9f4bd41c3b9a6d?diffRevisionId=1d843c1daf5f4a558ec5c06a098d83bc&doc=False&diffOnly=True
   * [Tables]  https://apiview.dev/Assemblies/Review/3b4afda6285148b994a6aee445c1a95e/bf3331f957624f56ae2d5da862ea2b80?diffRevisionId=901fc9f610024a6591e628badf76df23&doc=False&diffOnly=True
* Link to Champion Scenarios/Quickstart samples: 
    * [Tables]
https://github.com/Azure/azure-sdk-for-js/pull/23269/files#diff-1e1c069cc2d9f007bea31dfc70984ab67ef589d04d3166949aa6998b182cb675

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by ronniegeraghty** [comment]
Drafted

**Comment by ronniegeraghty** [comment]
Scheduled for Nov 17th, 2:05PM - 4PM PST

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/77a80840-98dc-ac1e-727b-f1ed66d46e9d) (MS INTERNAL ONLY)
