### ISSUE TITLE
Azure Stack support for the new Azure Go SDK

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk#5044]
Original requirement: 
Azure Stack wants us to provide an SDK which could only contains operations belonged to a sub-set of resource types and each resource type uses a specific API version.

Previous solution: 
In the previous version of Azure Go SDK, we use profile to support it. Since track1 compose all RPs with all API versions in one module, the profile sub-package will map the model and operation with needed RPs and API version. Package here: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v67.0.0+incompatible/profiles/2020-09-01.

Possible solutions: 
The new version of Azure Go SDK only supports single API version and releases different RPs with separated modules. So, if we need to support Azure Stack, we have two ways:
1. We generate and release a dedicated profile module that contains all the needed RPs’ packages, this is somehow follow what we do in previous SDK version. I did a proto work in this [PR](https://github.com/Azure/azure-sdk-for-go/pull/18841). Currently, data plane packages have not been added to profile module
2. We generate and release several modules, and each contains only one RP, this is somehow a batch of parallel modules of the current SDK module but generated with different API version.

Discussion: 
JS and Java all apply the second way and released a batch of separated packages for Azure Stack. But the disadvantage is that customer will need to import several packages when using Azure Stack. Do we need to keep consistency for all the languages? And which solution will be better?

**Comment by tadelesh** [comment]
cc @mikekistler @xboxeer @jhendrixMSFT @JeffreyRichter @RickWinter @lirenhe @ArcturusZhang @sandeep-sen

**Comment by JeffreyRichter** [comment]
I don't know enough about Azure Stack and profiles yet. Please educate me on exactly what a profile is in concept and how this maps to service api-versions. Ignore any thinking about Go packages/modules for the moment. Then, after I/we understand this well, we can apply the knowledge as to how to best address this with Go Track 2 packages/modules.

**Comment by tadelesh** [comment]
@JeffreyRichter Profile offer a means of virtualizing the API Versions of services that should be targeted by an application or SDK. You could find a profile config [here](https://github.com/Azure/azure-rest-api-specs/blob/main/profile/2020-09-01-hybrid.json). Azure Stack uses it to specify RP, resource types and API version they are using. They want us to provide SDKs according to the profile config.
For Go track1, we have sub package for this profile: https://github.com/Azure/azure-sdk-for-go/tree/main/profiles/2020-09-01. For JS track2, they have separated packages for the RPs configured in profile: https://www.npmjs.com/search?q=hybrid-profile. For Java track2, they do the same with JS: https://mvnrepository.com/artifact/com.azure.resourcemanager/azure-resourcemanager-network/1.0.0-hybrid.

**Comment by tadelesh** [comment]
@JeffreyRichter Is there anything else I could help to explain? I don't know much about the profile design history. Maybe @jhendrixMSFT could help to add more context.

**Comment by JeffreyRichter** [comment]
See email thread I added you to today

-- Jeffrey Richter
________________________________
