### ISSUE TITLE
Board Review: Introducing Azure EASM

### ISSUE THREAD

**Issue by nathanfalke** [Azure/azure-sdk#5062]
## Contacts and Timeline

* Service team responsible for the client library:
	- riskiq_easm@microsoft.com
* Main contacts:
	- Nate Falke, nathanfalke@microsoft.com, @nathanfalke
	- Brian Zak, brianzak@microsoft.com, @eqtip
	- Nisha Bhatia, nishabhatia@microsoft.com, @nishabhatia-msft
* Expected stable release date for this library:

## About the Service 

* Link to documentation introducing/describing the service:
	- [External Attack Surface Management](https://learn.microsoft.com/en-us/azure/external-attack-surface-management/)
* Link to the service REST APIs: 
	* [2022-04-01-preview/easm.json](https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSMaster/specification/riskiq/data-plane/Microsoft.Easm/preview/2022-04-01-preview/easm.json)
* Is the goal to release a Public Preview, Private Preview, or GA? 
	* Private Preview

## About the client library

* Name of client library:
	* Azure-EASM
	* Azure-Mgmt-EASM
* Link to library reference documentation:
	* [Azure-EASM](https://github.com/nathanfalke/azure-sdk-for-python/tree/main/sdk/easm/azure-easm)
	* [Azure-Mgmt-EASM](https://github.com/nathanfalke/azure-sdk-for-python/tree/main/sdk/easm/azure-mgmt-easm)
* Is there an existing SDK library? If yes, provide link: 
	* No.

## Step 1: Champion Scenarios 
* Data Plane Champion scenarios
    * [Create and view discovery runs](https://github.com/nathanfalke/azure-sdk-for-python/blob/main/sdk/easm/azure-easm/samples/sample1_managing_discovery_runs.md)
    * [Create discovery groups from templates](https://github.com/nathanfalke/azure-sdk-for-python/blob/main/sdk/easm/azure-easm/samples/sample2_create_disco_group_from_template.md)
    * [Use a saved filter to synchronize queries](https://github.com/nathanfalke/azure-sdk-for-python/blob/main/sdk/easm/azure-easm/samples/sample3_use_saved_filters.md)
    * [Tag assets with external IDs](https://github.com/nathanfalke/azure-sdk-for-python/blob/main/sdk/easm/azure-easm/samples/sample4_managing_external_ids.md)
    * [Create Sentinel Data Connection](https://github.com/nathanfalke/azure-sdk-for-python/blob/main/sdk/easm/azure-easm/samples/sample5_creating_a_sentinel_data_connection.md)
* Control Plane Champion scenarios
	* [Create a workspace](https://github.com/nathanfalke/azure-sdk-for-python/blob/main/sdk/easm/azure-mgmt-easm/samples/sample1_create_workspace.md)
	* [Create labels](https://github.com/nathanfalke/azure-sdk-for-python/blob/main/sdk/easm/azure-mgmt-easm/samples/sample2_create_labels.md)

## Step 2: Quickstart Samples (Optional)
 * [Data Plane Quickstart Samples](https://github.com/nathanfalke/azure-sdk-for-python/blob/main/sdk/easm/azure-easm/README.md)
 * [Control Plane Quickstart Samples](https://github.com/nathanfalke/azure-sdk-for-python/blob/main/sdk/easm/azure-mgmt-easm/README.md)

## API Stewardship Board Review
* Please refer to [#7029](https://github.com/Azure/azure-rest-api-specs-pr/issues/7029) for API Review notes

**Comment by ronniegeraghty** [comment]
Drafted

**Comment by ronniegeraghty** [comment]
@nathanfalke, please include any materials like package names, champion scenarios, etc. for other programing languages.

**Comment by nathanfalke** [comment]
We currently only have materials for a Python SDK

**Comment by ronniegeraghty** [comment]
@nathanfalke it would be helpful if you could upload the API View links for the python libraries. Thank you.

**Comment by nathanfalke** [comment]
sure thing

[azure-easm](https://apiview.dev/Assemblies/Review/6ac55662c2ab454ea9515cf6f47608ff)
[azure-mgmt-easm](https://apiview.dev/Assemblies/Review/0fd63c3d327a4627a2268aee689fcee1)

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/a1a00840-98dc-ac1e-f390-f1ed70409313) (MS INTERNAL ONLY)

Approved names:
- .NET: `Azure.Analytics.Defender.Easm`
- Java: `com.azure.analytics.defender.easm`
- Python: `azure-defender-easm`
- JS/TS: `@azure/defender-easm`
