### ISSUE TITLE
Board Review: Distributed tracing for Preview 2

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk#507]
See [gist](https://gist.github.com/johanste/319960a2c60f1f3bc7e0596af2c61324) outlining the assumptions and requirements for supporting distributed tracing for preview 2.

**Comment by johanste** [comment]
>> None of our libraries have a hard dependency on any 3rd part tracing library (including the opentelemetry/opencensus libraries) for preview-2. This includes both code and packaging.
> @lmolkova: open-telemetry support ships as plugin (when required) and is common for all SDKs. 

If you only install one of our azure libraries today, there is (to the best of my knowledge) no open telemetry package getting installed (neither SDK nor API package).

**Comment by lmolkova** [comment]
This guy: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/tracing/azure-tracing-opentelemetry/pom.xml#L42

**Comment by adrianhall** [comment]
BOARD DECISION: Johans proposal is accepted.
