### ISSUE TITLE
Board Review: CADL+DPG+Model Anomaly Detector preview

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#5070]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Anomaly Detector team
* Main contacts: Chunlei Wang; Louise Han
* Expected code complete date: 12/1
* Expected release date: 12/5

## About the Service 

* Link to documentation introducing/describing the service: https://learn.microsoft.com/en-us/azure/cognitive-services/Anomaly-Detector/overview
* Link to the service REST APIs: https://westus2.dev.cognitive.microsoft.com/docs/services/AnomalyDetector-v1-1
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Anomaly Detector
* Languages for this review: .NET, Pyhton, JAVA, TS/JS

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### CADL

PR: https://github.com/Azure/azure-rest-api-specs/pull/21525
APIView: https://apiview.dev/Assemblies/Review/4a54b24951a24458bb0a46b09983d998

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/0eacd79245e14c6fa88d5991aac2e02f
* Code: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/anomalydetector/Azure.AI.AnomalyDetector
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net/pull/32673

### Java

* APIView Link: https://apiview.dev/Assemblies/Review/3302ff98602642e1b8d0541357e6d069
* Code: https://github.com/Azure/azure-sdk-for-java/pull/32182
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-java/pull/32303

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/a97ff6898fb443ee82a679e0ac1aedd6?diffRevisionId=cee43f5f3d3345c594c526675a225853&diffOnly=False&revisionId=5f7debea09204d8097f90998ff86a520&doc=False
* Code: https://github.com/Azure/azure-sdk-for-python/pull/27516
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-python/pull/27694

### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/da34017601e14eb59f9f94ebe28f704e
* Code: https://github.com/Azure/azure-sdk-for-js/pull/23866
* Link to Champion Scenarios/Quickstart samples: https://github.com/qiaozha/azure-sdk-for-js/pull/3/files

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by ronniegeraghty** [comment]
Scheduled for Nov 28th from 4:05PM - 6PM PST.

**Comment by ronniegeraghty** [comment]
@lmazuel Can we get samples for at least one language before the review session? Thank you.

**Comment by jr-MS** [comment]
> @lmazuel Can we get samples for at least one language before the review session? Thank you.

Already updated the sample links in the description from Laurent above.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/0ddd0840-98dc-ac1e-92db-f1ed7030d153) (MS INTERNAL ONLY)
