### ISSUE TITLE
Board Review: Cosmos Python logging policy and new API features

### ISSUE THREAD

**Issue by JericHunter** [Azure/azure-sdk#5084]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure.

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Cosmos DB
* Main contacts: Jeric Hunter (jerichunter@microsoft.com), Kushagra Thapar (kuthapar@microsoft.com)
* Expected code complete date: N/A
* Expected release date: N/A

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/en-us/azure/cosmos-db/
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/cosmos-db/
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/4232

## About the client library

* Name of the client library: [azure-cosmos](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cosmos/azure-cosmos)
* Languages for this review: Python
## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### Python

* APIView Link: https://apiview.dev/Assemblies/Review/99a97c8e97f040199245c99d899318a4?diffRevisionId=6a47daa4935d4630af3a79b8a9168225&diffOnly=True&revisionId=270d881183594119aa33084ba0a5cb52&doc=False#comment-thread-0
* Link to powerpoint with information: https://microsoft-my.sharepoint.com/:p:/p/jerichunter/EYaptpsWZvdLpW2iF8f3ZyIBEczogsT7oqy5traqbWp-QA?e=F2txLn

**Comment by JericHunter** [comment]
still going to be adding information over the next few days

**Comment by ronniegeraghty** [comment]
Drafted

**Comment by ronniegeraghty** [comment]
@JericHunter please let us know when the information in this issue is stable so the Architects can review it in preparation for the review board session.

**Comment by ronniegeraghty** [comment]
@JericHunter, I wanted to check in and see if the information in the issues is stable and ready to be reviewed.

**Comment by ronniegeraghty** [comment]
Scheduled for Nov 30th from 2:05PM - 4PM PST.

**Comment by ronniegeraghty** [comment]
Hi @JericHunter sorry to hear that. Yes, we can push back the review session. There are two later dates available before most of the Arch team starts taking holiday leave. Would either the 13th or 14th of Dec work? If not, we can push the review back to any time on or after Jan 9th, 2023. Let me know what works best for you. Thanks

**Comment by JericHunter** [comment]
After Jan 9th works for me!

**Comment by ronniegeraghty** [comment]
Sure thing. 
Rescheduled to Jan 9th from 2:05PM - 4PM PST.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/59830840-98dc-ba75-5bc6-f1edabc51be3) (MS INTERNAL ONLY)
