### ISSUE TITLE
Add version checks during our pipelines

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#509]
Add some tools to each of our repo build pipelines, perhaps during our Analyze job, which will verify that the package being built is not already published to any registry. If it is published fail with a note that calls out we need to bump the version.

**Comment by kurtzeborn** [comment]
Definitely related to (possibly a dupe of): https://github.com/azure/azure-sdk-tools/issues/103

**Comment by mitchdenny** [comment]
We should discuss whether we want to do this. During the GA publishing there were multiple times where particular packages didn't make it out of the pipeline for whatever reason and we had to requeue where some of its sibling packages had already been published. Enforcing this early in the pipeline would block us from doing that. We already have a block in place for the release stage where release fails if we attempt to re-release a package.

/cc @weshaggard

**Comment by weshaggard** [comment]
That is fair maybe we don't make it an error but we can at least make it a warning as I think it is still a good idea to give folks an early warning sign that packages will not be able to be released.

**Comment by mitchdenny** [comment]
Looking to clean up old issues, is this one still a priority? I'm not seeing this be a huge problem for us. It seems like the worst case scenario is that the pipeline fails in release and we update the version numbers and publish again (which would only happen if someone didn't merge the version bump PR anyway).

**Comment by weshaggard** [comment]
Lets close this until we have a specific scenario in mind that we want to validate. I don't know of any specific checks we should do currently.
