### ISSUE TITLE
Write some tools that will go in an bump the versions in the repo after release

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#510]
Each time we publish a package we need to ensure that the version number, either the preview or stable version gets bumped in the repo. I think this issue can come in stages:

- [x] [Preview 3] Create a set of instructions that outlines how and when to version (added to [this document](https://github.com/Azure/azure-sdk/blob/master/docs/policies/releases.md#version-updates))
- [ ] [Preview 3] Create a tool that people can run to update the versions automatically.
- [ ] [Preview 3] Create automation that will automatically submit a PR that bumps the versions in the repo after a published package is created.

**Comment by kurtzeborn** [comment]
@mikeharder is writing the documentation for the first item currently.
