### ISSUE TITLE
Come up with a strategy and process to produce library docs across branches

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#511]
A number of our libraries ship out of branches other then master and in those cases we need a way to produce documentation for those preview releases and merge them into one set of documentation on github.io.

Ideally if we can build docs at a pre-library level and publish those to the same github.io storage location and update the index to ensure there are links to that library.

**Comment by kurtzeborn** [comment]
Most everything is releasing from master for current and future previews.  That was not completely true for preview 1, and the only planned exception of that for preview 2 will be the storage libraries for JS.
