### ISSUE TITLE
Change Request: Telemetry and dependencies (General Guidelines)

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk#5110]
### Current Telemetry Guidance

Today https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy states:

> Client library usage telemetry is used by service teams (not consumers) to monitor what SDK language, client library version, and language/platform info a client is using to call into their service. Clients can prepend additional information indicating the name and version of the client application.
> 
> Client library usage telemetry is used by service teams (not consumers) to monitor what SDK language, client library version, and language/platform info a client is using to call into their service. Clients can prepend additional information indicating the name and version of the client application.
> 
> {% include requirement/MUST %} send telemetry information in the [User-Agent header] using the following format:
> 
> ```
> [<application_id> ]azsdk-<sdk_language>-<package_name>/<package_version> <platform_info>
> ```
> 
> - `<application_id>`: optional application-specific string. May contain a slash, but must not contain a space. The string is supplied by the user of the client library, e.g. "AzCopy/10.0.4-Preview"
> - `<sdk_language>`: SDK's language name (all lowercase): "net", "python", "java", or "js"
> - `<package_name>`: client library package name as it appears to the developer, replacing slashes with dashes and removing the Azure indicator.  For example, "Security.KeyVault" (.NET), "security.keyvault" (Java), "keyvault" (JavaScript & Python)
> - `<package_version>`: the version of the package. Note: this is not the version of the service
> - `<platform_info>`: information about the currently executing language runtime and OS, e.g. "(NODE-VERSION v4.5.0; Windows_NT 10.0.14393)"
> 
> For example, if we re-wrote `AzCopy` in each language using the Azure Blob Storage client library, we may end up with the following user-agent strings:
> 
> - (.NET) `AzCopy/10.0.4-Preview azsdk-net-Storage.Blobs/11.0.0 (.NET Standard 2.0; Windows_NT 10.0.14393)`
> - (JavaScript) `AzCopy/10.0.4-Preview azsdk-js-storage-blob/11.0.0 (Node 10.16.0; Ubuntu; Linux x86_64; rv:34.0)`
> - (Java) `AzCopy/10.0.4-Preview azsdk-java-storage.blobs/11.0.0 (Java/1.8.0_45; Macintosh; Intel Mac OS X 10_10; rv:33.0)`
> - (Python) `AzCopy/10.0.4-Preview azsdk-python-storage/4.0.0 Python/3.7.3 (Ubuntu; Linux x86_64; rv:34.0)`
> 
> {% include requirement/MUST %} allow the consumer of the library to set the application ID.  This allows the consumer to obtain cross-service telemetry for their app.  The application ID should be settable in the relevant `ClientOptions` object.
> 
> {% include requirement/MUST %} enforce that the application ID is no more than 24 characters in length.  Shorter application IDs allows service teams to include diagnostic information in the "platform information" section of the user agent, while still allowing the consumer to obtain telemetry information for their own application.
> 
> {% include requirement/SHOULD %} send telemetry information that is normally sent in the `User-Agent` header in the `X-MS-UserAgent` header when the platform does not support changing the `User-Agent` header.  Note that services will need to configure log gathering to capture the `X-MS-UserAgent` header in such a way that it can be queried through normal analytics systems.
> 
> {% include requirement/SHOULD %} send additional (dynamic) telemetry information as a semi-colon separated set of key-value types in the `X-MS-AZSDK-Telemetry` header.  For example:
> 
> ```http
> X-MS-AZSDK-Telemetry: class=BlobClient;method=DownloadFile;blobType=Block
> ```
> 
> The content of the header is a semi-colon key=value list.  The following keys have specific meaning:
> 
> * `class` is the name of the type within the client library that the consumer called to trigger the network operation.
> * `method` is the name of the method within the client library type that the consumer called to trigger the network operation.
> 
> Any other keys that are used should be common across all client libraries for a specific service.  **DO NOT** include personally identifiable information (even encoded) in this header.  Services need to configure log gathering to capture the `X-MS-SDK-Telemetry` header in such a way that it can be queried through normal analytics systems.

### The Problem

We occasionally have one library used to help implement another library.  An example includes `Azure.Storage.Files.DataLake` using `Azure.Storage.Blobs` under the covers because it turns out they’re really the same thing and DataLake just adds a few Hadoopy extras.  How do we deal with our client library dependencies when it comes to telemetry?  We want calls originating from DataLake to not say they’re coming from the Blobs library in our standard `user-agent` string.

### Option A: Telemetry Impersonation

.NET created a new [`TelemetryDetails` class](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/TelemetryDetails.cs) where you can customize the assembly (to say use `typeof(DataLakeServiceClient).Assembly`) and then call `Apply` to your `HttpMessage`.  DataLake would use this by creating its internal helper `BlobClient` instance with a custom per-call pipeline policy that allows structured customization of the telemetry details to make all requests look like they were coming from DataLake.  This was discussed in detail at https://github.com/Azure/azure-sdk/issues/3979 around the 41 minute mark of https://msit.microsoftstream.com/video/80ba0840-98dc-a999-6a6a-f1ec9c2686b2.

For the DataLake scenario, this approach would result in user-agent like `TedsCoolApp azsdk-net-Storage.DataLake/12.0.0 (.NET Standard 2.1; Windows_NT 10.0.14393)`.

### Option B: Extending the User-Agent

Some languages extend the `user-agent` string to list all dependencies.  They sort them from outermost to innermost in case the `user-agent` is truncated.  It looks like we've seen two separate variants of this in practice across different languages:
- Java like `[<application_id> ](azsdk-<sdk_language>-<package_name>/<package_version> )+<platform_info>` where everything is prefix by `azsdk-<lang>`
- JS like `[<application_id> ]azsdk-<sdk_language>-(<package_name>/<package_version> )+<platform_info>` where only the first entry is prefixed by `azsdk-<lang>`

For the DataLake scenario, this approach would result in a user-agent like `TedsCoolApp azsdk-net-Storage.DataLake/12.0.0 azsdk-net-Storage.Blobs/12.0.0 azsdk-net-Core/1.0.0 (.NET Standard 2.1; Windows_NT 10.0.14393)` or `TedsCoolApp azsdk-net-Storage.DataLake/12.0.0 Storage.Blobs/12.0.0 Core/1.0.0 (.NET Standard 2.1; Windows_NT 10.0.14393)`.

### Desired outcome

Whatever telemetry approach we take needs to be consistent across languages.  We should pick one of the options for dependency telemetry and all adopt it.

**Comment by tg-msft** [comment]
We should follow-up with https://github.com/Azure/azure-sdk/issues/5004 where this issue was originally raised after making a decision.

**Comment by srnagar** [comment]
**Option B:**
For Java, the pattern mentioned above is used only in Storage libraries. Also, we don't list all the dependencies in the user agent string. This pattern applies only to client libraries that depend on Azure Storage Blobs. In those cases, we include Azure Storage Blobs and its consumer in UA. No other dependencies are included (like azure-storage-common, azure-core etc). 

See [BlobUserAgentModificationPolicy](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/implementation/util/BlobUserAgentModificationPolicy.java#L16-L21).

**Comment by m-nash** [comment]
Option B is what would be needed for mgmt dotnet.

We want to be able to track usage around our common Azure.ResourceManager library as well as the leaf node libraries like Azure.ResourceManager.Compute.  Right now there is a single client in the Azure.ResourceManager library and all "subclients" get created from this client for all other leaf node libraries.  There are 2 scenarios here that should work

1. The API call originates directly from Azure.ResourceManager.  This is the case for common resources like Subscription and ResourceGroup.  Expected result is `azsdk-net-ResourceManager/1.2.0 (.NET 6.0.7; Microsoft Windows 10.0.17763)`
2. The API call originates from a leaf node.  This is the case for resources that live in leaf nodes like VirtualMachine.  Expected result is `azsdk-net-ResourceManager.Compute/1.1.0-alpha.20220726.1 azsdk-net-ResourceManager/1.2.0 (.NET 6.0.7; Microsoft Windows 10.0.17763)`

In both cases we shouldn't have any duplicate as this puts pressure on max string length.  All of this is independent of the application id that customers can set in their client options which gets prepended to all of that.

**Comment by kyle-patterson** [comment]
If relevant: some services limit the user agent length and truncate, it sounds like Option B could risk collecting the OS information... 

See [Adding an additional format for the UA string](https://github.com/Azure/azure-sdk/issues/1457)

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/19db0840-98dc-ba75-9960-f1edabcda561) (MS INTERNAL ONLY)
