### ISSUE TITLE
Transition design guidelines to Jekyll / Markdown

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-sdk#512]
The current guidelines are written in a (basically single) madoko file.  Proposal would convert all the design guidelines into markdown files in a jekyll template. 

## Pros
* Markdown has better tooling than Madoko (e.g. Acrolinx works as standard)
* Jekyll has better visual appeal for zero cost (except transition costs)
* Jekyll provides better functionality for the docs, include site maps, search, and analytics
* We can auto-publish to a github.io site (azure.github.io/azure-sdk)
* We can integrate the engineering systems documentation as well

## Cons
* This will be a wholesale re-org of the repository to conform to Jekyll
* There are features of Madoko that are not available in Markdown, but can be placed in plugins and will need to be reformatted.  Examples include the requirements:

```
~ Must {#foo}
do something
~
```

becomes

```
{% must name="foo" %}
do something
{% endmust %}
```

**Comment by adrianhall** [comment]
No real concerns - it's a basic "meh" - going to be writing the same text.

**Comment by adrianhall** [comment]
Done

**Comment by Carlos8510** [comment]
> Las directrices actuales están escritas en un único archivo Madoko. La propuesta convertiría todas las directrices de diseño en archivos Markdown en una plantilla Jekyll.
> 
> ## Ventajas
> * Markdown tiene mejores herramientas que Madoko (por ejemplo, Acrolinx funciona como estándar)
> * Jekyll tiene un mejor atractivo visual por un coste cero (excepto los costes de transición)
> * Jekyll proporciona una mejor funcionalidad para los documentos, incluye mapas del sitio, búsqueda y análisis.
> * Podemos publicar automáticamente en un sitio github.io (azure.github.io/azure-sdk)
> * También podemos integrar la documentación de los sistemas de ingeniería.
> 
> ## Contras
> * Esta será una reorganización total del repositorio para cumplir con Jekyll
> * Hay funciones de Madoko que no están disponibles en Markdown, pero que pueden incluirse en complementos y que deberán reformatearse. Algunos ejemplos incluyen los requisitos:
> 
> ```
> ~ Must {#foo}
> do something
> ~
> ```
> 
> se convierte
> 
> ```
> {% must name="foo" %}
> do something
> {% endmust %}
> ```
