### ISSUE TITLE
Board Review: Preview Features in Stable Packages

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk#5122]
The Cosmos team is requesting that we support shipping preview features in stable packages. Something like that already shipped in Cosmos Java packages, and the most recent request is for .NET Cosmos packages. We should talk at the arch board level if and how we want to support such requests. 

The .NET platform supports some such scenarios. See https://github.com/dotnet/designs/blob/main/accepted/2021/preview-features/preview-features.md. The .NET platform solution does not work for the Azure SDK as it's not designed for Net Standard NuGet packages, but we met with the BCL team and we have a plan for how to make similar feature/checks working for Net Standard packages. 

We also need to discuss how this would look for other languages.

**Comment by ronniegeraghty** [comment]
Scheduled for Dec 8th from 2:05PM - 4PM PST.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/60d10840-98dc-ba75-57bf-f1edabcc394b) (MS INTERNAL ONLY)
