### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) Video Gallery Pinned Participants [JS] [Public Preview]

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#5148]
[Team] - ACS Web UI Library
[Release Type] - Public Preview
[Feature to be reviewed] - Video Gallery Pinned Participants

The video gallery supports new layouts including spotlight and focus, in addition to the existing grid layout. These new layouts allow developers to pick and choose the view in which they want to showcase participants and content.  

Artifacts:
APIView Link: https://apiview.dev/Assemblies/Review/7276a0d82fce4755b833fc91def19dbc/80605558e3ea4faa8acc2db2edb2e3fa?diffRevisionId=e5319a9cae2746049a23d00e1af908d2&doc=False&diffOnly=True
Powerpoint detailing changes: https://microsoft.sharepoint-df.com/:p:/t/IC3SDK/Ecnn_fV2j-pLngq_UER31yYBRD3jKnLDwun88bhDCGLdVQ?e=cxutPu

**Comment by ronniegeraghty** [comment]
Scheduled for Dec 12th from 2:05PM - 3PM PST.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/60d10840-98dc-ba75-7705-f1edabcb185d) (MS INTERNAL ONLY)
