### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) End of Call Survey [JS] [Public Preview]

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#5149]
Service name: 
Key contact for this review: srahaman
Link to previous API version: https://apiview.dev/Assemblies/Review/9a67b94f720c4138845ecf5e8f0efac8?revisionId=999f2920c4ee4e9db2879e659119fc08&doc=False
Description of the material to be reviewed/changed: ACS Calling Web SDK - End of Call Survey API
Champion scenarios that briefly explain how developers will use your API:

Scenario 1: Contoso rated the Call alone
When the Call ended
Then the Contoso can call the SDK call rating API
And able to rate the overall call experience

Scenario 2: Contoso rated the call category(s) selected (audio, video, screensharing)
When the Call ended
Then the Contoso can call the SDK call rating API
And rate the call by category(s) selected (audio, video, screensharing)

Scenario 3: Contoso rated both the Call and category(s)
When the Call ended
Then the Contoso can call the SDK call rating API
And able to rate the overall call experience
And rate the call by category(s) selected (audio, video, screensharing)

Scenario 4: Contoso rated the Call with pre-defined issues
When the Call ended
Then the Contoso can call the SDK call rating API
And able to rate the overall call experience
And rate the call by category(s) selected (audio, video, screensharing)
And send pre-defined issues (Enum values to be language agnostic)
 
Scenario 5: Contoso rated the Call with custom feedback scale
When the Call ended
Then the Contoso can call the SDK call rating API
And define custom feedback scale (0-100) and cutoff threshold for overall call rating and each category
And able to rate the overall call experience
And rate the call by category(s) selected (audio, video, screensharing)
And send pre-defined issues (Enum values to be language agnostic)

Languages for this review: TypeScript
Artifacts per language.

"Microsoft shipped enhanced capabilities within ACS that allows its customers to submit at the end of a call a questionnaire to ask details about the call. Be enabling customers the ability to ask questions directly from the end user feedback on the call will give greater visibility into end users perspective of the calling product and the overall calling quality and reliability".

Functionality to allow a customer at the end of a call a customer could ask their clients questions on how they felt the call went. The customer could ask their clients to rate the call and for other deeper level questions with regards to the call. The data from this functionally would be ingested by ACS and eventually stored in the customers Azure Monitor account. This would be a critical component to help customers and us understand subjective feedback by end users.

**Comment by ronniegeraghty** [comment]
Scheduled for Dec 12th from 3:05PM - 4PM PST.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/60d10840-98dc-ba75-b717-f1edabca9f96) (MS INTERNAL ONLY)
