### ISSUE TITLE
Board Review: Introducing ADP Data Management client library

### ISSUE THREAD

**Issue by imakhlin** [Azure/azure-sdk#5168]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library:
* Main contacts: 
* Expected stable release date for this library: NA

## About the Service 

* Link to documentation introducing/describing the service: [Architectural Overview](https://msazure.visualstudio.com/ADP/_wiki/wikis/ADP.wiki/139029/Architectural-Overview)
* Link to the service REST APIs: Find the references to new ADP APIs [here](https://github.com/Azure/azure-rest-api-specs-pr/issues/7483) 
* Is the goal to release a Public Preview, Private Preview, or GA? **Public Preview**

## About the client library

* Name of client library: Adp.DataManagement
* Link to library reference documentation:
* Is there an existing SDK library? If yes, provide link: No, we do generate SDK client for csharp only using the Autorest at build time. This SDK with convenient API is used internally by the backend services and not in use outside of ADP yet.

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:
1. Data Ingestion
2. Data Management (measurements, data-streams, classifications, etc.)

1. What is the app the developer is building that uses your client library? The client libraries will be used by partners and customers as convenient API for implementing data ingestion and data management functionality. The client libraries will also be used by UI (portal) developers. 
3. Who is the end-user of the application (the developer's customer)? Partners and large enterprise companies
4. What features of the API need to be explained in the sample so that someone could use this API in real app?
5. How does the **authentication** workflow look? Default Azure authentication.
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1
    * Link to library’s sample folder: 
* Champion scenario 2
    * Link to library’s sample folder:
* …
* Champion scenario n
    * Link to library’s sample folder:

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 

* Create a new resource
* Read the resource
* Modify the resource
* Delete the resource
* Error handling 
* Handling race conditions/concurrency issues

**Comment by ronniegeraghty** [comment]
Review drafted for Dec 7th from 2:05PM - 4PM PST.

**Comment by ronniegeraghty** [comment]
@imakhlin Please add any links to API Views or samples if available.

**Comment by ronniegeraghty** [comment]
Scheduled for Dec 7th from 2:05PM - 4PM PST

**Comment by ronniegeraghty** [comment]
@imakhlin Before the review session, the architect team will you to add some materials to this GitHub Issue. You can find a list of what materials are needed in [our policies docs](https://azure.github.io/azure-sdk/policies_reviewprocess.html#1-introductory-session) in the "Introductory Session" section, under "What to bring". Please let me know if you have any questions about the materials or need assistance in creating them. Thanks

**Comment by ronniegeraghty** [comment]
Rescheduling to Jan 10th from 9:05AM - 11AM PST.

**Comment by qiaozha** [comment]
The generated JS RLC api view for ADP https://apiview.dev/Assemblies/Review/1225057b3a4043cbae9e9765fd9c6fb3

**Comment by archerzz** [comment]
The generated CSharp SDK:
- PR: https://github.com/Azure/azure-sdk-for-net-pr/pull/1806
- API View: https://apiview.dev/Assemblies/Review/ab2cf057835f41bcb4663414be5a86b9

**Comment by lmazuel** [comment]
Python:
- https://apiview.dev/Assemblies/Review/c17ef0d977484bc1ad7d69acb042b14a

**Comment by ronniegeraghty** [comment]
@imakhlin Looks like the only tier 1 language were missing an API View for is Java. It would be really helpful if you could get that added to the issue ASAP so the architects can review it before the meeting. Thank you.

**Comment by haolingdong-msft** [comment]
Java:
PR: https://github.com/Azure/azure-sdk-for-java-pr/pull/1388

API View: https://apiview.dev/Assemblies/Review/3b77bee6b3b940ad9c85df75cee51df1

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/60d10840-98dc-ba75-1573-f1edabc8a450) (MS INTERNAL ONLY)
