### ISSUE TITLE
Update Azure cli library to add support for VMSS Plan name update

### ISSUE THREAD

**Issue by SamRakaba** [Azure/azure-sdk#519]
When creating an Redhat custom image, the plan information meta data is not carried with the image. if we are creating a scale set and use custom image with one plan and attempt to update to new image, the Plan information can only be done through ARM PATCH verb.
can we add support  for "Az vmss update " command

**Comment by Petermarcu** [comment]
Issue moved to [Azure/azure-cli #9981](https://github.com/Azure/azure-cli/issues/9981) via [**ZenHub**](https://www.zenhub.com/)
