### ISSUE TITLE
Add guidance for Circuit Breaker pipeline policies

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk#520]
## The Basics

* Which design guideline is affected?
_General Guideline 3.2.3 dealing with network requests_

* Which target languages are affected?
_All languages_

* Describe the change:
_We should add circuit breaking pipeline policies that can automatically stop retrying requests for a service after a certain number of failures in a given time window.  It'd be good to add them before we GA our client libraries so we can get feedback on our default configuration._

## Reasoning
I was recently hired to build a client library and naturally started by watching a [YouTube tutorial](https://www.youtube.com/watch?v=eWljhk1RvCM&t=6m53s).  It said I should use circuit breaking pipeline policies, but your various `Azure.Core` libraries have none.

**Comment by adrianhall** [comment]
Per @JeffreyRichter, this is not a concern with libraries, so dropping.
