### ISSUE TITLE
[Go] Release page for deprecated libraries has dead link for migration guide

### ISSUE THREAD

**Issue by sandeep-sen** [Azure/azure-sdk#5207]
Release page for deprecated libraries has wrong migration guide link, which leads 404
https://azure.github.io/azure-sdk/releases/deprecated/index.html#go

Link should be: https://aka.ms/azsdk/golang/t2/migration
Please update the release csv starting row 240.
https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/go-packages.csv#L240

**Comment by mario-guerra** [comment]
https://github.com/Azure/azure-sdk/pull/5208

**Comment by mario-guerra** [comment]
PR with fix has been merged.
