### ISSUE TITLE
Board Review: Distributed Tracing Preview 2

### ISSUE THREAD

**Issue by SuyogSoti** [Azure/azure-sdk#524]
https://gist.github.com/SuyogSoti/3b1d8b22f40eb3c1f34300a0565db55e

This gist tries to clear some up confusion up. There are 2 main confusions to clear up.

1. When is the tracing enabled for each languages
1. What spans should be generated when the user writes certain code. 
    1. Regular requests vs Paging vs Polling?
    1. How does Authentication and caching show up?

Related to: #501 #507

**Comment by adrianhall** [comment]
We just did a distributed tracing meeting with the arch board where this was covered.  Can you please work with @johanste to get specific answers to your questions?

**Comment by johanste** [comment]
I believe all these issues were covered in the meeting. Tracing requires opt in. Paging and polling, each outgoing request is traced. No relationship between requests (links) for preview 2. Authentication, each individual request is traced.
