### ISSUE TITLE
Potential issue with autogenerated package index includes

### ISSUE THREAD

**Issue by vmagelo** [Azure/azure-sdk#5241]
@weshaggard 

Looking at [Python package index page](https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-library-package-index) or [Javascript package index page](https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-library-package-index) there seems to be repeated entries in the "All libraries" table (second on each page).

For example, go to either page and search for "Communication Network Traversal". It appears once in the first table and twice in the second table (all libraries). The question is if that is correct?

The Python and JavaScript articles above above use these includes in the azure-dev-docs repo to pull in tables:

[python-new.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/includes/python-new.md)
[python-all.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/includes/python-all.md)
[javascript-new.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/includes/javascript-all.md)
[javascript-all.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/includes/javascript-new.md)

These includes look to be auto-generated. I went back in the history of the *python-all.md* file and it looks like on Dec 8 2021 refresh of file, duplicates started appearing. ([commit](https://github.com/MicrosoftDocs/azure-dev-docs-pr/commit/10754c64acf0094a8a2ac9fb6aa12284c95db6f2), [file](https://github.com/MicrosoftDocs/azure-dev-docs-pr/blob/10754c64acf0094a8a2ac9fb6aa12284c95db6f2/articles/includes/python-all.md) at that point). The checkin prior to this didn't have dups.

Again, was curious if this is by design or I don't understand what the "all" table represent.

Thanks!

**Comment by weshaggard** [comment]
Thanks for the bug report this is not by design this was a bug in the partition of the packages to sort the newer packages on top. I fixed that issue with https://github.com/Azure/azure-sdk/commit/f645302b48408c971c87eac5cb9febbfe617d1ea and so the next time the automation runs this should get fixed.
