### ISSUE TITLE
Board Review: event hubs buffered sender

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk#525]
I'd like to understand the plans (or lack thereof) to provide a buffered sender/producer for our event hubs libraries. Per my understanding, the plans include a batched sender, but no buffered sender, leaving the users of our library to do the heavy lifting in order to optimize network utilization balanced with latency.

**Comment by adrianhall** [comment]
Board update: Javier will see if this is a core requirement.  If it is, @johanste will meet with @ramya-rao-a to determine an API plan and bring that to the board.
