### ISSUE TITLE
Board Review: Introducing Azure AI Health Decision Support

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk#5253]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Health Decision Support
* Main contacts: asaflevi@microsoft.com
* Expected stable release date for this library: First Public Preview: March 2023

## About the Service 

* Link to documentation introducing/describing the service: 
* Link to the service REST APIs: 
* Is the goal to release a Public Preview, Private Preview, or GA?  Public preview

## About the client library

* Name of client library: Azure.AI.HealthDecisionSupport
* Link to library reference documentation: 
* Is there an existing SDK library? If yes, provide link: N/A

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
4. How does the **authentication** workflow look? 
   
See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1
    * Link to library’s sample folder:  https://github.com/Azure/azure-sdk-for-net-pr/blob/asaflevi/feature/healthdecisionsupport-sdk-for-net/sdk/healthdecisionsupport/Azure.AI.HealthDecisionSupport/samples/Sample_InferOncologyPhenotyping.md
* Champion scenario 2
    * Link to library’s sample folder:  https://github.com/Azure/azure-sdk-for-net-pr/blob/asaflevi/feature/healthdecisionsupport-sdk-for-net/sdk/healthdecisionsupport/Azure.AI.HealthDecisionSupport/samples/Sample_MatchTrials.md
* …
* Champion scenario n
    * Link to library’s sample folder:

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 

* Create a new resource
* Read the resource
* Modify the resource
* Delete the resource
* Error handling 
* Handling race conditions/concurrency issues

**Comment by ronniegeraghty** [comment]
@catalinaperalta Before the introduction session can be scheduled could you please add champion scenarios to this GitHub Issue. The scenarios can use pseudo code. This will give the architects an idea of how customers would use the SDK.

**Comment by catalinaperalta** [comment]
@asaflevi-ms will add more information to this issue.

**Comment by ronniegeraghty** [comment]
@catalinaperalta just a reminder that before we can schedule this session, we'll need to have the champion scenarios added to the issue.

**Comment by catalinaperalta** [comment]
Thanks for the reminder @ronniegeraghty! @asaflevi-ms is working on updating the issue with the champion scenarios. You two can coordinate scheduling the arch board together after that :) He is the main point of contact for this arch board.

**Comment by asaflevi-ms** [comment]
@ronniegeraghty 
champion scenarios attached (one for each inner model)

**Comment by catalinaperalta** [comment]
CADL apiview: https://apiview.dev/Assemblies/Review/205e1a393e0c4ed8b5a42fb5ba5988cd

**Comment by tg-msft** [comment]
.NET PR ApiView: https://apiview.dev/Assemblies/Review/8752b674208144f0b7ccb3c13343099c

**Comment by tg-msft** [comment]
After discussing offline with the Arch Board, we've settled on using `Azure.Health.*` as the technology group for this family of services.

**Comment by asaflevi-ms** [comment]
Thank you @tg-msft , @catalinaperalta 
For public preview we are going to release two packages with the following namespaces:
Azure.Health.Insights.ClinicalMatching
Azure.Health.Insights.CancerProfiling

**Comment by catalinaperalta** [comment]
cc: @tg-msft @srnagar @johanste @bterlson for approval on the package names

> Thank you @tg-msft , @catalinaperalta For public preview we are going to release two packages with the following namespaces: Azure.Health.Insights.ClinicalMatching Azure.Health.Insights.CancerProfiling
