### ISSUE TITLE
MGMT Namespace Review: Liftr Qumulo

### ISSUE THREAD

**Issue by shams11** [Azure/azure-sdk#5255]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Liftr Qumulo
* Main contacts: shamsthabrez@microsoft.com, santhoshkv@microsoft.com, oscardsouza@microsoft.com
* Expected code complete date: 23-Dec
* Expected release date: 11-Jan-2023

## About the Service 

* Link to documentation introducing/describing the service:  https://microsoftapc-my.sharepoint.com/:v:/r/personal/ahosabettu_microsoft_com/Documents/Recordings/Qumulo%20Private%20Preview%20Demo.mp4?csf=1&web=1&e=PqoYqn
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Liftr Qumulo
* Languages for this review: Python, Go, Java, JS

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by ronniegeraghty** [comment]
Review scheduled for Jan 11th, from 2:05PM - 4PM PST.

**Comment by xboxeer** [comment]
@ronniegeraghty  did Qumulo finish the namespace review?

**Comment by ronniegeraghty** [comment]
@xboxeer I don't a request for a namespace review from Liftr Qumulo. Would this be for their MGMT plane SDK?

**Comment by xboxeer** [comment]
@ronniegeraghty  yes this is for their mgmt. plane SDK. @shams11 would you help provide your client library namespace here so they can be reviewed in arch board review?

**Comment by ronniegeraghty** [comment]
> @ronniegeraghty yes this is for their mgmt. plane SDK. @shams11 would you help provide your client library namespace here so they can be reviewed in arch board review?

Normally MGMT Plane Namespace reviews are done with there own issue that includes the proposed namespaces for each language

**Comment by shams11** [comment]
> @ronniegeraghty yes this is for their mgmt. plane SDK. @shams11 would you help provide your client library namespace here so they can be reviewed in arch board review?

Our service name space is `Qumulo.Storage`

**Comment by ronniegeraghty** [comment]
@shams11 and @xboxeer, What I really need to understand here is what type of review request this is. Is this a request to have the MGMT Plane Library namespaces reviewed and approved or is this a request to have an introduction meeting with the Architecture board in preparation for a data plane release?

**Comment by xboxeer** [comment]
@ronniegeraghty from mgmt. sdk point of view we'd like service have their mgmt. plane sdk client library name reviewed in the introduction meeting. 
@shams11 we'd like to know the namespace for client library， example of client library name for mgmt plane like below
.NET
Resource Management - Confidential Ledger
Azure.ResourceManager.**ConfidentialLedger**
Java
Resource Management - Confidential Ledger
azure-resourcemanager-**confidentialledger**
JavaScript
Resource Management - Confidentialledger
@azure/arm-**confidentialledger**
Go/Golang
Resource Management - Confidentialledger
sdk/resourcemanager/confidentialledger/**armconfidentialledger**
Phyton
Resource Management - Confidential Ledger
azure-mgmt-**confidentialledger**

**Comment by ronniegeraghty** [comment]
> @ronniegeraghty Ronnie Geraghty FTE from mgmt. sdk point of view we'd like service have their mgmt. plane sdk client library name reviewed in the introduction meeting. @shams11 Shams Thabrez FTE we'd like to know the namespace for client library， example of client library name for mgmt plane like below .NET Resource Management - Confidential Ledger Azure.ResourceManager.**ConfidentialLedger** Java Resource Management - Confidential Ledger azure-resourcemanager-**confidentialledger** JavaScript Resource Management - Confidentialledger @azure/arm-**confidentialledger** Go/Golang Resource Management - Confidentialledger sdk/resourcemanager/confidentialledger/**armconfidentialledger** Phyton Resource Management - Confidential Ledger azure-mgmt-**confidentialledger**

Okay, it's not normally done that way so in the review I would be sure to mention that to the architects.

**Comment by tg-msft** [comment]
Adding a few links to Qumulo data plane API resources for today's review:
- [official link](https://qumulo.com/discover/technical-guide/rest-api/)
- [versioning philosophy](https://qumulo.com/blog/engineering-at-qumulo-rest-api/) where they mention they'll make breaking changes
- [documentation](https://care.qumulo.com/hc/en-us/articles/360060876334-Upgrading-your-Qumulo-Python-SDK)
- [python library](https://pypi.org/project/qumulo-api/)
- [github documentation](https://docs.qumulo.com/index.html) and [API intro](https://github.com/Qumulo/qumulo-api-introduction)
- [github repos](https://github.com/orgs/Qumulo/repositories) with a variety of random projects

**Comment by ronniegeraghty** [comment]
@shams11 Can you please add the proposed namespaces for Liftr Qumulo's Management SDKs. 
They should follow the examples @xboxeer provided a few comments up in this thread.

**Comment by pchoudhary-microsoft** [comment]
@ronniegeraghty For Qumulo's Management SDKs, we would want the namespace to be LiftrQumulo

**Comment by bterlson** [comment]
`@azure/arm-liftrqumulo` is fine for JS.

**Comment by JeffreyRichter** [comment]
I see that the proposed Go path is sdk/resourcemanager/liftrqumulo/armconfidentialledger but all the other languages changed the ending to liftrqumulo so should Go's be sdk/resourcemanager/liftrqumulo/armliftqumulo?

**Comment by annatisch** [comment]
`azure-mgmt-liftrqumulo` is fine for Python

**Comment by m-nash** [comment]
If I understand correctly the `Liftr` is [a business program within Microsoft's Developer Division organization](https://microsoft.sharepoint.com/sites/knowledgecenter/_layouts/15/TopicPagePreview.aspx?topicId=AL_oaGj7vfnSL87EYIykdpnaw&topicName=Liftr&lang=en&ls=Ans_Bing).  `Qumolo` is [a startup that deals with storage](https://qumulo.com/).  The ARM namespace seems to be `[Qumolo.Storage](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/liftrqumulo/resource-manager/Qumulo.Storage/preview/2022-10-12-preview/Qumulo.Storage.json#L83)`.

Since we typically don't want to use team names, but we have in used 3rd party brand names like [Kubernetes](https://www.nuget.org/packages/Azure.ResourceManager.Kubernetes/1.0.0-beta.1) and [Grafana](https://www.nuget.org/packages/Azure.ResourceManager.grafana) would all the languages be ok with.

.NET
Azure.ResourceManager.Qumulo
Java
azure-resourcemanager-qumulo
JavaScript
@azure/arm-qumulo
Go/Golang
sdk/resourcemanager/liftrqumulo/armqumulo
Phyton
azure-mgmt-qumulo

**Comment by annatisch** [comment]
Thanks @m-nash - that looks preferable to me!

**Comment by JonathanGiles** [comment]
I'm good with @m-nash's proposal

**Comment by JeffreyRichter** [comment]
Go will use sdk/resourcemanager/liftrqumulo/armqumulo

**Comment by ronniegeraghty** [comment]
Phase 2 of MGMT Plane Namespace approval started.

**Comment by ronniegeraghty** [comment]
Review Completed. Namespaces have been approved.

**Comment by nikhgup** [comment]
@ronniegeraghty can you please close this issue.
