### ISSUE TITLE
Microsoft.NetworkCloud MGMT Plane Namespace Review

### ISSUE THREAD

**Issue by vabelsare** [Azure/azure-sdk#5263]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

@ronniegeraghty  @kyle-patterson - please review this and rename title API Review/API Sign Off to management and/or client libraries Introducing .NET Microsoft.NetworkCloud  approval

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Bryan Strassner <bstrassner@microsoft.com>; Marina Bashtovaya <mbashtovaya@microsoft.com>; Jared Stein <jaredstein@microsoft.com>
* Main contacts: Vaishali Belsare <vabelsare@microsoft.com>; Uma Devi Chedalla <uchedalla@microsoft.com>
* Expected code complete date:  
* Expected release date: 1/6/2023

## About the Service 

* Link to documentation introducing/describing the service: AODS Solution-Document 2022-11-15.docx](https://microsoft.sharepoint.com/:w:/t/AFO-NC/EQqHS0BD3QdOlHsjz7rgvYMBEAqpQgZiAU3EJp1GZTSQ6w?e=Gd4esf)
* Link to the service REST APIs: [azure-rest-api-specs-pr/specification/networkcloud/resource-manager/Microsoft.NetworkCloud/preview/2022-09-30-preview at RPSaaSMaster · Azure/azure-rest-api-specs-pr (github.com)](https://github.com/Azure/azure-rest-api-specs-pr/tree/RPSaaSMaster/specification/networkcloud/resource-manager/Microsoft.NetworkCloud/preview/2022-09-30-preview)
* Link to GitHub issue for previous review sessions, if applicable:  NA

## About the client library

* Name of the client library:  NA 
* Languages for this review: 

management plane (ARM): Microsoft.Networkcloud.NET
 Languages for this review: .NET

### .NET

* APIView Link: azure-rest-api-specs-pr/specification/networkcloud/resource-manager/Microsoft.NetworkCloud/preview/2022-09-30-preview at RPSaaSMaster · Azure/azure-rest-api-specs-pr (github.com)](https://github.com/Azure/azure-rest-api-specs-pr/tree/RPSaaSMaster/specification/networkcloud/resource-manager/Microsoft.NetworkCloud/preview/2022-09-30-preview
* Link to Champion Scenarios/Quickstart samples:

•	Go/Golang
Resource Management - Confidentialledger
sdk/resourcemanager/networkcloud/armnetworkcloud
•	Python
Resource Management - Confidential Ledger
azure-mgmt-networkcloud

And these should follow the same:
•	.NET
Resource Management - Confidential Ledger
Azure.ResourceManager.NetworkCloud
•	Java
Resource Management - Confidential Ledger
azure-resourcemanager-networkcloud
•	JavaScript
Resource Management - Confidentialledger
@azure/arm-networkcloud

**Comment by vabelsare** [comment]
@ronniegeraghty  @kyle-patterson - please review this and rename title API Review/API Sign Off to management and/or client libraries Introducing .NET Microsoft.NetworkCloud  approval

**Comment by ronniegeraghty** [comment]
@vabelsare before we can begin the namespace review, you need to add the proposed namespaces for each of the tier 1 programing languages the SDK team supports as well as Go. You can find examples of namespaces for each programming language at the bottom of this [page](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/821/Naming-for-new-initial-management-or-client-libraries-(new-SDKs)).

**Comment by vabelsare** [comment]
@ronniegeraghty @kyle-patterson  - Updated the Go, Python, Java Script related namespaces entry above per request.

**Comment by vabelsare** [comment]
Updated the Microsoft.NetworkCloud MGMT Plane Namespace Review * Issue #5263 * Azure/azure-sdk (github.com)<https://github.com/Azure/azure-sdk/issues/5263> with required updates.

Thank you,
Vaishali

**Comment by ronniegeraghty** [comment]
Starting offline review

**Comment by johanste** [comment]
Package name good for Python

**Comment by srnagar** [comment]
Package name `azure-resourcemanager-networkcloud` is good for Java.

**Comment by ArthurMa1978** [comment]
Good for .Net

**Comment by vabelsare** [comment]
@ronniegeraghty @kyle-patterson - Based on comments, am I to assume that only 2 approvals is now remaining - for Go and Javascript?

**Comment by ronniegeraghty** [comment]
@vabelsare We are also still waiting on an approval from a .NET architect. I'll be sending out reminder messages to our architects today, to review this issue.

**Comment by JeffreyRichter** [comment]
sdk/resourcemanager/networkcloud/armnetworkcloud is good for Go

**Comment by vabelsare** [comment]
@ronniegeraghty -I see Arthur approved for .Net. So Go, Java, ,Net, Python have approved. So now only JavaScript is remaining, right?

**Comment by vabelsare** [comment]
@ronniegeraghty @kyle-patterson  - Do we have ETA for these pending approvals? The way I understand, we cannot start till we get these approvals.

**Comment by ronniegeraghty** [comment]
> @ronniegeraghty Ronnie Geraghty FTE @kyle-patterson Kyle Patterson FTE - Do we have ETA for these pending approvals? The way I understand, we cannot start till we get these approvals.

Were just waiting on JS now. I'll remind them again today, to take a look here.

**Comment by joheredi** [comment]
@azure/arm-networkcloud for JS looks good to me

**Comment by ronniegeraghty** [comment]
Looks like all the languages have gotten approval. 
@vabelsare your good to move forward.

**Comment by vabelsare** [comment]
Thank you so much!
