### ISSUE TITLE
Standardize Prettier configuration

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#528]
The configuration files for tool `Prettier` should be standardized across all repos.  Proposal:

1. Use a single `.prettierrc` file at the repo root
2. All config files should be named `.prettierrc` and use the YAML format (no `.prettierrc.json`)
3. No `.prettierrc` files in sub-folders unless there's a good reason.  We want to be as consistent across folders as possible.
4. Use the "override" feature to specify different formats for different files (e.g. double-quotes for `*.yml` but single-quotes for `*.js`)

**Comment by kurtzeborn** [comment]
@chidozieononiwu, this issue is over a year old at this point.  It's definitely tools related, but @weshaggard and I suspect there isn't any work left to do here.  Please take a look and close if it's already done.

**Comment by chidozieononiwu** [comment]
So far prettier has not been used on any other repo other than JS. @mikeharder do you still think ther is a need to make the configuration cross repo. Also right now the json style is still used, I can go ahead and do the work to convert to the yml format if that is still useful.

**Comment by mikeharder** [comment]
I think it's fine to close this out until there is more demand for it.
