### ISSUE TITLE
Board Review: azure-cosmos-db-query-editor React Component published as azure/ NPM package

### ISSUE THREAD

**Issue by languy** [Azure/azure-sdk#5287]
## Contacts and Timeline

* Responsible service team: Azure Cosmos DB (portal team)
* Main contacts: Laurent Nguyen (languye)
* Expected code complete date: First implementation completed as of 12/23/22. Development is ongoing.
* Expected release date: Release to NpmJS asap

## About the Service 
We are developing a Query Editor that can be consumed by our various open-source projects.
The query editor is a small UI typescript React component. It allows the user to input a query and displays its result in a collapsible tree form or simply as a JSON string. It is defined to be integrated into a React app.
The plan is to release this component as an NPM package, so that our other typescript open-source projects can consume it.
Although the purpose is mainly for code-sharing (it is not our main product), the query editor is implemented as a generic re-usable component. The project has received approval from our MS OSS folks to open-source and for the repo name.

Link to [azure-cosmos-db-query-editor github repo](https://github.com/Azure/azure-cosmos-db-query-editor).
Although the definition file is automatically generated, here is [the current component API top-level file](https://github.com/Azure/azure-cosmos-db-query-editor/blob/main/src/index.ts).

We were advised to release the npm package as a scoped package and the suggestion was to contact this team to get approval for the azure scope.

## About the client library

* Name of the client library: azure-cosmos-db-query-editor
* Languages for this review: typescript

## Artifacts required (per language)
The artifacts include a [minified javascript module](https://github.com/Azure/azure-cosmos-db-query-editor/blob/206cadf03a019581fc7fc67070dfc1cc37055328/package.json#L6) and its typescript definition file which are generated at build time by parcel.

### TypeScript
The documentation on how to use is not yet written as the API is still in flux, but there is a [test application](https://github.com/Azure/azure-cosmos-db-query-editor/tree/main/testapp) that integrates the component in [this file](https://github.com/Azure/azure-cosmos-db-query-editor/blob/main/testapp/src/index.tsx).

**Comment by ronniegeraghty** [comment]
Scheduled for Feb 1st from 2:05PM - 4PM PST.
