### ISSUE TITLE
Update release pipelines to PowerShell Core 6 (pwsh)

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#530]
All build scripts and pipelines are being updated to PowerShell Core 6 (`pwsh`) in #529.  The same should be done for the release pipelines, however they are currently defined in the DevOps UI rather than YAML, so I think we should defer this work until the release pipelines are converted to YAML.

**Comment by mitchdenny** [comment]
Having a pending PR on internal for this.
