### ISSUE TITLE
Board Review: Introducing Azure.OpenAI

### ISSUE THREAD

**Issue by jpalvarezl** [Azure/azure-sdk#5328]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: **AI Cognitive Services**
* Main contacts: 
  * **Service: Ralf Beckers (Olivier Nano)**
  * **Client library: Travis Wilson (Rob Chambers)**
* Expected stable release date for this library: **February 6th, 2023**

## About the Service 

* Link to documentation introducing/describing the service: [link](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/)
* Link to the service REST APIs: [cadl files](https://github.com/Azure/azure-rest-api-specs/tree/feature/cognitiveservices/openai-cadl/specification/cognitiveservices/OpenAI.Inference)
* Is the goal to release a Public Preview, Private Preview, or GA? **The Azure OpenAI service entered GA in December 2022**

## About the client library

* Name of client library: 
  * **Azure.OpenAI** (We have implemented "Inference" so far, but we plan to add "Authoring" in the near future)
* Link to library reference documentation:
  * https://github.com/Azure/azure-sdk-for-net/pull/33457/files#diff-f4ce28190a20fc7c68498a6d365edf0090f20d7215c9833d94562feaa8292490
* Is there an existing SDK library? If yes, provide link: 
  * **No**, however there is currently a working branch with the intended code that can be found [here](https://github.com/Azure/azure-sdk-for-net/pull/33457)

Python ApiView: https://apiview.dev/Assemblies/Review/131735ded1a144a6a15ee68831e25852
Java ApiView: https://apiview.dev/Assemblies/Review/cff7890772ed40e8a5785e5efda9d2e2
.NET ApiView: https://apiview.dev/Assemblies/Review/a4d96437df8848ada1339fbf0a0f29c8
JS/TS ApiView: https://apiview.dev/Assemblies/Review/a20cde963d8942a1940722acaad389eb

## Step 1: Champion Scenarios 

[README](https://github.com/Azure/azure-sdk-for-net/blob/glharper-openapi/sdk/openai/Azure.OpenAI.Inference/README.md) link containing more details and code samples for the champion scenario.

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?
**Applications leveraging [embeddings](https://beta.openai.com/docs/api-reference/embeddings) and/or [completions](https://beta.openai.com/docs/api-reference/completions/create) of OpenAI**
2. Who is the end-user of the application (the developer's customer)?
**Any current or new user of OpenAI Inference features.**
3. What features of the API need to be explained in the sample so that someone could use this API in real app?
See above in question 1. the link to the public documentation of `embeddings` and `completions`.
4. How does the **authentication** workflow look? 
By using either `Azure.Core.AzureKeyCredential` or `Azure.Core.TokenCredential `

See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario `Completions`
    * Link to library’s sample folder: [ChatBot example](https://github.com/Azure/azure-sdk-for-net/pull/33457/commits/928be1e5e5a15a5a233743d19067fe56c3282cc8#diff-1fa17e895d6cf5045c1be7ffb027c5428d98ca0b7470e4899c89da9a49cc1563)

## Step 2: Quickstart Samples (Optional)

The `GenerateChatbotResponses` method gives an example of generating text responses to input prompts.

```C#
using System;
using System.Collections.Generic;
using Azure.OpenAI.Inference.Models;

namespace Azure.OpenAI.Inference.Tests.Samples
{
    public partial class Chatbot
    {
        public void GetChatbotResponses()
        {
            // Replace with your Azure subscription key
            string key = "YOUR_AZURE_KEY";
            string endpoint = "http://myaccount.openai.azure.com/";
            OpenAIClient client = new OpenAIClient(new Uri(endpoint), new AzureKeyCredential(key));

            #region Snippet:GenerateChatbotResponses
            List<string> examplePrompts = new(){
                "How are you today?",
                "What is Azure OpenAI?",
                "Why do children love dinosaurs?",
                "Generate a proof of Euler's identity",
                "Describe in single words only the good things that come into your mind about your mother.",
            };

            foreach (var prompt in examplePrompts)
            {
                Console.Write($"Input: {prompt}");
                var request = new CompletionsRequest();
                request.Prompt.Add(prompt);

                Completion completion = client.Completions("myModelDeployment", request);
                var response = completion.Choices[0].Text;
                Console.WriteLine($"Chatbot: {response}");
            }
            #endregion
        }
    }
}
```

**Comment by ronniegeraghty** [comment]
Scheduled for Jan 25th from 10:05AM - 12PM PST.

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/96ae0840-98dc-ba75-2c1d-f1ed9ced89a0) (MS INTERNAL ONLY)
