### ISSUE TITLE
PRs created by bots with certain tags should not assign Code Owners

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk#533]
Example PR: https://github.com/Azure/azure-sdk-for-js/pull/4505

In this case the CODEOWNERS policy assigned @ramya-rao-a to a PR targeting a non-master branch. While an email filter would help keep these out of an engineer's inbox, they'll stay in the GitHub notifications. 

Research on this issue shows a few options:  

* Keeping different CODEOWNERS files in different branches will fix this behavior but we would need to cherry pick changes. This approach is complex and prone to a variety of failure modes over time. Described here: https://github.com/Azure/azure-sdk-for-js/pull/4500/files 

* Other tools exist today (Open API Hub) which might satisfy the engineering needs that the current automation does while not opening PRs. This would require investigating and changing existing habits. 

* A test with @bsiegel revealed that we could react to these PRs and remove the codeowners. This would remove (or prevent appearance of) notifications in GitHub notifications UI and any email notifications could be handled with email filter rules. We might be able to use existing workflow systems to handle this.

**Comment by ramya-rao-a** [comment]
Can we only react to PRs with the `SpecPRInProgress` label instead of PRs that dont target master branch?

**Comment by danieljurek** [comment]
We should be able to. I'll be investigating the workflow system once I get access.

**Comment by danieljurek** [comment]
Work item opened to track this: #598 

After some discussion w/ @lmazuel weeks ago the CODEOWNERS behavior is by design though some PRs may incorporate too many changes to too many projects resulting in spammy behavior. 

The two fixes are: 
* Open a bug referencing instances where the bot opens a noisy PR (#598) 
* Update CODEOWNERS when gaps in coverage appear. Leads should not
