### ISSUE TITLE
Board Review: ACS Cross Platform Messaging and WebUI

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-sdk#5360]
Merge of Two ACS Arch Board Review requests. 

## Cross Platform Messaging
New SDK Review meeting has been requested.

Service Name: IC3 ACS Cross Platform Messaging
Review Created By: Jorge Garcia Hirota
Review Date: 1/25/2023 2:05 PM PT

Hero Scenarios Link: Not Provided
Architecture Diagram link: Not Provided
Core Concepts Doc Link: Not Provided
APIView Links: [.NET](https://apiview.dev/Assemblies/Review/06657e2f6b3a40d0b538e04a675fcd6d?diffRevisionId=c2c5e1ad34e64b938c974efafaeca20b&diffOnly=False&revisionId=459beffc85794a28a9afd6ee22590c39&doc=False),

Description: join a rooms using different roles like teacher(presenter in rooms) and student (attendee in rooms), presenter has all permissions like share screen and remove participant, while attendee only has the permission of listen to the meeting without talking.
    
## WebUI
New SDK Review meeting has been requested.

Service Name: ACS WebUI
Review Created By: Jorge Garcia Hirota
Review Date: 1/23/2023 2:05 PM PT

Hero Scenarios Link: Not Provided
Architecture Diagram link: Not Provided
Core Concepts Doc Link: Not Provided

Description of the material to be reviewed/changed: Add support to using teams identity to join a call
Champion scenarios that briefly explain how developers will use your API: developers will follow the way how previous ACS call works, but replace some key functions to teams call function and they will need to provide a teams user token(AAD Token) before they create the teamsCallAgent
Languages for this review: TypeScript
Artifacts per language: [TS](https://apiview.dev/Assemblies/Review/b6f14545f42f4e49adea543026d9d53b/fb72a8a140424b3f8b4f367990e510bb?diffRevisionId=f72961d8973243648f547647e0992b83&doc=False&diffOnly=True)

The joint review for these 2 topics will be held on Jan 23rd, 2023, from 2:05PM - 4PM PST. 
The main contact on the service side is @garchiro7

**Comment by garchiro7** [comment]
Code sample, **Cross Platform Messaging:**

Champion scenarios that briefly explain how developers will use your API:

            var fileResponse = notificationMessagesClient.DownloadMedia(mediaId);
            using (Stream outStream = File.OpenWrite(rootDirectory + "file1.jpg"))
            {
                fileResponse.ContentStream.CopyTo(outStream);
            }

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/8d7b0840-98dc-ba75-a58d-f1ed9c5683b9) (MS INTERNAL ONLY)
