### ISSUE TITLE
Board Review: [Cognitive Services - Health Decision Support]

### ISSUE THREAD

**Issue by asaflevi-ms** [Azure/azure-sdk#5421]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team:
* Main contacts: @asaflevi-ms 
* Expected code complete date:
* Expected release date: March 31 2023

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Azure.AI.HealthDecisionSupport
* Languages for this review:

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: https://apiview.dev/Assemblies/Review/8752b674208144f0b7ccb3c13343099c
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-net-pr/tree/asaflevi/feature/healthdecisionsupport-sdk-for-net/sdk/healthdecisionsupport/Azure.AI.HealthDecisionSupport/samples

### Java

* APIView Link:  https://apiview.dev/Assemblies/Review/cdc0a31e48bf40ee8fee0aee9511c7f3
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-java-pr/tree/asafarnon/feature/healthdecisionsupport-sdk-for-java/sdk/healthdecisionsupport/azure-ai-healthdecisionsupport/src/samples

### Python

* APIView Link:  https://apiview.dev/Assemblies/Review/66fda628dba3497990f63b8d439866b6
* Link to Champion Scenarios/Quickstart samples:  https://github.com/Azure/azure-sdk-for-python-pr/tree/asaflevi/feature/healthdecisionsupport-sdk-for-python/sdk/healthdecisionsupport/azure-ai-healthdecisionsupport/samples
  
### TypeScript

* APIView Link: TBD
* Link to Champion Scenarios/Quickstart samples: TBD

### CADL

* APIView Link: https://apiview.dev/Assemblies/Review/205e1a393e0c4ed8b5a42fb5ba5988cd
* 

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by asaflevi-ms** [comment]
Cadl PR that related to this issue: https://github.com/Azure/azure-rest-api-specs-pr/pull/10411
Introduction review related to this issue: https://github.com/Azure/azure-sdk/issues/5253

**Comment by ronniegeraghty** [comment]
Hi @asaflevi-ms 
We're transitioning to scheduling all Architecture Board Reviews using our [Scheduling Tool](https://apps.powerapps.com/play/e/ed2ffefd-774d-40dd-ab23-7fff01aeec9f/a/f0a98ca4-117c-4d4b-a06a-3e2cdfe46753?event=bdc70dab-458d-ed11-81ad-000d3a3418aa&skipmetadata=true).
Please use the link to the Scheduling Tool to scheduling this meeting, then close this issues, as the tool will open it's own issue.
Let me know if you have any questions about the process.

**Comment by asaflevi-ms** [comment]
Hi @ronniegeraghty 
Looking at the [Scheduling Tool](https://apps.powerapps.com/play/e/ed2ffefd-774d-40dd-ab23-7fff01aeec9f/a/f0a98ca4-117c-4d4b-a06a-3e2cdfe46753?event=bdc70dab-458d-ed11-81ad-000d3a3418aa&skipmetadata=true). It doesn’t give us time that is reasonable to our time zone (12:00AM – 02:00AM local time)
We can have a meeting between 9:00AM-11:00AM (pacific time) which is 7:00PM-9:00PM (local time).
Can you help with that?

**Comment by ronniegeraghty** [comment]
Yes, I can help with that. If you look at the scheduling tool you should be able to see what days are still open. Let me know which of those days works best for you, and I'll check with the architect team and see if they can meet from 9AM - 11AM PST that day. Genral rule of thumb is that Wednesdays are not good for that morning time slot for many of the architects.

**Comment by ronniegeraghty** [comment]
@asaflevi-ms, 
Just pinging again on my question above. Could you take a look at the open days on the scheduling tool and tell me which day will work for your team from 9AM - 11AM PST. Then I'll check with the architects to see if that day works for an early session. Again, Wednesdays are usually no good for an early session.

**Comment by catalinaperalta** [comment]
@asaflevi-ms should we close this issue and reopen it closer to your GA date? Or are you planning on getting some more feedback in the interim?

**Comment by asaflevi-ms** [comment]
@ronniegeraghty, @catalinaperalta 
Yes,
This issue can be closed.

Our current goal is GA end of November 2023.
Thank you.
