### ISSUE TITLE
Board Review: Text Analytics

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk#5425]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Cognitive Service for Language
* Main contacts: @kristapratico @mssfang @joseharriaga @minhanh-phan @deyaaeldeen
* Expected code complete date: 03/10/2023
* Expected release date: 03/14/2023

## About the Service 

* Link to documentation introducing/describing the service: [What is new in Azure Cognitive Service for Language in Octorber 2022](https://learn.microsoft.com/en-us/azure/cognitive-services/language-service/whats-new?tabs=java#october-2022)
* Link to the service REST APIs: [Swagger document](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/Language/preview/2022-10-01-preview/analyzetext.json)
* Link to GitHub issue for previous review sessions, if applicable: https://github.com/Azure/azure-sdk/issues/2188, https://github.com/Azure/azure-sdk/issues/3167, https://github.com/Azure/azure-sdk/issues/3294, https://github.com/Azure/azure-sdk/issues/3774, https://github.com/Azure/azure-sdk/issues/4339, https://github.com/Azure/azure-sdk/issues/4357, 

## About the client library

* Name of the client library: Azure Text Analytics
* Languages for this review: .NET, Python, JavaScript, Java

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link: [link](https://apiview.dev/Assemblies/Review/2454aa18c96c4d559994364cc99dfba9?diffRevisionId=537d308957254d2aa333c49ac21c42df&diffOnly=False&revisionId=fd3313e767614631a4af221cc004cc1f&doc=False)
* Link to Champion Scenarios/Quickstart samples: [link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/textanalytics/Azure.AI.TextAnalytics/samples)

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link: [link](https://apiview.dev/Assemblies/Review/f654d0b58676400a9fe225b5df013d73)
* Link to Champion Scenarios/Quickstart samples: [link](https://github.com/kristapratico/azure-sdk-for-python/tree/ta-beta-updates/sdk/textanalytics/azure-ai-textanalytics/samples)
  
### TypeScript

* APIView Link: [link](https://apiview.dev/Assemblies/Review/28b09dacde3c4abda59954a7ab02dab5?diffRevisionId=787ebbcafed24f5b8424c0ad5a97897c&diffOnly=False&revisionId=df89cfcc9c3845ea818ca5bc8c68264f&doc=False)
* Link to Champion Scenarios/Quickstart samples: [link](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/cognitivelanguage/ai-language-text/samples/v1-beta)

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by ronniegeraghty** [comment]
Hi @deyaaeldeen,
We're transitioning to scheduling all Architecture Board Reviews using our [Scheduling Tool](https://apps.powerapps.com/play/e/ed2ffefd-774d-40dd-ab23-7fff01aeec9f/a/f0a98ca4-117c-4d4b-a06a-3e2cdfe46753?event=bdc70dab-458d-ed11-81ad-000d3a3418aa&skipmetadata=true).
Please use the link to the Scheduling Tool to scheduling this meeting, then close this issues, as the tool will open it's own issue.
Let me know if you have any questions about the process.

**Comment by deyaaeldeen** [comment]
@ronniegeraghty thanks! I opened https://github.com/Azure/azure-sdk/issues/5476
