### ISSUE TITLE
Board Review: Microsoft.ManagedNetworkFabric Mgmt Plane Namespace Review

### ISSUE THREAD

**Issue by surajmb** [Azure/azure-sdk#5428]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: Network Fabric Automation
* Main contacts: Suraj MB (surmb@microsoft.com), Anmol Agarwala (anmaga@microsoft.com), Rakesh Malipatil (rmalipatil@microsoft.com), Chandrakiran Sarvepally (chsarvep@microsoft.com)
* Expected code complete date:
* Expected release date: 1/6/2023

## About the Service 

* Link to documentation introducing/describing the service: https://aka.ms/afo-nfa
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs-pr/tree/RPSaaSMaster/specification/managednetworkfabric/resource-manager/Microsoft.ManagedNetworkFabric
* Link to GitHub issue for previous review sessions, if applicable: NA

## About the client library

* Name of the client library: NA
* Languages for this review:

### .NET
Resource Management - Confidential Ledger
Azure.ResourceManager.ManagedNetworkFabric

### Java

Resource Management - Confidential Ledger
azure-resourcemanager-managednetworkfabric

### Python

Resource Management - Confidential Ledger
azure-mgmt-managednetworkfabric
  
### JavaScript

Resource Management - Confidentialledger
@azure/arm-managednetworkfabric

### Go/Golang
Resource Management - Confidentialledger
sdk/resourcemanager/managednetworkfabric/armmanagednetworkfabric

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by JonathanGiles** [comment]
Fine with Java

**Comment by annatisch** [comment]
Looks good for Python

**Comment by joheredi** [comment]
Looks good for Javascript

**Comment by m-nash** [comment]
Fine with dotnet

**Comment by surajmb** [comment]
Thanks everyone for the review. @kyle-patterson  @ronniegeraghty , need your final review as well and sign-off :)

**Comment by ronniegeraghty** [comment]
> Thanks everyone for the review. @kyle-patterson Kyle Patterson FTE @ronniegeraghty Ronnie Geraghty FTE , need your final review as well and sign-off :)

Just waiting on the Go Architect to approve the Go namespace.

**Comment by JeffreyRichter** [comment]
Go will use sdk/resourcemanager/managednetworkfabric/armmanagednetworkfabric

**Comment by ronniegeraghty** [comment]
All languages have been approved. You're good to move forward.
