### ISSUE TITLE
Add .NET guidance for "pubternal" usage

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk#544]
We should have formal guidance for the usage of "pubternal" (public APIs shipped in .Internal namespace)

I think the guidance should be:

DO NOT use pubternal for general purpose libraries, like the Azure SDK libraries.
CONSIDER using InternalVisibleTo if you must hide APIs of a shared dll

cc: @terrajobst, @bartonjs

**Comment by terrajobst** [comment]
The DO NOT guideline makes sense.

IVT is just one option. Other options include not exposing the assemblies in the ref set of the NuGet package (i.e. the customer can't access the API without hacking the package).
