### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) - SIP routing, new version of API

### ISSUE THREAD

**Issue by nostojicMs** [Azure/azure-sdk#5441]
## Contacts and Timeline

* Responsible service team: ACS-PSTN
* Main contacts: [acs-pstn@microsoft.com](mailto:acs-pstn@microsoft.com), [nostojic@microsoft.com](mailto:nostojic@microsoft.com)
* Expected code complete date: 
* Expected release date:

## About the Service 

* Link to documentation introducing/describing the service: https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/ESvU8UOBK-ZMn_2frVj_WLcB50ssGwrGZmCp4v-Fn-C-aQ?e=IoMQEx
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/pull/19502
* Link to GitHub issue for previous review sessions, if applicable: 

## About the client library

* Name of the client library: Sip Routing
* Languages for this review: Javascript

### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/1540546a90684bb399c00658f70be448
* Link to Champion Scenarios/Quickstart samples: https://github.com/Azure/azure-sdk-for-js/tree/ef9f8e35e533b13e01b69a9f08a969bb74200d53/sdk/communication/communication-phone-numbers/samples/v1/javascript/siprouting

**Comment by ronniegeraghty** [comment]
Hi @nostojicMs, 
We're transitioning to scheduling all Architecture Board Reviews using our [Scheduling Tool](https://apps.powerapps.com/play/e/ed2ffefd-774d-40dd-ab23-7fff01aeec9f/a/f0a98ca4-117c-4d4b-a06a-3e2cdfe46753?event=bdc70dab-458d-ed11-81ad-000d3a3418aa&skipmetadata=true).
Please use the link to the Scheduling Tool to scheduling this meeting, then close this issues, as the tool will open it's own issue. 
Let me know if you have any questions about the process.

**Comment by ronniegeraghty** [comment]
@nostojicMs, If the linked Issue will cover the same topics as this issue, please close this issue.
