### ISSUE TITLE
Board Review: Easm Mgmt Plane Namespace Review

### ISSUE THREAD

**Issue by nathanfalke** [Azure/azure-sdk#5499]
## Contacts and Timeline

* Responsible service team: [riskiq_easm@microsoft.com](mailto:riskiq_easm@microsoft.com)
* Main contacts:
  - Nate Falke, [nathanfalke@microsoft.com](mailto:nathanfalke@microsoft.com), @nathanfalke
  - Brian Zak, [brianzak@microsoft.com](mailto:brianzak@microsoft.com), @eqtip
  - Nisha Bhatia, [nishabhatia@microsoft.com](mailto:nishabhatia@microsoft.com), @nishabhatia-msft

## About the Service 

* Link to documentation introducing/describing the service: [External Attack Surface Management](https://learn.microsoft.com/en-us/azure/external-attack-surface-management/)
* Link to the service REST APIs: [2022-04-01-preview/easm.json](https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSMaster/specification/riskiq/data-plane/Microsoft.Easm/preview/2022-04-01-preview/easm.json)
* Link to GitHub issue for previous review sessions, if applicable:  https://github.com/Azure/azure-sdk/issues/5062

## About the client library

suggested management client name:
* Name of the client library: easm

**Comment by ronniegeraghty** [comment]
Here are the generated namespaces: 

- .NET: `Azure.ResourceManager.DefenderEasm`
- Go: `sdk/resourcemanager/denfender/armdefendereasm`
- Java: `azure-resourcemanager-defendereasm`
- JavaScript: `@azure/arm-defendereasm`
- Python: `azure-mgmt-defendereasm`

@nathanfalke please give you sign off on these names with a comment or a 👍reaction.

**Comment by m-nash** [comment]
Easm seems to be a brand name by Microsoft which we typically try to avoid.  When looking at the ARM namespace it was odd since the [link provided](https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSMaster/specification/riskiq/data-plane/Microsoft.Easm/preview/2022-04-01-preview/easm.json) falls under data-plane folder and none of the [URI's](https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSMaster/specification/riskiq/data-plane/Microsoft.Easm/preview/2022-04-01-preview/easm.json#L21) had provider segments in them.

Can you help clarify whether this is an ARM service and if so what the URI's will be? Typically we see /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}`/provider/{namespace}`/workspaces/{workspaceName} but the highlighted section is missing.

**Comment by m-nash** [comment]
It looks like the [dataplane library](https://github.com/Azure/azure-sdk/issues/5062#issuecomment-1331471859) will keep `Easm` in the name.  In that case its probably best to keep the continuity between the two.

Dotnet is fine with `Azure.ResourceManager.DefenderEasm`

**Comment by nathanfalke** [comment]
I was under the impression that a java namespace would look more like `com.azure. resourcemanager.defendereasm` - am I thinking of something else?

additionally, there's a typo in the go name - `denfender`

**Comment by ronniegeraghty** [comment]
> I was under the impression that a java namespace would look more like `com.azure.resourcemanager.defendereasm` - am I thinking of something else?
> 
> additionally, there's a typo in the `Go` name - `denfender`

Fixed the typo in the Go lib name. 
In Java the lib name with it's Group ID will be `com.azure.resourcemanager.azure-resourcemanager-defendereasm`

**Comment by ronniegeraghty** [comment]
@nathanfalke if the proposed names look good with the typo fix and the Java name looks good, knowing the group ID will be added, let me know and we can move on to the next phase of the approval process.

**Comment by nathanfalke** [comment]
> `com.azure.resourcemanager.azure-resourcemanager-defendereasm`

just for a bit of background info here, why is this the choice over `com.azure.resourcemanager.defendereasm`? 
our team is curious about the reasoning behind the repetition

**Comment by ronniegeraghty** [comment]
> > `com.azure.resourcemanager.azure-resourcemanager-defendereasm`
> 
> just for a bit of background info here, why is this the choice over `com.azure.resourcemanager.defendereasm`? our team is curious about the reasoning behind the repetition

I can ask the Java SDK architects to respond why the Java MGMT Plane SDK name patter is this way.

**Comment by ronniegeraghty** [comment]
@nathanfalke, I've just clarified with the Java Architect. 
There are two parts to the Java naming. 
1. The Maven Artifact ID: `azure-resourcemanager-defendereasm`
2. The package name: `com.azure.resourcemanager.defendereasm`
The package name will follow what you suggested. 
Sorry for the confusion. If that looks okay with you, then we can move on to phase 2 of the approval process.

**Comment by nathanfalke** [comment]
> * .NET: `Azure.ResourceManager.DefenderEasm`
> * Go: `sdk/resourcemanager/defender/armdefendereasm`
> * Java: `com.azure.resourcemanager.defendereasm` (maven artifact id: `azure-resourcemanager-defendereasm `)
> * JavaScript: `@azure/arm-defendereasm`
> * Python: `azure-mgmt-defendereasm`

just to confirm, is this the final set of names? (if so, looks good to me)

**Comment by ronniegeraghty** [comment]
> > * .NET: `Azure.ResourceManager.DefenderEasm`
> > * Go: `sdk/resourcemanager/defender/armdefendereasm`
> > * Java: `com.azure.resourcemanager.defendereasm` (maven artifact id: `azure-resourcemanager-defendereasm `)
> > * JavaScript: `@azure/arm-defendereasm`
> > * Python: `azure-mgmt-defendereasm`
> 
> just to confirm, is this the final set of names? (if so, looks good to me)

Yes

**Comment by nathanfalke** [comment]
moving on to phase 2 of the process sounds good to me

**Comment by ronniegeraghty** [comment]
Review completed. Namespaces have been approved.
