### ISSUE TITLE
Publish step should enforce working links

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk#552]
It's possible today for links in package info (e.g. Nuget "Project Site") to link to 404 pages. A tool could visit all URLs associated with a release and validate that we get a 2xx or 3xx code back and fail the release in the event of error http codes (e.g. 4xx or 5xx)

**Comment by danieljurek** [comment]
Special thanks to @AlexGhiondea 's tool for filing this issue

**Comment by sima-zhu** [comment]
The issue has been addressed by verify-link.yml and added to all language repo. Closed the issue for now. Please feel free to reopen if anything undone.
