### ISSUE TITLE
Health Insights 1.0.0b1

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#5535]

**Comment by msyyc** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/29339

**Comment by asaflevi-ms** [comment]
@lmazuel 
New name is Health Insights.

**Comment by lmazuel** [comment]
As of March 27th:
Java:  PR in review, not merged yet.
Python: PR in review, in progress.
Dotnet:  PR merged.   SDK not released.

**Comment by lmazuel** [comment]
Released all in 4/11
