### ISSUE TITLE
DevCenter 1.0.0b2

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk#5556]

**Comment by msyyc** [comment]
python released: https://pypi.org/project/azure-developer-devcenter/1.0.0b2/

**Comment by lmazuel** [comment]
https://www.nuget.org/packages/Azure.Developer.DevCenter/1.0.0-beta.2
https://www.npmjs.com/package/@azure-rest/developer-devcenter
https://mvnrepository.com/artifact/com.azure/azure-developer-devcenter
