### ISSUE TITLE
Make new packages as needing review

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#5565]
For any new package that gets added we will start marking the Note field with the "Needs Review" comment. By default, we will set the fields to the following values:
1) Notes = "Needs Review"
2) DisplayName = "Unknown Display Name"
3) ServiceName = "Unknown Service Name"
4) Type = ""
5) RepoPath = "NA"

Depending on how we discover the new packages (by package manager, release tag, or devops release item) we might be able to pull better values for the fields above, so they have a good starting point for whoever reviews them. Regardless all the values should be reviewed by someone.

This way new packages which haven't gone through our standard release process that @czubair drives will be marked as "Needs Review" until someone reviews them. 

Then we will need someone to periodically review all entries with Note="Needs Review" and do the following:
1) Ensure the DisplayName field to correct value
2) Ensure the ServiceName field to correct value
3) Ensure the Type field is set to the correct value
4) Ensure the RepoPath field is set to the correct value
5) Remove the "Needs Reivew" comment from the Notes field

cc @ronniegeraghty @Petermarcu @lfraleigh

**Comment by czubair** [comment]
Note: for deprecated packages, remove the link to the package.

**Comment by czubair** [comment]
For internal use only packages, please put "tool" in the Type column of the CSV. Then you can remove "Needs Review" from the Notes column. 

For dependency packages, packages that may be downloaded in a users dev env but they don't touch the API surface directly, please put "compat" in the Type column of the CSV. Then you can remove "Needs Review" from the Notes column.

**Comment by czubair** [comment]
If you are unsure of the correct naming of packages, especially for mgmt. packages, you can do the following:
 
a.	Contact a service/package owner if you have a contact
b.	Check:
I.	[Directory of Azure Cloud Services | Microsoft Azure](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fen-us%2Fproducts%2F&data=05%7C01%7CCala.Zubair%40microsoft.com%7C4ba8b14f9f5940eddd2008db7e44ee07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638242606750209956%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XoWPaWzNE%2BZNIIkEcSkfkOwuRCGyeV6XXRBVvM6%2Fqvw%3D&reserved=0)
II.	[Microsoft Learn: Build skills that open doors in your career](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2F&data=05%7C01%7CCala.Zubair%40microsoft.com%7C4ba8b14f9f5940eddd2008db7e44ee07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638242606750209956%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0yzg0b%2ByLreipAXcHAThHtcCHWD5zmv1Drvhp7nazSo%3D&reserved=0) (look for any service docs that already exist)
c.	Ask [@Cala Zubair](mailto:Cala.Zubair@microsoft.com) [@Ronnie Geraghty](mailto:rgeraghty@microsoft.com), [@Lori Fraleigh](mailto:lorifraleigh@microsoft.com)
