### ISSUE TITLE
Azure Defender EASM 1.0.0b1

### ISSUE THREAD

**Issue by lirenhe** [Azure/azure-sdk#5580]

**Comment by msyyc** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/28450

**Comment by lmazuel** [comment]
https://pypi.org/project/azure-defender-easm/

**Comment by maririos** [comment]
@lirenhe looking at the information provided, seems like the API Spec was swagger and not TypeSpec. Is this correct? or the information linked should be updated

**Comment by lirenhe** [comment]
You are right. @maririos,   I updated the format of this release.
