### ISSUE TITLE
Board Review: Introducing azure-webpubsub-client (Python) and azure-messaging-webpubsub-client (Java)

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk#5623]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Service team responsible for the client library: Azure Web PubSub Service
* Main contacts: weidxu@microsoft.com, yuchaoyan@microsoft.com
* Expected stable release date for this library: TBD

## About the Service 

* Link to documentation introducing/describing the service: https://docs.microsoft.com/azure/azure-web-pubsub/
* Link to the service REST APIs: Not a REST API client. Communication between client and backend uses subprotocol on WebSocket.
* Is the goal to release a Public Preview, Private Preview, or GA? The service has been already GA. Plan for client is first public preview, then GA.

## About the client library

* Name of client library: azure-webpubsub-client (Python) and azure-messaging-webpubsub-client (Java)
* Link to library reference documentation: 
    * Client spec: https://github.com/Azure/azure-webpubsub/blob/main/protocols/client/client-spec.md
    * Wire package:
      * JSON: https://docs.microsoft.com/en-us/azure/azure-web-pubsub/reference-json-reliable-webpubsub-subprotocol
      * Protobuf: https://docs.microsoft.com/en-us/azure/azure-web-pubsub/reference-protobuf-reliable-webpubsub-
* Is there an existing SDK library? If yes, provide link: 
    * [.NET SDK Azure.Messaging.WebPubSub.Client](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/webpubsub/Azure.Messaging.WebPubSub.Client)
    * [TypeScript SDK azure/web-pubsub-client](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/web-pubsub/web-pubsub-client)
    * [Python SDK azure-webpubsub-client (WIP)](https://github.com/Azure/azure-sdk-for-python/tree/webpubsub-client/sdk/webpubsub/azure-webpubsub-client)
    * [Java SDK azure-messaging-webpubsub-client (WIP)](https://github.com/weidongxu-microsoft/azure-sdk-for-java/tree/azure-messaging-webpubsub-client/sdk/webpubsub/azure-messaging-webpubsub-client)

* apiview
    * [Python apiview](https://apiview.dev/Assemblies/Review/e23e634cecdd4793811106492ab03942)
    * [Java apiview](https://apiview.dev/Assemblies/Review/8c899fc98a6f473eb6fc866a76e3f62c), [design discussion](https://github.com/Azure/azure-sdk-for-java/issues/33287)

## Step 1: Champion Scenarios 

Ultimately the library should be easy to use for common scenarios that developers want. Consider the following questions when thinking about champion scenarios:

1. What is the app the developer is building that uses your client library?

They use the client library to develop a client app (or webpage) that maintains a websocket connection and pub sub messages.

2. Who is the end-user of the application (the developer's customer)?
3. What features of the API need to be explained in the sample so that someone could use this API in real app?

  * Connect
  * Disconnect
  * JoinGroup
  * LeaveGroup
  * SendToGroup
  * SendEvent
  
4. How does the **authentication** workflow look? 

Access URL in the form of `wss://<service_name>.webpubsub.azure.com/client/hubs/<hub_name>?access_token=<token>`
   

See Champion Scenario section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html).

Code is appreciated but optional. Pseudocode is fine.  

* Champion scenario 1
    * Link to library’s sample folder: [Python, join group and send hello, listen to messages](https://github.com/Azure/azure-sdk-for-python/blob/webpubsub-client/sdk/webpubsub/azure-webpubsub-client/samples/hello_world.py)
* Champion scenario 2
    * Link to library’s sample folder: [Java, join group, listen and reply to every messages](https://github.com/weidongxu-microsoft/azure-sdk-for-java/blob/azure-messaging-webpubsub-client/sdk/webpubsub/azure-messaging-webpubsub-client/src/samples/java/com/azure/messaging/webpubsub/client/EchoSample.java)
* …
* Champion scenario n
    * Link to library’s sample folder:

## Step 2: Quickstart Samples (Optional)
Include samples demonstrating how to consume the client library if available: 

* Create a new resource
* Read the resource
* Modify the resource
* Delete the resource
* Error handling 
* Handling race conditions/concurrency issues

## Thank you for your submission!
    
PS: developers on Shanghai site

**Comment by ronniegeraghty** [comment]
Hi @weidongxu-microsoft, 
The Azure SDK Architecture Board has switched to using our [Azure SDK Scheduling Experience tool](https://apps.powerapps.com/play/e/ed2ffefd-774d-40dd-ab23-7fff01aeec9f/a/f0a98ca4-117c-4d4b-a06a-3e2cdfe46753). 
Please use the scheduling tool to schedule your review session and then close this issue. The scheduling tool will handle creating the GitHub Issue and sending out the meeting invites. 
Please let me know if you have any questions.

**Comment by weidongxu-microsoft** [comment]
Thanks Ronnie.

The tool created issue https://github.com/Azure/azure-sdk/issues/5646

Should I like this one. (maybe link it to the new issue, as this one got more details)

**Comment by ronniegeraghty** [comment]
You can close this issue. If you want to add some of the details in this issue to the new issue in a comment you can do that, or link the issues should be good enough.
