### ISSUE TITLE
KeyVault - accessing secret from App Service is not working.

### ISSUE THREAD

**Issue by jettinag** [Azure/azure-sdk#5680]
Authentication is working with 'DefaultAzureCredential' but when I try to access the value by key getting error as 
"Bearer token authentication is not permitted for non-TLS protected (non-https) URLs." Reproduced same issue by running code at VM.

 cred = DefaultAzureCredential()
 client = SecretClient(vault_url="https://<key-valut-name>.vault.azure.net/)", credential=cred)
 client.get_secret("sample-key") 
 
 Any assistance you can provide would be greatly appreciated.

**Comment by weshaggard** [comment]
@jettinag I'm not an expert here but that doesn't look like a full vault url you would need to give that a full url in order to connect. This looks like python code so if you still have issues I'd suggest moving your question over to https://github.com/Azure/azure-sdk-for-python

**Comment by jettinag** [comment]
@weshaggard , Thanks for your comment, the URL which we are referring is correct but for security reasons, we haven't shared full URL here. As you suggested, I am closing this ticket here and creating a new query at python-sdk.
