### ISSUE TITLE
Define and enforce maximum path length in repo

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#57]
We should define a maximum path length for files in our repos, then add a check to our CI to enforce the limit.

As an example, the repo https://github.com/Azure/azure-sdk-for-java currently has a file whose path is 233 chars:

```
azuredatabasemigrationservice/resource-manager/v2018_07_15_preview/
src/main/java/com/microsoft/azure/management/azuredatabasemigrationservice/
v2018_07_15_preview/MigratePostgreSqlAzureDbForPostgreSqlSyncTaskOutputMigrationLevel.java
```

Windows `MAX_PATH` is 260 chars, which means you need to clone this repo into a path 27 chars or less.

A reasonable max path for the repo might be say 200 chars, which allows 60 chars for the client prefix.

Enforcement during CI should be fairly easy.  One option is a simple shell script to measure the max repo path after cloning and fail if the limit is exceeded.  A more thorough option is to intentionally clone and build into a long folder (on Windows).  If the clone or build fails, the log should indicate if it was caused by `MAX_PATH`.  This is more thorough because sometimes the files in the repo are under `MAX_PATH`, but files generated by the build are longer.

**Comment by Petermarcu** [comment]
@mikeharder , still something we care to track?

**Comment by mikeharder** [comment]
@Petermarcu: I still think this would add value, it's just been a relatively low priority.  Just last week one of our partner teams hit this issue in the .NET repo.

CC: @weshaggard

**Comment by weshaggard** [comment]
I agree there is some value but it just hasn't bubbled to the top of our list yet.

**Comment by seanmcc-msft** [comment]
C:\Users\seanmcc\git>git clone https://github.com/Azure/azure-sdk-for-net.git
Cloning into 'azure-sdk-for-net'...
remote: Enumerating objects: 8543, done.
remote: Counting objects: 100% (8543/8543), done.
remote: Compressing objects: 100% (194/194), done.
remote: Total 269983 (delta 8437), reused 8354 (delta 8349), pack-reused 261440
Receiving objects: 100% (269983/269983), 566.48 MiB | 15.33 MiB/s, done.
Resolving deltas: 100% (215179/215179), done.
error: unable to create file sdk/deviceprovisioningservices/Microsoft.Azure.Management.DeviceProvisioningServices/tests/SessionRecords/DeviceProvisioningServices.Tests.ScenarioTests.DeviceProvisioningClientSharedAccessPolicyTests/ListCreateDelete.json: Filename too long
Checking out files: 100% (22415/22415), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by amishra-dev** [comment]
@Petermarcu @weshaggard (as Sean shows above) we are hitting this same issue in .NET sdks as well. JFYI and would appreciate a higher priority on this.

**Comment by mikeharder** [comment]
@seanmcc-msft, @amishra-dev: Does it work if you clone into a shorter root folder, like say `C:\git\net`?

```
mkdir C:\git
cd c:\git
git clone https://github.com/Azure/azure-sdk-for-net net
```

**Comment by seanmcc-msft** [comment]
C:\>git clone https://github.com/Azure/azure-sdk-for-net

Works for me.  But I'd prefer to keep the repo in C:\Users\seanmcc\git with my other repos.  Also, the default location for repos in Visual Studio C:\Users\username\source\repos.  There's a decent chance any 3rd party who is attempting to contribute may clone there.

I think this issue should be address to reduce unnecessary friction for 1st and 3rd party contributors.

**Comment by mikeharder** [comment]
Thanks for confirming.  We understand the impact of this issue on contributors, I just wanted to provide a workaround.
