### ISSUE TITLE
Change Request: Multi-level pipelines support

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-sdk#570]
# Change Request: Multi-level pipelines support

## Problem

Current pipeline spec is oriented towards call per attempted network request. This works well for cases where there is a 1:1 relationship between operation and network request.

For Cosmos, most of our operations can result in a chain of calls and operations like query can involve complex fan-out/fan-in patterns. This complicates the task of creating policies that are operation oriented. For instance, if I want to have telemetry which captures the e2e time of a query, I'll have to detect when the final request comes through, which is frequently impossible because we'll do background buffering/etc.

A more generic example would be a refresh of an AAD token which would affect the duration of the operation, but not the service request, thus hiding latency.

## Proposed solution

- You *should* be able to define the scope in which a given pipeline plugin will be run. 
- You *should* support "operation" and "request" levels.
- You *may* support other levels. (For example "query" could be useful for hooks that do custom aggregators in our query pipeline in Cosmos)
- You *should* default to "operation" level for plugins if you want to support a default level.
    - This could probably use some conversation - should we have defaults? Do those defaults need to be consistent across azure sdks/languages?

## Example implementation

In the @azure/cosmos js lib, we have non-public implementation of this which we've used in our portal. You can see this in action in our test cases: https://github.com/Azure/azure-cosmos-js/blob/master/test/functional/plugin.spec.ts (Note this does not yet use the @azure/core pipelines, but they are functionally similar and we'll be changing our implementation to use @azure/core shortly)

You can then specify the scope for a given plugin like so:

```typescript
    const plugins: PluginConfig[] = [
      {
        on: "request",
        plugin: alwaysThrow
      },
      {
        on: "operation",
        plugin: alwaysSucceed
      }
    ];
```

<details><summary>Full sample</summary>

```typescript
  it("should handle all operations", async function() {
    const successResponse = {
      headers: {},
      code: 200,
      result: {
        message: "yay"
      }
    };
    let requestCount = 0;
    const alwaysSucceed: Plugin<any> = async (context: RequestContext, next: Next<any>) => {
      requestCount++;
      return successResponse;
    };
    const alwaysThrow: Plugin<any> = async (context: RequestContext, next: Next<any>) => {
      throw new Error("I always throw!");
    };

    const options: CosmosClientOptions = {
      endpoint: "https://faaaaaaaaaaaaake.com",
      key: "THIS IS A FAKE KEY"
    };

    const plugins: PluginConfig[] = [
      {
        on: "request",
        plugin: alwaysThrow // I'll never be called since operation will always succeed.
      },
      {
        on: "operation",
        plugin: alwaysSucceed
      }
    ];

    const client = new CosmosClient({ ...options, plugins } as any);
    const response = await client.database("foo").read();
    assert.equal(requestCount, 2); // Get Database Account + Get Database
    assert.notEqual(response, undefined);
    assert.equal(response.statusCode, successResponse.code);
    assert.deepEqual(response.resource, successResponse.result);
  });
```

</details>

## Next steps

- [ ] Board review
- [ ] Language specific implementation details
- [ ] Azure Core support

**Comment by adrianhall** [comment]
@johanste - can you take this discussion and drive to completion?

**Comment by mayurid** [comment]
Also looping in @bterlson as I believe this is part of Cosmos JS pipeline

**Comment by bterlson** [comment]
We could consider the question of a staged pipeline more broadly. This solution is if I understand correctly isomorphic with Java's "before retry, after retry" model. Other stages may be useful to hook, including an explicit "retry" phase, or a sign/verify phase.

In any case I'm +1 on this, it seems like an incremental improvement that enables more users to compose a pipeline. My main concern with today's pipeline is that it is very hard to modify (requires expert knowledge), and while I think the same is true of this model, it's at least better with respect to retries.

**Comment by johanste** [comment]
What is the request/response type for the operation level pipeline plugins?

**Comment by johanste** [comment]
Per discussion, we agree that having the ability to "inject" policies in at least two named predefined slots is useful. Specifically:

- First:ish (initialize/operation level/before retry). Canonical usage: measuring total time of operation execution.
- Last:ish (request/network/after retry). Canonical usage: Race two requests to different locations, using first response.

**Comment by adrianhall** [comment]
@chrisanderson - are you satisfied with the resolution here?  (7-day auto-close)
