### ISSUE TITLE
Deeper Guidance on Dependency Management

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk#577]
The Azure SDK architectural guidelines are clear on which dependencies are acceptable and the process to review new dependencies, but they fail to call out how to manage a dependency once it has been approved. In this issue I will address a particular dependency, but I think the discussion would apply to any dependency which is not owned the Azure SDK team.

## Azure.Identity and MSAL
The particular dependency I'll cover in this issue is the Microsoft Authentication Library, or MSAL. Currently we have taken a dependency on MSAL in the Azure.Identity library. While MSAL is owned by the Azure Identity team so it is not a third party dependency, introducing it as a dependency poses certain risks which require consideration:
 - The library has a variety of customers and as such it can evolve for circumstances outside of the purview of the Azure SDK.
 - Support varies by language, and not all languages targeted by the Azure SDK have a GA version of MSAL available.
 - Historically the library has introduced breaking changes between major releases.
 - In some languages the library also depends upon other 3rd party dependencies, and these dependencies would be transitively inherited by the Azure SDK.

## Current Isolation Strategy

Currently to mitigate the risks of this dependency we have introduced layers of isolation of MSAL:

 - __Created an abstracted authentication pattern__ - This allows users to implement authentication flows for any Azure SDK client library without any transitive dependency on MSAL. Client libraries __only__ depend on the abstraction and not any particular implementation.
 - __Isolated the MSAL dependency to the Azure.Identity library__ - No other client libraries have a dependency on Azure.Identity or MSAL directly.  This provides flexibility in the version of Azure.Identity, and ultimately the version of MSAL, the application references, helping to avoid diamond dependency issues.
 - __Completely encapsulated the dependency__ - Azure.Identity depends on MSAL only for implementation. No MSAL types, methods, events or exceptions are exposed from Azure.Identity.

## Possible Further Isolation
There are measures we could take to insulate the Azure SDK more from the MSAL dependency, but these each come with their own drawbacks.
- __Minimize the implementation dependency on MSAL__ - Currently since we have already taking MSAL as a dependency for implementation of certain authentication flows, we also utilize it for other authentication flows, which could possibly be implemented directly in the Azure.Identity library.  
  - Pros:
    - This would limit the impact if a breaking change forces us to remove MSAL dependency
  - Cons:
    - Slows down the velocity that we can deliver new authentication flows
    - Increased maintenance cost 
- __Offer a separate Azure.Identity library with no MSAL dependency__ - We could split the Azure.Identity library into two distinct libraries. One which offers more basic authentication flows with no MSAL dependency, and a separate library which provides the authentication flows where MSAL is needed.
  - Pros:
    - Offers application an alternative way to avoid an indirect MSAL dependency, without completely implementing the core authentication abstraction
  - Cons:
    - Complicates the authentication experience, creating confusion as to which library applications should reference in which scenarios
- __Move the MSAL implementation out of process__ - Rather than calling directly into MSAL from Azure.Identity, we could provide a command line utility which provides an RPC interface for obtaining tokens from MSAL.
  - Pros:
    - Azure.Identity no longer has to load MSAL into the process
    - Eliminates transitive dependency issues
  - Cons:
    - Complicates the distribution of Azure.Identity as now another binary must be deployed alongside it
    - Introduction of RPC complicates authentication implementation and introduces another point of failure
    - Decreases the ability to debug and diagnose authentication issues

- __Intern the MSAL dependency__ - Rather than taking a dependency on the MSAL library we could directly intern the MSAL code in the Azure.Identity library.
  - Pros:
    - Completely eliminates the dependency
  - Cons:
    - Greatly increases maintenance costs
    - Limits interoperability with other programs using MSAL, affecting possible SSO opportunities.

**Comment by adrianhall** [comment]
This feels like something that should be discussed at arch board.

**Comment by adrianhall** [comment]
Rescheduling to 1/16/2020 due to snow and power outages.
