### ISSUE TITLE
Change Request:  Upleveling retry options for all languages

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-sdk#578]
Python, I hear, has found that retry options are so popular that stuffing those under some sort of "pipelineOptions" config key isn't as good as a top-level option. Might be good to discuss which pipeline options we think are super common and consider whether we should require they be top-level options or arguments to client constructors.

**Comment by ramya-rao-a** [comment]
What is the plan to get a consensus on this?
Timeline wise, are we targeting the September or October release?

**Comment by adrianhall** [comment]
We believe this is already done, so closing.
