### ISSUE TITLE
Access Token Refresh Strategy: Proactive vs. On Demand 

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk#579]
We don't have consensus on what strategy should be used for refreshing access tokens in Azure SDK libraries. Currently there are two proposed strategies to handle refreshing access tokens. While both meet the requirements laid out by the Azure SDK guidelines, their behavior differs greatly and impact the functionality of client libraries across the SDK. We need to have a deeper discussion on the benefits and drawbacks of each approach, and decide which is preferable, so we can provide a consistent authentication experience across all the Azure SDKs.

## Proactive Strategy

The proactive strategy for token refresh attempts to keep access tokens continually up to date. In this scheme an access token, along with an expiration time is retrieved when the TokenCredential is first instantiated. This is exposed via the TokenCredential Token property which a service client's authentication policy can access synchronously to authenticate requests. Each time an access token is retrieved a timer is scheduled to fire some time before the token's expiration to refresh the token. Authentication requests to refresh tokens are performed out of band with service client's requests to its service.

### Pros
- Refreshing tokens out of band makes response time for client times more uniform as no requests are preempted by an authentication request
- Eliminates race conditions around token refresh as it guarantees only one thread will be refreshing the token so there is no need for synchronization

### Cons
- Failures in authentication requests are raised outside of any context of where and for what that access token is needed
- In order to handle authentication failures applications would have to implement their own TokenCredential types
- Out of band token refresh still doesn't guarantee that the Token property is fresh and valid when it's used by a service client authentication policy, so authentication failures can still originate from service client calls
- TokenCredential instances need to be constructed with all the information necessary to retrieve tokens with the appropriate claims for services where it is intended to be used
  - Doesn't allow authentication schemes where the scope is not known ahead of time (challenge based)
  - Inhibits credential instance reuse.
- Authentication requests are performed throughout the lifetime of the TokenCredential regardless of whether a refreshed token will be used
- TokenCredential instances need to be properly disposed of to ensure any outstanding timers are cancelled and memory is properly collected

## On Demand Strategy

The on demand strategy for token refresh retrieves access tokens in a lazy fashion. In this scheme an access token is not retrieved immediately when a TokenCredential is instantiated. Instead the TokenCredential exposes a method GetToken / GetTokenAsync which a service client's authentication policy can call to retrieve an access token along with an expiration time. Authentication requests to acquire new or refreshed tokens are performed inline with service client's requests to its service.

### Pros
- Failures in authentication requests are raised in the context of a service client call which requires the token to call the service
- Authentication failures can be handled by application code without having to implement their own TokenCredential types
- TokenCredential instances are not tied to specific scopes, so they can be reused across different clients
- Not having to acquire a token when a TokenCredential is instantiated allows for challenge based authentication flow
- No unnecessary authentication requests are performed
- TokenCredential types do not require any special disposal 

### Cons
- Service client response time will vary as some calls will result in both a request to authenticate and a request to the client's service
- Requires synchronization around token refresh as multiple threads can simultaneously attempt to refresh the token
- Any service client call which requires an access token could potentially fail to authenticate

**Comment by adrianhall** [comment]
From board meeting on 8/27/2019:

## Access Token Refresh Strategy
* @schaabs has an epic ppt showing the refresh strategy
* @KrzysztofCwalina  suggests a client-side token cache; @schaabs thinks this is a reasonable middle ground.  note - this is different from the global token cache which is more of a boondoggle.
* @bterlson points out that timers in JS are problematic; they tend to hand on to large chunks of memory forever, and timers don't fire during sync workloads.
* @schaabs approves of the hybrid approach.  Clients hold scope information, token cache vends tokens, and refreshes as needed.  Token cache policies can be evolved over time.
* Conclusion: go with the on-demand strategy and we can opportunistically move token refresh to a background thread/timer.  No need for a first-class token cache.  Can add when needed.  If we fail to refresh the token, we return an `AuthenticationFailed` exception.

## Dependency Mgmt
* Ok with current strategy for now
* Want to meet with MSAL team to form a minimal contract around just what we need.
