### ISSUE TITLE
Board Review: @azure/search-documents UX Improvements

### ISSUE THREAD

**Issue by dgetu** [Azure/azure-sdk#5809]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

**The Architecture Board reviews [Track 2 libraries](https://azure.github.io/azure-sdk/general_introduction.html) only.** If your library does not meet this requirement, please reach out to [Architecture Board](adparch@microsoft.com) before creating the issue. 

Please reference our [review process guidelines](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand what is being asked for in the issue template.

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

For Tier-2 languages (C, C++, Go, Android, iOS), the review will be on an as-needed basis.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.** 

## Contacts and Timeline

* Responsible service team: N/A
* Main contacts: @dgetu 
* Expected code complete date: 
* Expected release date: 

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: @azure/search-documents
* Languages for this review: TS

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### TypeScript

* APIView Link: https://apiview.dev/Assemblies/Review/72c9c9070ecf462dbb6f221f45ad3a0d/6a7d2f3e1cc9417ca7787de80e157352?diffRevisionId=102466a3486b4884896a69a3496baf86&doc=False&diffOnly=True
* Link to Champion Scenarios/Quickstart samples: https://apiview.dev/Assemblies/Samples/72c9c9070ecf462dbb6f221f45ad3a0d

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by ronniegeraghty** [comment]
Hi @dgetu,
The Azure SDK Architecture Board has switched to using our [Azure SDK Scheduling Experience tool](https://apps.powerapps.com/play/e/ed2ffefd-774d-40dd-ab23-7fff01aeec9f/a/f0a98ca4-117c-4d4b-a06a-3e2cdfe46753).
Please use the scheduling tool to schedule your review session and then close this issue. The scheduling tool will handle creating the GitHub Issue and sending out the meeting invites.
Please let me know if you have any questions.
