### ISSUE TITLE
Change Request: Remove "Search" as a namespace group for all languages

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/azure-sdk#582]
## The Basics

This is regarding the namespace guidelines for all languages: https://azure.github.io/azure-sdk/general_design.html#namespaces

There is a namespace group for all search technologies in Azure: `Azure.Search.<service>`. We propose removing this as a group, and finding a different organizing principle for the various search-related services in Azure.

## Reasoning

If Azure Search and the Bing Search APIs were to use this group, it would cause a few problems:

1. It would group Azure Search and the Bing Search APIs under the same top-level namespace, which would create customer confusion. These services are completely different offerings, used for different purposes by different customers. We've had issues in the past with misdirected support cases just because both services have "Search" in the name. Using the "Search" namespace group would make this problem worse.
1. The namespace for Azure Search would end up being Azure.Search.Search, which would be redundant.

For Azure Search, I propose that we eschew grouping altogether and just use "Azure.Search", which is already unambiguous (for reference, our Track 1 .NET data plane SDK uses a top-level namespace of Microsoft.Azure.Search). Any other namespace for Azure Search is likely to cause customer confusion. While I recognize that this guideline is meant to avoid tying namespaces to branding, in practical terms Azure Search has about the simplest branding possible, and it is unlikely to change.

For Bing Search APIs, I am @-mentioning folks who will have opinions on what the Track 2 SDK namespaces should be.

CC @pablocastro @wkwok-msft @yangyuan @dfulcer

**Comment by brjohnstmsft** [comment]
CC @ChrisHMSFT

**Comment by brjohnstmsft** [comment]
Hi @adrianhill -- Is there anything we can provide to help kick-start this discussion? We have a team actively working on our first Track 2 SDK for Azure Search (in Java) and we'd like to resolve the namespace/package name issue soon to avoid disrupting them too much.

**Comment by adrianhall** [comment]
I just got back from vacation, and will discuss with the architects today specifically on the following proposal:

* `Azure.Search` would be your namespace, with a `SearchClient` being the center-piece
* `Azure.Search.<type>` would be used for alternate search technologies, such as those provided by Bing / Cognitive Services.

This proposal is a small divergence from the guidelines, but I agree repeating "Search.Search" is bad.

Will let you know the outcome later on today.

**Comment by dfulcer** [comment]
I understand the challenges involved and agree that search.search is not a good namespace.  But, calling this Azure.search.<type> would also be very bad.

We have a service called Azure Search which is not at all related to the Cognitive Services Bing Search APIs.  We need to keep these namespaces separate.

Dean

**Comment by brjohnstmsft** [comment]
@adrianhall A couple things:

- I agree with @dfulcer -- Bing/Cognitive Services' search-related services need to be in a substantially different namespace than `Azure.Search`, or we're going to cause customer confusion and support tickets. These services are totally unrelated. That's why I'm questioning the entire existence of "Search" as a group -- it makes no business sense to group these things together, given their different purposes and different audiences. Our teams have a lot of historical experience with this problem, so please take our word for it. :)
- Regarding `SearchClient` -- for various reasons, we have two clients in our track 1 .NET SDK -- `SearchServiceClient` and `SearchIndexClient` -- but that is outside the scope of this namespace discussion.

**Comment by adrianhall** [comment]
Worth a quick meeting.  I'll schedule 30 minutes on your calendars to close on this.

**Comment by adrianhall** [comment]
Per meeting:

* azure.search is approved as the base namespace for the client.  See PR #621 for the registration
* Namespaces are non-exclusive.  We will deal with "search related" services as they onboard.  However, all other services will be a sub-namespace (i.e. no other clients directly in azure.search).
