### ISSUE TITLE
Change Request: Static Constructors for JavaScript

### ISSUE THREAD

**Issue by chradek** [Azure/azure-sdk#587]
## The Basics

* Which design guideline is affected?
[Use overloads over unions](https://azure.github.io/azure-sdk/typescript_design.html#ts-use-overloads-over-unions)

* Which target languages are affected?
JavaScript

* Describe the change:
Many of our clients accept passing a `connectionString` or `TokenCredential` in their constructor via overloads. This change proposes using `fromConnectionString` when a client supports using a connection string for authentication.

## Reasoning
I think there are two benefits gained by making this change, with one possible negative.
Pros:
 - Better consistency with the other language guidelines.
 - Easier implementation of the constructor.

Cons:
 - Having multiple methods for instantiating an object (e.g. factory methods) might be confusing to users.

With TypeScript we can use constructor overloads to support passing in different credential types when instantiating a client. This works for consumers of our API so long as our overload signatures are not ambiguous.

For example, here's what the constructor overloads look like for Event Hubs:
```typescript
  /**
   * @constructor
   * @param connectionString - The connection string to use for connecting to the Event Hubs namespace.
   * It is expected that the shared key properties and the Event Hub path are contained in this connection string.
   * e.g. 'Endpoint=sb://my-servicebus-namespace.servicebus.windows.net/;SharedAccessKeyName=my-SA-name;SharedAccessKey=my-SA-key;EntityPath=my-event-hub-name'.
   * @param options - A set of options to apply when configuring the client.
   */
  constructor(connectionString: string, options?: EventHubClientOptions);
  /**
   * @constructor
   * @param connectionString - The connection string to use for connecting to the Event Hubs namespace;
   * it is expected that the shared key properties are contained in this connection string, but not the Event Hub path,
   * e.g. 'Endpoint=sb://my-servicebus-namespace.servicebus.windows.net/;SharedAccessKeyName=my-SA-name;SharedAccessKey=my-SA-key;'.
   * @param eventHubPath - The path of the specific Event Hub to connect the client to.
   * @param options - A set of options to apply when configuring the client.
   */
  constructor(connectionString: string, eventHubPath: string, options?: EventHubClientOptions);
  /**
   * @constructor
   * @param host - The fully qualified host name for the Event Hubs namespace. This is likely to be similar to
   * <yournamespace>.servicebus.windows.net
   * @param eventHubPath - The path of the specific Event Hub to connect the client to.
   * @param credential - SharedKeyCredential object or your credential that implements the TokenCredential interface.
   * @param options -  A set of options to apply when configuring the client.
   */
  constructor(
    host: string,
    eventHubPath: string,
    credential: TokenCredential,
    options?: EventHubClientOptions
  );
```
And here is the constructor signature for the actual implementation:
```typescript
constructor(
    hostOrConnectionString: string,
    eventHubPathOrOptions?: string | EventHubClientOptions,
    credentialOrOptions?: TokenCredential | EventHubClientOptions,
    options?: EventHubClientOptions
  )
```
Assuming the user has provided all of the required parameters, there is no ambiguity between the overloads, and the TypeScript compiler will check mistakes.

The implementation has a lot of ambiguity, and necessitates checking the type of each parameter to determine which overload is being used. Some implementations perform regex on the connection string to check whether it is a host or connection string. While this can generally be avoided, switching away from complicated constructor overloads can reduce the developer urge to go this route in the first place.

I also found that Java and Python have a separate method for passing in a connection string.

In Java, this is done using the builder pattern, where the user can set the connection string using a `connectionString` method.

In Python, the [guidelines](https://azure.github.io/azure-sdk/python_design.html#python-client-connection-string) specifically call out to use a factory method when using connection strings. While Python doesn't have types, I wonder if there were other reasons to use a factory method for Python as well.

C# does use constructor overloads, but they also have the benefit of being able to provide a separate implementation for each overload. This reduces the ambiguity on the implementation side that TypeScript can't avoid.

## Alternative
My motivation is strictly due to the ambiguity caused by supporting multiple credential types in client constructors. Alternatively, if we can create a credential that implements the `TokenCredential` interface in the core-auth package that can take in a connection string, we might be able to get rid of passing in connection strings to client constructors altogether.

**Comment by bterlson** [comment]
In general I don't care overmuch about complexity in the constructor implementation _when that complexity is providing user value_ such as an easier time constructing clients. The general idea of the constructor overload design is there is only one affordance to construct clients and there is some signature that takes what you have.

However your point about this being worse without types seems correct - JS users without TypeScript may have difficulty passing in parameters in the correct order.

/cc @johanste who may have insights.

**Comment by johanste** [comment]
The lack of overloads in Python combined with the fact that a connection string is just a string led me to the guidance for connection strings. Using class based factory method is the accepted way in Python. The "positional parameter means different things based on other positional parameters" not so much.

**Comment by chradek** [comment]
I agree that we should take on the burden of complexity to provide a better experience for the user. I can see how having one way of instantiating a client is preferable compared to multiple methods that may be hard to discover.

Yes, my main concern is with the position parameters when not using TypeScript. I think when I typically see overloads, it's to support optional arguments, or the situation where a parameter can be represented with multiple types.
For example, looking at the node.js `http.request` method, the options object and callback function are optional. The first parameter is a url that can be represented as either a string or a URL object, but means the same thing.
```javascript
http.request(string, [object], [function])
http.request(URL, [object], [function])
http.request(object, [function])
```

With the way we're using overloads in our constructors, that first parameter could be the host or a connection string...it doesn't actually represent the same underlying _thing_.
```javascript
new(string, [object])
new(string, string, [object])
new(string, string, Credentials, [object])
```

That said I don't have the data to back up whether this matters when it comes to ease of use, and wanted to hear what went into the decision-making for other SDKs.
