### ISSUE TITLE
Azure.AI.Vision.ImageAnalysis 0.9.0-beta.1 RID case conflict with Microsoft.Data.SqlClient 4.1.0

### ISSUE THREAD

**Issue by mlorbetske** [Azure/azure-sdk#5875]
When including both Azure.AI.Vision.ImageAnalysis 0.9.0-beta.1 and Microsoft.Data.SqlClient 4.1.0 in the same package graph, the following error appears in the build logs on our Linux build agents

```
/usr/share/dotnet/sdk/7.0.202/Microsoft.Common.CurrentVersion.targets(4862,5): error MSB3027: Could not copy "/root/.nuget/packages/microsoft.data.sqlclient.sni.runtime/4.0.0/runtimes/win-arm64/native/Microsoft.Data.SqlClient.SNI.dll" to "bin/Release/net7.0/runtimes/win-arm64/native/Microsoft.Data.SqlClient.SNI.dll". Exceeded retry count of 10. Failed. 

/usr/share/dotnet/sdk/7.0.202/Microsoft.Common.CurrentVersion.targets(4862,5): error MSB3021: Unable to copy file "/root/.nuget/packages/microsoft.data.sqlclient.sni.runtime/4.0.0/runtimes/win-arm64/native/Microsoft.Data.SqlClient.SNI.dll" to "bin/Release/net7.0/runtimes/win-arm64/native/Microsoft.Data.SqlClient.SNI.dll". Could not find a part of the path '/src/{Redacted}/bin/Release/net7.0/runtimes/win-arm64/native/Microsoft.Data.SqlClient.SNI.dll'. 
```

It appears that Microsoft.Data.SqlClient targets a directory cased as `win-arm64` where Azure.AI.Vision.ImageAnalysis targets a directory cased as `win-ARM64`. On Windows this works out, but on Linux it causes the builds to fail.

Minimal repro csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Vision.ImageAnalysis" Version="0.9.0-beta.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="4.1.0" />
  </ItemGroup>

</Project>
```

Command line to repro (on Linux)
`dotnet publish TheProject.csproj -c Release -o /app`

**Comment by mlorbetske** [comment]
still occurs in 0.15.1-beta.1

**Comment by Dplenge** [comment]
I am experiencing the same issue with Azure.AI.Vision.ImageAnalysis 0.15.1-beta.1 and Microsoft.Data.SqlClient 5.1.2

**Comment by dargilco** [comment]
Thank you @mlorbetske for bringing this to our attention. Unfortunately, this issue was not routed to the correct team within Microsoft in April when you filed the issue. It will be fixed in the next SDK update, however, that will only be in January 2024.

**Comment by martin-airia** [comment]
can you point to the PR/change where that is fixed

**Comment by dargilco** [comment]
@martin-airia package dependencies were updated with the latest stable release (v1.0.0) of the Image Analysis SDK. Do you still see this issue when using that version?
