### ISSUE TITLE
Investigate Pipelines failures building PRs from private forks

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#59]
It appears that Azure Pipelines cannot clone sources of PRs from forks.  Might be specific to **private repos** and the "DevOps GitHub App" for auth. 
 Examples:

https://dev.azure.com/azure-sdk/public-staging/_build/results?buildId=540&view=logs
https://dev.azure.com/azure-sdk/public-staging/_build/results?buildId=538&view=logs

Error:

```
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

We should get a minimal repro and report to the Azure Pipelines team.

## Expected outcomes
We either need to:
1. [Varify] Be able to create forks of private repos and validate PRs from the forks in the CI for the private repo.
2. [Document] Provide documentation clarifying that private forks of private repos will not work.

**Comment by kurtzeborn** [comment]
We don't do builds from private forks today and we really don't have it as a goal at this point.  Since this is so old, going to go ahead and close this one.
