### ISSUE TITLE
The job successfully finishes in Pipeline but I receive an error that Build Failed in email

### ISSUE THREAD

**Issue by monajalal** [Azure/azure-sdk#5915]
(sorry I was not sure where this should be asked exactly--please feel free to forward it to another appropriate channel)

I used MLOps templates and the job successfully runs for 1 epoch with no error for 29 minutes. Then, I run the same job for 60 epochs and takes 15hr, still successfully in azure ML-->pipeline menu.

![Screenshot from 2023-04-11 10-42-58](https://user-images.githubusercontent.com/1892917/231199945-b7fbc5ac-d676-4662-84f9-8ae86dc27aba.png)

However, I received an email from Azure that same job failed. The error is:
![Screenshot from 2023-04-11 10-48-24](https://user-images.githubusercontent.com/1892917/231200932-8340d5ce-2fa5-436d-b8cc-d639d2c3f25b.png)
![Screenshot from 2023-04-11 10-48-43](https://user-images.githubusercontent.com/1892917/231200963-cfbde487-b1da-46d3-9a22-8548da47cc45.png)

```
Details
--
DeployTrainingPipeline2 error(s), 1 warning(s) The job running on agent Azure Pipelines 2 ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134  The operation was canceled. | DeployTrainingPipeline | 2 error(s), 1 warning(s) The job running on agent Azure Pipelines 2 ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134  The operation was canceled. | 2 error(s), 1 warning(s) |   | The job running on agent Azure Pipelines 2 ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134 |   | The operation was canceled.
DeployTrainingPipeline
2 error(s), 1 warning(s) The job running on agent Azure Pipelines 2 ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134  The operation was canceled. | 2 error(s), 1 warning(s) |   | The job running on agent Azure Pipelines 2 ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134 |   | The operation was canceled.
2 error(s), 1 warning(s)
  | The job running on agent Azure Pipelines 2 ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134
  | The operation was canceled.

```

Also, here is some information from the cluster I used for this experiment: mona-gpu-cluster:
![Screenshot from 2023-04-11 10-50-58](https://user-images.githubusercontent.com/1892917/231202118-c1bf8b33-9d14-46da-a462-d1300f425ccc.png)

![image](https://user-images.githubusercontent.com/1892917/231202050-fa9001bd-47e3-4f51-ae3a-cfc7d5b93736.png)

Also, as a side question, should I use the node that ends in r if I am using DistributedDataParallel?

**Comment by ronniegeraghty** [comment]
Hello @monajalal, 
Thank you for reaching out with this issue. I'll get the appropriate team's attention to assist you.

**Comment by ronniegeraghty** [comment]
Hi @monajalal. Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this repository is focused on the Azure SDK - we're unable to assist with other Azure issues.  Since what you're describing appears to be related to the MLOps Service and not one of the SDKs, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
