### ISSUE TITLE
Package list for Go has empty package names

### ISSUE THREAD

**Issue by sandeep-sen** [Azure/azure-sdk#5998]
Package Index [go-all.md - line 249 to 1005](https://github.com/MicrosoftDocs/azure-dev-docs-pr/blob/bdd3d924361d91932fc444f172514d84b4be56bd/articles/includes/go-all.md?plain=1#L249), generated by [Generate-Package-Index.ps1](https://github.com/Azure/azure-sdk/blob/main/eng/scripts/Generate-Package-Index.ps1) has empty package names, probably coming from the management libraries.

**Comment by weshaggard** [comment]
Those all have empty names in the csv https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/go-packages.csv as well. So what would we put?

**Comment by sandeep-sen** [comment]
@weshaggard skip them they should not go on the package list as they are track 1 and don't go on our release site on GitHub IO as well

**Comment by weshaggard** [comment]
OK that should be easy enough.
