### ISSUE TITLE
Package list for Go missing doc links

### ISSUE THREAD

**Issue by sandeep-sen** [Azure/azure-sdk#5999]
Package Index [go-all.md](https://github.com/MicrosoftDocs/azure-dev-docs-pr/blob/main/articles/includes/go-all.md), generated by [Generate-Package-Index.ps1](https://github.com/Azure/azure-sdk/blob/main/eng/scripts/Generate-Package-Index.ps1) does not have a pkg.go.dev doc link.

**Comment by weshaggard** [comment]
This will be fixed by https://github.com/Azure/azure-sdk/pull/6004 because that table only gets msdoc links now but we updated that template to point at go.dev
