### ISSUE TITLE
Transient HTTP errors when downloading tools

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#60]
The `downloadTool()` function in Azure Pipelines doesn't retry on HTTP errors, so a single transient HTTP error is sufficient to cause a build failure.

## Build Logs
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1075

## Pipelines Issue
https://github.com/Microsoft/azure-pipelines-tool-lib/issues/49

CC: @Azure/azure-sdk-eng

**Comment by vtbassmatt** [comment]
FYI, I closed your bug in favor of the [bug](https://github.com/Microsoft/azure-pipelines-tool-lib/issues/25) and [PR](https://github.com/Microsoft/azure-pipelines-tool-lib/pull/39) we already have in flight. (Now, landing that PR is another matter since it's gotten a bit stale. I'll push on that.)

**Comment by kurtzeborn** [comment]
This was fixed with this PR: https://github.com/Microsoft/azure-pipelines-tool-lib/pull/39/files
