### ISSUE TITLE
Board Review: Management Plane Namespace Review Azure Cosmos DB for PostgreSQL

### ISSUE THREAD

**Issue by mozansaka** [Azure/azure-sdk#6002]
Thank you for submitting this review request. Thorough review of your management library namespaces ensures that your library names are consistent with the guidelines and the consumers of your management library have a consistently good experience when using Azure.

To ensure consistency, all language library names will generally be reviewed together.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.**

## Contacts and Timeline

* Responsible service team: Azure Cosmos DB for PostgreSQL
* Main contacts: @mozansaka, @senatol
* Expected code complete date:
* Expected release date:

## About the Service (required)

* Link to documentation introducing/describing the service: https://learn.microsoft.com/en-us/azure/cosmos-db/postgresql/introduction
* Link to the service REST APIs Specs: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/postgresqlhsc/resource-manager/Microsoft.DBforPostgreSQL/stable/2022-11-08
* Link to GitHub issue for previous review sessions, if applicable:  

## Namespace Proposals (required per language)

We relatively recently rebranded our service from "Azure Database for PostgreSQL Hyperscale" into "Azure Cosmos DB for PostgreSQL"; practically became one of the Cosmos DB APIs from customer perspective. However, we are still using our previous resource provider Microsoft.DBforPostgreSQL; sharing it with Azure Database for PostgreSQL - Flexible Server and Single Server services.  More detail: https://learn.microsoft.com/en-us/azure/postgresql/hyperscale/moved?tabs=direct

That's why, we decided to focus on our new service name with the namespaces rather than using resource provider names.

- **.NET:** `Azure.ResourceManager.CosmosDBForPostgreSql`
- **Java:** `azure-resourcemanager-cosmosdbforpostgresql (com.azure.resourcemanager.cosmosdbforpostgresql)`
- **Go/Golang:** `sdk/resourcemanager/cosmosforpostgresql/armcosmosforpostgresql`
- **JavaScript:** `@azure/arm-cosmosdbforpostgresql`
- **Python:** `azure-mgmt-cosmosdbforpostgresql`

## Thank you!

**Comment by ArthurMa1978** [comment]
For .Net, the name space shoule be Azure.ResourceManager.CosmosDB**F**orPostgreSQL

**Comment by ronniegeraghty** [comment]
I made the name change @ArthurMa1978 suggested for .NET. 
Now moving the approval process into phase 2. The names will be presented to the rest of the Azure SDK architect team. They will have until the end of business on May 11th to state any comments or objections they have with the proposed names.

**Comment by m-nash** [comment]
@ArthurMa1978 is there any reason we don't go with `Azure.ResourceManager.CosmosDB.PostgresSQL`?  @KrzysztofCwalina do you have an opinion on this one?

**Comment by tadelesh** [comment]
Go will use `sdk/resourcemanager/cosmosforpostgresql/armcosmosforpostgresql`.

**Comment by ronniegeraghty** [comment]
The names in the description of this issue have been approved as they show in the description in it's most recent update.
