### ISSUE TITLE
Create Live Test tracking dashboard

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk#603]
We have been manually generating spreadsheets that show pipeline status. It has been helpful at understanding live test results but we need an automated way to do this. 

What we need is a PowerBI report that grabs historic information from the DevOps API (provided the DevOps API makes enough historic information available)

**Comment by kurtzeborn** [comment]
We have a live test dashboard for track 2 [here](https://dev.azure.com/azure-sdk/internal/_dashboards/dashboard/d2224fd5-beee-47a0-90df-b24b73fdc8e7).  It's not PowerBI, but it does the job.
