### ISSUE TITLE
Board Review: Storage client-side encryption

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk#613]
The Storage client libraries have historically supported client-side encryption for customers who want yet another layer of data security.  We need to expose the same algorithm in our Azure.Core client libraries so data encrypted with one version/language of a Storage client can be used with all the others.

You can read more about the general feature at https://docs.microsoft.com/en-us/azure/storage/common/storage-client-side-encryption
and we have a couple of specific questions we’re looking for guidance on:

1. Do we include client-side encryption in the same package or a separate package?  The same package means less work figuring out how they’ll work together   _(Leaning toward same.)_
2. Do we want to expose this via settings on StorageClientOptions or an EncryptedBlobClient? _(Leaning toward StorageClientOptions for now because we could add an EncryptedBlobClient for later)_
3. Could we create a shared interface for processing streams?  We’ll need something similar for the CRC work.
4. Can we merge the CPK interface to work the same as client-side encryption?  Then customers only have to learn one pattern.
5. Whether we should offer more protection for customers against accidentally erasing the metadata on encrypted blobs
6. Should we support encryption for all blob types?

**Comment by adrianhall** [comment]
Link to notes (MICROSOFT INTERNAL): https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/OneNote.aspx?id=%2Fteams%2FAzureDeveloperExperience%2FShared%20Documents%2FGeneral%2FAzure%20SDK%20-%20General&wd=target%28Board%20Meetings.one%7C19375C24-42BA-455A-A479-8E59FBB01EF3%2FClient%20Side%20Encryption%20for%20Storage%20-%209%5C%2F5%5C%2F2019%7C011AE3AB-852A-43B5-B856-13365283EC43%2F%29
onenote:https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/Shared%20Documents/General/Azure%20SDK%20-%20General/Board%20Meetings.one#Client%20Side%20Encryption%20for%20Storage%20-%209/5/2019&section-id={19375C24-42BA-455A-A479-8E59FBB01EF3}&page-id={011AE3AB-852A-43B5-B856-13365283EC43}&end
