### ISSUE TITLE
Board Review: Management Plane Namespace Review Microsoft.CodeSigning

### ISSUE THREAD

**Issue by ashutak84** [Azure/azure-sdk#6150]
Thank you for submitting this review request. Thorough review of your management library namespaces ensures that your library names are consistent with the guidelines and the consumers of your management library have a consistently good experience when using Azure.

## Contacts and Timeline

* Responsible service team: Azure Code Signing
* Main contacts: ashuku@microsoft.com, rakiasegev@microsoft.com, meha.sharma@microsoft.com, Amrita.Shanbhag@microsoft.com
* Expected code complete date: **June 30, 2023**
* Expected release date: **June 30, 2023**

## About the Service (required)

* Link to documentation introducing/describing the service: https://techcommunity.microsoft.com/t5/security-compliance-and-identity/azure-code-signing-democratizing-trust-for-developers-and/ba-p/3604669
* Link to the service REST APIs Specs: https://github.com/Azure/azure-rest-api-specs-pr/pull/12621/checks
* Link to GitHub issue for previous review sessions, if applicable:  N/A

- **.NET:** `Azure.ResourceManager.CodeSigning`
- **Java:** `azure-resourcemanager-codesigning (com.azure.resourcemanager.codesigning)`
- **Go/Golang:** `sdk/resourcemanager/codesigning/armcodesigning`
- **JavaScript:** `@azure/arm-codesigning`
- **Python:** `azure-mgmt-codesigning`

## Thank you!

**Comment by ronniegeraghty** [comment]
Hi @ashutak84. 
I made some updates to the suggested namespaces so that they better fit our patterns for each programming language. 
Please give the main description of this issue or this comment a 👍if the namespaces look good to you.

**Comment by m-nash** [comment]
@ashutak84 the spec link above links to a PR with only md files no swagger files.  Do you have a link to the actual spec itself?

**Comment by ashutak84** [comment]
PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/12621/files
Link to Swagger Specs: https://github.com/Azure/azure-rest-api-specs-pr/blob/azurecodesign/sdks/specification/codesigning/resource-manager/Microsoft.CodeSigning/preview/2023-04-30-preview/codeSigningAccount.json

**Comment by m-nash** [comment]
Looks good for dotnet

**Comment by ronniegeraghty** [comment]
Alright, I'll move the approval process into the second phase. The rest of our architect team will have 1 week (to EOB on June 1st) to make any objections to the names.

**Comment by ashutak84** [comment]
Can i get some traction on this request. My team is on a timeline. Sorry for pushing it like this.

**Comment by ronniegeraghty** [comment]
Hi @ashutak84,
The rest of our SDK Architect team is reviewing the names in their own forum. They have a full week to make any objections to the proposed names. If there are objections, we'll work with them to resolve them. If not, we'll be able to approve the names, but we need to give the architects the time to review the names. As my previous comment says, the architect's week will be done at EOB on June 1st.

**Comment by ashutak84** [comment]
Thanks @ronniegeraghty for replying, sorry for asking, the comments would be given here in this comments section or some where else?

**Comment by ronniegeraghty** [comment]
@ashutak84, the architects discussion is internal to their group.

**Comment by ronniegeraghty** [comment]
The names in the description of this issue have been reviewed by the SDK Architects and are approved.
