### ISSUE TITLE
Change Request: Add guidance on supporting batched operations

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk#619]
## The Basics

* Which design guideline is affected?
The General Guidelines call out common patterns like pagination, long running operations, etc.  We should have similar guidance for sending multiple operations in a batch.

* Which target languages are affected?
All languages should eventually add language-specific guidance.

* Describe the change:
There are a lot of ways that batching manifests in practice from [Blobs homogeneous batches](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch), [Tables transactional batches](https://docs.microsoft.com/en-us/rest/api/storageservices/performing-entity-group-transactions), [OData's general batching](https://www.odata.org/documentation/odata-version-2-0/batch-processing/), etc.  We should have recommendations on how to expose these patterns in client libraries.

## Reasoning

We need to implement batching for Storage blobs in our libraries.

**Comment by adrianhall** [comment]
Scheduled for 9/26

**Comment by adrianhall** [comment]
Notes (MICROSOFT INTERNAL): https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/OneNote.aspx?id=%2Fteams%2FAzureDeveloperExperience%2FShared%20Documents%2FGeneral%2FAzure%20SDK%20-%20General&wd=target%28Board%20Meetings.one%7C19375C24-42BA-455A-A479-8E59FBB01EF3%2FBatching%20Operations%20-%209%5C%2F26%5C%2F2019%7C3DD8E723-580E-4D01-AC3F-1A55CA30B5EC%2F%29
onenote:https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/Shared%20Documents/General/Azure%20SDK%20-%20General/Board%20Meetings.one#Batching%20Operations%20-%209/26/2019&section-id={19375C24-42BA-455A-A479-8E59FBB01EF3}&page-id={3DD8E723-580E-4D01-AC3F-1A55CA30B5EC}&end
