### ISSUE TITLE
Persistent Notification Members

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk#622]
In at least one case we have someone who wants to know whenever any nightly Java build fails. 

The CODEOWNERS file is not sufficient to this task because this person would have to be edited to include the person on every entry (thus reducing the usefulness of CODEOWNERS). 

An automation tool could add this person to all groups associated with java builds, but this tool would need to run periodically. 

We should instead keep a source of truth for individuals/groups that are interested in any failures of builds and subscribe them as part of the CODEOWNERS sync process (or something like it).

**Comment by kurtzeborn** [comment]
Pretty sure you fixed this (and I even reviewed the PR).  If I'm wrong, please reopen this issue.
