### ISSUE TITLE
Board Review: Azure Search Java SDK (MVP)

### ISSUE THREAD

**Issue by CodeRunRepeat** [Azure/azure-sdk#625]
## The Basics

* Service team responsible for the client library: Dev Crews, Commercial Software Engineering, with the support of the Azure Search team (Bruce Johnston) and DevDiv (Jonathan Giles)  
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/search/
* Contact email (if service team, provide PM and Dev Lead):
  * Tech Lead (CSE): Tamir Kamara takamara@microsoft.com (stand-in until Sept. 15 Nava Vaisman Levy navale@microsoft.com)
  * TPM (CSE): Natasa Manousopoulou anastm@microsoft.com
  * Please cc jong@microsoft.com nathanm@microsoft.com

## About this client library

* Name of the client library: Azure Search Java SDK (MVP)
* Languages for this review: Java
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/searchservice/
* Link to the reference documentation: *WIP* https://github.com/navalev/azure-sdk-for-java-pr/blob/master/sdk/search/azure-search-data/README.md
* Link to several samples: *WIP* https://github.com/navalev/azure-sdk-for-java-pr/tree/master/sdk/search/azure-search-data/src/samples/java/com/azure/search/data

## Champion Scenarios

Scenario 1 - Search for dynamic documents
Basic usage of the SDK
*    Building sync and async clients
*    Searching for documents
*    Interacting with dynamic data (built-in types, Map<String, Object>, List<>, etc)
*    Use of common query concepts (ordering, skip, top, facets)

Scenario 2 - Client configuration
How to create and configure the search index client
*    Minimal configuration
*    Advanced configuration

Scenario 3 - Search for typed documents
Using the SDK with user-provided types
*    The Document.as() method

Scenario 4 - Index content management
Managing index contents
*    Simple usage to merge/upload data into an index
*    Support for complex user-provided types
*    Advanced usage to send many operations with data in a single batch
*    Partial success handling (IndexBatchException on HTTP 207)

## Agenda for the review

The following agenda will normally be followed:

1. Introduction to the service (10 minutes max)
2. Class Hierarchy (general) and public API surface
    * To ensure consistency, discuss any language then indicate how the other languages are constructed
3. Per-language exceptions and examples
4. Implementation of champion scenarios (top 3-4 only) with code in preferred language
    * Include samples as attachments for other languages - all languages under consideration must be provided

**Comment by CodeRunRepeat** [comment]
@navalev @tamirkamara @jongio @millerna26

**Comment by adrianhall** [comment]
Pass to Jonathan for a first pass review.

**Comment by adrianhall** [comment]
@JonathanGiles - assign back to me when this is ready for the board.

**Comment by CodeRunRepeat** [comment]
@adrianhall @JonathanGiles when are we going to close this? will there be a new review that the recommendations were applied?

**Comment by adrianhall** [comment]
Link to recording (MICROSOFT INTERNAL): https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/OneNote.aspx?id=%2Fteams%2FAzureDeveloperExperience%2FShared%20Documents%2FGeneral%2FAzure%20SDK%20-%20General&wd=target%28Board%20Meetings.one%7C19375C24-42BA-455A-A479-8E59FBB01EF3%2FAzure%20Search%20for%20Java%20-%2010%5C%2F2%5C%2F2019%7C9879E0FC-3147-41B7-8DAB-23E9D636BFEA%2F%29
onenote:https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/Shared%20Documents/General/Azure%20SDK%20-%20General/Board%20Meetings.one#Azure%20Search%20for%20Java%20-%2010/2/2019&section-id={19375C24-42BA-455A-A479-8E59FBB01EF3}&page-id={9879E0FC-3147-41B7-8DAB-23E9D636BFEA}&object-id={24814D0B-9E92-0568-0FDC-D7E80FEB804B}&8F

- The `.apiVersion()` in the builder can be optional - default to last stable version.
- Change `.credential(API_KEY)` to `.credential(AzureSearchApiKeyCredential(API_KEY))`
- Replace `.searchName()` and `.searchDnsSuffix()` with `.endpoint()`
- Remove the `.as()` method and provide code snippet in documentation
- Remove or hide the batch builder - just use IndexBatch to construct batches.

Other things that need discussing:
- The regular expressions around changing generated code - send to @JonathanGiles so we can take a look at updating autorest code generators
- Strongly typed deserialization in Azure Core - will be discussed by arch board.
