### ISSUE TITLE
Add these concepts to the arch doc

### ISSUE THREAD

**Issue by Petermarcu** [Azure/azure-sdk#64]
Consider adding context in for CRUD operations in the name of the method unless it is clearly obvious.

All Azure SDK APi's that go over the network must support cancellation. See specification for each language.

The ability to access the raw headers for both diagnosability and forward compat. Ability to enumerate headers should also be required to support logging?

**Comment by adrianhall** [comment]
Specific requirements have been added to general guidelines:

* Cancellation
* Response of T guidelines

In addition, see #358 for design guidelines around semantic naming of verbs.
