### ISSUE TITLE
Board Review: Identity August GA

### ISSUE THREAD

**Issue by billwert** [Azure/azure-sdk#6439]
Thank you for submitting this review request. Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

## Contacts and Timeline

* Responsible service team: Identity
* Main contacts:
* Expected code complete date: 8/4/2023
* Expected release date: 8/8/2023

## About the Service 

* Link to documentation introducing/describing the service:
* Link to the service REST APIs: 
* Link to GitHub issue for previous review sessions, if applicable:  

## About the client library

* Name of the client library: Identity
* Languages for this review: .NET, Java, Python, JS

## Artifacts required (per language)

Please read through “API Review” section [here](https://azure.github.io/azure-sdk/policies_reviewprocess.html) to understand how these artifacts are generated. **It is critical that these artifacts are present and are in the right format. If not, the language architects cannot review them with the SDK Team’s API review tool.**

### .NET

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Java

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

### Python

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:
  
### TypeScript

* APIView Link:
* Link to Champion Scenarios/Quickstart samples:

For all other languages, send a request to the Architecture Board to discuss the best format on individual basis.

**Comment by billwert** [comment]
This is the actual content of our review:
# Identity August GA

## Api Views

- Python 
  - [Identity](https://apiview.dev/Assemblies/Review/ee993c29a21746d5b3d98d496b538f93/ce0774546e494fc69ecb1c1f60649d3d?diffRevisionId=f152333f50014fd1b0f485dee415f1fe&doc=False&diffOnly=True) 
  - [Core](https://apiview.dev/Assemblies/Review/ee993c29a21746d5b3d98d496b538f93/ce0774546e494fc69ecb1c1f60649d3d?diffRevisionId=f152333f50014fd1b0f485dee415f1fe&doc=False&diffOnly=True)
- .NET
  - [Identity](https://apiview.dev/Assemblies/Review/6a40db7f9eeb41dabfe5768f1e796c81/3918fbd42fd74d39892f6cd4031ccfe8?diffRevisionId=0abb74123eb9455099c9d77a7ce280ce&doc=False&diffOnly=True)
- Java 
  - [Identity](https://apiview.dev/Assemblies/Review/6a8beb3fcd5f4ebe963694580b0eb925/81602943ecee4f9ba83ab66090ffb985?diffRevisionId=823dd90eaf8a4b7fbdbc47d4057ce6e2&doc=False&diffOnly=True)
  - [Core](https://apiview.dev/Assemblies/Review/f05053009089449ea8fad56273dca2a4/24d09a7042c34ad582596ff1a862fbb6?diffRevisionId=a9bfa9ef236c4fffb86e0989c6661089&doc=False&diffOnly=True)
- JS
  - [Identity](https://apiview.dev/Assemblies/Review/c96f3151901e44e3af32cce967aac46d/1e81fe3caa9f4b2d9fe23798ba81b635?diffRevisionId=f50b8cd5268b42f39f27120a6a0db2db&doc=False&diffOnly=True)
  - [Core](https://apiview.dev/Assemblies/Review/1b93581f3baa4d0ea90dae0e8e23ccc0/9f726cfba07a483296403a69a96807ac?diffRevisionId=f1e7775ef088430392d3df680de84200&doc=False&diffOnly=True)

Go and C/C++ are not planning a GA with this release as they have not yet picked up these features.

.NET has already shipped the Core change for enabling CAE on the Core TokenRequestOptions type, so it is not included here.

## DAC should continue if a dev-time credential fails

[Issue](https://github.com/Azure/azure-sdk-for-python/issues/30167) for more context.

In the case `SharedTokenCredential` found an expired token it would cause `ChainedTokenCredential` to stop further processing. This is undesirable behavior. In addition to fixing this, we decided to make `DefaultAzureCredential` also continue on any failure from a dev-time credential (such as the CLIs or IDEs.) This change has no API surface changes; it is behavioral. We do not believe modifying the DAC policy here will break customers.

## Continuous Access Evaluation for service principals

[Issue](https://github.com/Azure/azure-sdk-for-python/pull/30777) for more context.

CAE support is now configurable per request. This is exposed through a new property on `TokenRequestContext` in Core. Names:
.NET: `IsCaeEnabled`
Java: `setEnableCae(boolean)` and `isCaeEnabled`
Python: `enable_cae`
JS: `enableCae`

We now maintain two token caches differentiated by filename. This should not be a visible change to users.

The existing `AZURE_IDENTITY_DISABLE_CP1` environment variable is now a no-op and has been removed.

Although disabling CAE by default could be a breaking behavioral change for clients talking to services that support CAE and also are subject to a directory policy that forces it to be enabled, the impact is relatively minor given this is a rare policy and CAE support is rare among RPs. To resolve this issue, clients that support CAE need to add a client option to allow customers to opt in to CAE support. The rationale for the change is that keeping behavior as is could be worse, since clients unprepared for CAE challenges won't be able to properly respond and acquire tokens as their RP start supporting CAE.

## EnableSupportLogging in MSAL

[Issue](https://github.com/Azure/azure-sdk-for-java/issues/34072) for more context.

MSAL has requested we give users the ability to turn on additional MSAL logging. They have had ICMs that would have been much faster to resolve with this capability. For MSAL based credentials we add an option to enable this based on the name `EnableSupportLogging`.

It should be clear that this feature will cause PII to be logged in an unredacted form. Our docs are clear about this danger, but we wanted to highlight it.

## New option for controlling interactive browser options for Azure PowerShell.

[Issue](https://github.com/Azure/azure-sdk-for-net/issues/34972) for more context.

The Azure PowerShell team is required to customize the web view displayed after authentication. Identity needs to pass options through to MSAL to accomplish this.

**Comment by ronniegeraghty** [comment]
Hi @billwert, 
Have you schedule a review for these changes using the [Scheduling Tool](https://apps.powerapps.com/play/e/ed2ffefd-774d-40dd-ab23-7fff01aeec9f/a/f0a98ca4-117c-4d4b-a06a-3e2cdfe46753)?

**Comment by scottaddie** [comment]
@ronniegeraghty The architects should already be well aware of these changes. Bill sent an email last night in hopes of getting sign off that way.

**Comment by billwert** [comment]
Closing this issue in favor of #6448
