### ISSUE TITLE
Board Review: Azure KeyVault Certificates SDK (all languages)

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk#657]
Preferred Time: 3rd Oct 2 -4
## The Basics

* Service team responsible for the client library:  DevDiv - Azure KV Team(Scott Schaab, Jonathan Turner, Charles Lowell, Vinay Gera, Isabella Cai, Daniel Rodriguez)  
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/key-vault/

## About this client library

* Name of the client library: Azure KeyVault Certificates SDK (MVP)
* Languages for this review: Java, .NET, Python, JS/TS
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/keyvault/
* Link to the reference documentation: *WIP* https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/README.md
* Link to several samples: *WIP* https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/samples

## Champion Scenarios

 **Under development** 

## Agenda for the review

The following agenda will normally be followed:

1. Introduction to the Azure KV Certificates service (5 - 10 minutes)
2. Class Hierarchy (general) and public API surface
    * To ensure consistency, discuss any language then indicate/look at the API surface of other languages.
3. Per-language exceptions and examples
4. Implementation of champion scenarios (top 3-4 only) with code in preferred language
    * Include samples as attachments for other languages - all languages under consideration must be provided

**Comment by adrianhall** [comment]
In .NET:
* Combine Certificate and Certificate Policy

In Python
* Johan thinks the poller needs a .result() - to be reviewed (in Azure.Core)
* Tags and Enabled in create_certificate should be **kwargs
* Splat out the args in update_certificate_policy
* Rename `name` to `certificateName` in update_certificate_policy

In Java
* The sync version of createCertificate should return a poller
* Method name should be beginCreateCertificate

In JavaScript
* Need to provide example with the poller
* createCertificate should be beginCreateCertificate and return a poller
* Enabled and tags should go in an options bag
* Rename `name` to `certificateName` in updateCertificatePolicy

Generally
* Maybe place the deleted certificates in a sub-space of the clinet.
* Give more thought to naming of certificate / certificate-with-policy (perhaps getCertificate and getCertificateVersion)
* Convert delete_certificate to a poller (may have issues - check design with architects)
