### ISSUE TITLE
Enable Verbose logging within DevOps pipelines

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk#658]
To be able to diagnose issues which occur only on the pipelines verbose logging or tracing should be enabled in the DevOps Pipelines

**Comment by kurtzeborn** [comment]
I talked with @weshaggard about this a bit more.  Let's not dump the logs to the console output window.  Instead, the verbose logs should just go to a file that's uploaded as an artifact for further investigation when needed.  Putting it all to the console output would have non-trivial perf implications for DevOps UI and build times.

**Comment by weshaggard** [comment]
This was partly done with https://github.com/Azure/azure-sdk-for-net/pull/12008/.

**Comment by weshaggard** [comment]
There isn't a great general way to do this across the board so lets close this issue and if there are specific places we want extra logging we should file an issue for that.
