### ISSUE TITLE
Board Review: Management Plane Namespace Review Edge Market Place

### ISSUE THREAD

**Issue by aneesh-ponneth** [Azure/azure-sdk#6586]
Thank you for submitting this review request. Thorough review of your management library namespaces ensures that your library names are consistent with the guidelines and the consumers of your management library have a consistently good experience when using Azure.

To ensure consistency, all language library names will generally be reviewed together.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.**

## Contacts and Timeline

* Responsible service team: azstc@microsoft.com
* Main contacts: anponnet@microsoft.com; lloydg@microsoft.com
* Expected code complete date: 09/06/2023
* Expected release date: 09/15/2023

## About the Service (required)

* Link to documentation introducing/describing the service: 
* Link to the service REST APIs Specs: https://github.com/Azure/azure-rest-api-specs/pull/25556
* Link to GitHub issue for previous review sessions, if applicable:  

## Namespace Proposals (required per language)

**In the examples below please replace every occurrence of [ResourceProviderName] with your the service resource provider name. Be sure to keep the casing shown with [ResourceProviderName] when replacing it with the service resource provider name.**

- **.NET:** `Azure.ResourceManager.EdgeMarketplace`
- **Java:** `azure-resourcemanager-edgemarketplace (com.azure.resourcemanager.edgemarketplace)`
- **Go/Golang:** `sdk/resourcemanager/edgemarketplace/armedgemarketplace`
- **JavaScript:** `@azure/arm-edgemarketplace`
- **Python:** `azure-mgmt-edgemarketplace`

## Thank you!

**Comment by ArthurMa1978** [comment]
Please remove the `Microsoft` prefix, the namespace should be:
- .NET: `Azure.ResourceManager.EdgeMarketPlace`
- Java: `azure-resourcemanager-edgemarketplace (com.azure.resourcemanager.edgemarketplace)`
- Go/Golang: `sdk/resourcemanager/edgemarketplace/armedgemarketplace`
- JavaScript: `@azure/arm-edgemarketplace`
- Python: `azure-mgmt-edgemarketplace`

**Comment by ronniegeraghty** [comment]
@aneesh-ponneth, I've updated the proposed namespaces in the description to reflect @ArthurMa1978's comments. 
Please give this comment a 👍if they look good to you. Then I'll start the next phase of the review process.

**Comment by ronniegeraghty** [comment]
Starting phase 2 of the review. The proposed namespaces will be brought in front of our SDK architects, and they will have 1 week to make any comments or objections to the names. If there are no objections by EoB on 9/26, the namespaces will be considered approved.

**Comment by ronniegeraghty** [comment]
The second phase of our review process is over. Only one objection was made for the .NET namespace. The architects pointed out that Marketplace is one word and the "P" in place should not be capitalized. The proposed namespace in the main description of this issue has been changed to reflect this.

The namespaces as they appear in the main description of this issue are approved.
