### ISSUE TITLE
Change Request: Provide cloud configuration with endpoint information for various clouds

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk#663]
Thank you for contributing to the design guidelines for Azure SDKs.  We welcome all discussions and contributions.  Since the design guidelines affect the client libraries for all Azure services, we thoroughly discuss and vet any design guideline changes before we incorporate them into the official guidance.  This process can take some time, so your patience is appreciated.

## The Basics

Different clouds use different endpoints for services as well as for authentication. For customers who want to use non-public Azure, finding all the endpoints is cumbersome. 

For an example of one way the problem is addressed, see https://docs.microsoft.com/en-us/cli/azure/manage-clouds-azure-cli?toc=%2Fcli%2Fazure%2Ftoc.json&bc=%2Fcli%2Fazure%2Fbreadcrumb%2Ftoc.json&view=azure-cli-latest

* Which design guideline is affected?
Configuration

* Which target languages are affected?
All

* Describe the change:
Provide a simple name/mechanism for a user to indicate that they want to work with a specific cloud and have client libraries automagically pick up the right endpoints by default.
## Reasoning

Please provide any additional detail or reasoning for the request.

**Comment by johanste** [comment]
FYI, @schaabs

**Comment by jongio** [comment]
Related: https://github.com/Azure/azure-sdk/issues/1054

**Comment by jongio** [comment]
Related in Python Mgmt plane docs: https://github.com/Azure/azure-sdk-for-python/blob/master/doc/sphinx/multicloud.rst

**Comment by jongio** [comment]
Related, msrestazure-for-python has get_cloud_from_metadata_endpoint method: https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_cloud.py#L229
