### ISSUE TITLE
generate-releasenotes.yml isn't setting the correct start date for the release

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk#6643]
It was pointed out by @czubair that the releases for September were going into October's release notes yml files.

The problem is inside of the [eng/pipelines/template/steps/generate-releasenotes.yml](https://github.com/Azure/azure-sdk/blob/main/eng/pipelines/template/steps/generate-releasenotes.yml#L30) which is being used by the [automation - azure-sdk - version-updater pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1284&_a=summary). The inline powershell script for the Set Release Period Value step sets the ReleaseStartDate to the second Friday of the month. In the case of September, 2023, the first Friday was September 1st and the second was September 8th which means everything after the 8th is being added to October's release yml. Release cycles run mid-month to mid month. So, the September release notes will include anything released 8/14-9/15, for example but because the second Friday was September 8th, it's putting everything released after the 8th into October's yml.

**Comment by weshaggard** [comment]
Fixed with https://github.com/Azure/azure-sdk/commit/f02580f88b538b6b6ec6ffca7234a90a91076be5
