### ISSUE TITLE
Board Review:  Azure Key Vault Keys and Secrets Full API Review

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk#668]
| Language | Secrets Review |  Keys Review |
| --- | --- | --- |
| .NET | [Azure.Security.KeyVault.Secrets](https://apiview.azurewebsites.net/Assemblies/Review/051acebc7a044a6d8cee8109d1eb6b70) | [Azure.Security.KeyVault.Keys](https://apiview.azurewebsites.net/Assemblies/Review/d74052731cb94759804beaa492b7a17a) |
| Java | [com.azure.security.keyvault.secrets](https://apiview.azurewebsites.net/Assemblies/Review/bf09a78126134cff82faa4a3d40593d3) | [com.azure.security.keyvault.keys](https://apiview.azurewebsites.net/Assemblies/Review/a7ad65c7534d4138a14d8654b575510a) |
| JS | [@azure/keyvault-secrets](https://github.com/Azure/azure-sdk-for-js/pull/5394) | [@azure/keyvault-keys](https://github.com/Azure/azure-sdk-for-js/pull/5395) |
| Python | [azure-keyvault-secrets](https://github.com/Azure/azure-sdk-for-python/pull/7614) | [azure-keyvault-keys](https://github.com/Azure/azure-sdk-for-python/pull/7615) |

**Comment by adrianhall** [comment]
.NET Review: https://msit.microsoftstream.com/video/1dea18c6-0b49-46e0-97cc-188aaeb582c5

* Include VaultUri property in the SecretClinet
* Should we move the deleted secrets operations to a separate client?  Probably - everything but delete, move to DeletedSecretClient - don't add a getDeletedSecretClient() method to main client.
* DeletedDate - check with service team on nullability - does null mean something to users?
* Secret - rename KeyVaultSecret
* Key - rename KeyVaultKey
* Enabled on secret - check with service team on nullability - does null mean something to users?
* Secret.KeyId -> should be Uri type
* Expires -> ExpiresOn
* Mabe convert the recoveryLevel to a flags enum (lump into .NET extensible flags enum discussion)
* Add On to DateTimeOffset properties (Deleted -> DeletedOn, Updated -> UpdatedOn)
* KeyCreateOptions -> CreateKeyOptions (guidelines)
* Consider collapsing CreateRsaKey and CreateEcKey into CreateKey as an overload
* Hsm -> HardwareProtected
* Investigate KeyImportOptions to remove additional type
* Consider rename of RestoreKey -> RestoreKeyBackup
* Move Hsm and KeySize to get/set properties

Discussion on GetSecrets - no resolution in meeting.

**Comment by adrianhall** [comment]
JavaScript Review: https://msit.microsoftstream.com/video/e5cb0daf-fecc-43a1-b12f-f958248602c5

* SecretsClient -> SecretClient
* Consider vaultUrl -> endpoint
* expires -> expiresOn
* Fore ciphertext, UInt8Array feels wrong - check what CryptoJS does to gain inspiration
* KeySignatureAlgorithm -> SignatureAlgorithm and export from top level
* Typealias the UInt8Array to something else?
* Key.keyType / keyOperations should be getters or copy the data to key.
* Drop JsonWeb from types like JsonWebKeyCurveName
* Move NewPipelineOptions into core-http
* What's the diff between Delay and Interval in RetryOptions?  @bterlson to investigate
* getCryptographyClient() should hang off the KeyClient

Back to GetSecrets:
* Rename to GetPropertiesOfSecrets or similar, and return SecretProperties.

**Comment by adrianhall** [comment]
Java Review: https://msit.microsoftstream.com/video/bf027e45-8dac-4492-8fc6-076eb9218923 

* KeyVaultCredentialPolicy - move to azure-core and rename ChallengeBasedAuthentication?
    * Make private and punt this task until next release
* Make the deleted secrets methods to a DeletedSecretsClient?
    * Gut instinct is to not use a different client.
    * Potentially add them back in to the client in .NET?
* listSecrets -> listPropertiesOfSecrets (follow other languages)
* endpoint -> vaultEndpoint
* Rename Secret -> KeyVaultSecret, Key -> KeyVaultKey
* getRecoveryLevel - potentially move to a flags enum / extensible enum
* If isManaged() is always returned from service, change to a primitive type
* Hsm -> hardwareProtected
* KeyImportOptions -> ImportKeyOptions
    * Remove the simple overload for importKey
* Consider restoreKey -> restoreKeyBackup
* getKeyWithResponse - need to have just once (revisit once we've completed renames)
* Make getKeyWithResponse() on CryptographyClient internal
* Rename getKeyMaterial() -> getKey()
    * Why don't we call it getJsonWebKey()?
* Lift keyOps and keyType to Key client
* @JonathanGiles to follow-up with @g2vinay on moving JsonWebKey into root.

**Comment by adrianhall** [comment]
Python Review: https://msit.microsoftstream.com/video/41a79604-f7f6-4843-97df-623b5d4208dc

* Across board - move optional args into kwargs (except version, which will be a named argument)
* list_secrets_properties -> list_properties_of_secrets
* expires -> expires_on
    * Move into kwargs - ordering ceases to be an issue
