### ISSUE TITLE
Change Request: Guidelines for C - Introduction.md 

### ISSUE THREAD

**Issue by mamokarz** [Azure/azure-sdk#682]
#### The Basics
* We must not introduce breaking changes, no exceptions.  The sentences are too vague.
    * Replace: Incompatibilities should never be introduced deliberately without thorough review and very strong justification.
    * By: Incompatibilities should never be introduced. Any change on signature or in the behavior that is incompatible with the previous behavior, shall be done introducing a new API and deprecating the previous one.

#### Reasoning
* Breaking changes are bad behavior.
* Breaking changes harm our customers and became strong arguments to customers avoid our services.
* Other teams in Microsoft relies their services on our SDK, in some cases offering 30 years of guaranty over our LTS. Introduce a breaking change on our code will break the contract of these other teams. Ex: Azure Sphere.

**Comment by adrianhall** [comment]
This is a design principal change, so it needs to be approved by the whole board, and it needs to go into all the guidelines (not just C99)

**Comment by JeffreyRichter** [comment]
I agree that we have a strong goal of maintaining compatibility. However, to a large extent, this is out of our hands as most of the operations implementation is controlled by the service we are wrapping and the service may break compatibility. So, I'm hesitant to use such strong wording when we don't control the whole implementation. 

However, if the guideline allows us to produce a new, non-backwards compatible library that customers opt into allowing us to slowly deprecate older libraries, then I'm OK with the strong wording.

**Comment by barcharcraz** [comment]
I think here it's more important to look at what azure as a whole guarantees, do we promise to our customers that we'll never introduce a breaking change? We want to align this with what we are telling our customers, not with what we wish were true.

**Comment by mamokarz** [comment]
We have some customers, like Azure Sphere, that has a contract with theier customers with guarantees of 30 years on the public API. On Azure IoT we inherited this guarantees and we never introduce breaking changes. If other Azure Services intend to work with theses customers, they should do the same thing.
