### ISSUE TITLE
Change Request: Guidelines for C99 - design.md

### ISSUE THREAD

**Issue by mamokarz** [Azure/azure-sdk#685]
### Naming conventions.
* Can we use single leading underscore to indicate non-public API?
* Missing: Do use upper-case for macros, constants, and enumerators.
* The way that we organize the variables inside of the structures shall NOT be mandatory. Other factors may be more relevant than the type or the alphabetic order. 
* No pascal-casing in the enum. Let’s be consistent with snake-casing. 

### Client interface.
* The az_shortname_create_client() function predict that this function will allocate and return the control block of the client. Instead, it shall receive the memory already allocated and just initialize it. This function shall return a result instead of a pointer. 
* The API should be symmetric, it means that if we have `create`, we should have `destroy`. For `open`, `close`, and for `init`, `deinit`. 
* What is the difference between `begin` function and `async`?
* Everything particular to HTTP should not be in the guidelines.
* We cannot use libuv.

### Pagination.
* Why we have it in the guidelines?

### Error handling.
* Missing az_result format.

### Memory management.
* The az_iot_create_client example is not correct, it should return az_result, and the name should init because we are not creating the client.
* Missing a better definition of the memory ownership, for example, if a function needs to keep a provided buffer for more time that its execution, how the function inform the caller that it is time to release the memory? 

### Object model.
* Init function shall return az_result.
* `internal` is a reserved word. We are using double definition of the structure, one private with the parameters, and one public with a dummy size. 
* The example az_catherding_herb_init_with_cats is not correct.

### Missing test guidelines.
* The guidelines shall make it clear that no code shall be pushed without UT and E2E test, no exceptions.
* What is the minimum code coverage or any other parameter that we can reinforce that no code is pushed without test. 
* To be able to write define the UT, all components shall have a list of requirements.

### Missing sample guidelines.
* All functionalities shall have samples to easily show developers how to use it.

### Missing code review guidelines.
* The guidelines shall predict the minimum number of reviews over any code before go to master.

**Comment by barcharcraz** [comment]
Internal is a reserved word by whom? I'm not seeing it in the C spec

**Comment by barcharcraz** [comment]
#721 for changing internal

**Comment by barcharcraz** [comment]
In the case of the catherding_herd_init functions they can not fail, and so don't return az_result.

**Comment by barcharcraz** [comment]
#722  for returning az_result instead of az_error
