### ISSUE TITLE
Change Request: Guidelines for C99 - implementation.mb

### ISSUE THREAD

**Issue by mamokarz** [Azure/azure-sdk#686]
### Complexity management
* Initialize variable with a predict state is wrong. We should say the opposite of it.
* Most of the example use what is knowing as Yoda style, we should invert it.

**Comment by barcharcraz** [comment]
Are you saying we should never initialize variables? I'm a fan of zeroing everything by default unless you have a good reason not to do so, it makes your code more robust in the face of external change.

Maybe we should change it from MUST to SHOULD (I certainly have no problem with not initializing things in some cases).

**Comment by barcharcraz** [comment]
Changing away from yoda style is fine by me, since there are compiler warnings to catch the bug it prevents.

**Comment by barcharcraz** [comment]
actually the section on variable initialization is wrong in any case, since compiler warnings will pretty much never catch use of an uninitialized variable except in very specific cases (static analyzers do sometimes, however).

**Comment by barcharcraz** [comment]
opened a pull request with proposed new position on variable initialization.

**Comment by barcharcraz** [comment]
OK. Consider the code:
```c
#include <stdio.h>
#include <stdlib.h>

void other_function(int* i) {
    if(rand() == 0) {
        *i = 4;
    }
}

int thing() {
    int i;
    other_function(&i);
    return i;
}

int main() {
    return thing();
}
```

this compiles with no warnings on gcc 6.3 and msvc 19.22, it even passes static analysis checks on msvc (haven't tried other static analysis tools).

However i can clearly be uninitialized.

This could happen in the error case if the error is set in an out parameter (for some third party library), or if the function you call happens to return an uninitialized value itself.

**Comment by barcharcraz** [comment]
I compiled that with
/W4 /analyze on msvc and -Wall -Wextra -pedantic on gcc

**Comment by barcharcraz** [comment]
The following code also compiles cleanly on gcc and clang, although msvc warns (msvc's backend seems to be insanely good at this)

```c
bool test() { return true; };

int thing()
{
    int i;
    for (int j = 0; j < 150; ++j)
    {
        if (test() && j == 4)
        {
            break;
        } else {
            i = 4;
        }
    }
    return i;
}

int main()
{
    return thing();
}
```

**Comment by mamokarz** [comment]
This is odd that compilers accept it. In this case, we should have a restriction for variables that return function value.

"variables that are intended to hold the function’s return value shall not be initialized, so that the compiler can warn about paths where the return value is not set"

**Comment by mamokarz** [comment]
I did some more reserches on out test infra, and OSX compiler (clang with a lot of warnings enable, including non-initialized) throws an error for the thing() function.
