### ISSUE TITLE
Define strategy to avoid leading customers to websites published by repo-forks

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk#6876]
GitHub pages supports publishing the website from each fork w/o any control or hint about if the site is coming from a fork or not.
This might result in multiple sites pointing to the docs, from different urls, and confusing customers.

Some mitigation ideas:
- Add a note to the [contributing doc](https://github.com/Azure/azure-sdk/blob/main/CONTRIBUTING.md) to ask contributors to avoid keeping the site published from their fork. Tell folks they can publish the site in their fork to share a demo for a change, but once the work is completed, they should unpublish the site
- Include a note within the site that validates the current url and displays a note when host is not azure.github.io. This would mitigate future cases to happen, helping customers to get to the main site. However, this will not help with any current site published.
- Create a pipeline to check if the site is publish from each fork and create a report/alert when a site is published. Use the report to ask the user to remove it.

**Comment by weshaggard** [comment]
While this can cause some confusion, I'm not sure we need to do anything here. At most I'd suggest someone write a script to see how many of the forks have an github.io site and then try to reach out to those folks. I personally don't think we even need that but if someone feels inclined by all means go for it.
