### ISSUE TITLE
Board Review: Azure Identity Full API Review

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk#696]
| Language | Review |
| --- | --- |
| .NET | [Azure.Identity](https://apiview.azurewebsites.net/Assemblies/Review/dc117ad55cc04d5d999458e44c99ee54) |
| Java | [com.azure.identity](https://apiview.azurewebsites.net/Assemblies/Review/2a23558e091248958cbfd49125e58cb7) |
| JS | [@azure/identity](https://github.com/Azure/azure-sdk-for-js/pull/5559) |
| Python | [azure-identity](https://github.com/Azure/azure-sdk-for-python/pull/7875) |

**Comment by adrianhall** [comment]
Scheduled for 10/18 and 10/21

**Comment by adrianhall** [comment]
Review Link: https://msit.microsoftstream.com/video/10a38eba-1998-487f-9e13-71a140f6ffa5

Java:
- Resolve DeviceCodeChallenge vs. DeviceCodeInfo - DeviceCodeInfo is the winner
- Reconsider organization of classes within the package tree
- AuthorizationCodeCredential -> TokenRequestContext
- getExpiresIn() -> getExpiresOn() (and calculate it)
- deviceCodeChallengeConsumer -> Rename as needed and check the parameter name is consistent
- Remove getMsiEndpoint() and getMsiSecret()
- Verify all client/tenant ID parameters are ordered tenant_id, client_id (and appropriately optional)

.NET:
- AzureCredentialOptions -> TokenCredentialOptions
- DefaultAzureCredential -> DefaultCredential 
    - Do we feel it is worth the change?  Make not be given timeline and marginal improvement
- DefaultAzureCredentialOptions
    - Rename Include -> Exclude and make entire chain included
    - Design consideration follow-up offline
    - Like DefaultCredentialOptions as a rename
- PreferredAccountUsername -> SharedTokenCacheUsername
- Kill type SharedTokeCacheCredentialOptions
- DeviceCode - remove Interval
- @KrzysztofCwalina - should we add a base AzureException?
- MSAL gets pulled in when Azure.Identity is pulled in
- Verify all client/tenant IDS are in order tenant_id, client_id (and ensure appropriately optional)

Python:
- InteractiveBrowserCredential - client_id is optional and should be a kwarg
- client_id/tenant_id should always be ordered tenant_id, client_id when required (and in kwargs when optional)
- client_id in ManagedIdentityCredential should be in kwargs

JavaScript:
- Change underscored property names to camel case
- Remove const AggregateAuthenticationErrorName
- clientSecret issue - use constructor overloads
- getToken needs to be updated to take a TokenRequestContext
- Always use tenant_id, client_id and move to options bag when optional
- For ManagedIdentityClient, make the constructor an overload so we can doc properly

Q: Should we move Azure.Identity to be under Azure.Core
- High risk with large changes
- Would need sign off - @KrzysztofCwalina to send proposal to arch board.

Q: Should DefaultAzureCredential be moved to Azure namespace?  
- Defer until we decide renaming scope

Action Items:
- @schaabs to produce table of all the credentials and their params, compare across languages
