### ISSUE TITLE
Board Review: Management Plane Namespace Review <Azure.ResourceManager.Microsoft.Discovery>

### ISSUE THREAD

**Issue by tarsharm** [Azure/azure-sdk#6965]
Thank you for submitting this review request. Thorough review of your management library namespaces ensures that your library names are consistent with the guidelines and the consumers of your management library have a consistently good experience when using Azure.

To ensure consistency, all language library names will generally be reviewed together.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.**

## Contacts and Timeline

* Responsible service team: Azure Migrate engineering team.
* Main contacts: tarsharm, manthanm
* Expected code complete date:10-12-23
* Expected release date:14-01-24

## About the Service (required)

Link to documentation introducing/describing the service: https://learn.microsoft.com/en-us/azure/migrate/ 
Link to the service REST APIs Specs: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/migrate/resource-manager/Microsoft.OffAzure
Link to GitHub issue for previous review sessions, if applicable: NA 

## Namespace Proposals (required per language)

**In the examples below please replace every occurrence of [ResourceProviderName] with your the service resource provider name. Be sure to keep the casing shown with [ResourceProviderName] when replacing it with the service resource provider name.**

- **.NET:** `Azure.ResourceManager.MigrationDiscovery`
- **Java:** `azure-resourcemanager-migrationdiscovery(com.azure.resourcemanager.migrationdiscovery)`
- **Go/Golang:** `sdk/resourcemanager/migrationdiscovery/armmigrationdiscovery`
- **JavaScript:** `@azure/arm-migrationdiscovery`
- **Python:** `azure-mgmt-migrationdiscovery`

## Thank you!

**Comment by tarsharm** [comment]
To provide more context. We are from azure migrate service and we provide the following capabilities

Discovery workloads/servers from customer's on-premise setups
Assess and migrate these workloads to azure.
We're a GA service and are planning to do an SDK release alliging with APEX PLR requirements.
We own two RP namespaces
Microsoft.OffAzure - discovery services
Microsoft.Migrate - assessment and migrate powering services
I have some questions related to SDK generation. Please help answer those or point me to any documentation i can follow

According to the issue template ive updated the package names. If you feel we can get more customized package names, do let us know. We will make the package names more user friendly. especially for Microsoft.OffAzure RP as that is not a customer friendly name (we will create a similar request for that RP soon)
We have several services under Microsoft.Migrate RP and are planning to check-in seperate swaggers for them in the official repo. Can we (and should we) publish a common SDK or multiple SDKs according to the swaggers?
We are trying to release the SDK by EOY, but I presume you will have release embargoes during year end. When can we release post that? Mid Jan?

Issue raised for Migrate RP - https://github.com/Azure/azure-sdk/issues/6964

**Comment by ronniegeraghty** [comment]
Hi @tarsharm,
Thank you for submitting a request for a MGMT Plane Namespace Review.

On the namespaces you proposed, we generally don't use the Microsoft prefix from the RP and we avoid using Azure in the low level of the namespace since all packages are already prefixed with Azure. 

Please see my answers below on your questions.

> According to the issue template ive updated the package names. If you feel we can get more customized package names, do let us know. We will make the package names more user friendly. especially for Microsoft.OffAzure RP as that is not a customer friendly name (we will create a similar request for that RP soon)

We can use custom names for the packages. In most cases the RP just tends to be the best name.
The namespace for this service name be a little difficult to come up with. Since we avoid repeating Azure in the namespace, following our normal pattern the namespaces for this service would look like `Azure.ResourceManager.Off` and I don't believe that is a great choice. 
@tarsharm, if you have a suggestion, please comment it below. 
@ArthurMa1978, if you have any suggestions as well, please do the same. 

> We have several services under Microsoft.Migrate RP and are planning to check-in seperate swaggers for them in the official repo. Can we (and should we) publish a common SDK or multiple SDKs according to the swaggers?

The answer to this question may depend on if you're strictly talking about MGMT libraries or Data Plane libraries. I'll ask @ArthurMa1978 to comment on the MGMT plane, but on the data plane side the answer would be yes. It usually better to break the library up if the API Surface of the service is large and has distinct parts.

> We are trying to release the SDK by EOY, but I presume you will have release embargoes during year end. When can we release post that? Mid Jan?

I do believe there is a cut off date for release MGMT Plane libraries before the end of the year. @ArthurMa1978 can you please let us know what that date is. For Data plane libraries there is no in-band release cycle in December but teams can still release out-of-band, however I cannot guarantee the Azure SDK team will be able to support your team if you run into issues since a large amount of our team will be taking time off. We also generally recommend against releasing in December for this reason.

**Comment by ArthurMa1978** [comment]
Some questions I replied in https://github.com/Azure/azure-sdk/issues/6964, as these 2 resources are under the same folder, please only can be released in one package.

**Comment by ronniegeraghty** [comment]
@tarsharm, in #6964 it was stated that the RP would no longer be broken into multiple libraries. Because of that I think this issue is no longer needed. If I am right, please close out this issue.

**Comment by ronniegeraghty** [comment]
@tarsharm, pinging again to see if this issue is still needed. If not, please close it. If it is needed let me know.

**Comment by ronniegeraghty** [comment]
Closing issue as there has been no response.

**Comment by tarsharm** [comment]
HI @ronniegeraghty / @ArthurMa1978 , We have decided to go with single SDK for OffAzure , And want to name it as Azure.ResourceManager.Discovery . This is a first time release of SDK. So please approve this name and reopen this issue if required.

**Comment by ronniegeraghty** [comment]
> HI @ronniegeraghty / @ArthurMa1978 , We have decided to go with single SDK for OffAzure , And want to name it as Azure.ResourceManager.Discovery . This is a first time release of SDK. So please approve this name and reopen this issue if required.

Please update the main description of this issue with the proposed names for each language. 
Thank you.

**Comment by tarsharm** [comment]
> > HI @ronniegeraghty / @ArthurMa1978 , We have decided to go with single SDK for OffAzure , And want to name it as Azure.ResourceManager.Discovery . This is a first time release of SDK. So please approve this name and reopen this issue if required.
> 
> Please update the main description of this issue with the proposed names for each language. Thank you.

DOne

**Comment by tarsharm** [comment]
Hope the names follow all required quidelines of naming- 
.NET: Azure.ResourceManager.Discovery
Java: azure-resourcemanager-Discovery(com.azure.resourcemanager.discovery)
Go/Golang: sdk/resourcemanager/Discovery/armdiscovery
JavaScript: @Azure/armdiscovery
Python: azure-mgmt-discovery

**Comment by ArthurMa1978** [comment]
The new namespace LGTM.

**Comment by ronniegeraghty** [comment]
Updated the Java and Go names to only contain lowercase letters. 
We'll now move to the second phase of the review process. The proposed namespaces will be shown to our SDK Architecture team. They will have 1 week to make any objections to the proposed namespaces. If there are no objections by EoB on 2/6 the namespaces will be considered approved, and I'll update this issue with a comment stating so.

**Comment by tarsharm** [comment]
Let me check internally and respond.

**Comment by tarsharm** [comment]
Let me know if this can be approved

**Comment by ronniegeraghty** [comment]
I'll share your counter proposal for the namespace with our architects, but I think we'll get feedback saying we should not reuse the word "Resource" as it's redundant or confusing since it refers to a different context of resources.

**Comment by tarsharm** [comment]
But that's what we do we discover different resources like VM, webapps , sql and do it in different context like DR, MIgration and Arc, so this is one name that fits .

**Comment by tarsharm** [comment]
@ronniegeraghty  Also to our partners like Oracle , SAP who will be consuming our discovery sdk , we are going to suggest Azure.ResourceManager.ResourceDiscovery.SAP / Azure.ResourceManager.ResourceDiscovery.Oracle etc. , basically Azure.ResourceManager.ResourceDiscovery.<PartnerName>, Can you also confirm and get this format approved ?

**Comment by ArthurMa1978** [comment]
The namespace shouldn't be 4 levels.

And I think `ResourceDiscovery` is ok, as we already have other similar RPs:

- Azure.ResourceManager.ResourceGraph
- Azure.ResourceManager.ResourceHealth
- Azure.ResourceManager.ResourceMover
- Azure.ResourceManager.Resources

**Comment by tarsharm** [comment]
Sure @ronniegeraghty, we can go with Azure.ResourceManager.ResourceDiscovery and Azure.ResourceManager.ResourceDiscoveryOracle / Azure.ResourceManager.ResourceDiscovery<PartnerName> for partners if approved.

**Comment by tarsharm** [comment]
hi @ronniegeraghty , how long should i expect this issue to close in , as partners are waitinf to start work on sdk generation.

**Comment by ronniegeraghty** [comment]
Hi @tarsharm, once we resolve the objection on of our architects made, we'll be good to go. 

Here's the latest feedback from our architect on the `Azure.ResourceManager.ResourceDiscovery` naming.

> ResourceDiscovery reads like [part of a service mesh a la Consul](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.hashicorp.com%2Fconsul%2Fdocs%2Fconcepts%2Fservice-discovery&data=05%7C02%7Crgeraghty%40microsoft.com%7C1970c544711d4d58d83408dc27a8544d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638428851133266471%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=sR9unGMdhfVlJFKfTxQc3KiX46h7WnM%2BoqcW%2BrHARWM%3D&reserved=0) to me.  And you’re right that Resource is misleading when you’re putting it in an ARM package but it refers to non-ARM things.  More importantly though, their docs at [https://learn.microsoft.com/en-us/azure/migrate/migrate-services-overview](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fmigrate%2Fmigrate-services-overview&data=05%7C02%7Crgeraghty%40microsoft.com%7C1970c544711d4d58d83408dc27a8544d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638428851133275942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=e5VjfYAT2kPNJRBJAiCwy5YDHIa67yNLu%2B7zM6sIgo0%3D&reserved=0) describe it as:
> > Azure Migrate: Discovery and assessment –  Discover and assess servers including SQL and web apps
> > Discover and assess on-premises servers running on VMware, Hyper-V, and physical servers in preparation for migration to Azure.

> It sounds very much like this library’s primary use case is to help people migrate their workloads to Azure.  Sticking the word Migration or Migrate in there will really help their target customers find the right package.  Similarly, I don’t think anyone already running on Azure would want this package and Migrate would help them easily avoid it when [scrolling through nuget search results](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nuget.org%2Fpackages%3Fq%3DAzure.ResourceManager&data=05%7C02%7Crgeraghty%40microsoft.com%7C1970c544711d4d58d83408dc27a8544d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638428851133281655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=6tKXwOUZP1xnxTsJZb96XEUIfKLYHDscg6qscLOu%2FyQ%3D&reserved=0).

If you let me know your email address, I can add you to the thread where the architects are discussing the names.

**Comment by tarsharm** [comment]
The scenario is discovery + migrate, we already have another RP Migrate for that, and there we will be utilizing Migrate SDK namespace. This is the initial step for migration and is kept generic and not made part of migrate, Multiple scenarios are there for discovery, few of the important one are DR, ARC etc. apart from Migration. In summary, migrate will be taken as namespace for another service that actually does the migrate. Issue 6964 was opened for it but that is still under discussion. I would recommend it keeping as generic as possible like ResourceDiscovery.

**Comment by tarsharm** [comment]
Email id is - tarsharm@microsoft.com

**Comment by tarsharm** [comment]
@ronniegeraghty , Let's name it - Azure.ResourceManager.MigrationDiscovery,  Please approve this , and unbloack this issue. To partners we can suggest Azure.ResourceManager.MigrationDiscoveryOracle.

**Comment by tarsharm** [comment]
Hi @ronniegeraghty , **Can we close the issue now ?** 
Here is what we will be following :
**Discovery SDK :** 
Namespace - Azure.ResourceManager.MigrationDiscovery
**Namespace proposol for each language:**
.NET: Azure.ResourceManager.MigrationDiscovery
Java: azure-resourcemanager-migrationdiscovery(com.azure.resourcemanager.migrationdiscovery)
Go/Golang: sdk/resourcemanager/migrationdiscovery/armmigrationdiscovery
JavaScript: @azure/arm-migrationdiscovery
Python: azure-mgmt-migrationdiscovery

**Namespace proposol for partners :** 
Azure.ResourceManager.MigrationDiscovery<PartnerName>   , Example - Azure.ResourceManager.MigrationDiscoveryOracle

**Comment by ronniegeraghty** [comment]
Yes, we can now close this review as all languages have approved their proposed names.
