### ISSUE TITLE
Test packages in both live and simulated environments

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#7]
All tests should be runnable against both live Azure and some form of locally-runnable simulated environment.  This simulated environment could be the actual service code running in a container (e.g. CosmosDB), or a set of recorded HTTP requests and responses and scripts for how they should be replayed.

Ideally we would have a single simulator per service which can be used for tests in all languages.  We do *not* want a different simulator per service per language, both because it's duplicated work and could lead to inconsistencies.

CC: @weshaggard

**Comment by johanste** [comment]
On two separate occasions (once for Python, once for Java) have I had to answer questions on how to handle storage/streaming tests for large files. Even without fault injection, the naive implementation of testing a "very large file"(tm) upload involves creating a local file of said size (multiple TB) and then convincing your recording framework to not actually include the payloads. Similar problems in reverse for downloads.

Taking it one step further, as soon as you want to try things like our retryable stream up and download implementations, additional custom steps (different for different playback frameworks/languages) are needed to trick the playback to inject errors.

**Comment by Petermarcu** [comment]
@mikeharder is this still an issue and if so, are we using it to track open items or are they tracked elsewhere?

**Comment by kurtzeborn** [comment]
Closing old epic which is now covered by new work/epics.
