### ISSUE TITLE
Merge etag handling guidelines into .NET guidelines

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-sdk#707]
See PR #646

**Comment by heaths** [comment]
At some point, @KrzysztofCwalina wanted me to write up specifics on `ETag` handling as shown here: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search.Documents/src/Indexes/Models/SearchIndex.cs until the generator does it (https://github.com/Azure/autorest.csharp/issues/668). This doc work should document that.
