### ISSUE TITLE
Board Review: Management Plane Namespace Review Azure.TrustedSigning

### ISSUE THREAD

**Issue by ashutak84** [Azure/azure-sdk#7099]
Thank you for submitting this review request. Thorough review of your management library namespaces ensures that your library names are consistent with the guidelines and the consumers of your management library have a consistently good experience when using Azure.

To ensure consistency, all language library names will generally be reviewed together.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.**

## Contacts and Timeline

Responsible service team: Azure Code Signing
Main contacts: [ashuku@microsoft.com](mailto:ashuku@microsoft.com), [rakiasegev@microsoft.com](mailto:rakiasegev@microsoft.com), [meha.sharma@microsoft.com](mailto:meha.sharma@microsoft.com), [Amrita.Shanbhag@microsoft.com](mailto:Amrita.Shanbhag@microsoft.com)
Expected code complete date: Feb 20, 2024
Expected release date: April 1st, 2024

## About the Service (required)

* Link to documentation introducing/describing the service: https://techcommunity.microsoft.com/t5/security-compliance-and-identity/azure-code-signing-democratizing-trust-for-developers-and/ba-p/3604669
* Link to the service REST APIs Specs: https://github.com/Azure/azure-rest-api-specs-pr/pull/16461
* Link to GitHub issue for previous review sessions, if applicable:  

## Namespace Proposals (required per language)

- **.NET:** `Azure.ResourceManager.TrustedSigning`
- **Java:** `azure-resourcemanager-trustedsigning(com.azure.resourcemanager.trustedsigning)`
- **Go/Golang:** `sdk/resourcemanager/trustedsigning/armtrustedsigning`
- **JavaScript:** `@azure/arm-trustedsigning`
- **Python:** `azure-mgmt-trustedsigning`

## Thank you!

**Comment by ronniegeraghty** [comment]
Pinging here again to add the namespaces for the other languages

**Comment by ronniegeraghty** [comment]
@ashutak84 
Pinging here again. Please add the namespaces for the other languages. If there is no update in a week, I'll close this issue out.

**Comment by ronniegeraghty** [comment]
Closing this issue as there has been no response from review requester. No namespaces have been approved.

**Comment by ashutak84** [comment]
Could you please reopen this one. I think my comments were there at the bottom, but i missed to update each namespace there.

**Comment by ArthurMa1978** [comment]
According to the description of the service, the namespace should be:
- **.NET:** `Azure.ResourceManager.CodeSigning`
- **Java:** `azure-resourcemanager-codesigning (com.azure.resourcemanager.codesigning)`
- **Go/Golang:** `sdk/resourcemanager/codesigning/armcodesigning`
- **JavaScript:** `@azure/arm-codesigning`
- **Python:** `azure-mgmt-codesigning`

**Comment by ashutak84** [comment]
Hi Arthur, thanks for taking a look at it, the one in the comments are the latest and the approved ones from our PMs, i have updated the description accordingly.

**Comment by ronniegeraghty** [comment]
@ashutak84, 
The namespaces in the description of the issue break a few of our naming rules. 
Rules to follow: 
- `Azure` should not be repeated in the namespace. `Azure` is already at the beginning of every namespace and does not need to be repeated. 
- `microsoft` should not be included in the naming as Azure is a known brand of Microsoft and including `microsoft` in the naming is also seen as repetitive. 
- There should be no `[` or `]` in the namespaces. Those were included in the sample patterns to show where you need to replace something with specifics for your service. 
- Mgmt Plane namespaces should be kept to only 3 levels. 
   - For .NET this means only 3 words or phrases separated by `.`. So .NET would be `Azure.ResourceManager.CodeSigning`. 

Please re-do the proposed namespaces to fit these rules.

**Comment by ashutak84** [comment]
Thanks for the clarifications @ronniegeraghty  i have updated the names, for .net our pms had decided to keep it as Azure.Developer.Signing

**Comment by ronniegeraghty** [comment]
> Thanks for the clarifications @ronniegeraghty i have updated the names, for .net our pms had decided to keep it as Azure.Developer.Signing

That will not work either. The mgmt plane namespaces need to follow the rules I listed above and the pattern for mgmt plane namespaces.  
.NET namespaces must follow this pattern: `Azure.ResourceManager.[ServiceName]`. Replace `[ServiceName]` with the name of your service. So for this example I would suggest `Azure.ResourceManager.DeveloperSigning`. If you go with this proposal the other languages namespaces would have to switch from using `CodeSigning` as the service name, to using `DeveloperSigning`.

**Comment by ArthurMa1978** [comment]
As offline synced with @ashutak84, we agreed to use `developersigning` :
**.NET:** `Azure.ResourceManager.DeveloperSigning`
**Java:** `azure-resourcemanager-developersigning(com.azure.resourcemanager.developersigning)`
**Go/Golang:** `sdk/resourcemanager/developersigning/armdevelopersigning`
**JavaScript:** `@azure/arm-developersigning`
**Python:** `azure-mgmt-developersigning`

**Comment by ashutak84** [comment]
as per the last update from @ronniegeraghty's  email i have updated it to trustedsigning please take a look at it and approve.

**Comment by ArthurMa1978** [comment]
TrustedSigning is good for me.

**Comment by ronniegeraghty** [comment]
Moving to phase 2 of the review process. The proposed namespaces will be shown to the Azure SDK Architecture Board and our architects will have 1 week to make any objections to the proposed namespaces. If there are no objections by 3/20 then the namespaces will be considered approved, and I'll close out this issue and leave a comment stating so.

**Comment by ronniegeraghty** [comment]
The week is up and there have been no objections from our architects. The names in the description of this issue are considered approved.
