### ISSUE TITLE
Storage container delete and recreate requires user to implement their own long running operation semantics

### ISSUE THREAD

**Issue by Petermarcu** [Azure/azure-sdk#710]
azure.core.exceptions.ResourceExistsError: The specified container is being deleted. Try operation later.
RequestId:a39257c4-201e-00da-114d-840de0000000
Time:2019-10-16T18:10:51.2893769Z
ErrorCode:ContainerBeingDeleted
Error:None

Our guidelines "in spirit" specify that anywhere the response from the service is effectively a "try again later" means that this is a retryable error. We will likely need service support but we should be providing a good semantic for customers to be able to specify that they want to retry, what the timeout should be, etc.

**Comment by tg-msft** [comment]
Closing as I don't think we want to add this to the storage client libraries today.  Deleting and immediately recreating the same resource would probably be better handled using [something like Polly](https://github.com/App-vNext/Polly#retry) in an application specific context.  //fyi @seanmcc-msft
