### ISSUE TITLE
Board Review: Azure.Storage.Files.DataLake

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#712]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Storage
* Link to documentation describing the service: https://apiview.azurewebsites.net/Assemblies/Review/548418d761fb45ce9fc98c8cfa9f5ef8
* Contact email (if service team, provide PM and Dev Lead): seanmcc

## About this client library

* Name of the client library: Azure.Storage.Files.DataLake
* Languages for this review: .Net
* Link to the service REST APIs:

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.azurewebsites.net/Assemblies/Review/548418d761fb45ce9fc98c8cfa9f5ef8
* Link to samples for champion scenarios:

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link:
* Link to samples for champion scenarios:

### Python

* Upload the api as a Draft PR.  Link to PR:
* Link to samples for champion scenarios:

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR:
* Link to samples for champion scenarios:

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Describe the champion scenario
    * Estimate the percentage of developers using the service who would use the champion scenario
    * Link to the code sample

_ Repeat for each champion scenario _

Examples of good scenarios are technology agnostic (i.e. the customer can do the same thing in multiple ways), and are expected to be used by > 20% of users:

* Upload a file
* Update firmware on the device
* Recognize faces in an uploaded image

Examples of bad scenarios:
* Create a client (it's part of a scenario, and we'll see it often enough in true champion scenarios)
* Send a batch of events (again, part of the scenario)
* Create a page blob (it's not used by enough of the user base)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by adrianhall** [comment]
.NET Review:

- This SDK calls two endpoints - the blob endpoint and the DFS endpoint.
- majority of "big" customers have hierarchical namespace turned on for the storage account.
- Major issue is that hierarchical namespace detection - we may want to ask for a precondition from the service.  Known issue / docs issue.
- Assumption is that this is for larger / more sophisticated customers.
- Add constructors that just takes the `serviceUri`, and `serviceUri` + shared key, and `serviceUri` + token
    - pattern should be applied to all clients
- Rename clients to ensure DataLake is prepended to all client names.
- Ensure credential types are tied to all clients appropriately. (token credential is missing some places)
- Board thinks `Read` and `Flush` are non-consistent - dig into requirement from customers; our preferred verbs are `Download` and `Commit`.
- In `PathClient`, 
    - `BuildMetadataString` should be internal.
    - `SetNameFieldIfNull` should be protected internal.
- Verify that `FileClient.Rename` only shows a `FileClient` return type, not `PathClient`.
- Split SetAccessControl into two methods - one for permissions and one for ACLs (split the model types as well).
     - Work on design for models.  The permissions strings are of concern as they are specific forms.
     - These are posix permissions, but the ACL is more complex
- Don't derive `DataLakeClientOptions` from `BlobClientOptions` (ditto for other derived types in blob namespace)
- Remove `GetPathsOption` (follow getblobs)
- Remove `CustomerProvidedKey` (not supported in data lake)
- `PathHttpHeaders` should be a class.
- `PathSegment` should be hidden
- Rename conflicting types from Blob to have the `DataLake` prefix.  
- Remove the `EncryptionAlgorithmType` - it's part of CPK

-
