### ISSUE TITLE
EngSys: Updating GitHub Assignees and Reviewers fields are super slow for Azure/* repos

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk#717]
Opening up a tracking issue by request;

The Assignees and Reviewers fields on GitHub Issues and Pull Requests in the azure/azure-sdk-for-* repos contain everyone in the Azure org, which stresses the limits of the GitHub web UI.

Please investigate ways to make this better (usable) for the teams working in these repos.

**Comment by kurtzeborn** [comment]
@joshfree Is this specifically within ZenHub or are you seeing this in the raw github UI as well?  I've seen slowness occasionally when the ZenHub add-in is running, but GitHub as always been pretty snappy.

**Comment by Petermarcu** [comment]
It wasn't in ZenHub, it was in the regular github UI.
