### ISSUE TITLE
Board Review: Azure App Configuration

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#720]
### .NET

https://apiview.azurewebsites.net/Assemblies/Review/4f563eae75b14e4e8dea2a632e096f82

### Java

https://apiview.azurewebsites.net/Assemblies/Review/2209f75a19ca4076a31b2c7cbdbbca98/8809ab6541414db08d9a00983cbb8b7b

### Python

https://github.com/Azure/azure-sdk-for-python/pull/8101

### TypeScript

https://github.com/Azure/azure-sdk-for-js/pull/5471/files

**Comment by adrianhall** [comment]
.NET Review:

- ClearReadOnly / SetReadOnly do a user study to see if this is confusing?  It feels confusing.
    - maybe an overload? 
    - Also consider if read-only is an option and options will be expanded?
    - Needs to align with portal, perhaps?
- Consider adding an overload for GetSettings(SettingSelector(SettingSelector.Any)) to get everything? 
- SettingsFields - treat 0 as None (not All)
- Consider re-visiting AsOf naming after a user study
- Rename SettingSelector to be more in line with JS

Java Review:
- Move `ConfigurationCredentialsPolicy` to implementation folder
- Check version string with service team.
- Close on `AsOf` consistency
- Rename SettingSelector to be more in line with JS

TypeScript Review:
- Rename `readOnly` to `isReadOnly`
- Rename `lastModifiedHeader?` to `lastModified?`
    - is it an HTTP date?  (Need to review).
    - If so, it should be a date/time type. (and in other headers)
- `acceptDatetime`? Should be renamed.

Python Review:
- `set_read_only` / `clear_read_only` / `set_configuration_setting` - per user study
- `etag` and `match_conditions` should be in kwargs


Generally:
- Make the noun thing (keyvalue, setting, configurationSetting) consistent across 
- Align on setReadOnly / clearReadOnly - especially in case of options.

**Comment by annelo-msft** [comment]
.NET Review:

- ClearReadOnly / SetReadOnly do a user study to see if this is confusing? It feels confusing. 
  - maybe an overload?
  - Also consider if read-only is an option and options will be expanded?
  - Needs to align with portal, perhaps?

  **User study initiated**

- Consider adding an overload for GetSettings(SettingSelector(SettingSelector.Any)) to get everything?

    **This would require updating eight methods to maintain consistency across the client, and will be revisited based on user feedback.**

- SettingsFields - treat 0 as None (not All)

  **This is already handled correctly.**

- Consider re-visiting AsOf naming after a user study

  **User study initiated**

- Rename SettingSelector to be more in line with JS

  **Evaluating.**

General:

- Make the noun thing (keyvalue, setting, configurationSetting) consistent across

 **ConfigurationSetting was selected.**
