### ISSUE TITLE
Board Review: Management Plane Namespace Review mongocluster

### ISSUE THREAD

**Issue by olivertowers** [Azure/azure-sdk#7232]
Thank you for submitting this review request. Thorough review of your management library namespaces ensures that your library names are consistent with the guidelines and the consumers of your management library have a consistently good experience when using Azure.

To ensure consistency, all language library names will generally be reviewed together.

**Before submitting, ensure you adjust the title of the issue appropriately.**

**Note that the required material must be included before a meeting can be scheduled.**

## Contacts and Timeline

* Responsible service team: Azure Cosmos DB for Mongo vCore
* Main contacts: olivert@microsoft.com, jfigueroa@microsoft.com, siddhesh.vethe@microsoft.com, gahllevy@microsoft.com, meichint@microsoft.com
* Expected code complete date: 2/28/2024 (completed service changes and deployment and specifications review)
* Expected release date: March 2024

## About the Service (required)

* Link to documentation introducing/describing the service: https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/introduction
* Link to the service REST APIs Specs: https://github.com/Azure/azure-rest-api-specs/pull/27733
* Link to GitHub issue for previous review sessions, if applicable:  

## Namespace Proposals (required per language)

**In the examples below please replace every occurrence of [ResourceProviderName] with your the service resource provider name. Be sure to keep the casing shown with [ResourceProviderName] when replacing it with the service resource provider name.**

- **.NET:** `Azure.ResourceManager.MongoCluster`
- **Java:** `azure-resourcemanager-mongocluster (com.azure.resourcemanager.mongocluster)`
- **Go/Golang:** `sdk/resourcemanager/mongocluster/armmongocluster`
- **JavaScript:** `@azure/arm-mongocluster`
- **Python:** `azure-mgmt-mongocluster`

## Thank you!

**Comment by olivertowers** [comment]
Adding some context here:
- This is not a new RP namespace, we are adding a new service folder for existing namespace `Micrsoft.DocumentDB`. This is to allow more agility with our sister teams and de-couple the API releases for resource types that are specific to the Mongo vCore cluster service vs the rest of Cosmos DB.
- Mongo vCore service GA'd last November.
- The Mongo cluster APIs were released as **preview APIs** only under `specifications/cosmos-db` and this did include preview SDK and Azure CLI releases.
  - See existing [mongoCluster.json spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/preview/2023-11-15-preview/mongoCluster.json).
- The rollout plan will include adding the new service folder `mongocluster` + releasing new SDKs under relase 2023-03-01-preview. A subsequent change will be made to removie the existing mongoCluster.json specs from the `cosmos-db` service folder with the next API version release for that service - example relsae:
  - cosmos-db release 2024-02-15-preview - last release on cosmos-db with mongoCluster specification.
  - mongocluster release 2024-03-01-preview - first release under new folder structure with mongoCluster.json.
  - cosmos-db release 2024-03-15-preview - first release on cosmos-db without mongoCluster spec.
  - mongocluster release 2024-04-01 (stable) - second release under new folder with first stable version of mongoCluster API.

**Comment by m-nash** [comment]
Do we need the word `Cluster` here?  It looks like we went with [Azure.ResourceManager.CosmosDB](https://www.nuget.org/packages/Azure.ResourceManager.CosmosDB/1.4.0-beta.5) would we want synergy here with maybe Azure.ResourceManager.MongoDB?

**Comment by olivertowers** [comment]
@m-nash `MongoDB` conflicts with the non-MSFT Mongo database product vs the Azure/MSFT implementation of Mongo that this product represents. We opted for `MongoCluster` here since it's in aligns with the resource type that is made available through the SDK/APIs.

**Comment by m-nash** [comment]
Understood I think MongoCluster will work then in that case.

@ronniegeraghty , @ArthurMa1978 we should be good to go from my perspective on this one.

**Comment by ArthurMa1978** [comment]
Hey @olivertowers, is this similar as the https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresqlhsc/resource-manager/readme.md? which the service is part of cosmos db?
If yes, the namespace for SDK should be `CosmosDBForMongoCluster`. 
Otherwise, `MongoCluster` if good to me.

**Comment by olivertowers** [comment]
@ArthurMa1978 the intention is for the MongoCluster service to be considered independent of CosmosDB even though the ARM resources are hosted under the same RP - therefore we wanted to use a neutral name for SDK namespace as opposed to one that is inclusive of CosmosDB.

**Comment by ArthurMa1978** [comment]
Thanks @olivertowers , then the namespace `MongoCluster` is good to me.

**Comment by ronniegeraghty** [comment]
Well now be moving to phase 2 of the review process. The proposed namespaces above will be shown to our architect team. Our architects will then have 1 week to make any objections to the names. If there are no objections by End of Business on 4/19 the names will be considered approved, and I will leave a comment on this issue stating so.

**Comment by ronniegeraghty** [comment]
Yes, Since the week is up and there have been no objections from our architects, the names in the description of this issue are considered approved. Sorry for the delay.
