### ISSUE TITLE
Enable Azure DevOps SDL tools Extension

### ISSUE THREAD

**Issue by maggiepint** [Azure/azure-sdk#728]
Per internal [security guidelines](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/1761/Static-Analysis?anchor=**static-analysis-tool-applicability-per-programming--language**).

**Comment by weshaggard** [comment]
Closing issue as duplicate of https://github.com/Azure/azure-sdk/issues/335
