### ISSUE TITLE
Change Request: Private structures with public size for C99

### ISSUE THREAD

**Issue by mamokarz** [Azure/azure-sdk#730]
To expose the size of the structure without make the fields public, the structure shall be split in 2 parts. 
1)	A private structure with the fields inside, it shall be defined in an internal header like inc/internal/<my_class>.h, and the name shall start with `_`. 
2)	A public structure, that will contain only one field called `az_private` with the type of the internal structure, shall be placed in the public API header file, like inc/<my_class>_api.h, and shall have the same name as the internal one, but without the `_`.

For example, suppose a IPC class that have the control block `az_ulib_ipc`.

The internal structure shall be defined on “inc/internal/az_ulib_ipc.h” with the following format:

```c
typedef struct _az_ulib_ipc_tag {
  AZ_PAL_OS_LOCK lock;
  size_t number_of_interfaces;
  const void *interface_list;
} _az_ulib_ipc;
```

The public structure shall be defined on “inc/az_ulib_ipc_api.h” and shall contain the private field:

```c
typedef struct az_ulib_ipc_tag {
  _az_ulib_ipc az_private;
} az_ulib_ipc;
```

Doing that, the user shall create the IPC control block using the public API:

```c
static az_ulib_ipc ipc_handle;
```

if the user decide to use the fields directly, the name `az_private` will shows up before any internal field, making it clear that those fields shall not be used.

Internally, where we will use the fields, we shall cast the public structure in to the internal structure, and after that, all fields shall be accessed without the `az_private`. The cast is done as part of the inline function that handles the multiple versions of the API, for example, the IPC init function shall be something like:

```c
static inline AZ_ULIB_RESULT az_ulib_ipc_init(az_ulib_ipc *ipc_handle) {
#ifdef AZ_ULIB_CONFIG_IPC_VALIDATE_CONTRACT
  return _az_ulib_ipc_init((_az_ulib_ipc *)ipc_handle);
#else
  return _az_ulib_ipc_init_no_test((_az_ulib_ipc *)ipc_handle);
#endif /* AZ_ULIB_CONFIG_IPC_VALIDATE_CONTRACT */
}
```

**Comment by barcharcraz** [comment]
see #721

**Comment by barcharcraz** [comment]
#721 merged, please close this issue if things look right.
