### ISSUE TITLE
Documentation 404 / Link Checker

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk#735]
Some of our README.md / docs have shipped with 404s / bad links.

We should have a link checker run for all 4 languages.

related: https://github.com/Azure/azure-sdk/issues/552

**Comment by kurtzeborn** [comment]
@sdbedd I think this becomes a feature in the link remapping that you're scripts are doing in the tools repo.

**Comment by jongio** [comment]
I use this GitHub action on other repos that I manage: https://github.com/gaurav-nelson/github-action-markdown-link-check

**Comment by pakrym** [comment]
cc @AlexGhiondea

**Comment by sima-zhu** [comment]
.NET/Python/JS/C/CPP/Android/IOS verification steps have been merged already.
Go/Java is currently in progress.
