### ISSUE TITLE
As Microsoft pays so much attention to Rust, why is there not Azure SDK for Rust

### ISSUE THREAD

**Issue by IrakliLomidze** [Azure/azure-sdk#7369]
# Attention
**As Microsoft pays so much attention to Rust, why is there not Azure SDK for Rust **
Office 365 API services are going to move to Rust. Is there not a time to provide Azure SDK for Rust as well?

**Comment by maririos** [comment]
FYI @heaths

**Comment by RickWinter** [comment]
Thank you for the feedback. We encourage you provide feedback at
https://github.com/Azure/azure-sdk-for-rust on which packages and Azure services you would like to see supported in Rust.
