### ISSUE TITLE
Documentation - Indexes Should Account for Renamed Packages

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#761]
Right now, we generate github.io landing pages purely based off of what is present within the repo.

We know that packages will be renamed (most recent example being `azure-storage-fileshare`), so we may need to account for this. Depending on the level of investment to github.io docs, this may be important. 

Most straightforward way I can think of is to always include locations in the index for packages that we've published to blob storage before.\

CC @kaerm

**Comment by kurtzeborn** [comment]
This is super rare and we don't lose any history/data related to docs without this.  Cutting this feature since we'll never prioritize it enough to do it.  The amount of work needed doesn't match the benefit given how rare this will occur.
