### ISSUE TITLE
Change Request: Client interface API design is inconsistent for C99

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk#764]
Thank you for contributing to the design guidelines for Azure SDKs.  We welcome all discussions and contributions.  Since the design guidelines affect the client libraries for all Azure services, we thoroughly discuss and vet any design guideline changes before we incorporate them into the official guidance.  This process can take some time, so your patience is appreciated.

** Before submitting, ensure you adjust the title of the issue appropriately **

## The Basics

* Which design guideline is affected?

* Which target languages are affected?

* Describe the change:

## Reasoning

Please provide any additional detail or reasoning for the request.

**Comment by barcharcraz** [comment]
can you go into more detail here?

**Comment by barcharcraz** [comment]
I suspect this was the whole allocation callbacks thing.
