### ISSUE TITLE
Add more detailed snippet guidelines

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk#769]
Now that we seem to be settled on how snippets should be layed out inside the sample directory we should write it down and figure out some details like:

1. Should there be a README.md inside samples directory
2. Should we still name .md files using SampleN_ prefix?
3. Should samples add the pixel tracking like we do in READMEs?
4. Should we have MDs for both sync and async examples like we did with source files, or just reference both at the bottom?
5. Should samples/README primarily use sync or async?

@KrzysztofCwalina  @heaths @annelo-msft

**Comment by heaths** [comment]
IMO - and also because guidelines say we should (not that they can't be changed) - we should use Sample*N*_ as a prefix so that we can lexigraphically order samples based from easiest to more advanced.

**Comment by heaths** [comment]
A couple of other things to consider:

* Should samples add the pixel tracking like we do in READMEs?
* Should we have MDs for both sync and async examples like we did with source files, or just reference both at the bottom?

**Comment by kaerm** [comment]
cc: @maggiepint

**Comment by richardpark-msft** [comment]
@willmtemple has had a fun time handling this on the JS side and has gone through something similar with our dual JS/TS sample folders.
