### ISSUE TITLE
Publish Azure SDK supported versions

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk#783]
Tracking issue for publishing Azure SDK GA supported versions

Example:  https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by joshfree** [comment]
@Petermarcu @loarabia any update on this?

**Comment by loarabia** [comment]
Right now, there is already a policy documented. It’s this one : https://support.microsoft.com/en-us/help/18486/lifecycle-faq-azure .

I think there are clarifications that can be made on parts of that and I’ve been gathering data for something more thorough. I have not started condensing that into a write up yet.
