### ISSUE TITLE
Change Request: HTTP Header Logging

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk#793]
## The Basics

* Which design guideline is affected?

https://azure.github.io/azure-sdk/general_implementation.html#logging

* Which target languages are affected?

All

* Describe the change:

Change the log level used to log HTTP headers during request and response.

## Reasoning

Currently, the specification states that HTTP header logging should happen at the `Informational` log level. The specification also states that the `Informational` log level is meant to log that “things happened”, basically logging the flow of the application. Logging headers at this level could introduce a lot of noise in attempting to follow the flow of the application, additionally depending on the service this could incur a high disk and CPU usage for the purposes of logging.

My proposal is to change the HTTP header logging from the `Informational` to the `Verbose` log level. This would reduce the logging overhead if only the flow of the application should be logged and it feels more correct based on the short explanations for each log level (Verbose is meant for details).

**Comment by adrianhall** [comment]
Copying the arch board for review.  

Arch board: If you are ok with this proposal, then please indicate with a +1 or comment to that effect.  If it needs to be discussed, then please indicate that as well.

**Comment by JeffreyRichter** [comment]
I think the guidelines should be more explicit. Here's what I suggest...

Change: **DO log request line and headers as an Informational message. The log should include the following information:**
To this: **DO log outgoing requests as Verbose. The log should include the following information:**

Change the next guideline: **DO log response line and headers as an Informational message. The format of the log should be the following:**
To this: **DO log incoming responses as Informational for 1xx, 2xx and 3xx status codes and as errors for 4xx and 5xx status codes. The format of the log should include the log should include the request information (as shown above) and should also include the following response information:**

@alzimmermsft : How do you feel about the usage of verbose, informational, and error here?

**Comment by johanste** [comment]
We have almost nothing in Python that raises to the level of an `Error` log. I'd prefer to reserve `Error` for things that almost certainly require immediate attention. A 429 response that we will retry on does not fall into the `Error` category for me.

**Comment by JeffreyRichter** [comment]
I'm fine with demoting my error recommendation to warning.

**Comment by alzimmermsft** [comment]
@JeffreyRichter I am on-board with those guideline changes, the only comment I would have is potentially logging the request URL and HttpMethod at the information level as those feel like events happening and could be useful in logging the flow of an application. I also agree with @johanste around logging exceptions as a warning.

@johanste In Python when a 429 or a 503 is returned does a warning get logged then the request is retried or will the warning only be logged once retries are exhausted?

**Comment by JeffreyRichter** [comment]
I met with the Java team in person. We now think that the verbose/informational level should be language dependent. In some language ecosystems, where many things are logged, the verbose is better and in others where fewer things are logged, informational is better.

**Comment by bterlson** [comment]
We currently are logging under informational, and while I can't say which is better (or whether we fall into a log-more or log-less bucket), we'll continue doing as we have done unless there is strong reason to change.

**Comment by adrianhall** [comment]
So, do we need a guideline change to general guidelines, or is it sufficient for language architects to incorporate advice into language specific guidelines?

**Comment by JeffreyRichter** [comment]
I think we need to update the language agnostic guidelines to be more lenient otherwise the language-specific guidelines could be in violation.

**Comment by JeffreyRichter** [comment]
+1
