### ISSUE TITLE
Automate Cloudshell testing

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk#795]
We need to automate the way we run tests. The steps to run tests in CloudShell for the identity component are as follows:

### Initial Setup:
PLEASE NOTE: This setup is Go specific since CloudShell is running an older version of Go by default and we need to include the current version that has module support. Other languages will have a different set up. 
Also, if running CloudShell with a linked storage account steps 1-4 only need to be done the first time this test is run. Step 5 still needs to be run since the environment variables are not persisted every session. 
1. Open https://shell.azure.com/
2. **cd $HOME**
3. Download Golang version 1.13.1
    Run this command: **wget https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz**
4. Extract contents from tar.gz
    Run this command: **tar -xvf go1.13.1.linux-amd64.tar.gz**
5. Set environment variables:
    Run the following commands in order:
   **$env:GOROOT="$HOME/go"**
   **$env:GOPATH=$HOME**
   **$env:PATH="$env:GOPATH/bin:$env:GOROOT/bin:$env:PATH"**
6. Confirm you are running go version 1.13 or above
    Run this command: **go version**
    Expected output: _go version go1.13.1 linux/amd64_
### Run the test:
7. Clone the Go SDK repo. 
    Run this command: **git clone https://github.com/Azure/azure-sdk-for-go.git**
8. Change directory to the azidentity package.
    Run this command: **cd azure-sdk-for-go/sdk/azidentity**
9. Run the CloudShell test:
    Run this command: **go test -run TestManagedIdentityCredential_GetTokenInCloudShellLive**
    Expected output: _PASS_

**Comment by joshfree** [comment]
@AlexGhiondea - can you please help get this to the Vendor team

@kurtzeborn - can you please include this on the EngSys backlog as a template for future integration into devOps (for all languages)

**Comment by jianghaolu** [comment]
Java:
1. Open https://shell.azure.com/
2. cd $HOME

### Run the test:
3. Clone the Java SDK repo.
Run this command: git clone https://github.com/jianghaolu/azure-sdk-for-java.git -b msilivetests
4. Change directory to the root directory.
Run this command: cd azure-sdk-for-java
5. Run the CloudShell test:
Run this command: `mvn test -Dtest=ManagedIdentityCredentialLiveTest#testMSIEndpointOnAzure -pl sdk/identity/azure-identity -f pom.client.xml -Dgpg.skip`
Expected output: SUCCEED

**Comment by chlowell** [comment]
Python instructions are [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/tests/managed-identity-live/cloudshell.md).

**Comment by XuGuang-Yao** [comment]
Hi @jianghaolu  ,

I am following above steps to do python E2E test. My suggestion as below. Please correct me if I miss anything.

1.Commands with **-Dgpg.skip** fails with below error. 
![image](https://user-images.githubusercontent.com/53599438/79427316-0bcf3500-7ff7-11ea-943f-63821fde2b87.png)

So we need to inclose -Dgpg.skip with quotation marks.
`mvn test -Dtest=ManagedIdentityCredentialLiveTest#testMSIEndpointWithSystemAssigned* -pl sdk/e2e -f pom.client.xml -"Dgpg.skip" -am -DfailIfNoTests=false`

**Comment by XuGuang-Yao** [comment]
Hi @catalinaperalta ,

I am following above steps to do Go E2E test. My suggestion as below. Please correct me if I miss anything.

1.Test fails when running last command "go test".
![image](https://user-images.githubusercontent.com/53599438/79427963-10e0b400-7ff8-11ea-8c1a-99991faba7b7.png)

I tried to specify the test name by running 
`go test -run TestManagedIdentityCredential_GetTokenInCloudShellLive`
and it passed. 
![image](https://user-images.githubusercontent.com/53599438/79428493-cdd31080-7ff8-11ea-9019-5f05c9e4e3e3.png)

Did you miss specifying the test case name? If it is by design, could you please add more detial to guide me how to resolve this error?

**Comment by jianghaolu** [comment]
@XuGuang-Yao I believe on some shells the symbol "." needs to be escaped like "\." or "`.". You may be running on such a terminal. I did not test it in PowerShell as most of our customers run this in CMD or Bash.

**Comment by jonathandturner** [comment]
For JavaScript:

# Testing azure-identity in Azure Cloud Shell

# Open Azure Cloud Shell
https://shell.azure.com/

# Create an Azure Key Vault

## set environment variables to simplify copy-pasting
- RESOURCE_GROUP
  - name of an Azure resource group
  - must be unique in the Azure subscription
  - e.g. 'cloudshell-identity-test'
- KEY_VAULT_NAME
  - 3-24 alphanumeric characters
  - must begin with a letter
  - must be globally unique

## create a resource group
```sh
az group create -n $RESOURCE_GROUP --location westus2
```

## create the Key Vault
```sh
az keyvault create -g $RESOURCE_GROUP -n $KEY_VAULT_NAME --sku standard
```

# Run the tests (from inside Cloudshell)

### Build the webapp
```
git clone https://github.com/azure/azure-sdk-for-js --single-branch --branch master --depth 1
```

```
cd azure-sdk-for-js/sdk/identity/identity/test/manual-integration/Cloudshell
```

Install the requirements:
```
npm install
```

```
npm install typescript
```

Build the job:
```
node_modules/typescript/bin/tsc -p .
```

### Run test
The tests expect the vault's URI in an environment variable. Replace `<put key vault name here>` with the name of the keyvault you created earlier :
```sh
export KEY_VAULT_NAME=<put key vault name here>
```

```sh
node index
```

### Deactivate
```sh
deactivate
```

# Verify success

```
az keyvault secret show -n "secret-name-cloudshell" --vault-name "$($KEY_VAULT_NAME)"
```

# Delete Azure resources
After running tests, delete the resources provisioned earlier:
```sh
az group delete -n $RESOURCE_GROUP -y --no-wait
```

**Comment by XuGuang-Yao** [comment]
Hi @jonathandturner,

I am following above steps to do JS E2E test. My suggestion as below. Please correct me if I miss anything.

Bolow error occurred after running command `nmp install`. It may be caused by the [known keytar](https://github.com/atom/node-keytar#on-linux) issue on linux. Could you please help to change the test step to resolve the error?

![image](https://user-images.githubusercontent.com/53599438/80326636-fdd9a980-886b-11ea-86f6-0ea802306de5.png)

**Comment by jonathandturner** [comment]
Yes, all of these issues seem to be related to keytar. We'll have to figure out what is happening there. These steps largely worked before we added it but it may mean there are additional steps we need to take now that we've added keytar.

**Comment by catalinaperalta** [comment]
@XuGuang-Yao Yes you are correct to include the test name when running this test. Thanks for catching that, I've also updated the instructions to include that.

**Comment by JosueJoshua** [comment]
@jonathandturner - we are following the step of E2E Javascript test.
It will return an error when we execute `npm install`.
![image](https://user-images.githubusercontent.com/24564161/105935732-75539800-608d-11eb-805a-8904fd1a2774.png)

 And then, it return an error(Permission denied) when we try to fix it by execute the command `apt install libsecret-1-0`.Could you help to check and resolve the error?
![image](https://user-images.githubusercontent.com/24564161/105935682-5ead4100-608d-11eb-9f3f-e3ae90e9e36f.png)

**Comment by v-jiaodi** [comment]
Hi @jntrnr, I am following above steps to do JavaScript E2E test. Bolow error occurred after running command `node index` with `@azure/identity version 2.0.1`. There is no problem using this version in the local environment. Could you help to check and resolve the error?

![image](https://user-images.githubusercontent.com/80496810/141936951-28b63a8d-17f6-4372-8aae-d5ddd3f20295.png)

**Comment by v-jiaodi** [comment]
Hi @catalinaperalta, @chlowell  follow the above steps to test for go. When run command `go test -run TestManagedIdentityCredential_GetTokenInCloudShellLive`, get error as follow:

![image](https://user-images.githubusercontent.com/80496810/236982654-3f251522-33df-4e7b-85c3-f8c0dee8405b.png)


Through investigation, after clone the code, switch to `azure-sdk-for-go/sdk/samples/azidentity/manual-tests/managed-identity/general` and run `go run main.go`. It works normally. For more details, please refer to [Azure Arc testing](https://github.com/Azure/azure-sdk/issues/1908#issuecomment-1060972307).

For Azure Cloudshell testing, can we refer to [Azure Arc testing](https://github.com/Azure/azure-sdk/issues/1908#issuecomment-1060972307) to update testing instructions?

**Comment by v-jiaodi** [comment]
@joshfree, @billwert, @g2vinay For Cloudshell testing for Java, when run `mvn clean install -Dgpg.skip -DskipTests  -f sdk/core/azure-core/pom.xml `,get error message : No space left on device.

Can you help check this issue?

**Comment by billwert** [comment]
Will take a look. @v-jiaodi is this a clean VM? Do you have a link to a pipeline run?

**Comment by v-xuto** [comment]
@joshfree This issue has been closed. Do we need to continue testing this `Automate Cloudshell testing`?
