### ISSUE TITLE
Group built artifacts logically

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk#799]
At the moment our build process will upload any package produced by the build into a ```packages``` artifact. Later stages in the pipeline then need to do all kinds of filtration gymnastics to stage files into particular directories to make sure that the wrong set of files isn't accidentally published.

Rather than continue with this duplication of logic all over the place we want to change our initial artifact publishing steps to segregate each logical grouping of artifacts into its own directory. For example in our Java builds we produce three jar files and a pom file which all correspond to the same logical artifact.

We need to group artifacts by their common name, e.g. azure-core for Java or Azure.Core for .NET as a sub-folder in the packages artifact. The ```name``` attribute on the artifact list can then be used to scope operations to grouped sets of artifacts.

As part of this work we should stop uploading any artifacts which are not officially a product of a particular build pipeline (and perhaps warn that this happened).

Finally - the release pipelines do have some additional consumers beyond our mono-repos so we'll need to make sure that we accommodate these simplified scenarios (perhaps a path override).

**Comment by mitchdenny** [comment]
I've been looking at this for the POM only pipelines and rather than manipulating the package output directory the most consistent way to do it seems to be to do a ```mvn deploy``` with an altDeploymentRepository. And then just lift that repository.

The publish script then just knows how to traverse the entire directory structure. The added bonus is that we don't need the little ant script to copy the POM file since when you do a deployment the ```*.pom``` file is produced.

Once the POM-only deployment pipeline is debugged then I think that this would be a logical improvement to make to our client, data and management pipelines.

**Comment by weshaggard** [comment]
Based on some recent issues (partially release azure-core-https while trying to release azure-core-http) and the increasing number of steps in our release pipelines I think it is even more important for us to do the work to segregate the different artifacts into folder matching the name of the artifact we are releasing.

@scbedd already filed an issue for python https://github.com/Azure/azure-sdk-for-python/issues/11397 but we need to have a similar issue for the other languages as well.

**Comment by weshaggard** [comment]
I filed an associated issue for each language to do this work.

**Comment by mitchdenny** [comment]
I've promoted this issue to an epic in its own right after what I did in Java. Tieing it specifically to Unified Pipelines doesn't really make sense.

**Comment by mitchdenny** [comment]
Assigning across to Praveen, I think JS is the only one outstanding now.

**Comment by mitchdenny** [comment]
Actually I'll continue to hold the epic for now. But @praveenkuttappan do you have a timeframe for the artifact breakout in JS?

**Comment by praveenkuttappan** [comment]
I believe I will be able to get to this only after parental leave. I will try if this can be done before the leave starts.

**Comment by mitchdenny** [comment]
@praveenkuttappan thats OK, do it when you get back. I know you've got a lot on your plate. I will assign this epic to you though since JS is the only outstanding repo I believe.

**Comment by praveenkuttappan** [comment]
We have already implemented grouping based on package name. Only pending item is specific to JS where we need to create grouping more specific and organized as directory based on the scope of project. I will file an issue in JS repo since it's more specific to JS.
