### ISSUE TITLE
Add a few existing SDKs to engineering system

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#8]
- SDKs
  - KeyVault
  - Batch
- Languages
  - .NET
  - Java
  - Python
  - JavaScript
- Steps
  - Restore
  - Build
  - Test
  - Create package
  - Publish package
- Build types
  - Nightly / per-checkin
    - Signing?
    - Publish to MyGet (or equivalent)
  - PR Validation
    - No publish
    - No signing
    - Community PR (untrusted) vs Own PR (trusted)
  - Official
    - Signing
    - Publish to NuGet (or equivalent)
- Test types
  - Live Azure
  - Simulated service

**Comment by kurtzeborn** [comment]
We're done standing up the build/release pipelines in Azure DevOps.
