### ISSUE TITLE
azure.github.io Pages do not render markdown tables correctly

### ISSUE THREAD

**Issue by dellch** [Azure/azure-sdk#8068]
Hello,

I've noticed that markdown tables in the documentation are not rendering correctly on the [Azure SDK](https://azure.github.io/azure-sdk/) GitHub Pages site. Instead of displaying as formatted tables, the raw markdown code is shown.

## Example of affected page

- [Distributed Tracing Conventions](https://azure.github.io/azure-sdk/distributed_tracing_conventions.html#azure-sdk-semantic-conventions)

  In the section **"Azure SDK Semantic Conventions"**, the tables are not rendered properly.

## Source Markdown

- [distributed-tracing-conventions.md](https://github.com/Azure/azure-sdk/blob/main/docs/tracing/distributed-tracing-conventions.md)

  The tables are correctly formatted in the markdown source file. You can view the raw markdown [here](https://raw.githubusercontent.com/Azure/azure-sdk/refs/heads/main/docs/tracing/distributed-tracing-conventions.md).
  
  Note that the table headings use three `-` characters, e.g. `|---|`.

## Potential Cause

It looks like kramdown (during the jeckyl build) is rendering the `---` used to separate table headings (like `|---|` from table rows is being converted to the em-dash character (`|—|`) _before_ it tries to render the table, breaking the rendering of the table.  

See [the Typographic Symbols heading](https://kramdown.gettalong.org/syntax.html#typographic-symbols):
> ## Typographic Symbols
> _The original Markdown syntax does not support these transformations._
>
> kramdown converts the following plain ASCII character into their corresponding typographic symbols:
> --- will become an em-dash (like this —)

## Possible solution(s)
Use four (or more) `-` characters when creating table headings.

**Comment by weshaggard** [comment]
Thanks for the bug report. I've fixed this in https://github.com/Azure/azure-sdk/pull/8070

**Comment by weshaggard** [comment]
I had to revert my change because it causes other issues such as escaping inline html.

![image](https://github.com/user-attachments/assets/fd063c3c-d846-4f90-857b-7c5c3504a65b)

I'll come back to see why these tables aren't correctly rendering.

**Comment by weshaggard** [comment]
Ok Jekyll is very particular that the top and bottom of the tables must be empty lines and cannot have any content, including comments. After doing that these tables correctly render.
