### ISSUE TITLE
Automate VM MSI testing

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk#815]
We need to automate the way we run tests. The steps to run MSI tests in VM for the identity component are as follows:

# prerequisite tools
- Azure CLI

# Azure resources
This test requires instances of these Azure resources:
- Azure Key Vault
- Azure Managed Identity
  - with secrets/set and secrets/delete permission for the Key Vault
- Azure Virtual Machine
  - with system assigned identity and user assigned identity

# Initial Setup:
PLEASE NOTE: This setup is Java specific since it installs the Java & Maven environments. Other languages will have a different set up.

## Set environment variables to simplify copy-pasting
- RESOURCE_GROUP
  - name of an Azure resource group
  - must be unique in the Azure subscription
  - e.g. 'identity-test-rg'
- VM_NAME_SYSTEM_ASSIGNED
  - name of an Azure Virtual machine
  - must be unique in the resource group
  - e.g. 'identity-test-vm-system'
- VM_NAME_USER_ASSIGNED
  - name of an Azure Virtual machine
  - must be unique in the resource group
  - e.g. 'identity-test-vm-user'
- MANAGED_IDENTITY_NAME
  - 3-128 alphanumeric characters
  - must be unique in the resource group
- KEY_VAULT_NAME
  - 3-24 alphanumeric characters
  - must begin with a letter
  - must be globally unique

## Create resources
1. In a terminal with Azure CLI, run 
```bash
az vm create \
    -n $VM_NAME_SYSTEM_ASSIGNED \
    -g $RESOURCE_GROUP \
    --image Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:latest \
    --assign-identity \
    --size Standard_DS1_v2 \
    -l westus2
    --generate-ssh-keys
```
to create a VM with system assigned identity.
2. Create a user identity for the second VM:
```bash
az identity create \
    -n $MANAGED_IDENTITY_NAME \
    -g $RESOURCE_GROUP \
    -l westus2
```
Get the identity resource id
```
identityResourceId=`az identity show -g $RESOURCE_GROUP -n $MANAGED_IDENTITY_NAME -o json --query "id" | tr -d '"'`
```
and then create a VM with this identity assigned:
```
az vm create \
    -n $VM_NAME_USER_ASSIGNED \
    -g $RESOURCE_GROUP \
    --image Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:latest \
    --assign-identity $identityResourceId \
    --size Standard_DS1_v2 \
    -l westus2
    --generate-ssh-keys
```
3. Create a Key Vault:
```
az keyvault create  -n $KEY_VAULT_NAME -g $RESOURCE_GROUP
```
Get the principal ID for the VM with system assigned identity:
```
principalId=`az vm show -n $VM_NAME_SYSTEM_ASSIGNED -g $RESOURCE_GROUP -o json --query identity.principalId | tr -d '"'`
```
Allow the VM with system assigned identity to access the key vault secrets:
```
az keyvault set-policy -n $KEY_VAULT_NAME --object-id $principalId --secret-permissions get list
```
Get the principal ID for the VM with user assigned identity:
```
principalId=`az vm show -n $VM_NAME_USER_ASSIGNED -g $RESOURCE_GROUP -o json --query "identity.userAssignedIdentities.*.principalId | [0]" | tr -d '"'`
```
Allow the VM with user assigned identity to access the key vault secrets:
```
az keyvault set-policy -n $KEY_VAULT_NAME --object-id $principalId --secret-permissions get list
```
Add a secret called "secret":
```
az keyvault secret set --vault-name $KEY_VAULT_NAME -n secret --value "Secret value"
```

## Install Java & Maven on VMs
4. Install Java 8 & Maven 3.x:
Run on both VMs:
```bash
echo -e `az vm run-command invoke \
    --ids /subscriptions/{subscription}/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Compute/virtualMachines/{vm} \
    --command-id RunShellScript \
    --scripts "sudo apt-get update && sudo apt-get install openjdk-8-jdk -y && sudo apt-get install maven -y" \
    -o json \
    --query "value[0].message"`
```

# Run tests
5. Clone azure-sdk-for-java repo
Run on both VMs:
```bash
echo -e `az vm run-command invoke \
    --ids /subscriptions/{subscription}/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Compute/virtualMachines/{vm} \
    --command-id RunShellScript \
    --scripts "cd /tmp && git clone https://github.com/Azure/azure-sdk-for-java.git --depth 1" \
    -o json \
    --query "value[0].message"`
```
6.  Build the dependencies:

```bash
 echo -e `az vm run-command invoke \
    --ids /subscriptions/{subscription}/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Compute/virtualMachines/{vm} \
    --command-id RunShellScript \
    --scripts "cd /tmp/azure-sdk-for-java && export AZURE_VAULT_URL=https://$KEY_VAULT_NAME.vault.azure.net && mvn install -pl sdk/identity/azure-identity,sdk/core/azure-core,sdk/core/azure-core-http-netty,sdk/keyvault/azure-security-keyvault-keys,sdk/keyvault/azure-security-keyvault-secrets,sdk/keyvault/azure-security-keyvault-certificates,sdk/core/azure-core-test -T 1 -f pom.xml -Dgpg.skip -Dmaven.javadoc.skip -Drevapi.skip -DskipSpringITs -DskipTests -Dspotbugs.skip -Djacoco.skip -am -DfailIfNoTests=false" \                                                                                                                   -o json \
    --query "value[0].message"`
```
7. Run the MSI test:
On the VM with system assigned identity:
```bash
echo -e `az vm run-command invoke \
    --ids /subscriptions/{subscription}/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Compute/virtualMachines/{vm} \
    --command-id RunShellScript \
    --scripts "cd /tmp/azure-sdk-for-java && export AZURE_VAULT_URL=https://$KEY_VAULT_NAME.vault.azure.net && mvn test -Dtest=ManagedIdentityCredentialLiveTest#testIMDSEndpointWithSystemAssigned* -pl sdk/e2e -f pom.client.xml -Dgpg.skip -am -DfailIfNoTests=false" \
    -o json \
    --query "value[0].message"`
```
On the VM with user assigned identity:
```bash
echo -e `az vm run-command invoke \
    --ids /subscriptions/{subscription}/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Compute/virtualMachines/{vm} \
    --command-id RunShellScript \
    --scripts "cd /tmp/azure-sdk-for-java && export AZURE_VAULT_URL=https://$KEY_VAULT_NAME.vault.azure.net && export AZURE_CLIENT_ID=$clientId && mvn test -Dtest=ManagedIdentityCredentialLiveTest#testIMDSEndpointWithUserAssigned* -pl sdk/e2e -f pom.client.xml -Dgpg.skip -am -DfailIfNoTests=false" \
    -o json \
    --query "value[0].message"`
```
To find the identity's client id
```
clientId=`az vm show -n $VM_NAME_USER_ASSIGNED -g $RESOURCE_GROUP -o json --query "identity.userAssignedIdentities.*.clientId | [0]" | tr -d '"'`
```
Boths result should be printed showing
```
[INFO] -------------------------------------------------------
[INFO] T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.azure.e2e.identity.ManagedIdentityCredentialLiveTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.911 s - in com.azure.e2e.identity.ManagedIdentityCredentialLiveTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by kurtzeborn** [comment]
@jianghaolu, it looks like you've got most of this figured out, what assistance do you need from the engineering system team?

**Comment by catalinaperalta** [comment]
For Golang VM testing the set up is the same up to step 3. The steps for installing Go on the VM and then running the tests are as follows:

## Install Golang on each VM
4. ``echo (az vm run-command invoke --ids /subscriptions/{subscription}/resourceGroups/{resource group}/providers/Microsoft.Compute/virtualMachines/{vm name} --command-id RunShellScript --scripts "sudo add-apt-repository ppa:longsleep/golang-backports && sudo apt-get update -y && sudo apt-get install golang-go -y" --o json --query "value[0].message")``

## Clone Go SDK repo
5. ``echo (az vm run-command invoke --ids /subscriptions/{subscription}/resourceGroups/{resource group}/providers/Microsoft.Compute/virtualMachines/{VM name} --command-id RunShellScript --scripts "mkdir tmp && cd /tmp && git clone -b track2_cloudshell https://github.com/Azure/azure-sdk-for-go.git" -o json --query "value[0].message")``

## Run tests
6. ``echo (az vm run-command invoke --ids /subscriptions/{subscription}/resourceGroups/{resource group}/providers/Microsoft.Compute/virtualMachines/{VM name} --command-id RunShellScript --scripts "cd /tmp/azure-sdk-for-go/sdk/azidentity && export AZURE_VAULT_URL=https://kvcpname0.vault.azure.net && go test -run TestManagedIdentityCredential_GetTokenInVMLive" -o json --query "value[0].message")``

## Expected result (it should say PASS in the message)
``"Enable succeeded: \n[stdout]\nPASS\nok  \tgithub.com/Azure/azure-sdk-for-go/sdk/azidentity\t0.435s\n\n[stderr]\n"``



### **Please Note**
If step 6 returns an error saying that GoCache variable or HOME variables aren't set, then assign the path of the user's home directory as follows: 
``export HOME=/path/to/home/directory ``

**Comment by chlowell** [comment]
# Python

# prerequisite tools
- Azure CLI

# Azure resources
This test requires instances of these Azure resources:
- Azure Key Vault
- Azure Managed Identity
  - with secrets/set and secrets/delete permission for the Key Vault
- Azure Virtual Machine with system-assigned identity
- Azure Virtual Machine with user-assigned identity
  - don't use the same VM twice

The rest of this section is a walkthrough of deploying these resources.

## Set environment variables to simplify copy-pasting
- RESOURCE_GROUP
  - name of an Azure resource group
  - must be unique in the Azure subscription
  - e.g. 'identity-test-rg'
- VM_NAME_SYSTEM_ASSIGNED
  - name of an Azure Virtual machine with a system-assigned identity
  - must be unique in the resource group
  - e.g. 'identity-test-vm-system'
- VM_NAME_USER_ASSIGNED
  - name of an Azure Virtual machine with a user-assigned identity
  - must be unique in the resource group
  - e.g. 'identity-test-vm-user'
- MANAGED_IDENTITY_NAME
  - name of the user-assigned identity
  - 3-128 alphanumeric characters
  - must be unique in the resource group
- KEY_VAULT_NAME
  - 3-24 alphanumeric characters
  - must begin with a letter
  - must be globally unique

## resource group
```sh
az group create -n $RESOURCE_GROUP --location westus2
```

## Managed identity
Create the identity:
```sh
az identity create \
    -n $MANAGED_IDENTITY_NAME \
    -g $RESOURCE_GROUP \
    -l westus2
```

## Virtual machines
With system-assigned identity:
```sh
az vm create \
    -n $VM_NAME_SYSTEM_ASSIGNED \
    -g $RESOURCE_GROUP \
    --image UbuntuLTS \
    --assign-identity \
    --size Standard_DS1_v2 \
    -l westus2 \
    --generate-ssh-keys
```

With user-assigned identity:
```sh
az vm create \
    -n $VM_NAME_USER_ASSIGNED \
    -g $RESOURCE_GROUP \
    --image UbuntuLTS \
    --assign-identity $(az identity show -g $RESOURCE_GROUP -n $MANAGED_IDENTITY_NAME -o tsv --query id) \
    --size Standard_DS1_v2 \
    -l westus2 \
    --generate-ssh-keys
```

## Key Vault:
```sh
az keyvault create -g $RESOURCE_GROUP -n $KEY_VAULT_NAME --sku standard
```

Allow the VM with system-assigned identity to access the Key Vault's secrets:
```sh
az keyvault set-policy -n $KEY_VAULT_NAME \
    --object-id $(az vm show -n $VM_NAME_SYSTEM_ASSIGNED -g $RESOURCE_GROUP --query identity.principalId -o tsv) \
    --secret-permissions set delete
```

Do the same for the user-assigned identity:
```sh
az keyvault set-policy -n $KEY_VAULT_NAME \
    --object-id $(az identity show -g $RESOURCE_GROUP -n $MANAGED_IDENTITY_NAME --query principalId -o tsv) \
    --secret-permissions set delete
```

# Install dependencies

## gather VM ids
```sh
export VM_ID_SYSTEM_ASSIGNED=$(az vm show -g $RESOURCE_GROUP -n $VM_NAME_SYSTEM_ASSIGNED -o tsv --query id) \
       VM_ID_USER_ASSIGNED=$(az vm show -g $RESOURCE_GROUP -n $VM_NAME_USER_ASSIGNED -o tsv --query id) && \
export VM_IDS="$VM_ID_SYSTEM_ASSIGNED $VM_ID_USER_ASSIGNED"
```

## install prerequisites
```sh
echo -e `az vm run-command invoke \
    --ids $VM_IDS \
    --command-id RunShellScript \
    --scripts "sudo apt update && sudo apt install python-pip python3-pip -y --no-install-recommends && \
               git clone https://github.com/Azure/azure-sdk-for-python.git --depth 1 --single-branch --branch master /sdk && \
               cd /sdk/sdk/identity/azure-identity/tests/managed-identity-live && \
               pip install setuptools wheel && pip3 install setuptools wheel && \
               pip install -r requirements.txt && pip3 install -r requirements.txt"`
```

# Run tests
Do this for each VM, that is to say, once passing `--ids $VM_ID_SYSTEM_ASSIGNED` and again
passing `--ids $VM_ID_USER_ASSIGNED`:

## Python 2
```sh
echo -e `az vm run-command invoke \
    --ids $VM_ID_SYSTEM_ASSIGNED \
    --command-id RunShellScript \
    --scripts "cd /sdk/sdk/identity/azure-identity/tests/managed-identity-live && \
               export AZURE_IDENTITY_TEST_VAULT_URL=https://$KEY_VAULT_NAME.vault.azure.net && \
               python2 -m pytest -v --log-level=DEBUG"`
```

## Python 3
```sh
echo -e `az vm run-command invoke \
    --ids $VM_ID_SYSTEM_ASSIGNED \
    --command-id RunShellScript \
    --scripts "cd /sdk/sdk/identity/azure-identity/tests/managed-identity-live && \
               export AZURE_IDENTITY_TEST_VAULT_URL=https://$KEY_VAULT_NAME.vault.azure.net && \
               python3 -m pytest -v --log-level=DEBUG"`
```

Successful test output looks like this:
```
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-5.3.2, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /azure-sdk-for-python, inifile: setup.cfg
plugins: asyncio-0.10.0
collecting ... collected 2 items

test_managed_identity_live.py::test_managed_identity_live PASSED
test_managed_identity_live_async.py::test_managed_identity_live PASSED

============================== 2 passed in 0.61s ===============================
```
`test_managed_identity_live` must pass. Other tests may be skipped. No test may fail.

# Delete Azure resources
```sh
az group delete -n $RESOURCE_GROUP -y --no-wait
```

**Comment by XuGuang-Yao** [comment]
Hi All,
I am following above steps to do E2E test. My suggestion as below. Please correct me if I miss anything.

@chlowell 
1.Since the [test ](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/tests/managed-identity-live/test_managed_identity_live.py)needs to delete secret after setting. 

    client = SecretClient(live_managed_identity_config["vault_url"], credential, logging_enable=True)
    secret = client.set_secret("managed-identity-test-secret", "value")
    **client.begin_delete_secret(secret.name)**

So we need to create a non-soft-delete KV for this test.  

`az keyvault create -g $env:RESOURCE_GROUP -n $env:KEY_VAULT_NAME  --sku standard --enable-soft-delete false`
If not, the test command will fail with below error. 

![image](https://user-images.githubusercontent.com/53599438/79421362-3ae0a900-7fed-11ea-985c-cd8e7fc70b60.png)

@jianghaolu 
2.For creating vm command, we need specify the admin name using below command or error will occur.

`az vm create -n $env:VM_NAME_SYSTEM_ASSIGNED -g $env:RESOURCE_GROUP  --image UbuntuLTS --assign-identity  --size Standard_DS1_v2  -l westus2 --generate-ssh-keys --admin-username $env:VM_ADMIN_USER_NAME`

**Comment by XuGuang-Yao** [comment]
Hi @jianghaolu,

I am following above steps to do Java E2E test. My suggestion as below. Please correct me if I miss anything.

1.In step of creating vm command, we need specify the admin name using below command or error will occur.

`az vm create -n $VM_NAME_SYSTEM_ASSIGNED -g $RESOURCE_GROUP  --image UbuntuLTS --assign-identity  --size Standard_DS1_v2  -l westus2 --generate-ssh-keys --admin-username $VM_ADMIN_USER_NAME`

`az vm create  -n $VM_NAME_USER_ASSIGNED    -g $RESOURCE_GROUP --image UbuntuLTS  --assign-identity $identityResourceId  --size Standard_DS1_v2   -l westus2   --generate-ssh-keys --admin-username $VM_ADMIN_USER_NAME`

**Comment by jianghaolu** [comment]
@XuGuang-Yao Which version of Azure CLI are you using? I'm using 2.0.78 on Mac and the username is automatically using my local user account's name. When I run `az vm create -h` there's a section:
```
...
Authentication Arguments
    --admin-password               : Password for the VM if authentication type is 'Password'.
    --admin-username               : Username for the VM.  Default: jianghlu.
...
```

**Comment by XuGuang-Yao** [comment]
@jianghaolu ，Thanks for your quick reply. I am using 2.2.0 on windows. There is something wrong with  my default account name, my fault. 
Since we talk about environment. Which OS should I use to run these tests? May I continue with windows if we don't have specific one?

**Comment by XuGuang-Yao** [comment]
@jianghaolu, I tried to repeat the test steps today and found the last command doesn't work as expected. 
Error as below picture. 
![image](https://user-images.githubusercontent.com/53599438/79844170-e6bf3580-83ed-11ea-866c-02e7b236398e.png)

In the lastest verison of [repo](https://github.com/Azure/azure-sdk-for-java.git). I can't find the pom.client.xml any more. I noticed this [file ](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/parents/azure-client-sdk-parent/pom.xml) highly like the removed pom.client.xml. I tried to use it instead of the pom.client.xml, but it doesn't work either. 

Could you please help to do a further investigation and correct the command?

**Comment by jianghaolu** [comment]
Ahh yes - they changed the pom file structure in the repo. Breaking a lot of people apparently. Let me fix the instructions.

**Comment by jonathandturner** [comment]
For JavaScript:

# prerequisite tools
- Azure CLI

# Azure resources
This test requires instances of these Azure resources:
- Azure Key Vault
- Azure Managed Identity
  - with secrets/set and secrets/delete permission for the Key Vault
- Azure Virtual Machine with system-assigned identity
- Azure Virtual Machine with user-assigned identity
  - don't use the same VM twice

The rest of this section is a walkthrough of deploying these resources.

## Set environment variables to simplify copy-pasting
- RESOURCE_GROUP
  - name of an Azure resource group
  - must be unique in the Azure subscription
  - e.g. 'identity-test-rg'
- VM_NAME_SYSTEM_ASSIGNED
  - name of an Azure Virtual machine with a system-assigned identity
  - must be unique in the resource group
  - e.g. 'identity-test-vm-system'
- VM_NAME_USER_ASSIGNED
  - name of an Azure Virtual machine with a user-assigned identity
  - must be unique in the resource group
  - e.g. 'identity-test-vm-user'
- MANAGED_IDENTITY_NAME
  - name of the user-assigned identity
  - 3-128 alphanumeric characters
  - must be unique in the resource group
- KEY_VAULT_NAME
  - 3-24 alphanumeric characters
  - must begin with a letter
  - must be globally unique

## Run inside of PowerShell

These instructions assume you're running inside of PowerShell.

## resource group
```sh
az group create -n $RESOURCE_GROUP --location westus2
```

## Managed identity
Create the identity:
```sh
az identity create -n $MANAGED_IDENTITY_NAME -g $RESOURCE_GROUP -l westus2
```

## Virtual machines
With system-assigned identity:
```sh
az vm create -n $VM_NAME_SYSTEM_ASSIGNED -g $RESOURCE_GROUP --image UbuntuLTS --assign-identity --size Standard_DS1_v2 -l westus2 --generate-ssh-keys
```

With user-assigned identity:
```sh
az vm create -n $VM_NAME_USER_ASSIGNED -g $RESOURCE_GROUP --image UbuntuLTS --assign-identity $(az identity show -g $RESOURCE_GROUP -n $MANAGED_IDENTITY_NAME -o tsv --query id) --size Standard_DS1_v2 -l westus2 --generate-ssh-keys
```

## Key Vault:
```sh
az keyvault create -g $RESOURCE_GROUP -n $KEY_VAULT_NAME --sku standard
```

Allow the VM with system-assigned identity to access the Key Vault's secrets:
```sh
az keyvault set-policy -n $KEY_VAULT_NAME --object-id $(az vm show -n $VM_NAME_SYSTEM_ASSIGNED -g $RESOURCE_GROUP --query identity.principalId -o tsv) --secret-permissions set delete
```

Do the same for the user-assigned identity:
```sh
az keyvault set-policy -n $KEY_VAULT_NAME --object-id $(az identity show -g $RESOURCE_GROUP -n $MANAGED_IDENTITY_NAME --query principalId -o tsv) --secret-permissions set delete
```

# Install dependencies

## get user-assigned client id
```sh
$VM_ID_USER_ASSIGNED = az vm show -g $RESOURCE_GROUP -n $VM_NAME_USER_ASSIGNED -o tsv --query "identity.userAssignedIdentities.*.{clientId: clientId}"
```

### Build the webapp

```
cd azure-sdk-for-js\sdk\identity\identity\test\manual-integration\AzureVM
```

Install the requirements:
```
npm install
```

Build the job:
```
tsc -p .
```


## Build and run the tests
```sh
 az vm run-command invoke -g $RESOURCE_GROUP -n $VM_NAME_USER_ASSIGNED --command-id RunShellScript --parameters "KEY_VAULT_NAME=$($KEY_VAULT_NAME) VM_ID_USER_ASSIGNED=$($VM_ID_USER_ASSIGNED)"--scripts '"sudo apt update && (yes | sudo apt install npm) && npm install -g typescript && git clone https://github.com/azure/azure-sdk-for-js --single-branch --branch master --depth 1 && cd azure-sdk-for-js/sdk/identity/identity/test/manual-integration/AzureVM && npm install && tsc -p ."'
```

```sh
az vm run-command invoke -g $RESOURCE_GROUP -n $VM_NAME_SYSTEM_ASSIGNED --command-id RunShellScript --parameters "KEY_VAULT_NAME=$($KEY_VAULT_NAME)" --scripts '"sudo apt update && (yes | sudo apt install npm) && sudo npm install -g typescript && git clone https://github.com/azure/azure-sdk-for-js --single-branch --branch master --depth 1 && cd azure-sdk-for-js/sdk/identity/identity/test/manual-integration/AzureVM && npm install && tsc -p . && node index"'
 ```

Note, if you see a message like "Could not get lock /var/lib/apt/lists/lock - open", you may need to re-run the command.

# Verify success

```
az keyvault secret show -n "secret-name-system" --vault-name "$($KEY_VAULT_NAME)"
```

```
az keyvault secret show -n "secret-name-user" --vault-name "$($KEY_VAULT_NAME)"
```

# Delete Azure resources
```sh
az group delete -n $RESOURCE_GROUP -y --no-wait
```

**Comment by XuGuang-Yao** [comment]
Hi @jonathandturner,

I am following above steps to do JS E2E test. My suggestion as below. Please correct me if I miss anything.

Same [keytar issue](https://github.com/atom/node-keytar#on-linux) here.

![image](https://user-images.githubusercontent.com/53599438/80327779-cb31b000-886f-11ea-8e1a-7596f57e0279.png)

I tried to add` (yes | sudo apt-get install libsecret-1-dev)` before `npm install ` as the following command, and the test passed.

`az vm run-command invoke -g $RESOURCE_GROUP -n $VM_NAME_USER_ASSIGNED --command-id RunShellScript --parameters "KEY_VAULT_NAME=$($KEY_VAULT_NAME) VM_ID_USER_ASSIGNED=$($VM_ID_USER_ASSIGNED)"--scripts "sudo apt update && (yes | sudo apt install npm) && npm install -g typescript && git clone https://github.com/azure/azure-sdk-for-js --single-branch --branch master --depth 1 && cd azure-sdk-for-js/sdk/identity/identity/test/manual-integration/AzureVM &&  (yes | sudo apt-get install libsecret-1-dev) && npm install && tsc -p . && node index_user"`

I also tried to update the command in other tests (such as Cloud Shell and Pod),but they failed with below error.

> sudo: The term 'sudo' is not recognized as the name of a cmdlet, function, script file, or operable program.

**Comment by jonathandturner** [comment]
@XuGuang-Yao - can you describe these to help us understand what is happening?

* The version of Windows you're running
* The terminal you're using (WSL, PowerShell, CMD, etc)

You shouldn't need to use commands like `sudo` if you're running in Windows. Keytar should be able to detect you're in Windows and switch to that mode.

**Comment by XuGuang-Yao** [comment]
@jonathandturner - I am using PowerShell on windows 10 to test. Since this test needs create a linux VM, so I think the `sudo `is necessary.

**Comment by jonathandturner** [comment]
@XuGuang-Yao - the steps above invoke the VM from Windows rather than ssh'ing into the VM.  Were there steps above that needed you to log into the VM and run commands directly?  I may need to rewrite some of the instructions to be more clear.

**Comment by XuGuang-Yao** [comment]
@jonathandturner - Let forget the `'sudo' is not recognized` error. We should focus on how to install libsecret for other tests(such as [CloudShell ](https://github.com/Azure/azure-sdk/issues/795#issuecomment-618059659)and [Pod](https://github.com/Azure/azure-sdk/issues/814#issuecomment-618058741)) so that we can reslove the keytar issue. Once this done, the error is no longer a problem.

BTW, I do use `invoke `to run command in my OS(windows 10) rather than login into VM, just as your instructions above.

**Comment by jonathandturner** [comment]
@XuGuang-Yao - we may need to add a step where you log into the VM and run:

```
sudo apt install libsecret-1-0
```

And then do the build steps from the VM.  I was able to run the above, `sudo npm install -g typescript`, `npm install`, and `tsc -p .` and have a runnable example.

**Comment by XuGuang-Yao** [comment]
@jonathandturner -Thanks for your updating. `sudo apt install libsecret-1-0` works in this VM test. I tried to run it in other tests([CloudShell](https://github.com/Azure/azure-sdk/issues/795#issuecomment-618059659) and [Pod](https://github.com/Azure/azure-sdk/issues/814#issuecomment-618058741)), but it doesn't work. The `sudo`   can't be recognized in Dockerfile or cloudshell. 

BTW, I do run Pod test against Docker lunix container environment.

**Comment by XuGuang-Yao** [comment]
@jianghaolu 
Hi, I am following java instrucation to do E2E test against May release. I noticed you haven't update the run test command to `pom.xml`. Anyway, I tried to change it to `pom.xml` during the test. But below error occured. 

> ![image](https://user-images.githubusercontent.com/53599438/81882476-6abba600-95c5-11ea-9ee4-0d5e8d0a9c64.png)

Did I use the wrong pom file? Could you please take a look and correct the test steps?

**Comment by XuGuang-Yao** [comment]
@jonathandturner - Hope you are doing well. The `sudo apt install libsecret-1-0` does solve the problem in VM test. It would be better that we can add `sudo apt install libsecret-1-0` to the JS test instruction above. Could you please do that?

**Comment by XuGuang-Yao** [comment]
@jianghaolu - Hi, I noticed that the instructions are still using the pom.client.xml file. Could you please find time to solve it? Thanks in advance.

**Comment by v-jiaodi** [comment]
Hi @catalinaperalta, @chlowell  follow the above steps to test for go. When we reached step 6:
```
echo (az vm run-command invoke --ids /subscriptions/{subscription}/resourceGroups/{resource group}/providers/Microsoft.Compute/virtualMachines/{VM name} --command-id RunShellScript --scripts "cd /tmp/azure-sdk-for-go/sdk/azidentity && export AZURE_VAULT_URL=https://kvcpname0.vault.azure.net && go test -run TestManagedIdentityCredential_GetTokenInVMLive" -o json --query "value[0].message")
```
Add command `go get github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.3.0-beta.5.0.20230425151240-402376456ba8` to install **identity version** `v1.3.0-beta.5.0.20230425151240-402376456ba8` before command `go test -run TestManagedIdentityCredential_GetTokenInVMLive `. get error as follow:

![image](https://user-images.githubusercontent.com/80496810/237041056-59b70109-cbb4-481d-b44f-e419187fa79e.png)

Through investigation, after clone the code, switch to `azure-sdk-for-go/sdk/samples/azidentity/manual-tests/managed-identity/general` and run `go run main.go`. It works normally. For more details, please refer to [Azure Arc testing](https://github.com/Azure/azure-sdk/issues/1908#issuecomment-1060972307).

For Azure VM MSI testing for go, can we refer to  [Azure Arc testing](https://github.com/Azure/azure-sdk/issues/1908#issuecomment-1060972307) to update testing instructions?

**Comment by v-xuto** [comment]
@joshfree This issue has been closed. Do we need to continue testing this `Automate VM MSI testing`?
