### ISSUE TITLE
Board Review: Small API Change to App Configuration SettingSelector API

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk#842]
## The Basics

* Service team responsible for the client library:  Azure SDK AppConfiguration Feature Team
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/azure-app-configuration/overview
* Contact email (if service team, provide PM and Dev Lead):  annelo-msft

## About this client library

* Name of the client library:  Azure.Data.AppConfiguration version 1.0.0-preview.5
* Languages for this review: .NET, Java, Python, JS
* Link to the service REST APIs: https://github.com/Azure/AppConfiguration#rest-api-reference

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.azurewebsites.net/Assemblies/Review/62a221f8b9204e089862d86557637dab?diffRevisionId=5aae541729db431c83c7e0b076f831e2

* Link to samples for champion scenarios:
@AlexanderSher 

### Java
* [PR](https://github.com/Azure/azure-sdk-for-java/pull/6693)
* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link:
https://apiview.azurewebsites.net/Assemblies/Review/2209f75a19ca4076a31b2c7cbdbbca98?diffRevisionId=c01be5d6644140dd8489579a8f551bf7
* Link to samples for champion scenarios:
@mssfang 

### Python

[PR](https://github.com/Azure/azure-sdk-for-python/pull/9066)

### TypeScript
  
* [PR](https://github.com/Azure/azure-sdk-for-js/pull/6417) (has been merged into master)
* [API Extractor](https://github.com/Azure/azure-sdk-for-js/pull/6417/commits/26d46ed7f3961db17c401d5316c47301daabed9e#diff-c688d486eab90cecce43d37f23ddf04d)
* [Link to samples for champion scenarios](https://github.com/Azure/azure-sdk-for-js/pull/6417/commits/26d46ed7f3961db17c401d5316c47301daabed9e#diff-692d04c22b2d53080c96bbebecd071af)
@richardpark-msft 

## Champion Scenarios
n/a

## Agenda for the review
Expect to handle without in-person meeting, unless an architect requests a meeting.

@AlexGhiondea, @KrzysztofCwalina

**Comment by annelo-msft** [comment]
@jimmyca15 , @zhenlan as FYI.

**Comment by KrzysztofCwalina** [comment]
The diff in the .NET API listing looks good to me.

**Comment by JonathanGiles** [comment]
I don't believe the Java listing has been updated yet. @mssfang Will you be providing the updated API so that it may be reviewed?

**Comment by mssfang** [comment]
@JonathanGiles  yes. It is updated now

**Comment by richardpark-msft** [comment]
I talked with @bterlson and we're approved on the TS side. You can see his comments in the PR linked above.

**Comment by mssfang** [comment]
Added the PR for the Java side as well.

**Comment by xiangyan99** [comment]
I talked with @johanste and the change is good to Python.

**Comment by annelo-msft** [comment]
@JonathanGiles it looks like Java is the last remaining language to be approved - would you be able to have a look?

**Comment by JonathanGiles** [comment]
The diff in the Java API listing looks good to me.

**Comment by annelo-msft** [comment]
We are good to go - API is approved!  Thanks, all!!
