### ISSUE TITLE
Register CName for Blob-Hosted Documentation

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#848]
@heaths made a suggestion back in October that we should do this for all the individual package docs linked to from our various language-specific github.io pages.

[Reference Documentation](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-custom-domain-name)

**Comment by scbedd** [comment]
My absolute best-case scenario is we replace the entire `https://azuresdkdocs.blob.core.windows.net/$web` part of the URL, but all the examples in the reference only allow us to replace the domain name only.

Continuing to dig.

**Comment by scbedd** [comment]
After reading through the documentation a bit more, it appears that I can directly access content below the `$web` container through standard http requests. Will test this theory with `azuresdkdocsdev`

**Comment by kurtzeborn** [comment]
It's been three years since we had this idea.  Nobody has screamed.  GitHub.io docs have dropped in priorty (mainly because they just work and don't need constant attention).  If someone complains about this, we can address it then.  For now, what we have works and requires nearly zero maintenance.
