### ISSUE TITLE
Google 'azure storage sdk', the top results all point to track 1 SDKs

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk#857]
Some suggestions
1. Have clear announcements in track 1 SDK pages (github repo, readthedocs.io sites, etc.) and point users to track 2 SDKs.
2. Can we do something to change google search results? e.g. if SEO work helps?

**Comment by kaerm** [comment]
We were just discussing that earlier today. @tamram and @rishabpoh are supposed to sync later to discuss what are the options here and share the knowledge.

**Comment by tamram** [comment]
@twooley - FYI. The repositories for the legacy client librarys (pre-v12) are often showing up in search before the v12 repos or docs.ms content. 

While this is not something we can solve directly, we can update our references to the repos in the docs and TOC to diminish the SEO power of the older repos.

Any other ideas are welcome.

**Comment by xiangyan99** [comment]
Update: seems like it works correctly now. When I searched "azure storage sdk", the first page showed all track 2 libraries.

Close.
