### ISSUE TITLE
Enable Component Governance for each build

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk#86]
We need to enable the Component Governance task for each of our build pipelines. See https://docs.opensource.microsoft.com/tools/cg.html for more information.

- [ ]  azure-sdk-for-java
- [ ]  azure-sdk-for-net
- [ ]  azure-sdk-for-js
- [ ]  azure-sdk-for-python

**Comment by kurtzeborn** [comment]
This is a duplicate to: https://github.com/Azure/azure-sdk/issues/40
