### ISSUE TITLE
Stand up engineering system for mobile SDK libraries (Android and iOS)

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#861]
Beyond just creating the repos (azure-sdk-for-android and azure-sdk-for-ios) we'll need to work with the mobile libraries team stand up pipelines and release process for the mobile libraries we want to produce.

**Comment by tjprescott** [comment]
@bsiegel is there a way to include this issue on our ZenHub boards? Otherwise we could create tracking issues and link them to this.

**Comment by bsiegel** [comment]
> @bsiegel Brandon Siegel FTE is there a way to include this issue on our ZenHub boards? Otherwise we could create tracking issues and link them to this.

In theory we could add this repo but then we would end up with lots of unrelated issues. Since this is an epic, the easiest way will probably be to track implementation with issues in the iOS repo and link them to this epic, but unfortunately the epic won't appear on the board.

**Comment by kurtzeborn** [comment]
Closing this uber epic since we're doing a good job tracking iOS and Android separately.  They will also be completed separately as well, so it doesn't make sense to track them as a group.
