### ISSUE TITLE
Board Review: Go Guidelines Review

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-sdk#862]
## The Basics

Review the Draft guidelines  for GoLang (https://azure.github.io/azure-sdk/golang_introduction.html)

## About this client library

None.

## Artifacts required (per language)

https://azure.github.io/azure-sdk/golang_introduction.html

**Comment by adrianhall** [comment]
Ack on the request.  I think we should chat this week to discuss what is needed.  I'll set something up.

**Comment by adrianhall** [comment]
Scheduled for 9-JAN-2020
