### ISSUE TITLE
Ensure provisioning/deprovisioning scripts are up to date in all language repos

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk#890]

**Comment by heaths** [comment]
We might close this in lieu of Azure/azure-sdk-tools#358.

**Comment by kurtzeborn** [comment]
@chidozieononiwu, @danieljurek says the work is mostly done for this.  The scripts are already moved to the eng folder and mirrored into each language repo.  The only work left is to update the archetype-sdk-tests.yml files (and archetype-sdk-integration.yml for JS)  to point to the scripts located in eng/common/TestResources.  The other thing to include in this is to update the contributing.md files to explain how to provision live test resources.

@chidozieononiwu, please help with this.

**Comment by heaths** [comment]
Please be sure to delete the files directly in eng/ as well.
