### ISSUE TITLE
Need move the azure-uamqp-python build pipeline into the azure-sdk org on DevOps

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#91]
Here is the pipeline that needs to be moved: https://dev.azure.com/uamqp/uamqp-python-private/_build?definitionId=1

It might make sense to have a separate pipeline from the rest of the python for multiple reasons:
- Artifacts are not published publicly
- The repo is separate from azure-sdk-for-python (though we should talk to Anna/Laurant about why that is)

**Comment by bsiegel** [comment]
@annatisch Do you have an idea of when we can merge the branch into master that contains the pipeline definitions?

**Comment by annatisch** [comment]
@bsiegel - sorry I kinda dropped this. I will want to merge soon - but need to do some more work to get Windows for 2.7 working in some capacity....
Otherwise I could leave that for now and just build that one wheel manually....
Either way I will try to revisit this ASAP.
