### ISSUE TITLE
Change Request: Adding guidelines for service specific authentication protocols

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk#947]
Currently the Azure SDK general guidelines simply state that services which provide custom authentication protocols should provide a mechanism to support them. However, they don't provide any guidance on how they should be supported. This guidance is needed so we have consistency across services with respect to additional authentication mechanisms. Below are proposed general guidelines to address this. Once these are added language specific guidelines would also need to be added.

## Suporting service specific authentication protocols

__MUST__ define public custom credential type(s) in the case that the service provides authentication protocols other than OAUTH token via Azure Active Directory.

__MUST__  provide a mechanism to instantiate service clients using each of the applicable credential types.

__MUST__ define custom credential types in a service specific library, not in `Azure.Core` or `Azure.Identity`.

__MUST__ prepend the custom credential type name with the service name to provide clear context to its intended scope and usage.
  
  - :white_check_mark: `StorageSharedKeyCredential`
  - :white_check_mark: `CognitiveApiKeyCredential`  
  - :x: ~~`ApiKeyCredential`~~

__MUST__ append `Credential` to the end of the custom credential type name. Note this must be singular not plural.

  - :white_check_mark: `StorageSharedKeyCredential` 
  - :x: ~~`StorageSharedKeyCredentials`~~

__MUST__ define a constructor or factory for the custom credential type which takes in ALL data needed for the custom authentication protocol.

__MUST__ define a single method which takes in all mutable credential data needed to the custom authentication protocol, and updates the credential in an __atomic__, thread safe manner.

__SHOULD NOT__ define public properties or fields which allow users to access the authentication data directly. They are often unnecessary, and are difficult to use in a thread safe manner.

__MUST NOT__ define public settable properties or fields which allow users to update the authentication data directly in a non-atomic manner.

__MUST NOT__ allow mutating any credential data which would invalidate its use in previously allocated clients. For instance, if a custom credential is specific to an account or region, this data should not be mutable if clients using that credential are also specific to that account or region.

  :white_check_mark: __Correct__
  ~~~ c#
  public class CognitiveApiKeyCredential
  {
      public CognitiveApiKeyCredential(string region, string key) { ... }

      public void Refresh(string key) { ... }
  }
  ~~~

  :x: __Incorrect__
  ~~~ c#
  public class CognitiveApiKeyCredential
  {
      public string Region { get; set; }

      public string Key { get; set; }

      // or

      public void Refresh(string region, string key) { ... }
  }
  ~~~

**Comment by jongio** [comment]
Probably a more language specific comment, but do we also want to specify which base class they derive from, i.e. TokenCredential, and do we want an interface for the Refresh method.

**Comment by noelbundick** [comment]
Note: we'll want to ensure the correct spelling "`Cognative`" -> "`Cognitive`" throughout both guidelines and code

**Comment by adrianhall** [comment]
Notes from arch board:

- Last requirement needs rephrasing.  Maybe "DO ensure clients still work after updating credentials"
- Add "DO support AAD token credentials at a service level"  Note that everything else should be rare.
- Where should the per-service credential types go?  In the same namespace and package as the service (preferred) or the service group common library (less common).  Never in Core.
- SHOULD NOTE derive from Azure Core credential types.
- Add examples.

Next Steps
[] @schaabs to write guidelines in PR.
[] @johanste to research Python requirements.

**Comment by xirzec** [comment]
As a minor piece of naming feedback, I feel like "Refresh" to me implies an async server call being made (e.g. an OAuth access token being refreshed) whereas this is an atomic set. 

I don't want to bikeshed hard on this, but to me a verb like "set" or "update" makes more sense when the final authentication secret is known.

**Comment by YijunXieMS** [comment]
When multiple services, even though not all services, have the same authentication protocol, do we try to re-use the code or at least sync the design? For instance, if there are StorageSharedKeyCredential and EventHubSharedKeyCredential with the same attributes like policy/key, do we try to have a single implementation?
If code-reuse is not our intention in this case, it will be better if they have the same API (like attribute names) to users, who may use both services.

**Comment by mssfang** [comment]
After implementing it in Java. There could be another way to do a rotating subscription key. But it violates this rule
```
MUST define a single method which takes in all mutable credential data needed to the custom authentication protocol, and updates the credential in an atomic, thread safe manner.
```

Example of Java code samples:
```
public final class TextAnalyticsSubscriptionKeyCredential {
    private Supplier<String> subscriptionKeySupplier;
    public TextAnalyticsSubscriptionKeyCredential(Supplier<String> subscriptionKeySupplier) {
        this.subscriptionKeySupplier = Objects.requireNonNull(subscriptionKeySupplier, "'subscriptionKeySupplier' cannot be null");
    }
    public String getSubscriptionKey() {
        return this.subscriptionKeySupplier.get();
    }
}

// Policy that created to get the subscription key value
public final class SubscriptionKeyCredentialPolicy implements HttpPipelinePolicy {
    private static final String OCP_APIM_SUBSCRIPTION_KEY = "Ocp-Apim-Subscription-Key";
    private final TextAnalyticsSubscriptionKeyCredential credential;

    public SubscriptionKeyCredentialPolicy(TextAnalyticsSubscriptionKeyCredential credential) {
        this.credential = credential;
    }

    @Override
    public Mono<HttpResponse> process(HttpPipelineCallContext context, HttpPipelineNextPolicy next) {
        context.getHttpRequest().setHeader(OCP_APIM_SUBSCRIPTION_KEY, credential.getSubscriptionKey());
        return next.process();
    }
}
```
```
@Test
public void rotateSharedKeyCredentialSyncClient() {
        // Arrange
        final String endpoint = getEndpoint();
        final String subscriptionKey = "expiredKey";
        final String newSubscriptionKey = getSubscriptionKey();

        final TextAnalyticsSubscriptionKeyCredential credential =
            new TextAnalyticsSubscriptionKeyCredential(() -> {
                if (subscriptionKey == null || isTokenExpired()) {
                    return newSubscriptionKey;
                }
                return subscriptionKey;
            });

        final TextAnalyticsClient client = new TextAnalyticsClientBuilder()
            .subscriptionKey(credential)
            .endpoint(endpoint)
            .buildClient();

        // Action and Assert
        validateDetectedLanguages(Arrays.asList(new DetectedLanguage("English", "en", 1.0)),
            client.detectLanguage("This is a test English Text").getDetectedLanguages());
}
```

So there will be no `Refresh()\updateSubscriptionKey()` method is given to user. But giving the user a `Supplier` function that returns the subscription key that they think it is a valid subscription key.

Also, there is already a place uses the `Supplier`, I think we can apply the same mechanism.

[BearerTokenAuthenticationPolicy](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/BearerTokenAuthenticationPolicy.java)
[SimpleTokenCache](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/credential/SimpleTokenCache.java#L24)

The current design with Refresh() method, we maintained the subscription key and need to make sure updating the subscription key is atomic and thread-safe. But with Supplier, we always know the return of the Supplier is the latest key that the user wants to use. 

Just brought it up for discussion. I think with the `Supplier` idea is easier for users to maintain their source code.

**Comment by xirzec** [comment]
@schaabs I feel like `TextAnalyticsSubscriptionKeyCredential` is getting a bit too lengthy and will get us made fun of on Twitter. Any ideas as to how we might be able to shorten this while staying in the spirit of your proposal?
