### ISSUE TITLE
[Resource Provisioner] Enable Storage Analytics logging

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#950]
Storage has a feature [analytics logging](https://docs.microsoft.com/en-us/azure/storage/common/storage-analytics-logging) which logs every API call to the storage account, and it's super helpful when investigating live test failures.  I think we should add it to the resource provisioner scripts:
 
* In the setup script, enable analytics logging for any storage accounts.
* In the cleanup script, before deleting the storage account, download the logs and upload them as a DevOps artifact.

CC: @danieljurek

**Comment by danieljurek** [comment]
Once storage is using resource templates: 

If the analytics logging cannot be enabled in the ARM template you can use a "post" script that will run after the resources are stood up [docs](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/48/Create-a-new-Live-Test-pipeline?anchor=optional-pre--and-post-steps). Ideally it's a property you can enable in an ARM template and we can skip this step. 

The log extraction will probably be best placed in a `PostIntegrationSteps` in the [archetype-sdk-integration.yml](https://github.com/Azure/azure-sdk-for-js/blob/master/eng/pipelines/templates/jobs/archetype-sdk-integration.yml#L111).

**Comment by kurtzeborn** [comment]
Assigning to storage team for follow up.  Please work with @mikeharder and @danieljurek if you have an questions or need help setting this up.
