### ISSUE TITLE
Elaborate documentation request based on the SDK type

### ISSUE THREAD

**Issue by vick-git** [Azure/azure-sdk#951]
Thank you for contributing to the design guidelines for Azure SDKs.  We welcome all discussions and contributions.  Since the design guidelines affect the client libraries for all Azure services, we thoroughly discuss and vet any design guideline changes before we incorporate them into the official guidance.  This process can take some time, so your patience is appreciated.

** Before submitting, ensure you adjust the title of the issue appropriately **

## The Basics

* Which design guideline is affected?
Elaborate documentation request based on the SDK type

* Which target languages are affected?
.NET, Storage, Blob Stroage

* Describe the change:
An elaborate documentation request based on the SDK type would be really helpful considering how much tedious it could get for people developing projects on specific requirement but unable to choose the right SDK for the requirement.

**Comment by adrianhall** [comment]
Thanks for the input.  This isn't really an SDK guideline, but a request for the documentation team.  I've passed this on to the appropriate people and we will see what we can do.

**Comment by kaerm** [comment]
Hey @vick-git thanks for the feedback! I am trying to better understand what information would you need - would you mind adding some more details on what you are trying to accomplish and what information you're missing?
