### ISSUE TITLE
Board Review: AzureCliCredentials

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#958]
The Azure Identity team has AzureCliCredential implementations for each language.  @schaabs and I would like to review the AzureCliCredential plan and discuss Azure Identity Dev Credentials in general.

Pull requests:
https://github.com/Azure/azure-sdk-for-js/pull/6521
https://github.com/Azure/azure-sdk-for-net/pull/9106
https://github.com/Azure/azure-sdk-for-python/pull/9162
https://github.com/Azure/azure-sdk-for-java/pull/6842
https://github.com/Azure/azure-sdk-for-go/pull/7023

**Comment by adrianhall** [comment]
Scheduled for 1/21/2020

**Comment by kyle-patterson** [comment]
Stream is available here (MSFT INTERNAL): https://msit.microsoftstream.com/video/a71c7bdb-1c16-4e6c-8b28-3cf4a3afd0cd

Notes from the meeting:

1.	Two possibilities considered: Expose multiple types of credentials (such as Cli, Powershell, VS, VSCode…); or expose one type of credential (DevCredential) implemented by the different types
2.	Considerations in changing the order of credential selection – Should there be an opt-in flag to the new flow, or an opt-out? 
3.	There should be a security review (with respect to shelling out when getting credentials) 
4.	We should write down & investigate customer use cases for credentials, such as: having multiple credentials (or tenant accounts)

Consensus among the board is to expose a single DevCredential to encompass the AzureCliCredential, with possibility for expansion via enum later on.
