### ISSUE TITLE
Board Review: Is supporting new environmental variables in EnvironmentCredential a breaking change?

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-sdk#964]
## Overview

Across all our languages, we have a credential type, `EnvironmentCredential`, which uses environment variables to control how the credential is configured.  We've documented a list of variables in [our general guidelines](https://azure.github.io/azure-sdk/general_azurecore.html#environment-variables), however some languages do not yet support this complete list (for example, .NET today does not support `AZURE_CERTIFICATE_PATH`, Java only support `AZURE_CLIENT_ID`, `AZURE_TENANT_ID` and `AZURE_CLIENT_SECRET` (but we have a PR open to add support for more).  The language specific client libraries document on the type what environment variables are used today.

## Changes

The identity team would like to do two things, both which might be considered breaking changes:

1. Support the entire set of environment variables, across all our languages

Since we've already shipped these types with limited support on some platforms, do we consider increasing the set of environment variables we use to be a breaking change?  It is important to note that today in all of these languages, we allow the construction of an `EnvironmentCredential` even if the required environment variables are not present.  In this case, the credential will fail during the call to GetToken, with a message explaining how it is not configured correctly.  This means calls to GetToken which previously failed may now return an actual token.  This means that in cases where you had chained a bunch of credentials together (i.e. when using `DefaultAzureCredential` or when creating a chain yourself via `ChainedTokenCredential`) it's possible that you would have previously been falling back to some other credential and now you'd instead get a token (possibly for some other identity).

A concrete example here would be a customer deploys a Java into Azure.  Their code uses `DefaultAzureCredential` as the credential when used to access a service.  They've set the environment variables `AZURE_TENANT_ID` and `AZURE_CLIENT_ID and  `AZURE_CERTIFICATE_PATH`, but they are being ignored today.  However, the machine the customer has deployed to also has a System or User assigned managed identity assigned to it, which means DefaultAzureCredential is able to get credentials.  When the customer upgrades to a new version of the identity library and redeploy their application, they now get credentials associated with the environment variables they had set.  This will likely result in their application using a different principal, which may have different permissions assigned to it, which could break the app.

2. Add `AZURE_AUTH_LOCATION` as another environment variable to consider.

The Azure CLI supports writing a JSON document that has information which can be used to authenticate (the document contains the information needed to authenticate using either a client id and secret or client id and certificate).  We are planning to add an `AuthFileCredential` type which uses this file.  We'd like to add support to `EnvironmentCredential` to also use this environment variable, when set.

In some ways, this is "more breaking" than the above, because this is an environment variable we've never documented as being supported in our language agnostic guidelines.  However, in practice support of these guidelines was not uniform (so you couldn't use them as a model for language specific behavior), and I'm not sure how well publicized the general guidelines are.  Auth Files are something that the previous identity SDK supported, and `AZURE_AUTH_LOCATION` is the canonical environment variable to use for this file.

## Guidence

The identity team would like help in understanding if we would consider these breaking changes.  Personally, I think that we should be able to make these sorts of additions to `EnvironmentCredental`.  At a minimum, I think we should be able to make the changes needed to reach the overall guidance we've already published.  While I do see the possible break when paired with `DefaultAzureCredential` or another chained credential, I think customers who are in this state are very likely to have things working by happenstance.  I believe it would be incredibly confusing to understand why the SDK is "ignoring" the environment variables which are set.  I also we believe that we should not try to make these additions "opt-in" via flags to `EnvironmentCredetial` where it by default uses the released behavior but you can ask it to consider additional variables.

However, I do believe that adding this support is worthy of a minor number bump instead of a simple patch revision.  I also think we should have crisp guidance in the chagelog and release notes about the possible impact here.

**Comment by adrianhall** [comment]
From Arch Board:

Issue-1: 
* Supporting new environment variables is not specifically breaking.   It depends. 
* Supporting the certificate path as part of the environment credential (.NET update) is **APPROVED**

Issue-2: 
* Adding support for `AZURE_AUTH_LOCATION`: **Not Approved Yet**
* It's only breaking if we handle it in the default credential flow.
* Let's go and talk to a customer who is using Track1 version and this feature.
* We can possibly offer this as a separate (unlinked) credential type.

(Remove the entire feature for issue issue-2)

* Bring back to architects once we've talked to the customer(s).
