### ISSUE TITLE
Board Review: Storage API review for STG71/Jul19

### ISSUE THREAD

**Issue by ljian3377** [Azure/azure-sdk#966]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Storage
* Link to documentation describing the service: https://docs.microsoft.com/en-us/azure/storage/
* Contact email (if service team, provide PM and Dev Lead): @ljian3377 @XiaoningLiu for JavaScript

## About this client library

* Name of the client library: @azure/storage-file-share and @azure/storage-blob
* Languages for this review: JavaScript
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/storageservices/

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

[JavaScript]
Link to [API review PR]: https://github.com/Azure/azure-sdk-for-js/pull/7068

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link:
* Link to samples for champion scenarios:

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link:
* Link to samples for champion scenarios:

### Python

* Upload the api as a Draft PR.  Link to PR:
* Link to samples for champion scenarios:

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR: https://github.com/Azure/azure-sdk-for-js/pull/7068
* Link to samples for champion scenarios:

## Champion Scenarios
N/A

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

## Thank you for your submission

CC: @kurtzeborn @vinjiang @jiacfan @ramya-rao-a @jeremymeng @HarshaNalluru

**Comment by adrianhall** [comment]
Can you please be a bit more specific about what the changes entail?  Do you have a diff available between old and new APIs?

**Comment by ljian3377** [comment]
@adrianhall 
Please refer to PR #7068 for the detail. Thanks.
