### ISSUE TITLE
Change Request: HTTP request/response timeouts for all languages

### ISSUE THREAD

**Issue by JeffreyRichter** [Azure/azure-sdk#972]
Mike Harder discussed with me an issue he's been investigating where it appears that a service occasionally (about 1 in 5000 attempts) fails to send any response to a request. He (and I believe) that this is a recurring enough issue with distributed systems that our SDKs should try to handle it more gracefully.

I believe that some of our SDKs have a per-try timeout and this is a great step in this direction but some of our SDKs may not have this feature and are therefore subject to indefinite hangs. 

We should discuss the default time for a per-try timeout as it is affected by the bandwidth (distance of the client to the service) and also affected by the amount of data being uploaded in the request and downloaded in the the response. The amount of data can vary dramatically between a simple service request and uploading/downloading a large blob (for example). So, an intelligent per-try timeout should take these things in to account.

Alternatively, we could "decorate" the sending/receiving network streams with a stream that tracks bytes-per-millisecond and, if this falls to zero for some time, the SDK cancels the I/O request and retries it. This may be the better approach as it removes the dependency on payload size and focuses more on just bandwidth.

**Comment by chradek** [comment]
Do any SDKs allow the user to configure a socket idle timeout? It seems like that should be able to detect when no response is being received after some period of time. JavaScript only has a timeout setting that controls how long it takes to finish getting a response but node.js supports socket-idle timeouts.

**Comment by kyle-patterson** [comment]
Link to recording (MSFT Internal): https://msit.microsoftstream.com/video/837dbc99-86e5-4987-b905-ae179bc56433

- Agreement that timeout should be implemented
- Ask is on engineering to test and investigate timeout situations and approaches, then return to arch board with path forward.
