### ISSUE TITLE
Change Request: Consider retrying calls for HTTP 500

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk#975]
We see occasional HTTP 500 responses with server calls during tests or logged from customers. Given the 99.999% up time, some errors are bound to happen. Should we consider retrying on HTTP 500?

Currently, at least in .NET, we only retry on 429 and 503, but if customers would commonly have to retry on 500 server failures, should we just do it in the libraries? It's worth noting that not all services may want that, but at least for Key Vault they recommended we should.

If we do retry on HTTP 500s, should we also consider implementing a circuit breaker pattern?

/cc @pakrym @mikeharder

**Comment by mikeharder** [comment]
CC @JeffreyRichter

**Comment by adrianhall** [comment]
Dupe of #972?

**Comment by mikeharder** [comment]
Not a dupe.  #972 is about timeouts.  This issue is about which HTTP status code should be retried in Core.  Currently the languages are not consistent.  For example, .NET only retries on 503, but JS retries on all 5XX with the exception of 501 and 505.

**Comment by JeffreyRichter** [comment]
We could retry on 500 but I'd probably just do 1 retry and if it fails again with 500 then I wouldn't try yet again because the 1st 500 could be an indication that anything is wrong with that particular server instance. The 2nd 500 probably means that there is something wrong with the request itself which is causing the service to go bad. Additional retries are likely to also produce 500s and possibly stress more service instances.

**Comment by JeffreyRichter** [comment]
Circuit breakers are a possibility and they've always been on my list to consider. However, there is a bit of complexity to implementing them in our SDKs and so I've been waiting for more need for them before actually taking this new feature on.

**Comment by mikeharder** [comment]
I would recommend treating 500 the same as 503, to keep things simple and consistent.  If our API fails with HTTP 500, what is the app supposed to do?  Probably wrap our API in retries, which suggests the retries should be done in the SDK itself.

**Comment by heaths** [comment]
Just to help codify the differences:

Repo | Status codes | Notes
:--- | :--- | :---
[.NET](https://github.com/Azure/azure-sdk-for-net/blob/8d5028b7b1c1da787060e4c06e1459ba52bb4af7/sdk/core/Azure.Core/src/ResponseClassifier.cs#L17-L20) | 429, 503 | Storage has additional status codes
[Java](https://github.com/Azure/azure-sdk-for-java/blob/126f19539f0d232ff1d6ce57bb1b34329f069324/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/RetryStrategy.java#L39-L46) | 408, 429, 5xx, !501, !505 | CosmosDB has some additional checks
[JS](https://github.com/Azure/azure-sdk-for-js/blob/0c6eb3fd11ac9bc5f6d9eac66583b4484d6ba781/sdk/core/core-http/lib/policies/exponentialRetryPolicy.ts#L153-L175) | 408, 429, 5xx, !501, !505 | 429 is actually in a throttlingRetryPolicy file; quite a few services like storage and CosmosDB define their own codes
[Python](https://github.com/Azure/azure-sdk-for-python/blob/dacc6a8252b3365af47e33400befd958207a93af/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L267-L287) | 408, 429, 500, 502, 503, 504 | At least CosmosDB has additional retry logic

**Comment by mikeharder** [comment]
Note that all languages except .NET are effectively the same.  `5xx, !501, !505` is effectively the same as `500, 502, 503, 504` since other `5xx` codes are rarely used.

@heaths, @pakrym: Maybe the only issue here is for .NET to align with the other languages?

**Comment by pakrym** [comment]
I'm very happy to align. I would prefer the allow list approach the python does but don't feel very strongly about it.

**Comment by pakrym** [comment]
Let me just to that, feels safe enough if everyone is doing it.

**Comment by heaths** [comment]
@pakrym fixed this for .NET by making retries work like the other 3 languages were already doing.
