### ISSUE TITLE
Update Azure Pipelines hosted images to "latest" labels

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#977]
On March 23 2020, Azure Pipelines will be removing the following hosted images:

> * Windows Server 2012R2 with Visual Studio 2015, a.k.a `vs2015-win2012r2`
> * macOS X High Sierra 10.13, a.k.a `macOS-10.13`
> * Windows Server Core 1803, a.k.a `win1803`
> 
> https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/

Many of our pipelines are currently using `macOS-10.13`, which will need to be updated.

I recommend updating our pipelines to use the `latest` labels.  This will ensure we are always using the latest images, and the labels should never need to be updated again.

* `windows-latest`
* `ubuntu-latest`
* `macOS-latest`

CC: @mitchdenny

**Comment by weshaggard** [comment]
Do we think that is a good idea to always move forward? In the past that causes issues and in particular during servicing events we might need to stay on older versions. However if they are removing older ones we might not be able to use those either. It really depends on the time window for when they retire the versions.

**Comment by mikeharder** [comment]
Here are the current images (excluding those sunsetting in March 2020):

Image | YAML VM Image Label
-- | --
Windows Server 2019 with Visual Studio 2019 | `windows-latest` OR `windows-2019`
Windows Server 2016 with Visual Studio 2017 | `vs2017-win2016`
Ubuntu 18.04 | `ubuntu-latest` OR `ubuntu-18.04`
Ubuntu 16.04 | `ubuntu-16.04`
macOS X Mojave 10.14 | `macOS-latest` OR `macOS-10.14`

> https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#use-a-microsoft-hosted-agent

The advantage to using `windows-latest` instead of `windows-2019` is we should never need to update the label again.  The downside is that we might be silently updated to say `windows-2022` when it is released, which might break builds.

I don't feel strongly either way.  Labels are not added very often, so manually updating them when required is not much work.  On the other hand, images are constantly being updated even if you specify the major version, so using the `latest` label doesn't seem to add that much risk.

**Comment by weshaggard** [comment]
I personally like to pin the version we know works for us and not automatically float to the latest as we don't want to take down our pipelines (potentially all of them) if there are issues with the newe versions. This is the same strategy we use for our tools and other things we do to ensure our builds remain reliable and then we do an update at a point and we can do the testing to ensure it doesn't break things and then move to the latest version.

**Comment by kurtzeborn** [comment]
I'm in favor of pinning versions as well.  It allows us to keep this work predictable.  We have to remember to look at what we're using and update them periodically, but that cost is much lower and more managable than the suprise breaks when latest moves unexpectedly.

Because we're producing SDKs, the urgency of being on latest I think is a bit lower because our customers will not instantly be on the latests OSs.  There will be an adoption curve which gives us time to move forward a month or two after new OSs become available.

**Comment by mikeharder** [comment]
Even if we want to keep using the specific-version labels, we need to periodically update them.  At a minimum, we need to update `macOS-10.13` before March 23 2020.  I will open a new issue to update just the macOS image.
