### ISSUE TITLE
Board Review: Querying

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk#979]
_(This is a placeholder that will be updated after discussing with the feature crew on Thursday...)_

# Querying
There are several services requiring rich query support in this upcoming wave including Azure Cognitive Search, Azure Tables, and other TBD options.  Cosmos has already shipped public previews.  

We're starting with Search today with the hope of codifying major decision decisions as Guidelines so please keep [Tables](https://docs.microsoft.com/en-us/rest/api/storageservices/querying-tables-and-entities) and [Cosmos](https://docs.microsoft.com/en-us/rest/api/cosmos-db/querying-cosmosdb-resources-using-the-rest-api) in mind as well.

## Azure Cognitive Search
We've already had an [introductory Arch Board discussion about Search](https://github.com/azure/azure-sdk/issues/625), but to refresh your memory the APIs can be split into two major categories:
* [Service Operations](https://docs.microsoft.com/en-us/rest/api/searchservice/#key-concepts) that create and manage search indexes, Cognitive Skillsets for AI Enrichment, indexers for crawling data sources like Blob Storage/Cosmos, etc.
* [Document Operations](https://docs.microsoft.com/en-us/rest/api/searchservice/document-operations) that add/update/delete documents in a search index and provide rich querying capabilities over those indexes.

This meeting will focus on rich querying capabilities as that's our goal for our first preview.  If we finish with time remaining, we may move on to the remaining Document Operations as those are a stretch goal for the first preview.

_(Please note that we're **NOT** planning to discuss strongly typed queries and will follow up with another Arch Board discussion on how to best support User Defined Schemas in our Track 2 client libraries.  In other words, we're focusing more on what goes into our query methods than what comes out for the moment.)_

### 1. Simple Searching
New developers should be able to get basic search results for a simple text query within 5 minutes of getting started.

#### Python
```python
from azure.search import SearchApiKeyCredential, SearchIndexClient

client = SearchIndexClient(
    search_service_name="my-search-service",
    index_name="hotels-sample-index",
    credential=SearchApiKeyCredential(api_key="xxxxxxxxx")
)

results = client.get_search_results(search="WiFi")

for doc in results:
    print(doc['Description'])
    print(doc['Type'])
    print(doc['BaseRate'])
```

### 2. Advanced Searching
Complicated filtering, sorting, faceting, etc., should be discoverable and easy to customize based on user input.

#### Python
```python
from azure.search import SearchApiKeyCredential, SearchIndexClient, SearchQuery
from azure.search.odata import AND, asc, desc, geo_distance

client = SearchIndexClient(
    search_service_name="my-search-service",
    index_name="hotels-sample-index",
    credential=SearchApiKeyCredential(api_key="xxxxxxxxx")
)

query = SearchQuery(
    search_text="WiFi",
    highlightPreTag="<em>",
    highlightPostTag="</em>"
)

# Base API accepts strings, templating/substitution TBD
query.filter("Address/City eq 'Portland and Address/Country eq 'US'"))
query.orderby("Rating desc", "geo.distance(FOO, geography'POINT(10 20)') asc")
query.select("HotelId", "HotelName", "Rating")


results = client.get_search_results(search=query)

for doc in results:
    print(doc['HotelName'])
    print(doc['Rating'])
```

### 3. Paged Searching
Searches returning huge numbers of results should provide an object model that makes implementing traditional search interfaces straightforward _(i.e., making it easy to communicate how the results have been faceted, etc.)_

```
Sample code coming soon...
```

### 4. Suggestions

Suggestions can power both traditional experiences like an autocomplete search field or [exploratory discovery of related documents in the index](https://www.youtube.com/watch?v=JFdF-Z7ypQo).

#### Python
```python
from azure.search import SearchApiKeyCredential, SearchIndexClient

client = SearchIndexClient(
    search_service_name="my-search-service",
    index_name="hotels-sample-index",
    credential=SearchApiKeyCredential(api_key="xxxxxxxxx")
)

results = client.get_suggestions(search_text="cof", suggester_name="sg")

for result in results:
    print(result['text'])
```

## References
- [Search Documentation](https://docs.microsoft.com/en-us/azure/search/search-what-is-azure-search)
- Java Track 2 Search [Meeting](https://github.com/azure/azure-sdk/issues/625), [Internal notes/recording](https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/OneNote.aspx?id=%2Fteams%2FAzureDeveloperExperience%2FShared%20Documents%2FGeneral%2FAzure%20SDK%20-%20General&wd=target%28Board%20Meetings.one%7C19375C24-42BA-455A-A479-8E59FBB01EF3%2FAzure%20Search%20for%20Java%20-%2010%5C%2F2%5C%2F2019%7C9879E0FC-3147-41B7-8DAB-23E9D636BFEA%2F%29), and [API Review](https://apiview.dev/Assemblies/Review/2abf935de65e4187964bea5b817872d6)
- Swagger for [Document Operations](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/search/data-plane/Microsoft.Azure.Search.Data/stable/2019-05-06/searchindex.json) and [Service Operations](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/search/data-plane/Microsoft.Azure.Search.Service/stable/2019-05-06/searchservice.json)
- [.NET Track 1 Source](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/search)

**Comment by bterlson** [comment]
You might be working on it still, but we will need at least a description and ideally any supporting documents/links/code/etc. in order to convene the board.

**Comment by AlexGhiondea** [comment]
@bterlson yes, we are going to add more information :).

**Comment by tg-msft** [comment]
I added an additional agenda and we'll follow up soon with additional detail.

**Comment by jongio** [comment]
We should determine if we want to integrate any of the Odata query libraries.  See examples here: https://www.odata.org/getting-started/understand-odata-in-6-steps/

We have query fluent style libs for .NET.

**Comment by kyle-patterson** [comment]
Recording is available here (MSFT INTERNAL): https://msit.microsoftstream.com/video/d4543885-a916-4cee-908b-58b758ff7817

MINBAR: For all languages, take a string that can use a helper to format (using string formatting/interpolation); consider a query provider in the future.

- Have a core API that takes strings, and experiment with ways to build the string
- If the mapping from functions to string (such as in python) is simple, allow that to be language specific
- Having some call to do escaping could help with debuggability
