### ISSUE TITLE
Clarify "rules of engagement" with arch board

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#982]
PR: https://github.com/Azure/azure-sdk/pull/983

**Comment by kyle-patterson** [comment]
Link to recording (MSFT INTERNAL): https://msit.microsoftstream.com/video/85df0951-2cd5-4fa9-8f1d-2e3cbc9026c6

- By default, aspire to preview every API change, but exceptions to go directly to GA may be made if sufficient business justification exists (for API changes). The Client library should be tested side-by-side with service features.

For API reviews:
- Meeting 1 could be brownbag-style on how the feature works, meeting 2 a full API discussion, ad hoc meeting TBD pending a call from architects based on API diff
-- For example, if few small changes come out of meeting 2, third meeting may not be required or done via github issues or email (use azure-sdk-pr for issues tracking internal previews/communications)
- Get in the habit of checking final API with system to detect breaking changes
- Meeting 2 should be restricted to "controversial" pieces, not line-by-line changes; minimum 1 week to bake with comments closing 1 day before the scheduled meeting

SLA on issues:
- Whenever an APIview is given, architects need a minimum of 5 working days to review/comment
- Discussion at a higher level is how to handle SLA on Sev1 Azure changes, for example
