### ISSUE TITLE
Board Review: Service Bus: Introductory session with champion scenarios

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk#992]
## The Basics

* Team responsible for the client library: **Azure SDK team**

* Link to documentation describing the service:
  - Top level docs
     - [What is Azure Service Bus](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview)
     - [Service Bus Queues, Topics & Subscriptions](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions)
     - [Compare the 3 Azure Messaging solutions](https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services?toc=%2fazure%2fservice-bus-messaging%2ftoc.json)
     - [Compare Storage Queue & Service Bus Queues](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-azure-and-service-bus-queues-compared-contrasted)
     - [Choose the right Messaging Service for your needs](https://azure.microsoft.com/en-us/blog/events-data-points-and-messages-choosing-the-right-azure-messaging-service-for-your-data/)
     - [Two different modes of receiving messages in Service Bus](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-transfers-locks-settlement#settling-receive-operations)
     - [Messages, Payload & Serialiazation](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messages-payloads)
  - Client Implementation details
     - [AMQP in Service Bus](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-overview)
     - [More AMQP in Service Bus](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-protocol-guide)
     - [Simulate request/response pattern in AMQP](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-protocol-guide#amqp-management)
     - [Spec for request/response features in ServiceBus](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response) that follows the previous point
     - [AMQP spec](http://www.amqp.org/sites/amqp.org/files/amqp.pdf)

* Contact email:
  - PM: Ashish Chhabria
  - Dev Lead: Shankar Reddy Sama

## Champion Scenarios

Service Bus is intended for traditional enterprise applications. These enterprise applications require transactions, ordering, duplicate detection, and instantaneous consistency. Service Bus enables [cloud-native](https://azure.microsoft.com/en-us/overview/cloudnative/) applications to provide reliable state transition management for business processes. When handling high-value messages that cannot be lost or duplicated, use Azure Service Bus. Service Bus also facilitates highly secure communication across hybrid cloud solutions and can connect existing on-premises systems to cloud solutions.

Service Bus is a brokered messaging system. It stores messages in a "broker" (for example, a queue) until the consuming party is ready to receive the messages.

It has the following characteristics:

- reliable asynchronous message delivery (enterprise messaging as a service) that requires polling
- advanced messaging features like FIFO, batching/sessions, transactions, dead-lettering, temporal control, routing and filtering, and duplicate detection
- at least once delivery
- optional in-order delivery

Some sample scenarios
- Order processing
- Financial transactions

**Comment by adrianhall** [comment]
Scheduled for the 18th

**Comment by richardpark-msft** [comment]
Scenario: 

Service bus used for resiliency ("no lost messages"), allowing for backpressure
and coordination with an external system.

1. An external system (Azure DevOps) generates events for a repo (ex: pull request created).
   The code that generates these messages is pre-canned and not under user control.
2. The events are sent to a single queue, which is configured to auto-forward to a topic.
3. That topic is subscribed to by multiple Azure Functions:
    * A telemetry function that forwards data to appinsights with no throttling.
    * A status function that updates a SQL Server database that users view (through a webpage)
      to see which builds are active and where.
    * A build function that launches jobs in a datacenter with more capable hardware.
      * This function cancels messages when it detects too much activity to prevent
        overwhelming the remote service which can

**Comment by richardpark-msft** [comment]
Scenario:

Service bus coordinates work between several components which are in various languages and platforms:
* Mobile (Android, IOS)
* Desktop (Linux, Windows)
* Web

Several key parts of this design:
* Disparate systems can make tracing and debugging difficult. Not only working with multiple programs but multiple groups.
* Network connectivity can be erratic - user needs some form of local buffering to handle "outboxing" a message which will get sent when the network comes back up.
* Some services send messages but infrequently - sometimes just once a day.

**Comment by ramya-rao-a** [comment]
Some more helpful links from Clemens
- [Messaging Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/category/messaging)
- More on [choosing messaging service from an architecture perspective](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/messaging)

**Comment by ramya-rao-a** [comment]
cc @KieranBrantnerMagee, @JoshLove-msft, @hemanttanwar, @richardpark-msft, @HarshaNalluru, @ShivangiReja, @yunhaoling, @srnagar

**Comment by kyle-patterson** [comment]
The recording is available here (MSFT INTERNAL): https://msit.microsoftstream.com/video/0222fec8-2c36-4db3-a710-74ed2811454f

.NET Samples are available here: https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus
