### ISSUE TITLE
Service Overviews Across All Languages Inconsistently Appear

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#998]
A lot of the time these service overviews actually aren't present. But there are a few hard cases where we _know_ they should appear.

We expect the service overview to render on [this page. ](https://docs.microsoft.com/en-us/python/api/overview/azure/keyvault?view=azure-python)

![image](https://user-images.githubusercontent.com/45376673/73996273-0aef9800-4910-11ea-89b3-b8d5f0b628e0.png)

This happens in various locations, and it doesn't appear that there is a specific erroneous configurations that are causing this. I have a suspicion that something wonky is happening during publishing. Perhaps the `docfx.json` is messing up the publish by not copying the service overviews to the correct location?

Once we understand this for one language, the rest should fall in quickly.

**Comment by danieljurek** [comment]
I think the ToC needs to be updated: https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-mapping/reference-previous.yml#L7
