### ISSUE TITLE
Board Review: Event Hubs (.NET client advanced scenarios)

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk#999]
## The Basics

* Developer platform team responsible for the client library:
  **Event Hubs Feature Team**

* Link to documentation describing the client library:    
  **[Azure.Messaging.EventHubs README](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs)**

* Contact email:  
  - **Ramya Achutha Rao (Feature team lead)**
  - **Jesse Squire (.NET client engineer)**
  - **Caio Saldanha (.NET client engineer)**  
  <br />
* Service team responsible for the client library:    
  **Azure Messaging Team**

* Link to documentation describing the service:    
  **[Product documentation](https://docs.microsoft.com/en-us/azure/event-hubs/)**

* Contact email (if service team, provide PM and Dev Lead):  
  - **Shubha Vijayasarathy (PM)**
  - **Javier Fernandez (PM)**
  - **SeongJoon Kwak (SJ) (Engineering manager)**
  - **Serkant Karaca (Lead product engineer)**

## About this client library

* Name of the client library:  
  **Event Hubs client library for .NET**

* Languages for this review:  
  **C#**

* Link to the service REST APIs:  
  **_N/A_**

### .NET

* Feature: **Partition Receiver Client**
    * [ApiView](https://apiview.dev/Assemblies/Review/9d81436944b94a2e9d3c5f6d448dacc1)
    * [Design proposal](https://gist.github.com/jsquire/4ea3368192cfee98dcbb4adfb29a9822)<br />  <br /> 

* Feature: **Event Processor Base**
    * [ApiView](https://apiview.dev/Assemblies/Review/c0a3774f6a9e4310b430282d1fa588b5)
    * [Design proposal](https://gist.github.com/jsquire/1f4a1e72fc02871f443ce365222d40f6)

### Java

Not applicable.  These features are specific to the .NET client.

### Python

Not applicable.  These features are specific to the .NET client.

### TypeScript

Not applicable.  These features are specific to the .NET client.

## Champion Scenarios (Partition Receiver)

Enable developers with advanced or specialized needs access to a client which provides minimal wrapping of the low-level transport, allowing them to receive batches of events on demand with deterministic control over network usage and the ability to tune the advanced aspects of the transport to best power their application scenario.  

### Read a batch of events from a partition

* Target audience: **advanced developers with special needs (~10%)**
* [Code sample](https://gist.github.com/jsquire/4ea3368192cfee98dcbb4adfb29a9822#consuming-events-from-a-partition)

## Champion Scenarios (Event Processor Base)

Enable developers to create a custom event processor by implementing a base class which requires minimal ceremony and allows for method-level overriding rather than making use of higher-level patterns such as event handlers.  The base class works natively with event batches and handles the low-level implementation details such as resiliency and performing collaborative load balancing with other processors working against the same Event Hub and consumer group.

### Implement a minimal processor using the default partition context

* Target audience: **advanced developers with special needs (~10%)**
* [Code sample](https://gist.github.com/jsquire/1f4a1e72fc02871f443ce365222d40f6#create-a-minimal-custom-processor)

### Implement a processor with a custom partition context

* Target audience: **advanced developers with special needs (~10%)**
* [Code sample](https://gist.github.com/jsquire/1f4a1e72fc02871f443ce365222d40f6#create-a-processor-with-custom-partition-context)

### Use a custom implementation for processing events

* Target audience: **advanced developers with special needs (~10%)**
* [Code sample](https://gist.github.com/jsquire/1f4a1e72fc02871f443ce365222d40f6#create-a-processor-and-perform-basic-event-processing)

**Comment by adrianhall** [comment]
* Should this lower-level library exist?
    * What's the purpose?  10-20% are advanced users in high-scale scenarios.  Left a gap v.v. track 1
    * It feels like the purpose is network control, not high performance. (CONFIRM / DENY)
    * Java uses back-pressure in reactor to handle this; Node & Python deals with this differently.
    * Should other languages have these low-level clients?  
    * What value are we providing over the AMQP library?  We provide the driving instructions (which is service specific).
    * **TO DO**: How to do this scenario for all languages?  (For JS & Python - needs additional work; Java???) 

* Should we follow the `Client` semantics, or remove the `Client` suffix?
    * Pro-removal: It's hiding the type for common usage
    * Anti-removal: It's a 1:1 relationship with the protocol, so feels like a client.
    * Question: How does the customer determine what client to use?
    * **Board Decision**:  60% of board suggests call it a client; however, if we hang it off the consumerclient, can just be a receiver.  It's a little early to talk about naming.

* EventProcessorClient
    * This is the equivalent of the pluggable checkpoint store in other languages.
    * .NET doesn't have plugins.
    * ParittionOwnership - properties should be get/set and remove params in constructor.
    * Take a look at ETag and how to make it generic w.r.t. checkpoint stores that don't support ETag. 
    * Suggest "version" and type string. 
    * **Board Decision**: API is approved.
